ldm/simplet2i.py, scripts/dream.py
could probably be improved, but I think this is pretty useful for mixing styles or putting more emphasis on certain things. 
example: `"a forest under blue sky: by Studio Ghibli:1.7 in the style of Starry Night:1"`
the above example turns into 3 sub-prompts:
"a forest under blue sky" 1.0 (default if no value)
"by Studio Ghibli" 1.7
"in the style of Starry Night" 1.0
The weights are added and normalized by default, but if `-x` is added, normalization is skipped which allows greater control
The resulting image will be: 27% a forest under blue sky, 45% by Studio Ghibli, 27% in the style of Starry Night
=> Prompt weighting for creative blending

ldm/models/diffusion/ksampler.py, ldm/simplet2i.py, scripts/dream.py
"a kitten  -s250 -C12.0 -S560119332"
k_heun:
k_euler (sorry, different seed - 2856290759):
k_dpm_2_ancestral:
=> FEAT:  Add ability use all k_* samplers

scripts/dream.py
=> FIX: Test for the presence of the specified img2img 

README.md
I hate doing this kind of thing sooo much, but my partner keeps telling me to be "more of a self-promoter" (job-wise)...
Also, a few people on the SD Discord wanted to use the other samplers, so simply in terms of making it more visible...
=> DOCS: update release features for v1.09 in README - add k_diffusion samplers note

README.md
Adding link to -v discussion... and giving myself some kudos damnit ;) (and fixing some links)
=> Update readme with variant disc

ldm/simplet2i.py
Wanted to make sure you were aware of this issue. By not calling model.cuda here, memory utilization is far worse.
=> fix VRAM utilization

static/dream_web/index.html
=> Replace numerical size inputs with dropdowns

static/dream_web/index.html
To match the CLI. Plus 64x64 is not a good default.
=> make web ui default to 512x512

ldm/dream/pngwriter.py
@lstein  Grid image not saving after recent changes has been fixed.
=> Fixed grid image not saving

ldm/dream/server.py, scripts/dream.py
Same as https://github.com/lstein/stable-diffusion/pull/151, but also covering the two other places files are read/written.
=> read/write plain text files in utf-8, not ascii

ldm/dream/pngwriter.py
In case of 6 images 3rd image was also copied to 4th box missing the last image in the grid.
=> Bug fix in grid

README.md
cf https://github.com/lstein/stable-diffusion/issues/196
=> fix path to dream server in readme

static/dream_web/index.html
Some minor tweaks to index.html for accessibility and browsers.
=> Minor updates to index.html

ldm/dream/server.py
This bug fix addresses Issue #191
=> BUGFIX: fix WebUI so that the selected sampler is actually applied

ldm/dream/server.py, ldm/models/diffusion/ddim.py, ldm/simplet2i.py, static/dream_web/index.js
Fixes #211.
btw @lstein what do you think about only requiring a single review when the contribution comes from a collaborator? Requiring two approvals is an unusually high bar.
=> support progress for img2img

CHANGELOG.md, README.md
- Added badges to the read me
- Moved older changelogs to Changelogs.md -- The read me was getting too big.
=> Add Badges to README.md and add CHANGELOG.md

configs/stable-diffusion/v1-finetune.yaml, main.py
Based on the changes made in [textual_inversion](https://github.com/rinongal/textual_inversion), I carried over the relevant changes that improved model training. These changes reduce the amount of memory used, significantly improve the speed at which training runs, and improve the quality of the results.
It also fixes the problem where the model trainer wouldn't automatically stop when it hit the set number of steps.
=> Training optimizations

.gitignore
Include log folders in git ignore.
=> Update .gitignore to include log folders

ldm/models/diffusion/ddim.py, scripts/orig_scripts/img2img.py, scripts/orig_scripts/txt2img.py
Fix precision_scope for cuda.
Move seed_everything after load_model_from_config (might break all seeds?).
Fix torch.randn for cuda.
=> txt2img changes: fixed some things for cuda, experimental seed change

README.md
=> Fix link to Mac instructions in README

ldm/simplet2i.py
Just a small warning to let the user know that their image is much bigger than default and that if they OOM, they need to make it smaller.
=> Add Warning When Image Is Too Large

README.md
Fixing typo in header and hyperlinking a file.
=> README.md - fixing "further reading" formatting

VARIATIONS.md, ldm/dream/pngwriter.py, scripts/dream.py
Per https://github.com/lstein/stable-diffusion/pull/277#issuecomment-1235881134.
=> replace list delimiters in variations syntax

static/dream_web/index.js
One of the previous updates got rid of the ability to submit a prompt by pressing Enter, so this adds that back and also adds the ability to cancel by pressing Escape. 
If you still want to add line breaks you can do so with Shift + Enter.
=> Add more keyboard support on the web server

static/dream_web/index.html
Add the "3x" upscale option on the Web UI.
=> Add 3x upscale option on the Web UI

README.md
Opening this for @softyoda in place of #471
=> fix(readme): add note about updating env via conda

ldm/modules/diffusionmodules/model.py
Please approve #518 first (the other way would probably conflict).
=> Remove pointless del statements in diffusionmodules.model.

ldm/modules/attention.py
This version should be on par with the fastest ever from 8 to 128 GB. It also allows to generate large images, as before.
Added optimisations for 16-32GB and cleaned up a bit of code.
It would be great to have a tester with CUDA to make sure everything still works.
=> Update attention.py for 16-32GB M1 performance

docs/installation/INSTALL_MAC.md
* slightly more consistent in how the different scenarios are described
* moved the stuff about `/usr/bin/python` to be adjacent to the stuff about `/usr/bin/python3`
* added an example of the 'option 1' goal state
* described a way to directly answer the question: how many snakes are living in your computer?
=> Minor cleanup and re-arranging of PATH docs

docs/features/IMG2IMG.md
Fixes https://github.com/lstein/stable-diffusion/issues/544
=> Clarify behavior of -v and -n parameters

ldm/modules/attention.py
Tested on 8GB eGPU nvidia setup so YMMV.
Re-land with .clone() fix, context #508
=> ~7% speedup by switch to += in ldm.modules.attention.

ldm/dream/server.py
Fix https://github.com/lstein/stable-diffusion/issues/565
=> Fix image location on webpage - windows

main.py
Allows testing textual inversion / training flow on cpu only (very slow though).
Context: #508
Also removes a duplicate statement.
=> Use cuda only when available in main.py.

docs/installation/INSTALL_MAC.md
=> refine env rebuild tip: add 'conda deactivate'

ldm/dream/args.py
Fixes #686 by handling if generation was a grid.
=> Fixes metadata implementation #686

ldm/dream/conditioning.py
Tokens are being displayed in an incremental way. This fix the issue. Also add the subprompt weight being used.
=> Fix token display when using -t

ldm/dream/log.py, scripts/dream.py
Substitute of pulling https://github.com/lstein/stable-diffusion/pull/605
=> New log option: add markdown as a log option

README.md, ldm/generate.py, scripts/dream.py
Two changes here:
- Adding a new command prompt flag -D
- Default strength when using -D is upped to 0.83
- Added prompt parsing from the image supplied in -I if there is no prompt
This outpainting extension makes it easy to extend an existing generated image to any direction top,right,bottom,left. E.g. let's take this image of Erwin that I generated:
`dream> "Portrait of Erwin Smith from Attack On Titan, tone mapped, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and Alphonse mucha" -s50 -W448 -H448 -C7.5 -Aplms -G0.6 -F -S224862249`
And we want to extend it to the top so we can see his face:
`dream> -I ./erwin.png -D bottom -n 10`
Now we get a couple of extension candidates such as: …
=> Outpainting extension

README.md
[Preview](https://github.com/tildebyte/InvokeAI/blob/fix-doc-readme-useful-forks-link/README.md)
=> fix(docs): point readme useful-forks link to new repo

README.md
Fixes previous name of repo in README
=> Fixes previous name of repo in README

ldm/generate.py
=> Fix CodeFormer not working if GFPGAN is enabled

frontend/src/app/features.ts, frontend/src/common/components/GuideIcon.tsx, frontend/src/common/components/GuidePopover.tsx, frontend/src/features/options/OptionsAccordion.tsx, frontend/src/features/system/SettingsModal.tsx, frontend/src/features/system/systemSlice.ts
@lstein @psychedelicious  - Addressed the merge conflicts after cherry picking changes into a fresh PR.
=> Addressed merge conflicts for adding UI tooltips

docs/help/SAMPLER_CONVERGENCE.md
Add documentation about the different samplers, and their convergence, performance and comparison for different topics.
Following on: https://github.com/invoke-ai/InvokeAI/issues/604#issuecomment-1249284791 and https://github.com/invoke-ai/InvokeAI/issues/604#issuecomment-1249523911
=> Create Sampler Tips (SAMPLER_CONVERGENCE.md)

backend/server.py
Set correct seed in metadata on image generation with more then one image.
=> Fix webui metadata issue #734

notebooks/Stable-Diffusion-local-Windows.ipynb
=> fix(install): update repo/org name in install Notebook

ldm/dream/app/api_app.py, scripts/invoke.py
I think the permanent fix for the sys.path bug is to make an `__init__.py` file, but not sure.
=> Adds CORS middleware and a fix for a bug with sys.path

docs/features/CLI.md, docs/help/TROUBLESHOOT.md, docs/other/CONTRIBUTORS.md
As requested in comments to #778
=> Update documents, add new options information to CLI.md 

backend/invoke_ai_web_server.py
Fixes mimetypes missing on systems that don't have them yet. @tildebyte Fixes your issue and probably many others.
=> WebUI - Fix mimetypes missing on Windows

backend/modules/create_cmd_parser.py, backend/server.py
=> Implement --free_gpu_mem for server/backend.py

docs/installation/INSTALL_MAC.md
To reflect the new file name from this pull request: https://github.com/invoke-ai/InvokeAI/commit/bc9f892cab91fbc5340836c95f5950166a9bc9bc
=> INSTALL_MAC.md - change environment-mac.yaml to yml

ldm/dream/args.py
=> Fix bug generating dream prompt when variations used

ldm/dream/app/api/routers/results.py, ldm/dream/app/api/routers/sessions.py
Adds operation_id to each route so that automatic API generation gets friendly method names.
=> Adds operation_id to routes

ldm/dream/generator/base.py
Fixes issue where when seed is zero, a random seed is used instead. Tested and it does indeed fix the issue.
Fixes #875
=> Fixes issue where when seed is zero, a random seed is used instead

docs/installation/INSTALL_MAC.md
With feedback from #896 regarding Intel Macs and data usage, I've updated the installation instructions for Macs to include Intel-specific commands and provide a bit more clarity for the overall process.
=> Updates INSTALL_MAC.md

backend/invoke_ai_web_server.py, frontend/README.md
Fixes img2img sampler metadata hardcoded to ddim
Needed now that img2img supports all samplers.
@blessedcoolant pls cherry-pick into your stuff
=> Web UI: Fixes img2img sampler metadata hardcoded to ddim

ldm/dream/args.py, ldm/dream/generator/embiggen.py
- embiggen needs to use ddim sampler due to low step count
- --hires_fix option needs to be written to log and command string
=> fix miscellaneous regressions

ldm/generate.py
Some code duplications creeped in.
=> remove duplicated code

requirements-mac-MPS-CPU.txt, requirements.txt
Add realesrgan to requirements.txt, remove nighties for torch and torchvision due to performance issues
=> add realesrgan to requirements.txt, remove nighties for torch and torchvision

ldm/util.py
@lstein I'm having the same issue #955 that @ioma was having before, but on CUDA. This fixes it for me (yet more .to(device) calls)
=> Fix for Perlin noise issue for cuda as well.

ldm/generate.py
Make results reproducible (so runs with the same seed produce the same result). Implements fix by @wbowling referenced in https://github.com/invoke-ai/InvokeAI/issues/397#issuecomment-1240679294
=> reintroduce fix for m1 from https://github.com/invoke-ai/InvokeAI/pull/579 missing after merge

.gitignore
Eventually making it slightly more flexible
=> Update gitignore to ignore codeformer weights at new location

ldm/generate.py
fix for https://github.com/invoke-ai/InvokeAI/issues/1163
=> fix for 'model is not defined' when loading embedding

scripts/preload_models.py
- [Fix typo](https://github.com/invoke-ai/InvokeAI/commit/307fde9cd4cea2ccbc642d74b82bef412c4ba4b3)
- [Fixes torch.load() for MPS/CPU](https://github.com/invoke-ai/InvokeAI/commit/bce904273060e7c3888d6bc5e2023f2fc3b7d58e)
- [Improves logic to determine if clipseg weights should be downloaded](https://github.com/invoke-ai/InvokeAI/commit/2a8f9f28176dac7316134d4e03282887d7f1cb43)
=> Fixes for `preload_models.py` related to clipseg

docs/installation/INSTALL_MAC.md
Fixes indentation causing rendering issue with github.io page
=> Fixes indentation causing rendering issue with github.io page

ldm/generate.py
Realized that the `fix_func` code block is duplicated twice in `generate.py`. I have checked the code and confirmed that both are identical. This PR will remove the duplicate code.
=> remove duplicate fix_func for MPS

.dockerignore, .github/workflows/build-container.yml, docker-build/Dockerfile, docker-build/build.sh, docker-build/entrypoint.sh, docker-build/env.sh, docker-build/run.sh, docs/installation/INSTALL_DOCKER.md, environment-linux-aarch64.yml
succesfully Tested the Container with aarch64 and x86_64.
=> New dockerfile - including a build- and a run- script as well as a GH-Action

ldm/invoke/prompt_parser.py, tests/test_prompt_parser.py
handle unicode chars beyond ASCII, closes #1240
=> handle all unicode characters

.gitignore
I thought this might be useful for people who like to test out others branches etc. and hate having to make sure their config doesn't end up with conflicts or being outright overwritten.
=> adds models.user.yml to .gitignore

.github/workflows/test-invoke-conda.yml
to find out if only mac or ubuntu is broken
(otherwise if one fails the otherone automatically cancels)
=> remove debug branch, set fail-fast to false

ldm/generate.py
I have not explicitly tested mode P
=> Prevent indexing error for mode RGB

ldm/invoke/conditioning.py, ldm/invoke/prompt_parser.py, ldm/models/diffusion/shared_invokeai_diffusion.py, scripts/invoke.py
This pull request 
1. hopefully fixes a bug that @Kyle0654 saw doing k_lms with `.swap()` syntax
2. improves error handling when parsing fails
3. brings back the coloured `log_tokenization`
=> Several small prompting fixes

.github/workflows/test-invoke-conda.yml, configs/models.yaml.example
- fix model dl path for sd-v1-4.ckpt
- copy configs/models.yaml.example to configs/models.yaml
=> Fix models.yaml.example and test-invoke-conda

ldm/invoke/txt2mask.py
Theoretically less work inverting the image while it's small but I can't measure a significant difference. Though, handy option to have in some cases.
=> Option to directly invert the grayscale heatmap

ldm/models/diffusion/cross_attention_control.py
This PR addresses excessive VRAM usage with `.swap` and also fixes a silly bug
=> Fix cross-attention control VRAM usage and index bug

ldm/invoke/txt2mask.py
Don't merge right now, just wanted to show the necessary changes
=> Optional refined model for Txt2Mask

ldm/modules/diffusionmodules/util.py
Reverts invoke-ai/InvokeAI#1357
=> Revert "Use array slicing to calc ddim timesteps"

frontend/README.md
* Fixes environment typo
* Adds missing `run` command
=> Fixes typos in README.md

README.md, docs/index.md
- changes pointers to installation instructions from README
- Adds the changelog for the 2.1.3 release
=> documentation hot fixes

docs/installation/INSTALL_MANUAL.md
adding troubleshooting tips for macos to the new docs
=> adding troubleshooting tips to the newer doc

.github/CODEOWNERS
This PR assigns responsibility for the .github/workflows directory to @mauwii.
=> make @mauwii codeowner for the CI workflows

notebooks/Stable-Diffusion-local-Windows.ipynb
I believe this is what you meant to link?
=> Fixing Dead Link

notebooks/Stable_Diffusion_AI_Notebook.ipynb
I noticed the requirements URL was not updated to reflect the new folder structure
=> Fixed Google Colab requirements URL

environments-and-requirements/environment-lin-aarch64.yml, environments-and-requirements/environment-lin-amd.yml, environments-and-requirements/environment-lin-cuda.yml, environments-and-requirements/environment-mac.yml, environments-and-requirements/environment-win-cuda.yml, environments-and-requirements/requirements-base.txt, installer/requirements.in, ldm/invoke/model_cache.py, ldm/util.py
Uses the [picklescan](https://github.com/mmaitre314/picklescan) library to scan the models that are being loaded to InvokeAI.
If the model is infected in anyway, the app shuts down immediately and the user is warned. If the model is unable to be scanned, then the user is presented with options to either continue or exit.
=> Add Model Scanning

ldm/invoke/args.py
=> fix(args): fix INITFILE spelling

docker-build/Dockerfile, docker-build/models.yaml
fix broken Dockerfile by using a custom models.yml which is using the checkpoint directly from the volume
=> fix Dockerfile

ldm/invoke/conditioning.py
The log was deleted at some point, this brings it back when user does `--log_tokenization`/`-t`
=> When doing -t/--log_tokenization, also log prompt parser output

ldm/invoke/args.py, ldm/invoke/restoration/outcrop.py
=> fix outcropping crash when png has no InvokeAI metadata

ldm/invoke/CLI.py, ldm/invoke/model_cache.py
remove duplicate import: os
ldm.util.ask_user is imported only once now
introduce textwrap and contextlib packages to clean up the code
return, returns None implicitly so it is omitted
a function returns None by default so it is omitted
dict.get returns None by default if the key doesn't exist so it is omitted
type of True is a bool and if the module only returns True then it should not return anything in the first place
and added some indentations and line breaks to further improve readability
=> cleanup ldm/invoke/model_cache.py

installer/install.bat, installer/install.sh, setup.py
- install scripts:
- allow EN-abling pip cache (use 'use-cache' as an arg to the install script: no flag, no dashes)
- debug message showing which sourceball we're downloading
- add 'wheel' to pip update, so we can speed up installs from source (and get rid of deprecation warnings)
- install.sh: use absolute path for micromamba
- setup.py:
- fill 'install_requires' using 'requirements.in'
- fix 'load_models' script name
=> fix(install): more fixes

environments-and-requirements/requirements-mac-mps-cpu.txt
limit it to last good version until fixed.
=> grpcio 1.51.0 is broken on M1 Macs. 

ldm/invoke/model_cache.py
Reverts invoke-ai/InvokeAI#1539
=> Revert "make the docstring more readable and improve the list_models logic"

.github/workflows/test-invoke-conda.yml, .github/workflows/test-invoke-pip.yml
path of the cache was wrong, which is why the PRs are failing since they do not have the model available in cache, neither can they download it since they have no access to the secret 🤦🏻‍♂️
=> fix model cache path

.github/workflows/test-invoke-conda.yml, .github/workflows/test-invoke-pip.yml
for debugging purpose we need to see the content of the invokeai config file which is created.
=> include a step after config to `cat ~/.invokeai`

environment.yaml
Was unintentionally added in #1621
Thanks for catching this @JPPhoto
=> Removes symlinked environment.yaml

docs/CHANGELOG.md, docs/features/OUTPAINTING.md, docs/features/POSTPROCESS.md, docs/index.md, docs/installation/INSTALLING_MODELS.md, docs/installation/INSTALL_JUPYTER.md, docs/installation/INSTALL_MANUAL.md, docs/installation/INSTALL_SOURCE.md, docs/installation/index.md, docs/installation/older_docs_to_be_removed/INSTALL_LINUX.md, docs/installation/older_docs_to_be_removed/INSTALL_MAC.md, docs/installation/older_docs_to_be_removed/INSTALL_WINDOWS.md
These are documentation fixes for the 2.2 release
=> Documentation updates for 2.2 release

scripts/configure_invokeai.py
- Adds a new option to download <a>ll the models, in addition to <r>ecommended and <c>ustomized.
=> configure_invokeai.py enhancement

docs/installation/INSTALLING_MODELS.md
Adds a tip for dragging models onto the command prompt window to auto-insert the path. 
Thanks to Wlnter on discord for this tip: https://discord.com/channels/1020123559063990373/1048020104648077395/1048020104648077395
=> Adds tip for importing models on Windows

ldm/invoke/args.py
Not sure what the procedure is for the version number. Is this supposed to match every git tag or just major versions? Same question for setup.py
=> Eventually update APP_VERSION to 2.2.3

.github/workflows/build-cloud-img.yml
untill we have a solution for the token!
=> disable pushing the cloud container

ldm/invoke/CLI.py, ldm/invoke/generator/embiggen.py
Addresses #1647 and fixes embiggen
=> Fix embiggen

frontend/src/features/options/components/PromptInput/PromptInput.tsx
=> Syntax hints in the prompt field placeholder

tests/pr_prompt.txt, tests/validate_pr_prompt.txt
- run 3 tests for PR with different samplers
- reduce tests for PR to do only 5 Iterations
this should imho be merged asap
=> Run more tests for PRs

frontend/src/styles/Mixins/_Responsive.scss, frontend/src/styles/Mixins/index.scss
This doesn't not work for the Canvas Painting yet, but works on img2img and text2img
=> Responsive for devices under 600px

docs/installation/INSTALL_AUTOMATED.md, installer/install.bat.in, installer/install.sh.in
This corrects a few formatting errors in the installer instructions file.
=> fix mkdocs formatting

ldm/invoke/pngwriter.py
This fix was authored by @mebelz PR #1775  and is reissued here to base it on `main`.
=> correct bug when trying to enhance JPG images

installer/install.bat.in, installer/install.sh.in
This is final step before release 2.2.4.
=> update installers for v2.2.4 tag

ldm/invoke/concepts_lib.py
=> Fix crash when upscaling with CLI

ldm/invoke/globals.py
Not sure if this was the intended logic you were going for. If it is, then it should fix a crash introduced in #1948 .. Please give it a test. @lstein
=> Possible fix for crash introduced in #1948

environments-and-requirements/environment-lin-aarch64.yml, environments-and-requirements/environment-lin-amd.yml, environments-and-requirements/environment-lin-cuda.yml, environments-and-requirements/environment-mac.yml, environments-and-requirements/environment-win-cuda.yml, environments-and-requirements/requirements-base.txt
- Update pypatchmatch to 0.1.5 (see request from @Kyle0654 here https://discord.com/channels/1020123559063990373/1034740515209486387/1052465462757310464 )
- Removed basicsrs workaround for environment files, now that we know problem was caused by Windows long path issue.
=> update requirements and environment files for patchmatch 0.1.5

.github/workflows/pyflakes.yml
[pyflakes](https://pypi.org/project/pyflakes/) is probably the easiest Python linter to get started with:
- it's focused on Python content, not style.
- it runs quickly with low resource requirements. This is due to the fact that it does some light static analysis without actually executing any of the code under review. That limits its scope, but also means you don't have to set up on a machine with the right hardware and install all the heaps of binary dependencies.
I haven't used this specific `reviewdog` action before, but it seems like it's how presenting pyflakes results in a PR request should work?
not sure how to PR request changes to GitHub workflows either. I see the check hasn't run on this commit itself, presumably because randos can't submit PR requests to run random GitHub …
=> build: GitHub Action to lint python files with pyflakes

.github/workflows/lint-frontend.yml, frontend/.eslintrc.cjs, frontend/src/app/socketio/emitters.ts, frontend/src/app/socketio/listeners.ts, frontend/src/common/components/IAISlider.tsx, frontend/src/common/components/radix-ui/IAISlider.tsx, frontend/src/common/components/radix-ui/IAITooltip.tsx, frontend/src/common/hooks/useClickOutsideWatcher.ts, frontend/src/common/util/parameterTranslation.ts, frontend/src/features/lightbox/components/ReactPanZoom.tsx, frontend/src/features/tabs/components/UnifiedCanvas/UnifiedCanvasBeta/UnifiedCanvasDisplayBeta.tsx, frontend/src/features/tabs/components/UnifiedCanvas/UnifiedCanvasBeta/UnifiedCanvasToolbar/UnifiedCanvasToolSelect.tsx, frontend/src/global.d.ts
Based on #1995 for the Github action workflow file. Will mark as ready once that is merged.
=> Reduce frontend eslint warnings to 0

frontend/src/features/system/components/ThemeChanger.tsx
=> Fix intitial theme setting

README.md
The link still points to 2.2.3 .
=> Replace latest link

ldm/invoke/CLI.py
Passing --config was not being recognized.
=> Fix --config arg not being recognized

.github/workflows/test-invoke-conda.yml, .github/workflows/test-invoke-pip.yml, scripts/configure_invokeai.py
Add PR-types to test workflows:
- 'ready_for_review'
- 'opened'
- 'synchronize'
- 'converted_to_draft'
add a job to fail for draft-PRs to test workflows
=> set workflow PR triggers to filter PR-types

docs/installation/010_INSTALL_AUTOMATED.md
Follow up on a few issues (see commit messages)
=> Install documentation updates

InvokeAI_Statement_of_Values.md, docs/other/CONTRIBUTORS.md
Just adding little ol' me to the documentation pages.
=> Add @ebr to Contributors

docker-build/env.sh
=> [docker] use `uname -m` instead of `arch`

ldm/invoke/CLI.py, ldm/invoke/__init__.py
quick post-release patch to fix the embedded version number.
=> update version number

README.md
=> fix spelling mistake in readme

configs/INITIAL_MODELS.yaml
- Default to SD 1.5
- Add waifu diffusion 1.4
=> adjust initial model defaults

environments-and-requirements/requirements-lin-amd.txt, environments-and-requirements/requirements-lin-cuda.txt, environments-and-requirements/requirements-win-colab-cuda.txt
This PR pushes the requirements to torch >=1.13 + CUDA 11.7
AMD support has been updated to ROCm5.2
=> upgrade requirements to CUDA 11.7, torch 1.13

scripts/configure_invokeai.py
Fixes https://github.com/invoke-ai/InvokeAI/issues/2083
=> Save HFToken only if it is present

scripts/textual_inversion_fe.py
- Add num_train_epochs
- Reorganize widgets so all sliders that control # of steps are together
=> [enhancement] Reorganize form for textual inversion training

ldm/invoke/ckpt_to_diffuser.py
Previously the conversion ("optimization") process re-downloaded CLIP, safety checker and other ancillary files, even if they were already available in the models directory. This is now fixed.
=> [bugfix] ckpt conversion script respects cache in ~/invokeai/models

frontend/src/features/gallery/components/CurrentImageButtons.tsx
=> Fix download button styling

environments-and-requirements/requirements-lin-cuda.txt, environments-and-requirements/requirements-win-colab-cuda.txt
Fixes simple typo in requirements added in #2465
=> Fix typo in xformers version, 0.16 -> 0.0.16

installer/readme.txt
Just a quick update about Python 3.11.
=> Add python version warning from the docs

environments-and-requirements/requirements-base.txt, ldm/invoke/app/api/routers/sessions.py, ldm/invoke/app/api_app.py
- Pin api-related requirements
It breaks if you have later versions.
- Remove confusing extra CORS origins list
Took me an hour to find the second `origins` >.<
- Adds response models for HTTP 200
`openapi.json` includes the schemas for session responses now. Makes it much easier to consume the API. I'm not sure how to do this appropriately for images.
=> [nodes] A few minor changes

ldm/invoke/training/textual_inversion.py
- This fixes an edge case crash when the textual inversion frontend tried to display the list of models and no default model defined in models.yaml
=> This fixes a crash in the TI frontend

ldm/invoke/CLI.py, ldm/invoke/args.py, ldm/invoke/model_manager.py, ldm/util.py, pyproject.toml
This change allows passing a directory with multiple models in it to be imported.
Ensures that diffusers directories will still work.
Fixed up some minor type issues.
=> Allow multiple models to be imported by passing a directory. 

.github/workflows/build-container.yml
=> hotfix `build-container.yml`

ldm/invoke/app/services/graph_execution_state.py
- Makes a number of optional things `Optional[]`
- See line 491 for a class property that doesn't seem to exist?
- I couldn't figure out the rest of the typing warnings. The tests pass so I assume I haven't broken anything :)
=> [nodes] minor typing fixes

ldm/generate.py, ldm/invoke/generator/base.py, ldm/invoke/generator/txt2img2img.py
Cleaned up code and refactored to enable accurate statistical reporting for CUDA by collecting stats before clearing the cache.
=> Refactor CUDA cache clearing to add statistical reporting.

.github/workflows/build-container.yml, .github/workflows/test-invoke-pip-skip.yml, .github/workflows/test-invoke-pip.yml
remove leading Slash from paths
=> Fix workflow path filters

invokeai/frontend/public/locales/en.json
=> Fixed grammar in "other options" feature tooltip

invokeai/frontend/public/locales/en.json, invokeai/frontend/public/locales/it.json
My last attempt to fix the Weblate missing keys was done incorrectly and caused a merge conflict on the Weblate repo.
This PR follows these steps to fix it https://docs.weblate.org/en/latest/faq.html#how-to-fix-merge-conflicts-in-translations
:crossed_fingers:
=> [ui] fix weblate merge conflict

.github/CODEOWNERS
- In an emergency, one or the other of these individuals will be available to review any part of the code.
=> add @lstein and @blessedcoolant to all codeowner paths

invokeai/backend/invoke_ai_web_server.py
Documentation strings are the first thing inside the function body. https://docs.python.org/3/tutorial/controlflow.html#defining-functions
=> doc(invoke_ai_web_server): put docstrings inside their functions

ldm/invoke/app/cli_app.py, ldm/invoke/app/services/events.py, ldm/invoke/app/services/graph.py, ldm/invoke/app/services/processor.py, tests/nodes/test_invoker.py, tests/nodes/test_nodes.py
Adds better error information to graph execution, prints better errors in the CLI, and sends errors as events.
=> [nodes] Add better error handling to processor and CLI

ldm/invoke/conditioning.py
=> fix newlines causing negative prompt to be parsed incorrectly

invokeai/frontend/web/package.json, invokeai/frontend/web/yarn.lock
Added missing dependency declaration `@chakra-ui/styled-system`
=> add missing package

invokeai/frontend/web/src/component.tsx, invokeai/frontend/web/src/main.tsx
Decouple default component from react root
=> decouple default component from react root

invokeai/app/cli_app.py
Executes piped commands in the order they were provided (instead of executing CLI commands immediately).
=> [cli] Execute commands in-order with nodes

ldm/invoke/CLI.py, ldm/invoke/config/model_install_backend.py, ldm/invoke/model_manager.py
This commit enhances support for V2 variant (epsilon and v-predict) import and conversion to diffusers, by prompting the user to select the proper config file during startup time autoimport as well as in the invokeai installer script. Previously the user was only prompted when doing an `!import` from the command line or when using the WebUI Model Manager.
=> improve support for V2 variant legacy checkpoints

invokeai/backend/model_management/model_manager.py
=> [fix] Get the model again if current model is empty

invokeai/app/api_app.py
Correctly reference output types in node schemas
=> [nodes-api] Fix API generation to correctly reference outputs

invokeai/app/api/routers/sessions.py, invokeai/app/cli_app.py, invokeai/app/services/graph.py, static/dream_web/test.html, tests/nodes/test_node_graph.py, tests/nodes/test_nodes.py
Adds an `Edge` data type, replacing the current tuple used for edges.
=> [nodes] Add Edge data type

invokeai/frontend/web/src/features/lightbox/components/ReactPanZoomButtons.tsx
=> fix(ui): fix viewer tooltip localisation strings

installer/lib/installer.py
Right link on pytorch installer for linux rocm
=> Right link on pytorch installer for linux rocm

invokeai/app/api/routers/images.py, invokeai/app/services/image_storage.py, invokeai/app/util/save_thumbnail.py
Save and serve thumbnail images
=> feat(nodes): save thumbnails

.github/workflows/build-container.yml
Add permission go write packages to GITHUB_TOKEN
=> fix build-container.yml

invokeai/app/api/routers/models.py, invokeai/app/api_app.py
Goal: Get Model API into main, then extend with new API endpoints
=> Model API Merge Into Main

invokeai/frontend/CLI/CLI.py
!fetch puts its output file into the output directory; it may be beneficial to have !replay look in the output directory as well.
=> Change where !replay looks for its infile

invokeai/app/invocations/generate.py, invokeai/app/invocations/latent.py
the name of this was changed at some point. nodes still used the old name, so scheduler selection did nothing. simple fix.
=> fix(nodes): `sampler_name` --> `scheduler`

invokeai/backend/stable_diffusion/concepts_lib.py
#3218 
Huggingface API will not be queried if --no-internet flag is set
=> [bug] #3218 HuggingFace API off when --no-internet set

.gitignore
Mistakenly closed the previous pr.
=> chore: add ".version" and ".last_model" to gitignore

invokeai/frontend/web/package.json, invokeai/frontend/web/src/app/constants.ts, invokeai/frontend/web/src/features/nodes/components/FieldHandle.tsx, invokeai/frontend/web/src/features/nodes/components/FieldTypeLegend.tsx, invokeai/frontend/web/src/features/nodes/components/Flow.tsx, invokeai/frontend/web/src/features/nodes/components/IAINode/IAINodeInputs.tsx, invokeai/frontend/web/src/features/nodes/components/IAINode/IAINodeResizer.tsx, invokeai/frontend/web/src/features/nodes/components/InvocationComponent.tsx, invokeai/frontend/web/src/features/nodes/components/panels/MinimapPanel.tsx, invokeai/frontend/web/src/features/nodes/components/search/NodeSearch.tsx, invokeai/frontend/web/yarn.lock
- Style the Minimap
- Made the Node UI Legend Responsive
- Set Min Width for nodes on Spawn so resize doesn't snap.
- Initial Implementation of Node Search
- Added FuseJS to handle the node filtering
=> [Nodes UI] More Work

invokeai/app/api/models/images.py, invokeai/app/api/routers/images.py, invokeai/app/api/routers/sessions.py, invokeai/app/services/image_storage.py
- add `delete_image` and `delete_images` endpoints
- tidy sessions and images routers
=> [nodes] add delete image & delete images endpoint

ldm/invoke/_version.py
Bump version number for 2.3.5 release candidate.
=> bump version number to 2.3.5-rc1

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/app/store/store.ts, invokeai/frontend/web/src/common/components/Loading/Loading.tsx, invokeai/frontend/web/src/common/util/getUrl.ts, invokeai/frontend/web/src/features/gallery/components/CurrentImageButtons.tsx, invokeai/frontend/web/src/features/gallery/components/CurrentImagePreview.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGalleryPanel.tsx, invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts, invokeai/frontend/web/src/features/parameters/components/ProcessButtons/CancelButton.tsx, invokeai/frontend/web/src/features/parameters/hooks/usePrompt.ts, invokeai/frontend/web/src/features/system/components/Console.tsx, invokeai/frontend/web/src/features/system/components/ProgressBar.tsx, invokeai/frontend/web/src/features/system/components/SiteHeader.tsx, invokeai/frontend/web/src/features/system/store/systemPersistsDenylist.ts, invokeai/frontend/web/src/features/system/store/systemSlice.ts, invokeai/frontend/web/src/features/ui/components/FloatingGalleryButton.tsx, invokeai/frontend/web/src/features/ui/components/FloatingParametersPanelButtons.tsx, invokeai/frontend/web/src/features/ui/components/InvokeTabs.tsx, invokeai/frontend/web/src/services/events/middleware.ts, invokeai/frontend/web/src/services/events/types.ts, invokeai/frontend/web/src/services/events/util/setEventListeners.ts, invokeai/frontend/web/src/services/thunks/schema.ts
persist socket sessions across reloads so you can refresh the page during generation and resume.
=> ui: session persistence

invokeai/app/invocations/generate.py, invokeai/frontend/web/src/features/parameters/components/MainParameters/HeightSlider.tsx, invokeai/frontend/web/src/features/parameters/components/MainParameters/WidthSlider.tsx
=> ui, nodes: fix img2img fit param

invokeai/frontend/web/package.json, invokeai/frontend/web/yarn.lock
- Resolves an issue with gallery not rendering all items
=> chore(ui): bump react-virtuoso

invokeai/frontend/web/src/features/nodes/components/InputFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/fields/ItemInputFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/types/constants.ts, invokeai/frontend/web/src/features/nodes/types/types.ts, invokeai/frontend/web/src/features/nodes/util/fieldTemplateBuilders.ts, invokeai/frontend/web/src/features/nodes/util/linearGraphBuilder/buildIterateNode.ts, invokeai/frontend/web/src/features/nodes/util/parseSchema.ts, invokeai/frontend/web/src/features/system/store/systemSlice.ts
also set default log level to `debug`
=> ui: support collect nodes

invokeai/frontend/web/src/features/system/store/systemSlice.ts, invokeai/frontend/web/src/services/thunks/session.ts
Surface HTTPException detail field to `sessionInvoked` redux layer for 403 errors
=> surface error detail field to redux layer for 403 errors

invokeai/app/services/image_storage.py
Check if the cache has the object before deleting it.
=> fix(nodes): fix #3306

invokeai/app/api_app.py
- UI available at `http://localhost:9090`
=> feat(nodes): add ui build static route

invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/features/gallery/components/CurrentImageButtons.tsx, invokeai/frontend/web/src/features/gallery/components/HoverableImage.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Hires/ParamHiresCollapse.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Noise/ParamNoiseCollapse.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Seamless/ParamSeamlessCollapse.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Symmetry/ParamSymmetryCollapse.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Variations/ParamVariationCollapse.tsx, invokeai/frontend/web/src/features/system/hooks/useFeatureStatus.ts, invokeai/frontend/web/src/features/system/store/configSlice.ts
now may disable individual SD features eg Noise, Variation, etc - stuff which is not ready for consumption in commercial.
=> feat(ui): expand config options

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/features/system/components/InvokeAILogoComponent.tsx
=> ui: commercial fixes

invokeai/frontend/web/src/features/system/components/InvokeAILogoComponent.tsx
Fix for a failing package build
=> fix(ui): fix syntax error in the logo component flexbox

.github/workflows/test-invoke-pip.yml
- Restore conditional which ensures tests are only run on `main`
- Fix `yaml` syntax error
=> build: fix test-invoke-pip.yml

.github/workflows/test-invoke-pip.yml
i think this conditional needs to be removed.
=> fix: attempt to fix actions

invokeai/frontend/web/src/features/gallery/components/CurrentImageButtons.tsx, invokeai/frontend/web/src/features/gallery/components/HoverableImage.tsx, invokeai/frontend/web/src/features/gallery/components/ImageMetaDataViewer/ImageMetadataViewer.tsx, invokeai/frontend/web/src/features/gallery/components/NextPrevImageButtons.tsx, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildTextToImageGraph.ts, invokeai/frontend/web/src/features/parameters/hooks/useParameters.ts, invokeai/frontend/web/src/features/parameters/hooks/usePrompt.ts, invokeai/frontend/web/src/features/parameters/store/setAllParametersReducer.ts
Various UI fixes to handle new metadata object
=> Use parameter fixes

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/index.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasMerged.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasSavedToGallery.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageDeleted.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageMetadataReceived.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageUploaded.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageUrlsReceived.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/receivedResultImagesPage.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/receivedUploadImagesPage.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/sessionCanceled.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/sessionCreated.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/sessionInvoked.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/sessionReadyToInvoke.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/graphExecutionStateComplete.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/invocationComplete.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/invocationError.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/invocationStarted.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/userInvokedCanvas.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/userInvokedImageToImage.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/userInvokedNodes.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/userInvokedTextToImage.ts, invokeai/frontend/web/src/common/components/ImageUploader.tsx, invokeai/frontend/web/src/features/gallery/store/resultsSlice.ts, invokeai/frontend/web/src/features/gallery/store/uploadsSlice.ts, invokeai/frontend/web/src/features/system/store/systemSlice.ts, invokeai/frontend/web/src/services/events/middleware.ts, invokeai/frontend/web/src/services/thunks/gallery.ts, invokeai/frontend/web/src/services/thunks/image.ts, invokeai/frontend/web/src/services/thunks/session.ts
- Make the thunks themselves as lean as possible, with data processing and logging in reducers or middleware
- Add handling for all network events (uhh possible I missed some, but the big ones are all now handled)
- Demote most log messages to `debug`
- Fix a couple small bugs
=> ui: error and event handling

ldm/modules/kohya_lora_manager.py
Currently hooks registers multiple time for some modules.
As result - lora applies multiple time to this modules on generation and images looks weird.
If have any other minds how to fix it better - feel free to push.
=> [Fix] Lora double hook

invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildTextToImageGraph.ts
I missed a spot when working on the graph logic yesterday.
=> fix(ui): fix width and height not working on txt2img tab

scripts/invoke.py, scripts/invokeai-cli.py, scripts/invokeai-web.py
- launch web ui with `scripts/invokeai-web.py`
- launch cli with `scripts/invokeai-cli.py`
=> feat(nodes): add separate scripts to launch cli and web

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasToolbar.tsx, invokeai/frontend/web/src/features/nodes/components/FieldTypeLegend.tsx, invokeai/frontend/web/src/features/nodes/components/NodeEditor.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamNegativeConditioning.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamPositiveConditioning.tsx, invokeai/frontend/web/src/features/system/components/InvokeAILogoComponent.tsx, invokeai/frontend/web/src/features/system/components/SiteHeader.tsx, invokeai/frontend/web/src/features/ui/components/InvokeTabs.tsx, invokeai/frontend/web/src/features/ui/components/PinParametersPanelButton.tsx
- canvas (non-beta) toolbar now wraps
- responsive changes were causing a lot of weird layout issues, had to remove the rest of them
- reduces minH for prompt boxes a bit
=> feat(ui): improve UI on smaller screens

invokeai/frontend/web/src/features/nodes/components/NodeGraphOverlay.tsx
sure this isn't really important at the moment
just limited the size of the width and gave it a shadow
=> Graph overlay was expanding off the screen to the size of the prompt line

invokeai/frontend/web/src/features/controlNet/store/controlNetSlice.ts
I had accidentally defaulted it to false
=> fix(ui): default controlnet autoprocess to true

invokeai/app/api/dependencies.py, invokeai/app/cli_app.py, invokeai/backend/model_management/model_manager.py
This PR creates the databases directory at app startup time. It also removes a couple of debugging statements that were inadvertently left in the model manager.
=> create databases directory on startup

invokeai/app/api/routers/models.py, invokeai/backend/model_management/model_manager.py, invokeai/backend/model_management/models/lora.py, invokeai/backend/model_management/models/stable_diffusion.py
Fix lora import
Fix sd2 config - `variant` field not added
Fix list models api - `base_model` arg not provided, redundant assert check
=> Model manager fixes

invokeai/app/cli_app.py
This PR corrects a crash during startup of `invokeai-node-cli` due to failure to initialize the image board service.
=> Add image board support to invokeai-node-cli

invokeai/app/services/config.py, invokeai/app/services/model_manager_service.py
The new configuration option for `max_cache_size`  was not exposed in config. This PR fixes that.
=> Expose max_cache_size in config

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageDeleted.ts, invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts
=> fix(ui): deleting image selects first image

invokeai/frontend/web/src/features/controlNet/components/ControlNetImagePreview.tsx, invokeai/frontend/web/src/features/nodes/components/fields/ImageInputFieldComponent.tsx
I had broken this earlier today
=> fix(ui): fix dnd on nodes

invokeai/backend/install/migrate_to_3.py
Update path for clip model according to path used in ckpt conversion and invokeai-configure
=> Fix clip path in migrate script

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketConnected.ts, invokeai/frontend/web/src/common/hooks/useIsReadyToInvoke.ts, invokeai/frontend/web/src/features/gallery/components/ImageGalleryContent.tsx
* load images once gallery mounts instead of waiting for socket to connect
* don't enable invoke button until main models are loaded
=> Improved loading for UI

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/index.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/modelSelected.ts, invokeai/frontend/web/src/common/components/IAIMantineMultiSelect.tsx, invokeai/frontend/web/src/common/components/IAIMantineSelect.tsx, invokeai/frontend/web/src/common/components/IAIMantineSelectItemWithTooltip.tsx, invokeai/frontend/web/src/features/embedding/components/ParamEmbeddingPopover.tsx, invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx, invokeai/frontend/web/src/features/lora/store/loraSlice.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/addVAEToGraph.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildCanvasImageToImageGraph.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildCanvasInpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildCanvasTextToImageGraph.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearImageToImageGraph.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearTextToImageGraph.ts, invokeai/frontend/web/src/features/parameters/components/Parameters/Advanced/ParamClipSkip.tsx, invokeai/frontend/web/src/features/parameters/hooks/useRecallParameters.ts, invokeai/frontend/web/src/features/parameters/store/actions.ts, invokeai/frontend/web/src/features/parameters/store/generationSlice.ts, invokeai/frontend/web/src/features/parameters/store/parameterZodSchemas.ts, invokeai/frontend/web/src/features/system/components/ModelSelect.tsx, invokeai/frontend/web/src/features/system/components/VAESelect.tsx
Ensure that all submodels are compatible with selected base_model
Note: since adding a textual inversion embedding updates the prompt itself, I'm not sure its worth trying to unparse that from the string
=> UI model compatibiltiy

invokeai/frontend/web/src/features/embedding/components/AddEmbeddingButton.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamPositiveConditioning.tsx, invokeai/frontend/web/src/features/ui/components/PinParametersPanelButton.tsx
=> feat(ui): improve embed button styles

invokeai/app/api_app.py, invokeai/app/cli_app.py, invokeai/app/invocations/noise.py, invokeai/backend/generator/base.py, invokeai/backend/generator/img2img.py, invokeai/backend/stable_diffusion/diffusers_pipeline.py, invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py, invokeai/backend/util/devices.py, invokeai/backend/util/mps_fixes.py
This PR is to allow FP16 precision to work on Macs with MPS. In addition, it centralizes the torch fixes/workarounds required for MPS into a new backend utility `mps_fixes.py`. This is conditionally imported in `api_app.py`/`cli_app.py`.
Many MANY thanks to @StAlKeR7779 for patiently working to debug and fix these issues.
=> Mac MPS FP16 fixes

invokeai/frontend/web/src/services/api/thunks/image.ts
Reverts invoke-ai/InvokeAI#3679
=> Revert "get uploads working again"

invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildCanvasImageToImageGraph.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildCanvasTextToImageGraph.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearImageToImageGraph.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearTextToImageGraph.ts, invokeai/frontend/web/src/features/parameters/components/Parameters/Noise/ParamCpuNoise.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Noise/ParamNoiseCollapse.tsx, invokeai/frontend/web/src/features/parameters/store/generationSlice.ts
=> ui: add cpu noise

invokeai/frontend/web/src/common/components/IAIMantineMultiSelect.tsx, invokeai/frontend/web/src/common/components/IAIMantineSelect.tsx, invokeai/frontend/web/src/features/embedding/components/ParamEmbeddingPopover.tsx, invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx, invokeai/frontend/web/src/features/nodes/components/AddNodeMenu.tsx
Mantine's multiselect does not let you edit the search box with mouse, paste into it, etc. Normal select is fine.
I can't remember why I made Lora etc multiselects, but everything seems to work with normal selects, so I've change to that.
=> fix(ui): fix selection on dropdowns

invokeai/frontend/web/src/features/nodes/components/AddNodeMenu.tsx, invokeai/frontend/web/src/features/nodes/components/Flow.tsx, invokeai/frontend/web/src/features/nodes/components/IAINode/IAINodeHeader.tsx, invokeai/frontend/web/src/features/nodes/components/InvocationComponent.tsx, invokeai/frontend/web/src/features/nodes/components/NodeWrapper.tsx, invokeai/frontend/web/src/features/nodes/components/ProgressImageNode.tsx, invokeai/frontend/web/src/features/nodes/hooks/useBuildInvocation.ts, invokeai/frontend/web/src/features/nodes/store/util/makeTemplateSelector.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildNodesGraph.ts
it is excluded from graph, so you can add it without affecting generation
=> feat(ui): add progress image node

invokeai/frontend/web/src/features/nodes/components/panels/TopCenterPanel.tsx
Just a small thing now, as nodes are all still wip, but since @psychedelicious was nice enough to add the progress image node for me, what I noticed was missing now is the cancel button on nodes tab
=> Add Cancel Button button to nodes tab

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/Flow.tsx, invokeai/frontend/web/src/features/nodes/components/panels/TopCenterPanel.tsx, invokeai/frontend/web/src/features/nodes/components/ui/ReloadSchemaButton.tsx
- Make the viewport fit to view on Init
- Update Reload Schema to an icon.
=> Node Editor: QoL Fixes

installer/lib/installer.py, tests/test_config.py
=> installer installs torchimetrics 0.11.4

invokeai/backend/model_management/model_manager.py, invokeai/backend/model_management/models/__init__.py, invokeai/backend/model_management/models/base.py, invokeai/backend/model_management/models/controlnet.py, invokeai/backend/model_management/models/lora.py, invokeai/backend/model_management/models/stable_diffusion.py, invokeai/backend/model_management/models/textual_inversion.py, invokeai/backend/model_management/models/vae.py
=> Less naive model detection

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/sessionCreated.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/sessionInvoked.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationError.ts
quick n dirty but better than what we have now
=> output stringified error for session and invocation errors

invokeai/frontend/web/src/features/nodes/components/ui/ClearNodesButton.tsx, invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts
@psychedelicious added the changes into a new pr as I deleted the old branch, can you see if its right please
=> Fix clear nodes with psychedelicious Requests

invokeai/frontend/web/src/features/lora/store/loraSlice.ts, invokeai/frontend/web/src/features/nodes/util/graphBuilders/addLoRAsToGraph.ts
=> fix(ui): fix crash on LoRA remove / weight change

README.md
This information was missing when I tried to get 3.0 running. I think this covers what what missing but please do let me know if anything is missing.
=> Updating installation instructions to include Node.JS

docs/contributing/LOCAL_DEVELOPMENT.md
add vscode setup instructions
- using vscode python debugger
- automatic python environment activation
- remote dev
- Related Issue # n/a
- Closes # n/a
Somebody could try out the instructions
=> docs: add vscode setup instructions

invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/AddModelsPanel/ScanAdvancedAddModels.tsx
=> fix: Model Manager scan Auto Add not detecting checkpoint correctly

invokeai/frontend/web/src/features/parameters/components/Parameters/MainModel/ParamMainModelSelect.tsx
hides sdxl models from linear ui model select. just a hold-me-over
- Closes #
=> feat(ui): hide sdxl from linear UI

invokeai/app/invocations/compel.py
=> Rename clip1 to clip

invokeai/frontend/web/src/features/system/components/InvokeAILogoComponent.tsx
=> add option to hide version on logo

invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsClearIntermediates.tsx
=> clear canvas alongside intermediates

invokeai/app/api_app.py
Resolves #3515
@ebr @brandonrising can't imagine this would cause issues but just FYI
=> feat(api): use next available port

invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/ModelManagerPanel/ModelList.tsx
Fixes a bug where a user could not scroll through checkpoints.
=> fix: Model List not scrolling through checkpoints

invokeai/frontend/web/src/common/components/IAIDndImage.tsx, invokeai/frontend/web/src/common/components/IAIDroppable.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardContextMenu.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardsList.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardsSearch.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/GalleryBoard.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/GenericBoard.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/SystemBoardButton.tsx, invokeai/frontend/web/src/features/gallery/components/GalleryBoardName.tsx, invokeai/frontend/web/src/features/gallery/components/GalleryPanel.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx, invokeai/frontend/web/src/features/ui/components/InvokeTabs.tsx, invokeai/frontend/web/src/features/ui/components/tabs/ResizeHandle.tsx, invokeai/frontend/web/src/services/api/hooks/useBoardName.ts, invokeai/frontend/web/src/services/api/hooks/useBoardTotal.ts, invokeai/frontend/web/src/theme/colors/colors.ts, invokeai/frontend/web/src/theme/components/editable.ts, invokeai/frontend/web/src/theme/theme.ts, invokeai/frontend/web/src/theme/util/getInputOutlineStyles.ts
Update the boards styling. See demo video
- Related Issue # discord discussions
- Closes #
https://github.com/invoke-ai/InvokeAI/assets/4822129/8df8be44-e232-43a8-a5a7-cf0cb3c1a300
make sure it look purdy
=> feat(ui): boards styling

invokeai/frontend/web/src/services/api/endpoints/images.ts
=> if updating intermediate, dont add to gallery list cache

invokeai/frontend/web/src/services/api/endpoints/images.ts
two areas marked TODO were not TODONE!
n/a
The `deleteImage` and `updateImage` mutations were missing the manual cache updates needed to keep the `No Board` board in sync. Fixed those.
- Related Issue # 
- Closes # https://discord.com/channels/1020123559063990373/1131314394823925871
- Delete an image that is not in a board. The `No Board` count should go down.
nah
=> fix(ui): fix no_board cache not updating

invokeai/app/api/routers/app_info.py
- [ X] Feature
- [X ] Yes
- [ X] Yes (swagger)
This add new routes for getting and setting the command line console logging level.
=> Add get_log_level and set_log_level operations to the app route

docs/index.md, docs/installation/010_INSTALL_AUTOMATED.md, docs/installation/index.md, docs/nodes/communityNodes.md, docs/nodes/overview.md, pull_request_template.md
Some minor docs tweaks
- Closes #
=> Couple doc tweaks

invokeai/backend/util/mps_fixes.py
Attention fix for MPS & SD-2
From @StAlKeR7779 , who is AFK at the moment
- Related Issue # discord
- Closes #
=> fix: mps attention fix for sd2

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/panels/TopCenterPanel.tsx, invokeai/frontend/web/src/features/nodes/components/ui/ClearGraphButton.tsx, invokeai/frontend/web/src/features/nodes/components/ui/LoadGraphButton.tsx, invokeai/frontend/web/src/features/nodes/components/ui/LoadNodesButton.tsx, invokeai/frontend/web/src/features/nodes/components/ui/SaveGraphButton.tsx
Uploading an incorrect JSON file to the Node Editor would crash the app.
While this is a much larger problem that we will tackle while refining the Node Editor, this is a fix that should address 99% of the cases out there.
When saving an InvokeAI node graph, there are three primary keys.
1. `nodes` - which has all the node related data.
2. `edges` - which has all the edges related data
3. `viewport` - which has all the viewport related data.
So when we load back the JSON, we now check if all three of these keys exist in the retrieved JSON object. While the `viewport` itself is not a mandatory key to repopulate the graph, checking for it will allow us to treat it as an additional check to ensure that the graph was saved from InvokeAI.
As a result ...
- If you upload an invalid JSON file, …
=> fix: Fix app crashing when you upload an incorrect JSON to node editor

invokeai/app/util/misc.py
=> fix: Generate random seed using the generator instead of RandomState

invokeai/backend/model_management/lora.py, invokeai/backend/model_management/models/lora.py
This import is missing and used later in the file.
=> Add missing import

invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/features/nodes/components/fields/ModelInputFieldComponent.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/MainModel/ParamMainModelSelect.tsx
=> add option to disable model syncing in UI

invokeai/frontend/web/src/features/nodes/util/parseSchema.ts
Temp fix for is intermediate switch for only l2i node
was also getting these
[0] /home/invokeuser/InvokeAI/invokeai/frontend/web/src/features/nodes/util/parseSchema.ts
[0]    33:5   warning  Forbidden non-null assertion  @typescript-eslint/no-non-null-assertion
[0]   102:33  warning  Forbidden non-null assertion  @typescript-eslint/no-non-null-assertion
changed some code to stop them (change that back if you didn't want that changed or I did it wrong)
- Closes #
=> [Nodes/Temp fix] for is intermediate switch for l2i

invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx
=> enable hide localization toggle

docs/index.md, docs/installation/010_INSTALL_AUTOMATED.md
- [X ] Documentation Update
- [X ] Yes
- [X ] Yes
Added solutions for installation issues related to large SDXL files and Windows dependency glitches.
=> Update troubleshooting guide with ~ydantic and SDXL unet issue advice

docs/nodes/communityNodes.md
- Remove old version of FaceMask and add link to FaceTools repository, which includes maintained versions of FaceMask, FaceOff, and FacePlace
- Move Ideal Size up from under the template entry
=> Update communityNodes.md - FaceTools

invokeai/app/services/config.py
This is a relatively stable release that corrects the urgent windows install and model manager problems in 3.0.1. It still has two known bugs:
1. Many inpainting models are not loading correctly.
2. The merge script is failing to start.
=> 3.0.1post3

invokeai/frontend/web/.husky/pre-commit
=> Add python black check to pre-commit

pyproject.toml
=> Add onnxruntime to the main dependencies

invokeai/frontend/web/src/services/events/middleware.ts
=> fix https/wss behind reverse proxy

invokeai/app/invocations/image.py
Added nodes for Hue Saturation and Luminosity
=> Added HSL Nodes

invokeai/backend/model_management/model_manager.py
- [X No, because small fix
A logic bug was introduced in PR #4109 that caused Web-based model updates to fail with a pydantic validation error. This corrects the problem.
PR #4109
=> Fix crash when attempting to update a model

invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx
- [s] Bug Fix
was sorting with disabled at top of list instead of bottom
fixes #4217
- Closes #4217
=> fix(ui): fix lora sort

invokeai/app/invocations/generate.py
=> Temporary force set vae to same precision as unet

invokeai/frontend/web/src/features/system/store/systemSlice.ts, invokeai/frontend/web/src/services/api/endpoints/images.ts, invokeai/frontend/web/src/services/api/thunks/session.ts
=> surface error detail

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/stagingAreaImageSaved.ts
=> fix missed spot for autoAddBoardId none

invokeai/app/api/routers/images.py, invokeai/app/services/image_record_storage.py, invokeai/app/services/models/image_record.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/index.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imagesStarred.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imagesUnstarred.ts, invokeai/frontend/web/src/common/components/IAIDndImage.tsx, invokeai/frontend/web/src/common/components/IAIDndImageIcon.tsx, invokeai/frontend/web/src/features/controlNet/components/ControlNetImagePreview.tsx, invokeai/frontend/web/src/features/gallery/components/GallerySettingsPopover.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/MultipleSelectionMenuItems.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImageGrid.tsx, invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts, invokeai/frontend/web/src/features/gallery/store/types.ts, invokeai/frontend/web/src/features/nodes/components/fields/fieldTypes/ImageInputField.tsx, invokeai/frontend/web/src/services/api/endpoints/images.ts, invokeai/frontend/web/src/services/api/schema.d.ts, invokeai/frontend/web/src/services/api/util.ts
Add the ability to "star" and "unstar" images, either one-by-one or via multiselect.
Changes the delete icon functionality - removes it as an optional setting, and adds interaction to have it show up on shift+hover.
- Closes #
=> Star images

docs/installation/INSTALLATION.md
This corrects a bunch of broken links I found in the installation overview page.
=> Fix several broken links in the installation index

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageDeleted.ts
There is a issue when you delete a image it quickly moves on to next image in line but resets nearly right away to the last created image,
after some checking ,I found and fixed the issue (as it is working for me now correctly on both single and multiple images)
- Closes #
#4247
=> Fix for Image Deletion issue

invokeai/app/invocations/compel.py
Report correctly to compel if we want get pooled in future(affects blend computation)
=> Report correctly to compel if we want get pooled in future

invokeai/app/invocations/image.py
Allows for the creation of blank images of any color. Especially handy for ControlNet. And basically any other use case where a blank image needs to be imported.
Based off #4339
=> feat: Blank Image Node

docs/nodes/communityNodes.md
discarded commits, resynced, added Load Video Frames to the community nodes. Hopefully I can start to understand github soon... sigh...
This is a video frame image provider + indexer/video creation nodes for hooking up to iterators and ranges and ControlNets and such for invokeAI node experimentation. Think animation + ControlNet outputs.
- Closes #
=> Update communityNodes.md - Load Video Frame

invokeai/backend/model_management/seamless.py
Last commit that didn't get merged in with #4370
=> Seamless Patch from Stalker

invokeai/app/invocations/model.py, invokeai/backend/stable_diffusion/diffusion/cross_attention_control.py, invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py, invokeai/backend/stable_diffusion/image_degradation/bsrgan.py, invokeai/backend/stable_diffusion/image_degradation/bsrgan_light.py, invokeai/backend/stable_diffusion/image_degradation/utils_image.py, invokeai/backend/training/textual_inversion_training.py, invokeai/backend/util/mps_fixes.py, invokeai/backend/util/util.py
=> fix: SDXL Lora Loader not showing weight input

invokeai/frontend/web/src/features/controlNet/components/ControlNetImagePreview.tsx
=> fix: ControlImage Dimension retrieval not working as intended

invokeai/frontend/web/src/features/nodes/types/types.ts
The logic that introduced a circular import was actually extraneous. I have entirely removed it.
This fixes the frontend lint test.
=> fix(ui): fix circular imports

invokeai/app/invocations/compel.py, invokeai/app/invocations/model.py
=> Fix sdxl lora loader input definitions, fix namings

docs/nodes/communityNodes.md
Adds my (@dwringer's) released nodes to the community nodes page.
Adds my released nodes -
Depth Map from Wavefront OBJ
Enhance Image
Generative Grammar-Based Prompt Nodes
Ideal Size Stepper
Image Compositor
Final Size & Orientation / Random Switch (Integers)
Text Mask (Simple 2D)
=> Update communityNodes.md with a few more nodes

invokeai/app/services/graph.py, invokeai/frontend/web/src/features/nodes/util/parseSchema.ts
fix(nodes): add version to iterate and collect
- Closes #
=> fix(nodes): add version to iterate and collect

docs/index.md
There was an issue with the responsiveness of the quick links buttons in the documentation.
- Related Issue #4455
- Closes #4455
• On the documentation website, go to the Home page, scroll down to the quick-links section.
[Home - InvokeAI Stable Diffusion Toolkit Docs.webm](https://github.com/invoke-ai/InvokeAI/assets/92071471/0a7095c1-9d78-47f2-8da7-9c1e796bea3d)
=> fixed quick links responsiveness

invokeai/frontend/web/src/services/api/endpoints/images.ts
If using the `shouldFetchMetadataFromApi` flag, do not try to GET the image at all.
- Closes #
=> dont try to load image at all if shouldFetchMetadataFromApi

invokeai/frontend/web/src/services/api/thunks/schema.ts
fix(ui): construct openapi url from window.location.origin
bugfix for commercial workflows
- Closes #
=> fix(ui): construct openapi url from window.location.origin

invokeai/frontend/web/src/features/parameters/store/generationSlice.ts
- [ X ] Optimization
- [ X ] Yes
- [ X ] No
Mask Edge was set to default, and producing poor results. I've updated the default back to Unmasked.
=> Unmasked default

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/queue/components/ClearQueueButton.tsx, invokeai/frontend/web/src/features/queue/components/common/QueueButton.tsx
feat(ui): add confirmation dialog box to clear queue button
- Related Issue https://discord.com/channels/1020123559063990373/1130288930319761428/1154027682460340224
=> feat(ui): add confirmation dialog box to clear queue button

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlNetImageProcessed.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketQueueItemStatusChanged.ts, invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts, invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemComponent.tsx, invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemDetail.tsx, invokeai/frontend/web/src/features/queue/components/QueueList/QueueListHeader.tsx, invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/AddModelsPanel/SimpleAddModels.tsx
Just a few tiny fixes that I stashed while working on other stuff:
- UI tweaks in the queue UI
- fix edge case where queue status update network request didn't fire
- remove console.logs
=> ui: misc small fixes

invokeai/frontend/web/src/features/queue/components/QueueBackButton.tsx, invokeai/frontend/web/src/features/queue/components/common/QueueButton.tsx
=> restore text of Invoke button

docs/features/UTILITIES.md
This is a doc file that was missing from PR #4587 . Since that PR was already merged. I’m pushing it in now.
=> add missing UTILITIES.md

invokeai/frontend/web/src/common/components/IAIInformationalPopover.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/BoundingBox/ParamBoundingBoxSize.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamSize.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx, invokeai/frontend/web/src/features/system/store/systemSlice.ts, invokeai/frontend/web/src/features/system/store/types.ts
=> set default for informational popups to be disabled

invokeai/frontend/web/src/common/components/GreyscaleInvokeAIIcon.tsx, invokeai/frontend/web/src/features/queue/components/QueueBackButton.tsx
https://github.com/invoke-ai/InvokeAI/assets/4822129/9a4632d7-c435-4b8b-9d67-8f625a31b099
=> feat(ui): add greyscale invoke logo to invoke button when as icon

invokeai/app/invocations/controlnet_image_processors.py, invokeai/app/invocations/latent.py, invokeai/app/invocations/onnx.py, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputFieldRenderer.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/BooleanInputField.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ImageInputField.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/NumberInputField.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/StringInputField.tsx, invokeai/frontend/web/src/features/nodes/hooks/useAnyOrDirectInputFieldNames.ts, invokeai/frontend/web/src/features/nodes/hooks/useConnectionInputFieldNames.ts, invokeai/frontend/web/src/features/nodes/types/constants.ts, invokeai/frontend/web/src/features/nodes/types/types.ts
[feat(nodes): remove ui_type overrides for polymorphic fields](https://github.com/invoke-ai/InvokeAI/commit/0bd7d7b29a0b3c093b9ca7df3abb435ba8a8cac0)
[feat(ui): render input components for polymorphic fields](https://github.com/invoke-ai/InvokeAI/commit/416163f4321899db5b71ef00b04605dc127a854d)
Polymorphic fields now render the appropriate input component for their base type.
For example, float polymorphics will render the number input box.
You no longer need to specify ui_type to force it to display.
**TODO: The UI *may* break if a list is provided as the default value for a polymorphic field.**
- Related Issue https://discord.com/channels/1020123559063990373/1130288930319761428/1151913978050641961
=> feat(nodes): polymorphic field UI

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketConnected.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketDisconnected.ts, invokeai/frontend/web/src/features/queue/components/CancelCurrentQueueItemButton.tsx, invokeai/frontend/web/src/features/queue/components/ClearQueueButton.tsx, invokeai/frontend/web/src/features/queue/components/PauseProcessorButton.tsx, invokeai/frontend/web/src/features/queue/components/PruneQueueButton.tsx, invokeai/frontend/web/src/features/queue/components/ResumeProcessorButton.tsx, invokeai/frontend/web/src/features/queue/hooks/useCancelBatch.ts, invokeai/frontend/web/src/features/queue/hooks/useCancelCurrentQueueItem.ts, invokeai/frontend/web/src/features/queue/hooks/useCancelQueueItem.ts, invokeai/frontend/web/src/features/queue/hooks/useClearQueue.ts, invokeai/frontend/web/src/features/queue/hooks/usePauseProcessor.ts, invokeai/frontend/web/src/features/queue/hooks/usePruneQueue.ts, invokeai/frontend/web/src/features/queue/hooks/useResumeProcessor.ts, invokeai/frontend/web/src/features/system/store/systemPersistDenylist.ts, invokeai/frontend/web/src/features/system/store/systemSlice.ts, invokeai/frontend/web/src/features/system/store/types.ts
[fix(ui): no duplicate network requests on app startup](https://github.com/invoke-ai/InvokeAI/commit/16c1cba9af7a9e4d278d7befce11e8d1bc901077)
[feat(ui): disable queue-related buttons when disconnected](https://github.com/invoke-ai/InvokeAI/commit/9049f8f3bb11e266167c134ea539bad48c2bc7ad)
=> ui: duplicate network requests

invokeai/backend/ip_adapter/README.md
Updates the IP-Adapter documentation to reflect this bugfix: https://huggingface.co/InvokeAI/ip_adapter_sdxl_vit_h/commit/e178288fb6fca1a64868ca1e8458722d4d27dbb5
=> (minor) Update IP-Adapter documentation

pyproject.toml
- [ x ] Optimization
- [ x ] Yes
- [ x ] No
Updates to Diffusers .21
=> Update Diffusers to .21 and Accelerate to .23

invokeai/app/services/session_queue/session_queue_sqlite.py
fix(queue): fix duplicate queue item status events
the only session_queue methods that should emit are:
- `_set_queue_item_status()` - handles individual queue items
- `cancel_by_batch_ids()` - handles whole batches and does not call `_set_queue_item_status()`
- `cancel_by_queue_id()` - handles the entire queue and does not call `_set_queue_item_status()`
=> fix(queue): fix duplicate queue item status events

invokeai/app/invocations/ip_adapter.py, invokeai/frontend/web/src/features/nodes/types/constants.ts
=> fix(nodes): fix ip-adapter field positioning on workflow editor

invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts
fix(ui): do not reset node outputs on queue item completed
=> fix(ui): do not reset node outputs on queue item completed

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/InvocationNodeFooter.tsx, invokeai/frontend/web/src/features/nodes/hooks/useHasImageOutput.ts, invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts
[fix(ui): fix node glow styling](https://github.com/invoke-ai/InvokeAI/commit/4b03741c9218cd204c15b477e1f8f56b434289a1)
[fix(ui): hide workflow and gallery checkboxes on image primitive](https://github.com/invoke-ai/InvokeAI/commit/2e79905447dfcf13bf4b8d9474ae29b0c6bc723f)
This node doesn't actually *save* the image, so these checkboxes do nothing on it. Remove them.
=> fix(ui): misc nodes fix

invokeai/app/api_app.py, invokeai/frontend/web/src/common/components/IAIMantineMultiSelect.tsx, invokeai/frontend/web/src/common/components/IAIMantineSearchableSelect.tsx, invokeai/frontend/web/src/common/components/IAIMantineSelect.tsx
Notably in the change board modal.
- Related Issue https://discord.com/channels/1020123559063990373/1149513625321603162/1155123297554550794
=> fix(ui): fix hidden dropdowns

invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemSkeleton.tsx, invokeai/frontend/web/src/features/queue/components/QueueList/QueueList.tsx
Adds a skeleton loading state for the queue list so it doesn't look like your queue is empty while its loading
- Closes #
=> add skeleton loading state for queue list

invokeai/app/api/routers/models.py
I left a dangling debug statement in a recent merged PR (#4674 ). This removes it.
=> Remove dangling debug statement

invokeai/app/services/invocation_cache/invocation_cache_memory.py
Remove extra arg
This snuck into the #4657 & breaks generation
=> fix(backend): remove extra cache arg

invokeai/frontend/web/public/locales/en.json
fix(ui): fix loading queue item translation
=> fix(ui): fix loading queue item translation

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/app/components/PreselectedImage.tsx, invokeai/frontend/web/src/features/parameters/hooks/usePreselectedImage.ts
fix(ui): usePreselectedImage causing re-renders
This hook was rerendering any time anything changed. Moved it to a logical component, put its useEffects inside the component. This reduces the effect of the rerenders to just that tiny always-null component.
@maryhipp I don't think this changes anything but please double check
=> fix(ui): usePreselectedImage causing re-renders

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/batchEnqueued.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlNetImageProcessed.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/upscaleRequested.ts, invokeai/frontend/web/src/features/controlNet/store/controlNetSlice.ts
Update error handling for enqueue endpoints to surface usage errors correctly
- Closes #
=> surface usage errors for queues

invokeai/frontend/web/src/common/components/IAICollapse.tsx, invokeai/frontend/web/src/common/components/IAIDndImage.tsx, invokeai/frontend/web/src/common/components/IAIDndImageIcon.tsx, invokeai/frontend/web/src/common/components/IAIIconButton.tsx, invokeai/frontend/web/src/common/components/IAIMantineSearchableSelect.tsx, invokeai/frontend/web/src/common/components/IAIMantineSelect.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/AddBoardButton.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardsList.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardsSearch.tsx, invokeai/frontend/web/src/features/gallery/components/CurrentImage/CurrentImagePreview.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGalleryContent.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/ImageGridItemContainer.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/ImageGridListContainer.tsx, invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/ControlNet/ParamControlNetCollapse.tsx, invokeai/frontend/web/src/features/parameters/components/Parameters/ImageToImage/InitialImage.tsx, invokeai/frontend/web/src/features/queue/components/QueueControls.tsx, invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemComponent.tsx, invokeai/frontend/web/src/features/queue/components/QueueStatus.tsx, invokeai/frontend/web/src/features/queue/components/common/QueueButton.tsx
=> add data-testids to UI components that may be hard to target with automation

invokeai/frontend/web/src/common/components/IAIDndImage.tsx
fix(ui): `data-testId` -> `data-testid`
Must be strict kebab-case for react to pass the attribute to DOM
=> fix(ui): `data-testId` -> `data-testid`

docs/nodes/communityNodes.md
Adds another node description (Rotate/Flip Image) to Image and Mask Composition Pack
n/a
n/a
=> update communitynodes.md to add Rotate/Flip Image to composition pack

docs/contributing/contribution_guides/development.md
- [ x ] Documentation Update
- [ x ] No, because:
- [x  ] Yes
=> Fix typo of Psychedelicious name

docs/nodes/communityNodes.md
add Image to Character Art Image Node's to communityNodes.md
https://github.com/mickr777/imagetoasciiimage
- Closes #
=> add Character Art Node's to communityNodes.md

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageUploaded.ts
Fixes missing toast text when a user uploads an image
- Closes #
=> fix missing toast message on image upload

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/modelsLoaded.ts, invokeai/frontend/web/src/features/controlNet/components/ipAdapter/IPAdapterPanel.tsx, invokeai/frontend/web/src/features/controlNet/components/ipAdapter/ParamIPAdapterImage.tsx, invokeai/frontend/web/src/features/controlNet/components/ipAdapter/ParamIPAdapterModelSelect.tsx
Update UI for IP adapter to take up less real estate and auto-select first model in list
- Closes #
=> IP adapter UI

docs/nodes/communityNodes.md
- [D] Community Node Submission
I added my project to the links of community nodes. This links to a workflow plugin that allows users to create 3D stereo images from 2D originals.
- Closes #
=> Add 'make 3d' plugin.

invokeai/backend/ip_adapter/ip_adapter.py
Add support for IPAdapterPlusXL based on https://github.com/tencent-ailab/IP-Adapter/commit/6219530507cb4696a0496f10c0e5a4f1dbdc7672.
This is required to support the new IP-Adapter model here: https://huggingface.co/InvokeAI/ip-adapter-plus_sdxl_vit-h
I tested manually that all of the IP-Adapter models here still work: https://huggingface.co/InvokeAI
=> New IP-Adapter model type (`IPAdapterPlusXL`)

invokeai/frontend/web/src/features/gallery/components/CurrentImage/CurrentImageButtons.tsx
Fix the `a` use all parameters hotkey
- Closes #4800
The hotkey should work. Cut and dry fix.
=> fix(ui): fix use all hotkey

invokeai/frontend/web/src/features/controlAdapters/store/constants.ts
feat(ui): add mapping for sketch and scribble control adapter processors
=> feat(ui): add mapping for sketch and scribble control adapter processors

invokeai/backend/model_management/model_cache.py
Demote model cache warnings to debug level based on the conversation here: https://discord.com/channels/1020123559063990373/1049495067846524939/1161647290189090816
=> Demote model cache logs from warning to debug

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsClearIntermediates.tsx
feat(ui): add translation strings for clear intermediates
- Closes #4851
@Millu this can go into 3.3.0
=> feat(ui): add translation strings for clear intermediates

pyproject.toml
I should have included this message when the hack was originally added, but better late than never. At this point, it's looking likely that the relevant fix will be included in the next diffusers minor version bump.
=> Add a comment describing required action before bumping diffusers

invokeai/backend/stable_diffusion/diffusers_pipeline.py, invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/index.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlAdapterAddedOrEnabled.ts, invokeai/frontend/web/src/features/controlAdapters/store/controlAdaptersSlice.ts, invokeai/frontend/web/src/services/api/schema.d.ts
#4914 was merged prematurely. Needs to wait for next diffusers release.
=> Revert 4914 feat/mix cnet t2iadapter

invokeai/backend/image_util/invisible_watermark.py, invokeai/backend/image_util/safety_checker.py
Trivial fix of nsfw/watermarker types
- Related Issue: split out from #4686, where it has no business being
=> fix(backend): fix nsfw/watermarker util types

invokeai/frontend/web/src/features/nodes/hooks/useAnyOrDirectInputFieldNames.ts, invokeai/frontend/web/src/features/nodes/hooks/useConnectionInputFieldNames.ts, invokeai/frontend/web/src/features/nodes/hooks/useOutputFieldNames.ts, invokeai/frontend/web/src/features/nodes/util/getSortedFilteredFieldNames.ts
closes #4934
fix(ui): fix field sorting
tbh I don't understand why it broke but this fixes it
- Closes #4934
=> fix(ui): fix field sorting

invokeai/app/invocations/math.py
Update field_validator api for pydantic v2
- Related Issue https://discord.com/channels/1020123559063990373/1049495067846524939/1163810964311912498
math nodes should work
=> fix(nodes): fix math node validation

invokeai/app/invocations/baseinvocation.py
fix(nodes): enable number to string coercion
- Closes #4933
=> fix(nodes): enable number to string coercion

invokeai/app/services/model_manager/__init__.py, invokeai/frontend/merge/merge_diffusers.py
Some PRs were merged with failing tests, causing all PRs to faill. Fixing flake8 tests.
=> chore: flake8

invokeai/app/services/workflow_records/workflow_records_sqlite.py
[fix(db): fix deprecated pydantic .json() method](https://github.com/invoke-ai/InvokeAI/commit/1d4441309fb3bc9536b2bed0bd083e4cefccaf20)
- Closes #4970
=> fix(db): fix deprecated pydantic `.json()` method

invokeai/frontend/install/invokeai_update.py
This PR gives the user the option of upgrading to the latest PRE-RELEASE in addition to the default of updating to the latest release. This will allow users to conveniently try out the latest pre-release for a while and then back out to the official release if it doesn't work for them.
=> Add option to invokeai update script to install latest prerelease

invokeai/backend/model_management/lora.py
This PR makes a minor change to `apply_ti(..)` for significant speed savings. (See the in-code documentation for a full explanation). The change reduces the time for the copy step from ~1sec to ~0.05secs. This speedup is incurred 2x in a typical SD1 text-to-image workflow and 4x in a typical SDXL text-to-image workflow. The speedup is observed even if no TI embeddings are being used.
Tested with and without TI embeddings.
=> Speed optimization in `apply_ti(...)`

invokeai/backend/model_management/model_cache.py
See https://github.com/invoke-ai/InvokeAI/pull/5034#discussion_r1382381733
=> Fix model cache gc.collect() condition.

invokeai/configs/INITIAL_MODELS.yaml
Removing LowRA from the initial models as it's been deleted from CivitAI. 
https://discord.com/channels/1020123559063990373/1168415065205112872
- Closes #
=> Remove LowRA from Initial Models

pyproject.toml
- [ x ] Optimization
- [ x ] Yes
- [ x ] Yes
Updates Diffusers dependency.
=> Update Diffusers to .22

installer/lib/installer.py, pyproject.toml
Need to update the installation docs - will do after 3.4.0rc goes out
- Closes #
=> Update xformers to ~=0.0.22 & cuda to cu121

invokeai/app/api/sockets.py
- :bug:  Bug Fix
- Yes, https://discord.com/channels/1020123559063990373/1049495067846524939/1171976251704086559
- N/A
unsubscribe should result in leaving, not joining.
=> fix(socketio): leave room on unsubscribe

invokeai/backend/install/invokeai_configure.py
[fix(installer): fix import of ValidationError](https://github.com/invoke-ai/InvokeAI/commit/606282240eb8fbf3987280ad38f7ce0bb8d0d9ff)
It was being imported from a deprecated module
=> fix(installer): fix import of `ValidationError`

pyproject.toml
=> Update diffusers to ~=0.23

docs/index.md, invokeai/backend/install/legacy_arg_parsing.py, invokeai/backend/stable_diffusion/schedulers/schedulers.py, invokeai/frontend/web/src/features/parameters/types/parameterSchemas.ts, invokeai/frontend/web/src/services/api/schema.d.ts
~~**DOES NOT WORK** -- Need to fix the incorrect shapes and then we probably need to isolate the type for LCM Models so we can control the schedulers for them. But the Scheduler is implemented.~~
UPDATE 2023-11-10
With the latest changes to diffusers package, this PR works for the LCMScheduler / LCM-LoRA combo.
- Closes #
=> wip: Add LCMScheduler

installer/lib/installer.py
=> Update installer.py to use cu118 instead of 121

README.md, docs/installation/010_INSTALL_AUTOMATED.md, docs/installation/040_INSTALL_DOCKER.md
=> Update README.md to include M3

README.md, docs/installation/010_INSTALL_AUTOMATED.md, docs/installation/020_INSTALL_MANUAL.md, docs/installation/030_INSTALL_CUDA_AND_ROCM.md, docs/installation/070_INSTALL_XFORMERS.md, installer/lib/installer.py
=> Revert torch to use cu121

docs/nodes/communityNodes.md
=> Added unsharp mask node to communityNodes.md

docs/nodes/exampleWorkflows.md
Some links to example workflows were not working as intended
=> Fix links to example workflows

invokeai/backend/model_management/model_probe.py
This one-line patch adds support for LCM models such as `SimianLuo/LCM_Dreamshaper_v7`
- Closes #4951 
Try installing  `SimianLuo/LCM_Dreamshaper_v7` and using with CFG 2.5 and the LCM scheduler.
=> Add support for LCM main models

README.md
Fixes wrong Q&A Troubleshooting link (original leads to 404)
- Closes #
=> Update README.md (Q&A 404)

invokeai/frontend/web/src/features/parameters/hooks/usePreselectedImage.ts
The back-end response changed and shame on me for casting.
- Closes #
=> fix preselected image

invokeai/frontend/web/src/theme/theme.ts
[https://github.com/invoke-ai/InvokeAI/issues/5079](https://github.com/invoke-ai/InvokeAI/issues/5079)
This is pull request for this Ticket
=> move toast to the bottom right

invokeai/frontend/web/src/app/hooks/useSocketIO.ts
=> dont set socketURL until socket is initialized

invokeai/frontend/web/.husky/pre-commit, invokeai/frontend/web/package.json, invokeai/frontend/web/yarn.lock
You can only have one pre-commit setup on a repo. Removing husky so it doesn't interfere with the python pre-commit.
- Related Issue https://discord.com/channels/1020123559063990373/1149513625321603162/1181752622684831884
=> feat(ui): remove husky

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/batchEnqueued.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlNetImageProcessed.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/upscaleRequested.ts, invokeai/frontend/web/src/app/store/store.ts, invokeai/frontend/web/src/services/api/authToastMiddleware.ts, invokeai/frontend/web/src/services/api/endpoints/images.ts
=> add middleware to handle 403 errors

docs/nodes/communityNodes.md
Updates to community nodes with  VeyDlin's nodes
=> Update communityNodes.md with VeyDlin's nodes

invokeai/frontend/web/.eslintrc.js, invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml
Makes unused imports a violation
=> feat(ui): add eslint unused-imports plugin

invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts
Insurance against invalid inputs. Closes #5250
=> fix(ui): add validation to field value reducers

invokeai/frontend/web/src/features/nodes/util/workflow/migrations.ts
This should default to "1.0.0" to match the behaviour of the backend.
- Related Issue https://discord.com/channels/1020123559063990373/1049495067846524939/1184533310731468911
@JPPhoto This branch should fix the loading of all those workflows that complain about the node data version.
This can be merged once @JPPhoto confirms it resolves his issue.
=> fix(ui): fix frontend workflow migration when node is missing version

docs/installation/020_INSTALL_MANUAL.md
see diff
This PR can be merged when approved.
=> docs: add warning to developer install about database & main

invokeai/app/invocations/tiles.py
missed this [node] when I added classification
=> fix(nodes): mark CalculateImageTilesInvocation as beta

invokeai/backend/model_management/util.py, invokeai/backend/model_manager/probe.py
This adds a probe for the SDXL LoRA format found in the wild at https://civitai.com/models/224641.
See discord message at: https://discord.com/channels/1020123559063990373/1149510134058471514/1184982133912113182
Try installing the SDXL LoRA at the URL given above.
This can be merged when approved.
=> [feat] Make model prober recognize yet another LoRA format

invokeai/backend/model_management/model_probe.py
This change enables the model probe to work with TI embeddings that have the follow state_dict structure:
```python
{
"<any_key>": torch.Tensor(...), # where the tensor has shape (N, embedding_dim)
}
```
I can't imagine an embedding format that would previously have passed the model probe, and would now fail after this change. That being said, I'll exercise a bunch of existing TIs before merging.
=> Update model_probe to work with diffuser-format SD TI embeddings.

invokeai/frontend/install/invokeai_update.py
Updater script pulls from PyPI instead of GitHub releases (this is why the RC packages are having issues when updating through the launcher script)
- Closes #
=> (feat) updater installs from PyPi instead of GitHub releases

invokeai/frontend/web/src/app/store/store.ts, invokeai/frontend/web/src/services/api/authToastMiddleware.ts
=> add authToastMiddleware back and fix parsing

invokeai/app/services/workflow_records/default_workflows/ESRGAN Upscaling with Canny ControlNet.json, invokeai/app/services/workflow_records/default_workflows/Face Detailer with IP-Adapter & Canny (See Note).json, invokeai/app/services/workflow_records/default_workflows/Multi ControlNet (Canny & Depth).json, invokeai/app/services/workflow_records/default_workflows/Prompt from File.json, invokeai/app/services/workflow_records/default_workflows/Text to Image with LoRA.json
Added more default workflows to the workflow library
- Closes #
=> Add more default workflows

invokeai/frontend/web/src/features/nodes/components/flow/panels/TopPanel/WorkflowName.tsx
=> remove (Unsaved) if workflow library is disabled

invokeai/app/invocations/compel.py, invokeai/app/invocations/onnx.py, invokeai/app/util/ti_utils.py
=> Ti trigger from prompt util

README.md, invokeai/backend/install/check_root.py
The error message that tells the user to run option [7] in the invoke launcher is incorrect. The correct option number is [6]. This PR fixes the problem
- closes #5209
- Closes #
=> [bugfix] Fix the message that tells user how to fix a broken install

invokeai/app/services/config/config_default.py
Strange behavior could occur when INVOKEAI_ROOT was a symlink and relative pathnames were used in `models.yaml`. This PR resolves symlinks along the root path at the `InvokeAIAppConfig` layer so that the real path is always returned. 
- Related Issue #5224 
- Closes #
Make a symlink to your invokeai root and then point the server at the symlink using `invokeai-web --root <path/to/symlink>`. After startup, try listing diffusers and checkpoints in the web model manager tab. Listings should work.
=> [Bugfix] Resolve symlinked INVOKEAI_ROOT

docs/workflows/ESRGAN_img2img_upscale_w_Canny_ControlNet.json, docs/workflows/Face_Detailer_with_IP-Adapter_and_Canny.json, docs/workflows/Multi_ControlNet_Canny_and_Depth.json, docs/workflows/Prompt_from_File.json, docs/workflows/SDXL_Text_to_Image.json, docs/workflows/Text_to_Image.json, invokeai/app/services/workflow_records/default_workflows/ESRGAN Upscaling with Canny ControlNet.json, invokeai/app/services/workflow_records/default_workflows/Multi ControlNet (Canny & Depth).json
=> Fix model names to match defaults in workflows & update example workflows in docs

docs/nodes/communityNodes.md
Adds nightmare promptgen to the community nodes list.
=> add nightmare promptgen to communityNodes.md

invokeai/app/services/workflow_records/default_workflows/Tiled Upscaling.json
Add Tiled Upscaling to default workflows
- Closes #
=> Add Tiled Upscaling to default workflows

invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/assets/images/invoke-key-wht-lrg.svg, invokeai/frontend/web/src/common/components/InvTooltip/theme.ts, invokeai/frontend/web/src/common/components/Loading/Loading.tsx
=> define tooltip color, optional new logo 

invokeai/version/invokeai_version.py
Release
v3.6.0rc2 release
- Closes #
Test latest main & [Uploading InvokeAI-installer-v3.6.0rc2.zip…](Installer zip)
PR can be merged immediately
Publish release on PyPI and GitHub
=> Release:  v3.6.0rc2

invokeai/frontend/web/src/features/ui/hooks/usePanel.ts
=> fix default panel width

invokeai/frontend/web/src/features/ui/components/InvokeTabs.tsx
=> replace gear instead of adding below if custom nav component

invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/app/store/nanostores/customAppInfo.ts, invokeai/frontend/web/src/app/store/nanostores/logo.ts, invokeai/frontend/web/src/features/system/components/InvokeAILogoComponent.tsx
=> logo override

README.md
=> Update Readme w/ New Brand Images

invokeai/version/invokeai_version.py
Release v3.6.0rc3
- [] Yes
Next release candidate
N/A
- Closes #
[Uploading InvokeAI-installer-v3.6.0rc3.zip…](Installer zip)
Release on PyPI & Github
=> {release} v3.6.0rc3

invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/useClearIntermediates.ts
=> only GET intermediates if that setting is an option

invokeai/frontend/web/src/features/lora/components/LoRACard.tsx
=> fix text color for lora card

pyproject.toml
Hello everyone, happy late New Year!
This PR updates Diffusers to the latest version. No regressions have accrued during my testing.
**Note:** 
It seems like diffusers implemented some optimizations for SDXL specifically, being advertised as "3x faster SDXL performance". They do not seem to be enabled/used by default. As earlier discussions on discord have pointed out, we might want to look into these and implement them. However, everything seem to be running right now as it is.
Greetings
- Closes #
=> Update diffusers to the lastest version

invokeai/version/invokeai_version.py
Release - InvokeAI v3.5.0rc5
Release - InvokeAI v3.5.0rc5
[InvokeAI-installer-v3.6.0rc5.zip](https://github.com/invoke-ai/InvokeAI/files/13863661/InvokeAI-installer-v3.6.0rc5.zip)
Releasee on PyPi & GitHub
=> {release} v3.5.0rc5

invokeai/frontend/web/src/services/api/authToastMiddleware.ts
=> do not show toast if 403 is triggered by forbidden image

invokeai/frontend/web/src/features/nodes/hooks/useWorkflowWatcher.ts
Minor perf improvement.
This PR can be merged when approved.
=> fix(ui): use memoized selector for workflow watcher

invokeai/version/invokeai_version.py
Release v3.6.0rc6
Release candidate $6 
[InvokeAI-installer-v3.6.0rc6.zip](https://github.com/invoke-ai/InvokeAI/files/13890206/InvokeAI-installer-v3.6.0rc6.zip)
Release on PyPi & Github
=> {release} v3.6.0rc6

invokeai/app/services/config/__init__.py
At some point the reorganization of the app/services directories changed the import location of `PagingArgumentParser`, which is used by the textual inversion training script. This fixes the issue.
- Closes #5395 
- Closes #
Can merge when approved.
=> Bugfix textual inversion crash

invokeai/app/services/workflow_records/workflow_records_sqlite.py, invokeai/frontend/web/src/features/nodes/store/workflowSlice.ts, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryList.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryListItem.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryModal.tsx
- [ x ] Optimization
- [ x ] Yes
This ticket changes the Library styling to a more condensed max W/H, and ensures the description doesn't cause major formatting issues even when long. It likely has room for improvement, but this addresses feedback re: full screen Library --
#5419 
This shouldn't really change much for anyone except those who have a large monitor.
=> Enhancement: Workflow Library Styling

invokeai/frontend/web/src/features/gallery/components/NextPrevImageButtons.tsx
Quick fix to stop right button hiding under hidden gallery button, and evened out the alignment of boths sides,
tested on chrome and edge
- Closes #
=> Quick Fix for right gallery button

invokeai/frontend/web/src/app/components/ThemeLocaleProvider.tsx
Prevent edge cases where light mode is set externally.
=> fix(ui): force dark mode

invokeai/backend/model_management/model_manager.py
Previously, when renaming any models file using the model manager API, the file extension would be dropped unless specified in the new name. This PR maintains the original suffix across renames.  It does not affect diffusers or other folder-style models.
- Closes #5518
Go to the Web interface model manager, select a checkpoint or LoRA model, and rename it. Then check the `models` directory to confirm that the `.safetensors` suffix is retained across the rename operation. 
=> Retain suffix (.safetensors, .bin) when renaming a model file

invokeai/frontend/web/src/app/components/AppErrorBoundaryFallback.tsx, invokeai/frontend/web/src/common/components/IAIDndImage.tsx, invokeai/frontend/web/src/common/components/IAIImageFallback.tsx, invokeai/frontend/web/src/common/components/IAIInformationalPopover/IAIInformationalPopover.tsx, invokeai/frontend/web/src/features/controlAdapters/components/ControlAdapterImagePreview.tsx, invokeai/frontend/web/src/features/dynamicPrompts/components/ParamDynamicPromptsPreview.tsx, invokeai/frontend/web/src/features/embedding/AddEmbeddingButton.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardContextMenu.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/GalleryBoard.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/GalleryBoardContextMenuItems.tsx, invokeai/frontend/web/src/features/gallery/components/CurrentImage/CurrentImagePreview.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImageGrid.tsx, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/DataViewer.tsx, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataItem.tsx, invokeai/frontend/web/src/features/gallery/components/NextPrevImageButtons.tsx, invokeai/frontend/web/src/features/lora/components/LoRACard.tsx, invokeai/frontend/web/src/features/modelManager/subpanels/AddModelsPanel/ScanAdvancedAddModels.tsx, invokeai/frontend/web/src/features/modelManager/subpanels/AddModelsPanel/SearchFolderForm.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/InvocationNodeClassificationIcon.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/InvocationNodeInfoIcon.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/InvocationNodeStatusIndicator.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/FieldContextMenu.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/LinearViewField.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ImageFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/panels/TopPanel/UpdateNodesButton.tsx, invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemComponent.tsx, invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemDetail.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLPrompts/SDXLConcatButton.tsx, invokeai/frontend/web/src/features/system/components/StatusIndicator.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryPagination.tsx
=> feat: :lipstick: update lots of icons

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/promptChanged.ts, invokeai/frontend/web/src/features/dynamicPrompts/components/ParamDynamicPromptsPreview.tsx, invokeai/frontend/web/src/features/dynamicPrompts/components/ShowDynamicPromptsPreviewButton.tsx, invokeai/frontend/web/src/features/dynamicPrompts/store/dynamicPromptsSlice.ts, invokeai/frontend/web/src/features/dynamicPrompts/util/getShouldProcessPrompt.ts
- Bump `@invoke-ai/ui` for updated styles
- Update regex to parse prompts with newlines
- Update styling of overlay button when prompt has an error
- Fix bug where loading and error state sometimes weren't cleared
This test case prompt should work and create 3 prompts:
```
{cat|
dog|
hamster}
```
=> feat(ui): improved dynamic prompts behaviour

pyproject.toml
This commit updates all huggingface dependencies to their latest versions.
Since these dependencies are hard pinned now (e.g. ==version) every minior release needs to be updated manually.
Usually minor X.1 releases don't bring breaking changes. Maybe we should think about brining ~= pins back for huggingface dependencies.
Anyway, no regression occurred during my testing with these updated deps.
Greetings.
- Closes #
=> Update huggingface deps to their lastest versions

invokeai/frontend/web/src/app/hooks/useSocketIO.ts, invokeai/frontend/web/src/i18n.ts, invokeai/frontend/web/src/services/api/index.ts, invokeai/frontend/web/src/services/api/thunks/schema.ts
We can't assume that the base URL is `host:port/` - it could be `host:port/some/path/`. Make the path handling dynamic to account for this.
- Test the UI in dev mode
- Test the UI build
(I've done both and it all works for me)
=> feat(ui): handle proxy configs rewriting paths

invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/app/hooks/useSocketIO.ts, invokeai/frontend/web/src/app/store/nanostores/openAPISchemaUrl.ts, invokeai/frontend/web/src/services/api/thunks/schema.ts
Fixes socket connection when `baseUrl` is passed in
- Closes #
=> account for baseUrl

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/system/components/AboutModal/AboutModal.tsx
This copies the dependencies as JSON.
feat(ui): add a copy button to the about modal
This copies the dependencies as JSON.
Output:
```json
{
"accelerate": "0.25.0",
"compel": "2.0.2",
"cuda": "12.1",
"diffusers": "0.25.0",
"numpy": "1.26.3",
"opencv": "4.9.0.80",
"onnx": "1.15.0",
"pillow": "10.2.0",
"python": "3.10.12",
"torch": "2.1.2+cu121",
"torchvision": "0.16.2",
"transformers": "4.36.2",
"xformers": "0.0.23.post1"
}
```
=> feat(ui): add a copy button to the about modal

invokeai/frontend/web/config/vite.package.config.mts
=> add UI library to rollup config

invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasToolChooserOptions.tsx, invokeai/frontend/web/src/features/canvas/hooks/useCanvasZoom.ts
- Related Issue #5443
- Closes #5443
=> changed hotkeys

invokeai/app/services/config/config_default.py, invokeai/app/services/invocation_processor/invocation_processor_default.py, invokeai/app/util/profiler.py, pyproject.toml, scripts/generate_profile_graphs.sh, tests/test_profiler.py
- Add a simple profiler utility
- Add config settings to enable profiling graphs, output dir for the profiles, and a prefix for the profile outputs
- Add helper script to generate graph visualizations from the profiles
- Add `snakeviz` and `gprof2dot` as dev deps (you also need graphviz but it's not available as a standalone python package, comments added to link to it)
- Use profile in invocation processor (only if profiling is enabled)
- Add tests for profiler
- `pip install -e '.[dev]'` to get `snakeviz` and `gprof2dot`
- install [graphviz](https://www.graphviz.org/download/) 
- In `invokeai.yaml`, under `Development:` add `profile_graphs: true` (profiles will be written to `$INVOKEAI_ROOT/profiles` by default, can change this with `profiles_dir: /some/path/`)
- Generate
- Run …
=> feat: add profiler util

invokeai/frontend/web/src/features/nodes/components/flow/panels/TopRightPanel/WorkflowEditorSettings.tsx
Got borked in the redesign. Fixed now.
=> fix(ui): workflow settings styling

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/boardIdSelected.ts
fixes bug where selecting boards cleared the preview image
- Closes #
=> board switching : select first image if no selectedImageName

docs/installation/020_INSTALL_MANUAL.md
docs: update link to frontend README
=> docs: update link to frontend README

invokeai/frontend/web/.eslintrc.js, invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/src/features/nodes/components/flow/panels/TopPanel/ClearFlowButton.tsx, invokeai/frontend/web/src/features/nodes/components/flow/panels/TopPanel/SaveWorkflowButton.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/SaveWorkflowAsDialog/SaveWorkflowAsDialog.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryMenu/SaveWorkflowMenuItem.tsx, invokeai/frontend/web/src/features/workflowLibrary/hooks/useSaveWorkflowAs.ts
Chore
bump `@invoke-ai/eslint-config-react` & lint
Some rules had been misplaced and are now restored.
=> chore(ui): bump `@invoke-ai/eslint-config-react`

invokeai/frontend/web/src/features/settingsAccordions/components/ImageSettingsAccordion/ImageSettingsAccordion.tsx
fix(ui): hide HRF if SDXL model selected
https://discord.com/channels/1020123559063990373/1149513625321603162/1202678138044158023
=> fix(ui): hide HRF if SDXL model selected

invokeai/backend/stable_diffusion/diffusion/cross_attention_control.py, invokeai/backend/util/hotfixes.py, pyproject.toml
A [new version](https://github.com/huggingface/diffusers/releases) of diffusers has just released yesterday with some major [refractions](https://github.com/huggingface/diffusers/commit/1f0705adcfe9e57db1bb90c2938922249b186cfc). I tried to catch all imports, but it is possible that I missed some. The old imports will be deprecated in version 0.29.0, so I tried to find them all and change them while I am at it.
If you like, please look if I missed some somewhere.
There seem to be some scripts that might use the old imports. But as I said, for now, there is nothing breaking.
Fixed the hotfix.py for a name change (fix?) [introduced upstream here](https://github.com/huggingface/diffusers/commit/fee93c81eb7c5e9fe1618f858f1e369567170edc)
Everything seems to be running fine for me. Invoke is …
=> Update diffusers to 0.26.0 and fix imports/names

invokeai/app/services/invocation_stats/invocation_stats_default.py, invokeai/app/services/item_storage/item_storage_base.py, invokeai/app/services/item_storage/item_storage_common.py, invokeai/app/services/item_storage/item_storage_memory.py, tests/test_item_storage_memory.py
See [fix(item-storage-memory): throw when requested item does not exist](https://github.com/invoke-ai/InvokeAI/commit/33f805ec028433f4aa1abcce3098975dea2884e6) for a detailed description of the issue.
Also tidied up a couple things. 
- Related Issue https://discord.com/channels/1020123559063990373/1149513647022948483/1203202612086972436
I'm not sure how to reproduce the issue in the app, but I updated the tests to catch the situation.
=> fix(nodes): fix error when pruning graph stats

pyproject.toml
These are some minor bug fixes for diffusers and hf_hub, both running without regressions.
This is just to make sure that the next Version (3.6.3?) is shipping with all current updates.
Greetings
- Closes #
=> Minor updates for diffusers and hf_hub

invokeai/frontend/web/src/common/hooks/useDownloadImage.ts, invokeai/frontend/web/src/features/gallery/store/actions.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useDownloadWorkflow.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useLoadWorkflowFromFile.tsx, invokeai/frontend/web/src/features/workflowLibrary/hooks/useSaveWorkflow.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useSaveWorkflowAs.ts, invokeai/frontend/web/src/features/workflowLibrary/store/actions.ts
Add various actions needed for commercial purposes
- Closes #
=> add actions for workflow library

docs/nodes/communityNodes.md
- Adds BriaAI's new 1.4 model for background removal. Far superior results from what I've tested compared to any other BG removal so far: https://github.com/blessedcoolant/invoke_bria_rmbg
=> community node: BriaAI RMBG 1.4

pyproject.toml
These are another minor dep updates that I was able to test without any regressions. This will ensure we are up-to-date again.
The fixes are very minor, probably not noticeable in InvokeAI (at least for diffusers) but it's still good to have them.
This is also to make sure that the RC is releasing with the latest packages to ensure extended testing.
Greetings
- Closes #
=> Minor dep updates for diffusers and numpy

invokeai/app/api/sockets.py, pyproject.toml
Update version of fastapi/socketio and change path of the socketio path to match the new needs in fastapi
- Closes #
=> Upgrade version of fastapi and socketio

invokeai/app/invocations/upscale.py, invokeai/backend/image_util/basicsr/LICENSE, invokeai/backend/image_util/basicsr/__init__.py, invokeai/backend/image_util/basicsr/arch_util.py, invokeai/backend/image_util/basicsr/rrdbnet_arch.py, invokeai/backend/image_util/realesrgan/realesrgan.py, pyproject.toml
`basicsr` has a hard dependency on torchvision <= 0.16 and is unmaintained. Extract the code we need from it and remove the dep.
---
See `invokeai/backend/image_util/basicsr/__init__.py` for details.
- Closes #5108
Upscaling should still work.
=> feat(backend): remove dependency on basicsr

pyproject.toml
Bump pydantic, uvicorn, ruff.
App should still work. These should be low-impact changes, looking at release notes. 
This PR can be merged when approved.
=> chore: bump deps

installer/lib/messages.py
String formatting for a message in the installer was causing errors with Python 3.10/3.11
- Closes #
Run create_installer.sh and test the installer runs as expected - 
[InvokeAI-installer](https://github.com/invoke-ai/InvokeAI/files/14233678/InvokeAI-installer-v3.6.2.zip)
Merge once approved
=> Update installer string formatting

invokeai/frontend/web/src/features/lora/store/loraSlice.ts
=> fix(ui): enable lora when recalling

invokeai/frontend/web/src/common/hooks/useDownloadImage.ts
- Closes # https://github.com/invoke-ai/InvokeAI/issues/5706
=> revert to using fetch to download images to metadata is not stripped

pyproject.toml
This PR updates accelerate to the most recent version.
After some testing, no regressions have been found. This makes sure all deps are as up-to-date as they can be for the next release announced my @Millu on discord.
Greetings and have a nice week.
- Closes #
=> Update accelerate 0.26.1 -> 0.27.2

invokeai/app/invocations/latent.py
=> fix(nodes): fix t2i adapter model loading

invokeai/app/invocations/controlnet_image_processors.py
=> fix: Fix Alpha Channel breaking DWProcessor

docs/nodes/communityNodes.md
Adds the 'latent upscale' community node
=> add latent-upscale to communityNodes.md

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlNetImageProcessed.ts, invokeai/frontend/web/src/common/hooks/useGroupedModelCombobox.ts, invokeai/frontend/web/src/common/hooks/useModelCombobox.ts, invokeai/frontend/web/src/features/embedding/EmbeddingSelect.tsx, invokeai/frontend/web/src/features/lora/components/LoRACard.tsx, invokeai/frontend/web/src/features/lora/components/LoRASelect.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ControlNetModelFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/IPAdapterModelFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/LoRAModelFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/MainModelFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/RefinerModelFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/SDXLMainModelFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/T2IAdapterModelFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/VAEModelFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/types/common.ts, invokeai/frontend/web/src/features/parameters/components/VAEModel/ParamVAEModelSelect.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerModelSelect.tsx, invokeai/frontend/web/src/services/api/endpoints/models.ts, invokeai/frontend/web/src/services/api/types.ts
All model selects (linear & workflow editor) now work to select models.
Model names don't work and there is no migration logic, but technically this does mean `next` is fully functional for generation.
Selecting models should work. 
=> fix(ui): get model selects working across the app

invokeai/frontend/web/tsconfig.node.json, invokeai/frontend/web/vite.config.mts
Fixes the package mode build. Still get craploads of TS errors about inferred types but there's no easy solution to that and it doesn't stop anything from working.
=> fix(ui): fix package build

invokeai/app/invocations/compel.py, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataActions.tsx, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataItem.tsx, invokeai/frontend/web/src/features/lora/components/LoRACard.tsx, invokeai/frontend/web/src/features/nodes/types/common.ts, invokeai/frontend/web/src/features/nodes/types/metadata.ts, invokeai/frontend/web/src/features/parameters/components/VAEModel/ParamVAEModelSelect.tsx, invokeai/frontend/web/src/features/parameters/hooks/useRecallParameters.ts, invokeai/frontend/web/src/features/parameters/types/parameterSchemas.ts, invokeai/frontend/web/src/features/settingsAccordions/components/AdvancedSettingsAccordion/AdvancedSettingsAccordion.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/GenerationSettingsAccordion/GenerationSettingsAccordion.tsx, invokeai/frontend/web/src/services/api/endpoints/models.ts, invokeai/frontend/web/src/services/api/hooks/useSelectedModelConfig.ts, invokeai/frontend/web/src/services/api/index.ts
- Display model names in the UI
- TIs have an issue still https://discord.com/channels/1020123559063990373/1149513647022948483/1209770616786260018
- Fix metadata recall (validating against key)
- Also add validation to recalling main model and VAE (this wasn't validated before)
=> fix(ui): use model names

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/bulkDownload.tsx
Instead of auto-downloading the zip, the toast has a link. You can save as to save it wherever you want and with whatever name you want.
- Closes #5757
Try it out
This PR can be merged when approved by @blessedcoolant
=> feat(ui): bulk download click to download

.github/workflows/mkdocs-material.yml
Bit of a merge of the docs at https://github.com/squidfunk/mkdocs-material/blob/master/docs/publishing-your-site.md and the previous workflow.
Not sure how to test this without access to the main repo.
This PR can be merged when approved. If it doesn't work, will need to follow up.
Check that it actually builds and deploys the docs.
=> ci: update mkdocs workflow

pyproject.toml
Hello everyone,
I see that a bulk of the rework for 4.0 is done, and I started testing dependencies updates. Transformers updated to a new version. No regression found so far. I tested it on 3.7.0 and 4.0 (build on main by me).
Should be good to be merged.
Greetings
- Closes #
=> Update Transformers 4.37.2 -> 4.38.2

invokeai/frontend/web/src/services/api/endpoints/images.ts
bugfix for endpoint to get workflow off image
- Closes #
=> fix(ui): fix URL for get image workflow

invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelView.tsx
* default settings should only be shown on main models
- Closes #
=> fix(ui): only show default settings on main models

invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelConvertButton.tsx
Only show button to convert model if its a ckpt
- Closes #
=> fix(ui): only render convert button if ckpt model

docs/features/CONFIGURATION.md, docs/features/DATABASE.md, invokeai/app/services/config/config_default.py, mkdocs.yml
Docs updates for v4.0.0rc1. See commit messages.
=> docs: update docs

pyproject.toml
- `fastapi-events`: 0.10.1 -> 1.11.0
- `fastapi`: 0.109.2 -> 0.110.0
- `pydantic-settings`: 2.1.0 -> 2.2.1
- `pydantic`: 2.6.1 -> 2.6.3
- `uvicorn`: 0.27.1 -> 0.28.0
App still runs, socket events work.
=> chore: bump app deps

.github/workflows/release.yml
ci: add missing permission to release workflow
=> ci: add missing permission to release workflow

invokeai/app/invocations/controlnet_image_processors.py, invokeai/backend/image_util/depth_anything/__init__.py
Was merged into next but never carried over to main. So cleaning up again.
=> chore: cleanup DepthAnything code

invokeai/frontend/web/public/locales/en.json
Calling the workflows tab "Workflow editor" when the default view is the linear ui, with another button to actually get to the editor doesn't make a lot of sense. Let's just call that view "Workflows".
- Closes #
=> feat: :pencil2: rename "Workflow Editor" tab label to "Workflows"

invokeai/app/services/config/config_default.py, invokeai/app/services/model_install/model_install_default.py, invokeai/backend/model_hash/model_hash.py, invokeai/backend/model_manager/probe.py, scripts/probe-model.py, tests/test_model_hash.py
BLAKE3 has poor performance on spinning disks when parallelized. See https://github.com/BLAKE3-team/BLAKE3/issues/31
- Replace `skip_model_hash` setting with `hashing_algorithm`. Any algorithm we support is accepted.
- Add `random` algorithm: hashes a UUID with BLAKE3 to create a random "hash". Equivalent to the previous skip functionality.
- Add `blake3_single` algorithm: hashes on a single thread using BLAKE3, fixes the aforementioned performance issue
- Update model probe to accept the algorithm to hash with as an optional arg, defaulting to `blake3`
- Update all calls of the probe to use the app's configured hashing algorithm
- Update an external script that probes models
- Update tests
- Move ModelHash into its own module to avoid circuclar import issues
- Closes #5938
There should …
=> feat(mm): faster hashing for spinning disk HDDs

invokeai/frontend/install/model_install.py
There was a check for the existence of a `models.yaml` file in the command-line script `invokeai-model-install`, which was invalidated in the shift MM to MM2. This updates the check to work properly with MM2.
- Closes #5932
=> Restore ability to install models from command line

docs/features/CONFIGURATION.md
Update model hashing docs
Update model hashing docs
=> docs: update CONFIGURATION.md

invokeai/app/services/model_install/model_install_default.py
- [] No, because:
The recent change to using absolute paths for all installed models resulted in an inability to permanently delete any models that had legacy relative paths in the database. The user would delete the model using the web interface, but the model would not be removed from disk, even though it resided in the `models` directory.
This fixes the problem, and works for both relative and absolute model paths.
- Closes #
Find a model that still uses relative addressing in the database (there should be many). Attempt to delete it in the model manager UI. Check that it is deleted from disk.
Repeat with a model installed with an absolute path (you may need to install a new one).
=> Allow removal of models with legacy relative path addressing

.github/pull_request_template.md
Updates the PR template... _to the template I am using right now!_
n/a
You're doing it!
n/a
=> gh: update pr template

invokeai/app/invocations/compel.py, invokeai/app/invocations/controlnet_image_processors.py, invokeai/app/invocations/cv.py, invokeai/app/invocations/facetools.py, invokeai/app/invocations/image.py, invokeai/app/invocations/infill.py, invokeai/app/invocations/ip_adapter.py, invokeai/app/invocations/latent.py, invokeai/app/invocations/math.py, invokeai/app/invocations/metadata.py, invokeai/app/invocations/model.py, invokeai/app/invocations/noise.py, invokeai/app/invocations/param_easing.py, invokeai/app/invocations/primitives.py, invokeai/app/invocations/prompt.py, invokeai/app/invocations/sdxl.py, invokeai/app/invocations/strings.py, invokeai/app/invocations/t2i_adapter.py, invokeai/app/invocations/tiles.py, invokeai/app/invocations/upscale.py
Bump all nodes in prep for v4.0.0.
=> chore: bump nodes versions

invokeai/version/invokeai_version.py
=> chore: v4.0.0rc3

invokeai/backend/model_hash/model_hash.py
Use `tqdm` to display progress when hashing models.
https://github.com/invoke-ai/InvokeAI/assets/4822129/ec02f5ed-380d-45d4-ba20-77d5a4b452a5
N/A
N/A
N/A
=> feat(mm): display progress when hashing files

invokeai/version/invokeai_version.py
Bumps version to v4.0.0rc5
This should only merge after these:
- #6027
- #6028
- #6029
N/A
After merging, tag the release, publish to PyPi and update the github release.
=> chore: v4.0.0rc5

invokeai/app/services/model_install/model_install_default.py
If a user has created a symlink within the `models` directory, this allows the symlink to be deleted from the model manager UI.
Closes #6034 
=> allow deletion of symlinked models in models dir

pyproject.toml
Hello everyone,
this PR Updates transformers from 4.38.2 -> 4.39.1
and a minor diffusers update from 0.27.0 -> 0.27.2
Both been tested and working on my setup.
Greetings
=> Update transformers and diffusers

README.md, docs/index.md, docs/installation/020_INSTALL_MANUAL.md, docs/installation/INSTALL_TROUBLESHOOTING.md, installer/install.bat.in, installer/lib/messages.py, installer/templates/invoke.sh.in
- Remove `MALLOC_MMAP_THRESHOLD_` env var. Per testing in #6007 this can cause performance issues, and the benefit of it is marginal for most users.
- Update documentation for this change.
- Fix incorrect troubleshooting documentation links
Supersedes #6047
Closes #6007
Use @RyanJDick 's troubleshooting methodology to test the impact of the change.
N/A
=> feat(mm): remove `MALLOC_MMAP_THRESHOLD_` env var

invokeai/version/invokeai_version.py
=> chore: v4.0.0rc6

installer/lib/installer.py
- Restore installation successful message (was previously part of the configure script)
N/A
N/A
N/A
=> fix(installer): restore install successful message

installer/lib/installer.py
=> chore: ruff

docs/installation/INSTALL_DEVELOPMENT.md
Fix a broken link
https://discord.com/channels/1020123559063990373/1049495067846524939/1224970148058763376
n/a
n/a
=> docs: fix broken link

invokeai/frontend/web/src/services/api/endpoints/queue.ts
Fix the cancel batch button not working. Confirmed no other instances of same root cause
Closes #6110
Queue a large back and confirm the cancel button works
n/a
=> fix(ui): cancel batch status button greyed out

invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelManagerPanel/ModelListItem.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/Model.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelAttrView.tsx
fix(ui): fix model name overflow
https://github.com/invoke-ai/InvokeAI/assets/4822129/90f55f28-a465-4c5a-895d-f464436f5f11
Closes #3897
Rename a model to something really long (this won't be possible until #6113 is merged - can just shrink the window down quite a bit instead).
n/a
=> fix(ui): fix model name overflow

docs/installation/020_INSTALL_MANUAL.md
remove refs to conda
n/a
n/a
n/a
=> docs: update 020_INSTALL_MANUAL.md, remove conda section

invokeai/frontend/web/src/features/ui/store/uiSlice.ts
update "Load Workflow" to navigate to the workflow/nodes tab
1. generate an image with a workflow
2. right click image and click "load workflow"
3. arrive at the workflow tab
=> navigate to workflow tab when clicking load workflow

invokeai/invocation_api/__init__.py
title
https://discord.com/channels/1020123559063990373/1130288930319761428/1225848441788170341
=> fix(nodes): add WithBoard to public API

pyproject.toml
Hello everyone,
This PR updates the following dependencies:
Accelerate 0.28.0 -> 0.29.2
Huggingface_Hub 0.21.4 -> 0.22.2
Torch 2.2.1 -> 2.2.2
Torchvision 0.17.1 -> 0.17.2
Transformers 4.39.1 -> 4.39.3
xFormers 0.0.25 -> 0.0.25post1
Greetings
No regressions found in my testing. These are just minor updates, nothing should break.
=> Update deps to their lastest versions

invokeai/app/services/model_install/model_install_default.py
This PR addresses intermittent test failures in the `test_huggingface_download` unit test of `test_model_install.py`. 
_Details_: During a multi-file download the installer adds a record of the file being downloaded to a data structure of pending downloads and then submits the job to the download queue. When the download job finishes it records that the download is done. The installer checks that all the pending downloads are done, and if so continues with the install process.
There was a race condition that would occur when download jobs submitted early in the process completed before all the later jobs were submitted. This only happens in the test environment where a mock URL requests object is being used and downloads complete almost instantaneously. The fix was to update the data …
=> [mm] Fix race condition when installing multi-file models

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlAdapters/components/parameters/ParamControlAdapterIPMethod.tsx
Update dropdown label to be appended with `(Beta)`
=> update IP adapter method labels to be designated as Beta

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/components/InformationalPopover/constants.ts, invokeai/frontend/web/src/features/controlAdapters/components/parameters/ParamControlAdapterIPMethod.tsx
Fine to merge. Unless there needs a help documentation to be made. Can do once the feature is not marked as beta.
=> fix: IP Adapter Method having incorrect informational popover

invokeai/backend/model_manager/starter_models.py
=> fix: update ip adapter starter models path

invokeai/app/services/download/download_default.py
`PC_PATH_MAX` doesn't exist for (some?) external drives on macOS. We need error handling when retrieving this value.
Also added error handling for `PC_NAME_MAX` just in case. This does work for me for external drives on macOS, though.
Closes #6277
Download a model to an external drive on macOS.
n/a
=> feat(mm): handle PC_PATH_MAX on external drives on macOS

invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasOutpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasSDXLOutpaintGraph.ts
In unscaled situations. Addressing this issue: https://discord.com/channels/1020123559063990373/1020123559831539744/1240034446606995456
=> fix: Fix Outpaint not applying the expanded mask correctly

docs/installation/010_INSTALL_AUTOMATED.md
=> docs: fix install reqs link

invokeai/frontend/web/src/features/nodes/util/graph/generation/addSDXLLoRAs.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildGenerationTabSDXLGraph.ts, invokeai/frontend/web/src/features/parameters/components/Advanced/ParamClipSkip.tsx, invokeai/frontend/web/src/features/parameters/types/constants.ts
#6378 was merged prematurely, my fault for not marking it a draft and being clearer in the PR description.
The intention was for technical users to test the functionality and figure out if this should be exposed in linear. The current consensus is no. Reverting this so we can release without introducing a broken feature.
Reverts #6378
Related #4583
n/a
n/a
=> revert(ui): SDXL clip skip

invokeai/app/services/events/events_base.py, invokeai/app/services/session_processor/session_processor_default.py
Adds an optional `user_id` and `project_id` to error payload for commercial purposes
Should have no OSS impact
=> feat(worker): add nullable user_id and project_id to invocation error events

docs/installation/020_INSTALL_MANUAL.md
=> docs: fix link to. install reqs

invokeai/frontend/web/src/features/controlLayers/components/RGLayer/RGLayerNegativePrompt.tsx, invokeai/frontend/web/src/features/controlLayers/components/RGLayer/RGLayerPositivePrompt.tsx, invokeai/frontend/web/src/features/parameters/components/Core/ParamNegativePrompt.tsx, invokeai/frontend/web/src/features/parameters/components/Core/ParamPositivePrompt.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLPrompts/ParamSDXLNegativeStylePrompt.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLPrompts/ParamSDXLPositiveStylePrompt.tsx
Restore spellcheck on the prompt boxes
n/a
n/a
n/a
=> feat(ui): restore spellcheck on prompt boxes

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/components/AppErrorBoundaryFallback.tsx
Update the UI error boundary to link to creating a support ticket if not a local user
=> Update error boundary to link to support ticket for non-local 

installer/templates/invoke.bat.in, installer/templates/invoke.sh.in
fix: remove db maintenance script from launcher
It is broken and the contributor who was maintaining it has not had time to fix it.
#6188
#6103
n/a
Will need to do a release to get this out.
=> fix: remove db maintenance script from launcher

invokeai/app/api/routers/images.py
I set these to warn during testing and neglected to undo the change.
https://discord.com/channels/1020123559063990373/1149506274971631688/1242948082484641832
n/a
n/a
=> feat(api): downgrade metadata parse warnings to debug

invokeai/frontend/web/src/features/nodes/util/graph/generation/addControlLayers.ts
Whoops!
https://discord.com/channels/1020123559063990373/1049495067846524939/1243186572115837009
- Generate w/ initial image layer
n/a
=> fix(ui): initial image layers always ignored

invokeai/version/invokeai_version.py
=> chore: v4.2.3

invokeai/frontend/web/public/locales/en.json
minor translation fix
https://discord.com/channels/1020123559063990373/1054129386447716433/1243849211053735949
n/a
n/a
=> fix(ui): parameter not set translation

invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelEdit.tsx
only main models have a variant field
Closes #6444
- Edit a LoRA. There should be no `variant` field and you should be able to change the base model.
n/a
=> fix(ui): edit variant for main models only

docs/help/FAQ.md
add FAQ for fixing controlnet_aux
Closes #6112
Closes #6457
n/a
Once merged, we should direct users who have issues with this package to this FAQ.
=> docs: add FAQ for fixing controlnet_aux

invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts
=> fix sort order

.github/actions/install-frontend-deps/action.yml
Fixes front-end test failures in CI.
Merge at will.
=> Update pnpm github action

.github/pull_request_template.md
This PR tweaks the wording of the PR template QA instructions with the goals of:
1. Make it more clear that PR authors are responsible for testing their PRs.
2. Encouraging sufficient detail in the test descriptions.
=> Update the PR template QA instructions

invokeai/app/services/workflow_records/default_workflows/ESRGAN Upscaling with Canny ControlNet.json, invokeai/app/services/workflow_records/default_workflows/Face Detailer with IP-Adapter & Canny (See Note in Details).json, invokeai/app/services/workflow_records/default_workflows/Multi ControlNet (Canny & Depth).json, invokeai/app/services/workflow_records/default_workflows/MultiDiffusion SDXL (Beta).json, invokeai/app/services/workflow_records/default_workflows/Prompt from File.json, invokeai/app/services/workflow_records/default_workflows/Text to Image - SD1.5.json, invokeai/app/services/workflow_records/default_workflows/Text to Image - SDXL.json, invokeai/app/services/workflow_records/default_workflows/Text to Image with LoRA.json, invokeai/app/services/workflow_records/default_workflows/Tiled Upscaling (Beta).json, invokeai/backend/image_util/lineart_anime.py
- Update all existing defaults
- Add Tiled MultiDiffusion workflow
n/a
n/a
n/a
=> chore: update default workflows

invokeai/version/invokeai_version.py
chore: bump version to 4.2.6post1
n/a
n/a
I will do a release once this and #6624 are merged.
=> chore: bump version to 4.2.6post1

invokeai/backend/model_manager/starter_models.py
Adds `xinsir/controlnet-tile-sdxl-1.0` to starter models
=> add sdxl tile to starter models

invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsMenu.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsUpsellMenuItem.tsx
Fix settings menu layout issues
n/a
Before:
After:
https://github.com/user-attachments/assets/61b39399-4b56-44fa-9650-c0cfabb77140
n/a
=> fix(ui): settings menu layout

invokeai/frontend/web/pnpm-lock.yaml
#6645 inadvertently removed the lockfile
n/a
UI should build using lockfile
n/a
=> fix(ui): restore pnpm-lock.yaml

invokeai/version/invokeai_version.py
chore: bump version v4.2.7rc1
n/a
n/a
Will do the release after
=> chore: bump version v4.2.7rc1

invokeai/backend/lora.py
Unfortunately I broke LoKR in latest refactor, so here fix for it.
Also added support for normal layers.
Lora to test: https://civitai.com/models/505411
My result:
https://discord.com/channels/1020123559063990373/1149510134058471514/1270176777238614036
\-
\-
=> LyCORIS - LoKR and Norm layers

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml
Recent dep bump broke a lot of stuff in subtle but mysterious ways. Was `framer-motion`. Fixed upstream in `@invoke-ai/ui-library`.
n/a
n/a
n/a
=> fix(ui): combobox scroll

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/gallery/components/Gallery.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGalleryContent.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/UpscaleSettingsAccordion.tsx
Add translation for this:
Translation-friendly styling for these:
https://discord.com/channels/1020123559063990373/1054129386447716433/1274390457698488461
n/a
n/a
=> fix(ui): translation fixes

invokeai/version/invokeai_version.py
chore: bump version v4.2.9post1
N/A
N/A
N/A
=> chore: bump version to v4.2.9rc1

invokeai/version/invokeai_version.py
=> chore: 4.2.9rc2 version bump

invokeai/frontend/web/src/features/controlLayers/components/CanvasAddEntityButtons.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasEntityList/CanvasEntityList.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasEntityList/EntityListGlobalActionBarAddLayerMenu.tsx, invokeai/frontend/web/src/features/ui/components/VerticalNavBar.tsx
Update order of layers to match the option displayed in menu
=> fix(ui): map order of layer types to the menu order

invokeai/backend/flux/denoise.py
Fix progress image when inpainting with FLUX
=> fix(worker): fix progress image for FLUX inpainting

invokeai/frontend/web/src/index.ts
=> export hotkeys modal

invokeai/frontend/web/src/features/gallery/hooks/useGalleryNavigation.ts
Revert change to grid calculation algorithm that locks up the UI
=> fix(ui): revert change to grid calc algorithm

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/ui/components/CanvasV2Announcement.tsx, invokeai/frontend/web/src/features/ui/components/Notifications.tsx, invokeai/frontend/web/src/features/ui/components/VerticalNavBar.tsx, invokeai/frontend/web/src/features/ui/store/uiSlice.ts, invokeai/frontend/web/src/features/ui/store/uiTypes.ts
Adds a lightning bulb "What's New" to side navigation, with an indicator badge for if you not yet clicked on it. Popover contains details on new releases.
Links in popover will change before 5.0 stable release
=> feat(ui): "What's New" in side nav with indicator badge

invokeai/frontend/web/src/features/controlLayers/components/CanvasEntityList/EntityListSelectedEntityActionBarFill.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolBboxButton.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolBrushButton.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolColorPickerButton.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolEraserButton.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolFillColorPicker.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolMoveButton.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolRectButton.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolViewButton.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolModule.ts, invokeai/frontend/web/src/features/system/components/HotkeysModal/useHotkeyData.ts
=> UI fixes followup

invokeai/frontend/web/src/features/controlLayers/konva/CanvasBackgroundModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts, invokeai/frontend/web/src/features/controlLayers/konva/util.ts
Hopefully fixes `TaintedCanvas` issues.
n/a
@ebr Can you test this?
n/a
=> fix(ui): set crossOrigin on every image load

invokeai/frontend/web/src/features/gallery/components/GalleryHeader.tsx, invokeai/frontend/web/src/features/gallery/components/GalleryPanelContent.tsx
Align project name with gallery header
=> fix(ui): align project name with gallery header

invokeai/frontend/web/src/features/ui/components/Notifications.tsx, invokeai/frontend/web/src/features/ui/store/uiSlice.ts, invokeai/frontend/web/src/features/ui/store/uiTypes.ts
open notification by default, get rid of indicator
=> tweak(ui): open notification by default, get rid of indicator

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterMethod.tsx, invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbar.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/useCanvasFilterHotkey.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/useCanvasTransformHotkey.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolModule.ts, invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts, invokeai/frontend/web/src/features/metadata/util/handlers.ts, invokeai/frontend/web/src/features/system/components/HotkeysModal/useHotkeyData.ts
Misc fixes/features. See commits, nothing big.
n/a
n/a
n/a
=> fix, feat: canvas followups 14

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/parameters/components/Advanced/ParamOptimizedDenoisingToggle.tsx
Mark optimized inpainting setting as beta
=> fix(ui): mark optimized inpainting as beta

invokeai/app/api/routers/app_info.py
change order of infill methods
=> change order of infill methods

invokeai/frontend/web/src/features/controlLayers/store/paramsSlice.ts, invokeai/frontend/web/src/features/modelManagerV2/hooks/useMainModelDefaultSettings.ts, invokeai/frontend/web/src/features/nodes/util/schema/buildFieldInputInstance.ts, invokeai/frontend/web/src/features/nodes/util/schema/buildFieldInputTemplate.ts, invokeai/frontend/web/src/features/system/store/configSlice.ts
update default scheduler to dpmpp_3m_k
=> update default scheduler to dpmpp_3m_k

invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts
So close, yet so far away.
n/a
Use arrow keys in gallery
n/a
=> fix(ui): gallery nav hotkeys not working

invokeai/frontend/web/src/features/controlLayers/konva/CanvasStageModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolModule.ts
As part of resolving merge conflicts in #7007, I noticed two issues:
1. The MMB panning didn't work with `pointer` events, but we need to use them for tablet support.
2. There was also an edge case where if the tool was changed mid-MMB drag, the drag event didn't stop so it couldn't clean up after itself.
As I was troubleshooting 1) and looking at Konva's GH, I was reminded of the simpler way to implement MMB panning (as seen in this PR). I had tried approach a while ago but couldn't get it to work. Of course, the problem was (mostly) my own code.
There were two challenges:
- Konva's [docs say that the default drag buttons for _all_ drag events is primary mouse](https://konvajs.org/api/Konva.html#.dragButtons), but this isn't true. The actual default is [primary OR …
=> feat(ui): mmb panning (another approach)

invokeai/version/invokeai_version.py
chore: bump version to v5.1.0rc2
n/a
n/a
I will do the release
=> chore: bump version to v5.1.0rc2

docs/nodes/communityNodes.md
Added an Ollama Node to the community nodes
Added an Ollama node to the community nodes list. This node communicates with a local Ollama API to expand basic prompts into detailed natural language prompts using local LLMs. Provides a toggle to immediately unload LLM model after expansion to free up VRAM for Invoke.
=> Update communityNodes.md add Ollama node

invokeai/frontend/web/public/locales/en.json
fix(ui): incorrect hotkeys on floating button tooltips
Discord: https://discord.com/channels/1020123559063990373/1149506274971631688/1291653440786792511
n/a
n/a
=> fix(ui): incorrect hotkeys on floating button tooltips

invokeai/version/invokeai_version.py
chore: bump version to v5.1.0rc4
n/a
n/a
release after
=> chore: bump version to v5.1.0rc4

invokeai/version/invokeai_version.py
chore: bump version to v5.1.0rc5
n/a
n/a
n/a
=> chore: bump version to v5.1.0rc5

README.md
Adds FLUX to the list of supported models.
=> docs: list FLUX as supported

docs/contributing/INVOCATIONS.md, docs/contributing/LOCAL_DEVELOPMENT.md, docs/contributing/contribution_guides/development.md, docs/contributing/contribution_guides/tutorials.md
Hello
I fixed several spelling issues.
Br,e Elias.
=> Docs fix spelling issues

invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardEditableTitle.tsx
- Minor styling tweak
- Fix edge case w/ hover state 
n/a
n/a
n/a
=> feat(ui): board edit tweaks

invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/ActiveWorkflow.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowName.tsx
=> add missing translations

invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceMenuItemsAddPromptsAndIPAdapter.tsx, invokeai/frontend/web/src/features/controlLayers/components/common/CanvasEntityDeleteButton.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx
Missed a few spots in #7048, not sure how/why but the revert didn't catch em.
https://discord.com/channels/1020123559063990373/1149513625321603162/1293359632504590438
n/a
n/a
=> fix(ui): remove straggling onPointerUp handlers

invokeai/frontend/web/src/features/nodes/hooks/useCopyPaste.ts
Add validation when pasting edges. Uses the same validation logic as normal edge connections. A warning is logged if a pasted edge is invalid.
Closes #7058
Try the simple test cases:
- Copy & paste a source node and edge from the source node to a target node. The target field should only accept single connections.
- Copy & paste a source node and edge from the source node to a target node. The target field should accept multiple connections.
Video demonstrating the test cases:
https://github.com/user-attachments/assets/831c7d73-fa1d-483a-977c-8b3834e428e2
n/a
=> fix(ui): validate edges on paste

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/CopyWorkflowLinkModal.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/WorkflowListItem.tsx, invokeai/frontend/web/src/features/nodes/hooks/useCopyWorkflowLinkModal.ts
add option to copy share link for workflows if projectURL is defined (commercial)
=> feat(ui): add option to copy share link for workflows

invokeai/frontend/web/vite.config.mts
build(ui): set package mode target to ES2015
n/a
n/a
n/a
=> build(ui): set package mode target to ES2015

invokeai/app/api/routers/boards.py, invokeai/app/services/board_records/board_records_base.py, invokeai/app/services/board_records/board_records_common.py, invokeai/app/services/board_records/board_records_sqlite.py, invokeai/app/services/boards/boards_base.py, invokeai/app/services/boards/boards_default.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/changeBoardModal/components/ChangeBoardModal.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsListSortControls.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsSettingsPopover.tsx, invokeai/frontend/web/src/features/gallery/components/Gallery.tsx, invokeai/frontend/web/src/features/gallery/components/GalleryPanelContent.tsx, invokeai/frontend/web/src/features/gallery/components/GallerySettingsPopover/GallerySettingsPopover.tsx, invokeai/frontend/web/src/features/gallery/store/gallerySelectors.ts, invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts, invokeai/frontend/web/src/features/gallery/store/types.ts, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/BoardFieldInputComponent.tsx, invokeai/frontend/web/src/services/api/hooks/accessChecks.ts, invokeai/frontend/web/src/services/api/hooks/useBoardName.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts
Adds API and UI for sorting boards by either created date or name, ascending or descending.
Also splits out board settings from image gallery settings!
Closes https://github.com/invoke-ai/InvokeAI/issues/7079
Closes https://github.com/invoke-ai/InvokeAI/issues/6757
=> feat(ui,api): board sorting

invokeai/version/invokeai_version.py
chore: bump version to v5.2.0rc2
n/a
n/a
I will do a release.
=> chore: bump version to v5.2.0rc2

invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/ShareWorkflowModal.tsx
fix(ui): remove extra slash in workflow share link
=> fix(ui): remove extra slash in workflow share link

invokeai/app/services/image_files/image_files_disk.py, tests/app/services/image_files/test_image_files_disk.py
fix(app): directory traversal when deleting images
n/a
n/a
n/a
=> fix(app): directory traversal when deleting images

invokeai/backend/model_manager/starter_models.py
add starter model Architecture (RealVisXL5)
=> add starter model Architecture (RealVisXL5)

invokeai/version/invokeai_version.py
chore: bump version to v5.3.0rc2
n/a
n/a
Release after merging.
=> chore: bump version to v5.3.0rc2

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/ui/components/Notifications.tsx, invokeai/frontend/web/src/features/ui/components/WhatsNew.tsx, invokeai/frontend/web/src/features/ui/store/uiSlice.ts, invokeai/frontend/web/src/features/ui/store/uiTypes.ts
* Update `WhatsNew` component to be more generic
* Enable us to reset the ui state that tracks if someone has closed this so that it shows again when it changes
* Update non-local implementation to pull from back-end
=> feat(ui): update announcements for v5.3.0

invokeai/frontend/web/src/features/controlLayers/konva/CanvasCompositorModule.ts
=> fix(ui): compositor not setting processing flag when cleaning up

docs/contributing/contribution_guides/newContributorChecklist.md
=> Fix link in dev docs

invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterBase.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasProgressImageModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStateApiModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasMoveToolModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolModule.ts
Fixes:
- Layers not visible when exiting staging
- Flash of canvas stage between last progress image and generation output in staging area
- Cursor disappearing w/ move tool on empty layers
- Able to move layers while staging
Try to repro the issues
n/a
=> fix(ui): canvas misc bugs

invokeai/frontend/web/src/common/components/InformationalPopover/constants.ts
fix link for infill method popover
=> fix(ui): fix link for infill method popover

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/ui/components/WhatsNew.tsx
Update What's New for v5.3.1 features
=> update Whats New for 5.3.1

invokeai/frontend/web/src/features/ui/components/WhatsNew.tsx
fix typo from bad merge conflict
=> fix(ui): bad merge conflict

.github/pull_request_template.md
chore(gh): update pr template w/ reminder for what's new copy
=> chore(gh): update pr template w/ reminder for what's new copy

invokeai/backend/model_manager/config.py
Just stops the warning
Closes #7287
n/a
n/a
=> fix(app): silence pydantic protected namespace warning

invokeai/version/invokeai_version.py
chore: bump version to v5.4.1rc2
Do the release after
=> chore: bump version to v5.4.1rc2

invokeai/frontend/web/src/features/dnd/FullscreenDropzone.tsx
Missed migrating this logic over during dnd migration.
https://discord.com/channels/1020123559063990373/1149506274971631688/1304273883158941696
Paste an image or images, should work like it did before.
=> fix(ui): restore missing image paste handler

invokeai/frontend/web/src/features/parameters/util/optimalDimension.ts
fix(ui): add sd-3 grid size of 16px to grid util
Via @dunkeroni: https://discord.com/channels/1020123559063990373/1020123559831539744/1308205082017402950
=> fix(ui): add sd-3 grid size of 16px to grid util

invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/features/controlLayers/components/CanvasAlerts/CanvasAlertsInvocationProgress.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx
* do not show the setting for progress details if not local, and update component to always display non-local UI
=> fix(ui): simplify logic for non-local invocation progress alerts

invokeai/frontend/web/src/features/controlLayers/store/paramsSlice.ts
feat(ui): set default infill method to lama
n/a
n/a
=> feat(ui): set default infill method to lama

invokeai/frontend/web/src/features/system/components/VideosModal/VideoCard.tsx, invokeai/frontend/web/src/features/system/components/VideosModal/VideosModal.tsx, invokeai/frontend/web/src/features/system/components/VideosModal/VideosModalButton.tsx, invokeai/frontend/web/src/features/system/store/actions.ts
add actions for video modal clicks
=> feat(ui): add actions for video modal clicks

docs/contributing/index.md
Commit d27392cc2d9c4ac2ab2b9dd1703cc969daf85884 moved the code of conduct to `docs`. This PR adjusts sources to changes.
=> docs: update code of conduct reference

invokeai/app/invocations/flux_denoise.py, invokeai/app/invocations/flux_text_encoder.py
Updated node versions since fields changed.
https://discord.com/channels/1020123559063990373/1083864753543331981/1312275195486011468
=> Update node vers

invokeai/app/api/routers/session_queue.py
=> fix(app): adjust session queue api type

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewLayerFromImageSubMenu.tsx
Appears these actions disappeared at some point. Restoring them.
n/a
n/a
=> feat(ui): add gallery image ctx menu items to create ref image from image

invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsLanguageSelect.tsx, invokeai/frontend/web/src/features/system/store/types.ts
feat(ui): add vietnamese to language picker
Closes #7384
n/a
n/a
=> feat(ui): add vietnamese to language picker

invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsLanguageSelect.tsx
fix(ui): capitalization for vietnamese language
https://discord.com/channels/1020123559063990373/1054129386447716433/1313622278801588236
n/a
n/a
=> fix(ui): capitalization for vietnamese language

invokeai/frontend/web/public/locales/en.json
Add a missing translation string
Reported by @Linos1391 in https://discord.com/channels/1020123559063990373/1054129386447716433/1314777618108907572
n/a
n/a
=> fix(ui): missing translation string

invokeai/backend/model_manager/config.py, invokeai/backend/model_manager/load/model_loaders/lora.py, invokeai/backend/model_manager/probe.py
Add diffusers config object for control loras
=> Add diffusers config object for control loras

invokeai/app/invocations/flux_denoise.py
Raise a user-friendly error message if Control LoRAs are used with schnell model
=> raise error if control lora used with schnell

invokeai/frontend/web/public/locales/en.json
update whats new copy for Control LoRAs
=> update whats new copy for Control LoRAs

invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts
`schema.ts` is outdated due to recent changes.
=> chore(ui): update typegen schema

invokeai/version/invokeai_version.py
chore: bump version to v5.5.0rc1
n/a
n/a
I'll do the release
=> chore: bump version to v5.5.0rc1

mkdocs.yml
=> docs: fix installation docs home

mkdocs.yml
Fix the docs installation home link.
My last fix didn't do what I thought it did, whoops!
=> docs: fix installation docs home again

docs/installation/quick_start.md
Update the download links for the launcher now that it has been renamed to `Invoke Community Edition`.
Closes #7484
n/a
n/a
=> docs: update download links for launcher

docs/nodes/communityNodes.md
Add Stereogram community nodes to the InvokeAI documentation.
=> Add Stereogram Nodes to communityNodes.md

invokeai/frontend/web/src/common/components/InformationalPopover/constants.ts
The link on scale before processing was broken. This fixes it.
Discord. 
Hover over it. It should have a valid link.
Merge at will.
=> Correct Scale Informational Popover 

docs/contributing/dev-environment.md, docs/installation/manual.md
Don't need to specify version when doing an editable install. Caught by @JPPhoto - ty!
=> docs: no need to specify version for dev env setup

invokeai/app/invocations/constants.py
Follow-up fix for https://github.com/invoke-ai/InvokeAI/pull/7464
=> fix(app): remove obsolete DEFAULT_PRECISION variable

docs/installation/quick_start.md
docs: fix incorrect macOS launcher fix command
=> docs: fix incorrect macOS launcher fix command

invokeai/version/invokeai_version.py
chore: bump version to v5.6.0rc2
=> chore: bump version to v5.6.0rc2

invokeai/version/invokeai_version.py
chore: bump version to v5.6.0rc3
To be merged only after pending improvements to memory mgmt on Windows are merged. Then release RC3.
=> chore: bump version to v5.6.0rc3

invokeai/version/invokeai_version.py
Want to get #7567 out as its a really annoying bug.
=> chore: bump version to v5.6.0rc4

docs/installation/manual.md
Thanks to ShaneDK on discord for catching this.
https://discord.com/channels/1020123559063990373/1331410991862382613/1331658957940457492
=> docs: typo in manual docs install command

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/CanvasContextMenu/CanvasContextMenuGlobalMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/saveCanvasHooks.ts, invokeai/frontend/web/src/features/controlLayers/hooks/useCopyLayerToClipboard.ts
- Add menu items to copy the whole canvas or bbox to clipboard
Offline discussion
Try it out
n/a
=> feat(ui): support copy of canvas

invokeai/frontend/web/public/locales/en.json
fix(ui): restore missing translation
=> fix(ui): restore missing translation

docs/faq.md, docs/installation/requirements.md
- Remove outdated info from FAQ
- Update info about VRAM requirements and perf, linking to Low VRAM mode docs where appropriate
Noticed we were due for a quick cleanup when I added the firefox clipboard fix to FAQ.
n/a
Maybe glance over the changes to make sure I haven't removed something that is still relevant.
n/a
=> docs: cleanup faq

invokeai/frontend/web/src/features/toast/ErrorToastDescription.tsx, invokeai/frontend/web/src/services/events/setEventListeners.tsx
Not sure why the component was causing this on re-renders but using a simple function fixes it
=> fix(ui): [object object] in OOM toast

invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardEditableTitle.tsx
fix omnipresent pencil on board name - only show on hover
=> fix(ui): omnipresent pencil on board name

invokeai/frontend/web/public/locales/it.json
Something went sideways in the weblate repo and this change is needed to resolve the conflicts.
https://discord.com/channels/1020123559063990373/1054129386447716433/1342777510869598258
n/a
n/a
=> fix: weblate merge conflict issue

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/app/hooks/useStudioInitAction.ts, invokeai/frontend/web/src/common/components/Loading/Loading.tsx, invokeai/frontend/web/src/features/ui/components/Notifications.tsx
If a studio destination is passed in, do not render studio until everything is loaded
=> fix(ui): do not render studio until destination is loaded

invokeai/frontend/web/src/common/hooks/useCopyImageToClipboard.ts, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemOpenInNewTab.tsx, invokeai/frontend/web/src/features/gallery/store/actions.ts
add actions for copying image and opening image in new tab for use in commercial middleware
=> (ui): add actions for copying image and opening image in new tab

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Notes/NotesNode.tsx
Added same check for existence to notes node that we do for other invocation nodes
=> fix(ui): make sure notes node exists like we do for invocation nodes

invokeai/app/services/bulk_download/bulk_download_default.py, invokeai/app/services/images/images_default.py, invokeai/app/services/shared/invocation_context.py
New args were recently added to `get_all_board_image_names_for_board` but not all uses of that fn were updated
=> fix(api): fix args in other places that use get_all_board_image_names_for_board

invokeai/frontend/web/src/features/deleteImageModal/store/selectors.ts
When deleting a board w/ images, the image usage checking logic was not checking image collection fields. This could result in a nonexistent image lingering in a node.
We already handle single image fields correctly, it's only the image collection fields taht were affected.
n/a
- Add an image to a board
- Create a workflow w/ image collection field
- Add the image to the image collection
- Delete the board & images
On `main`, the image collection node will stick around. With this PR, it will be deleted (the correct behaviour).
n/a
=> fix(ui): image usage checks collection fields

invokeai/app/invocations/metadata.py, invokeai/app/invocations/metadata_linked.py, invokeai/frontend/web/src/services/api/schema.ts
Adopt @skunkworxdark 's popular Metadata nodes into Invoke. Thank you!
https://github.com/skunkworxdark/metadata-linked-nodes
https://discord.com/channels/1020123559063990373/1344452396847206493
n/a
n/a
=> feat(app): adopt metadata linked nodes

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedLinear.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedNodes.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedUpscale.ts
On the Canvas tab, when we made the network request to enqueue a batch, we were immediately resetting the request. This effectively disabled RTKQ's tracking of the request - including the loading state.
As a result, when you click the Invoke button on the Canvas tab, it didn't show a spinner, and it was not clear that anything was happening.
The solution is simple - just await the enqueue request before resetting the tracking, same as we already did on the workflows and upscaling tabs.
I also added some extra logging messages for enqueuing, so we get the same JS console logs for each tab on success or failure.
Offline discussion.
Enqueue on canvas tab. You should see a loading spinner as it processes the network request.
n/a
=> fix(ui): invoke button not showing loading indicator on canvas tab

invokeai/version/invokeai_version.py
chore: bump version to v5.7.2rc2
n/a
n/a
I'll do a release
=> chore: bump version to v5.7.2rc2

invokeai/frontend/web/public/locales/en.json
=> fix(ui): typo

.github/CODEOWNERS
repo: add @jazzhaiku to codeowners for CI, app and backend
n/a
n/a
n/a
=> repo: add @jazzhaiku to codeowners for CI, app and backend

invokeai/app/invocations/flux_denoise.py
A Redux field was added but the node version wasn't updated.
Version updated to 3.2.3 which should fix UI errors. Tested locally.
=> Changed version of FluxDenoiseInvocation

invokeai/frontend/web/src/app/store/nanostores/workflowCategories.ts
fix(ui): hide shared on workflow library
n/a
n/a
n/a
=> fix(ui): hide shared on workflow library

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/FormElementEditModeHeader.tsx
fix(ui): missing builder translations
https://discord.com/channels/1020123559063990373/1054129386447716433/1347409432438640712
n/a
n/a
=> fix(ui): missing builder translations

invokeai/app/services/workflow_records/workflow_records_common.py
=> fix(api) add default for opened_at

invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/HeadingElementContent.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/TextElementContent.tsx
fix(ui): respect line breaks in builder text and heading elements
n/a
n/a
=> fix(ui): respect line breaks in builder text and heading elements

invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/ContainerElement.tsx
fix(ui): prevent vertical scrolling on row containers
n/a
n/a
n/a
=> fix(ui): prevent vertical scrolling on row containers

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ImageFieldCollectionInputComponent.tsx
Upload button looked weird without a border.
n/a
n/a
n/a
=> tweak(ui): styling for image collection fields

invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelManagerPanel/ModelTypeFilter.tsx
Fix a misspelled translation key
n/a
n/a
n/a
=> fix(ui): siglip model translation key

invokeai/version/invokeai_version.py
chore: prep for v5.9.0rc2
n/a
n/a
n/a
=> chore: prep for v5.9.0rc2

invokeai/frontend/web/src/features/nodes/components/flow/nodes/common/NodeTitle.tsx
Old:
New:
Offline discussion
n/a
n/a
=> fix(ui): long node titles overflow

invokeai/frontend/web/src/features/controlLayers/components/ParamDenoisingStrength.tsx
feat(ui): disable denoising strength when selected models flux fill
https://discord.com/channels/1020123559063990373/1020123559831539744/1355598033709957422
n/a
n/a
=> feat(ui): disable denoising strength when selected models flux fill

.github/CODEOWNERS
- Add @psychedelicious as codeowner for docs
- Remove inactive contributors
n/a
n/a
n/a
=> gh: update codeowners

invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemComponent.tsx
Fix inverted logic for showing validation run badge
=> fix(ui): fix badge for validation run

invokeai/app/run_app.py
This message was inadvertently removed in #7668.
https://discord.com/channels/1020123559063990373/1049495067846524939/1357940756517486664
n/a
n/a
=> feat(app): restore "Using torch device" message on startup

invokeai/backend/model_manager/load/model_util.py
Model manager can now calculate the sizes of ONNX models. These are used by the DW OpenPose processor.
n/a
n/a
n/a
=> feat(mm): support size calculation for onnx models

invokeai/frontend/web/src/features/controlLayers/hooks/saveCanvasHooks.ts
The `Save Canvas to Gallery` and `Save Bbox to Gallery` buttons now include some basic settings:
- Positive prompt
- Negative prompt
- Seed
- Model (if set)
The rest is a bit complicated to derive as it comes from the graph building process.
To capture the same metadata that would be captured when you click Invoke requires:
- Invoke button is not greyed out due to invalid settings
- Some time to export canvas image state and do calculations on it
- Building the graph
So it's quite a bit of work. Not to mention, this logic is spread throughout the graph builders and helpers. For example, determining LoRAs is in a separate function that requires a partially built graph to even run. 
I think these basic settings will cover the majority of use-cases and does not require a substantial effort …
=> feat(ui): save canvas/bbox to gallery saves basic metadata

docs/contributing/dev-environment.md, docs/installation/manual.md
Update docs for manual/dev install w/ correct pytorch indices
Noted by @JPPhoto on discord: https://discord.com/channels/1020123559063990373/1149506274971631688/1361856453543203028
n/a
n/a
=> docs: update pytorch indices

invokeai/frontend/web/src/common/components/OverlayScrollbars/ScrollableContent.tsx
fix(ui): dnd autoscroll in scrollable containers
n/a
n/a
n/a
=> fix(ui): dnd autoscroll in scrollable containers

invokeai/backend/model_manager/taxonomy.py, invokeai/frontend/web/src/services/api/schema.ts
add gpt-image to possible base model types
=> add gpt-image to possible base model types

invokeai/frontend/web/public/locales/en.json
Fix a typo in a toast
n/a
n/a
n/a
=> fix(ui): toast typo

invokeai/frontend/web/src/features/nodes/util/graph/generation/buildChatGPT4oGraph.ts
send the list of reference images reversed to chatGPT so it matches displayed order
=> send the list of reference images reversed to chatGPT so it matches displayed order

invokeai/frontend/web/src/features/nodes/util/graph/generation/buildImagen3Graph.ts
add prompt validation of at least one character to imagen3 graph
=> add prompt validation of at least one character to imagen3 graph

invokeai/app/services/session_queue/session_queue_common.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemComponent.tsx, invokeai/frontend/web/src/features/queue/components/QueueList/QueueListHeader.tsx, invokeai/frontend/web/src/features/queue/components/QueueList/constants.ts, invokeai/frontend/web/src/features/system/store/configSlice.ts, invokeai/frontend/web/src/services/api/schema.ts
Display credit details in queue list if shouldShowCredits is true
=> display credit column in queue list if shouldShowCredits is true

invokeai/frontend/web/src/features/queue/components/QueueIterationsNumberInput.tsx
use the max for iterations passed in
=> use the max for iterations passed in

invokeai/frontend/web/src/features/queue/components/QueueList/QueueList.tsx
=> refetch queue list on mount

invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/app/store/nanostores/whatsNew.ts, invokeai/frontend/web/src/features/ui/components/WhatsNew.tsx
easier way to override Whats New
=> easier way to override Whats New

invokeai/app/invocations/baseinvocation.py, invokeai/invocation_api/__init__.py
feat(nodes): support bottleneck flag for nodes
=> feat(nodes): support bottleneck flag for nodes

invokeai/app/invocations/baseinvocation.py, invokeai/app/services/session_queue/session_queue_common.py, invokeai/app/services/shared/graph.py
Non-functional change.
n/a
Do a generation and ensure no explosions (it's fine, doesn't explode).
n/a
=> fix(app): address pydantic deprecation warning for accessing `BaseModel.model_fields`

invokeai/app/invocations/metadata.py, invokeai/frontend/web/src/services/api/schema.ts
Add new method types to metadata for IP adapter
=> fix(backend) add new method types to metadata

invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/publish.ts
fix names of unpublishable nodes
=> fix names of unpublishable nodes

invokeai/frontend/web/src/features/lora/components/LoRASelect.tsx, invokeai/frontend/web/src/features/parameters/components/ModelPicker.tsx
convert LoRA picker to use new model picker component
=> convert LoRA picker to use new model picker component

invokeai/frontend/web/src/features/nodes/components/NodeEditor.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/common/NodeWrapper.tsx
Tweak workflow editor styling to match new layout
=> feat(ui): workflows styling tweaks

invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowViewEditToggleButton.tsx
Fixes nav UX inside of the workflows.
When hitting the edit/view button, selects the correct view.
Click the buttons!
Merge when ready.
=> fix(ui):On Edit/View workflow buttons, navigate to the right panel.

invokeai/frontend/web/src/features/controlLayers/store/refImagesSlice.ts
handle flux-kontext reference images when switching bases
=> handle flux-kontext reference images when switching bases

invokeai/frontend/web/src/common/components/SessionMenuItems.tsx
Removes Canvas Session button.
N/A
No buttons
Push when ready
=> fix(ui):Remove Canvas Session button

invokeai/frontend/web/src/features/prompt/PromptExpansion/PromptExpansionOverlay.tsx
=> remove pulsing animation

invokeai/frontend/web/src/features/nodes/util/graph/buildLinearBatchConfig.ts
properly build batch for flux kontext api batches
=> properly build batch for flux kontext api batches

invokeai/frontend/web/src/features/prompt/PromptExpansion/expand.ts, invokeai/version/invokeai_version.py
=> chore: bump version to v6.0.0rc3

invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/publish.ts
add claude nodes to blacklist for publishing
=> add claude nodes to blacklist for publishing

invokeai/frontend/web/src/common/components/Picker/Picker.tsx, invokeai/frontend/web/src/features/parameters/components/ModelPicker.tsx
Model picker selected item is now highlighted in blue like the old picker component.
=> feat(ui): selected item in model picker styling

invokeai/version/invokeai_version.py
chore: bump version to v6.0.0rc5
=> chore: bump version to v6.0.0rc5

invokeai/frontend/web/src/app/components/GlobalImageHotkeys.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewLayerFromImageSubMenu.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImageButtons.tsx, invokeai/frontend/web/src/features/gallery/hooks/useImageActions.ts
dont show option to add new layer from if on generate tab
=> fix(ui): dont show option to add new layer from if on generate tab

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/setDefaultSettings.ts, invokeai/frontend/web/src/features/metadata/parsing.tsx
if on generate tab, recall dimensions instead of bbox
=> if on generate tab, recall dimensions instead of bbox

invokeai/frontend/web/public/locales/en.json
=> update whats new for v6

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/features/gallery/components/NewGallery.tsx, invokeai/frontend/web/src/features/gallery/hooks/useRangeBasedImageFetching.ts, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsLanguageSelect.tsx, invokeai/frontend/web/src/features/system/store/systemSlice.ts, invokeai/frontend/web/src/features/system/store/types.ts, invokeai/frontend/web/src/features/ui/layouts/TabWithLaunchpadIcon.tsx, invokeai/frontend/web/src/features/ui/layouts/TabWithoutCloseButton.tsx, invokeai/frontend/web/src/features/ui/layouts/TabWithoutCloseButtonAndWithProgressIndicator.tsx, invokeai/frontend/web/src/features/ui/layouts/use-hack-out-dv-tab-draggable.ts
- Fix an issue that could result in images getting stuck as placeholders.
- Alter the request frequency and prefetching logic for gallery to reduce network requests during scrolling, but keep the same UX.
- Fix an issue where you could drag a panel tab and end up with stacked panels.
- Fix an issue w/ certain languages hard-crashing the UI.
=> v6 followups 3

invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/QueueItemPreviewMini.tsx, invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/StagingAreaItemsList.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildSDXLGraph.ts
- Staging area images could slightly overflow the vertical space
- Center staging area images liost when there aren't enough to fill the horizontal space
- Native context menu on short and fat gallery images
- SDXL concat not working for negative prompt
n/a
=> fix(ui): assorted niggles

docs/contributing/dev-environment.md
Document the latest changes required to build Invoke 6.0.
Documentation was out of date and referenced old pnpm and nodejs versions. Fixed.
=> Updated docs for 6.0

invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelManagerPanel/ModelImage.tsx, invokeai/frontend/web/src/features/parameters/components/ModelPicker.tsx
* make sure description is legible on selected model item
* add fallback for image if model as cover image URL but image fails to load
=> fix(ui): model picker styling

invokeai/frontend/web/src/features/controlLayers/store/types.ts
fix(ui): aspect ratios out of order
Raised on discord
n/a
n/a
=> fix(ui): aspect ratios out of order

invokeai/frontend/web/src/features/ui/layouts/use-hack-out-dv-tab-draggable.ts
fix(ui): able to drag empty space in tab bar and detach panels
n/a
n/a
n/a
=> fix(ui): able to drag empty space in tab bar and detach panels

invokeai/frontend/web/src/features/nodes/util/graph/generation/buildSDXLGraph.ts
fix(ui): negative style prompt not recorded in metadata
n/a
n/a
n/a
=> fix(ui): negative style prompt not recorded in metadata

invokeai/frontend/web/src/features/nodes/components/sidePanel/inspector/InspectorDetailsTab.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/inspector/InspectorOutputsTab.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/inspector/InspectorTemplateTab.tsx
Fixes a crash when rendering the inspector panel
https://discord.com/channels/1020123559063990373/1149506274971631688/1395449873758687303
n/a
n/a
=> fix(ui): use invocation context provider in inspector panel

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/app/components/GlobalHookIsolator.tsx, invokeai/frontend/web/src/app/components/ThemeLocaleProvider.tsx, invokeai/frontend/web/src/app/hooks/useSyncLangDirection.ts
Workaround to prevent i18n translation errors for crashing the app _and_ get a styled error boundary.
n/a
n/a
n/a
=> fix(ui): unstyled error boundary

invokeai/frontend/web/src/features/nodes/util/graph/buildLinearBatchConfig.ts
fix iterations for all API models
=> fix iterations for all API models

invokeai/frontend/web/src/index.ts
build(ui): export loading component
n/a
n/a
n/a
=> build(ui): export loading component

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/RefImage/RefImageList.tsx, invokeai/frontend/web/src/features/gallery/components/BoardsListPanelContent.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemUseAsRefImage.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/viewMode/EmptyState.tsx, invokeai/frontend/web/src/features/ui/components/VerticalNavBar.tsx, invokeai/frontend/web/src/features/ui/layouts/GenerateLaunchpadPanel.tsx, invokeai/frontend/web/src/features/ui/layouts/LaunchpadAddStyleReference.tsx, invokeai/frontend/web/src/features/ui/layouts/LaunchpadEditImageButton.tsx, invokeai/frontend/web/src/features/ui/layouts/LaunchpadGenerateFromTextButton.tsx, invokeai/frontend/web/src/features/ui/layouts/LaunchpadUseALayoutImageButton.tsx, invokeai/frontend/web/src/features/ui/layouts/UpscalingLaunchpadPanel.tsx, invokeai/frontend/web/src/features/ui/layouts/canvas-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/generate-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/upscaling-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/workflows-tab-auto-layout.tsx
Add some missing translation strings
https://discord.com/channels/1020123559063990373/1054129386447716433/1397131600076083280
n/a
n/a
=> feat(ui): add missing translations

invokeai/version/invokeai_version.py
=> chore: bump version to v6.3.0rc2

invokeai/frontend/web/src/features/nodes/util/graph/generation/buildFluxKontextGraph.ts
fix graph building for flux kontext API multi-image prep
=> fix graph building for flux kontext API multi-image prep

invokeai/backend/model_manager/starter_models.py
Meant to do this ages ago but forgot. 
See https://github.com/invoke-ai/InvokeAI/issues/7814#issuecomment-2787899982 for an explanation of why this change is needed.
Try the new model (works fine for me)
n/a
=> feat(mm): change anime upscaling model to one that doesn't trigger picklescan

invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemMetadataRecallActionsCanvasGenerateTabs.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemMetadataRecallActionsUpscaleTab.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImageButtons.tsx, invokeai/frontend/web/src/features/gallery/hooks/useRecallPrompts.ts, invokeai/frontend/web/src/features/gallery/hooks/useRecallSeed.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildMultidiffusionUpscaleGraph.ts
- Include positive prompt in upscaling tab metadata
- Allow recalling prompt and seed on upscaling tab
https://discord.com/channels/1020123559063990373/1149506274971631688/1403747606785429687
n/a
n/a
=> fix(ui): upscaling prompt metadata

invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasColorPickerToolModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolModule.ts
Does what it says on the tin
Reported by user Outremer in https://discord.com/channels/1020123559063990373/1149506274971631688/1408859364395061379
n/a
n/a
=> fix(ui): disable color picker while middle-mouse panning canvas

invokeai/frontend/web/src/features/parameters/components/Core/ParamPositivePrompt.tsx, invokeai/frontend/web/src/features/parameters/components/Prompts/Prompts.tsx
do not show negative prompt or ref images on video tab
=> do not show negative prompt or ref images on video tab

invokeai/frontend/web/src/features/video/components/VideoPlayerControls.tsx
=> match screen capture button to the others

invokeai/frontend/web/src/features/parameters/types/constants.ts
add back negative prompt support for sd2
=> Add 'sd-2' to supported negative prompt base models

invokeai/frontend/web/src/features/parameters/components/Dimensions/DimensionsAspectRatioSelect.tsx
remove video base models from image aspect/ratio logic
=> ui(fix): remove video base models from image aspect/ratio logic

invokeai/backend/ip_adapter/ip_adapter.py
added support for NOOB-IPA-MARK1
made the code check for the unexpected layers in noob-ipa-mark1, this was to eliminate this error `Server Error RuntimeError: Encountered unexpected IP Adapter state dict key: 'adapter_modules.1.to_k_ip.weight'.`
downloaded [NOOB-IPA-MARK1](https://civitai.com/models/1000401/noob-ipa-mark1) from civitai and used vit-G as the clip vision
=> added support for NOOB-IPA-MARK1
