ldm/simplet2i.py

This allows users with 6 & 8gb cards to run 512x512 and for even larger resolutions for bigger GPUs
I compared the output in Beyond Compare and there are minor differences detected at tolerance 3, but side by side the differences are not perceptible.
(i moved this to its own branch)

use Half precision for reduced memory usage & faster speed

---

scripts/dream.py

os.path on Windows uses ntpath, which doesn't have an append method. Running it produces
`Traceback (most recent call last):
File ".\scripts\dream.py", line 277, in <module>
main()
File ".\scripts\dream.py", line 37, in main
os.path.append('.')
AttributeError: module 'ntpath' has no attribute 'append'`
This PR switches to join instead, which should be universal.

Fix windows path error

---

README.md
ldm/simplet2i.py

The [actual implementation](https://github.com/lstein/stable-diffusion/blob/6d1219deec9052ac3a1d5c99c913d15125a13c34/ldm/simplet2i.py#L29) spells it `txt2img`, not `text2image`.

Fix usage of simplified API in readme

---

.gitignore
ldm/models/diffusion/ddim.py
ldm/models/diffusion/plms.py
ldm/simplet2i.py
scripts/dream.py

A few small quality of life changes:
- added a python .gitignore preset to ignore the default image save location and model symbolic link
- allow users to set the device to run stable diffusion with, defaults to 'cuda'
- autocast will use the user set device ~~so should run on CPU with bfloat16 accelerated ops if device='cpu'~~
- cleaned up the stacked context manager lines
Changes tested and working with text2img.

A few small quality of life changes

---

ldm/models/diffusion/ddim.py
ldm/models/diffusion/plms.py
ldm/simplet2i.py
scripts/dream.py

This pr adds the following:
- Introduces a new flag, [-v, --variants] that accepts an int and pipes generated images back through the img2img pipeline in order to have a simple 'variants' method. This obvi has some limitations: works solely on strength, and uses the original prompt, but provides some interesting results
- Fixes the warning that LANCZOS is deprecated introduced by a different PR
- Hopefully better resolves the device issue for folks running on different device types in the ddim and plms samplers

Add simple variant mechanism

---

environment.yaml
requirements.txt
scripts/dream.py

- "pytorch" isn't a valid pip dependency, so fixed that and made sure that requirements.txt and environment.yaml are more in line
- Bump from upstream k-diffusers
- Fix bug in recent PR that caused iterations*variant_count variants to be created, rather than just variant_count

Various fixes

---

environment.yaml
ldm/models/diffusion/ksampler.py
ldm/simplet2i.py
requirements.txt
scripts/orig_scripts/txt2img.py

This library isn't actually required to be able to use the k-diffusion samplers. It is only part of the demonstration scripts.
There was also a small bug with the txt2img.py, where `x_sample = accelerator.gather(x_samples_ddim)` should have been `x_samples_ddim = accelerator.gather(x_samples_ddim)`, but doesn't matter since accelerate was removed.
KSampler.gather was never called anywhere and seems to just be accelerate related, so removed.
And fixed the attribution on the k-diffusion wrapper.
Tested both the original script and the dream interface, both still work.

Remove accelerate library

---

scripts/dream_web.py
scripts/static/index.css
scripts/static/index.html
scripts/static/index.js

This PR adds a simple Web UI that allows users to generate images remotely using the simplet2i interface.
TODO:
- If the `txt2img` function gets a progress callback parameter, I could add a progress bar.
- ~~img2img~~
- iterations
- Configurable sampler

Add bare bones web UI

---

.gitignore

- src was already in the gitignore, but it was still staged in the repo. I ran `git rm -r --cached src`. (when setting the env up, I had to remove src manually or the conda env setup would silently fail and hang) -> conda env setup should work reliably now
- added a directory "inputs" to .gitignore. I like to save my init-img for img2img inside the project directory -> this creates unstaged changes. `inputs/` serves as a directory where initial images can be stored. (should there be a .gitkeep to have the folder after cloning but not create unstaged changes when files get added there?)

Properly remove src from repository, add ignored directory for initial images

---

scripts/dream_web.py

This is a minor commit which keeps a log in `./outputs/img-samples/dream_web_log.txt`, similar to `dream.py` which keeps a log in `./outputs/img-samples/dream_log.txt`.

Keep a log of requests for dream_web

---

ldm/simplet2i.py

This cleans up `simplet2i.py` a bit more. In particular it deduplicates `_txt2img` and `_img2img` so that each just produces an infinite iterator of images, with `prompt2image` consuming the appropriate iterator in a loop.
If you'd prefer not to have generators I can tweak this a bit. It's convenient to use iterators here because the `img2img` case needs to save the `init_latent` value rather than recomputing it on every iteration, but we could have `prompt2image` be responsible for storing that value and passing it in.

More refactoring

---

ldm/simplet2i.py

I was testing this on M1 Mac and noticed that the `torch.device` is set to "cpu" even if there would be `mps` (Apple silicon) device available. Moved the device selection to its own function to cover this.
The `torch.backends.mps.is_available` should be included at least in torch `1.12.1`
```
In [2]: torch.backends.mps.is_available()
Out[2]: True
In [3]: torch.__version__
Out[3]: '1.12.1'
```
Btw. Thanks for all the work, this looks so fricking cool 😎

Move torch.device selection to it's own function

---

ldm/simplet2i.py
scripts/dream.py

Looking at the dream.py I noticed that files tend to stay open for a long time. This is a bad practice with potential impact on system resources. If an open file is not handled correctly and an exception occurs the file will never be closed. This is why in my opinion the use of a context manager when dealing with files is a must in python. Furthermore I would argue that in a context manager you should only do what's absolutely necessary and then exit.
This is what I'm trying to do with this small merge request.
Please test if this still functions as intended.

Refactor file handling

---

README.md
ldm/dream/pngwriter.py
ldm/gfpgan/gfpgan_tools.py
ldm/simplet2i.py
scripts/dream.py
scripts/preload_models.py

Optimize and Improve GFPGAN and Real-ESRGAN Pipeline

---

ldm/dream/server.py
static/dream_web/index.html

It's probably not a good idea to run the web UI anywhere an untrusted device could access it. But even so, best not to have this sort of vulnerability.
You might plausibly want to restrict this further, e.g. by not exposing stuff like `dream_log.txt`.

prevent directory traversal in the web UI

---

ldm/simplet2i.py
scripts/dream.py

Users can now change the sampler using `-m` prompt argument. This will prevent them from having to reboot the script. Tested out all sampler changes. Could not find any issues.
**Example Usage**
`<prompt> =m k_dpm_2`
All subsequent generations will be with the same sampler until the user changes it manually or reboots the application - at which point it reverts back to the default.

Enable Users To Change Sampler Using Prompts

---

ldm/simplet2i.py

Three commits to fix bugs that only appear when calling convenience methods directly.
1. The outdir was not being correctly passed from txt2img() and img2img() to prompt2png
2. On non-CUDA systems, load_model() was failing silently. Now it reports the error with a traceback.
3. When GFPGAN and/or upscaling in use, the modified image was not being returned in the method results list from prompt2image() (it was being passed to callback, which is why nobody spotted the problem). This is now fixed.
4. Unused variable on simplet2i.py Line 129 now removed.

Bugfixes to image generation logic

---

ldm/dream/server.py
static/dream_web/index.css
static/dream_web/index.html
static/dream_web/index.js

This PR adds the following features to the original (non-incremental) version of the dream web server:
1. Adds support for scaling and face reconstruction.
2. Adds a "reset to defaults" button for returning all form fields to their default values.
This closes issues #167 and #157.
However, it requires bugfix PR #177 for the image scaling and face reconstruction to work properly.

FEAT: Dream web upscaling

---

ldm/simplet2i.py
scripts/dream.py

This adds an option -t argument that will print out color-coded tokenization, SD has a maximum of 77 tokens, it silently discards tokens over the limit if your prompt is too long.
By using -t you can see how your prompt is being tokenized which helps prompt crafting.

tokenization logging (take 2)

---

ldm/dream/server.py
ldm/gfpgan/gfpgan_tools.py
static/dream_web/index.html
static/dream_web/index.js

This has the first two commits from https://github.com/lstein/stable-diffusion/pull/186 just to avoid merge conflicts. Third commit is the actual logic.
This hides the GFPGAN part of the web UI (and suppresses error messages in the server console) if the GFPGAN model isn't found. I actually don't have GFPGAN installed and so can't test that it still displays when the model actually is installed, but it should.

webui: hide gfpgan part if not installed

---

scripts/dream.py

This is based on and replaces #126
Added a new feature enabled via --prompt_as_dir or -p, separates generated images into subdirectories based on the prompt.
One concern about this however is the dream_log.txt file, currently for each prompt it makes a new one in each folder.
Changed 'directory_name_from_prompt' to 'prompt_as_dir' since it is simpler, can be changed back
Single directory and multi directory options are now always sanitized
Components are truncated to 255 characters to avoid windows pathing issues
Regex is compiled cached (Though I think python also caches regex itself anyway, cleaner at least)
Minor code cleanups

Add new prompt as output directory feature

---

ldm/dream/pngwriter.py
ldm/dream/server.py
static/dream_web/index.css
static/dream_web/index.html
static/dream_web/index.js

~Based on #180. Merge that PR first even if you intend to accept this one. Only look at the second commit; the first commit is in #180.~
This adds an off-by-default checkbox which lets you see images as they render, at the cost of slowing down generation. Doing this on every step ~doubles the time-to-generate on my machine, so I've made it do every 5th image, which seemed like a good tradeoff.

web ui: display in-progress images

---

README.md
ldm/dream/pngwriter.py
ldm/dream/readline.py
ldm/dream/server.py
ldm/simplet2i.py
scripts/dream.py

Per https://github.com/lstein/stable-diffusion/issues/204, this doesn't seem to be getting much use. It's annoying because the later images do not have a recoverable seed - that's both a bad experience for users and problematic internally because it means you end up with multiple images with the same seed/config.
I haven't changed any of the more "backend" code, like the diffusers; training and everything should work just the same as before. This only effects the `dream.py` and `simplet2i` wrappers.
PngWriter still has some code which refers to batch_size, but that code is in need of further refactoring, which I'll get to after this.

remove support for batch_size from dream.py

---

environment-mac.yaml

- this enables cpu fallback for op not yet implemented for m1 gpu
Without this set, this error message is encountered:
```
NotImplementedError: The operator 'aten::_index_put_impl_' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

set PYTORCH_ENABLE_MPS_FALLBACK in mac environment

---

static/dream_web/index.js

Followup to https://github.com/lstein/stable-diffusion/pull/239.
The total number of steps in img2img mode is controlled by the strength parameter, so this line needs to take that into account.

fix progress bar in webui when using strength parameter

---

static/dream_web/index.js

This small tweak provides better esthetics in the period between display of the last in-progress image and end of post-processing with GFPGAN and ERSGAN.

continue to display in-progress image until the post-processing is done

---

ldm/simplet2i.py

* Simplify `split_weighted_subprompts` method by replacing most of the logic with single a regular expression
* The original syntax is still fully supported, but has been expanded to handle all of the following variations of the syntax:
* `foo:2` integers
* `foo:-1.23` decimals and negative numbers
* `foo:` no weight (defaults to `1`)
* `foo::123` midjourney-style double-colon syntax
* `foo:2bar:1` `foo:bar` missing space characters between subprompts? no problem
* `foo:2 bar:1` spaces are fine too though
* <code>foo:&nbsp;&nbsp;&nbsp;&nbsp;bar</code> <code>foo:1.2&nbsp;&nbsp;&nbsp;&nbsp;bar:3</code> multiple spaces as well
* `foo:2 bar` and the last subprompt doesn't need a colon
* `foo` and a plain prompt works still too
* (Edit:) Added support for escaping colon characters with a …

feat: simplify and enhance prompt weight splitting

---

ldm/dream/image_util.py
ldm/simplet2i.py

Follow up to ##214 by @lstein 
Here's what this PR does.
**txt2img**
- When a user explicitly supplies either `-W` or `-H`, it performs a check to see if the resolution is a multiple of 64. If it is not, then it will change the resolution to the closest compatible number -- for both width and height or just one depending on what is set. The other will be defaulted to the boot default.
**img2img**
- In img2img, if the user does NOT explicitly state a `-W` or a `-H` then the input image (if not of compatible res) will be resized as per its aspect ratio to the closest compatible resolution.
- If the user sets only `-W`, then the image is resized using the set W as the reference and the height being driven by the input image.
- If the user sets only `-H`, then the image is resized using the …

Add Resolution Checker

---

README-Mac-MPS.md
environment-mac.yaml
ldm/simplet2i.py

I'm using stable-diffusion on a 2022 Macbook M2 Air with 24 GB unified memory.
I see this taking about 2.0s/it.
I've moved many deps from pip to conda-forge, to take advantage of the
precompiled binaries. Some notes for Mac users, since I've seen a lot of
confusion about this:
One doesn't need the `apple` channel to run this on a Mac-- that's only
used by `tensorflow-deps`, required for running tensorflow-metal. For
that, I have an example environment.yml here:
https://developer.apple.com/forums/thread/711792?answerId=723276022#723276022
However, the `CONDA_SUBDIR=osx-arm64` environment variable *is* needed to
ensure that you do not run any Intel-specific packages such as `mkl`,
which will fail with [cryptic errors](https://github.com/CompVis/stable-diffusion/issues/25#issuecomment-1226702 …

Move environment-mac.yaml to Python 3.9 and patch dream.py for Macs.

---

environment-mac.yaml
ldm/dream/devices.py
ldm/simplet2i.py
scripts/dream.py

- use MPS specific fork of k_diffusion
- move all device init logic to T2I.__init__
- handle m1 specific edge case with autocast device type
- check torch.cuda.is_available before using cuda
~Besides these changes, there is still an open question about what to do will the requirement to use `--full_precision` for M1. See discussion here for details: https://github.com/lstein/stable-diffusion/issues/237~ This is now addressed in the second commit.

changes to get dream.py working on M1

---

ldm/simplet2i.py

Autocast was being set for img2img even when `torch.cuda` is not available (for M1 machines)
This sets autocast only if `self.precision == 'autocast' and torch.cuda.is_available():`

Fix img2img on M1 machines

---

ldm/dream/pngwriter.py
ldm/models/diffusion/ksampler.py
ldm/simplet2i.py
scripts/dream.py

This is a continuation of https://github.com/lstein/stable-diffusion/pull/184 (and replaces that PR). I've credited @xraxra in the commit.
It adds two new flags: 
- `-v 0.1`, which generates variations with a specific strength (as in the above PR)
- `-V 1437160019,0.1;873874780,0.05`, which takes a list of seed,weight pairs used to apply variations (and must be combined with `--seed`)
You use the first flag to generate variations, and the second to reproduce them - including as input for further variations; this supports creating variations _of variations_, so you can wander around the space in multiple steps.
Also, I've extended it to support img2img mode, so that you can use the same flow as with txt2img: run with `prompt --init_image=whatever.png -n 10` to generate ten initial …

support generating variations

---

scripts/dream.py

1. Allow specifying the `--host` and `--port` for the web server to listen on
2. Default host to `127.0.0.1` for security reasons

web: allow custom host/port, default to 127.0.0.1 for security reasons 

---

README.md
ldm/dream/pngwriter.py
ldm/simplet2i.py
scripts/dream.py

Added capability for stable-diffusion to create seamless tiling image in `ldm/simplet2i.py`
Added --seamless command to both cmd argument and dream argument in `scripts/dream.py`
Examples:

Add seamless tiling mode and commands

---

README-Mac-MPS.md
environment-mac.yaml

Although pytorch-nightly should in theory be faster, it is currently
causing increased memory usage and slower iterations:
https://github.com/lstein/stable-diffusion/pull/283#issuecomment-1234784885
This changes the environment-mac.yaml file back to the regular pytorch
channel and moves the `transformers` dep into pip for now (since it
cannot be satisfied until tokenizers>=0.11 is built for Python 3.10).
I tried to update the tokenizers package (https://github.com/conda-forge/tokenizers-feedstock/pull/51)
but ran into some build failures; I'll try to fix those and then move `transformers`
into the conda-forge deps.

Switch to regular pytorch channel and restore Python 3.10 for Macs.

---

README.md

pip3 version did not work for me and this is the recommended way to install Anaconda now it seems

Update README.md with new Anaconda install steps

---

ldm/simplet2i.py

https://github.com/lstein/stable-diffusion/commit/5454a0edc245a92e1717102226544a200b27da8f broke img2img on MPS and when using `-v`.
PR'd against the `main` branch because the main branch is currently broken, but I can switch to `development` if you'd prefer.
(I also added a second commit fixing an assertion.)

fix img2img variations/MPS

---

README.md
ldm/simplet2i.py

Before this, the `--save_orig` flag was not working. The upscaled/GFPGAN would overwrite the original output image.

fix save_original flag saving to the same filename

---

ldm/simplet2i.py

Fixes https://github.com/lstein/stable-diffusion/issues/358. This fixes a regression in VRAM usage from https://github.com/lstein/stable-diffusion/pull/277 - specifically, in switching from an iterator to a closure, I did not add this decorator to the closure; it was still "in effect" for the body of an iterator but not for the body of a closure.
Sorry about that. But hey, now I know what `no_grad` does! (And also more about how decorators work in Python.)

put no_grad decorator on make_image closures

---

ldm/dream/server.py

This reverts commit 91e826e5f425333674d1e3bec1fa1ac63cfb382d.
The cross-origin policy is an important security feature which #363 disabled entirely. Adding these headers means that any website you visit can talk to the web server, including submitting requests. That's certainly not something I'd expect to happen by default, and and our codebase hasn't really been built with the level of attention to security necessary for that to be at all safe (cf https://github.com/lstein/stable-diffusion/pull/133).
Perhaps this functionality can be added back at a later time as an opt-in under a flag like `--dangerously-disable-cors`, or where the flag allows you to specify a specific origin rather than allowing literally anything, but best to start by reverting this and then re-doing it in a safe way. …

Revert "Add CORS headers to dream server to ease integration with third-party web interfaces"

---

scripts/orig_scripts/txt2img.py

Small patch to allow `txt2img.py --from-file` to work when the line count inside the file is lower than n_samples (batch_size in the code). Not fluent in python at all so maybe there a cleaner way to implement it.

feat(txt2img): allow from_file to work with len(lines) < batch_size

---

README-Mac-MPS.md

Like probably many others, I have a lot of different virtualenvs, one for each project. Most of them are handled by `pyenv`. 
After installing according to these instructions I had issues with ´pyenv`and `miniconda` fighting over the $PATH of my system.
But then I stumbled upon this nice solution on SO: https://stackoverflow.com/a/73139031 , upon which I have based my suggested changes.
It runs perfectly on my M1 setup, with the anaconda setup as a virtual environment handled by pyenv. 
Feel free to incorporate these instructions as you see fit. 
Thanks a million for all your hard work.

Documentation. Update instructions with how to install alongside pyenv

---

ldm/generate.py
scripts/dream.py

Very small change which prints out the maximum amount of VRAM used during model loading and initialization, as well as the amount of VRAM used to hold the model.

report VRAM usage stats during initial model loading

---

ldm/modules/attention.py

Reinstate neonpixel optimizations with special check for MPS device to avoid (hopefully) performance regression on that platform.

disable neonpixel optimizations on M1 hardware

---

Stable_Diffusion_AI_Notebook.ipynb
requirements-colab.txt

Colab notebook wasn't working anymore with release 1.09. As part of an issue #272  I gave as solution to [checkout to a different commit](https://github.com/lstein/stable-diffusion/issues/272#issuecomment-1237675893) but I wanted to refactor the notebook and resolve dependencies issues. 
I wanted to take advantage of the new approach of using a separated requirement files for each Env, but the requirements-lin didn't work as expected and I created a new requirements-colab very similar to requirements-lin. 
Also to leverage the pre-installed colab libraries, I removed pipenv and compared 1 by 1 the lin and colab libs. 
This is what I got:
Maintained almost all lin libs, except for torch, torchvision and numpy, also included some needed libs due to errors in dream script.
Changes I made:
- …

Colab improvements

---

ldm/dream/server.py

The image seed value is now correctly written into dream_web_log.txt rather than the -1 that is shown in the UI.

write correct image seed into web log

---

ldm/dream/server.py
static/dream_web/index.css
static/dream_web/index.js

This PR parses the web run log in order to populate the results list at startup. This gives the entire history at a glance. You can now reload you browser tab and still see your images. 
Imgs are lazy loaded, so just the topmost will load, but I haven't considered what'll happen once you've got thousands of pics in your log. This is easily fixed by some log cycling approach, though. 
For discussion:
The correct seed is currently not being written to the web log, just the seed setting in the GUI, which is usually -1. So you can't really click the seed caption to load it into the form until this is fixed. You could argue this PR is incomplete without first fixing this, and so I've left it as a draft PR.

Implemented support for parsing dream_web_log.txt for frontend init state

---

ldm/simplet2i.py

Disabled the debug output (the seed is present in the eventual output anyway.. no need to output it twice.

Disable the debug output

---

.gitignore
README-Mac-MPS.md

Temp file created when running `scripts/dream.py --web` and running with "initial image" set

.gitignore WebUI temp files

---

README.md
ldm/dream/generator/inpaint.py
ldm/dream/pngwriter.py
ldm/generate.py
scripts/dream.py

If the initial image contains a transparent region and no mask is provided explicitly, will try to convert the transparent regions into a mask. However, most image editors also clear the RGB values when creating transparent areas, which leads to bad results. The -M switch is provided so that you can load both the initial image and its transparent version, but this is a hack.
More work needs to be done on inpainting. @bmaltais has suggested that the masked area of the initial image be replaced with latent noise. This may be the right approach.

add auto-creation of mask for inpainting

---

ldm/dream/server.py
static/dream_web/index.html
static/dream_web/index.js

This PR contains two improvements in web ui:
- "Variation amount" and "With variations" fields are correctly updated when clicking on image captions, so the generator is ready to generate variations based on the selected image
- full normalized prompt is saved to PNG metadata using the same logic as the main script

better updating variations fields when clicking on images, saving full prompt to metadata in webui

---

ldm/generate.py
scripts/dream.py

When reading prompts from a file, the keyboard interrupt should abort everything, not just processing of the current prompt.
Closes #401

Allow ctrl c when using --from_file

---

ldm/modules/attention.py

~7% speedup (1.57 to 1.69it/s) from switch to += in ldm.modules.attention
Tested on 8GB eGPU nvidia setup so YMMV.
512x512 output, max VRAM stays same.

~7% speedup (1.57 to 1.69it/s) from switch to += in ldm.modules.attention

---

static/dream_web/index.html

Reverts lstein/stable-diffusion#442 to address the bug introduce when upscaling to x3.  (Reference to Issue: https://github.com/lstein/stable-diffusion/issues/487)

Revert "Add 3x upscale option on the Web UI"

---

ldm/gfpgan/gfpgan_tools.py

The upsampler currently disables itself on CPUs with a warning, even though on M1 (MPS) hardware it's able to run quick as long as the precision is set to full. This change removes the stop code and instead enables full precision when no cuda is available.

Enable upscaling on M1 mps

---

ldm/dream/devices.py
ldm/generate.py
ldm/modules/diffusionmodules/model.py

When running on just cpu (intel), a call to torch.layer_norm would error with "RuntimeError: expected scalar type BFloat16 but found Float"
Fix buggy device handling in model.py.
Tested with scripts/dream.py --full_precision on just cpu on intel laptop. Works but slow at ~10s/it.

Disable autocast for cpu to fix error. Remove unused precision arg.

---

docs/features/CLI.md

This minor documentation patch describes how negative numbers can be used to retrieve earlier values of seeds and image paths.

document negative index shortcuts

---

environment.yaml

This is a hot fix onto main. While debugging training, I inadvertently changed the environment name from "ldm" to "sd-ldm" in environment.yaml. This messes up the documentation, so I'm reverting it.

revert inadvertent change of conda env name

---

docs/features/VARIATIONS.md

Images had their relative paths broken. Adjust the paths in this doc to use their correct locations.
(Apologies if this is too small for a pull, but figured it was a trivial adjustment, and was faster to fix than to request changes.)
(Secondly, I assume a docs update is ok to base on main instead of development, correct me if otherwise.)

Fix images in Variations example

---

ldm/generate.py
scripts/dream.py

Make results reproducible (so runs with the same seed produce the same result). Implements fix by @wbowling referenced in https://github.com/lstein/stable-diffusion/issues/397#issuecomment-1240679294
Example: `"banana sushi" -s50 -W512 -H512 -C7.5 -Ak_euler_a -S618376249`
Before
After
Fix should be ignored in non-MPS devices, but test to make sure.

Update dream.py. k_euler_a and k_dpm_2_a M1 fix

---

ldm/dream/server.py

This change makes it so any API clients can show the same error as what happens in the terminal where you run the API. Useful for various WebUIs to display more helpful error messages to users.
As an example, setting `cfg_scale` to `1` would return nothing as the response body when making HTTP requests. The terminal window would print `AssertionError: CFG_Scale (-C) must be >1.0` together with a stack trace though, but only useful for whoever has access to the terminal window itself.
With this change, sending a request with `cfg_scale` set to `1`, it now returns the following response body before closing the connection:
```json
{"event": "error",
"message": "CFG_Scale (-C) must be >1.0",
"type": "AssertionError"}
```
It still raises the exception after printing it, so everything works as …

Make API return error before raising error again

---

ldm/dream/server.py

This keeps intermediate image filenames in order:
000010.None.01.png
000010.None.02.png
000010.None.03.png
000010.None.04.png
000010.None.05.png
000010.None.06.png
000010.None.07.png
000010.None.08.png
000010.None.09.png
000010.None.10.png
rather than:
000010.None.1.png
000010.None.10.png
000010.None.2.png
000010.None.3.png
000010.None.4.png
000010.None.5.png
000010.None.6.png
000010.None.7.png
000010.None.8.png
000010.None.9.png

Zero-pad intermediate image file names

---

README.md

Having a badge which shows our last commit as "Last Tuesday" (because it's reading 'main') doesn't look very good, particularly for a repo as active as this one - switched to "last 'development' commit"
- add "release" badge as a proxy for "last commit to 'main'"
- "linkify" all badges, so clicking on them goes somewhere useful
- switch badge service to badgen, as I couldn't figure out shields.io
[Click](https://github.com/tildebyte/stable-diffusion/blob/fix-readme-badges/README.md) for preview

fix(readme): switch last-commit badge to last DEVELOPMENT commit

---

ldm/dream/args.py
scripts/dream.py

A bug fix patch for things that broke with the generate and dream refactor. #534 
**Fixes:**
- Fixed `q` not working to exit the dream command line.
- Added `--sampler' to model_group too. This is an important argument that allows scripts to run a default sampler at boot.
- Fixed `generate` ignoring the width and height from the config file.
- Fixed some missing imports
- Fixed some opts not ported over correctly.
**ToDo:**
- **CRITICAL** >>> 2nd Prompt is Broken. The first prompt works. The 2nd prompt crashes. @lstein Please look into this.
---
This bug fix patch can be merged once all the bugs are fixed.

Bug Fixes: generate and dream refactor

---

README.md

Looks like we have to use a *deprecated* AND *obsoleted* HTML mechanism... +1 GitHub 😐
- maintaining the badges in embedded HTML is a P.I.T.A. (and embedding HTML in Markdown is highly discouraged)
- "don't use emphasis for header-like things - use headers"
- links aren't headers
[Preview](https://github.com/tildebyte/stable-diffusion/blob/toil-de-wart-readme-md/README.md)

toil(docs): readme - remove remaining markdown warts, HTML

---

ldm/modules/attention.py

EDIT:
Refactor attention.CrossAttention to remove 4 copies of einsum_op_compvis code.
Remove zeros tensor that's useless when we have enough VRAM.
For cuda keep VRAM usage and faster slicing consistent.

Keep VRAM usage and faster slicing consistent in attention.py

---

ldm/modules/diffusionmodules/model.py
ldm/modules/diffusionmodules/util.py

Fixes:
File "stable-diffusion/ldm/modules/diffusionmodules/model.py", line 37, in nonlinearity
return x*torch.sigmoid(x)
RuntimeError: CUDA out of memory. Tried to allocate 1.56 GiB [..]
Now up to 1536x1280 is possible on 8GB VRAM.
Also remove unused SiLU class.
`silu` is `x * torch.sigmoid(x)` is the swish function
https://pytorch.org/docs/stable/generated/torch.nn.functional.silu.html

Enable even larger images with one simple torch.nn.functional.silu import

---

README.md

Finally figured it out 😁
[Preview](https://github.com/tildebyte/stable-diffusion/blob/fix-doc-readme-ci-links/README.md)

fix(doc): readme - more meaningful CI badge links

---

README.md

I'd prefer a simple "Discord Server" badge, but badgen only provides "members" and "online members" 🤷 
[Preview](https://github.com/tildebyte/stable-diffusion/blob/feat-add-discord-badge/README.md)

feat(docs): readme - add discord server badge/link

---

ldm/dream/args.py
scripts/dream.py

The recent args refactor broke the handling of the --prompt_as_dir flag. This restores it.
In addition, there was a bit of semantic drift between the internal configuration variable "sampler_name" and the RFC field "sampler." I did a little workaround so as not to introduce many code changes.

restore ability to save files to directories named after prompt

---

docs/other/CONTRIBUTORS.md
ldm/dream/conditioning.py

This is an improved and optimized version of @rabidcopy's PR #637 that implements negative prompting.
Any words between a pair of square brackets will try and be ignored by Stable Diffusion's model during generation of images.
```this is a test prompt [not really] to make you understand [cool] how this works.```
In the above statement, the words 'not really cool` will be ignored by Stable Diffusion.
Here's a prompt that depicts what it does.
original prompt: `"A fantastical translucent poney made of water and foam, ethereal, radiant, hyperalism, scottish folklore, digital painting, artstation, concept art, smooth, 8 k frostbite 3 engine, ultra detailed, art by artgerm and greg rutkowski and magali villeneuve" -s 20 -W 512 -H 768 -C 7.5 -A k_euler_a -S 1654590180`
This one gave me a woman. …

Negative / Unconditioned Prompts

---

docs/features/VARIATIONS.md

A beginning line for a code section was left out.

VARIATIONS.md - fix typo in formatting

---

ldm/dream/args.py
scripts/dream.py
scripts/preload_models.py

The preload_models.py script will no longer download the gfpgan model file if it already exists on disk.

Gfpgan download fix

---

.gitignore
docs/features/UPSCALE.md
ldm/dream/args.py
ldm/generate.py
ldm/restoration/codeformer/codeformer.py
ldm/restoration/codeformer/codeformer_arch.py
ldm/restoration/codeformer/vqgan_arch.py
scripts/preload_models.py

This PR brings in support for Face Restoration with [CodeFormer](https://github.com/sczhou/CodeFormer). Another excellent library for Face Restoration.
When you first run the CodeFormer option, it should download the model for you. If it does not, you can also use `preload_models.py` to do the same. Or you can manually downloads the model and place it in `ldm/restoration/codeformer/weights`. The documentation is updated to reflect the installation instructions for CodeFormer.
- You enable face restoration by using `-G` as you do with GFPGAN. The value provided to `-G` will also control the strength of the restoration being applied.
- You can swap between CodeFormer and GFPGAN using a new argument called `-ft` that stands for `facetool`.
- CodeFormer has one exclusive argument. `-cf` which …

Implement CodeFormer Face Restoration

---

scripts/dream.py

Stumbled on this while playing with `blue`, and thought it looked like a typo.
Introduced in 239f41f https://github.com/lstein/stable-diffusion/blob/239f41f3e0027900ee73196ac89850a9d172c0e9/scripts/dream.py#L274

fix(scripts): dream.py typo

---

scripts/preload_models.py

Fixes lstein/stable-diffusion#678

Use model_url instead of model_path for gfpgan and CodeFormer

---

pyproject.toml

As discussed in #631
For clarification, this **only a config file**. It has no effect on anything.
The config is for 'blue', the only really important option here is that we're setting line-length to 90.
'target-version' basically tells blue which version of Python we're using, as blue is aware of syntax differences between versions. 
Note that this does not mean that it's going to disallow earlier versions or anything like that; more like it allows *newer* constructs

feat(ci): add pyproject.toml with `blue` config

---

.dev_scripts/test_regression_txt2img_dream_v1_4.sh
.github/workflows/test-dream-conda.yml
README.md
docs/features/CLI.md
docs/features/TEXTUAL_INVERSION.md
docs/index.md
docs/installation/INSTALL_MAC.md
ldm/dream/args.py
ldm/dream/devices.py
ldm/dream/generator/base.py
ldm/dream/generator/embiggen.py
ldm/dream/generator/img2img.py
ldm/dream/generator/inpaint.py
ldm/dream/generator/txt2img.py
ldm/generate.py
scripts/dream.py
server/application.py
server/containers.py

Allowed values are `auto`, `float32`, `autocast`, `float16`. If not specified or `auto` a working precision is automatically selected based on the torch device. Context: #526
Tested on both cuda and cpu by calling scripts/dream.py without arguments and checked in the right configuration. With --precision=auto/float32/autocast/float16 it performs as expected, either working or failing with a reasonable error. Also checked Img2Img.
As dropping `--full_precision` / `-F` is a significant user interface change I think this should be noted in the release notes for the next version. Should I start a section?

Replace --full_precision with --precision that works even if not specified

---

scripts/dream.py

This was removed from other calls to `metadata_dumps()` but not this one.

Fixes #717

---

README.md

Please don't make me keep having to clean this up
1) Centering of the front matter is completely wrecked
2) We are not a billboard for Discord. We have a perfectly good badge - if the *link* needs fixing, fix it.
3) Stop putting HTML in Markdown
4) We need to state who and what we are once, clearly, not 3 times...
- `<b>InvokeAI: A Stable Diffusion Toolkit</b>`
- `# Stable Diffusion Dream Script`
- `# **InvokeAI - A Stable Diffusion Toolkit**`
5) Headings in Markdown SHOULD NOT HAVE additional formatting

FIX readme (again)

---

docs/installation/INSTALL_LINUX.md

I recently installed InvokeAI, but the linux guide is out of date showing the old project name in many steps.
For new users this will be a big problem.
So here is a fix for the installation process on linux

linux instructions update to /InvokeAI/ folder name

---

README.md

~~There is an issue with the `[CI checks on dev badge]` link - I'm hoping it's some kind of "new org/new repo so we're not up to date yet" issue on badgen's end - the link for 'main' is still good, and only the name has changed for either.~~
LOL fixed already
[Preview](https://github.com/tildebyte/InvokeAI/blob/fix-doc-readme-badge-links-old-repo/README.md)

fix(docs): readme badge links point to old repo

---

ldm/dream/restoration/base.py
ldm/dream/restoration/gfpgan.py
ldm/generate.py
scripts/dream.py

Fixes. #749
This PR reworks how the restoration modules are loaded.
1. GFPGAN, CodeFormer and ESRGAN models are on by default.
2. If GFPGAN or CodeFormer models are not found, then instead of crashing the app, the user is notified and the app loads with Face Restoration disabled.
3. If only one of GFPGAN or CodeFormer models are not found, then the app loads with one of those enabled.
4. When you try to restore faces, the model defaults to GFPGAN but gives a notification error that face restoration is disabled if GFPGAN is not found. You can still use CodeFormer to restore by passing `ft` if you have only CodeFormer enabled.
5. You can completely turn off face restoration and upscaling using the `--no_restore` or `--no_upscale` switches.

Restoration Modules are now optional

---

ldm/generate.py

This PR updates the `Generator._make_image` method (used to load both the init image and inpainting mask) to take a few different types:
- A `str` path, which is treated just like it is today and is used as a file path to load the image.
- An existing instance of [`PIL.Image.Image`](https://pillow.readthedocs.io/en/stable/reference/Image.html#the-image-class), which is then used directly rather than trying to load an image.
- Any other type, which is passed directly to `Image.open` without treating it as a path. This means that any reader-like type should be useable, such as a `BytesIO` instance.
This is a small tweak I made to my InvokeAI fork that I felt was pretty useful. I needed a way to pass an existing `Image` instance to `Generator.prompt2image`, and creating a temporary file …

Allow `Generate` to take init image and mask directly

---

ldm/dream/generator/inpaint.py

When `Generate.prompt2image` is called in inpainting mode (including an init image plus a mask) and the sampler name is set to `ddim`, then the following exception occurs today:
```
AttributeError: 'DDIMSampler' object has no attribute 'ddim_alphas'
```
This happens because the line that creates the schedule only gets called in the case where a fallback sampler is used (i.e. any sampler other than DDIM). Creating the schedule unconditionally by moving the `make_scedule` call outside of the `if` block fixes this issue.

Fix exception when inpainting with DDIM sampler

---

docker-build/Dockerfile
docs/features/CLI.md
docs/features/UPSCALE.md
docs/installation/INSTALL_DOCKER.md
ldm/dream/args.py
ldm/dream/restoration/base.py
ldm/dream/restoration/gfpgan.py
scripts/preload_models.py

Upgrading GFPGAN to use the 1.4 model instead of the older 1.3 model.
Model Download: https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth
You can replace the model file in `src/gpfgan/experiments/pretrained_model' with this new one and it'll be good to go.

Upgrade GFPGAN to Version 1.4

---

ldm/generate.py

Build the base generator in same place and way as other generators to reduce the chance of missed arguments in the future. Fixes crash with display in-progress images, though note the feature still doesn't work for other reasons. Partial fix for #758

Fix Generate.sample_to_image crash.

---

ldm/generate.py

This will make codeformer face restoration work on macOS by forcing facexlib and codeformer to use CPU.
facexlib triggers a fatal error in the Metal Graphs, codeformer is just broke.
See https://github.com/invoke-ai/InvokeAI/issues/713 for more details.

facexlib and codeformer are broken on mps currently, force CPU device, works around  issue #713

---

requirements.txt

For installs using 'requirements*.txt':
Either Huggingface's 'transformers' lib introduced a regression in v4.22, or we changed how we're using 'transformers' in such a way that we break when using v4.22.
Pin 'transformers==4.21.*'

fix(install): pin 'transformers'

---

environment-mac.yaml

Pin `openh264` to 2.3.0 until OpenCV supports 2.3.1 or newer. Added just to `environment-mac.yml` since I know this happens on M1 / Apple Silicon Macs (running macOS 13) and that's all I can test on.

Pin openh264 to 2.3.0, Fixes #787

---

ldm/dream/args.py
ldm/dream/generator/txt2img.py
ldm/generate.py
scripts/dream.py

Sample model moved to cpu before processing samples to image
I am not sure how to handle additional parameter and supply it to underplaying classes
Related to FR #775

Add workaround low memory crash during image saving

---

ldm/dream/args.py
ldm/dream/restoration/realesrgan.py
ldm/generate.py
scripts/preload_models.py

Addressing #802
---
**Important Changes**
- ESRGAN now uses the new light weight model `realesr-general-x4v3` model instead of the older 4x model. The older model was 64MB in size compared to the 4.64MB of the new model. The inference times are significantly faster. Did not notice any great loss in quality. *Note: The Real-ESRGAN repo states that there are chances this light weight model might fail in some extreme cases. I haven't found any but it's a point to note.*
- `-U` or `--upscale` are now capable of taking any value for the scale factor and not just 2 or 4. Using `1` will sharpen the output but retain the size. As the model is meant for 4x scaling, any value up to `4` will yield good results. Anything above is simple upscaling and will eventually deteriorate in quality.
- Face …

ESRGAN Improvements

---

docs/installation/INSTALL_MAC.md

I had to use `osx-64` not `osx-x86-64` for conda to install the required packages from conda-forge

Fix `ResolvePackageNotFound` error on Intel Macs

---

backend/server.py

Fixes #822
During my last refactor of metadata handling in the new UI, the save_image function had changed but I didn't update its call in the progress callback. This corrects the call.

Fixes error on new UI when progress images is enabled

---

ldm/dream/readline.py
scripts/dream.py

- When --save_orig *not* provided during image generation with upscaling/face fixing, an extra image file was being created. This PR fixes the problem.
- Also generalizes the tab autocomplete for image paths such that autocomplete searches the output directory for all path-modifying options except for --outdir.

fix duplicate files created during upscaling/facial reconstruction

---

ldm/dream/readline.py
ldm/generate.py
scripts/dream.py

-if readline.set_auto_history() is not implemented, as in pyreadline3, will fall back gracefully to automatic history saving. The only issue with this is that !history commands will be recorded in the history. 
-!fetch on missing file no longer crashes script
-!history is now one of the autocomplete commands
-.dream_history now stored in output directory rather than ~user directory.
An important limitation of the last feature is that the history is loaded and saved to the .dream_history file in the --outdir directory specified at script launch time. It is not swapped around when the --outdir is changed during the session.

improve behavior and fix bugs in CLI history handling and completion

---

ldm/dream/args.py
ldm/dream/generator/txt2img2img.py
ldm/generate.py

As was mentioned in #840 it is possible to generate a lower resolution image with the same prompt, and then run img2img using your prompt again at your requested resolution with the low-res image as the source. This is a pretty good way of avoiding the repetition issues you get when using higher resolutions.
This is a test implementation of such scaling when --hires switch is used, sample input was
"brown corgi, clean background, flat design" -s 20 -S 1 -W 768 -H 1024 -C 7.5 -A ddim
and 
"brown corgi, clean background, flat design" -s 20 -S 1 -W 768 -H 1024 -C 7.5 -A ddim --hires
vs

Test implementation of hires mode with img2img scaling

---

scripts/dream.py

Passing a bad png file or a png file without proper metadata to !fix or !fetch causes a crash currently. Instead report the error and continue. Note that `OSError` catches `PIL.UnidentifiedImageError` as well, so this will catch bad image formats too

Gracefully handle invalid files passed to !fix and !fetch

---

ldm/dream/args.py
scripts/dream.py

- When generating multiple images, the first seed was being used for second
and subsequent files. This should only happen when variations are being
generated. Now fixed.
- Restore correct behavior of --grid argument

fix --grid and seed metadata

---

docs/features/UPSCALE.md

The documentation shows a wget command to download the gfpgan files and was missing the `-P` flag

missing flag in wget download example

---

ldm/generate.py

It turns out that the reason that we were losing colors under transparent masked regions was **not** because all photoeditors suck. It is because the PIL library doesn't know how to rescale/resample images that contain an alpha channel. The alpha channel was being combined with the RGB values during rescaling!
Changing the order of mask creation and rescaling solved the problem. The `-M` option should no longer be needed in most cases.

reorder mask creation and scaling to avoid deleting colors under transparency

---

ldm/dream/generator/txt2img.py
ldm/models/diffusion/ksampler.py

This puts the ksamplers back the way they were before I tried the Karras noise scheduler. Will continue to experiment offline.

Revert to old kdiffusion schedule

---

docs/features/CLI.md
environment.yml
ldm/dream/readline.py
requirements.txt
scripts/dream.py

- Added support for pyreadline3 so that Window users can benefit.
- Added the `!search` command to search the history for a matching string: 
~~~
!search puppies
[20] puppies at the food bowl -Ak_lms
[54] house overrun by hungry puppies -C20 -s100
~~~
- Added the `!clear` command to clear the in-memory and on-disk command history.

add enhancements to CLI command-line completion and history

---

frontend/src/features/gallery/CurrentImageDisplay.scss
frontend/src/features/gallery/CurrentImageDisplay.tsx
frontend/src/features/gallery/ImageGallery.tsx
frontend/src/features/gallery/gallerySlice.ts
frontend/src/features/system/HotkeysModal/HotkeysModal.tsx

- Buttons added to `CurrentImageDisplay` which display on hover over left/right edges of image display
- Hotkeys added to `ImageGallery` which are active whenever the image gallery is rendered
- Action/reducer added to `gallerySlice` to set next/prev image as current
Resolves #918
No bundle attached, hoping for PR #943 to be merged before this is.

[WebUI] Adds next/previous image buttons/hotkeys

---

ldm/dream/generator/img2img.py
ldm/models/diffusion/ksampler.py

- supersedes #977
- A limitation of this fix is that it works with txt2img only, and not with img2img. Please use plms or ddim samplers for applying minor variations to img2img until a better solution is found.

restore ability of ksamplers to process -v variation options

---

backend/invoke_ai_web_server.py

Currently, we always specify a list of CORS origins in the flask server. This appears to be incorrect (I didn't read the manual). 
With this PR, by default, the flask server follows the expected same-origin policy. Only if the user uses the `--cors` flag is the `cors_allowed_origins` passed to the server.
I have tested as much as I can on my current local network, which consists of my phone and laptop, hot-spot-ted to my phone. Everything works and I haven't needed to use `--cors` when accessing the app from laptop(server) or phone.

Fixes CORS handling

---

docs/installation/INSTALL_LINUX.md
docs/installation/INSTALL_WINDOWS.md
environment-mac.yml
environment.yml
notebooks/Stable-Diffusion-local-Windows.ipynb

This is targeting 'main' as this is a hotfix for 2.0.
'ldm' as venv name will definitely collide with other repo's venv names

hotfix(venv): rename 'ldm' -> 'invokeai'

---

README.md

Trivial change, two links went to `.m` rather than `.md`.

Fix two broken links in README

---

docs/installation/INSTALL_MAC.md

Fixes #1025.
I only updated the Mac instructions since those were the only ones I could actually verify. 3 references to ldm are still present but those refer to still existing file paths ("ldm/modules", "models/ldm/stable-diffusion-v1").
The main fix is for line 102 which I'm guessing is blocking a lot of people who don't have the knowledge/experience to realize what's going wrong.

update mac instructions to use invokeai for env name

---

ldm/generate.py

Make results reproducible (so runs with the same seed produce the same result). Implements fix by @wbowling referenced in https://github.com/invoke-ai/InvokeAI/issues/397#issuecomment-1240679294

reintroduce fix for m1 from https://github.com/invoke-ai/InvokeAI/pull/579 missing after merge

---

notebooks/Stable_Diffusion_AI_Notebook.ipynb

Making Stable_Diffusion_AI_Notebook.ipynb work smoothly on Google Colab

Update Stable_Diffusion_AI_Notebook.ipynb (Take 2)

---

.github/CODEOWNERS
ldm/invoke/pngwriter.py
ldm/invoke/server_legacy.py
scripts/legacy_api.py
tests/legacy_tests.sh

This commit "reverts" the new API changes by extracting the old functionality into new files.
The work is based on the commit `803a51d5adca7e6e28491fc414fd3937bee7cb79`
PngWriter regained PromptFormatter as old server used that.
`server_legacy.py` is the old server that `dream.py` used.
Finally `legacy_api.py` is what `dream.py` used to be at the mentioned commit.
One manually run test has been added in order to be able to test compatibility with the old API, currently just testing that the API endpoint works the same way + the image hash is the same as it used to be before.
Currently, the image hash is different than what it would be if output with the old `dream.py`. Reasons for this is unknown. New image gets hash `a77799226a4dfc62a1674498e575c775da042959a4b90b13e26f666c302f079f` …

Add back old `dream.py` as `legacy_api.py`

---

ldm/generate.py

Print out the device type which is used for generating images. Saw a few times that people asked why it took so long and run into the same issue, because I had the wrong torch version installed.
Not sure if the right place, but definitely an important information cuda, cpu or mps?

Print out the device type which is used

---

ldm/modules/diffusionmodules/model.py

Implements fix by @Any-Winter-4079 referenced in https://github.com/invoke-ai/InvokeAI/issues/1016#issuecomment-1276825640

fix for "1 leaked semaphore objects to clean up at shutdown" on M1

---

scripts/dream.py

Just a bit cleaner to forward using `import` instead of reexecuting python, also running "python3" risks bringing up the wrong interpreter. Added a deprecation warning as well.

Forward dream.py to invoke.py using the same interpreter, add deprecation warning

---

ldm/invoke/args.py
ldm/invoke/readline.py
ldm/models/diffusion/ksampler.py
ldm/models/diffusion/sampler.py
scripts/invoke.py

At step counts greater than ~75, the ksamplers start producing noisy images when using the Karras noise schedule. This PR reverts to using the model's own noise schedule, which eliminates the problem at the cost of slowing convergence at lower step counts.
This PR also introduces a new CLI `--save_intermediates <n>` argument, which will save every nth intermediate image into a subdirectory named `intermediates/<image_prefix>`.
Addresses issue #1083.

fix noisy images at high step counts

---

docs/installation/INSTALL_MAC.md

I know I'm supposed to merge into `development` but this seems like something that should be up-to-date in `main`

Update 'ldm' env to 'invokeai' in troubleshooting steps

---

ldm/invoke/args.py

A partial solution to #1101, don't print the default facetool parameters if face enhancement is not even enabled. This doesn't solve the saving or loading issue, but it will make the output less confusing.
For example of the prompt text rendering being confusing see: https://github.com/invoke-ai/InvokeAI/pull/1108#issuecomment-1279846403
Example with no facetool, no parameters:
```
invoke> test -s1
[121] outputs/img-samples/000060.1125788153.png: "test" -s 1 -S 1125788153 -W 512 -H 512 -C 7.5 -A k_lms
```
Example with gfpgan:
```
invoke> test -s1 -G1
[122] outputs/img-samples/000061.3072109442.png: "test" -s 1 -S 3072109442 -W 512 -H 512 -C 7.5 -A k_lms -G 1.0 -ft gfpgan
```
Example with codeformer:
```
invoke> test -s1 -G2 -ft codeformer -cf 0.75
[123] …
```

Only output facetool parameters if enhancing faces

---

ldm/modules/diffusionmodules/util.py

Added a [community solution](https://github.com/CompVis/stable-diffusion/issues/111#issuecomment-1229483511) to fix index out of bound when doing img2img generation with `ddim` sampler. Also, restored `steps_out` to be `ddim_timesteps + 1` since the removal was meant to fix the [1000 steps issue](https://github.com/invoke-ai/InvokeAI/issues/415)

Fix img2img DDIM index out of bound

---

ldm/invoke/restoration/codeformer.py
ldm/invoke/restoration/gfpgan.py

Our Codeformer and GFPGAN implementations are sending RGB image data to the restoration code, but they expect BGR image data (as used by OpenCV).
The fix is simple; use a cv2 method to convert the image from RGB to BGR before processing, and then back to RGB so we can continue using PIL. 
This fixes an until-today unknown flaw in our GFPGAN implementation, which was recognized by user JoshuaKimsey on discord.

Corrects color channels in face restoration; Fixes #1167

---

README.md
docs/index.md

Feels silly to make a PR for such a trivial thing, but that typo at the top of the docs has been bugging me for a while. Hopefully I'll have something more substantial to contribute in future PRs once I take some time to get more acquainted with the code. :)

Fix typo in docs: s/Formally/Formerly

---

ldm/invoke/restoration/realesrgan.py

Similar to issue #1175, REALSRGAN expects BGR as input instead of RGB. This implementation reused the same numpy array slicing code as #1178.

Correct color channels in upscale using array slicing

---

main.py

- remove unsupported testtubelogger, use csvlogger instead
- fix logic for parsing --gpus option so that it won't crash if trailing comma absent
- change trainer accelerator from unsupported 'ddp' to 'auto'
- closes #1168

fix a number of bugs in textual inversion

---

ldm/generate.py
ldm/invoke/args.py
scripts/invoke.py

- catch syntax errors in the outcrop coordinates
- work (after a fashion) on non-Invoke generated images
- closes #1197

outcropping improvements

---

configs/models.yaml
ldm/invoke/model_cache.py
scripts/invoke.py

1. Download the appropriate autoencoder and put it into models/ldm/stable-diffusion
Note that you MUST use a VAE that was written for the original CompViz Stable Diffusion codebase. For v1.4, that would be the file named vae-ft-mse-840000-ema-pruned.ckpt that you can download from https://huggingface.co/stabilityai/sd-vae-ft-mse-original
2. Edit config/models.yaml to contain the following stanza, modifying `weights` and `vae` as required to match the weights and vae model file names. There is no requirement to rename the VAE file.
~~~
stable-diffusion-1.4:
weights: models/ldm/stable-diffusion-v1/sd-v1-4.ckpt
description: Stable Diffusion v1.4
config: configs/stable-diffusion/v1-inference.yaml
vae: models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
width: 512
height: 512
~~~ …

add support for loading VAE autoencoders

---

ldm/invoke/args.py
ldm/invoke/pngwriter.py
scripts/invoke.py

This PR fixes several bugs in how the CLI stores, processes and retrieves metadata:
- fix incorrect handling of single quotes in prompts
- facetool and upscale arguments passed during image generation now written into metadata
- cleaned up handling of !fetch command

Metadata storage and retrieval fixes

---

shell.nix

Provides way to get InvokeAI environment through nix [1]
This merely wraps miniconda into a own shell environment, and does not try to reproduce the build itself.
Tested on both linux-x86_64 and aarch64-darwin
1: https://nixos.org/

nix: add shell.nix file

---

ldm/dream/args.py
ldm/dream/generator/base.py
ldm/dream/generator/txt2img.py
ldm/dream/generator/txt2img2img.py
ldm/generate.py

@Any-Winter-4079
Any idea how to test it?

Allow user to generate images with initial noise as on M1 / mps system

---

ldm/invoke/model_cache.py

Hi, please consider raising a proper exception here instead of an undefined internal state. This happens for example if the filepath to the model.ckpt is invalid on first load.

Raise exception instead of undefined internal state

---

docs/features/PROMPTS.md
ldm/invoke/conditioning.py
ldm/invoke/prompt_parser.py
ldm/models/diffusion/shared_invokeai_diffusion.py
tests/test_prompt_parser.py

This PR corrects the call signature for `do_diffusion_step()` and enhances the description of using `prompt2prompt` in the documentation.

Prompt tweaks

---

.github/workflows/build-container.yml

This fixes the docker-tag for Repositorys containing capital letters

Fix-build-container-action

---

.github/workflows/create-caches.yml
.github/workflows/test-invoke-conda.yml
tests/validate_pr_prompt.txt

- in this way the action is used from the base repository
- also use new secret HUGGINGFACE_TOKEN (username:token)
- f.e. `noreply@github.com:hf_lkaugfklagwrjglaslzfgkjzzf`
- change pr prompt file to validate_pr_prompt.txt
@lstein: you need to create the new secret as mentioned above

Protect-secrets-on-pr

---

environment-mac.yml

using conda packages where possible according to [conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages)
> Pip packages do not have all the features of conda packages and we recommend first trying to install any package with conda. If the package is unavailable through conda, try finding and installing it with [conda-forge](https://conda-forge.org/search.html).
> 
> If you still cannot install the package, you can try installing it with pip. The differences between pip and conda packages cause certain unavoidable limits in compatibility but conda works hard to be as compatible with pip as possible.

fix environment-mac.yml - tested on x64 and arm64

---

.github/workflows/create-caches.yml
.github/workflows/test-invoke-conda.yml

use propper bearer authentication to download the stable-diffusion model from huggingface.co, instead of `--user "username:token"`
@lstein: This should be even easier to reproduce, since the there should be only the huggingface token in `secrets.HUGGINGFACE_TOKEN` (but no linebreak in the end, so only `hf_blablalba`)
Also removeing -O since we don't want a file with original name as output, but already defined a outputfile

Use proper authentication to download model

---

.github/workflows/build-container.yml
.github/workflows/test-invoke-conda.yml

- integrated the sd-v-1-5 mdoel into the test matrix, which is easyli expandable / changeable for future changes
- switched to macOS-12 since latest still points to "Using 12 soon" and we are now at 13...
- removed unecesarry caches from test-invoke-conda after realizing that it was over 30GB / 10GB offered for a free account 🙈 
- made build-container.yml's cache reusable, which also heavily speeds up container creation
- before every build created a new cache....
- renamed test-invoke-conda workflow by removing the redundant parts from name

Integrate sd-v1-5 model into test matrix (easily expandable), remove unecesarry caches

---

ldm/models/diffusion/cross_attention_control.py
ldm/models/diffusion/shared_invokeai_diffusion.py

Reduce likelihood of out of memory error when doing `.swap`, and be more careful about clearing up after ourselves in case OOM does actually occur

Fix cross attention control oom

---

ldm/invoke/prompt_parser.py
tests/test_prompt_parser.py

Complete re-write of the prompt parsing logic to be more readable and logical, and therefore also hopefully easier to debug, maintain, and augment. In the process it has also become more robust to badly-formed prompts.
The current code for the prompt parser was literally my first time using `pyparsing`. The new logic solves a bunch of problems stemming from that.

Rebuild prompt parsing logic

---

ldm/invoke/txt2mask.py

Tested with `!mask outputs/img-samples/000025.2634654006.png -tm hair`
selected
deselected
masked

Option to directly invert the grayscale heatmap - fix

---

ldm/invoke/restoration/outcrop.py

```
│    28 │   │   self.generate._set_sampler()                                   │
│    29 │   │                                                                  │
│    30 │   │   def wrapped_callback(img,seed,**kwargs):                       │
│ ❱  31 │   │   │   image_callback(img,orig_opt.seed,use_prefix=prefix,**kwarg │
│    32 │   │                                                                  │
│    33 │   │   result= self.generate.prompt2image(                            │
│    34 │   │   │   orig_opt.prompt,                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not callable
```

Prevent outcrop error when no callback is supplied

---

ldm/modules/diffusionmodules/util.py

Use array slicing instead of `np.arrange` to calculate `ddim_timesteps`. The new implementation provides better readability and performance (I have bench-marked both methods with `timeit` module and the array slicing method is slightly faster).

Use array slicing to calc ddim timesteps

---

ldm/invoke/prompt_parser.py
tests/test_prompt_parser.py

With the current parser logic, `a fantasy forest landscape "".swap("in winter")` works but `a fantasy forest landscape ().swap("in winter")` (note empty parentheses) does not. 
These should both work. This pull request fixes that.

Fix for parser error doing `.swap` on any empty target `()`

---

docs/installation/INSTALL_MAC.md

Instructions tell user to use the --no_interactive flag, but this will bypass the model downloading step. This flag was intended for use in automated scripts such as CI workflows.

remove --no_interactive from preload_scripts.py example

---

requirements-lin-win-colab-CUDA.txt
requirements.txt

This commit addresses two bugs:
1) invokeai.py crashes immediately with a message about an undefined
attritube sigKILL (closes #1288). The fix is to pin torch at 1.12.1.
2) Version 1.4.2 of basicsr fails to load properly on Windows, and is
a requirement of realesrgan, however 1.4.1 works. Pinning basicsr
in our requirements file resulted in a dependency conflict, so I
ended up cloning realesrgan into the invoke-ai Git space and changing
the requirements file there.
If there is a more elegant solution, please advise. 
This PR needs testing on a Windows platform. Both a desktop install and the docker build need to be tested. I will wait until I get positive confirmation before merging.

HOTFIX: fix Windows library dependency issues

---

ldm/invoke/args.py
ldm/invoke/generator/txt2img2img.py

I've been playing around with the hires option.
My impression was that it should produce the same thing as doing the small image generation and then img2img with `--fit` and the larger H/W. 
```
bacon sushi -s 100 -S1
bacon sushi -s 100 -S1 -I outputs/img-samples/000001.1.png -H 1024 -W 1024 --fit
```
should do the same thing as
```
bacon sushi -s 100 -S1 -H 1024 -W 1024 --hires_fix
```
It's close but not the same.
However when I tried adding a low strength value, things got weird.
```
bacon sushi -s 100 -S1 -H 1024 -W 1024 --hires_fix --strength 0.01
```
gave me a blurry mess:
Compared to
```
bacon sushi -s 100 -S1 -I outputs/img-samples/000001.1.png -H 1024 -W 1024 --fit --strength 0.01
```
My suspicion is that it looks like it was way downscaled before being upscaled, so I tried …

Hires problems at low strength.

---

ldm/generate.py
ldm/invoke/generator/inpaint.py

Supports optionally resizing the image to a larger resolution for inpainting, then scaling back down before color correction and recombination. Produces better results when inpainting small areas.

Support inpainting at a different size than the input image

---

ldm/models/diffusion/cross_attention_control.py
ldm/models/diffusion/shared_invokeai_diffusion.py
ldm/modules/attention.py

This pull request fixes #1362 by making cross attention control manage VRAM in a better way. It also enables cross-attention control on larger outputs - it still uses a lot of VRAM but is more active and aggressive about offloading attention slices to system RAM when VRAM fills up. 
(When this happens the performance becomes quite bad quite quickly - this is expected, and in non VRAM-constrained use cases performance should not be impacted.)

Fix crash by improving VRAM usage patterns when doing `.swap()`

---

ldm/invoke/args.py
ldm/invoke/generator/txt2img2img.py

Reverts invoke-ai/InvokeAI#1299
This is causing tensor mismatch errors at certain combinations of width and height.

Revert "Hires problems at low strength."

---

ldm/invoke/readline.py
scripts/invoke.py

- Script will now offer the user the ability to create a minimal models.yaml and then gracefully exit.
- Closes #1420
This is not the most graceful implementation, but it works in a pinch.

fix invoke.py crash if no models.yaml file present

---

ldm/modules/attention.py

Fixes #1426 by removing torch cuda clear, which didn't appear to be reducing VRAM usage, but was significantly impacting performance (e.g. this reduces generation time from 15s to 6s in my testing).

Fix perf issue from cache clear

---

ldm/invoke/model_cache.py
scripts/invoke.py

Due to a logic bug, models imported via `!import_model` and marked `default=true` did not remove the default tag from the previous default model. This PR corrects this bug.

prevent two models from being marked default in models.yaml

---

docs/features/CLI.md
docs/features/POSTPROCESS.md
ldm/invoke/args.py
ldm/invoke/restoration/base.py
ldm/invoke/restoration/gfpgan.py
scripts/invoke.py
scripts/legacy_api.py
scripts/preload_models.py

gfpgan_dir is no longer needed because we are now installing gfpgan directly to the env. The user can just pass the path to the model file directly now using `--gfpgan_model_path` if they want to use a custom path for the checkpoint.

Remove gfpgan_dir

---

ldm/invoke/conditioning.py
ldm/models/diffusion/cross_attention_control.py
ldm/models/diffusion/shared_invokeai_diffusion.py

I was working on attention control in #1384, started making a few changes to improve the typing and make it easier to work with. Then the whitespace changes touched so many lines it seemed worth separating out these refactoring operations to this PR so they don't get mixed up with other functional changes.
It would be helpful to merge this to `development` before continuing work on attention control in #1384
The github diff isn't good at showing these together since they changed whitespace on so many lines. It may be easier to review by looking at the individual commits, and/or toggling the "hide whitespace differences" option in the view.

refactor(cross_attention_control): remove outer CrossAttentionControl class

---

scripts/invoke.py

Weirdly, I'm not even on a Mac or using a special Python distro.  Just plain old Debian stable and a plain old venv.

Fix CWD being removed from path again.  Refixes #723 again

---

installer/install.bat
installer/install.sh

This pull request will change the URL for the installer to `/refs/heads/main.tar.gz` so that it does not need to be updated every time main changes.

HOTFIX: change installer download repo to main.tar.gz

---

docs/features/EMBIGGEN.md
ldm/generate.py
ldm/invoke/args.py
ldm/invoke/server.py

Added the ability to adjust the number of steps (strength) that `--embiggen` uses, defaulting to the 0.4 that it was originally set to.

Feature: embiggen_strength

---

installer/install.sh
source_installer/install.sh

On macOS, patch python sysconfig just before creating the venv so that extensions (greenlet & grpcio) can build. 
Ref https://github.com/indygreg/python-build-standalone/issues/103, in particular the solution from @alecthomas posted here: https://github.com/indygreg/python-build-standalone/issues/103#issuecomment-1234942425
To use: checkout, cd into `installer`, run `create_installers.sh`, copy `InvokeAI-mac.zip` into an empty folder outside of your existing invokeAI install, unzip it and run `install.sh`.

Fix macOS install.sh by patching sysconfig

---

installer/install.sh

Moved the -O from after the file to after the tar command for compatibility with macOS. 
See https://github.com/invoke-ai/InvokeAI/issues/1500
Signed-off-by: Kevin Coakley <kcoakley@sdsc.edu>

Fix install.sh tar command 

---

installer/install.sh

This has been merged into development and is now proposed as a hotfix to `main`
Moved the -O from after the file to after the tar command for compatibility with macOS
Signed-off-by: Kevin Coakley <kcoakley@sdsc.edu>

Fix micromamba tar command for macOS

---

backend/invoke_ai_web_server.py
ldm/invoke/model_cache.py
ldm/invoke/restoration/outcrop.py

- dangling debug messages in several files, introduced during testing of the external root directory
- these need to be removed before they are interpreted as errors by users

remove several debugging messages

---

ldm/invoke/CLI.py

When started from web GUI, '.' is expanded as .../InvokeAI and sometimes .../Invoke/Idm. 
causing https://github.com/invoke-ai/InvokeAI/issues/1522
This doesn't happen from the CLI.
This PR expands '.' when first set.

Fix issues with Globals.root not being consistent when run using web gui.

---

ldm/invoke/model_cache.py
scripts/configure_invokeai.py

The step in which the new models.yaml file replaces the old one was crashing on Windows due to the fact that on Windows, the os.rename() function will refuse to replace an existing file, unlike the behavior on Linux and Mac. The os.replace() function, which was introduced in python3, supposedly fixes this.
**Please test on Windows 10 to see if this really does fix the problem.**

fixes configure_invokeai.py crash on Windows systems

---

ldm/invoke/model_cache.py
scripts/load_models.py
setup.py

Currently `development` will neither install cleanly nor run on Python 3.9. There are two fixes here:
1. setup.py has been updated to refer to `configure_invokeai.py`, which is the new name for `load_models.py`
2. `load_models.py` has been installed as an alias of `configure_invokeai.py` to avoid other related breakage
3. The use of the union typing hint "|" in `model_cache.py` only works on Python 3.10 or higher. I have replaced with `Union[]` to work on earlier versions.

High priority PR: Fix broken setup and install

---

scripts/configure_invokeai.py

This corrects behavior of --no-interactive, which was in fact asking for interaction!
New behavior:
If you pass --no-interactive it will behave exactly as it did before and completely skip the downloading of SD models.
If you pass --yes it will do almost the same, but download the recommended models. The combination of the two arguments is the same as --no-interactive.

fix non-interactive behavior of config_invokeai.py

---

installer/install.bat
installer/install.sh
installer/requirements.in
setup.py

This is the same as PR #1537 except that it removes a redundant `scripts` argument from `setup.py` that appeared at some point.
I also had to unpin the github dependencies in `requirements.in` in order to get conda CI tests to pass. However, dependencies are still pinned in `requirements-base.txt` and the environment files, and install itself is working. So I think we are good.

Installer final tweaks

---

installer/install.bat
installer/install.sh
installer/requirements.in
setup.py

This allows populating setup.py's 'install_requires' directly from 'requirements.in'
- setup.py:
- read 'requirements.in' instead of 'requirements.txt'
- add correct upstream pytorch repo to "dependency_links"
- requirements.in:
- append "name @" to git packages
- fix torch repo URL -> 'download.pytorch.org/whl/torch_stable.html'
ALso tweaked some logging and formatting here and there

feat(install): unify setup.py, requirements.in, pip

---

ldm/invoke/model_cache.py
ldm/modules/image_degradation/utils_image.py
scripts/preload_models.py

Windows does not support an atomic `os.rename()` operation, which causes a crash during model importation when the code tries to rename the temporary `models.yaml.temp ` file to `models.yaml`. 
This PR changes the call to `os.replace()`, which does the same thing.
Note that I'm making this a hotfix against `main` as multiple users have run into this bug. The fix is already accepted in `development`.

prevent crash that occurs when changing models.yaml on windows systems

---

ldm/invoke/model_cache.py

dict.update is more performant, on the side note, we can use something like
```
from typing import TypedDict
class ModelInfo(TypedDict):
status: str
description: str
def list_models(...) -> dict[str, ModelInfo]:
...
```
edit: or maybe we can use Dict from the typing module for compatibility reasons*

make the docstring more readable and improve the list_models logic

---

ldm/invoke/CLI.py
ldm/invoke/args.py
ldm/invoke/generator/inpaint.py
ldm/invoke/globals.py

This feature was added to prevent the CI Macintosh tests from erroring out when patchmatch is unable to retrieve its shared library from github assets.

add a --no-patchmatch option to disable patchmatch loading

---

ldm/invoke/CLI.py
ldm/invoke/concepts_lib.py

Fix #1599 by relaxing the `match_trigger` regex

---

ldm/invoke/generator/base.py
ldm/invoke/restoration/realesrgan.py

ESRGAN is known to have poor handling of RGBA images: https://github.com/xinntao/ESRGAN/issues/18
If we give it an RGBA image, it will output an image where the alpha channel has partial transparency across many pixels. 
The simplest solution is to convert the image to RGB before handing to ESRGAN (that is what this PR does).
Preserving alpha (of an input image with some transparency) is tricky. An *approximation* of the output alpha channel can be created by simply resizing the input image's alpha channel, but this isn't quite correct, because the RGB data is modified during upscaling. Other approaches are discussed in the above ESRGAN issue. 
Because there is no good method I could find with my brief search, and because I don't think it is really useful for our case, one effect of this …

Fixes for #1604

---

docker-build/Dockerfile
docker-build/build.sh
docker-build/run.sh
docs/installation/INSTALL_DOCKER.md

Debloated and updated Dockerfile:
- less options more but more userfriendly
- better Entrypoint to simulate CLI usage
- without command the container still starts the web-host
also debloated build.sh and updated run.sh

Debloat-docker

---

source_installer/install.sh

* refer to the platform as 'osx' instead of 'mac', otherwise the composed URL to micromamba is wrong.
* move the `-O` option to `tar` to be grouped with the other tar flags to avoid the `-O` being interpreted as something to unarchive.

Fix installer script for macOS.

---

ldm/invoke/generator/omnibus.py

- error was "Omnibus object has no attribute pil_image"
- closes #1596

fix error when inpainting using runwayml inpainting model

---

.github/workflows/test-invoke-conda.yml
.github/workflows/test-invoke-pip.yml
ldm/invoke/args.py

The NSFW filter apparently causes invoke.py to crash during CI testing, possibly due to out of memory errors. This workaround disables NSFW model loading.

disable NSFW checker loading during the CI tests

---

ldm/invoke/readline.py

This corrects a small bug in the readline parser which resulted it in it not being able to find its history file if user specified a non-standard image outputs directory.

fix missing history file in output director

---

ldm/invoke/readline.py

Some users have been complaining that the CLI "freezes" for a while before the invoke> prompt appears. I believe this is due to internet delay while the concepts library names are downloaded by the autocompleter. I have changed logic so that the concepts are downloaded the first time the user types a < and tabs.

defer loading of Hugging Face concepts until needed

---

binary_installer/install.bat.in

This corrects the incorrect use of shell-style comment symbols in the Windows binary installer .bat script. I wonder which Linux user entered those comments? H'mmmmm :-)

fix incorrect syntax for .bat

---

scripts/configure_invokeai.py

1. Some users were leaving whitespace at the end of their root directories or ending them with a backslash. This caused the root directory to become unusable. This removes whitespace and backslashes from the end of the directory names.
Note that more needs to be done to cleanse the input, but for now this will cover the cases we have seen so far in the wild.
2. Changed the Hugging Face token prompt to tell Windows users how to paste into the console window.

configure_invokeai.py usage improvements

---

docs/installation/INSTALL_INVOKE.md
docs/installation/INSTALL_SOURCE.md

Hotfix to change the documentation download links to point to the release candidate. I will bypass branch protections to push this out.

change download links to release candidate

---

docs/installation/INSTALL_INVOKE.md

Updates docs release link to `latest`
Was rc4. Now `latest`.

Updates docs release link to `latest`

---

binary_installer/install.bat.in
binary_installer/install.sh.in
binary_installer/invoke.sh.in
source_installer/install.bat.in
source_installer/invoke.sh.in

- The previous fix for the "install in Windows system directory" error would fail if the path includes directories with spaces in them. This fixes that.
- In addition, addressing the same issue in source installer, although not yet reported in wild.
- Add back MPS fallback for M1 machines.

more installer fixes

---

binary_installer/install.sh.in

This one addresses an error in which the installer is unable to copy `invoke.sh.in` to `invoke.sh`

Yet more installer fixes

---

docs/installation/index.md

Since the binary installer is unstable, this PR will remove references to it.
I propose this for 2.2.3

remove references to binary installer from docs

---

source_installer/invoke.sh.in

extra spaces cause syntax errors; found by https://discord.com/channels/1020123559063990373/1048313657177677824/1048319303390343178
Fixes #1717

(installer) fix syntax error in invoke.sh.in

---

docs/installation/INSTALL_SOURCE.md

The installation guide is pointing to an outdated link for downloading the installer files. This fixes that problem.

fix link in documentation

---

docs/installation/INSTALL_SOURCE.md

The source installer pages tell people that the binary installer is foolproof. I deleted this sentence.

Remove reference to binary installer

---

docs/installation/INSTALL_SOURCE.md
docs/installation/index.md
source_installer/install.sh.in

- Add Xcode installation instructions to source installer walkthrough
- Fix link to source installer page from installer overview
- If OSX install crashes, script will tell Mac users to go to the docs to learn how to install Xcode

documentation fixes for 2.2.3

---

README.md
docs/installation/INSTALL_SOURCE.md

Currently a few clicks are needed to get to the source installer, and a couple more clicks to get to the installer bundle. *Proposing* to update links to point more closely to the source installer, and to link installer bundles directly from Github releases, at least for 2.2.3, in an attempt to smooth over first-time installation experience.
NB - if we remove the version from the filenames, we can have an always-up-to-date link to the latest release assets without having to build the docs.

Modify installer links to point closer to the source installer

---

README.md
docs/index.md

Several users have been trying to run InvokeAI on GTX 1650 and 1660 cards. They really can't because these cards don't work with half-precision and only have 4-6GB of memory. Added a warning to the docs (in two places) about this problem.

add documentation warning about 1650/60 cards

---

README.md

also "Macintosh" → "macOS" to improve "We Support macOS Properly And Not Halfassed Like Other OSS Projects" signalling

Make install instructions discoverable in readme

---

ldm/invoke/globals.py
scripts/configure_invokeai.py

This PR adds the following improvements:
Ensures that the SD weights download proceeds in a truly non-interactive fashion when the `--yes` flag is used and a valid authentication token is present in any of the supported locations (env vars or cached).
Tested as follows:
- `HUGGING_FACE_HUB_TOKEN` env var is not empty:
- with `--yes`: weights download proceeds; token is not persisted in cache
- without `--yes`: weights download proceeds without an additional prompt; token is not persisted in cache
- `HUGGINGFACE_TOKEN` env var is not empty:
- same behaviour as with the official var (token not persisted)
- Env vars not present without `--yes` flag: user is prompted for the token, token is cached only if valid (same as current behaviour)
- Env vars not present with `--yes` flag: weights …

Non-interactive model download (support `HUGGINGFACE_TOKEN`)

---

binary_installer/install.bat.in
binary_installer/invoke.bat.in
binary_installer/invoke.sh.in
source_installer/invoke.bat.in
source_installer/invoke.sh.in

- Pass command-line arguments through to invoke.py via the .bat and .sh scripts.
- Remove obsolete warning message from binary install.bat
- Make sure that current working directory matches where .bat file is installed
- Please TEST this on a windows system

stability and usage improvements to binary & source installers

---

ldm/invoke/conditioning.py

there is currently an off-by-one issue that causes `.swap()` to operate on tokens at one index earlier than it is supposed to. 
prompt token sequences begin with a "beginning-of-sequence" marker `<bos>` and end with a repeated "end-of-sequence" marker `<eos>` - to make a default prompt length of `<bos>` + 75 prompt tokens + `<eos>`. the `.swap()` code was failing to take the column for `<bos>` at index 0 into account. the changes here do that, and also add extra handling for a single `<eos>` (which may be redundant but which is included for completeness).
based on my understanding and some assumptions about how this all works, the reason .swap() nevertheless seemed to do the right thing, to some extent, is because over multiple steps the conditioning process in Stable Diffusion operates …

fix off-by-one bug in cross-attention-control

---

binary_installer/invoke.sh.in

This PR ensures that when the binary installer's `invoke.sh` script runs, it changes the current working directory to match its install location.
The same change is also found in PR #1786

invoke script cds to its location before running

---

configs/stable-diffusion/v1-inference.yaml

This corrects a regression in loading of these models due to a change of the embedding_manager parameter `num_vectors_per_token`
Reverting to the original version (1) does not seem to affect concept embeddings.
Fixes #1718

Make PaperCut and VoxelArt models load again

---

ldm/invoke/CLI.py

It was not being assigned if the supplied path is correct crashing the app on load if loading with embeddings.

Fix --embedding_directory / --embedding_path not working

---

.dockerignore
.github/workflows/build-cloud-img.yml
docker-build/Dockerfile.cloud
docker-build/Makefile
docs/installation/INSTALL_DOCKER.md

- Adds a new `Dockerfile.cloud` intended for use with remote deployments. Extensively tested on Linux (x86_64 / CUDA), but not macOS or Windows. (Hence a new Dockerfile.cloud, to avoid surprises to users of current docker setup).
- Docker image does not bake in the models, and is 4 layers deep (2.5GB compressed, mainly `pytorch`). Utilizes docker build-time cache and multi-stage builds. Requires Docker Buildkit for caching (`DOCKER_BUILDKIT=1`).
- The runtime directory (`INVOKEAI_ROOT` which contains models, config, etc) is expected to be mounted into the container, allowing for seamless upgrades with no data loss
- Adds Github actions for automated image building and pushing. No special privileges or secrets are required for this. If this is merged, it will continuously build & push a …

Optimized Docker build with support for external working directory

---

.github/workflows/build-cloud-img.yml

Modifies the cloud image build workflow;  rules are as follows:
- image will be built on all pushes to `main`, all tags starting with `v`,  and all pull requests.
- image will NOT be pushed on any pull requests.
- do NOT perform docker login on pull requests.
- PR workflows from new contributors will need approval to run. Workflows from forked repo will run in the context of the fork first, and will not have access to any secrets in this repo. Collaborators can examine them before approving workflow runs on this repo.
Image tags added as follows:
- `:latest` for the last commit on the repo (any branch or tag, even though it's just `main` now)
- `:edge` for every last commit on `main` (like `:latest` but *only* for `main`)
- `:main` (or other <branch_name>, (even thouh we only run this on …

Fix `docker push` github action and expand with additional metadata

---

docs/installation/INSTALL_JUPYTER.md

* The link pointed to https://github.com/invoke-ai/InvokeAI/blob/main/notebooks/Stable-Diffusion-local-Windows.ipynb which does not exist so it has been replaced with https://github.com/invoke-ai/InvokeAI/blob/main/notebooks/Stable_Diffusion_AI_Notebook.ipynb
* Add buttons for running on Colab 
* Tried adding running InvokeAI on Binder but the error was: ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5 ERROR: Could not find a version that satisfies the requirement clipseg (from invokeai) (from versions: none) ERROR: No matching distribution found for clipseg
Removing intermediate container 25be65428187
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir .' returned a non-zero code: 1
`## Running Online On …

Fix Broken Link To Notebook

---

ldm/invoke/model_cache.py

Merged models from auto11 merge board are flat for some reason. Current behavior of invoke is not changed by this modification.

Account for flat models

---

source_installer/invoke.bat.in

Without locally scoped (to the script) environment variables, this script can only be run once and then you need to start a new cmd session to get a clean environment.
Surrounding the script with setlocal/endlocal achieves this.
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/setlocal https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/endlocal

Update invoke.bat.in isolate environment variables

---

docs/installation/INSTALL_PATCHMATCH.md
environments-and-requirements/environment-lin-aarch64.yml
environments-and-requirements/environment-lin-amd.yml
environments-and-requirements/environment-lin-cuda.yml
environments-and-requirements/environment-mac.yml
environments-and-requirements/environment-win-cuda.yml

* Added Arch Linux Specific Instructions to properly install Patchmatch.
* Fixed a codeblock not being properly closed in the INSTALL_PATCHMATCH.md file.
* Removed the "-e" flag on PyPatchMatch in all environment-xxx-yyy.yaml files and the INSTALL_PATCHMATCH.md file. 
Keeping the "-e" flag appears to cause an "RemoteNotFound" Error. This may break PyPatchMatch however allows successful installation of InvokeAI via conda. 
Screenshots before and after i made the changes:
* Added Quotes ( " ) around the PyPatchMatch git link.  
Reason for this is to avoid an error where ZSH sees the given link as regex, causing the command to not execute properly

Arch Linux Specific PatchMatch Instructions & fixing conda install on linux

---

ldm/invoke/generator/img2img.py

This PR attempts to ensure `--free_gpu_mem` option work in `img2img.py`. 
The solution is similar to the procedure in `txt2img.py`. I added condition check to see if `--free_gpu_mem` is enabled. If so, then move the loaded diffusion model into the CPU (the RAM, I presume?).

Make force free GPU memory work in img2img

---

ldm/generate.py

In the event where no `init_mask` is given and `invert_mask` is set to True, the script will raise the following error:
```bash
AttributeError: 'NoneType' object has no attribute 'mode'
```
The new implementation will run image inversion only when both variables are valid.

Fix error when init_mask=None and invert_mask=True

---

.github/workflows/test-invoke-conda.yml
.github/workflows/test-invoke-pip.yml
environments-and-requirements/requirements-base.txt
environments-and-requirements/requirements-win-colab-cuda.txt
ldm/invoke/args.py

this adds windows to the test workflows, but I disabled to run the tests themselves since for some reason the windows runners do not have enough memory (even when specs are the same as for linux https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

Add windows to test workflows

---

environments-and-requirements/requirements-base.txt

The new diffusers update requires an update to transformers, but the transformers update causes the NSFW checker to fail in a new way. Until this is resolved, I am pinning diffusers to the older working version.

pin diffusers to 0.9.0

---

backend/invoke_ai_web_server.py
ldm/generate.py
ldm/invoke/CLI.py
ldm/invoke/conditioning.py
ldm/invoke/generator/base.py
ldm/invoke/generator/txt2img.py
ldm/invoke/prompt_parser.py
ldm/invoke/readline.py
ldm/models/diffusion/cross_attention_control.py
ldm/models/diffusion/cross_attention_map_saving.py
ldm/models/diffusion/ksampler.py
ldm/models/diffusion/shared_invokeai_diffusion.py
ldm/modules/attention.py

This pull request enables the display of per-token attention maps after generating an image.
- `attentionMaps` (base64 image, size `width/8 x 77*height/8`), and
- `tokens`, see below.
Typical content of the `tokens` array is, eg for prompt `a fluffy miyazaki dog`, an array: `['a</w>', 'fluffy</w>', 'mi', 'yaz', 'aki</w>', 'dog']`. The `</w>` strings represent "end-of-word". With this implementation, to match tokens to fragments of the input prompt text in the input box, the frontend code is going to have to crawl through the prompt and do a best-fit match of these tokens to the prompt string.

Save and display per-token attention maps

---

configs/models.yaml.example

The inpainting entry should have width and height defined which are mandatory.

Fix Inpainting Model entry in models.yaml.example

---

backend/invoke_ai_web_server.py
binary_installer/requirements.in
environments-and-requirements/requirements-base.txt

Fixes GUI not working on the newer versions of flaskwebgui due to a changed syntax.
@lstein I updated the version requirement for flaskwebgui to use the latest. There are 3 references in the requirement files in the binary installers that I did not update. I'm not sure if they need updating at this point. I'll let you decide on that.
If they don't, then this PR is good to go.

Fix GUI not working

---

installer/install.bat.in
installer/install.sh.in

- This fixes the .bat and .sh file URLs for the installer's InvokeAI source code download and is needed for the 2.2.4 release.

fix InvokeAI download URLs

---

ldm/generate.py
ldm/invoke/generator/txt2img.py
ldm/invoke/generator/txt2img2img.py

Unload cond_stage_model on free_gpu_mem option is setted
#1897

Reduce more memories on free_gpu_mem option

---

ldm/generate.py
ldm/invoke/generator/inpaint.py

Bug fix for issue #1937 
#1937

Load model in inpaint when using free_gpu_mem option

---

scripts/configure_invokeai.py

The first few lines directed the user to run `python scripts/invoke.py`, which is not exactly correct anymore, and a holdover from previous versions.
Improves and clarifies the postscript messaging.

Improves configure_invokeai.py postscript

---

ldm/invoke/globals.py

This commit fixes the root search logic to be as follows:
1) The `--root_dir` command line argument
2) The contents of environment variable INVOKEAI_ROOT 
3) The VIRTUAL_ENV environment variable, plus '..' (yielding the parent of .venv, which is `invokeai`)
4) $HOME/invokeai
(3) is the new feature. Since we are now recommending to install InvokeAI and its dependencies into the .venv in the root directory, this should be a reliable choice.
This addresses multiple discord bug reports and Issue #1932 . The scenario it fixes is when the user runs `invoke.py` from outside the runtime directory, the script can't find its runtime directory and calls `configure_invoke.py` to rebuild it. Configure does this, but the `.venv` and `install.sh` are still inside the original runtime directory. …

add logic for finding the root (runtime) directory

---

.github/workflows/build-container.yml
docker-build/Dockerfile
docker-build/run.sh
ldm/invoke/CLI.py

Updating the `build-container.yml` Workflow to also push images (@ebr I also already PoC'ed that it would work to push both Dockerfiles with this single Workflow)
Also introducing a new env var: INVOKE_MODEL_RECONFIGURE
With this it is possible that the container pulls necesary Model Files without Interaction. If someone wants to alter configuration he has two easy options:
- SSH into the container (tested on runpod)
- create a fork
And if someone asks "whats the difference with the cloud image" - well, I think it has a inappropriate name now and should be renamed to "patchmatch". The Difference is that it comes with patchmatch but therfore only works on amd64, while the Dockerfile is at least tested on amd64 and arm64

Make Dockerfile cloud ready (tested on runpod)

---

.github/workflows/test-invoke-conda.yml
.github/workflows/test-invoke-pip.yml

configured to only cancel workflows in PRs, but not on main branch
origins in #1933, but opitmized to not cancel workflows of non PRs

add concurrency to test actions

---

ldm/invoke/generator/base.py

path variable should be defined even before 
"if not path:"
So a small fix for python for this problem:

Fix: define path as None before usage

---

docker-build/env.sh
docker-build/run.sh
docs/installation/INSTALL_DOCKER.md

This permits you to use GPUs by running the docker script like:
`GPU_FLAGS="--gpus all" ./docker-build/run.sh`
If you don't set the GPU_FLAGS it is ignored, and therefore does not affect running docker on the CPU for hosts without a GPU.

Permit usage of GPUs in docker script

---

ldm/invoke/conditioning.py

also handle blends properly; fixes #1908

fix attention maps crash by properly restricting token sequence length

---

README.md

@lstein - Assuming we're having people merge to main (still calling out doing that AND having an auto-merge is high risk), updating directive to do so.

update Contributors directive to merge to main

---

ldm/invoke/CLI.py

- The invoke.py script now checks that the root (runtime) directory contains the expected config/models.yaml file and if it doesn't exits with a helpful error message about how to set the proper root.
- Formerly the script would fail with a "bad model" message and try to redownload its models, which is not helpful in the case that the root is missing or damaged.
The error message on a bad root looks like this:
```
** Error. The file /home/lstein/badroot/configs/models.yaml could not be found.
** Please check the location of your invokeai directory and use the --root_dir option to point to the correct path.
** This script will now exit.
```

better error reporting when root directory not found

---

ldm/invoke/args.py

This PR adds a `--weight_folders` argument to invoke.py. Using argparse, it adds a "weight_folders" attribute to the Args object. It is intended to support @blessedcoolant 's weight file autoscan feature, and can be used like this:
```
'''test.py'''
from ldm.invoke.args import Args
args = Args().parse_args()
for folder in args.weight_folders:
print(folder)
```
Example output:
```
python test.py --weight_folders /tmp/weights /home/fred/invokeai/weights "./my folder with spaces/weight files"
/tmp/weights
/home/fred/invokeai/weights
./my folder with spaces/weight files
```

add an argument that lets user specify folders to scan for weights

---

ldm/invoke/concepts_lib.py

Before making a concept download request to HuggingFace, the concepts library module now checks the concept name against a downloaded list of all the concepts currently known to HuggingFace.  If the requested concept is not on the list, then no download request is made.

avoid leaking data to HuggingFace

---

frontend/src/features/options/store/optionsSlice.ts

Addresses #2049 but not other cases where the stored value is 0 (e.g. perlin noise). This should be investigated more thoroughly and something better put into place.

Updated to pull threshold from an existing image even if 0

---

docs/installation/010_INSTALL_AUTOMATED.md
docs/requirements-mkdocs.txt
mkdocs.yml

Documentation was recently reorganized, which resulted in broken links from search engines.
This PR fixes the issue by adding a `mkdocs-redirects` plugin and a config to automatically serve redirects to new pages.

Add redirects for moved pages

---

.github/workflows/test-invoke-conda.yml
.github/workflows/test-invoke-pip.yml
docs/features/CONCEPTS.md
docs/installation/020_INSTALL_MANUAL.md
ldm/invoke/CLI.py
scripts/configure_invokeai.py
setup.py

- Fixes links to the Stable Diffusion weights license agreement. Prints a message about implicit agreement if the user used the `--yes` flag. Shortens/simplifies messaging and makes the licensing blurb more visible.
- The configuration script will no longer exit if the Huggingface token is not provided. Instead, we show a message about the purpose of the token, with a link to updated documentation, and offer to proceed with the download.
- Always caches the HF token if one is found or provided
- Prints more detailed messaging about where the token was found (or not)
- Validates the token, if exists, by logging in to HuggingFace. Offers an option to re-enter it on failure. This will prevent caching of invalid tokens which are hard for the user to reset.
- Deprecates the …

Relax Huggingface login requirement during setup

---

ldm/generate.py

Prevents having to reload the model every time - speedup while debugging but also nice for users hitting minor non-critical bugs.

Don't crash CLI on exceptions

---

installer/create_installer.sh
installer/install.bat.in
installer/templates/update.bat.in
installer/templates/update.sh.in

install.bat was copying the requirements file into the install folder twice, causing an error message on the second try. This fixes the issue.

remove redundant code line

---

ldm/generate.py

This was put in the wrong place and appears to have broken the WebUI cancellation system.

Revert "Don't crash CLI on exceptions"

---

scripts/configure_invokeai.py

Also fixes the case where HF token is not set, but we're trying to save it. We're now handling all of the HF authentication elsewhere, so this isn't necessary.
Fixes #2077

Fix the configure script crash when no TTY is allocated (e.g. a container)

---

installer/install.sh.in
ldm/invoke/CLI.py

- Selecting `~/Data/myapps/` when prompted to choose a location would create a `./~/Data/myapps` directory (a '~' subdir in the installer directory). This is now properly expanded to the absolute path
- print out the abs path of the install location instead of relative
- point installer at `2.2.5-rc1` archive instead of `2.2.4`
- squash the double slash before `/invokeai` (if it was entered so by the user)

rc2.2.5 (install.sh) relative path fixes

---

ldm/invoke/model_cache.py

- A couple of users have reported that switching back and forth between ckpt models in RAM is causing a "GPU out of memory" crash. Traceback suggests there is actually a CPU RAM issue.
See https://discord.com/channels/1020123559063990373/1048399553142984784
- This change performs a round of garbage collection just prior to the point where the crash occurs. It shouldn't actually fix anything, but at least one user with the error reports that it stopped the crash, so I'm folding it into `main`. It shouldn't break anything.

attempt to address memory issues when loading ckpt models

---

installer/install.sh.in

Some users are unable to run the installer because the line 124 in install.sh:
`ROOTDIR=$(python -c "from pathlib import Path; print(Path('${ROOTDIR}').expanduser().resolve())")`
expects an executable in the path named `python`, or else it will fatally crash.
Some users have python installed as `python3` on their systems and not simply `python`, thus causing the error. 
Prior sections of the installer script already find the full path to a user's python executable in a variable called `$PYTHON`, so this change simply adds that discovered python in place of the hard-coded `python` call.
This will fix #2166

Explicitly call python found in system

---

.gitignore
ldm/invoke/concepts_lib.py
ldm/invoke/readline.py

**Added support for detecting & adding local embeddings to list of concepts.** 
- When autocomplete prompted with <+tab, `list_concepts() ` in `Concepts` will search for user-added .bin or .pt files in `/embeddings` directory and add them to list of concepts
- User can autocomplete or directly type their local embedding name, and it will be handled on generation by `embedding_manager` 
- User can add embeddings during CLI runtime and autocompleter will be able to query it.

Local embeddings support (CLI autocomplete) 

---

environments-and-requirements/requirements-base.txt

`import login` only works in huggingface-hub >= 0.11.0
Fixes https://github.com/invoke-ai/InvokeAI/issues/2149

Require huggingface-hub version 0.11.1

---

environments-and-requirements/requirements-lin-amd.txt
environments-and-requirements/requirements-lin-arm64.txt
environments-and-requirements/requirements-lin-cuda.txt
environments-and-requirements/requirements-mac-mps-cpu.txt
environments-and-requirements/requirements-win-colab-cuda.txt

since torch versions <0.13.1 have a critical security issue
maybe this is the right time to get rid of the conda environments

update python requirements

---

docs/installation/010_INSTALL_AUTOMATED.md

- Removed links from the install instructions to the installer zip files.
- Replaced "2.2.4" with "2.X.X" globally, to avoid the docs going out of date.

tweak install instructions

---

ldm/invoke/ckpt_generator/txt2img2img.py

missing Cktp in ldm/invoke/ckpt_generator/txt2img2img.py line 15
was causing Generator is not defined generating image with a ckpt file

Missing text in Dev/diffusers ckpt_generator/txt2img2img.py

---

installer/create_installer.sh
installer/install.bat.in

Two small fixes:
1. create_installers.sh now asks before tagging and committing the current repo
2. trailing whitespace removed from user-provided location of invokeai directory in install.bat

enhance the .bat installer

---

environments-and-requirements/requirements-base.txt

Fixes an issue with `configure_invokeai.py` (see https://github.com/invoke-ai/InvokeAI/issues/2323) due to [yesterday's release](https://www.dnspython.org/news/2.3.0/) of `dnspython`.

Pin dnspython version

---

ldm/invoke/generator/diffusers_pipeline.py
ldm/models/diffusion/shared_invokeai_diffusion.py

Pass `step_index` and `total_step_count` reliably when using diffusers codepath.

Fix `percent_through` calculation for cross-attention control

---

.github/workflows/test-invoke-pip.yml
scripts/configure_invokeai.py

Added a --default_only argument that limits model downloads to the single default model, for use in continuous integration.
New behavior
- switch -
--yes      --default_only           Behavior
-----      --------------           --------
<not set>     <not set>              interactive download
--yes         <not set>              non-interactively download all
recommended models
--yes        --default_only          non-interactively download the
default model

[Enhancement] add --default_only arg to configure_invokeai.py, for CI use

---

ldm/generate.py
ldm/invoke/ckpt_generator/base.py
ldm/invoke/ckpt_generator/txt2img.py
ldm/invoke/conditioning.py
ldm/invoke/devices.py
ldm/invoke/generator/base.py
ldm/invoke/generator/diffusers_pipeline.py
ldm/invoke/generator/txt2img.py
ldm/invoke/globals.py
ldm/invoke/model_manager.py
ldm/models/diffusion/cross_attention_control.py
ldm/models/diffusion/shared_invokeai_diffusion.py
ldm/modules/prompt_to_embeddings_converter.py
ldm/modules/textual_inversion_manager.py

- All tensors in diffusers code path are now set explicitly to float32 or float16, depending on the --precision flag.
- autocast is still used in the ckpt path, since it is being deprecated.
- SD2.1 (768 pixel version) **still does not run** in float16 mode.

do not use autocast for diffusers

---

configs/INITIAL_MODELS.yaml
ldm/invoke/CLI.py
ldm/invoke/model_manager.py

- Migration process will not crash if duplicate model files are found, one in legacy location and the other in new location. The model in the legacy location will be deleted in this case.
- Added a hint to stable-diffusion-2.1 telling people it will work best with 768 pixel images.
- Added the anything-4.0 model.

further improvements to initial load

---

ldm/invoke/generator/txt2img2img.py
ldm/invoke/model_manager.py

This commit suppresses a few irrelevant warning messages that the diffusers module produces:
1. The warning that turning off the NSFW detector makes you an irresponsible person.
2. Warnings about running fp16 models stored in CPU (we are not running them in CPU, just caching them in CPU RAM)

[bugfix] suppress extraneous warning messages generated by diffusers

---

ldm/invoke/CLI.py
ldm/invoke/args.py
ldm/invoke/generator/diffusers_pipeline.py
ldm/invoke/globals.py

Starting `invoke.py` with --no-xformers will disable memory-efficient-attention support if xformers is installed.
For symmetry, `--xformers` will enable support, but this is already the default if xformers is available.

[feat] Provide option to disable xformers from command line

---

docs/index.md
docs/installation/070_INSTALL_XFORMERS.md

I've written up the install procedure for xFormers on Linux systems.
I need help with the Windows install; I don't know what the build dependencies (compiler, etc) are. This section of the docs is currently empty.
Please see `docs/installation/070_INSTALL_XFORMERS.md`

Add instructions for installing xFormers on linux

---

ldm/modules/encoders/modules.py
ldm/modules/prompt_to_embeddings_converter.py

Stable Diffusion 2 does not use the eos_token for padding.
Fixes #2378 
Before:
After:
<details>
<summary>metadata</summary>
```json
{
"model": "stable diffusion",
"model_weights": "diffusers-2.1",
"model_hash": "0809e3597225faf22fd48f1034d500b55aea4afffe5ae974c5818bfaadd46ea8",
"app_id": "invoke-ai/InvokeAI",
"app_version": "2.3.0+a0",
"image": {
"prompt": [
{"prompt": "an astronaut riding a horse on mars", "weight": 1.0}
],
"steps": 15,
"cfg_scale": 7.5,
"threshold": 0,
"perlin": 0,
"height": 768,
"width": 768,
"seed": 453168600,
"seamless": false,
"hires_fix": false,
"type": "txt2img",
"postprocessing": null,
"sampler": "k_dpmpp_2",
"variations": []
}
}
```
</details>

fix: use pad_token for padding

---

frontend/src/common/hooks/useSingleAndDoubleClick.ts
frontend/src/features/canvas/components/IAICanvasToolbar/IAICanvasToolbar.tsx
frontend/src/features/canvas/store/canvasSlice.ts
frontend/src/features/tabs/components/UnifiedCanvas/UnifiedCanvasBeta/UnifiedCanvasToolbar/UnifiedCanvasResetView.tsx

Adds double-click to reset canvas view to 100%.
- Adds hook to manage single and double clicks
- Single Click `Reset Canvas View` --> scale to fit, no change to current behaviour
- Double Click `Reset Canvas View` --> set scale to 1

adds double-click to reset view to 100%

---

ldm/invoke/generator/txt2img2img.py

Can test by loading an inpainting model (e.g. `--model=inpainting-1.5`) and running something like
```
naturalist illustration of a seedling sprouting --width 640 --height 832 --hires_fix
```

fix dimension errors when inpainting model is used with hires-fix

---

ldm/invoke/generator/diffusers_pipeline.py

Otherwise the model seems too reluctant to change these areas, even though the mask channel should allow it to.
This makes the solid infill method proposed by #2441 less necessary, though I think there's still a place for an infill method that is faster than patchmatch and more predictable than tiles.
Even with #2441, this PR is still useful because it influences all areas to be painted, not just the infill area.
Fixes #2417

fix(inpainting model): blank areas to be repainted in the masked image

---

ldm/invoke/generator/inpaint.py

A new infill method, **solid:** solid color. currently using middle gray.
Fixes #2417
It seems like the runwayml inpainting model specifically expects those masked areas to be blanked out like this.
I haven't tried the SD 2.0 inpainting model with it yet.

feat(inpaint): add solid infill for use with inpainting model

---

.github/workflows/clean-caches.yml

This helps at least a bit to get rid of all those huge caches

add workflow to clean caches after PR gets closed

---

.github/CODEOWNERS

This PR changes the codeowner for the installer directory from @tildebyte to @ebr due to the former's time commitments.
Further reorganization of the codeowners is pending.

Swap codeowners for installer

---

installer/create_installer.sh
installer/installer.py
ldm/invoke/CLI.py
ldm/invoke/config/invokeai_configure.py
ldm/invoke/model_manager.py
pyproject.toml
scripts/configure_invokeai.py

- Rename configure_invokeai.py to invokeai_configure.py to be consistent with installed script name
- Remove warning message about half-precision models not being available during the model download process.
- adjust estimated file size reported by configure
- guesstimate disk space needed for "all" models
- fix up the "latest" tag to be named 'v2.3-latest'

Configuration script tidying up

---

ldm/invoke/CLI.py
ldm/invoke/generator/inpaint.py

This PR fixes the crash reported at https://discord.com/channels/1020123559063990373/1031668022294884392/1071782238137630800
It also quiets-down the "NSFW is disabled" nag during img2img generation.

Fix crash when text mask applied to img2img

---

invokeai/backend/invoke_ai_web_server.py
ldm/generate.py
ldm/invoke/args.py
ldm/invoke/conditioning.py
ldm/invoke/generator/diffusers_pipeline.py

This allows the --log_tokenization option to be used as a command line argument (or from invokeai.init), making it possible to view tokenization information in the terminal when using the web interface.

Add --log_tokenization to sysargs

---

ldm/invoke/merge_diffusers.py
ldm/invoke/training/textual_inversion.py

- Issue is that if insufficient diffusers models are defined in models.yaml the frontend would ungraciously crash.
- Now it emits appropriate error messages telling user what the problem is.

fix crash in both textual_inversion and merge front ends when not enough models defined

---

ldm/invoke/generator/base.py
ldm/invoke/generator/img2img.py
ldm/invoke/generator/txt2img.py

- get_perlin_noise() was returning 9 channels; fixed code to return noise for just the 4 image channels and not the mask ones.
- Closes Issue #2541

fix crash in txt2img and img2img w/ inpainting models and perlin > 0

---

.github/CODEOWNERS

This PR assigns @Kyle0654 to be the codeowner for the nodes code under `ldm/invoke/app` and `tests/nodes`

make Kyle the codeowner for ldm/invoke/app

---

ldm/invoke/generator/diffusers_pipeline.py

Justification of this change is that it enables very large image generation while imposing a *slight* performance penalty over no attention slicing. The current choice of `auto` has the same performance characteristics of `max`, and doesn't give the benefit of large image generation.
Stats on a 12GB CUDA card:
no slicing:
1280x1280
*OOM*
1024x1024
*OOM*
768x768
`>>   1 image(s) generated in 23.67s`
512x512
`>>   1 image(s) generated in 8.41s`
`auto`:
1280x1280
*OOM*
1024x1024
`>>   1 image(s) generated in 70.30s`
768x768
`>>   1 image(s) generated in 23.64s`
512x512
`>>   1 image(s) generated in 8.55s`
`max`:
1280x1280
`>>   1 image(s) generated in 147.21s`
1024x1024
`>>   1 image(s) generated in 65.62s`
768x768
`>>   1 image(s) generated in 23.19s`
512x512
`>>   1 image(s) generated in …

Switch to using max for attention slicing in all cases for the time being

---

invokeai/frontend/src/features/canvas/components/IAICanvasStatusText.tsx

[web ui] Add `Preserve Masked Area` to canvas status text area

---

invokeai/frontend/src/features/gallery/components/DeleteImageModal.tsx

The `useHotkeys` hook for this hotkey didn't have `isConnected` or `isProcessing` in its dependencies array. This prevented `handleDelete()` from dispatching the delete request.

[web ui] del hotkey doesn't work after canceling

---

docs/installation/020_INSTALL_MANUAL.md

* Windows location for the Python environment activate location is currently incorrect
* Due to this, this command will fail for Windows-based users
* The contributing link within the `Developer Install` sections leads to a [404](https://invoke-ai.github.io/index.md#Contributing)
* `Developer Install`'s numbered list currently lists 1, 1, 2, . . .
* Changed the location of Windows script based on actual location - [reference](https://docs.python.org/3/library/venv.html)
* Moved the link to point to one directory higher -- the main index.md
* Minor format adjustments to allow for the numbered list to appear as expected 
* `mkdocs serve` => Verified on local server that the changes reflected as expected
Contributing mentions to set the upstream towards the `development` branch, but that …

Fix Incorrect Windows Environment Activation Location (Manual Installation Documentation)

---

ldm/generate.py
ldm/invoke/CLI.py

I'm following the convention here of a generic "upscale" naming and thus we have "upscale_denoise_str", although this variable is currently only used with esrgan.

small change to pull esrgan denoise strength through to the generate API.

---

ldm/invoke/merge_diffusers.py
ldm/invoke/training/textual_inversion.py

- The invokeai-ti and invokeai-merge scripts will crash if there is not enough space in the console to fit the user interface (even after responsive formatting).
- This PR intercepts the errors and prints a useful error message advising user to make window larger.

Improve error messages from Textual Inversion and Merge scripts

---

README.md

Broken link in the README. Now pointing to correct mkdocs file.

Fix link to the installation documentation

---

ldm/invoke/generator/base.py

Tensors with diffusers no longer have to be multiples of 8. This broke Perlin noise generation. We now generate noise for the next largest multiple of 8 and return a cropped result. Fixes #2674.

Fix perlin noise generator for diffusers tensors

---

binary_installer/install.bat.in
scripts/configure_invokeai.py

`install.bat.in` was pointing to a deprecated configuration script, which itself was trying to call a non-existent function as a fallback.
This PR fixes both the install.bat.in and the fallback within the deprecated script.

Make install.bat.in point to correct configuration script

---

invokeai/frontend/.eslintignore
invokeai/frontend/.prettierignore

Frontend linter and formatter should ignore the build artifact `stats.html`

build: lint/format ignores stats.html

---

.github/workflows/build-container.yml
.github/workflows/test-invoke-pip-skip.yml
.github/workflows/test-invoke-pip.yml
README.md

- filter paths for `build-container.yml` and `test-invoke-pip.yml`
- add workflow to pass required checks on PRs with `paths-ignore`
- this triggers if `test-invoke-pip.yml` does not
- fix "CI checks on main link" in `/README.md`

skip huge workflows if not needed

---

ldm/invoke/merge_diffusers.py

This fixes a few cosmetic bugs in the merge models console GUI:
1) Fix the minimum and maximum ranges on alpha. Was 0.05 to 0.95. Now 0.01 to 0.99.
2) Don't show the 'add_difference' interpolation method when 2 models selected, or the other three methods when three models selected

Bugfixes on the merge_model GUI

---

ldm/invoke/__init__.py

It's not readily available on Windows and xformers only uses it on some very specific hardware anyway.
Thanks to https://github.com/comfyanonymous/ComfyUI/pull/11 for demonstrating how to handle this.

fix(xformers): shush about not having Triton available.

---

ldm/invoke/CLI.py
ldm/invoke/ckpt_to_diffuser.py
ldm/invoke/merge_diffusers.py

- The checkpoint conversion script was generating diffusers models with the safety checker set to null. This resulted in models that could not be merged with ones that have the safety checker activated.
- This PR fixes the issue by incorporating the safety checker into all 1.x-derived checkpoints, regardless of user's nsfw_checker setting.

fix conversion of checkpoints into incompatible diffusers models

---

ldm/models/diffusion/cross_attention_control.py

Diffusers' `prepare_attention_mask` was crashing when we didn't pass in a batch size.

Fix crash on calling diffusers' prepare_attention_mask

---

ldm/generate.py
ldm/invoke/generator/base.py
ldm/invoke/generator/embiggen.py

The `clear_cuda_cache` function was not being passed on to embiggen's `generate` call, and cuda stats weren't initialized prior to the call.

Fixed embiggening crash

---

ldm/invoke/generator/diffusers_pipeline.py

We now require more free memory to avoid attention slicing. 17.5% free was not sufficient headroom in all cases, so now we require 25%.

Fix crashing when using 2.1 model

---

ldm/invoke/training/textual_inversion.py
ldm/invoke/training/textual_inversion_training.py

-At some point pathlib was added to the list of imported modules and this broken the os.path code that assembled the sample data set.
-Now fixed by replacing os.path calls with Path methods

fix crash in textual inversion with "num_samples=0" error

---

.github/workflows/pypi-release.yml

This change will cause releases on the v2.3 branch to be pushed to PyPi.

push to pypi from branch v2.3

---

ldm/invoke/generator/base.py

The sample_to_image method in `ldm.invoke.generator.base` was still using ckpt-era code. As a result when the WebUI was set to show "accurate" intermediate images, there'd be a crash. This PR corrects the problem.
- Closes #2784
- Closes #2775

fix generate backend to generate "accurate" intermediate images

---

ldm/generate.py

Some CUDA users with low VRAM were reporting OOM errors after consecutive runs. The CUDA cache wasn't being completely emptied due to python's garbage collector not running.

Run garbage collection to allow the CUDA cache to completely empty.

---

ldm/invoke/model_manager.py

- an inadvertent change to the model manager broke the merging functions
- corrected here - will be a hotfix

fixes crashes on merge in both WebUI and console

---

invokeai/backend/invoke_ai_web_server.py

For size savings of about 80%, and jpeg encoding is still plenty fast.

perf(invoke_ai_web_server): encode intermediate result previews as jpeg

---

invokeai/configs/INITIAL_MODELS.yaml
ldm/invoke/_version.py

- stable-diffusion-2.1-base base model from stabilityai/stable-diffusion-2-1-base
- stable-diffusion-2.1-768 768 pixel model from stabilityai/stable-diffusion-2-1-768
- sd-inpainting-2.0 512 pixel inpainting model from runwayml/stable-diffusion-inpainting
This PR also bumps the version number up to v2.3.1.post2

restore previous naming scheme for sd-2.x models:

---

ldm/invoke/config/invokeai_configure.py
ldm/invoke/config/model_install_backend.py

This should prevent the errors that users are seeing with spaces in the file paths

quote output, embedding and autoscan directores in invokeai.init

---

invokeai/backend/generator/txt2img2img.py

Fix error when using txt2img 
ModuleNotFoundError: No module named 'invokeai.backend.models'
and
ModuleNotFoundError: No module named 'invokeai.backend.generator.diffusers_pipeline'

Fix for txt2img2img.py

---

invokeai/app/invocations/baseinvocation.py
invokeai/app/invocations/cv.py
invokeai/app/invocations/image.py

This places `#fmt: off` and `#fmt: on` blocks around sections of the invocation code that shouldn't be reformatted by Black.

Protect invocations against black autoformatting

---

pyproject.toml

Things to check for in this version:
- `diffusers` cache location is now more consistent with other huggingface-hub using code (i.e. `transformers`) as of https://github.com/huggingface/diffusers/pull/2005. I think ultimately this should make @damian0815 (and other folks with multiple diffusers-using projects) happier, but it's worth taking a look to make sure the way @lstein set things up to respect `HF_HOME` is still functioning as intended.
- I've gone ahead and updated `transformers` to the current version (4.26), but I have a vague memory that we were holding it back at some point? Need to look that up and see if that's the case and why.

deps: upgrade to diffusers 0.14, safetensors 0.3, transformers 4.26, accelerate 0.16

---

invokeai/backend/model_management/__init__.py
invokeai/backend/model_management/model_manager.py
invokeai/frontend/web/.husky/pre-commit

This fixes the borked #2867 PR.

migrate to new diffusers model layout

---

invokeai/backend/web/invoke_ai_web_server.py
invokeai/frontend/CLI/CLI.py

Fixed an import statement for the web UI server.
Fixed the new `run_patches()` function to create destination directories if they don't exist.

Fixed startup issues with the web UI.

---

ldm/invoke/conditioning.py

This is the same fix that was applied to main in PR 2837.

fix newlines causing negative prompt to be parsed incorrectly

---

ldm/invoke/CLI.py
ldm/invoke/model_manager.py

- Crash would occur at the end of this sequence:
- launch CLI
- !convert &lt;URL pointing to a legacy ckpt file&gt;
- Answer "Y" when asked to delete original .ckpt file
- This commit modifies model_manager.heuristic_import() to silently delete the downloaded legacy file after it has been converted into a diffusers model. The user is no longer asked to approve deletion.
NB: This should be cherry-picked into main once refactor is done.

Prevent crash when converting models from within CLI using legacy model URL

---

invokeai/backend/generator/base.py
invokeai/backend/generator/img2img.py
invokeai/backend/generator/inpaint.py
invokeai/backend/stable_diffusion/diffusers_pipeline.py

When the user picks a strength of 1 for img2img or inpainting, the current code slightly mixes in the initial image with random noise. Strength 1 should be a complete replacement and should yield the same results as txt2img in the img2img case.

Make img2img strength 1 behave the same as txt2img

---

pyproject.toml

add back pytorch-lightning dependency

---

ldm/invoke/ckpt_to_diffuser.py

When a legacy ckpt model was converted into diffusers in RAM, the built-in NSFW checker was not being disabled, in contrast to models converted and saved to disk. Because InvokeAI does its NSFW checking as a separate post-processing step (in order to generate blurred images rather than black ones), this defeated the
--nsfw and --no-nsfw switches.
This closes #2836 and #2580.
Note - this fix will be applied to `main` as a separate PR.

Disable built-in NSFW checker on models converted with --ckpt_convert

---

.github/workflows/close-inactive-issues.yml

I found it to be a chore to remove labels manually in order to "un-stale" issues. This is contrary to the bot message which says commenting should remove "stale" status. On the current `cron` schedule, there may be a delay of up to 24 hours before the label is removed. This PR will trigger the workflow on issue comments in addition to the schedule.
Also adds a condition to not run this job on PRs (Github treats issues and PRs equivalently in this respect), and rewords the messages for clarity.

Remove label from stale issues on comment event

---

.github/workflows/close-inactive-issues.yml

Reverts invoke-ai/InvokeAI#2903
@mauwii has a point here. It looks like triggering on a comment results in an action for each of the stale issues, even ones that have been previously dealt with. I'd like to revert this back to the original behavior of running once every time the cron job executes.
What's the original motivation for having more frequent labeling of the issues?

Revert "Remove label from stale issues on comment event"

---

docs/installation/020_INSTALL_MANUAL.md

Many people use oh-my-zsh for their command line: https://ohmyz.sh/ 
Adding `""` should work both on ohmyzsh and native bash

Make sure command also works with Oh-my-zsh

---

invokeai/backend/model_management/convert_ckpt_to_diffusers.py

Cause of the problem was inadvertent activation of the safety checker.
When conversion occurs on disk, the safety checker is disabled during loading. However, when converting in RAM, the safety checker was not removed, resulting in it activating even when user specified --no-nsfw_checker.
This PR fixes the problem by detecting when the caller has requested the InvokeAi StableDiffusionGeneratorPipeline class to be returned and setting safety checker to None. Do not do this with diffusers models destined for disk because then they will be incompatible with the merge script!!
Closes #2836

FIX bug that caused black images when converting ckpts to diffusers

---

ldm/invoke/CLI.py
ldm/invoke/_version.py
ldm/invoke/config/invokeai_configure.py
ldm/invoke/config/model_install_backend.py
ldm/invoke/globals.py
ldm/invoke/merge_diffusers.py
ldm/invoke/model_manager.py
ldm/invoke/training/textual_inversion_training.py
pyproject.toml

This PR ports the `main` PR #2871 to the v2.3 branch. This adjusts the global diffusers model cache to work with the 0.14 diffusers layout of placing models in HF_HOME/hub rather than HF_HOME/diffusers. It also implements the one-time migration action to the new layout.

use diffusers 0.14 cache layout, upgrade transformers, safetensors, accelerate

---

.github/workflows/close-inactive-issues.yml

- default value is 30
- limit per hour is 1000
This should help getting the count of open issues down.

raise operations-per-run for issue workflow to 500

---

.github/workflows/test-invoke-pip-skip.yml
.github/workflows/test-invoke-pip.yml

Prior to the folder restructure, the `paths` for `test-invoke-pip` did not include the UI's path `invokeai/frontend/`:
```yaml
paths:
- 'pyproject.toml'
- 'ldm/**'
- 'invokeai/backend/**'
- 'invokeai/configs/**'
- 'invokeai/frontend/dist/**'
```
After the restructure, more code was moved into the `invokeai/frontend/` folder, and `paths` was updated:
```yaml
paths:
- 'pyproject.toml'
- 'invokeai/**'
- 'invokeai/backend/**'
- 'invokeai/configs/**'
- 'invokeai/frontend/web/dist/**'
```
Now, the second path includes the UI. The UI now needs to be excluded, and must be excluded prior to `invokeai/frontend/web/dist/**` being included.
On `test-invoke-pip-skip`, we need to do a bit of logic juggling to invert the folder selection. First, include the web folder, then exclude everying around it …

build: exclude ui from `test-invoke-pip`

---

ldm/invoke/CLI.py
ldm/invoke/_version.py
ldm/invoke/config/invokeai_update.py
pyproject.toml

This is a temporary fix for #2930 . For reasons unknown, when doing a pip install from network the `configs/stable-diffusion` directory is not being installed into `.venv`, and this breaks the `run_patches()` routine in the CLI. 
This PR disables `run_patches()` until the problem can be dealt with more definitively. The only issue will be that the original checkpoint stable diffusion configuration files will not be updated with more recent versions.
[Edit]
Added line missing in `pyproject.toml` so config/stable-diffusion directory should now be created. Needs someone other than myself to test and confirm. Please don't merge till then.

Bugfix/fix 2.3.2 upgrade path

---

invokeai/backend/args.py

- The value of png_compression was always 6, despite the value provided to the --png_compression argument. This fixes the bug.
- It also fixes an inconsistency between the maximum range of png_compression and the help text.
- Closes #2945

fix --png_compression command line argument

---

invokeai/backend/model_management/convert_ckpt_to_diffusers.py
invokeai/backend/model_management/model_manager.py

Pickle files (.pkl, .ckpt, etc) are extremely unsafe as they can be trivially crafted to execute arbitrary code when parsed using `torch.load`
Right now the conventional wisdom among ML researchers and users is to simply `not run untrusted pickle files ever` and instead only use Safetensor files, which cannot be injected with arbitrary code. This is very good advice. 
Unfortunately, **I have discovered a vulnerability inside of InvokeAI that allows an attacker to disguise a pickle file as a safetensor and have the payload execute within InvokeAI.**
Within `model_manager.py` and `convert_ckpt_to_diffusers.py` there are if-statements that decide which `load` method to use based on the file extension of the model file. The logic (written in a slightly more readable format than it exists in …

Removed file-extension-based arbitrary code execution attack vector

---

invokeai/backend/generator/inpaint.py

After #2942, seed needs to be passed down from inpaint to seam_paint. Not doing so breaks inpainting and outpainting. This PR fixes it.

fix(inpaint): Seam painting being broken

---

pyproject.toml

Update `compel` to 1.0.0.
This fixes #2832.
It also changes the way downweighting is applied. In particular, downweighting should now be much better and more controllable. 
From the [compel changelog](https://github.com/damian0815/compel#changelog):
> Downweighting now works by applying an attention mask to remove the downweighted tokens, rather than literally removing them from the sequence. This behaviour is the default, but the old behaviour can be re-enabled by passing `downweight_mode=DownweightMode.REMOVE` on init of the `Compel` instance.
>
> Formerly, downweighting a token worked by both multiplying the weighting of the token's embedding, and doing an inverse-weighted blend with a copy of the token sequence that had the downweighted tokens removed. The intuition is that as weight …

update compel to fix black screens and use new downweighting algorithm

---

invokeai/app/invocations/generate.py
invokeai/app/services/events.py
invokeai/app/services/graph.py
invokeai/backend/generator/base.py
invokeai/backend/util/util.py

- 86932469e76f1315ee18bfa2fc52b588241dace1 add image_to_dataURL util
- 0c2611059711b45bb6142d30b1d1343ac24268f3 make fast latents method static
- this method doesn't really need `self` and should be able to be called without instantiating `Generator`
- 2360bfb6558ea511e9c9576f3d4b5535870d84b4 fix schema gen for GraphExecutionState
- `GraphExecutionState` uses `default_factory` in its fields; the result is the OpenAPI schema marks those fields as optional, which propagates to the generated API client, which means we need a lot of unnecessary type guards to use this data type. the [simple fix](https://github.com/pydantic/pydantic/discussions/4577) is to add config to explicitly say all class properties are required. looks this this will be resolved in a future pydantic release
- …

nodes: api fixes

---

pyproject.toml

Now that torch 2.0 is out, Invoke 2.3 should lock down its version to 1.13.1 for new installs and upgrades.

Keep torch version at 1.13.1

---

ldm/invoke/_version.py

Lots of little bugs have been squashed since 2.3.2 and a new minor point release is imminent. This PR updates the version number in preparation for a RC.

bump version to 2.3.3-rc1

---

docs/features/TEXTUAL_INVERSION.md
ldm/invoke/training/textual_inversion.py
ldm/invoke/training/textual_inversion_training.py

This PR addresses issues raised by #3008.
1. Update documentation to indicate the correct maximum batch size for TI training when xformers is and isn't used.
2. Update textual inversion code so that the default for batch size  is aware of xformer availability.
3. Add documentation for how to launch TI with distributed learning.

Fix textual inversion documentation and code

---

ldm/invoke/pngwriter.py

- Since 2.3.2 invokeai stores the next PNG file's numeric prefix in a file named `.next_prefix` in the outputs directory. This avoids the overhead of doing a directory listing to find out what file number comes next.
- The code uses advisory locking to prevent corruption of this file in the event that multiple invokeai's try to access it simultaneously, but some users have experienced corruption of the file nevertheless.
- This PR addresses the problem by detecting a potentially corrupted `.next_prefix` file and falling back to the directory listing method. A fixed version of the file is then written out.
- Closes #3001

fix corrupted outputs/.next_prefix file

---

ldm/invoke/dynamic_prompts.py

- The command `invokeai-batch --invoke` was creating a time-stamped logfile with colons in its name, which is a Windows no-no. This corrects the problem by writing the timestamp out as "13-06-2023_8-35-10"
- Closes #3005

fix batch generation logfile name to be compatible with Windows OS

---

ldm/invoke/ckpt_to_diffuser.py
ldm/invoke/model_manager.py

Several related security fixes:
1. Port #2946 from main to 2.3.2 branch - this closes a hole that allows a pickle checkpoint file to masquerade as a safetensors file.
2. Add pickle scanning to the checkpoint to diffusers conversion script.
3. Pickle scan VAE non-safetensors files
4. Avoid running scanner twice on same file during the probing and conversion process.
5. Clean up diagnostic messages.

Security patch: Scan all pickle files, including VAEs; default to safetensor loading

---

README.md

Hi, I am trying to install InvokeAI on my linux machine, the command in README.md cannot install correct dependency

doc(readme): fix incorrect install command

---

.github/CODEOWNERS
.github/workflows/mkdocs-material.yml

The mkdocs-workflow has been failing over the past week due to permission denied errors. I *think* this is the result of not passing the GitHub API token to the workflow, and this is a speculative fix for the issue.

add github API token to mkdocs workflow

---

invokeai/backend/model_management/convert_ckpt_to_diffusers.py
invokeai/backend/model_management/model_manager.py

This bug was causing a bunch of annoying warnings about not overwriting previously loaded tokens.
- as noted by JPPhoto

fix issue with embeddings being loaded twice

---

installer/templates/invoke.sh.in

At some point I put a loop around the menu for the `invoke.sh` script so that users could launch the merge or textual inversion scripts and then conveniently return to the menu to select another option. However, because of poor loop termination placement, selecting option [8] for the "developer's console" created an annoying infinite loop. This fixes the problem.
The fact that nobody noticed this before is interesting and a bit sad.

prevent infinite loop when launching developer's console

---

invokeai/app/api/routers/sessions.py
invokeai/app/invocations/generate.py
invokeai/app/invocations/image.py
invokeai/app/invocations/prompt.py
invokeai/app/services/graph.py
invokeai/app/services/invocation_queue.py
invokeai/app/services/invoker.py
invokeai/app/services/processor.py
invokeai/app/util/util.py
invokeai/backend/generator/base.py

keeping `main` up to date with my api nodes branch:
- bd7e515290b9ccf9b44398933e486df27e1c60a0: [nodes] Add cancelation to the API @Kyle0654
- 5fe38f7: fix(backend): simple typing fixes
- just picking some low-hanging fruit to improve IDE hinting
- c34ac91: fix(nodes): fix cancel; fix callback for img2img, inpaint
- makes nodes cancel immediate, use fix progress images on nodes, fix callbacks for img2img/inpaint
- 4221cf7: fix(nodes): fix schema generation for output classes
- did this previously for some other class; needed to not have node outputs be optional

nodes: add cancelation, updated progress callback, typing fixes

---

docs/installation/050_INSTALLING_MODELS.md
ldm/invoke/ckpt_to_diffuser.py
ldm/invoke/model_manager.py

- Imported V2 legacy models will now autoconvert into diffusers at load time regardless of setting of --ckpt_convert.
- model manager `heuristic_import()` function now looks for side-by-side yaml and vae files for custom configuration and VAE respectively.
Example of this:
illuminati-v1.1.safetensors illuminati-v1.1.vae.safetensors illuminati-v1.1.yaml
When the user tries to import `illuminati-v1.1.safetensors`, the yaml file will be used for its configuration, and the VAE will be used for its VAE. Conversion to diffusers will happen if needed, and the yaml file will be used to determine which V2 format (if any) to apply.
NOTE that the changes to `ckpt_to_diffusers.py` were previously reviewed by @JPPhoto on the `main` branch and approved.

enhance model autodetection during import

---

docs/installation/050_INSTALLING_MODELS.md
installer/templates/invoke.sh.in
ldm/invoke/ckpt_to_diffuser.py
ldm/invoke/model_manager.py

This includes a number of bug fixes described in the draft release notes.
It also incorporates a modified version of the dialog-based invoke.sh script suggested by JoshuaKimsey:
https://discord.com/channels/1020123559063990373/1089119602425995304

this is release candidate 2.3.3-rc1

---

README.md
docs/installation/010_INSTALL_AUTOMATED.md
docs/installation/020_INSTALL_MANUAL.md
docs/installation/030_INSTALL_CUDA_AND_ROCM.md

The Pytorch ROCm version in the documentation in outdated (`rocm5.2`) which leads to errors during the installation of InvokeAI. 
This PR updates the documentation with the latest Pytorch ROCm `5.4.2` version.

Doc: updating ROCm version in documentation

---

ldm/modules/textual_inversion_manager.py

- This variant, exemplified by "easynegative.safetensors" has a single 'embparam' key containing a Tensor.
- Also refactored code to make it easier to read.
- Handle both pickle and safetensor formats.

Add support for yet another TI embedding file format (2.3 version)

---

pyproject.toml

FastAPI is broken on `main` (17d8bbf3) - any request returns a `500` type error. 
This PR downgrades `fastapi` and related packages again. I wish I had a better solution, but this at least fixes the immediate breakage.
Fixes #3038

Downgrade FastAPI

---

invokeai/backend/model_management/convert_ckpt_to_diffusers.py

This commit fixes bugs related to the on-the-fly conversion and loading of legacy checkpoint models built on SD-2.0 base.
- When legacy checkpoints built on SD-2.0 models were converted on-the-fly using --ckpt_convert, generation would crash with a precision incompatibility error. This problem has been found and fixed.

Fix bugs in online ckpt conversion of 2.0 models

---

invokeai/backend/model_management/model_manager.py
invokeai/frontend/CLI/CLI.py

A long-standing issue with importing legacy checkpoints (both ckpt and safetensors) is that the user has to identify the correct config file, either by providing its path or by selecting which type of model the checkpoint is (e.g. "v1 inpainting"). In addition, some users wish to provide custom VAEs for use with the model. Currently this is done in the WebUI by importing the model, editing it, and then typing in the path to the VAE.
To improve the user experience, the model manager's `heuristic_import()` method has been enhanced as follows:
1. When initially called, the caller can pass a config file path, in which case it will be used.
2. If no config file provided, the method looks for a .yaml file in the same directory as the model which bears the same basename. e.g.
``` …
```

improve importation and conversion of legacy checkpoint files

---

invokeai/backend/stable_diffusion/textual_inversion_manager.py

- This PR adds support for embedding files that contain a single key "emb_params". The only example I know of this format is the "EasyNegative" embedding on HuggingFace, but there are certainly others.
- This PR also adds support for loading embedding files that have been saved in safetensors format.
- It also cleans up the code so that the logic of probing for and selecting the right format parser is clear.
- This is the same as #3045, which is on the 2.3 branch.

Add support for yet another TI embedding format (main version)

---

pyproject.toml

currently if users input eg `happy (camper:0.3)` it gets parsed incorrectly, which causes crashes if it's in the negative prompt. bump to compel 1.0.5 fixes the parser to avoid this (note the weight is parsed as plain text, it's not converted to proper invoke syntax)

[deps] bump compel version to fix crash on invalid (auto111) syntax

---

invokeai/app/api/routers/sessions.py

The typo accidentally did not affect functionality; when `query==""`, it `search()`ed but found everything due to empty query, then paginated results, so it worked the same as `list()`.
Still fix it

fix(nodes): fix typo in `list_sessions` handler

---

ldm/generate.py
ldm/invoke/CLI.py

- this allows invokeai to restore the last used model on startup, even after a crash or keyboard interrupt.

[Enhancement] save name of last model to disk whenever model changes

---

ldm/modules/kohya_lora_manager.py

Implementation of LyCORIS(extended LoRA), which is 2 formats - LoCon and LoHa([info1](https://github.com/KohakuBlueleaf/LyCORIS/blob/locon-archive/README.md), [info2](https://github.com/KohakuBlueleaf/LyCORIS/blob/main/Algo.md)).
It's works but i found 2 a bit different implementations of forward function for LoHa. Both works, but I don't know which is better.
2 functions generate same images if remove `self.org_module.weight.data` addition from LyCORIS implementation, but who's right?

[FEATURE] LyCORIS support in 2.3

---

installer/lib/installer.py

Now, for python 3.9 installer run upgrade pip command like this:
`pip install --upgrade pip`
And because pip binary locked as running process this lead to error(at least on windows):
```
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'e:\invokeai\.venv\scripts\pip.exe'
Check the permissions.
```
To prevent this recomended command to upgrade pip is:
`python -m pip install --upgrade pip`
Which not locking pip file.

[Bugfix] Pip - Access is denied durring installation

---

invokeai/app/api/dependencies.py
invokeai/app/cli/commands.py
invokeai/app/cli_app.py
invokeai/app/invocations/collections.py
invokeai/app/invocations/latent.py
invokeai/app/invocations/math.py
invokeai/app/services/graph.py
invokeai/app/services/invocation_services.py
invokeai/app/services/invoker.py
invokeai/app/services/latent_storage.py
tests/nodes/test_graph_execution_state.py
tests/nodes/test_invoker.py

Adds latent nodes for text to latent and latent to latent (roughly equivalent to text to image and image to image).
Adds latent storage.
Adds simple math nodes.
Fix bug in iteration expansion that was causing incorrect edges.
Add simple range and random range collection generator nodes.
Fix bug in CLI when linking to multiple nodes.
Example of new nodes:
```bash
random_range --size 3 | iterate | noise --link -1 item seed | t2l --prompt "banana sushi" | l2i | show_image
```
Generates 3 different images.

[nodes] Add latent nodes, storage, and fix iteration bugs

---

invokeai/backend/__init__.py
invokeai/backend/model_management/__init__.py
invokeai/backend/model_management/model_manager.py

This PR introduces a new set of ModelManager methods that enables you to retrieve the individual parts of a stable diffusion pipeline model, including the vae, text_encoder, unet, tokenizer, etc.
To use:
```
from invokeai.backend import ModelManager
manager = ModelManager('/path/to/models.yaml')
vae = manager.get_model_vae('stable-diffusion-1.5')
unet = manager.get_model_unet('stable-diffusion-1.5')
tokenizer = manager.get_model_tokenizer('stable-diffusion-1.5')
feature_extractor = manager.get_model_feature_extractor('stable-diffusion-1.5')
scheduler = manager.get_model_scheduler('stable-diffusion-1.5')
text_encoder = manager.get_model_text_encoder('stable-diffusion-1.5')
vae = manager.get_model_vae()
```

add a new method to model_manager that retrieves individual pipeline components

---

.github/stale.yaml

We are moving from the stale action to Stalebot. It allows for issues to be pinned so they are never stale.
I'll be going through our issues to mark those.
I've changed the messaging and the timings; please review and let me know if you want any changes.

chore: configure stale bot

---

invokeai/backend/args.py
invokeai/backend/config/model_install_backend.py
invokeai/frontend/CLI/CLI.py
invokeai/frontend/install/model_install.py

- the functionality to automatically import and run legacy checkpoint files in a designated folder has been removed from the backend but there are vestiges of the code remaining in the frontend that are causing crashes.
- This fixes the problem.
- Closes #3075

remove vestiges of non-functional autoimport code for legacy checkpoints

---

pyproject.toml

I'm not quite sure why this isn't being installed by fastapi's dependencies, but running without it installed yields:
```
root@gnubert:/srv/ssdtank/docker/invokeai/git/InvokeAI# docker run --gpus all -p 9989:9090 -v /srv/ssdtank/docker/invokeai/data:/data -v /srv/ssdtank/docker/invokeai/git/InvokeAI/static/dream_web/:/static/dream_web --rm -ti -u root --entrypoint /bin/bash ghcr.io/cmsj/invokeai-nodes@sha256:426ebc414936cb67e02f5f64d963196500a77b2f485df8122a2d462797293938
root@7a77b56a5771:/usr/src# /invoke-new.py --web
Form data requires "python-multipart" to be installed.
You can install "python-multipart" with:
pip install python-multipart
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /invoke-new.py:22 in <module> …
```

Add python-multipart, which is needed by nodes

---

invokeai/app/api/models/images.py
invokeai/app/api/routers/images.py
invokeai/app/cli/commands.py
invokeai/app/invocations/cv.py
invokeai/app/invocations/generate.py
invokeai/app/invocations/image.py
invokeai/app/invocations/reconstruct.py
invokeai/app/invocations/upscale.py
invokeai/app/models/exceptions.py
invokeai/app/models/image.py
invokeai/app/models/metadata.py
invokeai/app/services/image_storage.py
invokeai/app/services/processor.py
invokeai/app/util/step_callback.py

- add `list_images` endpoint at `GET api/v1/images`
- extend `ImageStorageBase` with `list()` method, implemented it for `DiskImageStorage`
- add `ImageReponse` class to for image responses, which includes urls, metadata
- add `ImageMetadata` class (basically a stub at the moment)
- uploaded images now named `"{uuid}_{timestamp}.png"`
- add `datatypes` module, moved a few classes into there. besides separating concerns more clearly, this helps to mitigate circular dependencies
- improve thumbnail handling

feat(nodes): add list_images endpoint

---

docs/contributing/INVOCATIONS.md
invokeai/app/services/graph.py

Another field that I realised should have its properties marked as required for schema generation.
Also added a README file for Invocations with a section explaining why this is needed.

feat(nodes): mark ImageField properties required, add invocation README

---

invokeai/backend/model_management/model_manager.py

When running this app first time in WSL2 environment, which is notoriously slow when it comes to IO, computing the SHAs of the models takes an eternity.
Computing shas for sd2.1
```
| Calculating sha256 hash of model files
| sha256 = 1e4ce085102fe6590d41ec1ab6623a18c07127e2eca3e94a34736b36b57b9c5e (49 files hashed in 510.87s)
```
I increased the chunk size to 16MB reduce the number of round trips for loading the data. New results:
```
| Calculating sha256 hash of model files
| sha256 = 1e4ce085102fe6590d41ec1ab6623a18c07127e2eca3e94a34736b36b57b9c5e (49 files hashed in 59.89s)
```
Higher values don't seem to make an impact.

Increase chunk size when computing diffusers SHAs

---

ldm/invoke/config/invokeai_update.py

This PR addresses the issue that when `invokeai-update` is run on a Windows system, and an instance of InvokeAI is open and running, the user's `.venv` can get corrupted. 
Issue first reported here:
https://discord.com/channels/1020123559063990373/1094688269356249108/1094688434750230628

[Bugfix] detect running invoke before updating

---

ldm/invoke/dynamic_prompts.py

- Previous PR to truncate long filenames won't work on windows due to lack of support for os.pathconf(). This works around the limitation by hardcoding the value for PC_NAME_MAX when pathconf is unavailable.
- The `multiprocessing` send() and recv() methods weren't working properly on Windows due to issues involving `utf-8` encoding and pickling/unpickling. Changed these calls to `send_bytes()` and `recv_bytes()` , which seems to fix the issue.
Not fully tested on Windows since I lack a GPU machine to test on, but is working on CPU.

[Bugfix] make invokeai-batch work on windows

---

ldm/invoke/_version.py
ldm/modules/kohya_lora_manager.py
pyproject.toml

- Pin diffusers to 0.14
- Small fix to LoRA loading routine that was preventing placement of LoRA files in subdirectories.
- Bump version to 2.3.4.post1

hotfix to 2.3.4

---

invokeai/app/api/dependencies.py
invokeai/app/cli/commands.py
invokeai/app/cli_app.py
invokeai/app/invocations/cv.py
invokeai/app/invocations/latent.py
invokeai/app/invocations/params.py
invokeai/app/services/default_graphs.py
invokeai/app/services/graph.py
invokeai/app/services/invocation_services.py
invokeai/app/services/sqlite.py
pyproject.toml
tests/nodes/test_graph_execution_state.py
tests/nodes/test_invoker.py
tests/nodes/test_node_graph.py

Subgraphs are now functional. They are stored in a graph library, and are automatically added to the CLI by name. They can expose inputs and outputs when used in the CLI (some more work will need to be done to support this in the UI - namely, storing some reference to the graph library graph somewhere on the GraphNode, or with the Graph).

[nodes] Add subgraph library, subgraph usage in CLI, and fix subgraph execution

---

invokeai/app/invocations/latent.py
invokeai/app/services/graph.py
invokeai/app/services/invocation_queue.py

This is needed so that items can be pushed to an external queue, backed e.g. by Redis

Make InvocationQueueItem serializable

---

ldm/invoke/config/model_install.py
ldm/invoke/config/model_install_backend.py

- This was inadvertently broken when we stopped supporting direct loading of checkpoint models.
- Now fixed.
- May fix #3209

fix the "import from directory" function in console model installer

---

ldm/modules/kohya_lora_manager.py

It's like LoHA but use Kronecker product instead of Hadamard product.
https://github.com/KohakuBlueleaf/LyCORIS#lokr
I tested it on this 2 LoKR's:
https://civitai.com/models/34518/unofficial-vspo-yakumo-beni
https://civitai.com/models/35136/mika-pikazo-lokr
More tests hard to find as it's new format)
Better to test with https://github.com/invoke-ai/InvokeAI/pull/3214
Also a bit refactor forward function.
//LyCORIS also have (IA)^3 format, but I can't find examples in this format and even on LyCORIS page it's marked as experimental. So, until there some test examples I prefer not to add this.

[Feature] Add support for LoKR LyCORIS format

---

.github/CODEOWNERS

Remove @mauwii and @keturn until they are able to reengage with the development effort. @GreggHelt2 is designated co-codeowner for the backend.

update CODEOWNERS for changed team composition

---

.github/CODEOWNERS

Both @mauwii and @keturn have been offline for some time. I am temporarily removing them from CODEOWNERS so that they will not be responsible for code reviews until they wish to/are able to re-engage fully.
Note that I have volunteered @GreggHelt2 to be a codeowner of the generation backend code, replacing @keturn . Let me know if you're uncomfortable with this.

CODEOWNERS update - 2.3 branch 

---

invokeai/frontend/web/index.d.ts
invokeai/frontend/web/src/app/App.tsx
invokeai/frontend/web/src/component.tsx
invokeai/frontend/web/src/features/gallery/components/ImageGalleryContent.tsx
invokeai/frontend/web/src/features/gallery/store/resultsSlice.ts
invokeai/frontend/web/src/services/events/middleware.ts
invokeai/frontend/web/src/services/thunks/image.ts

* if `shouldFetchImages` is passed in, UI will make an additional request to get valid image URL when an invocation is complete
* this is necessary in order to have optional authorization for images

feat(ui): add support for shouldFetchImages if UI needs to re-fetch an image URL

---

invokeai/backend/invoke_ai_web_server.py
ldm/invoke/conditioning.py
ldm/invoke/generator/diffusers_pipeline.py
ldm/models/diffusion/cross_attention_control.py
ldm/models/diffusion/ddim.py
ldm/models/diffusion/ksampler.py
ldm/models/diffusion/plms.py
ldm/models/diffusion/shared_invokeai_diffusion.py
ldm/modules/kohya_lora_manager.py
ldm/modules/lora_manager.py

Load LoRAs during compel's text embedding encode pass in case there are requested LoRAs which also want to patch the text encoder.
Also generally cleanup the attention processor patching stuff. It's still a mess, but at least now it's a *stateless* mess.

Enable LoRAs to patch the text_encoder as well as the unet

---

installer/lib/installer.py
ldm/invoke/CLI.py
ldm/invoke/config/invokeai_configure.py
ldm/invoke/config/invokeai_update.py
ldm/invoke/config/model_install_backend.py
ldm/invoke/config/post_install.py
ldm/invoke/model_manager.py
pyproject.toml

- Moved all postinstallation config file and model munging code out of the CLI and into a separate script named `invokeai-postinstall`
- Fixed two calls to `shutil.copytree()` so that they don't try to preserve the file mode of the copied files. This is necessary to run correctly in a Nix environment (see thread at https://discord.com/channels/1020123559063990373/1091716696965918732/1095662756738371615)
- Update the installer so that an existing virtual environment will be updated, not overwritten.
- Pin npyscreen version to see if this fixes issues people have had with installing this module.

improvements to the installation and upgrade processes

---

invokeai/frontend/web/src/features/gallery/components/CurrentImageButtons.tsx
invokeai/frontend/web/src/features/gallery/components/CurrentImageDisplay.tsx

When gallery was empty (and there is therefore no selected image), no progress images were displayed. 
- fix by correcting the logic in CurrentImageDisplay
- also fix app crash introduced by fixing the first bug

fix(ui): fix no progress images when gallery is empty

---

invokeai/app/services/invoker.py
invokeai/app/services/processor.py

On hyperthreaded CPUs we get two threads operating on the queue by default on each core. This cases two threads to process queue items. This results in pytorch errors and sometimes generates garbage.
Locking this to single thread makes sense because we are bound by the number of GPUs in the system, not by CPU cores. And to parallelize across GPUs we should just start multiple processors (and use async instead of threading)
Fixes #3289

nodes-api: enforce single thread for the processor

---

ldm/invoke/config/invokeai_update.py

Fixes #3228, where the check to see if invokeai is running fails because a process no longer exists.

[Bugfix] Update check failing because process disappears

---

invokeai/backend/web/invoke_ai_web_server.py

This PR fixes a bug that appeared in the legacy web server after the logging PR was merged.
closes #3343

Fix logger namespace clash in web server

---

docs/installation/010_INSTALL_AUTOMATED.md

hi there, love the project! i noticed a small typo when going over the install process.
when copying the automated install instructions from the docs into a terminal, the line to install the python packages failed as it was missing the `-y` flag.

add -y to the automated install instructions

---

.github/workflows/mkdocs-material.yml

This PR instructs github to deploy documentation pages from the v2.3 branch.

Deploy documentation from v2.3 branch rather than main

---

invokeai/frontend/web/src/services/events/middleware.ts

Changes transport order for the socket.io client. The `websocket` transport will be tried first, followed by the legacy `polling` transport. This helps establish persistent websocket connections.

Use websocket transport first for Socket.io

---

invokeai/backend/invoke_ai_web_server.py
ldm/invoke/concepts_lib.py
ldm/invoke/readline.py
ldm/modules/embedding_manager.py
ldm/modules/textual_inversion_manager.py

This is a partial fix for #3330 . It prevents the concepts library from hitting HuggingFace to download concept library terms every time a model is changed.
It does not address the issue that the web interface downloads the concepts even if it is not going to use them.

Turn the HuggingFaceConceptsLib into a singleton to prevent redundant connections

---

installer/lib/installer.py
pyproject.toml

This PR updates to `xformers ~= 0.0.19` and `torch ~= 2.0.0`, which together seem to solve the non-deterministic image generation issue that was previously seen with earlier versions of `xformers`.

Update dependencies to get deterministic image generation behavior (main branch)

---

invokeai/backend/model_management/model_manager.py

The error occurs when loading a model for the first time. (or after removing its checksum file, probably.)

fix(model manager): fix string formatting error on model checksum timer

---

invokeai/app/services/default_graphs.py

- Disable for now until we resolve the issue of changing node schemas causing application to fail to start up due to invalid graphs

fix(nodes): temporarily disable librarygraphs

---

invokeai/backend/generator/inpaint.py

The problem was the same seed was getting used for the seam painting pass, causing the fried look.
Same issue as if you do img2img on a txt2img with the same seed/prompt.
Thanks to @hipsterusername for teaming up to debug this. We got pretty deep into the weeds.

fix(nodes): fix seam painting

---

invokeai/app/invocations/generate.py
invokeai/app/invocations/latent.py
invokeai/frontend/web/src/features/parameters/store/generationSlice.ts

Proposing updating from lms as default scheduler, given its tendency to produce odd results as of late.

Default Scheduler Update

---

invokeai/app/invocations/image.py
invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/app/store/middleware/devtools/actionsDenylist.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/index.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/addCommitStagingAreaImageListener.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasSavedToGallery.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageCategoriesChanged.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/receivedPageOfImages.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketConnected.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketDisconnected.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketGeneratorProgress.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketGraphExecutionStateComplete.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationError.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationStarted.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketSubscribed.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketUnsubscribed.ts
invokeai/frontend/web/src/features/canvas/components/IAICanvasIntermediateImage.tsx
invokeai/frontend/web/src/features/canvas/components/IAICanvasStagingArea.tsx
invokeai/frontend/web/src/features/canvas/components/IAICanvasStagingAreaToolbar.tsx
invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
invokeai/frontend/web/src/features/gallery/components/CurrentImageButtons.tsx
invokeai/frontend/web/src/features/gallery/components/ImageGalleryContent.tsx
invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts
invokeai/frontend/web/src/features/gallery/store/imagesSlice.ts
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/InfillAndScaling/ParamInfillAndScalingCollapse.tsx
invokeai/frontend/web/src/features/system/store/systemSlice.ts
invokeai/frontend/web/src/services/events/actions.ts
invokeai/frontend/web/src/services/events/util/setEventListeners.ts
invokeai/frontend/web/src/services/thunks/image.ts

- [fix(ui): fix auto-switch to new images](https://github.com/invoke-ai/InvokeAI/commit/f62bb41667e197674dc79596d8de99a391b09097)
- [fix(ui): infill and scaling options label](https://github.com/invoke-ai/InvokeAI/commit/d215e98c34076830a9ab3766d5779ed81cfb6180)
- [fix(ui): fix save to gallery without bounding box](https://github.com/invoke-ai/InvokeAI/commit/233444daea0066adc0d3932a125b87a49e17a92a)
- [fix(ui): add additional socket event layer to gate handling socket ev…](https://github.com/invoke-ai/InvokeAI/commit/0867d29a8c87658f677f1c91b861812dea3d893e) (fix cancel not resetting progress as expected)
- [fix(ui): when session is complete, null out progress image](https://github.com/invoke-ai/InvokeAI/commit/0b4f09e9948776f9ff0811f8755f88e42d0eed33) (fix progress image sticking around …

misc fixes

---

invokeai/frontend/web/src/features/gallery/components/ImageGalleryContent.tsx

The gallery could get in a state where it thought it had just reached the end of the list and endlessly fetches more images, if there are no more images to fetch (weird I know).
Add some logic to remove the `end reached` handler when there are no more images to load.

ui: fix looping gallery fetch

---

invokeai/frontend/web/src/features/controlNet/components/ControlNetImagePreview.tsx
invokeai/frontend/web/src/features/gallery/components/CurrentImageDisplay.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/ImageToImage/InitialImagePreview.tsx

- Prevent init, current & control images from overflowing

feat(ui): fix image fit

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasCopiedToClipboard.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasDownloadedAsImage.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasMerged.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasSavedToGallery.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageMetadataReceived.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageUploaded.ts
invokeai/frontend/web/src/features/canvas/util/getBaseLayerBlob.ts
invokeai/frontend/web/src/features/canvas/util/getFullBaseLayerBlob.ts
invokeai/frontend/web/src/features/gallery/components/CurrentImagePreview.tsx
invokeai/frontend/web/src/features/gallery/store/imagesSlice.ts

[feat(ui): fix canvas saving](https://github.com/invoke-ai/InvokeAI/pull/3503/commits/b094512736febde41a737f065c7e5e9b0f1e34ef)
- fix "bounding box region only" not being respected when saving
- add toasts for each action
- improve workflow `take()` predicates to use the requestId
[fix(ui): fix metadata viewer not working for canvas images](https://github.com/invoke-ai/InvokeAI/pull/3503/commits/ded88bdb79cdd021496b47f4c865875e3b845c61)
[fix(ui): fix canvas auto-save not working](https://github.com/invoke-ai/InvokeAI/pull/3503/commits/0823a1edc6a53564468b899d15f7311dd05cdf54)
[feat(ui): sort images by updated_at instead of created_at](https://github.com/invoke-ai/InvokeAI/pull/3503/commits/25e70641b677075bec6403830c07dd1ad518a25b)

feat(ui): fix canvas saving

---

invokeai/app/services/graph.py
invokeai/app/services/invoker.py
tests/nodes/test_graph_execution_state.py

There was an issue where for graphs w/ iterations, your images were output all at once, at the very end of processing. So if you canceled halfway through an execution of 10 nodes, you wouldn't get any images - even though you'd completed 5 images' worth of inference.
Because graphs executed breadth-first (i.e. depth-by-depth), leaf nodes were necessarily processed last. For image generation graphs, your `LatentsToImage` will be leaf nodes, and be the last depth to be executed.
For example, a `TextToLatents` graph w/ 3 iterations would execute all 3 `TextToLatents` nodes fully before moving to the next depth, where the `LatentsToImage` nodes produce output images, resulting in a node execution order like this:
1. TextToLatents
2. TextToLatents
3. TextToLatents
4. LatentsToImage
5. …

feat(nodes): depth-first execution

---

invokeai/frontend/web/src/common/components/IAICustomSelect.tsx
invokeai/frontend/web/src/features/controlNet/components/parameters/ParamControlNetModel.tsx
invokeai/frontend/web/src/features/controlNet/components/parameters/ParamControlNetProcessorSelect.tsx
invokeai/frontend/web/src/features/controlNet/store/constants.ts
invokeai/frontend/web/src/features/controlNet/store/controlNetSlice.ts
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamScheduler.tsx
invokeai/frontend/web/src/features/system/components/ModelSelect.tsx

Now accepts an array of strings or array of `IAICustomSelectOption`s. This supports custom labels and tooltips within the select component.

feat(ui): enhance IAICustomSelect

---

invokeai/app/services/image_file_storage.py
invokeai/app/services/latent_storage.py

- `DiskImageStorage` and `DiskLatentsStorage` have now both been updated to exclusively work with `Path` objects and not rely on the `os` lib to handle pathing related functions.
- We now also validate the existence of the required image output folders and latent output folders to ensure that the app does not break in case the required folders get tampered with mid-session.
- Just overall general cleanup.
Tested it. Don't seem to be any thing breaking.

refactor(minor): Image & Latent File Storage

---

invokeai/frontend/web/package.json
invokeai/frontend/web/src/common/components/IAIDndImage.tsx
invokeai/frontend/web/src/common/hooks/useImageUploadButton.tsx
invokeai/frontend/web/src/features/controlNet/components/ControlNet.tsx
invokeai/frontend/web/src/features/controlNet/components/ControlNetImagePreview.tsx
invokeai/frontend/web/src/features/gallery/components/CurrentImageDisplay.tsx
invokeai/frontend/web/src/features/gallery/components/CurrentImagePreview.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/ImageToImage/InitialImagePreview.tsx
invokeai/frontend/web/src/services/api/thunks/image.ts
invokeai/frontend/web/yarn.lock

this PR is based on #3572 
[fix(ui): fix init image display buttons](https://github.com/invoke-ai/InvokeAI/commit/7025777aa29666dea730fa8932848b6876c11ca8)
- Reset and Upload buttons along top of initial image
- Also had to mess around with the control net & DnD image stuff after changing the styles
- Abstract image upload logic into hook - does not handle native HTML drag and drop upload - only the button click upload
[fix(ui): fix image fetching query string](https://github.com/invoke-ai/InvokeAI/pull/3576/commits/612a694575c12f09d2922d6478568a958df5ca2c)
- I don't understand what changed but suddenly the API didn't accept the format of query params for arrays. Added a `query-string`, a well-established lib, to serialize the query strings.

ui: fix initial image buttons, uploader functionality

---

.github/workflows/test-invoke-pip-skip.yml
.github/workflows/test-invoke-pip.yml
tests/conftest.py
tests/nodes/test_graph_execution_state.py
tests/nodes/test_invoker.py

"Fixes" the test suite generally so it doesn't fail CI, but some tests needed to be skipped/xfailed due to recent refactor.
- ignore three test suites that broke following the model manager refactor
- move `InvocationServices` fixture to `conftest.py`
- add `boards` items to the `InvocationServices`  fixture
This PR makes the unit tests work, but end-to-end tests are temporarily commented out due to `invokeai-configure` being broken in `main` - pending #3547 
Looks like a lot of the tests need to be rewritten as they reference `TextToImageInvocation` /  `ImageToImageInvocation`

Bypass failing tests

---

invokeai/frontend/web/src/i18.d.ts
invokeai/frontend/web/src/i18n.ts
invokeai/frontend/web/tsconfig.json

The TS Language Server slows down immensely with our translation JSON, which is used to provide kinda-type-safe translation keys. I say "kinda", because you don't get autocomplete - you only get red squigglies when the key is incorrect.
To improve the performance, we can opt out of this process entirely, at the cost of no red squigglies for translation keys. Hopefully we can resolve this in the future.
It's not clear why this became an issue only recently (like past couple weeks). We've tried rolling back the app dependencies, VSCode extensions, VSCode itself, and the TS version to before the time when the issue started, but nothing seems to improve the performance.
1. Disable `resolveJsonModule` in `tsconfig.json`
2. Ignore TS in `i18n.ts` when importing the JSON
3. Comment out the …

ui: fix ts perf

---

invokeai/backend/install/migrate_to_3.py

this caused the vae in the models.yaml to point to the wrong folder

Fix Typo in migrate_to_3.py

---

invokeai/backend/model_management/model_manager.py

This fixes model directory scanning so that it works properly when the root is a relative path (e.g. ".").

Fix duplicate model key addition when root directory is a relative path

---

invokeai/frontend/web/src/common/components/IAIMantineMultiSelect.tsx
invokeai/frontend/web/src/common/components/IAIMantineSelect.tsx
invokeai/frontend/web/src/theme/components/button.ts
invokeai/frontend/web/src/theme/components/tabs.ts

the light mode button colors were way off, much improved

feat(ui): tweak light mode colors, buttons pop

---

invokeai/frontend/web/config/common.ts
invokeai/frontend/web/package.json
invokeai/frontend/web/src/features/nodes/types/types.ts
invokeai/frontend/web/src/features/nodes/util/fieldTemplateBuilders.ts
invokeai/frontend/web/src/features/nodes/util/parseSchema.ts
invokeai/frontend/web/src/services/api/thunks/schema.ts
invokeai/frontend/web/yarn.lock

The node polyfills needed to run the `swagger-parser` library (used to dereference the OpenAPI schema) cause the canvas tab to immediately crash when the package build is used in another react application.
I'm sure this is fixable but it's not clear what is causing the issue and troubleshooting is very time consuming.
Selectively rolling back the implementation of `swagger-parser`.

fix(ui): fix canvas crash by rolling back swagger-parser

---

invokeai/frontend/web/src/features/ui/components/InvokeTabs.tsx
invokeai/frontend/web/src/features/ui/hooks/useMinimumPanelSize.ts

Add `useMinimumPanelSize()` hook to provide minimum resizable panel sizes (in pixels).
The library we are using for the gallery panel uses percentages only. To provide a minimum size in pixels, we need to do some math to calculate the percentage of window size that corresponds to the desired min width in pixels.

feat(ui): minimum gallery size

---

invokeai/frontend/web/src/features/gallery/components/GalleryPanel.tsx
invokeai/frontend/web/src/features/ui/components/InvokeTabs.tsx

- Set min size for floating gallery panel
- Correct the default pinned width (it cannot be less than the min width and this was sometimes happening during window resize)

feat(ui): gallery minSize tweak

---

invokeai/frontend/web/src/app/components/App.tsx
invokeai/frontend/web/src/features/gallery/components/ImageGalleryContent.tsx
invokeai/frontend/web/src/features/gallery/store/imagesSlice.ts
invokeai/frontend/web/src/features/system/components/ModelSelect.tsx

Need to keep suspense loading state so that $client is created correctly in time for API requests
Do we need to keep the more global `isAppReady` stuff?

loading state for gallery and model list

---

invokeai/frontend/web/src/features/nodes/components/ui/NodeInvokeButton.tsx
invokeai/frontend/web/src/features/parameters/components/ProcessButtons/InvokeButton.tsx
invokeai/frontend/web/src/features/system/components/ProgressBar.tsx
invokeai/frontend/web/src/theme/components/progress.ts

@blessedcoolant  it looks like with the new theme buttons not being transparent the progress bar was completely hidden, I moved to be on top, however it was not transparent so it hid the invoke text, after trying for a while couldn't get it to be transparent, so I just made the height 15%,

Fix Invoke Progress Bar

---

invokeai/app/invocations/compel.py

This commit prevents each image generation from leaking ~160 MB of VRAM. Thanks to @damian0815 and @StAlKeR7779 for helping to sort this out.

Quash memory leak when compel invocation called

---

invokeai/frontend/web/src/app/components/ImageDnd/DragPreview.tsx
invokeai/frontend/web/src/app/components/ImageDnd/typesafeDnd.tsx
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageDropped.ts
invokeai/frontend/web/src/features/batch/components/BatchImage.tsx
invokeai/frontend/web/src/features/controlNet/components/ControlNetImagePreview.tsx
invokeai/frontend/web/src/features/gallery/components/CurrentImagePreview.tsx
invokeai/frontend/web/src/features/gallery/components/GalleryImage.tsx
invokeai/frontend/web/src/features/lora/components/ParamLoraList.tsx
invokeai/frontend/web/src/features/nodes/components/fields/ImageInputFieldComponent.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamCFGScale.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamHeight.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamIterations.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamSteps.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamWidth.tsx

[fix(ui): fix selector memoization](https://github.com/invoke-ai/InvokeAI/commit/1323a45e30e95d671851b0cbbcc36d07dc4821d5)
Every `GalleryImage` was rerendering any time the app rerendered bc the selector function itself was not memoized. This resulted in the memoization cache inside the selector constantly being reset.
Same for `BatchImage`.
Also updated memoization for a few other selectors.
[fix(ui): change multi image drop to not have selection as payload](https://github.com/invoke-ai/InvokeAI/commit/4816fa9996f27b0543ecea7601ed024599e735b9)
This caused a lot of re-rendering whenever the selection changed, which caused a huge performance hit. It also made changing the current image lag a bit.
Instead of providing an array of image names as a multi-select dnd payload, there is now no …

ui: render perf fixes

---

invokeai/app/invocations/compel.py
invokeai/app/invocations/latent.py
invokeai/backend/model_management/lora.py
invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildCanvasInpaintGraph.ts
invokeai/frontend/web/src/features/ui/components/tabs/UnifiedCanvas/UnifiedCanvasParameters.tsx

- Add Loras to Canvas
- Revert inference_mode to no_grad coz inference tensors fail with latent to latent.

feat: Add Lora to Canvas

---

invokeai/frontend/web/src/common/components/IAICollapse.tsx
invokeai/frontend/web/src/common/components/IAISwitch.tsx
invokeai/frontend/web/src/features/controlNet/components/parameters/ParamControlNetFeatureToggle.tsx
invokeai/frontend/web/src/features/controlNet/util/getValidControlNets.ts
invokeai/frontend/web/src/features/dynamicPrompts/components/ParamDynamicPromptsCollapse.tsx
invokeai/frontend/web/src/features/dynamicPrompts/components/ParamDynamicPromptsEnabled.tsx
invokeai/frontend/web/src/features/dynamicPrompts/components/ParamDynamicPromptsMaxPrompts.tsx
invokeai/frontend/web/src/features/lora/components/ParamLoraCollapse.tsx
invokeai/frontend/web/src/features/nodes/util/addControlNetToLinearGraph.ts
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/BoundingBox/ParamBoundingBoxCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/InfillAndScaling/ParamInfillAndScalingCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/SeamCorrection/ParamSeamCorrectionCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/ControlNet/ParamControlNetCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Hires/ParamHiresCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Hires/ParamHiresToggle.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Noise/ParamNoiseCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Noise/ParamNoiseThreshold.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Noise/ParamNoiseToggle.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Noise/ParamPerlinNoise.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Seamless/ParamSeamlessCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Symmetry/ParamSymmetryCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Symmetry/ParamSymmetryToggle.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Variations/ParamVariationCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Variations/ParamVariationToggle.tsx
invokeai/frontend/web/src/features/parameters/store/generationSlice.ts
invokeai/frontend/web/src/features/ui/components/tabs/ImageToImage/ImageToImageTabCoreParameters.tsx
invokeai/frontend/web/src/features/ui/components/tabs/TextToImage/TextToImageTabCoreParameters.tsx
invokeai/frontend/web/src/features/ui/components/tabs/UnifiedCanvas/UnifiedCanvasCoreParameters.tsx

- Accordions now may be opened or closed regardless of whether or not their contents are enabled or active
- Accordions have a short text indicator alerting the user if their contents are enabled, either a simple `Enabled` or, for accordions like LoRA or ControlNet, `X Active` if any are active
https://github.com/invoke-ai/InvokeAI/assets/4822129/43db63bd-7ef3-43f2-8dad-59fc7200af2e

feat(ui): improve accordion ux

---

invokeai/backend/install/migrate_to_3.py

A user discovered that 2.3 models whose symbolic names contain the "/" character are not imported properly by the `migrate-models-3` script. This fixes the issue by changing "/" to  underscore at import time.

Detect invalid model names when migrating 2.3->3.0

---

invokeai/backend/install/migrate_to_3.py

This PR fixes the migrate script so that it uses the same directory for both the tokenizer and text encoder CLIP models. This will fix a crash that occurred during checkpoint->diffusers conversions
This PR also removes the check for an existing models directory in the target root directory when `invokeai-migrate3` is run.

Put tokenizer and text encoder in same clip-vit-large-patch14

---

invokeai/backend/install/model_install_backend.py
invokeai/backend/model_management/model_manager.py
invokeai/backend/model_management/model_probe.py
invokeai/frontend/install/model_install.py

This PR enables model manager importation of diffusers-style .bin LoRAs. However, since there is no backend support for this type of LoRA yet, attempts to use them will result in an unimplemented error.
It closes #3636 and #3637

LoRA model loading fixes

---

invokeai/backend/install/invokeai_configure.py
invokeai/backend/model_management/model_cache.py

This PR allows the user to set the model manager cache size from within the `invokeia-configure` TUI.

expose max_cache_size to invokeai-configure interface

---

invokeai/frontend/web/src/features/nodes/util/graphBuilders/addLoRAsToGraph.ts
invokeai/frontend/web/src/features/parameters/components/Parameters/Advanced/ParamAdvancedCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Advanced/ParamClipSkip.tsx
invokeai/frontend/web/src/features/parameters/store/generationSlice.ts

Clip Skip breaks when you supply a number greater than the number of layers for the model type. So capping this out based on the model on the frontend
- `sd-1` at 12
- `sd-2` at 24
- Will update later to whatever SDXL needs if it is different.
- Also fixes LoRA's breaking with Clip Skip.

fix: Adjust clip skip layer count based on model

---

invokeai/frontend/install/invokeai_update.py

Windows doesn't like single quotes in its command shell causing the update script's pip command to fail. This fixes the issue.

Make the update script work on Windows

---

invokeai/frontend/web/src/common/components/IAISlider.tsx
invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasToolChooserOptions.tsx
invokeai/frontend/web/src/features/dynamicPrompts/components/ParamDynamicPromptsMaxPrompts.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/BoundingBox/ParamBoundingBoxHeight.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/BoundingBox/ParamBoundingBoxWidth.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/InfillAndScaling/ParamScaledHeight.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/InfillAndScaling/ParamScaledWidth.tsx
invokeai/frontend/web/src/features/ui/components/tabs/UnifiedCanvas/UnifiedCanvasBeta/UnifiedCanvasToolSettings/UnifiedCanvasBrushSize.tsx

There was a props on IAISlider to make the input component readonly - I didn't know this existed and at some point used a component with that prop as a template for other sliders, copying the flag over.
It's not actually used anywhere, so I removed the prop entirely, enabling the number inputs everywhere.

fix(ui): fix readonly inputs

---

invokeai/frontend/web/src/app/store/middleware/devtools/actionsDenylist.ts
invokeai/frontend/web/src/common/components/IAIInput.tsx
invokeai/frontend/web/src/common/components/IAIMantineMultiSelect.tsx
invokeai/frontend/web/src/common/components/IAIMantineSelect.tsx
invokeai/frontend/web/src/common/components/IAINumberInput.tsx
invokeai/frontend/web/src/common/components/IAISlider.tsx
invokeai/frontend/web/src/common/components/IAITextarea.tsx

The shift key listener didn't catch pressed when focused in a textarea or input field, causing jank on slider number inputs.
Add keydown and keyup listeners to all such fields, which ensures that the `shift` state is always correct.
Also add the action tracking it to `actionsDenylist` to not clutter up devtools.

fix(ui): fix inconsistent shift modifier capture

---

invokeai/frontend/web/src/features/ui/components/InvokeTabs.tsx

model manager was using the wrong key due to the tabs render func subbing values in. made translation key a prop of a tab item.

fix(ui): fix tab translations

---

invokeai/app/services/config.py

I made a recent change to the function that finds the default root directory locatoin that broke it when run under Conda (where VIRTUAL_ENV is not set). This revision fixes the issue.

Version of _find_root() that works in conda environment

---

invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamModelandVAEandScheduler.tsx

Some users want the model select to take full width coz their model names might be long. As this is a more frequently used feature, rearrange it to do that.
Followed by VAE (as it is related to the model) and the Sampler next to it.

fix: Rearrange Model Select to take full width

---

invokeai/frontend/web/src/features/gallery/components/ImageGalleryGrid.tsx
invokeai/frontend/web/src/features/gallery/components/NextPrevImageButtons.tsx

@psychedelicious @blessedcoolant Somehow i deleted the branch the other version of this pull request was on. 🤭
Just an idea, if you think its worth while please make changes ( I did what I could)
I added a load more to the right arrow to avoid having to open gallery to load more images,
I am not sure about the icon i used, maybe it should just be the normal arrow, so you don't even need to show its loading more images.
there is an issue with it not disappearing once all images have been loaded, (I did play around for a while to try and fix that)

add load more images to the right arrow

---

invokeai/app/api_app.py

It's possible for the Windows mimetypes for js to be changed and cause content-type errors when running the app.
Explicitly set the mimetypes to rectify this. Note that the root cause is a misconfiguration on the client - not our end.
See https://github.com/invoke-ai/InvokeAI/discussions/3684#discussioncomment-6391352

fix(api): fix for borked windows mimetypes registry

---

invokeai/app/services/image_record_storage.py
invokeai/frontend/web/src/features/gallery/components/ImageContextMenu.tsx
invokeai/frontend/web/src/features/gallery/components/NextPrevImageButtons.tsx
invokeai/frontend/web/src/features/parameters/components/ProcessButtons/InvokeButton.tsx

[feat(ui): memoize ImageContextMenu selector](https://github.com/invoke-ai/InvokeAI/commit/265996d230f4727d1f58c3e75cdc847ddac6497b)
Without the selector itself being memoized, the gallery was rerendering on every progress image.
[feat(ui): memoize NextPrevImageButtons component](https://github.com/invoke-ai/InvokeAI/commit/a7b8109ac28d13bfc62d0246b2c07f139dc95358)
This was rerendering on every progress image, now it doesn't
[fix(ui): correctly set disabled on invoke button during generation](https://github.com/invoke-ai/InvokeAI/commit/1c45d18e6d1065dc875e98a6e510ddc51d098a4c)
It wasn't disabled when it should have been, looked clickable during generation.
[fix(nodes): remove board_id column from images table](https://github.com/invoke-ai/InvokeAI/commit/00e26ffa9a9d6d632c730312ee6bccfb87 …

ui, db: rand fixes

---

tests/test_config.py

Due to the deprecation of the old --max_loaded_models configuration parameter, the test-config.py regression test stopped working. This fixes the problem.

Fix the test of the config system

---

invokeai/frontend/web/src/common/components/IAINumberInput.tsx
invokeai/frontend/web/src/features/nodes/components/IAINode/IAINodeHeader.tsx
invokeai/frontend/web/src/features/nodes/components/IAINode/IAINodeInputs.tsx
invokeai/frontend/web/src/features/nodes/components/InvocationComponent.tsx
invokeai/frontend/web/src/features/nodes/components/NodeWrapper.tsx
invokeai/frontend/web/src/features/nodes/components/ProgressImageNode.tsx
invokeai/frontend/web/src/features/nodes/components/fields/NumberInputFieldComponent.tsx
invokeai/frontend/web/src/features/nodes/hooks/useBuildInvocation.ts

- Nodes are draggable only from header
- The mouse works, even *inside the node*
witness!
https://github.com/invoke-ai/InvokeAI/assets/4822129/27b1247a-d05f-4344-879d-b7a6697483d4

fix(ui): fix mouse interactions

---

invokeai/app/api/routers/models.py
invokeai/app/services/model_manager_service.py
invokeai/backend/install/model_install_backend.py
invokeai/backend/model_management/model_manager.py
invokeai/backend/model_management/model_merge.py
invokeai/backend/model_management/model_search.py
invokeai/backend/model_management/models/__init__.py
invokeai/backend/model_management/models/base.py
invokeai/backend/model_management/models/stable_diffusion.py

1. add a `/sync` route for synchronizing the in-memory model lists to models.yaml, the models directory, and the autoimport directories.
2. added optional destination directories to convert_model and merge_model operations.
3. added a `/ckpt_confs` route for retrieving known legacy checkpoint configuration files.
4. added a `/search` route for finding all models in a directory located in the server filesystem
5. added a `/add`  route for manual addition of a local models
6. added a `/rename` route for renaming and/or rebasing models
7. changed the path of the `import_model` route to `/import`
When adding a model manually using `/add`, the body JSON must exactly match one of the model configurations returned by `list_models` (i.e. there is no defaulting of fields). This includes the …

Model manager route enhancements

---

docs/features/CONFIGURATION.md
docs/index.md
invokeai/app/services/config.py

This PR adds a new documentation file that describes how to configure InvokeAI using `invokeai.yaml`, etc.

add documentation on the configuration system

---

invokeai/app/api/routers/models.py
invokeai/app/services/model_manager_service.py
invokeai/backend/model_management/__init__.py
invokeai/backend/model_management/model_manager.py

This PR allows the `update_model` API call to change the model's name and/or base type as well. The `rename_model` call has accordingly been retired.

add renaming capabilities to model update API route

---

invokeai/app/invocations/prompt.py

A new PromptFromFile custom node the provides similar functionality to the old 2.3.5 --from_file CLI command.  It reads prompts from a file one line per prompt and outputs them as a prompt collection. With inputs for filename, pre_prompt, post_prompt, start line number, and max_prompts. A max_prompts of 0 will read  int32.max number of lines from the file. 
This replaces the messed up pull request I closed PR "Create prompts_fromfile.py " https://github.com/invoke-ai/InvokeAI/pull/3757

Added class PromptsFromFileInvocation to prompt.py. 

---

pull_request_template.md

Adding a pull request template to help contributors and  reviewers handle pull requests more efficiently!

Create pull request template for the project

---

invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/common/components/IAIDndImage.tsx
invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasToolbar.tsx
invokeai/frontend/web/src/features/gallery/components/CurrentImage/CurrentImageButtons.tsx
invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageContextMenu.tsx
invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx
invokeai/frontend/web/src/features/ui/components/tabs/UnifiedCanvas/UnifiedCanvasBeta/UnifiedCanvasToolbar/UnifiedCanvasCopyToClipboard.tsx
invokeai/frontend/web/src/features/ui/hooks/useCopyImageToClipboard.ts
invokeai/frontend/web/src/theme/components/menu.ts

[feat(ui): improve context menu feel](https://github.com/invoke-ai/InvokeAI/commit/526e4d25984e3e5785c9369c22dc03c30de2db94)
- faster animation
- do not handle context menu events inside context menu (fixes issue where the context menu appears to not fire)
[feat(ui): fix copy image, add context menu to IAIDndImage](https://github.com/invoke-ai/InvokeAI/commit/9e77a7d33dc52ffc46b8cc3e310a0a6d9593de94)
- restore copy image functionality* in image context menu, current image buttons
- give IAIDndImage the same context menu
* copying image to clipboard is not possible on Firefox unless the user enables a setting which is disabled by default. if the browser does not support copying an image, the copy functionality is disabled.
[feat(ui): consolidate imagecontextmenu and send to …

ui: improve context menu

---

invokeai/frontend/web/src/app/components/GlobalHotkeys.ts
invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasBoundingBox.tsx
invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasToolChooserOptions.tsx
invokeai/frontend/web/src/features/nodes/components/AddNodeMenu.tsx
invokeai/frontend/web/src/features/nodes/components/IAINode/IAINodeHeader.tsx
invokeai/frontend/web/src/features/nodes/components/InvocationComponent.tsx
invokeai/frontend/web/src/features/nodes/components/NodeEditor.tsx
invokeai/frontend/web/src/features/nodes/components/NodeWrapper.tsx
invokeai/frontend/web/src/features/system/components/HotkeysModal/HotkeysModal.tsx
invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx
invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/ModelManagerPanel/ModelList.tsx
invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/ModelManagerPanel/ModelListItem.tsx
invokeai/frontend/web/src/theme/theme.ts
pyproject.toml

Making some final style fixes before we push the next 3.0 version tomorrow.
- Fixed light mode colors in Settings Modal.
- Double checked other light mode colors. Nothing seems off.
- Added Base Model badge to the model list item. Makes it visually better and also serves as a quick glance feature for the user.
- Some minor styling updates to the Node Editor.
- Fixed hotkeys 'G' and 'O', 'Shift+G' and 'Shift+O' used to toggle the panels not resizing canvas. #3780
- Fixed hotkey 'N' not working for Snap To Grid on Canvas.
- Fixed brush opacity hotkeys not working.
- Cleaned up hotkeys modal of hotkeys that are no longer used.
- Updated compel requirement to `2.0.0`
- Closes #3780

3.0 Pre-Release Polish -- Bug Fixes / Style Fixes / Misc

---

invokeai/app/invocations/generate.py

Fixes a bug in the `inpaint` node introduced by the new version of `compel`. The other nodes were updated, but this one was missed. Fixed by @StAlKeR7779 ty
- Related Issue # discord reports
- Closes #

fix(nodes): fix inpaint cond logic for new compel version

---

invokeai/backend/model_management/model_manager.py

- [ x] Optimization
- [ x] Yes
When `models.yaml` is read-only and the application tries to modify it, it crashes with an `OSError`. This PR avoids the crash and logs a warning message instead.

Avoid crash if unable to modify the model config file

---

invokeai/backend/model_management/model_cache.py

There no vram cleanup on models offload which leads to filling vram and slow generation speed.

Cleanup vram after models offloading

---

invokeai/app/invocations/latent.py

Fix for
```
File "/home/invokeuser/InvokeAI/invokeai/app/services/processor.py", line 70, in __process
outputs = invocation.invoke(
File "/home/invokeuser/InvokeAI/invokeai/app/invocations/latent.py", line 660, in invoke
device=choose_torch_device()
NameError: name 'choose_torch_device' is not defined
```
when using scale latents node
- Closes #

Missing def choose_torch_device

---

invokeai/frontend/web/src/features/nodes/components/ProgressImageNode.tsx
invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts

A while Back
Some tweaks to the Progress image Node
Fixed aspect ratio  and resize
Added nodesize option to nodeslice
- Closes #

Tweaks to Image Progress Node

---

invokeai/backend/model_management/model_probe.py

- [X ] Bug Fix
- [ X] No, because: it is a trivial fix
While preparing today's RC, I discovered that inpaint models were not installing correctly due to a change in the model variant enum. This fixes the issue.

fix inpaint model detection

---

invokeai/app/services/config.py

- [X ] Bug Fix
- [ X] Yes
This fixes the crash that occurs when fetching the configuration information of checkpoint models from a web server started by clicking on the launcher in Windows.
```
ValueError: 'C:\\Users\\foo\\Documents\\invokeai\\configs\\stable-diffusion\\v1-finetune.yaml' is not in the subpath of '' OR one path is relative and the other is absolute.
```
Very interesting edge case. Easy fix.

fix v1-finetune.yaml is not in the subpath of ""

---

invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/common/components/IAISwitch.tsx
invokeai/frontend/web/src/features/system/components/SettingsModal/SettingSwitch.tsx
invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx

Adds a Setting Switch component to replace the regular IAISwitch used in settings. Can now supply a `useBadge` to enable a badge and `badgeLabel` to supply badge text.

feat: Add Setting Switch Component

---

invokeai/app/invocations/latent.py
invokeai/app/invocations/sdxl.py
invokeai/app/util/step_callback.py

Add progress preview for sdxl generation nodes

Add sdxl generation preview

---

invokeai/frontend/web/src/features/gallery/components/GalleryBoardName.tsx

Fixes a bug where the board name is not displayed in the header if there are no images in it.

fix: No board name being displayed if it is empty

---

invokeai/backend/model_management/__init__.py
invokeai/backend/model_management/model_manager.py
invokeai/backend/model_management/models/__init__.py
invokeai/backend/model_management/models/base.py

- [X ] Bug Fix
- [ X] Yes
- [ X] No  -- not needed
If a model is install twice (e.g. in the autoimprot directory and the models directory) this will warn but not crash on load.
Note starred line
```
[2023-07-21 14:12:27,677]::[InvokeAI]::INFO --> InvokeAI version 3.0.0
[2023-07-21 14:12:27,688]::[InvokeAI]::DEBUG --> Config file=/home/lstein/invokeai-main/configs/models.yaml
[2023-07-21 14:12:27,688]::[InvokeAI]::INFO --> GPU device = cuda NVIDIA GeForce RTX 4070
[2023-07-21 14:12:27,688]::[InvokeAI]::DEBUG --> Maximum RAM cache size: 6.0 GiB
[2023-07-21 14:12:27,702]::[InvokeAI]::INFO --> Scanning /home/lstein/invokeai-main/models for new models
** [2023-07-21 14:12:27,703]::[InvokeAI]::WARNING --> Model with key sd-1/main/AnalogDiffusion added twice
[2023-07-21 …
```

Warn, do not crash, when duplicate models encountered

---

invokeai/frontend/web/src/features/gallery/components/CurrentImage/CurrentImageButtons.tsx

Restore deletion of current image using the "delete" hotkey.
I'm not entirely sure this is the best approach because accidentally hitting "delete" (e.g. when you think you're typing in a prompt textarea but actually aren't) could lead to accidental deletion, especially with the "don't ask for confirmation". I'd suggest modifying the default delete key to a combo like shift+delete, but I think fixing the issue is important enough in this state.
Fixes #3846.
Press delete. Rejoice upon seeing that you can quickly delete your 723 failed attempts.

Fix 'Del' hotkey to delete current image

---

invokeai/app/invocations/noise.py
invokeai/app/util/misc.py
invokeai/frontend/web/src/app/constants.ts

At some point I typo'd this and set the max seed to signed int32 max. It should be *un*signed int32 max.
This restored the seed range to what it was in v2.3.
Also fixed a bug in the Noise node which resulted in the max valid seed being one less than intended.
- Related Issues
#2843 is against v2.3 and increases the range of valid seeds substantially. Maybe we can explore this in the future but as of v3.0, we use numpy for a RNG in a few places, and it maxes out at the max `uint32`. I will close this PR as this supersedes it.
- Closes #3866
You should be able to use seeds up to and including `4294967295`.
nope!

feat: increase seed from int32 to uint32

---

mkdocs.yml

Within the `mkdocs.yml` file, there's a typo where `Model Merging` is spelled as `Model Mergeing`. I also found some unnecessary white space that I removed.
- Closes #
Might need to re-run the yml file for docs to regenerate, but I'm hardly familiar with the codebase so 🤷

docs generation: fix typo and remove trailing white space

---

invokeai/frontend/web/src/common/components/IAISlider.tsx
invokeai/frontend/web/src/features/embedding/components/ParamEmbeddingPopover.tsx
invokeai/frontend/web/src/features/lora/components/ParamLora.tsx
invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamAspectRatio.tsx

- Update the Aspect Ratio tags to show the aspect ratio values rather than Wide / Square and etc.
- Updated Lora Input to take values between -50 and 50 coz I found some LoRA that are actually trained to work until -25 and +15 too. So these input caps should mostly suffice. If there's ever a LoRA that goes bonkers on that, we can change it.
- Fixed LoRA's being sorted the wrong way in Lora Select.
- Fixed Embeddings being sorted the wrong way in Embedding Select.
- Closes #

3.0.1 - Pre-Release UI Fixes

---

invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearSDXLImageToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearSDXLTextToImageGraph.ts
invokeai/frontend/web/src/features/sdxl/components/ParamSDXLConcatPrompt.tsx
invokeai/frontend/web/src/features/sdxl/components/SDXLImageToImageTabParameters.tsx
invokeai/frontend/web/src/features/sdxl/components/SDXLTextToImageTabParameters.tsx
invokeai/frontend/web/src/features/sdxl/store/sdxlSlice.ts
invokeai/frontend/web/src/features/ui/components/ParametersDrawer.tsx
invokeai/frontend/web/src/features/ui/components/tabs/TextToImage/TextToImageTab.tsx

Style Prompt with SDXL is absolute bonkers. It overrides everything. From a ton of testing, it feels like the prompt merged with the style words actually produce results that are more in line with the prompt the user produces.
This is all very early for SDXL and the prompting is very much in its baby stages but for now, we might try to concat and then later see how 1.0 plays out.
Concat can be done with either the padding token `!` or with the defaulted `space`. In this one, we do space because in my personal testing, I found it to be closer to the original prompt.

feat: SDXL - Concat Prompt and Style for Style Prompt

---

invokeai/app/api_app.py
invokeai/backend/model_management/models/lora.py
invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/features/parameters/types/constants.ts
invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/ModelManagerPanel.tsx
invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/ModelManagerPanel/LoRAModelEdit.tsx
invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/ModelManagerPanel/ModelList.tsx
invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/ModelManagerPanel/ModelListItem.tsx
invokeai/frontend/web/src/services/api/endpoints/models.ts

- I wasn't aware one had to discuss with the team beforehand to contribute. I did join the Discord however.
- I tried ["raising my hand"](https://github.com/invoke-ai/InvokeAI#contributing) in #dev-chat on Discord but I do not have permission to write there and could not find instructions on how to get access on the readme or on the server.
- I need this feature myself anyway and I am upstreaming my contributions in the hope this can be useful to maintainers. I'd rather “ask for forgiveness rather than permission”, especially when donating my time to open-source software.
Add LoRA models to the manager tab, in addition to checkpoints and diffusers.
I do not believe anyone requested this.
1. Go to model manager
2. Click on LoRAs (or use the main list)
3. See the model info
4. Delete a LoRA

Add LoRAs to the model manager

---

invokeai/frontend/web/src/features/sdxl/components/ParamSDXLNegativeStyleConditioning.tsx
invokeai/frontend/web/src/features/sdxl/components/ParamSDXLPositiveStyleConditioning.tsx
invokeai/frontend/web/src/features/sdxl/components/ParamSDXLPromptArea.tsx
invokeai/frontend/web/src/features/sdxl/components/SDXLConcatLink.tsx

- Fix SDXL Concat Link animation not considering the fact that prompt boxes can be resized.
- Also fixed a minor issue where the overlaying animation box would block the prompt input resize slightly. Should be good now.

fix: Concat Link Styling

---

installer/lib/installer.py
installer/lib/main.py
invokeai/frontend/install/invokeai_update.py
invokeai/frontend/install/model_install.py

- [ X] Optimization
- [X ] Yes
- [X ] Yes
This PR does two things:
1. if the environment variable INVOKEAI_ROOT is defined at install time, the zipfile installer will default to its value when asking the user where to install the software
2. If the user has more than 72 models of any type installed, then the list will be truncated in the TUI and the user given a warning. Anything larger than this number of models causes the vertical space to overflow. The only effect of truncation is that the user will not be able to see and delete the models that were truncated. The message advises the user to go to the Web Model Manager interface in this event.

Installer tweaks

---

invokeai/frontend/merge/merge_diffusers.py

- [X ] Bug Fix
- [ X] Yes
The `invokeai-merge` script was crashing at an early stage due to a misnamed dict key. This has now been fixed.

Restore model merge script

---

invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/ModelManagerPanel/ModelList.tsx
invokeai/frontend/web/src/services/api/endpoints/models.ts

- [?] Optimization
- Fixed filter type select using `images` instead of `all` -- Probably some merge conflict.
- Added loading state for model lists. Handy when the model list takes longer than a second for any reason to fetch. Better to show this than an empty screen.
- Refactored the render model list function so we modify the display component in one area rather than have repeated code.
- The list can get a bit laggy on initial load when you have a hundreds of models / loras. This needs to be fixed. Will make another PR for this.

fix: Model Manager Tab Issues

---

flake.nix

patchmatch requires build dependencies including opencv4 with CUDA. Update the flake to add them.
This fixes patchmatch not being able to be built upon startup.

fix: flake: add opencv with CUDA, new patchmatch dependency

---

README.md
docs/installation/020_INSTALL_MANUAL.md

- [ X] Documentation Update
- [ X] No, because: obvious problem
- [ X] Yes
The manual installation documentation in both README.md and 020_MANUAL_INSTALL give an incomplete `invokeai-configure` command which leaves out the path to the root directory to create. As a result, the invokeai root directory gets created in the user’s home directory, even if they intended it to be placed somewhere else.
This is a fairly important issue.

Fix manual installation documentation

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageUploaded.ts
invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts

I'm not positive that I did this right - but I was running into issues locally where `autoAddBoardId` was `null`, which it seems is an unexpected state. It was getting sent as a `board_id` param when creating an upload in the "uncategorized" view. It seems that `autoAddBoardId` should always be defined, and that if a board is not selected, it should always be "none" - never null or undefined.
- Closes #

autoAddBoardId should always be defined as "none" or board_id

---

docs/installation/050_INSTALLING_MODELS.md

- [ X] Documentation Update
- [X ] No, because: noncontroversial
- [ X] Yes
Fixes broken Civitai example link in manual install documentation.
Closes #4152

fix broken civitai example link

---

invokeai/app/invocations/image.py

Hue adjustment wasn't working correctly because color channels got swapped. This has now been fixed.
The image resulting from a hue shift had discontinuities in color. This was a result of color channels being swapped prior to the conversion to/from HSV. This PR fixes the problem.
- Closes #

Fix hue adjustment

---

invokeai/frontend/web/src/features/lora/components/ParamLoraCollapse.tsx
invokeai/frontend/web/src/features/lora/components/ParamLoraList.tsx
invokeai/frontend/web/src/features/nodes/util/graphBuilders/addSDXLLoRAstoGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearSDXLImageToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearSDXLTextToImageGraph.ts
invokeai/frontend/web/src/features/sdxl/components/SDXLImageToImageTabParameters.tsx
invokeai/frontend/web/src/features/sdxl/components/SDXLTextToImageTabParameters.tsx
invokeai/frontend/web/src/services/api/schema.d.ts
invokeai/frontend/web/src/services/api/types.ts

Adds SDXL LoRA support in the Linear UI.
- new graph modifier `addSDXLLoRasToGraph()` handles adding LoRA to the SDXL t2i and i2i graphs.
1. Download and install https://civitai.com/models/118653?modelVersionId=128752 (per author, this only modifies UNet, and needs to be used with weight 2)
2. Restart server
3. Navigate to t2i tab
4. Write a simple prompt with `oil painting` in the name with manual seed, generate
5. Add the LoRA with weight 2, generate
6. Confirm the results are much more oil-painting-y
7. Generate an image without `oil painting` in the prompt, without LoRAs, to be used as init image
8. Navigate to i2i tab
9. Select the image from step 7 as init image
10. Add `oil painting` to prompt, change seed (to avoid fried images), generate
11. Add the LoRA with weight 2, generate …

feat(ui): add LoRA support to SDXL linear UI

---

invokeai/app/api/routers/images.py

Some clients, including whatever GIMP uses when you do "Open Location", do a HEAD request on a resource before downloading it.
Currently the image route only supports GET, so the HEAD request fails.
This lack of support for HEAD requests is something that should be addressed generally:
- https://github.com/tiangolo/fastapi/issues/1773
but in the meantime, I guess we handle it on a case-by-case basis? This PR adds HEAD to the route for `{image}/full`.
Test instructions:
- get the URL for a full image, perhaps by doing right-click _Open in New Tab_ and copying that URL.
- issue a HTTP HEAD request for that URL (maybe using [httpie](https://httpie.io/) or your other favorite HTTP test client) or with _File/Open Location_ in GIMP.
- ensure the request receives a `200 OK` response and/or the …

api(images): allow HEAD request on image/full

---

invokeai/backend/model_management/model_manager.py
invokeai/backend/model_management/models/sdxl.py

- [X Yes
If `models.yaml` is cleared out for some reason, the model manager will repopulate it by scanning `models`. However, this would fail with a pydantic validation error if any SDXL checkpoint models were present because the lack of logic to pick the correct configuration file. This has now been added.

Pick correct config file for sdxl models

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/tabChanged.ts

There was no check at all to see if the canvas had a valid model already selected. The first model in the list was selected every time.
Now, we check if its valid. If not, we go through the logic to try and pick the first valid model.
If there are no valid models, or there was a problem listing models, the model selection is cleared.
- Closes #4125
- Go to Canvas tab
- Select a model other than the first one in the list
- Go to a different tab
- Go back to Canvas tab
- The model should be the same as you selected

fix(ui): fix canvas model switching

---

README.md
docs/installation/010_INSTALL_AUTOMATED.md
docs/installation/020_INSTALL_MANUAL.md
docs/installation/030_INSTALL_CUDA_AND_ROCM.md
docs/installation/070_INSTALL_XFORMERS.md
installer/lib/installer.py

- [X Feature
- [X Yes
Install torch+cu118 rather than cu117. Also updates documentation regarding installing xformers and the CUDA toolkit, which were referring to older versions.

Update dependencies and docs to cu118

---

invokeai/app/api/routers/models.py
invokeai/backend/model_management/model_manager.py
tests/test_model_manager.py
tests/test_model_manager/configs/relative_sub.models.yaml

Empty model configuration fields sent by the Web Model Manager update call were sending empty strings for any field left blank, including `description` and `vae`. When the backend model manager tried to load a VAE with path `""`, it crashed.
This fixes two things:
1. If the `vae` field is an empty string, the call to `_get_model_path()` now returns `is_submodel_override` false, causing the custom VAE loading code to be bypassed. (a regression test has been added for this)
2. Added a router-level workaround to avoid writing empty strings into the model config file. These fields are replaced by None and end up not written into the config at all.
Discord bug report: https://discord.com/channels/1020123559063990373/1131987080466137219/1138829184349765652
Use the web model manager to send …

Prevent `vae: ''` from crashing model

---

invokeai/backend/install/invokeai_configure.py
invokeai/backend/install/migrate_to_3.py
invokeai/frontend/install/__init__.py
invokeai/frontend/install/invokeai_configure.py
pyproject.toml

@JPPhoto discovered that if he had previously manually set the value of `max_ram_cache` to greater than the amount available on his system, that `configure_invokeai` would crash. This is because the UI is now reading system values to set up the maximum value for the RAM and VRAM cache sliders, but was not checking that the old setting was within range.
This fixes the issue by clipping RAM and VRAM cache settings to the maximum and minimum permissible values.
It also cleans up some unneeded import code located in `invokeai.frontend.install.__init__`, which was exacerbating circular dependency issues and had no benefit other than making some `from` statements shorter. 
See this for @JPPhoto bug report and discussion thread:
https://discord.com/channels/1020123559063990373/1042475531079262378 …

Bugfix: Limit RAM and VRAM cache settings to permissible values

---

installer/lib/installer.py
invokeai/frontend/merge/merge_diffusers.py

During install testing I discovered two small problems in the command-line scripts. These are fixed.
- [X Bug Fix
- 
- installer - use correct entry point for invokeai-configure
- model merge script - prevent error when `--root` not provided

Two changes to command-line scripts

---

installer/readme.txt

One-line fix for the installer `readme.txt` file, which was still telling people that maximum python supported was 3.10.
Updated to indicate 3.9 through 3.11, consistent with other documentation.

Fix maximum python version installation instructions

---

invokeai/backend/model_management/models/lora.py

This PR introduces 2 related changes:
1. This PR adds support for SDXL LoRA models in the diffusers format. There are 2 popular SDXL LoRA weight formats: Stability AI format and diffusers format (produced by diffusers, kohya_ss, and soon invoke-training). Prior to this change, InvokeAI only supported the Stability AI format, and trying to load a LoRA model in diffusers format would raise an exception.
2. This PR fixes a bug in the current version of InvokeAI that causes all text encoder LoRA weights to be ignored. In other words, prior to this change InvokeAI was only loading UNet LoRA weights for SDXL models.
Relevant Discord conversation where someone encountered this issue: https://discord.com/channels/1020123559063990373/1133929466763161650/1139504370627661896
I tested the following …

Add support for SDXL LoRA models in diffusers format.

---

invokeai/backend/model_management/models/sdxl.py

During directory scanning for new models, if a corrupt model was detected, InvokeAI would st
Avoids this issue: https://discord.com/channels/1020123559063990373/1133929466763161650/1139606160505319575
To test:
1. Select any sdxl or sdxl-refiner model, go to its `unet` folder, and rename `config.json` to `config.json.hide`. 
2. Comment out the corresponding stanza in `models.yaml` in order to trigger a rescan of the directory.
3. Start InvokeAI
If the bug is fixed you'll get a warning that the model seems to be invalid. If not, you'll get a crash and stacktrace.

Warn instead of crashing when a corrupted model is detected during startup scan

---

invokeai/frontend/install/model_install.py
scripts/configure_invokeai.py

This fixes an import issue introduced in commit 1bfe983. The change made 'invokeai_configure' into a module but this line still tries to call it as if it's a function. This will result in a `'module' not callable` error.
imic from discord ask that I submit a PR to fix this bug.
- Closes #

Fixed import issue in invokeai/frontend/install/model_install.py

---

invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerStart.tsx
invokeai/frontend/web/src/features/sdxl/store/sdxlSlice.ts

This is the recommended value according to the paper.
Change the defaults of `refinerStart` to 0.8 -- the recommended value from the paper because the refiner was trained to deal with denoising the final 20% of the process.
https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl

fix: Change refinerStart default to 0.8

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/index.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasMaskSavedToGallery.ts
invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasMaskOptions.tsx
invokeai/frontend/web/src/features/canvas/store/actions.ts

This PR is based on #4114
Canvas Mask Options now has a new option that lets you save the mask to Assets for reusage for whatever purposes you need.

feat: Canvas - Save Mask

---

invokeai/backend/model_management/model_probe.py

- [X Yes
Enables correct detection and installation of SDXL-base controlnet models.
https://discord.com/channels/1020123559063990373/1085428210969358366/1141024732800614500

Autodetect SDXL ControlNet models

---

invokeai/app/invocations/baseinvocation.py
invokeai/app/invocations/latent.py

Adds a `Blend Latents` node which does a SLERP of two latent tensors, which is enough if somebody wants to reconstruct the functionality of variations in the nodes editor:
ie: take two `Noise` nodes, wire one to each input of Blend, and then set an alpha of eg 0.1 for classic "variations".

Add `BlendLatentsInvocation`

---

invokeai/app/services/invocation_stats.py

[fix(stats): fix fail case when previous graph is invalid](https://github.com/invoke-ai/InvokeAI/commit/d1d2d5a47d7cdfdb06b83d49ac090978b978f9ec)
When retrieving a graph, it is parsed through pydantic. It is possible that this graph is invalid, and an error is thrown.
Handle this by deleting the failed graph from the stats if this occurs.
[fix(stats): fix InvocationStatsService types](https://github.com/invoke-ai/InvokeAI/commit/1b70bd13804737e2980486a4e9069d149b38b9b9)
- move docstrings to ABC
- `start_time: int` -> `start_time: float`
- remove class attribute assignments in `StatsContext`
- add `update_mem_stats()` to ABC
- add class attributes to ABC, because they are referenced in instances of the class. if they should not be on the ABC, then maybe there needs to be some restructuring …

stats: handle exceptions

---

invokeai/backend/install/invokeai_configure.py
invokeai/frontend/install/widgets.py

This corrects a config script crash that occurred when `attention_slice_size` was set to `auto` and no previous `invokeai.yaml` file present.

fix crash that occurs when no invokeai.yaml is present

---

docs/nodes/communityNodes.md

Add GPT2RandomPromptMaker to communityNodes.md
- Closes #

Add GPT2RandomPromptMaker to communityNodes.md

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/index.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasImageToControlNet.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasMaskToControlNet.ts
invokeai/frontend/web/src/features/canvas/store/actions.ts
invokeai/frontend/web/src/features/controlNet/components/ControlNet.tsx
invokeai/frontend/web/src/features/controlNet/components/ControlNetImagePreview.tsx
invokeai/frontend/web/src/features/controlNet/components/imports/ControlNetCanvasImageImports.tsx

Send stuff directly from canvas to ControlNet
- Two new buttons available on canvas Controlnet to import image and mask.
- Click them.

feat: Send Canvas Image & Mask To ControlNet

---

invokeai/frontend/web/src/features/controlNet/components/ControlNetImagePreview.tsx

fix: Controlnet Prepreocessed Image Save Icon Missing

---

invokeai/app/invocations/latent.py
invokeai/backend/stable_diffusion/diffusers_pipeline.py

Hotfix to make second order schedulers work with mask

---

invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/AddModelsPanel/AdvancedAddCheckpoint.tsx
invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/AddModelsPanel/AdvancedAddDiffusers.tsx
invokeai/frontend/web/src/features/ui/components/tabs/ModelManager/subpanels/AddModelsPanel/util.ts

Automatically infer the name of the model from the path supplied IF the model name slot is empty. If the model name is not empty, we presume that the user has entered a model name or made changes to it and we do not touch it in order to not override user changes.
- Addresses: #4443

feat: Infer Model Name automatically if empty in Model Forms

---

invokeai/app/invocations/baseinvocation.py
invokeai/app/invocations/controlnet_image_processors.py
invokeai/app/invocations/latent.py
invokeai/app/invocations/primitives.py
invokeai/app/services/graph.py
invokeai/frontend/web/src/common/hooks/useIsReadyToInvoke.ts
invokeai/frontend/web/src/common/util/colorTokenToCssVar.ts
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/FieldHandle.tsx
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputField.tsx
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputFieldRenderer.tsx
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ControlInputField.tsx
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ImageInputField.tsx
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/LatentsInputField.tsx
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/NumberInputField.tsx
invokeai/frontend/web/src/features/nodes/hooks/useDoesInputHaveValue.ts
invokeai/frontend/web/src/features/nodes/hooks/useIsValidConnection.ts
invokeai/frontend/web/src/features/nodes/store/util/makeIsConnectionValidSelector.ts
invokeai/frontend/web/src/features/nodes/types/constants.ts
invokeai/frontend/web/src/features/nodes/types/types.ts
invokeai/frontend/web/src/features/nodes/util/fieldTemplateBuilders.ts
invokeai/frontend/web/src/features/nodes/util/fieldValueBuilders.ts
invokeai/frontend/web/src/services/api/schema.d.ts
tests/nodes/test_node_graph.py

Initial support for polymorphic field types. Polymorphic types are a single of or list of a specific type. For example, `Union[str, list[str]]`.
Polymorphics do not yet have support for direct input in the UI (will come in the future). They will be forcibly set as Connection-only fields, in which case users will not be able to provide direct input to the field.
If a polymorphic should present as a singleton type - which would allow direct input - the node must provide an explicit type hint.
For example, `DenoiseLatents`' `CFG Scale` is polymorphic, but in the node editor, we want to present this as a number input. In the node definition, the field is given `ui_type=UIType.Float`, which tells the UI to treat this as a `float` field.
The connection validation logic will prevent connecting a …

feat(nodes): polymorphic fields

---

invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/InfillAndScaling/ParamScaledHeight.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Canvas/InfillAndScaling/ParamScaledWidth.tsx

Scale Before Processing Dimensions now respect the Aspect Ratio that is locked in. This makes it way easier to control the setting when using it with locked ratios on the canvas.

feat: Scaled Bounding Box Dimensions now respect Aspect Ratio

---

docs/installation/030_INSTALL_CUDA_AND_ROCM.md

I added extra steps to update the Cudnnn DLL found in the Torch package because it wasn't optimised or didn't use the lastest version. So manually updating it can speed up iteration but the result might differ from each card. Exemple i passed from 3 it/s to a steady 20 it/s.
- Closes #

Added extra steps to update the Cudnnn DLL found in the Torch packages

---

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml

Minor corrections to spell and grammar in the feature request template.
This PR should be self explanatory.
Minor corrections to spell and grammar in the feature request template.
No code or behavioural changes.
- Closes #
N/A
There are no tests for the issue template.

fix(docs): Correct spelling and grammar in feature request template

---

invokeai/app/invocations/latent.py
invokeai/backend/model_management/model_cache.py

Pytorch has added an `empty_cache()` method for MPS, just as it has had for CUDA. This PR adds a `mps.empty_cache()` wherever there was a `torch.cuda.empty_cache()` in model_cache.py and latent.py. It helps significantly, especially after VAE decode.
`from torch import mps` was added, as there's currently a namespace issue in torch, so `torch.mps` can't be used as `torch.cuda` can be.
This change has been tested by myself and another MPS user - the torch.cuda.empty_cache() calls never caused any bother on non-CUDA hardware, so I'm hoping that the reverse is also true. I don't have the hardware to test this, though.
- Closes #
Test that you are able to load models and generate images as normal. 
Nope.

Add empty_cache() for MPS hardware

---

invokeai/frontend/web/src/app/components/App.tsx
invokeai/frontend/web/src/app/components/InvokeAIUI.tsx
invokeai/frontend/web/src/app/store/nanostores/customStarUI.ts
invokeai/frontend/web/src/app/store/nanostores/headerComponent.ts
invokeai/frontend/web/src/app/store/nanostores/index.ts
invokeai/frontend/web/src/app/store/store.ts
invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/MultipleSelectionMenuItems.tsx
invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx
invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx
invokeai/frontend/web/src/features/ui/store/uiSlice.ts
invokeai/frontend/web/src/features/ui/store/uiTypes.ts

Resolves an issue introduced in #4530 and enables checks to ensure we get a warning about this in the future.
JSX is not serializable, so it cannot be in redux. Non-serializable global state may be put into `nanostores`.
- Use `nanostores` for `customStarUI`
- Use `nanostores` for `headerComponent`
- Re-enable the serializable & immutable check redux middlewares
- Related PR #4530

fix(ui): store customStarUI outside redux

---

invokeai/app/invocations/image.py

Testing required the width and height to be multiples of 8. This is no longer needed.
Removed requirement that width and height for resizing be multiples of 8; this was originally there for testing and is no longer
needed.

Remove multiple of 8 requirement for ImageResizeInvocation

---

invokeai/frontend/web/src/features/canvas/components/IAICanvas.tsx
invokeai/frontend/web/src/features/canvas/util/calculateScale.ts
invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx

A few weeks back, we changed how the canvas scales in response to changes in window/panel size.
This introduced a bug where if we the user hadn't already clicked the canvas tab once to initialize the stage elements, the stage's dimensions were zero, then the calculation of the stage's scale ends up zero, then something is divided by that zero and Konva dies.
This is only a problem on Chromium browsers - somehow Firefox handles it gracefully.
Now, when calculating the stage scale, never return a 0 - if it's a zero, return 1 instead. This is enough to fix the crash, but the image ends up centered on the top-left corner of the stage (the origin of the canvas).
Because the canvas elements are not initialized at this point (we haven't switched tabs yet), the stage dimensions fall back to …

fix(ui): fix send to canvas crash

---

invokeai/frontend/web/src/app/store/store.ts

The immutable and serializable checks for redux can cause substantial performance issues. The immutable check in particular is pretty heavy. It's only run in dev mode, but this and really slow down the already-slower performance of dev mode.
The most important one for us is serializable, which has far less of a performance impact.
The immutable check is largely redundant because we use immer-backed RTK for everything and immer gives us confidence there.
Disable the immutable check, leaving serializable in.
- Related Issue # https://discord.com/channels/1020123559063990373/1149513625321603162/1151844513413861496

feat(ui): disable immutable redux check

---

invokeai/backend/util/hotfixes.py

In 0.21.0 diffusers in lora-conv forward function `scale` argument added.
!!! Check someone before merge as I can't run it now to test.

Update lora hotfix to new diffusers version(scale argument added)

---

pyproject.toml

Building invoke-ai's web with yarn adds python files that do not pass with flake8.
This only affect devs who run flake8 on the whole code base after having run yarn.
The added python files are outside the scope of this repo and so should not be checked with flake8.
- Closes #
None

Adding excludes to flake8 config

---

invokeai/app/invocations/baseinvocation.py
invokeai/app/services/events.py
invokeai/app/services/invocation_queue.py
invokeai/app/services/invoker.py
invokeai/app/services/model_manager_service.py
invokeai/app/services/processor.py
invokeai/app/services/session_processor/session_processor_default.py
invokeai/app/services/session_queue/session_queue_sqlite.py
invokeai/app/util/step_callback.py
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/addCommitStagingAreaImageListener.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketQueueItemStatusChanged.ts
invokeai/frontend/web/src/features/canvas/components/IAICanvasIntermediateImage.tsx
invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
invokeai/frontend/web/src/features/canvas/store/canvasTypes.ts
invokeai/frontend/web/src/features/system/store/systemSlice.ts
invokeai/frontend/web/src/features/system/store/types.ts
invokeai/frontend/web/src/services/events/types.ts
tests/nodes/test_graph_execution_state.py
tests/nodes/test_invoker.py

[fix: canvas not working on queue](https://github.com/invoke-ai/InvokeAI/commit/365e9ec8b8214e20efba03e8a32bb14767a13836)
Add `batch_id` to outbound events. This necessitates adding it to both `InvocationContext` and `InvocationQueueItem`. This allows the canvas to receive images.
When the user enqueues a batch on the canvas, it is expected that all images from that batch are directed to the canvas.
The simplest, most flexible solution is to add the `batch_id` to the invocation context-y stuff. Then everything knows what batch it came from, and we can have the canvas pick up images associated with its list of canvas `batch_id`s.
(This was on my list to fix yesterday but I forgot it)
- (https://discord.com/channels/1020123559063990373/1130288930319761428/1153996433612099604)
- Closes #4598 …

fix: canvas with queue

---

invokeai/frontend/web/src/features/parameters/components/Parameters/ControlNet/ParamControlNetCollapse.tsx

I wasn't able to pin down exact steps to replicate but frequently the `+` icon for adding a controlnet was disabled and I think it was because the store did not realize that there were any response. I also noticed that the UI is making each model (and some board requests) twice on page load, but the controlnet one _was_ omitted from the second batch without this change. We should probably fix the double requests but I'm not even sure where to start on that.
Double requests (with this change, you can see controlnet request in second batch)
Double requests (without this change, no controlnet request in second batch)
- Closes #

fix case where controlnet + is sometimes disabled

---

invokeai/frontend/web/src/features/controlNet/components/parameters/ParamControlNetFeatureToggle.tsx

wrap control net button with div to add width

---

installer/templates/invoke.bat.in
installer/templates/invoke.sh.in
invokeai/backend/util/db_maintenance.py
pyproject.toml

- 
This is a slightly modified version of techjedi's database maintenance script. It provides three functions:
1. Scan the database and remove entries for images that no longer exist on disk (db orphans)
2. Scan the output directory and archive images that are not referenced in the database (image orphans)
3. Regenerate thumbnail images that don't exist
I modified the script to allow for headless operation from the command line.
This will enter interactive mode:
```
invokeai-db-maintenance --root ~/invokeai --operation ask
```
This will run a specific operation:
```
invokeai-db-maintenance --root ~/invokeai --operation thumbnails
```
This will run all three operations in an appropriate order:
```
invokeai-db-maintenance --root ~/invokeai --operation all
```
The default is to ask. If …

Add techjedi's database maintenance script

---

invokeai/frontend/web/src/features/nodes/util/graphBuilders/addControlNetToLinearGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/addIPAdapterToLinearGraph.ts

fix(ui): add control adapters to canvas coherence pass
- Closes #4619
- Closes #4589 
I cannot figure out how to get the CLIP Vision model installed but I can confirm that the graph is correct, because I get a Model Not Found error that references this model, when invoking with IP adapter enabled..

fix(ui): add control adapters to canvas coherence pass

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageDropped.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageUploaded.ts
invokeai/frontend/web/src/features/controlNet/components/ControlNet.tsx
invokeai/frontend/web/src/features/controlNet/components/ControlNetImagePreview.tsx
invokeai/frontend/web/src/features/controlNet/components/ipAdapter/ParamIPAdapterFeatureToggle.tsx
invokeai/frontend/web/src/features/controlNet/components/ipAdapter/ParamIPAdapterImage.tsx
invokeai/frontend/web/src/features/controlNet/components/ipAdapter/ParamIPAdapterModelSelect.tsx
invokeai/frontend/web/src/features/controlNet/store/controlNetSlice.ts
invokeai/frontend/web/src/features/parameters/components/Parameters/ControlNet/ParamControlNetCollapse.tsx

[feat(ui): enable control adapters on image drop](https://github.com/invoke-ai/InvokeAI/commit/aa4b56baf201d223dea1e6c1760e55ab74e63e3c)
- Dropping/uploading an image on control adapter enables it (controlnet & ip adapter)
- The image components are always enabled to allow this

feat(ui): enable control adapters on image drop

---

pyproject.toml

Since https://github.com/invoke-ai/InvokeAI/pull/4552 python-socketio is required as a dependency. It was a dependancy of fastapi-socketio before it got removed.
This resolves the issue of "ModuleNotFoundError: No module named 'socketio'" on a fresh .venv on 3.2.0RC1 
- Closes #

Add missing python-socketio dependency

---

invokeai/frontend/web/src/common/components/IAIDroppable.tsx
invokeai/frontend/web/src/features/dnd/components/AppDndContext.tsx
invokeai/frontend/web/src/features/dnd/util/customPointerWithin.ts

fix(ui): skip firing collision detection on dnd when droppable scrolled out
Requires some additional logic in the collision detection algorithm.
Closes #4621
https://github.com/invoke-ai/InvokeAI/assets/4822129/88e3e6d1-d038-47ec-8410-81b76de3cf2f

fix(ui): skip firing collision detection on dnd when droppable scrolled out

---

invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/common/components/IAIInformationalPopover.tsx
invokeai/frontend/web/src/common/components/IAIMantineMultiSelect.tsx
invokeai/frontend/web/src/common/components/IAIMantineSearchableSelect.tsx
invokeai/frontend/web/src/common/components/IAIMantineSelect.tsx
invokeai/frontend/web/src/common/components/IAINumberInput.tsx
invokeai/frontend/web/src/common/components/IAISlider.tsx
invokeai/frontend/web/src/common/components/IAISwitch.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamIterations.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamNegativeConditioning.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Core/ParamPositiveConditioning.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/MainModel/ParamMainModelSelect.tsx
invokeai/frontend/web/src/theme/components/popover.ts

The informational popover wrapped children in a `div`. This can cause layout and interaction issues if we are not careful.
- replace the wrapper with a `Box` which handles refs
- rearrange some layouting of popover trigger components to not interrupt layout flow of a few components
- change the styling of the popover to better match the application (minor)
- render the popover in a portal so it can use any `placement`
- update the verbiage a bit
- update the types for the popover component
It's possible there are other layout issues lurking but it seems mostly ok now.
I'd like to find a way to do this without wrapping trigger components as this restricts how the popover component may be used. Perhaps we can instead use the `PopoverAnchor` or refs to position the popovers and trigger them. …

fix(ui): popover ref & wrapping of children (wip)

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasCopiedToClipboard.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasDownloadedAsImage.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasImageToControlNet.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasSavedToGallery.ts
invokeai/frontend/web/src/features/canvas/util/getBaseLayerBlob.ts
invokeai/frontend/web/src/features/system/util/copyBlobToClipboard.ts
invokeai/frontend/web/src/features/ui/hooks/useCopyImageToClipboard.ts

throwing Error in getBaseLayerBlob, instead of returning nil using copyBlobToClipboard for both Canvas and Text2Image clipboard functionality
Safari ClipboardItem functionality only works with unresolved Promises. Chrome (and Firefox with the ClipboardItem setting enabled) work with either.
Test copy to clipboard on both Canvas and Image2Text. Save to Gallery, Download Image and Send to ControlNet functionality on Canvas were also slightly affected.

fix(ui): passing Promise into ClipboardItem to make it work in Safari

---

invokeai/frontend/web/src/features/nodes/components/sidePanel/NodeEditorPanelGroup.tsx

fix(ui): workflow editor side panel remembers positioning
closes #4402

fix(ui): workflow editor side panel remembers positioning

---

invokeai/frontend/web/src/app/components/App.tsx
invokeai/frontend/web/src/features/parameters/hooks/usePreselectedImage.ts

…Parameters dep as it causes circular logic with model being set
Removed `recallAllParameters` dep in preselected image action because in introduced a circular dep causing infinite rerenders. Recalling all metadata sets the model, which then causes the `prepareLoRAMetadataItem` to change, which is a dep of `recallAllParameters, triggering a cycle. I know there is a better way to fix this but not sure what it is @psychedelicious 
- Closes #

fix circular dep with `recallAllParameters`

---

invokeai/app/services/config/invokeai_config.py
tests/test_config.py

Pedantic was misconfigured and was not picking up the INVOKEAI_ prefix on environment variables. Therefore, if the system had an unrelated environment variable such as `version`, this caused pedantic validation errors.
- Closes #4098

Respect INVOKEAI_ prefix on environment variables

---

pyproject.toml

Since https://github.com/invoke-ai/InvokeAI/commit/c82da330dbbbbb1eb1f9271f445e0ac45c32e8c5 the Safetensors package is pinned to version 0.3.1 because at the time no ARM64 builds for MacOSX were available. This has since changed and the most recent version (0.3.3) has all packages available. https://pypi.org/project/safetensors/0.3.3/#files (also for 0.3.2 now)
Safetensors is a core dependency for Diffusers and Transformers and part of the Huggingface ecosystem. In the release notes for version 0.3.3 the developers announce breaking changes for version 0.4.0.
https://github.com/huggingface/safetensors/releases
This small little change makes sure:
1) That we use the most recent version of Safetensors again, since the reason for pinning it has been solved.
2) We safeguard against breaking …

Unpin Safetensors dependency, safeguard against future breaking changes

---

invokeai/app/api/routers/models.py
invokeai/backend/install/model_install_backend.py
invokeai/backend/model_management/convert_ckpt_to_diffusers.py
invokeai/backend/model_management/model_probe.py
invokeai/configs/stable-diffusion/v1-inference-v.yaml
invokeai/frontend/web/dist/locales/en.json
invokeai/frontend/web/public/locales/en.json

It turns out that there are a few SD-1 models that use the `v_prediction` SchedulerPredictionType. Examples here: https://huggingface.co/zatochu/EasyFluff/tree/main . Previously we only allowed the user to set the prediction type  for sd-2 models. This PR does three things:
1. Add a new checkpoint configuration file `v1-inference-v.yaml`. This will install automatically on new installs, but for existing installs users will need to update and then run `invokeai-configure` to get it.
2. Change the prompt on the web model install page to indicate that some SD-1 models use the "v_prediction" method
3. Provide backend support for sd-1 models that use the v_prediction method.
- Closes #4277 
Update, run `invoke-ai-configure --yes --skip-sd --skip-support`, and then use the web …

Enable v_prediction for sd-1 models

---

invokeai/backend/model_management/model_search.py

ip_adapter models live in a folder containing the file `image_encoder.txt` and a safetensors file. The load-time probe for new models was detecting the files contained within the folder rather than the folder itself, and so models.yaml was not getting correctly updated. This fixes the issue.

fix probing for ip_adapter folders

---

invokeai/app/api_app.py

Unused import of logging in api_app.py breaks flake8 tests
- Closes #

Removing logging import from api_api.py

---

invokeai/frontend/web/src/features/gallery/components/CurrentImage/CurrentImageButtons.tsx

Change the statement to explicitly look for null and undefined so it doesn't fail to re-enable the button on images with seeds set to zero.
- Closes #4156
Its only a small line change, and I have tested it to make sure the button still disables when there's no metadata on the image and that it still works for zero and non-zero seed images. However, another set of eyes to make sure I didn't overlook something breaking with the change would be nice.

Re-enable button for seeds set to zero

---

invokeai/backend/install/model_install_backend.py
invokeai/configs/INITIAL_MODELS.yaml
invokeai/frontend/install/model_install.py

This PR adds support for selecting and installing IP-Adapters at configure time. The user is offered the four existing InvokeAI IP Adapters in the UI as shown below. The matching image encoders are selected and installed behind the scenes. That is, if the user selects one of the three sd15 adapters, then the SD encoder will be installed. If they select the sdxl adapter, then the SDXL encoder will be installed.
Note that the automatic selection of the encoder does not work when the installer is run in headless mode. I may be able to fix that soon, but I'm out of time today.

Add installer support for ip-adapters

---

invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/common/components/IAIImageFallback.tsx
invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemSkeleton.tsx
invokeai/frontend/web/src/features/queue/components/QueueList/QueueList.tsx

feat(ui): use spinner for queue loading state
Skeletons are for when we know the number of specific content items that are loading. When the queue is loading, we don't know how many items there are, or how many will load, so the whole list should be replaced with loading state.
The previous behaviour rendered a static number of skeletons. That number would rarely be the right number - the app shouldn't say "I'm loading 7 queue items", then load none, or load 50. This is a jarring user experience.
A future enhancement could use the queue item skeleton component and go by the total number of queue items, as reported by the queue status. I tried this but had some layout jankiness, not worth the effort right now. Also, the whole list is re-rendered so first it blanks out for a moment, then …

feat(ui): use spinner for queue loading state

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasImageToControlNet.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasMaskToControlNet.ts
invokeai/frontend/web/src/features/canvas/util/getBaseLayerBlob.ts

fix: Always use bbox bounds for Controlnet Image (canvas)

---

invokeai/frontend/web/src/features/queue/hooks/useCancelCurrentQueueItem.ts

fix(ui): only disable cancel item button if value is null/undefined
0 is falsy and the `item_id` is an integer
---
This would cause the very first queue item to not be cancelable.

fix(ui): only disable cancel item button if value is null/undefined

---

invokeai/frontend/web/src/features/nodes/util/graphBuilders/addSDXLRefinerToGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildCanvasSDXLInpaintGraph.ts

In the Refiner Graph, the inpaint mask was trying to retrieve `mask_combine` node for non-scaled processing. But inpainting does not combine masks causing the graph to crash when using Refiner. This PR should address that.
- Closes #4586 -- Untested (coz I can't test right now) but if anyone else can test this, we can go ahead.

fix: SDXL Refiner using the incorrect node during inpainting

---

invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/features/canvas/components/IAICanvas.tsx
invokeai/frontend/web/src/features/canvas/components/IAICanvasImageErrorFallback.tsx
invokeai/frontend/web/src/features/canvas/components/IAICanvasStagingArea.tsx
invokeai/frontend/web/src/features/canvas/components/IAICanvasStagingAreaToolbar.tsx
invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasBoundingBox.tsx
invokeai/frontend/web/src/features/canvas/store/canvasSelectors.ts
invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts

[fix(ui): fix canvas staging images offset from bounding box](https://github.com/invoke-ai/InvokeAI/commit/9a3c5705142390194266a6e5b56d628c4c167522)
The staging area used the stage bbox, not the staging area bbox.
[fix(ui): memoize event handlers on bounding box](https://github.com/invoke-ai/InvokeAI/commit/c67437c6d5e3c39fc8bc01d62f6481c7d6ff9dbb)
[fix(ui): canvas is staging if is listening for batch ids](https://github.com/invoke-ai/InvokeAI/commit/919a372bad1f896f2e5640dd57d401f24c8705bc)
[fix(ui): reset canvas batchIds on staging area init/discard/commit](https://github.com/invoke-ai/InvokeAI/commit/9e90ab8378e13bbf06138e548f86c60220b16e94)
This prevents the bbox from being used inadvertantly during canvas generation
[feat(ui): hide mask when …

feat/fix(ui): canvas bbox bug & enhancements

---

docs/installation/050_INSTALLING_MODELS.md
invokeai/backend/install/model_install_backend.py
invokeai/configs/INITIAL_MODELS.yaml

[## What type of PR is this? (check all applicable)
Very rarely a model lives in the subfolder of a non-pipeline HuggingFace repo_id. The example I've been working with is https://huggingface.co/monster-labs/control_v1p_sd15_qrcode_monster/tree/main, where the improved monster QR code controlnet model lives in the `v2` subdirectory.
In order to accommodate installing such files, I have made two changes to the model installer.
1. At installation/configuration time, if a stanza in `INITIAL_MODELS.yaml` contains the field `subfolder`, then the model will be installed from the indicated subfolder. The syntax in this case is:
```
sd-1/controlnet/qrcode_monster:
repo_id: monster-labs/control_v1p_sd15_qrcode_monster
subfolder: v2
```
2. From within the Web GUI or the installer TUI, if you wish …

enable downloading from subfolders for repo_ids

---

invokeai/frontend/web/src/features/controlNet/components/ipAdapter/ParamIPAdapterImage.tsx

Very tall IP adapter images didn't get fit to the panel. Now they do

fix(ui): fit ip adapter image to panel

---

invokeai/app/invocations/facetools.py

Make the font file relative to this source file. Not ideal, but it will work no matter where InvokeAI is launched. Also moved font loading to inside of the class where it's used.

Fix absolute path for font file

---

invokeai/app/invocations/infill.py

cv2 infill node was missing a version in its decorator, resulting in a red exclamation mark on the node

add version to cv2 infill

---

docs/nodes/communityNodes.md

Grid to Gif is two custom nodes, one that divides a grid image into an image collection, the other converts an image collection into a animated gif

Added GridtoGif to communityNodes.md

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts

Restore logic that updates board cover image when images are added or removed from it.
- Closes #

invalidate board cache when an image is added to a board

---

invokeai/frontend/web/src/features/canvas/components/IAICanvasStagingAreaToolbar.tsx
invokeai/frontend/web/src/features/canvas/store/canvasSelectors.ts

[fix(ui): canvas staging area works after undo](https://github.com/invoke-ai/InvokeAI/commit/3b1981964082e5cb7104e69c061c0d1ba5c7666e)
[feat(ui): staging styling tweak](https://github.com/invoke-ai/InvokeAI/commit/2f8bf7e9721e4bd2c5b0915a602688b597b34c47)
- Closes #4760
Accept a staging area image or discard the staged images, then undo. They should render as expected after undoing.

fix(ui): canvas undo staging

---

invokeai/app/invocations/facetools.py
pyproject.toml

This PR causes the font "Inter-Regular.ttf", which is needed by the facetools Face Identifier node, to be installed along with other assets in the virtual environment. It also fixes the font path resolution logic in the invocation to work with both package and editable installs.
Closes #4771

Add font Inter-Regular.ttf to installed assets

---

invokeai/app/invocations/facetools.py

Don't check bounds on first detection before chunking, allows larger faces to be detected
Larger faces weren't processed after detection because of a bounds check needed for chunking. Added a bool that is false on first non-chunking pass.
Closes #4777

FaceTools - add checkbounds bool

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts
invokeai/frontend/web/src/features/dnd/util/isValidDrop.ts
invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/GalleryBoard.tsx
invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/NoBoardBoard.tsx
invokeai/frontend/web/src/features/gallery/hooks/useMultiselect.ts
invokeai/frontend/web/src/features/gallery/hooks/useNextPrevImage.ts
invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts
invokeai/frontend/web/src/services/api/endpoints/boards.ts
invokeai/frontend/web/src/services/api/endpoints/images.ts
invokeai/frontend/web/src/services/api/hooks/useBoardTotal.ts

[feat(ui): remove all calls to getBoardImagesTotals/getBoardAssetsTotals](https://github.com/invoke-ai/InvokeAI/commit/428cda6cfda708006658bd95059260344baf1f0b)
This caused a crapload of network requests any time an image was generated.
The counts are necessary to handle the logic for inserting images into existing image list caches; we have to keep track of the counts.
Replace tag invalidation with manual cache updates in all cases, except the initial request (which is necessary to get the initial image counts).
One subtle change is to make the counts an object instead of a number. This is required for `immer` to handle draft states. This should be raised as a bug with RTK Query, as no error is thrown when attempting to update a primitive immer draft.
[fix(ui): fix duplicate image …

fix(ui): boards network chattiness

---

invokeai/app/invocations/upscale.py
invokeai/app/services/config/invokeai_config.py
invokeai/app/services/image_file_storage.py
invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildAdHocUpscaleGraph.ts

Adds tile_size field to the ESRGAN Upscaler node, which sends the tile kwarg to RealESRGANer's constructor, enabling tiled upscaling (default=512)
This adds the tile kwarg to the RealESRGANer constructor used in upscale.py to make an ESRGAN uspcaler, with a default value of 512. (Previous default in earlier invokeai was 400)
With this, it becomes possible to do upscales with ESRGAN beyond sizes that were previously possible given common VRAM constraints.
- Related Issue #4578
I have tested the node, but I was not able to [determine if further changes are necessary]~~rebuild the frontend and test the .ts change in my environment~~. It should be verified and ensured that the linear graph still successfully creates the upscaler. ~~I *think* I added the necessary code to create the ESRGAN …

Add support for tile kwarg for the RealESRGANer upscaler in upscale.py

---

invokeai/app/services/graph.py
invokeai/app/services/session_processor/session_processor_default.py
invokeai/app/services/session_queue/session_queue_base.py
invokeai/app/services/session_queue/session_queue_common.py
invokeai/app/services/session_queue/session_queue_sqlite.py

[feat(nodes): exhaustive graph validation](https://github.com/invoke-ai/InvokeAI/commit/d2a88a47bde7dde297b5fc4f328d28ddfdeea1a4)
Makes graph validation logic more rigorous, validating graphs when they are created as part of a session or batch.
`validate_self()` method added to `Graph` model. It does all the validation that `is_valid()` did, plus a few extras:
- unique `node.id` values across graph
- node ids match their key in `Graph.nodes`
- recursively validate subgraphs
- validate all edges
- validate graph is acyclical
The new method is required because `is_valid()` just returned a boolean. That behaviour is retained, but `validate_self()` now raises appropriate exceptions for validation errors. This are then surfaced to the client.
The function is named `validate_self()` because …

feat/fix: exhaustive graph validation & session processor soft-lock

---

invokeai/frontend/web/src/features/ui/hooks/useCopyImageToClipboard.ts

fix(ui): throw on fetch err when copying image

fix(ui): throw on fetch err when copying image

---

invokeai/backend/install/model_install_backend.py

PR #4725 added the ability to download arbitrary models from a repo_id subfolder. Unfortunately the code included a hard-coded subfolder name that was left over from debugging. This PR fixes the issue.
Nobody previously noticed this bug because the subfolder download was only added recently and its main use case is to support downloading the "qrcode monster" controlnet that was added to the startup models list:
```
sd-1/controlnet/qrcode_monster:
repo_id: monster-labs/control_v1p_sd15_qrcode_monster
subfolder: v2
```
The hardcoded subfolder happened to be "v2", so the use case works.

Remove hardcoded subfolder name from model downloader

---

invokeai/configs/INITIAL_MODELS.yaml
invokeai/frontend/install/model_install.py

This adds a list of T2I adapters to the “starter models” offered by the TUI installer. None of the models is selected by default; this can be done easily if requested. The models offered to the user are:
```
TencentARC/t2iadapter_canny_sd15v2
TencentARC/t2iadapter_sketch_sd15v2
TencentARC/t2iadapter_depth_sd15v2
TencentARC/t2iadapter_zoedepth_sd15v1
TencentARC/t2i-adapter-canny-sdxl-1.0
TencentARC/t2i-adapter-depth-zoe-sdxl-1.0
TencentARC/t2i-adapter-lineart-sdxl-1.0
TencentARC/t2i-adapter-sketch-sdxl-1.0
```
PR #4612 
The revised installer has a new IP-ADAPTERS tab that looks like this:

add a lists of t2i adapters to startup set

---

invokeai/app/services/events.py
invokeai/app/services/session_queue/session_queue_sqlite.py
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketQueueItemStatusChanged.ts
invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts
invokeai/frontend/web/src/features/system/store/systemSlice.ts
invokeai/frontend/web/src/services/api/endpoints/queue.ts
invokeai/frontend/web/src/services/api/index.ts
invokeai/frontend/web/src/services/api/schema.d.ts
invokeai/frontend/web/src/services/events/types.ts

[feat(events): add batch status and queue status to queue item status changed events](https://github.com/invoke-ai/InvokeAI/commit/561695d728f0d7567595d75de912ce584013a29c)
The UI will always re-fetch queue and batch status on receiving this event, so we may as well jsut include that data in the event and save the extra network roundtrips.
@maryhipp There are some changes to the session queue service and socket events here.
[fix(ui): fix canvas soft-lock if canceled before first generation](https://github.com/invoke-ai/InvokeAI/commit/6352cfc2abdbff14bb557764ca466039c49184fe)
The canvas needs to be set to staging mode as soon as a canvas-destined batch is enqueued. If the batch is is fully canceled before an image is generated, we need to remove that batch from the canvas `batchIds` …

fix(ui): fix canvas soft lock

---

invokeai/backend/model_management/model_cache.py
invokeai/backend/model_management/model_load_optimizations.py
tests/backend/model_management/test_model_load_optimization.py

This PR optimizes the time to load models from disk.
In my local testing, SDXL text_encoder_2 models saw the greatest improvement:
- Before change, load time (disk to cpu): 14 secs
- After change, load time (disk to cpu): 4 secs
See the in-code documentation for an explanation of how this speedup is achieved.
This change was previously proposed on the HF transformers repo, but did not get any traction: https://github.com/huggingface/transformers/issues/18505#issue-1330728188
I don't expect any adverse effects, but the new context manager is applied while loading **all** models, so it would make sense to exercise everything.

Improve model load times from disk: skip unnecessary weight init

---

pyproject.toml

@Millu pointed out this safetensors PR a few weeks ago, which claimed to offer a performance benefit: https://github.com/huggingface/safetensors/pull/362 . It was superseded by https://github.com/huggingface/safetensors/pull/363 and included in the latest [safetensors 0.4.0 release](https://github.com/huggingface/safetensors/releases/tag/v0.4.0).
Here are the results from my local performance comparison:
```
Before(0.3.1) / After(0.4.0)
sdxl:main:tokenizer from disk to cpu in                              0.46s / 0.46s
sdxl:main:text_encoder from disk to cpu in                           2.12s / 2.32s
embroidered_style_v1_sdxl.safetensors:sdxl:lora' from disk to cpu in 0.67s / 0.36s
VoxelXL_v1.safetensors:sdxl:lora' from disk to cpu in                1.64s / 0.60s …
```

Bump safetensors to ~=0.4.0

---

invokeai/frontend/web/src/features/controlAdapters/store/controlAdaptersSlice.ts
invokeai/frontend/web/src/features/parameters/store/generationSlice.ts

feat(ui): set w/h to multiple of 64 on add t2i
This is a temp fix to reduce issues with T2I adapter having a different downscaling factor than the UNet. Hopefully we get an upstream fix in diffusers.
https://discord.com/channels/1020123559063990373/1149513647022948483/1159463867508850819

feat(ui): set w/h to multiple of 64 on add t2i

---

invokeai/frontend/install/model_install.py
invokeai/frontend/install/widgets.py

A regression in 3.2.0 causes a seemingly nonsensical multiple choice menu to appear when importing an SD-1 checkpoint model from the autoimport directory. The menu asks the user to identify which type of SD-2 model they are trying to import, which makes no sense.
In fact, the menu is popping up because there are now both "epsilon" and "vprediction" SchedulerPredictionTypes for SD-1 as well as SD-2 models, and the prober can't determine which prediction type to use. This PR does two things:
1) rewords the menu as shown below
2) defaults to the most likely choice -- epsilon for v1 models and vprediction for v2s
Here is the revised multiple-choice menu:
```
Please select the scheduler prediction type of the checkpoint named v1-5-pruned-emaonly.safetensors:
[1] "epsilon" - most v1.5 models …
```

Fix gratuitous, parasitic, endlessly repeated, pointless menu in version 3.2.0

---

invokeai/app/services/config/config_default.py
invokeai/backend/install/invokeai_configure.py

The `invokeai-configure` TUI's slider for the RAM cache was not picking up the current settings in `invokeai.yaml`, leading users to think their change hadn't taken effect. This is fixed in this PR.
First described here:
https://discord.com/channels/1020123559063990373/1161919551441735711/1162058518417907743

Enable the ram cache slider in invokeai-configure

---

invokeai/backend/model_management/memory_snapshot.py
tests/backend/model_management/test_libc_util.py

[fix(backend): handle systems with glibc < 2.33](https://github.com/invoke-ai/InvokeAI/commit/f0ee3150c504d1e45601455643db1ef1d8ca2fa0)
`mallinfo2` is not available on `glibc` < 2.33.
On these systems, we successfully load the library but get an `AttributeError` on attempting to access `mallinfo2`.
I'm not sure if the old `mallinfo` will work, and not sure how to install it safely to test, so for now we just handle the `AttributeError`.
This means the enhanced memory snapshot logic will be skipped for these systems, which isn't a big deal.
- Closes #4878
@RyanJDick Requesting your review for this.
@RaphaelDreams , ideally you could test this PR on your affected system to confirm it resolves the issue. From my read of the code, it will, but I'm not sure how to test the …

fix(backend): handle systems with `glibc` < 2.33

---

invokeai/app/invocations/metadata.py
invokeai/frontend/web/src/features/nodes/util/graphBuilders/addT2IAdapterToLinearGraph.ts
invokeai/frontend/web/src/services/api/schema.d.ts

[fix(nodes,ui): optional metadata](https://github.com/invoke-ai/InvokeAI/commit/78b8cfede3e1d7bb21c46734c3a647ceef095202)
- Make all metadata items optional. This will reduce errors related to metadata not being provided when we update the backend but old queue items still exist
- Fix a bug in t2i adapter metadata handling where it checked for ip adapter metadata instaed of t2i adapter metadata
- Fix some metadata fields that were not using `InputField`

fix(nodes,ui): optional metadata

---

invokeai/app/services/board_image_records/board_image_records_sqlite.py
invokeai/app/services/board_records/board_records_sqlite.py
invokeai/app/services/image_records/image_records_sqlite.py
invokeai/app/services/item_storage/item_storage_sqlite.py
invokeai/app/services/session_queue/session_queue_sqlite.py
invokeai/app/services/shared/sqlite.py

When canceling by batch ids or canceling the whole queue, we tried to lock the db mutex within an existing lock, which of course locks the app forever. Use `RLock` instead to allow this pattern.
https://discord.com/channels/1020123559063990373/1149513625321603162/1163229923255791749

fix(db): use RLock instead of Lock

---

invokeai/app/api/sockets.py

Fix for breaking change in `python-socketio` 5.10.0 in which `enter_room` and `leave_room` were made coroutines.
- Closes #4899

fix(api): fix socketio breaking change

---

invokeai/frontend/web/src/common/hooks/useImage.ts
invokeai/frontend/web/src/common/hooks/useImageUrlToBlob.ts
invokeai/frontend/web/src/features/system/util/copyBlobToClipboard.ts
invokeai/frontend/web/src/features/ui/hooks/useCopyImageToClipboard.ts

[fix(ui): copy image via img onload to blob](https://github.com/invoke-ai/InvokeAI/commit/b1da70c188e816078636d20d799f56805da393df)
There's a bug in chrome that screws with headers on fetch requests and 307 responses. This causes images to fail to copy in the commercial environment.
This change attempts to get around this by copying images in a different way (similar to how the canvas works). When the user requests a copy we:
- create an `<img />` element
- set `crossOrigin` if needed
- add an onload handler:
- create a canvas element
- draw image onto it
- export canvas to blob
This is wrapped in a promise which resolves to the blob, which can then be copied to clipboard.
---
A customized version of Konva's `useImage` hook is also included, which returns the image blob in addition to the …

fix(ui): copy image via img onload to blob

---

invokeai/app/api/routers/session_queue.py
invokeai/app/services/session_queue/session_queue_base.py
invokeai/app/services/session_queue/session_queue_common.py
invokeai/app/services/session_queue/session_queue_sqlite.py
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/anyEnqueued.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlNetImageProcessed.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/upscaleRequested.ts
invokeai/frontend/web/src/features/queue/hooks/useIsQueueMutationInProgress.ts
invokeai/frontend/web/src/services/api/endpoints/queue.ts
invokeai/frontend/web/src/services/api/schema.d.ts
invokeai/frontend/web/src/services/api/types.ts

[feat: remove enqueue_graph routes/methods](https://github.com/invoke-ai/InvokeAI/commit/2201b4a0553f9361d18682dd4fe86b78b6cc08e6)
This is totally extraneous - it's almost identical to `enqueue_batch`.
- Related Issue: split out from #4686, where it has no business being
This route was used for controlnet image processing and ad-hoc upscaling:
- Upscale an image using the ad-hoc upscaling button, ensuring it upscales
- Set a control image, ensuring it auto-processes

feat: remove `enqueue_graph` routes/methods

---

invokeai/frontend/web/src/features/controlAdapters/store/constants.ts

fix(ui): use pidi processor for sketch control adapters

fix(ui): use pidi processor for sketch

---

invokeai/frontend/web/src/features/nodes/util/graphBuilders/addControlNetToLinearGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/addIPAdapterToLinearGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/addT2IAdapterToLinearGraph.ts

[fix(ui): fix multiple control adapters on canvas](https://github.com/invoke-ai/InvokeAI/commit/2e160c8c101a34a8d0b052a9f965fd1853158ea9)
We were making an edges for each adapter where we should isntead have one from the adapter's collect node into the denoising node
- Closes #4939
Try multiple t2i, controlnet or ip adapters on canvas outpainting.

fix(ui): fix multiple control adapters on canvas

---

invokeai/backend/model_management/model_manager.py

Prevent the app from dying on invalid models.
- [X ] Bug Fix
- [ X] No, because: Just discovered it, seemed like a simple fix.
- [X ] Yes
Fix multiple potential issues when scanning models on first load, specifically with an instructPix2Pix model and some non-safetensor files.
- Closes #
Nope.

Catch generic model errors

---

invokeai/app/api/routers/images.py
invokeai/app/services/image_records/image_records_base.py
invokeai/app/services/image_records/image_records_sqlite.py
invokeai/app/services/images/images_base.py
invokeai/app/services/images/images_default.py
invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsClearIntermediates.tsx
invokeai/frontend/web/src/services/api/endpoints/images.ts
invokeai/frontend/web/src/services/api/schema.d.ts

[feat: dedicated route to get intermediates count](https://github.com/invoke-ai/InvokeAI/commit/d4f6b093951cecba833b8282466d77830091c718)
This fixes a weird issue where the list images method needed to handle `None` for its `limit` and `offset` arguments, in order to get a count of all intermediates.
- do a canvas generation or something to generate some intermediates
- check settings modal - intermediates count should update whenever you close/open it
- clear intermediates should still work
- Related Issue: split out from #4686, where it has no business being

feat: dedicated route to get intermediates count

---

invokeai/frontend/web/src/features/canvas/hooks/useColorUnderCursor.ts

[fix(ui): fix canvas color picker when value is zero](https://github.com/invoke-ai/InvokeAI/commit/678333c9b871af67675f410fadbbed47de440f72)
good ol' zero is false-y
- Closes #4955

fix(ui): fix canvas color picker when value is zero

---

pyproject.toml

fix(nodes): explicitly include custom nodes files
setuptools ignores markdown files - explicitly include all files in `"invokeai.app.invocations"` to ensure all custom node files are included

fix(nodes): explicitly include custom nodes files

---

invokeai/app/invocations/metadata.py
invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildAdHocUpscaleGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/metadata.ts
invokeai/frontend/web/src/services/api/schema.d.ts

[fix(nodes): fix missing generation modes](https://github.com/invoke-ai/InvokeAI/commit/8615d53e654ecaf20960c9110b47a098756b5962)
Lax typing on the metadata util functions allowed a typing issue to slip through. Fixed the lax typing, updated core metadata node.
- Closes #4959 (thanks @coder543)

fix(nodes): fix missing generation modes

---

invokeai/backend/install/model_install_backend.py
invokeai/backend/model_management/models/controlnet.py
invokeai/configs/controlnet/cldm_v15.yaml
invokeai/configs/controlnet/cldm_v21.yaml

This PR allows users to install checkpoint (safetensors) versions of controlnet models. The models will be converted into diffusers format and cached on the fly.
This only works for sd-1 and sd-2 controlnets, as I was unable to find controlnet sdxl checkpoint models or their corresponding .yaml config files.
After updating, please run `invokeai-configure --yes --default-only` to install the missing config files. Users should be instructed to select option [7] from the launcher "Re-run the configure script to fix a broken install or to complete a major upgrade".
User request at https://discord.com/channels/1020123559063990373/1160318627631870092/1160318627631870092
- Related Issue #4743
- Closes #
See above for instructions on updating the config files after checking out the PR.

Support conversion of controlnets from safetensors to diffusers format

---

invokeai/app/services/model_manager/__init__.py
invokeai/backend/training/textual_inversion_training.py

Fix textual inversion training script crash caused by reorg of services.
- closes #4975
- Closes #

Make textual inversion script work again

---

invokeai/frontend/merge/merge_diffusers.py

The introduction of `BaseModelType.Any` broke the code in the merge script which relied on sd-1 coming first in the BaseModelType enum. This assumption has been removed and the code should be less brittle now.
- Closes #

Make the merge script work again

---

invokeai/app/invocations/ip_adapter.py

- [ x ] Feature
- [ x ] Yes
- [ x ] No
This enables support for negative IP adapters but allowing for a value of -1 or more. This limit may not be needed at all, but for the time being (unless proven otherwise) I think -1 will likely solve for most use-cases (if any).

Add negative IP Adapter support

---

invokeai/frontend/web/src/features/dynamicPrompts/components/ParamDynamicPromptsCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/Advanced/ParamAdvancedCollapse.tsx
invokeai/frontend/web/src/features/parameters/components/Parameters/HighResFix/ParamHrfCollapse.tsx

fix(ui): show collapse labels only if not default value
- Dynamic Prompts only displays if more than one prompt is parsed
- HRF only displays if enabled
- Noise device only shows if set to GPU
Closes #4974

fix(ui): show collapse labels only if not default value

---

invokeai/app/invocations/compel.py
invokeai/app/invocations/latent.py
invokeai/backend/model_management/lora.py
invokeai/backend/model_management/models/lora.py
tests/backend/model_management/test_lora.py

Improve LoRA patching speed with the following changes:
- Calculate LoRA layer weights on the same device as the target model. Prior to this change, weights were always calculated on the CPU. If the target model is on the GPU, this significantly improves performance.
- Move models to their target devices _before_ applying LoRA patches.
- Improve the ordering of Tensor copy / cast operations.
Tests:
Please hammer away with a variety of LoRAs in case there is some edge case that I've missed.

Improve LoRA patching speed

---

invokeai/app/services/config/config_default.py
invokeai/backend/model_management/memory_snapshot.py
invokeai/backend/model_management/model_cache.py
invokeai/backend/model_management/model_manager.py
tests/backend/model_management/test_memory_snapshot.py

Memory usage logging is helpful for diagnosing model cache / memory issues, but comes at a speed cost. This PR adds a `log_memory_usage` flag to the app config that controls this feature (off by default).
First-run text-to-image speed with (`log_memory_usage=True`):
- SD-1: 14.2s
- SDXL: 32.7s
First-run text-to-image speed with (`log_memory_usage=False`):
- SD-1: 10.2s
- SDXL: 25.7s
Tested locally with `log_memory_usage` enabled/disabled.

Add `log_memory_usage` flag to `ModelCache`

---

invokeai/backend/model_management/model_load_optimizations.py
tests/backend/model_management/test_model_load_optimization.py

This PR monkey patches `torch.nn.Embedding.reset_parameters(...)` to skip this operations when we are loading a text encoder (and are going to overwrite all of the weights anyways).
In my local testing, I saw the following speed improvements:
```txt
SD1 text_encoder:    before=2.0s, after=0.3s, change=-1.7s
SDXL text_encoder_1: before=2.1s, after=0.4s, change=-1.7s
SDXL text_encoder_2: before=3.8s, after=1.1s, change=-2.7s
```
Did some profiling to measure the speed improvement (see Description).
I also manually confirmed that there was no diff in the generated images.

Improve text encoder model loading speed by skipping parameter init

---

invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/features/lora/components/ParamLoraSelect.tsx
invokeai/frontend/web/src/features/sdxl/components/ParamSDXLRefinerCollapse.tsx

fix(ui): hide refiner collapse if refiner not installed

fix(ui): hide refiner collapse if refiner not installed

---

invokeai/backend/model_management/model_cache.py

This PR improves model loading speed by reducing the number of extraneous calls to `gc.collect(...)` in model_cache.py.
For context, here is some important background about garbage collection in python:
- In python, most objects are deleted by the interpreter as soon as their reference count hits 0. Contrary to what some people assume, the `gc` module is _only_ responsible for handling reference cycles (i.e. unreachable objects with reference cycles that prevent their reference count from reaching 0).
- Calling `gc.collect()` is expensive _even if there is no garbage to collect_. The time taken increases with the number of objects. In my rough local tests, every call in Invoke takes ~ 0.2-0.4 secs.
Prior to this change, we were making many costly calls to gc.collect, most of which weren't …

Speed optimization: reduce frequency of `gc.collect(...)` calls in model cache

---

invokeai/frontend/merge/merge_diffusers.py

The model merging command-line script made the assumption that the first enum in `ModelBaseType` was `sd-1`. When the `ModelBaseType.Any` was introduced, this assumption was broken, leading to "model not found" errors when running the script. This PR fixes the issue.
- Closes #

Fix model-not-found error in merge TUI

---

invokeai/frontend/install/invokeai_update.py

Fix updater option list numbering in invokeai_update.py so that they don't go 1, 2, 2, 3.  The options themselves work fine.

Fix updater option list numbering

---

invokeai/frontend/web/yarn.lock

[chore(ui): manually update vite to fix security issue in hoisted dep](https://github.com/invoke-ai/InvokeAI/commit/91eeab43a9001ab0abc059832118ef2a1d93d111)
`postcss` is a hoisted dependency of `vite`.
Missed that `postcss` was required by both `madge` and `vite` in #5061. Only did `madge` in that PR.

chore(ui): manually update vite to fix security issue in hoisted dep

---

invokeai/backend/install/model_install_backend.py
invokeai/backend/model_management/model_probe.py
invokeai/backend/model_management/models/lora.py

This PR adds support for downloading diffusers-format LoRAs that use the LCM scheduler. Tested on `latent-consistency/lcm-lora-sdxl`.
See discord thread https://discord.com/channels/1020123559063990373/1049495067846524939/1172250151742607480
- Closes #5059
Try installing `latent-consistency/lcm-lora-sdxl` or another HuggingFace diffusers-format LoRA model.

Add support for downloading and installing LCM lora diffusers models

---

invokeai/backend/model_management/lora.py
pyproject.toml

This PR updates Transformers to the most recent version and fixes the value `pad_to_multiple_of` for `text_encoder.resize_token_embeddings` which was introduced with https://github.com/huggingface/transformers/pull/25088 in Transformers 4.32.0.
According to the [Nvidia Documentation](https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc), `Performance is better when equivalent matrix dimensions M, N, and K are aligned to multiples of 8 bytes (or 64 bytes on A100) for FP16`
This fixes the following error that was popping up before every invocation starting with Transformers 4.32.0
`You are resizing the embedding layer without providing a pad_to_multiple_of parameter. This means that the new embedding dimension will be None. This …

Update Transformers to 4.35 and fix pad_to_multiple_of

---

invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataActions.tsx
invokeai/frontend/web/src/features/parameters/hooks/useRecallParameters.ts

#4796      
I don't believe there is any documentation explicitly referencing the recall parameters.
This code changes allows users to recall the VAE model as a Recall Parameter. The VAE model is now part of the "recall all parameters" setting. There is room to add the VAE Precision to the metadata and also making that a recall parameter..
- Related Issue #4796 
- Closes #4796 
1. Generate an image using a VAE other than default.
2. Select that generated image, change the VAE model, and select "Use All"
3. VAE model should change in the UI.
4. VAE model is available in "recall parameters" of the metadata section.
https://github.com/invoke-ai/InvokeAI/assets/22108632/04a52722-6faf-4ab4-b414-81806fe4aa54

Feat (ui): Add VAE Model to Recall Parameters

---

invokeai/backend/util/hotfixes.py

[fix(backend): fix controlnet zip len](https://github.com/invoke-ai/InvokeAI/commit/080608c05e8ec2ad78935fb0ae9d580efa4409a4)
Do not use `strict=True` when scaling controlnet conditioning.
When using `guess_mode` (e.g. `more_control` or `more_prompt`), `down_block_res_samples` and `scales` are zipped.
These two objects are of different lengths, so using zip's strict mode raises an error.
In testing, `len(scales) === len(down_block_res_samples) + 1`.
It appears this behaviour is intentional, as the final "extra" item in `scales` is used immediately afterwards.
- Related https://discord.com/channels/1020123559063990373/1049495067846524939/1173464143123197993
- Introduced by #5070 
Use controlnet with the control mode set to `more_control` or `more_prompt`. Should work.

fix(backend): fix controlnet zip len

---

installer/lib/installer.py

We use Pytorch ~2.1.0 as a dependency for InvokeAI, but the installer still installs 2.0.1 first until Invoke AIs dependencies kick in which causes it to get deleted anyway and replaced with 2.1.0. This is unnecessary and probably not wanted.
Fixed the dependencies for the installation script to install Pytorch ~2.1.0 to begin with.
P.s. Is there any reason why "torchmetrics==0.11.4" is pinned? What is the reason for that? Does that change with Pytorch 2.1? It seems to work since we use it already. It would be nice to know the reason.
Greetings
- Closes #

Update Pytorch to ~2.1.0 in the installer script

---

.github/workflows/style-checks.yml

After the switch to the "ruff" linter, I noticed that the stylecheck workflow is still described as "black" in the action logs. This small PR should fix the issue.

Change stylecheck name from "black" to "ruff"

---

invokeai/app/invocations/image.py
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildAdHocUpscaleGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/constants.ts

Resolves two bugs introduced in #5106:
1. Linear UI images sometimes didn't make it to the gallery.
This was a race condition. The VAE decode nodes were handled by the socketInvocationComplete listener. At that moment, the image was marked as intermediate. Immediately after this node was handled, a LinearUIOutputInvocation, introduced in #5106, was handled by socketInvocationComplete. This node internally sets changed the image to not intermediate.
During the handling of that socketInvocationComplete, RTK Query would sometimes use its cache instead of retrieving the image DTO again. The result is that the UI never got the message that the image was not intermediate, so it wasn't added to the gallery.
This is resolved by refactoring the socketInvocationComplete listener. We now skip the …

fix(nodes,ui): fix missed/canvas temp images in gallery

---

invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearImageToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graphBuilders/buildLinearSDXLImageToImageGraph.ts

Caused by a typo. Whoops!
Fixes 
- Closes https://discord.com/channels/1020123559063990373/1049495067846524939/1174867331478982656
img2img should work

fix(ui): metadata error on img2img

---

docs/contributing/INVOCATIONS.md

The example custom node code in the docs uses old (?) import paths for invokeai modules. These paths cause the module to fail to load. This PR updates them.

Docs: update imports for example custom node code

---

invokeai/app/invocations/upscale.py
invokeai/backend/image_util/esrgan.py
invokeai/backend/image_util/realesrgan/LICENSE
invokeai/backend/image_util/realesrgan/realesrgan.py
pyproject.toml

Removes dependency on https://github.com/xinntao/Real-ESRGAN/
---
We used the `RealESRGANer` utility class from the repo. It handled model loading and tiled upscaling logic.
Unfortunately, it hasn't been updated in over a year, had no types, and annoyingly printed to console.
I've adapted the class, cleaning it up a bit and removing the bits that are not relevant for us.
Upscaling functionality is identical.
- Related Issue #5167
Try upscaling an image.
I've tested on CUDA and MPS.

feat(nodes): remove dependency on realesrgan

---

invokeai/backend/model_management/model_probe.py

Without specifying map_location="cpu" in ModelProbe, Invoke attempts to use non-existent CUDA to deserialize embeddings on macOS, resulting in a warning / failure to load.
Noticed in a fresh install of 3.4.0post2 on macOS that InvokeAI logs a warning about attempting to deserialize embeddings on CUDA, which is not available.  This change eliminates that warning.
It is not clear to me if this needs to be conditional on the availability of CUDA hardware.  I noticed that other places in the code are hardcoded to use map_location="cpu", so I followed that lead.
I believe this is the same issue as #4265 
- Related Issue #4265
- Closes #4265

Fix attempt to deserialize on CUDA on Mac

---

invokeai/app/api_app.py
invokeai/app/invocations/__init__.py
invokeai/app/services/config/config_base.py
invokeai/app/services/config/config_default.py
invokeai/app/services/model_records/model_records_sql.py
pyproject.toml

This PR does two things:
1) Fixes various type-checking errors in invokeai/app/services/config/config_base.py and config_default.py.
2) Adds back the ability to get `invokeai-web` to print out the current version number with `--version` on the command line.
- Closes #
Just check that the frontend runs and that changing configuration variables in the `invokeai.yaml` file and/or command line are having the expected effect.

Fix type mismatches in invokeai.app.services.config

---

pyproject.toml

A recent merge introduced a new dependency on the `cv2.typing` module. This is not present in older versions of the `opencv-python` package. This pins `opencv-python` to a recent version that contains the module in question.
After pulling, run `pip install -e .` to update to a compatible version of `cv2`.

pin opencv-python to get required cv2.typing module

---

invokeai/backend/ip_adapter/ip_adapter.py
tests/backend/ip_adapter/test_ip_adapter.py

The recently-released [ip-adapter-full-face_sd15](https://huggingface.co/InvokeAI/ip-adapter-full-face_sd15) model uses a new IP-Adapter architecture (`IPAdapterFull`). This new architecture was added upstream in the official IP-Adapter repo here: https://github.com/tencent-ailab/IP-Adapter/pull/139
This PR adds support for `IPAdapterFull` models.
I tested the following:
- Installed the model via the UI.
- Generated with the following IP-Adapters:
- IPAdapter (SD1.5)
- IPAdapterPlus (SD1.5)
- IPAdapterPlusXL (SDXL)
- IPAdapterFul (SD1.5)
I added a unit test for IPAdapterFull model loading. Run with `pytest tests/ -m slow`.

Add support for `IPAdapterFull` models

---

invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/features/nodes/types/error.ts
invokeai/frontend/web/src/features/nodes/util/schema/buildFieldInputTemplate.ts
invokeai/frontend/web/src/features/nodes/util/schema/parseFieldType.ts
invokeai/frontend/web/src/features/nodes/util/schema/parseSchema.ts

Closes #5121
- Parse `anyOf` for enums (present when they are optional)
- Consolidate `FieldTypeParseError` and `UnsupportedFieldTypeError` into `FieldParseError` (there was no difference in handling and it simplifies things a bit)
- Closes #5121

fix(ui): fix enum parsing for optional enums

---

invokeai/app/invocations/latent.py
invokeai/app/invocations/tiles.py
invokeai/backend/tiles/tiles.py
invokeai/backend/tiles/utils.py
tests/backend/tiles/test_tiles.py
tests/backend/tiles/test_utils.py

Big thanks to @JPPhoto, @dwringer, @skunkworxdark and @dunkeroni for their contributions in this discord discussion: https://discord.com/channels/1020123559063990373/1161727357309165608.
The implementation in this PR is based closely on their work.
Check out that discussion for a more-advanced, continually-evolving implementation of tiled upscaling.
This PR adds several new invocations to enable image tiling workflows:
- `CalculateImageTilesInvocation`
- `TileToPropertiesInvocation`
- `PairTileImageInvocation`
- `MergeTilesToImageInvocation`
Here is a sample Tiled Upscaling workflow to illustrate how these tiling invocations are intended to be used: [tiled_upscaling.json](https://github.com/invoke-ai/InvokeAI/files/13420162/tiled_upscaling.json)
During development of this feature there …

Add image tiling nodes to enable Tiled Upscaling

---

invokeai/backend/model_management/lora.py
invokeai/backend/model_management/model_probe.py

This adds support for at least some of the SDXL embeddings currently available on Civitai. The embeddings I have tested include:
- https://civitai.com/models/154898/marblingtixl?modelVersionId=173668
- https://civitai.com/models/148131?modelVersionId=167640
- https://civitai.com/models/123485/hannah-ferguson-or-sdxl-or-comfyui-only-or-embedding?modelVersionId=134674 (said to be "comfyui only")
- https://civitai.com/models/185938/kendall-jenner-sdxl-embedding?modelVersionId=208785
I am _not entirely sure_ that I have implemented support in the most elegant way. The issue is that these embeddings have two weight tensors, `clip_g` and `clip_l`, which correspond to `text_encoder` and `text_encoder_2` in the main model. When the patcher calls the ModelPatcher's `apply_ti()` method, I simply …

Add support for SDXL textual inversion/embeddings

---

pyproject.toml

Set minimum `numpy` version in response to this bug: https://discord.com/channels/1020123559063990373/1049495067846524939/1180152828027748402

Set minimum numpy version

---

invokeai/app/api/routers/model_records.py
invokeai/app/services/latents_storage/latents_storage_disk.py
invokeai/backend/util/logging.py
tests/backend/util/test_logging.py

While writing regression tests for the queued downloader I discovered that when using `InvokeAILogger.get_logger()` to fetch a previously-created logger it resets that logger's log level to the default specified in the global config. In other words, this didn't work as expected:
```
import logging
from invokeai.backend.util.logging import InvokeAILogger
logger1 = InvokeAILogger.get_logger('TestLogger')
logger1.setLevel(logging.DEBUG)
logger2 = InvokeAILogger.get_logger('TestLogger')
assert logger1.level == logging.DEBUG
assert logger2.level == logging.DEBUG
```
This PR fixes the problem and adds a corresponding pytest.
- Closes #

Ensure that fetching a logger doesn't reset its loglevel to default

---

invokeai/configs/INITIAL_MODELS.yaml

The HuggingFace `XpucT/deliberate` model page has been reorganized and is no longer available as a diffusers model. This fix will download the current .safetensors version. Tested and works.
First mentioned on discord at: https://discord.com/channels/1020123559063990373/1181369595974647828/1181650223471267870
If you wish to test installation, please use `invokeai-model-install` and select the `Deliberate_v5` checkbox.

Fix link to xpuct/deliberate in starter models

---

docker/Dockerfile

CONTAINER_UID is used for the user ID within the container, however I noticed the UID was hard coded to 1000 in the Dockerfile chown -R command.
This leaves the default UID/GID as 1000, but allows it to be overrriden by setting CONTAINER_UID.
- Closes #

Fix: Respect CONTAINER_UID in Dockerfile chown

---

docs/features/CONFIGURATION.md
invokeai/app/api_app.py
invokeai/app/services/config/config_default.py

- Feature
- not yet
- Yes
The web server will use HTTPS when given a SSL certificate file, added to the Web section of the configuration file.
- Closes #3970

feat: serve HTTPS when configured with `ssl_certfile`

---

invokeai/app/services/model_install/model_install_default.py
invokeai/app/services/model_records/model_records_sql.py
invokeai/backend/model_manager/migrate_to_db.py

1. The new model manager sqlite3-based configuration record storage system is automatically populated with probed values from existing models found in the models path when `invokeai-web` starts up for the first time. However, the user's customization of these models in `invokeai.yaml`, including such things as the prediction type and model description, are not automatically copied over. This PR enhances the `invokeai-migrate-models-to-db` script so that any customized configuration data from `invokeai.yaml` replaces the original probed values. This script only needs to be run once, but it does not hurt to run it additional times. In the near future, I'm going to register this module with psychedelicious's sqlite migration system so that the update happens automatically during database …

[Feature] Allow the model record migrate script to update existing model records

---

invokeai/app/invocations/baseinvocation.py
invokeai/app/invocations/tiles.py
invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/InvocationNodeClassificationIcon.tsx
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/InvocationNodeHeader.tsx
invokeai/frontend/web/src/features/nodes/hooks/useNodeClassification.ts
invokeai/frontend/web/src/features/nodes/types/common.ts
invokeai/frontend/web/src/features/nodes/types/invocation.ts
invokeai/frontend/web/src/features/nodes/util/schema/parseSchema.ts
invokeai/frontend/web/src/services/api/schema.d.ts

[feat(nodes): add invocation classifications](https://github.com/invoke-ai/InvokeAI/commit/994d3ad94d94981b6eb2284b0266100ff7a680a6)
Invocations now have a classification:
- Stable: LTS
- Beta: LTS planned, API may change
- Prototype: No LTS planned, API may change, may be removed entirely
The `@invocation` decorator has a new arg `classification`, and an enum `Classification` is added to `baseinvocation.py`.
The default is Stable; this is a non-breaking change.
The classification is presented in the node header as a hammer icon (Beta) or flask icon (prototype).
The icon has a tooltip briefly describing the classification.
---
**I've not marked any nodes as beta or protoype yet.** Please let me know which nodes should be flagged as what. …

feat(nodes): add invocation classifications

---

invokeai/backend/tiles/tiles.py
tests/backend/tiles/test_tiles.py

In the tiled upscaling graph - In `calc_tiles_min_overlap` when the tile size is bigger than the image size it now correctly adjusts the tile size to fit. 
- Closes #

[BUG]: Tiled upscaling graph - fix for calc_tiles_min_overlap when tile size is bigger than image size

---

invokeai/app/services/model_install/model_install_base.py
pyproject.toml

This fixes a problem with `Annotated` which prevented us from using pydantic's `Field` to specify a discriminator for a union. We had to use FastAPI's `Body` as a workaround.

chore/fix: bump fastapi to 0.105.0

---

invokeai/backend/stable_diffusion/diffusers_pipeline.py
pyproject.toml

- [ X ] Optimization
- [ X ] No, because: dependency bump
- [ x ] No
Updating diffusers to .24 - fixes a few issues. Needs to be tested to ensure things like our IP Adapter implementation don't break

Bump Diffusers Dependency

---

installer/lib/installer.py
pyproject.toml

Update Pytorch to the most recent version 2.1.1 and Xformers to 0.0.23. Both versions are compatible with each other.
Update the required Torchvision version since Pytorch 2.1.1 requires Torchvision>=0.16.1
Tested without any errors or regressions.
- Closes #

Update torch to 2.1.1 and xformers to 0.0.23

---

.github/pull_request_template.md

This adds a Merge Plan section to the PR template. A merge plan describes any special handling needed for a PR after it is approved by a maintainer.
This PR can be merged when approved.

add merge plan to PR template

---

invokeai/app/services/workflow_records/workflow_records_common.py

This [`WorkflowWithoutID`] model was a bit too strict, and raised validation errors when workflows we expect to *not* have an ID (eg, an embedded workflow) have one.
Now it strips unknown attributes, allowing those workflows to load.
- Related Issue https://discord.com/channels/1020123559063990373/1049495067846524939/1184533384203083866
@JPPhoto this should fix the other image (and images like it).
This can be merged once @JPPhoto confirms it resolves the issue.

fix(nodes): fix embedded workflows with IDs

---

invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasImageToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasInpaintGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasOutpaintGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasSDXLImageToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasSDXLInpaintGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasSDXLOutpaintGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasSDXLTextToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasTextToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildLinearImageToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildLinearSDXLImageToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildLinearSDXLTextToImageGraph.ts
invokeai/frontend/web/src/features/nodes/util/graph/buildLinearTextToImageGraph.ts

The VAE decode on linear graphs was getting cached. This caused some unexpected behaviour around image outputs.
For example, say you ran the exact same graph twice. The first time, you get an image written to disk and added to gallery. The second time, the VAE decode is cached and no image file is created. But, the UI still gets the graph complete event and selects the first image in the gallery. The second run does not add an image to the gallery.
There are probbably edge cases related to this - the UI does not expect this to happen. I'm not sure how to handle it any better in the UI.
The solution is to not cache VAE decode on the linear graphs, ever. If you run a graph twice in linear, you expect two images.
This simple change disables the node cache for terminal VAE decode nodes in all …

fix(ui): do not cache VAE decode on linear

---

invokeai/app/api/routers/model_records.py

As discussed with @psychedelicious , this PR changes the swagger label on the model manager V2 routes to `model_manager_v2_unstable` in order to warn community members that the API is liable to change.
- Closes #

Tag model manager v2 api as unstable

---

docker/Dockerfile

3.5.0 rc1 Docker builds are broken due to the swap from npm to pnpm.
I think this should fix it.
- Related Issue #5253 #5258
- Closes #
Run docker build and tests as normal.
- Can be merged when approved and docker builds pass.

fix(pnpm): replace npm with pnpm in dockerfile

---

invokeai/backend/util/devices.py

As of pytorch 2.1.0, float16 works with our MPS fixes on Sonoma, so the check is no longer needed.
The original MacOS Sonoma check was implemented when we had reports of our float16 patches not working on beta versions of Sonoma. We implemented this so that it would fall back to float32 for those affected, rather than crashing, with the goal of eventually figuring out why things weren't working and fixing what was required, once Sonoma was fully released. 
Instead, pytorch 2.1.0 fixed the issues, so now that InvokeAI uses that version, we can remove the check.
- Closes #
To test the behavior, I printed the output of `choose_precision(choose_torch_device())`.
This PR can be merged when approved - as we're now using pytorch 2.1.0 in release/main, we're good to go.

remove MacOS Sonoma check in devices.py

---

invokeai/app/api/dependencies.py
invokeai/app/services/invocation_services.py
tests/aa_nodes/test_graph_execution_state.py
tests/aa_nodes/test_invoker.py

The graph library occasionally causes issues when the default graph changes substantially between versions and pydantic validation fails. See #5289 for an example.
We are not currently using the graph library, so we can disable it until we are ready to use it. It's possible that the workflow library will supersede it anyways.
- Closes #5289
This should be a totally transparent change. Starting the app successfully is enough to test.
This can be merged when approved.
nope

feat(backend): disable graph library

---

docker/.env.sample
docker/README.md
docker/run.sh

- corrects usage of `GPU_DRIVER` - `nvidia` replaced `cuda` in a prior PR - fixes #5336 
- sets up a default  "happy path" for docker on linux + nvidia and document
- simplifies docker quickstart / README

easy docker quickstart on nvidia + fix variable value

---

installer/lib/installer.py
pyproject.toml

This commit updates Torch to the last stable release of 2.1.2 and xformers to its compatible version 0.0.23post1. No regressions accrued so far.
This is most likely the last stable release before PyTorch 2.2 is released. Brace yourself for some discord issues about torch running on CPU only. This happens, when people use the updater and pip is updating torch using the non-cuda version. I don't know if this has since changed (I think I saw a commit that changed something about that). I always use the installer to update, which ensures that the correct PyTorch version is chosen.
Regardless, this should be safe to be merged.
Merry Christmas, dear developers! I hope you have a wonderful time with your friends and family, and thank you for all your making this wonderful piece of software <3 …

Update torch xformers

---

invokeai/backend/model_management/lora.py

if there are two multi vector TI in a prompt eg `<ti-1> <ti-2>` with ti-1 has vector size 16 and ti-2 has vector size 8 then the second one uses the first ti_embedding.shape[0] and you get errors like eg "<ti-2-!pad-8> is not found" because ti-2 only has vector size 8 but the code is taking the wrong ti_embedding.shape[0]
- Closes #

fix bug when there are two multi vector TI in a prompt

---

invokeai/frontend/web/src/features/ui/hooks/usePanel.ts

A bug that caused panels to be collapsed on a fresh indexedDb in was fixed in dd32c632cdf5006796614386f1f6094bdfb9328a, but this re-introduced a different bug that caused the panels to expand on window resize, if they were already collapsed.
Revert the previous change and instead add one imperative resize outside the observer, so that on startup, we set both panels to their minimum sizes.
- Collapse both panels
- Resize the window - they should not expand
- Reset web UI - panels should be expanded after refresh

fix(ui): fix panel resize bug

---

invokeai/backend/util/devices.py

On CUDA systems, `torch.bfloat16` is supposed to be ~25% faster than `torch.float16` according to this article: https://pytorch.org/blog/accelerating-generative-ai-3/. This small PR substitutes bfloat16 for float16 when half-precision is requested on a cuda system.
Unfortunately I don't see any change in speed in my benchmarking. The article says that the speedup is GPU dependent, so perhaps others will have more luck (I'm using an RTX 4070).
- Closes #
Can merge when tested and approved. Please try on different GPUs and OSs. Should make no difference on Macs.

[Optimization] Use torch.bfloat16 on cuda systems

---

invokeai/frontend/web/src/features/ui/components/FloatingGalleryButton.tsx
invokeai/frontend/web/src/features/ui/components/FloatingParametersPanelButtons.tsx

Slightly adjusted the position of the floating bars so begin right after the drag lines start/end and the drag line also becomes accessible on the gallery side now in the same areas as the button.

ui: slightly reposition floating bars.

---

invokeai/backend/model_management/lora.py

This change saves time when applying TI embeddings by skipping unnecessary weight initialization steps. (See inline source comment for more details.)
In my local testing with SDXL, this reduced `sdxl_compel_prompt` from ~8s to ~0.8s.
I confirmed that there was no change to the images produced with a fixed seed after the fix.

Improve speed of applying TI embeddings

---

invokeai/frontend/web/src/features/gallery/components/ImageGrid/ImageGridItemContainer.tsx
invokeai/frontend/web/src/features/gallery/components/ImageGrid/ImageGridListContainer.tsx
invokeai/frontend/web/src/features/gallery/hooks/useGalleryNavigation.ts

- Use the virtuoso grid item container and list containers to calculate imagesPerRow, skipping manual compensation for padding of images
- Round the imagesPerRow instead of flooring - we often will end up with values like 4.99999 due to floating point precision
- Update `getDownImage` comments & logic to be clearer
- Use variables for the ids in query selectors, preventing future typos
- Only scroll if the new selected image is different from the prev one
Arrow nav of gallery should work correctly at all gallery sizes and scales
n/a

fix(ui): fix gallery nav math

---

invokeai/frontend/web/src/features/nodes/components/flow/AddNodePopover/AddNodePopover.tsx

The new select component appears to close itself before calling the onchange handler. This short-circuits the autoconnect logic. Tweaked so the ordering is correct.
- Closes #5425
bug should be fixed

fix(ui): fix add node autoconnect

---

invokeai/backend/model_management/model_probe.py

- Closes #5435
This two-line fix enables correct probing of diffusers-style [latent-consistency/lcm-lora-sdxl](https://huggingface.co/latent-consistency/lcm-lora-sdxl)
Closes #5435 
- Closes #
Can merge when approved.

Enable correct probing of LoRA latent-consistency/lcm-lora-sdxl

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedNodes.ts
invokeai/frontend/web/src/features/nodes/store/workflowSlice.ts
invokeai/frontend/web/src/features/nodes/util/workflow/buildWorkflow.ts

Workflow building would fail when a current image node was in the workflow due to the strict validation.
So we need to use the other workflow builder util first, which strips out extraneous data.
This bug was introduced during an attempt to optimize the workflow building logic, which was causing slowdowns on the workflow editor.
@hipsterusername your workflow should produce a beautiful goat w/ embedded workflow

fix(ui): use less brutally strict workflow validation

---

installer/lib/installer.py
pyproject.toml

Organise deps into ~3 categories:
- Core generation dependencies, pinned for reproducible builds.
- Core application dependencies, pinned for reproducible builds.
- Auxiliary dependencies, pinned only if necessary.
I pinned / bumped these to latest:
- `controlnet_aux`
- `fastapi`
- `fastapi-events`
- `huggingface-hub`
- `numpy`
- `python-socketio`
- `torchmetrics`
- `transformers`
- `uvicorn`
I checked the release notes for these and didn't see any breaking changes that would affect us. There is a `fastapi` breaking change in v108 related to background tasks but it doesn't affect us.
I tested on a fresh venv. The app still works and I can generate on macOS.
Hopefully, enforcing explicit pinned versions will reduce the issues where people get CPU torch.
It also means we should periodically …

feat: pin deps

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/index.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/galleryImageClicked.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageDeleted.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageDropped.ts
invokeai/frontend/web/src/common/components/InvContextMenu/InvContextMenu.tsx
invokeai/frontend/web/src/common/components/InvMenu/InvMenuList.tsx
invokeai/frontend/web/src/common/hooks/useGlobalMenuClose.ts
invokeai/frontend/web/src/common/util/skipMouseEvent.ts
invokeai/frontend/web/src/features/dnd/components/DragPreview.tsx
invokeai/frontend/web/src/features/dnd/types/index.ts
invokeai/frontend/web/src/features/dnd/util/isValidDrop.ts
invokeai/frontend/web/src/features/gallery/components/Boards/BoardContextMenu.tsx
invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageContextMenu.tsx
invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx
invokeai/frontend/web/src/features/gallery/hooks/useGalleryImages.ts
invokeai/frontend/web/src/features/gallery/hooks/useMultiselect.ts
invokeai/frontend/web/src/features/gallery/hooks/useScrollIntoView.ts
invokeai/frontend/web/src/features/gallery/store/galleryPersistDenylist.ts
invokeai/frontend/web/src/features/gallery/store/gallerySelectors.ts
invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts
invokeai/frontend/web/src/features/gallery/store/types.ts
invokeai/frontend/web/src/features/nodes/components/flow/Flow.tsx
invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/FieldContextMenu.tsx
invokeai/frontend/web/src/features/nodes/components/flow/nodes/common/NodeWrapper.tsx
invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsMenu.tsx
invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryMenu/WorkflowLibraryMenu.tsx

- De-jank context menu, closes #5457
- Fix major bug with gallery where board selection sometimes didn't work. Ended up making some performance improvements to selecting images in gallery - its much faster now.
- You should be able to switch boards after loading more images in the gallery. This was broken before.
- The context menu shouldn't do the thing it was doing in #5457.

ui: redesign followups 10

---

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/anyEnqueued.ts
invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketConnected.ts
invokeai/frontend/web/src/features/system/store/systemPersistDenylist.ts
invokeai/frontend/web/src/features/system/store/systemSlice.ts
invokeai/frontend/web/src/features/system/store/types.ts
invokeai/frontend/web/src/services/api/endpoints/appInfo.ts
invokeai/frontend/web/src/services/api/endpoints/boards.ts
invokeai/frontend/web/src/services/api/endpoints/images.ts
invokeai/frontend/web/src/services/api/endpoints/queue.ts
invokeai/frontend/web/src/services/api/endpoints/utilities.ts
invokeai/frontend/web/src/services/api/endpoints/workflows.ts
invokeai/frontend/web/src/services/api/index.ts

See the changes in `invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketConnected.ts` for well-commented recovery logic.
- Add checks to the "recovery" logic for socket connect events to reduce the number of network requests.
- Remove the `isInitialized` state from `systemSlice` and make it a nanostore local to the socketConnected listener. It didn't need to be global state. It's also now more clearly named `isFirstConnection`.
- Export the queue status selector (minor improvement, memoizes it correctly).
Note: Currently re-fetch _everything_ during a socket connect event. We don't need to re-fetch everything - we only need to re-fetch things related to the queue and gallery. At least, I think that's all we need to re-fetch. However, those are …

fix(ui): reduce reconnect requests

---

invokeai/app/services/config/config_default.py
invokeai/backend/util/devices.py

Allow bfloat16 to be configured in invoke.yaml
Need help testing as I cannot on my machine. 
Set `precision: bfloat16` and test generations. Then set `precision: auto` and test generations. 
Can be merged once tested.
N/A

Allow bfloat16 to be configurable in invoke.yaml

---

invokeai/frontend/web/package.json
invokeai/frontend/web/pnpm-lock.yaml
invokeai/frontend/web/src/features/ui/hooks/usePanel.ts

Per user feedback, this is preferrable to letting them expand when the window grows.
Also bumps `react-resizable-panels` now that one of my PRs is merged to fix an issue.
---
https://discord.com/channels/1020123559063990373/1195752052136087582/1195752052136087582
Panel should resize to minimum when the window resizes.

feat(ui): resize options/gallery panels to min on window resize

---

invokeai/backend/install/model_install_backend.py

- Related Issue #5525 
- Closes #5525 
No

fix(backend) installed models being redownloaded

---

invokeai/app/api/no_cache_staticfiles.py
invokeai/app/api_app.py

The previous method wasn't totally foolproof, and locales/assets were cached.
To solve this once and for all (famous last words, I know), we can subclass `StaticFiles` and use maximally strict no-caching headers to disable caching on all static files.
- Related Issue #5507
First, reproduce the issue:
- Build the frontend on `main`
- Navigate to the UI, open the network panel of your browser devtools and reload the page
- Change the language to something else and back to your preference
- Reload again
- Change the language to the one you selected before and back again
- Reload again, change lang again
- Note that instead of transferred, you see `cached` for JS assets and language files
Next, check out this PR, open an incognito window (or clear your cache) and do the same steps. You should …

fix(api): add `NoCacheStaticFiles` to prevent *all* caching

---

invokeai/frontend/web/src/features/nodes/types/common.ts

Remove `trim()` from model identifier schema, which prevented parsed model identifiers from matching.
The root issue here is that model names are identifiers. This will be resolved in the model manager refactor.
Closes #5556

fix(ui): handle model names with spaces

---

invokeai/frontend/web/src/features/nodes/util/workflow/buildWorkflow.ts

fix workflow updating

---

invokeai/frontend/web/src/features/queue/components/ClearQueueIconButton.tsx
invokeai/frontend/web/src/features/ui/components/FloatingParametersPanelButtons.tsx

Buttons that handle the queue on the floating panel used to perform the same thing which is confusing. This pr makes the bottom one only clear the entire queue while the upper one clears the current item (behavior unchanged).
1. Toggle the side panel to the folded state so that the floating panel appears
2. Queue up multiple items
3. The bottom button should cancel the entire queue (via confirmation dialog)

fix(ui): the bottom button on floating side panel clears all queue items

---

pyproject.toml

This updates Safetensors to the new released version 0.4.2. It was released just yesterday, so I couldn't include it in my earlier Huggingface update PR. No regressions found thus far.
Edit: Mini-Update for transformers also added since it's the same ecosystem
Greetings
- Closes #

Update safetensors and transformers to their latest versions

---

invokeai/frontend/web/src/features/canvas/store/canvasNanostore.ts

Remove resetting cursor when resetting state letting event handlers to take care of presentation
This PR addresses a bug on unified canvas tab when switching between tools using shortcuts. It only happens if the "Limit strokes to box" setting is on. While inside the bounding box switching tools resets the cursor to default thus obstructing the brush (especially if the brush size is small).
https://github.com/invoke-ai/InvokeAI/assets/4258136/922697fe-7eb6-45dc-9ce2-941620a63b59

fix(ui): cursor obstructing brush

---

invokeai/app/services/invocation_processor/invocation_processor_default.py
invokeai/app/services/invocation_stats/invocation_stats_base.py
invokeai/app/services/invocation_stats/invocation_stats_common.py
invokeai/app/services/invocation_stats/invocation_stats_default.py

feat(stats): refactor InvocationStatsService to output stats as dataclasses
This allows the stats to be written to disk as JSON and analyzed.
- Add dataclasses to hold stats.
- Move stats pretty-print logic to `__str__` of the new `InvocationStatsSummary` class.
- Add `get_stats` and `dump_stats` methods to `InvocationStatsServiceBase`.
- `InvocationStatsService` now throws if stats are requested for a session it doesn't know about. This avoids needing to do a lot of messy null checks.
- Update `DefaultInvocationProcessor` to use the new stats methods and suppresses the new errors.
When generating:
- Stats should still be logged to the terminal same as before
- If profiling is enabled, you should get a JSON file with the stats in your `profiles/` dir

feat(nodes): structured stats

---

invokeai/app/services/config/config_default.py

This substantially reduces the time spent encoding PNGs. In workflows with many image outputs, this is a drastic improvement.
For a tiled upscaling workflow going from 512x512 to a scale factor of 4, this can provide over 15% speed increase.
---
There is a minor file size increase, but bytes are far cheaper than time.
Snippet from [profiling](https://github.com/psychedelicious/pil-vs-cv2):
file @ (1024, 1024), compress_level=1 -> 63.35ms +-0.08ms (1494.83kb)
file @ (1024, 1024), compress_level=6 -> 215.78ms +-0.30ms (1327.04kb)
`1` takes 30% of the time for a 13% larger filesize.
@Millu We may want to communicate to users that they can set this in `invokeai.yaml` for a speed boost, in case the setting is already set for them.

perf(config): change default png_compress_level to 1

---

invokeai/frontend/web/public/locales/en.json
invokeai/frontend/web/src/common/hooks/useDownloadImage.ts
invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx

In some environments, a simple `a` element cannot trigger a download of an image. Fetching the image directly can get around this and provide more reliable download functionality.
This PR can be merged when approved by @maryhipp

fix(ui): download image opens in new tab

---

invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx
invokeai/frontend/web/src/features/system/components/SettingsModal/useClearIntermediates.ts

The `getIntermediatesCount` query is set to `refetchOnMountOrArgsChange`. The intention was for when the settings modal opens (i.e. mounts), the `getIntermediatesCount` query is refetched. But it doesn't work - modals only mount once, there is no lazy rendering for them. 
So we have to imperatively refetch, by refetching as we open the modal.
--- 
Another way to handle this would be to invalidate the `IntermediatesCount` tag when the settings modal is opened, but this is a bit more complex. Internally, the `clearIntermediates` mutation invalidates this tag, so when you click the button, it automatically refreshes.
We will not be making the intermediates count refresh "live", we'd have to refetch constantly. With this change, you can close and open the settings modal again to update it.
- …

fix(ui): refetch intermediates count when settings modal open

---

invokeai/frontend/web/src/features/nodes/util/schema/buildFieldInputTemplate.ts
invokeai/frontend/web/src/features/nodes/util/schema/parseFieldType.ts

Turns out the OpenAPI schema definition for a pydantic field with a `Literal` type annotation is different depending on the number of options.
When there is a single value (e.g. `Literal["foo"]`, this results in a `const` schema object. The schema parser didn't know how to handle this, and displayed a warning in the JS console.
This situation is now handled. When a `const` schema object is encountered, we interpret that as an `EnumField` with a single option.
I think this makes sense - if you had a truly constant value, you wouldn't make it a field, so a `const` must mean a dynamically generated enum that ended up with only a single option.
- Closes #5616
Example node:
```py
@invocation(
"literal_test", title="Literal Test", tags=["primitives", "boolean"], category="primitives", …
```

fix(ui): handle fields with single option literal

---

invokeai/frontend/web/src/features/nodes/util/schema/parseSchema.ts

- Unknown errors were swallowed during schema parsing. Now they log a warning.
- Added trace log for when skipping reserved input field type
I don't know how to create a situation where this is relevant, but I'm sure it exists.

fix(ui): do not swallow errors during schema parsing 

---

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ColorFieldInputComponent.tsx
invokeai/frontend/web/src/features/nodes/util/graph/buildNodesGraph.ts

Closes #5647
The alpha values in the UI are `0-1` but the backend wants `0-255`.
Previously, this was handled in `parseFIeldValue` when building the graph. In a recent release, field types were refactored and broke the alpha handling.
The logic for handling alpha values is moved into `ColorFieldInputComponent`, and `parseFieldValue` now just does no value transformations.
Though it would be a minor change, I'm leaving this function in because I don't want to change the rest of the logic except when necessary.
Color fields' alpha values should work correctly:
- When executing a node w/ color field, the output value for alpha should be 0-255, matching the slider in the UI
- When switching tabs, the alpha value should not reset

fix(ui): fix color input field alpha

---

invokeai/app/services/invocation_processor/invocation_processor_default.py
invokeai/app/services/invocation_stats/invocation_stats_default.py

Improved stats reporting and error handling. See commits.
- Related https://discord.com/channels/1020123559063990373/1149513625321603162/1204279425231749181
- Cancel a running graph (just a normal t2i on linear tab is fine). You should get stats for it.
- Create a graph that will fail (for example, a single resize image node with no image - disable validation in the workflow editor settings to be able to submit this). You should get only the invocation error, and then stats. You should _not_ get an error message saying "Attempted to get graph statistics for unknown graph..."
Note: If you cancel during the very first model load, you get no output. I cannot figure out where the processor loop exits for the life of me. I thought it might be here:
```py
if …
```

feat(nodes): improved stats reporting, error handling

---

installer/lib/messages.py

…elected
Small bugfix: the installer would always print the latest stable version as the one to be installed, even if a different one was selected. The selected version would still be installed correctly. This PR fixes the message. 
Select a pre-release version on install and observe the correct version being printed. Compare to current behaviour to ascertain the fix.
- "This PR can be merged when approved"

Print correct version when a non-default version is selected for install
