invokeai/frontend/web/src/features/nodes/util/graph/addSDXLLoRAstoGraph.ts, invokeai/frontend/web/src/features/settingsAccordions/components/GenerationSettingsAccordion/GenerationSettingsAccordion.tsx
We weren't omitting disabled LoRAs from the SDXL graphs. Fixed that.
Also fixed the LoRA count badge - it was showing `0` when there were were LoRAs added but all disabled.
Use a LoRA on SDXL with manual seed. Disable the LoRA; the image should be different.
=> fix(ui): omit disabled loras from sdxl graphs

invokeai/frontend/web/src/features/controlAdapters/components/ControlAdapterImagePreview.tsx
The control image dimensions were set directly without rounding them to 8, causing an error during generation if they weren't a multiple of 8.
- Upload an image with dimensions that are not a multiple of 8
- Use it as a control image
- Click the button to use the control image dimensions
- They should round to 8 before being set
=> fix(ui): when using control image dimensions, round to 8

invokeai/app/services/shared/graph.py
The change to memory session storage brings a subtle behaviour change.
Previously, we serialized and deserialized everything (e.g. field state, invocation outputs, etc) constantly. The meant we were effectively working with deep-copied objects at all time. We could mutate objects freely without worrying about other references to the object.
With memory storage, objects are now passed around by reference, and we cannot handle them in the same way.
This is problematic for nodes that mutate their own inputs. There are two ways this causes a problem:
- An output is used as input for multiple nodes. If the first node mutates the output object while `invoke`ing, the next node will get the mutated object.
- The invocation cache stores live python objects. When a node mutates an output pulled …
=> fix(nodes): deep copy graph inputs

docker/README.md, docs/installation/040_INSTALL_DOCKER.md
`.env.sample` was misspelled as `env.sample` in a few places.
This changes documentation only. You may need to re-build/deploy docs, I'm not sure.
=> fix references to .env.sample

invokeai/frontend/web/src/features/workflowLibrary/components/UploadWorkflowButton.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryList.tsx, invokeai/frontend/web/src/features/workflowLibrary/hooks/useLoadWorkflowFromFile.tsx
Add option to upload workflow from file in workflow library modal
- Closes #
=> move upload button into workflow library modal

pyproject.toml
https://github.com/huggingface/diffusers/releases/tag/v0.26.3
This fixes an issue with `DPMSolverSinglestepScheduler` with even numbers of steps.
https://discord.com/channels/1020123559063990373/1149506274971631688/1206564014184861766
=> chore: bump diffusers 0.26.2 -> 0.26.3

invokeai/backend/model_management/seamless.py
- [ X ] Bug Fix
- [ X ] No, because: It's small
- [ X ] No
This pulls out some of the updates from the WIP Seamless branch that has yet to be completed, and hardcodes values that are exposed in that branch. Given that seamless currently does not generate seamless textures, and this fix results in seamless outputs, it's an improvement even if it doesn't resolve this in a "perfect" way that exposes all variables to the end user.
better over perfect.
=> Quick Seamless Fixes

invokeai/app/services/shared/graph.py
Methods `get_node` and `complete` were typed as returning a dynamically created unions `InvocationsUnion` and `InvocationOutputsUnion`, respectively.
Static type analysers cannot work with dynamic objects, so these methods end up as effectively un-annotated, returning `Unknown`.
They now return `BaseInvocation` and `BaseInvocationOutput`, respectively, which are the superclasses of all members of each union. This gives us the best type annotation that is possible.
Note: the return types of these methods are never introspected, so it doesn't really matter what they are at runtime.
=> feat(nodes): improve types in graph.py

invokeai/app/services/images/images_default.py
The error was misleading, indicating an issue with getting the image DTO, when it was actually an issue with getting metadata.
This is a very simple change, only the log message is changed. No testing needed.
=> fix(images_default): correct get_metadata error message

docker/Dockerfile, docker/run.sh
I briefly mentioned it to sophrocyne on HN.
The documentation does not require any updates.
With these changes, the Docker image can be built and executed successfully on hosts with AMD devices with ROCm acceleration. Previously, a ROCm-enabled version of torch would be installed, but later removed during installation of InvokeAI itself. This was caused by InvokeAI needing a newer torch version than was previously installed.
The fix consists of multiple components:
* Update the hardcoded versions of torch and torchvision to the versions currently used in pyproject.toml, so that a new version need not be installed during installation of InvokeAI.
* Specify --extra-index-url on installation of InvokeAI so that even if a verison mismatch occurs, the correct torch version should still be …
=> fix: repair Dockerfile for ROCm

invokeai/backend/install/invokeai_configure.py, invokeai/frontend/install/model_install.py
- Removed a legacy function definition that was causing a crash after marshalling arguments.
- Fixed bug that was causing "auto" precision to revert to "float16" each time.
Problem first reported by `joshistoast` at https://discord.com/channels/1020123559063990373/1049495067846524939/1207914069324210196
After pulling this PR, run `invokeai-configure --root /path/to/root --yes`. Should download default models without crashing.
=> Fix invokeai-configure crash on next branch

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/components/InformationalPopover/constants.ts, invokeai/frontend/web/src/features/controlAdapters/components/parameters/ParamControlAdapterBeginEnd.tsx, invokeai/frontend/web/src/features/controlAdapters/components/parameters/ParamControlAdapterProcessorSelect.tsx, invokeai/frontend/web/src/features/hrf/components/ParamHrfMethod.tsx, invokeai/frontend/web/src/features/hrf/components/ParamHrfStrength.tsx, invokeai/frontend/web/src/features/hrf/components/ParamHrfToggle.tsx, invokeai/frontend/web/src/features/lora/components/LoRACard.tsx, invokeai/frontend/web/src/features/lora/components/LoRASelect.tsx, invokeai/frontend/web/src/features/parameters/components/Canvas/InfillAndScaling/ParamInfillPatchmatchDownscaleSize.tsx, invokeai/frontend/web/src/features/parameters/components/Core/ParamHeight.tsx, invokeai/frontend/web/src/features/parameters/components/Core/ParamWidth.tsx, invokeai/frontend/web/src/features/parameters/components/ImageSize/AspectRatioSelect.tsx, invokeai/frontend/web/src/features/parameters/components/ImageToImage/ImageToImageFit.tsx, invokeai/frontend/web/src/features/parameters/components/MainModel/ParamMainModelSelect.tsx, invokeai/frontend/web/src/features/parameters/components/Seamless/ParamSeamlessXAxis.tsx, invokeai/frontend/web/src/features/parameters/components/Seamless/ParamSeamlessYAxis.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerCFGScale.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerModelSelect.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerNegativeAestheticScore.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerPositiveAestheticScore.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerScheduler.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerStart.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerSteps.tsx
Added new tooltip popovers and updated copy of existing ones
- Closes #
=> updated tooltip popovers

Makefile
This PR adds two new targets to the `Makefile`:
* `test` -- This runs `pytest tests` from the root directory
* `frontend-install` -- This empties the old `invokeai/frontend/web/node_modules` directory and reinstalls the most up-to-date node modules by running `pypm install`.
- Closes #
Try:
```
make test
make frontend-install
make frontend-build
```
Can merge when approved.
=> Add a few convenience targets to Makefile

invokeai/app/invocations/fields.py, invokeai/app/invocations/latent.py, invokeai/app/invocations/primitives.py, invokeai/backend/stable_diffusion/diffusers_pipeline.py
Adds a node for Gradient Masking (referred to as "Soft Inpainting" in webui Forge, or "Differential Diffusion" in the first known implementation). This node is designed to be easily integrated with our existing Compositing settings in the Canvas without adding more graph complexity.  Canvas integration to be done in a future PR.  
Gradient Mask dynamically expands the masked area during the diffusion process based on the value of the mask. This improves edge coherence and can give better results than coherence pass while only requiring a single denoise stage.
Mask blurring is handled internally. This is to account for some special considerations that are otherwise hard to get right:  
* Masks blur outwards, not inwards. Particularly in small masked regions, blurring often erases too much …
=> Feat(Nodes): Add Gradient Mask node and denoising functions

invokeai/app/api/routers/model_manager.py, invokeai/app/services/model_install/model_install_base.py, invokeai/backend/install/install_helper.py, tests/app/services/model_install/test_model_install.py
This PR tidies up the model installer a bit.
- Support the extended HF repoid syntax previously discussed with @hipsterusername and @maryhipp. This allows easy installation of repo_id subfolders and files, and can be used to import a checkpoint file that is buried in a HF repo, as in `XpucT/Deliberate::Deliberate_v5.safetensors`
- Add `error` and `error_traceback` properties to the install job objects.
- Rename the `heuristic_import` route to `heuristic_install`.
- Fix the example `config` input in the `heuristic_install` route.
- Closes #
Start the webui and navigate to http://localhost:9091/docs#/model_manager/heuristic_install_model. Press "Try it Out" and paste in an extended repo_id. The following syntaxes should work:
```
foo/bar
foo/bar:fp16      # or fp32, onnx, …
```
=> Several small model install enhancements and fixes

invokeai/app/services/model_install/model_install_default.py, invokeai/app/services/model_manager/model_manager_base.py, invokeai/app/services/model_manager/model_manager_default.py
Previously, the Model Manager had CUDA as a hard-coded pre-req, which would fail on non-nvidia systems. This addresses this by adding Torch and selecting the correct device.
=> Next: Allow users to run model manager without cuda

invokeai/app/services/model_install/model_install_default.py, invokeai/backend/model_manager/probe.py
Currently there's no way to install a model with a predetermined key. This will allow us to pass a model_record key into the heuristic import call via the config parameter.
- Closes #
=> Next: Allow bespoke key on register

invokeai/backend/model_manager/load/model_cache/model_cache_base.py, invokeai/backend/model_manager/load/model_cache/model_cache_default.py, invokeai/backend/model_manager/load/model_cache/model_locker.py
At least on my system, if the model manager runs out of VRAM while moving a model into the GPU, the partial model gets stuck in VRAM and can't easily be removed. This makes the model unusable, and uses precious VRAM.
I encountered this when playing with large language models on the same system, but I suspect it will also happen if a video game is being played. I tried various approaches to recover from this state, including clearing the vram cache, deleting the model object, and running garbage collection, but without success.
This PR avoids the issue by implementing a check for sufficient available VRAM before trying to move a model to a CUDA GPU. If there is insufficient room, it raises a `torch.cuda.OutOfMemoryError`. This message is propagated to the front end. If more VRAM becomes …
=> Gracefully recover from VRAM out of memory errors (next branch version)

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/components/InformationalPopover/constants.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasInpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasOutpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasSDXLInpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasSDXLOutpaintGraph.ts, invokeai/frontend/web/src/features/parameters/components/Canvas/Compositing/MaskAdjustment/ParamMaskBlur.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/CompositingSettingsAccordion/CompositingSettingsAccordion.tsx, invokeai/frontend/web/src/features/system/store/configSlice.ts
- Canvas Mask Blur now has its own slider for independent control from the edge size of the coherence pass.
- Coherence Pass Edge Size can now be set to 0.
=> feat(ui): Split the Canvas Mask Blur & Edge Size Setting

invokeai/app/invocations/compel.py, invokeai/app/util/ti_utils.py
While we decide the best avenue for passing TI/Embeddings to the backend, this PRs allows the TI trigger word to be either the key of the TI model or the name of it.
- Related Issue [5804](https://github.com/invoke-ai/InvokeAI/issues/5804)
=> Next: Allow TIs to be either a key or a name in the prompt during our transition to using keys

invokeai/app/api/routers/model_manager.py, invokeai/backend/model_manager/search.py
Drastically speeds up initial invokeai startup time and subsequent model scans
- Closes #
=> Switch ModelSearch from os.walk to os.scandir

invokeai/app/invocations/compel.py, invokeai/backend/model_manager/search.py, invokeai/backend/model_patcher.py
Fix assertion issue in `compel.py`. Currently we check for just an instance of `CLIPTextModel` but SDXL text encoder can be either `CLIPTextModel` or `CLIPTextModelWithProjection`. This PR updates the assertion to permit either.
=> fix: Assertion issue with SDXL Compel

invokeai/app/api_app.py, invokeai/backend/model_manager/search.py
FastAPI is deprecating app.on_event which we currently use as our startup and shutdown hooks. FastAPI recommends replacing it with this lifespan feature.
=> Next: Remove deprecated app.on_event usage in api runner

docs/nodes/INVOCATION_API.md, docs/nodes/NODES_MIGRATION_V3_V4.md, docs/requirements-mkdocs.txt, docs/stylesheets/extra.css, invokeai/app/invocations/ip_adapter.py, invokeai/app/services/shared/invocation_context.py, invokeai/app/util/ti_utils.py, mkdocs.yml, pyproject.toml
- Update `mkdocs` config
- Add `mkdocstrings` to auto-document invocation context
- Fix some invocation context arg names (sorry, this should be in a separate PR but I wanted to test the docs generation together)
- Add docs for v3 -> v4 migration and the public API
- `pip install -e ".[docs]" to get latest deps, you may need to add `--force-reinstall` to get updated versions
- `mkdocs serve` to generate and browse the new docs - they are under `Workflows & Nodes`
Ensure that the docs page updates - we may need to manually kick that off once `next` merges to `main`.
=> docs: add node api migration docs

invokeai/app/services/download/download_default.py, invokeai/app/services/model_install/model_install_base.py, invokeai/app/services/model_install/model_install_default.py, pyproject.toml, tests/app/routers/test_images.py, tests/app/services/download/test_download_queue.py, tests/app/services/model_install/test_model_install.py, tests/backend/model_manager/model_manager_fixtures.py, tests/conftest.py
This PR fixes the periodic hang and timeout that occurs during the `test_model_install` and `test_download` unit tests.  It also  changes the default timeouts for unit tests (1 minute rather than 5 hours) and fixes the handling of the invokeai root during pytest.
Finally, it removes redundant and slow hashing calls executed during the model install process.
See discord thread: https://discord.com/channels/1020123559063990373/1212521379593719918/1212521450393829417
- Closes #
Use git actions to run `test_invoke.py pip` repeatedly. There should no longer be intermittent hangs and timeouts.
Merge after review.
=> Fix hang on model manager install unit tests

invokeai/app/services/model_install/model_install_default.py, invokeai/backend/model_manager/probe.py, tests/app/services/model_install/test_model_install.py
- Also fix redundant scanning of models directory at startup.
Two fixes to model manager:
1. Fix issue of all models being assigned a key of "<NOKEY>".
2. Fix issue of the models directory being scanned and probed at startup time even if no new models added.
Issue 1 was reported in discord: https://discord.com/channels/1020123559063990373/1049495067846524939/1212919046526472283
- Closes #
Try importing models now. They should be assigned random hexadecimal keys in the way the used to be.
No.
=> Fix problem of all installed models being assigned "<NOKEY>"

invokeai/app/invocations/controlnet_image_processors.py, invokeai/backend/image_util/depth_anything/__init__.py
=> cleanup: Remove manual offload from Depth Anything Processor

invokeai/app/services/model_install/model_install_default.py, invokeai/app/services/shared/sqlite_migrator/migrations/util/migrate_yaml_config_1.py, invokeai/backend/model_manager/hash.py, invokeai/backend/model_manager/probe.py, pyproject.toml, tests/app/services/model_install/test_model_install.py, tests/test_model_hash.py
Previously, when a model was installed, it was assigned a random database key. This caused issues because if the model was reinstalled, its key would change. It also makes metadata irreproducible. This PR changes the behavior so that keys are assigned determinstically based on the model contents
- .safetensors, .ckpt and other single file models are hashed with sha1. This is compatible with A1111's model hashes.
- The contents of diffusers directories are hashed using imohash (faster, but nonstandard)
See discord: https://discord.com/channels/1020123559063990373/1149513647022948483/1210441942249377792
- Closes #
Try installing and uninstalling a model, using the command line `invokeai-model-install --add <url or repoid>`, followed by `invokeai-mode-install --delete <name …
=> Make model key assignment deterministic

docs/nodes/defaultNodes.md, invokeai/app/invocations/latent.py, invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasInpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasOutpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasSDXLInpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildCanvasSDXLOutpaintGraph.ts
* Gradient Mask Node skips processing and returns tensorified version of image if edge_radius=0
* Gradient Mask Node now outputs an image representing the expanded mask area of the gradient.  
* Canvas workflows use this expanded mask for the paste-back operation (goes through MASK_RESIZE_DOWN)  
This enables two new use cases in workflows:
* Inpainting graphs can use the output for paste operations in a larger image without losing gradient denoise details
* Pre-made gradient mask images (by hand, depthmap, etc.) can be converted to mask tensors without modification and/or return an image of the total affected region.  
This fixes a bug noticeable when using a large edge radius where the canvas paste back would clip the result to the original mask boundaries and then apply a paste …
=> fix(canvas): use a corrected gradient mask for canvas pasteback

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/lora/components/LoRASelect.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/ImportQueue/ImportQueueBadge.tsx, invokeai/frontend/web/src/features/parameters/components/MainModel/NavigateToModelManagerButton.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/GenerationSettingsAccordion/GenerationSettingsAccordion.tsx
UI changes to consolidate the tabs in generation table - now main model and "concepts"/LoRAs appear alongside each other.
=> consolidate tabs for main model and concepts in generation panel

invokeai/app/api/routers/model_manager.py, invokeai/app/services/model_install/model_install_default.py
Allow in-place installs of local models without copying them to the <INVOKE_ROOT>/models dir.
=> Allow in place local installs of models

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/modelsLoaded.ts, invokeai/frontend/web/src/features/parameters/store/generationSlice.ts
* move `defaultModel` logic to modelsLoaded - if user does not have a model in their state already (typically after a web UI refresh or first load), it will use the passed in `defaultModel` key if it is in their list of main models. it will also fire the optimal width/height logic for that model type.
* update to work for key instead of name/base/type string
=> updates for `defaultModel`

invokeai/app/services/invocation_cache/invocation_cache_base.py, invokeai/app/services/invocation_cache/invocation_cache_memory.py, invokeai/frontend/web/src/services/api/endpoints/images.ts, tests/test_invocation_cache_memory.py
- Fix issue with invocation cache not clearing when images are deleted. 
- Add tests for invocation cache.
- Closes #5805
- Clear your invocation cache
- Create a workflow w a single resize image node, ensure cache is enabled for the node
- Invoke once with save to gallery enabled, once with it disabled
- Check cache stats, should show size 2
- Clear intermediates
- Cache size should reduce to 1
=> fix(nodes): invocation cache clearing

Makefile, invokeai/frontend/web/scripts/typegen.js, scripts/generate_openapi_schema.py
- Add python script that generates the openapi schema without needing to start up the application
- Update `typegen.js` to support piping in a schema from stdout or an arg with a URL or path to `openapi.json`
- Add `frontend-typegen` to `Makefile`
You should be able to run `make frontend-typegen` from repo root, without the app running, and generate the frontend types.
=> feat(scripts): typegen improvements

invokeai/app/api_app.py
This was preventing custom nodes from loading if a custom nodes dir was specified
Closes #5862
- Set a custom nodes dir in `invokeai.yaml` & put some nodes in it
- The custom nodes should load on startup
=> fix(nodes): load config before doing anything else

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasSettingsButtonPopover.tsx, invokeai/frontend/web/src/features/canvas/hooks/useCanvasZoom.ts, invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts, invokeai/frontend/web/src/features/canvas/store/canvasTypes.ts
Adds a setting to the canvas settings to invert the direction of brush size on mouse wheel.
- Closes #5872 
=> invert canvas brush size hotkey setting

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/canvas/components/IAICanvasStagingAreaToolbar.tsx, invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
Adds a new button to the canvas staging area toolbar to clear the current staged image.
- Closes #
=> discard current inpaint instance

invokeai/app/services/model_install/model_install_default.py
On model manager startup, this will check if a user has 0 rows in their model table _and_ 1+ entries in their models yaml file. If so, we will attempt to add each of their yaml entries to the models DB. This is designed to run one time, when a user first starts their app after updating to 4.0.
=> migrate models on service start

invokeai/frontend/web/src/features/modelManagerV2/store/modelManagerV2Slice.ts, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/ScanFolder/ScanFolderForm.tsx
Scan path is not remembered by the app. Now it remembers. Never forgets.
- Closes #
=> ui(model_manager): Remember Scan Path

invokeai/app/services/model_records/model_records_sql.py
Add `order_by` with default of `"type, base, name, format"` for the function that we use for model list
- Closes #
=> fix(ui): add ordering for model list

invokeai/app/services/model_install/model_install_default.py
If yaml entry has a `config`, make sure that is migrated into DB as absolute `config_path` path
=> fix(app): include `config_path` in yaml -> DB migration

invokeai/app/services/model_install/model_install_default.py
The old logic to check if a model needed to be moved relied on the model path being a relative path. Paths are now absolute, causing this check to fail. We then assumed the paths were different and moved the model from its current location to, well, its current location.
Use more resilient method to check if a model should be moved.
- Start the app on `main` with memory db, note that it moves all your models on startup
- Try this PR - no extra moves.
=> fix(mm): only move model files if necessary

invokeai/app/services/model_install/model_install_default.py
- If the metadata yaml has an invalid version, exist the app. If we don't, the app will crawl the models dir and add models to the db without having first parsed `models.yaml`. This should not happen often, as the vast majority of users are on v3.0.0 models.yaml files.
- Fix off-by-one error with models count (need to pop the `__metadata__` stanza
- After a successful migration, rename `models.yaml` to `models.yaml.bak` to prevent the migration logic from re-running on subsequent app startups.
With a v3.X.Y `models.yaml` and database:
- Make backups of your `models.yaml` and db
- Run the app from this PR, all models should migrate successfully and show up in the app
- `models.yaml` should have been renamed `models.yaml.bak`
- Restart the app, it should not show any model migration …
=> fix(mm): yaml migration fixup

invokeai/app/api_app.py, invokeai/app/invocations/controlnet_image_processors.py, invokeai/app/invocations/ip_adapter.py, invokeai/app/invocations/latent.py, invokeai/app/invocations/model.py, invokeai/app/invocations/sdxl.py, invokeai/app/invocations/t2i_adapter.py, invokeai/app/services/shared/invocation_context.py, invokeai/frontend/web/.storybook/ReduxInit.tsx, invokeai/frontend/web/src/common/hooks/useGroupedModelCombobox.ts, invokeai/frontend/web/src/common/hooks/useModelCombobox.ts, invokeai/frontend/web/src/common/hooks/useModelCustomSelect.ts, invokeai/frontend/web/src/features/controlAdapters/store/controlAdaptersSlice.ts, invokeai/frontend/web/src/features/lora/store/loraSlice.ts, invokeai/frontend/web/src/features/metadata/util/handlers.ts, invokeai/frontend/web/src/features/metadata/util/modelFetchingHelpers.ts, invokeai/frontend/web/src/features/metadata/util/parsers.ts, invokeai/frontend/web/src/features/nodes/types/common.test-d.ts, invokeai/frontend/web/src/features/nodes/types/common.ts, invokeai/frontend/web/src/features/nodes/types/field.ts, invokeai/frontend/web/src/features/nodes/util/graph/addLoRAsToGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/addSDXLLoRAstoGraph.ts, invokeai/frontend/web/src/features/parameters/components/MainModel/ParamMainModelSelect.tsx, invokeai/frontend/web/src/features/parameters/components/VAEModel/ParamVAEModelSelect.tsx, invokeai/frontend/web/src/features/parameters/types/parameterSchemas.ts, invokeai/frontend/web/src/features/parameters/util/optimalDimension.ts, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerModelSelect.tsx, invokeai/frontend/web/src/services/api/schema.ts, invokeai/invocation_api/__init__.py
Add name, hash, base and type to the model identifiers used throughout the app.
Generate, load an old workflow, etc.
=> feat(nodes): enriched model identifiers

invokeai/app/invocations/latent.py
Inpainting models have 9 input channels instead of 4  
[(4-channel latent), (1-channel mask), (4-channel masked_latents)]  
When using Gradient Mask, creating masked_latents is skipped, which breaks inpainting models.
Our existing Create Denoise Mask node zeros out the masked parts of the input image and then encodes the result to latent form using VAE.  
This implementation takes the already-encoded latent image and zeros out the masked parts.  
These two operations are not quite the same. However, I could not find any good description of which method is correct, and this is the way that the diffusers library code handles it for inpaint pipelines. As some consequence of the training, doing nothing to the original image latents does not allow the model to function.
We should consider if …
=> fix: make Canvas compatible with inpainting models again

invokeai/app/services/model_install/model_install_default.py, invokeai/backend/model_manager/search.py, tests/test_model_search.py
- No need for it to by a pydantic model. Just a class now.
- Remove ABC, it made it hard to understand what was going on as attributes were spread across the ABC and implementation. Also, there is no other implementation.
- Add tests
You should have the same models imported at startup as on `main` (using a memory db).
Tests offer solid coverage, too.
=> tidy(mm): ModelSearch cleanup

invokeai/app/services/model_install/model_install_default.py
Two fixes:
1. [fix(mm): fix models.yaml backup filename](https://github.com/invoke-ai/InvokeAI/commit/52872d383940903625906dacae3850ad91d85a9d)
Was erroneously `models.bak`, now `models.yaml.bak`
2. [fix(mm): models lose file extension when syncing](https://github.com/invoke-ai/InvokeAI/commit/1cfe56aac91f9c96ae84496a28af5e0132993c90)
We were stripping the file extension from file models when  moving them in `_sync_model_path`. For example, `some_model.safetensors` would be moved to `some_model`, which of course breaks things.
Instead of using the model's name as the new path, use the model's path's last segment. This is the same behaviour for directories, but for files, it retains the file extension.
The issue was kinda side-stepped in 67163c2224007ceac38d804ebd708bf89da5cb62, but the …
=> fix(mm): do not erroneously rename files

invokeai/app/invocations/latent.py, invokeai/backend/stable_diffusion/diffusers_pipeline.py, invokeai/backend/stable_diffusion/diffusion/conditioning_data.py, invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py
Remove dead code related to an old symmetry feature.
Note that `postprocessing_settings` was hard-coded to:
```python
PostprocessingSettings(
threshold=0.0,  # threshold,
warmup=0.2,  # warmup,
h_symmetry_time_pct=None,  # h_symmetry_time_pct,
v_symmetry_time_pct=None,  # v_symmetry_time_pct,
)
```
This fixed configuration meant that the post-processing logic was having no effect.
I ran image generation with and without this change. The resultant images are identical.
=> Remove dead code related to an old symmetry feature.

invokeai/app/invocations/ip_adapter.py, invokeai/app/invocations/model.py
fix(nodes): ip adapter uses valid ModelIdentifierField for image encoder model
- Add class method to `ModelIdentifierField` to construct the field from a model config
- Use this to construct a valid IP adapter model field
- Closes  #5918
IP Adapter should work
=> fix(nodes): ip adapter

invokeai/app/services/config/config_base.py, invokeai/backend/install/invokeai_configure.py
Prior to this PR, invokeai-configure crashes when it attempts to process the remote_api_tokens config due to it not containing primitive objects. This detects Basemodels as well as lists of BaseModels and converts them to dicts that omegaconf can handle.
- Create an invokeai.yaml file with a list of remote_api_tokens similar to those below
``` yaml
Model Install:
remote_api_tokens:
- url_regex: .*
token: test1
- url_regex: .*
token: test2
- url_regex: .*
token: test3
- url_regex: .*
token: test4
```
- Run invokeai-configure defined on this branch. Validate the script neither crashes nor rewrites your invokeai.yaml file without the configs above.
=> Allow lists of basemodel objects in omegaconf

invokeai/backend/model_manager/load/model_cache/model_cache_default.py
A recent change was made to force `log_memory_usage=True` when debug logs are enabled (commit: https://github.com/invoke-ai/InvokeAI/commit/67eb71509370214a04d7f5512eb3663dc3df5a9d). This PR reverts that change.
The speed cost of log_memory_usage=True is large (as documented here: https://github.com/invoke-ai/InvokeAI/pull/5028). It is common to want debug logs without enabling `log_memory_usage`.
=> Do not override log_memory_usage when debug logs are enabled

invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/TriggerPhrases.tsx
Disables submission of the trigger phrase form if it is empty
closes https://github.com/invoke-ai/InvokeAI/issues/5941
=> fix(ui): disable trigger phrase form if empty

.github/workflows/frontend-checks.yml, .github/workflows/frontend-tests.yml, .github/workflows/python-checks.yml, .github/workflows/python-tests.yml, .github/workflows/release.yml
ci: add `always_run` input to checks & tests, use this on release workflow
This bypasses the `changed-files` check, and forces the checks to run. The release workflow sets this flag to ensure that the checks and tests are always run for a release.
=> ci: add `always_run` input to checks & tests, use this on release workflow

invokeai/frontend/web/src/features/controlAdapters/components/parameters/ParamControlAdapterModel.tsx, invokeai/frontend/web/src/features/parameters/components/MainModel/ParamMainModelSelect.tsx
* In some environments, the initial invalid state of an empty CustomSelect seems to get memoized and not updated when the items/selectedItem load. There is probably a better fix to be done in the CustomSelect component itself but this worked for now.
=> fix(ui): force CustomSelect's to rerender when models load to update invalid state 

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketConnected.ts
Initiate TI query when socket connects so that user does not have to wait for results when they engage with prompt trigger phrase popover
=> (ui): fetch TIs on socket connect

invokeai/app/invocations/metadata.py, invokeai/frontend/web/src/features/controlAdapters/store/constants.ts, invokeai/frontend/web/src/features/nodes/util/graph/addControlNetToLinearGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/addIPAdapterToLinearGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/addT2IAdapterToLinearGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/addVAEToGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/metadata.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts
For some time during the MM2 refactor, we wanted more model information in metadata than we we wanted to load models. We only stored the essential model-loading data in the frontend. 
A separate pydantic model `ModelMetadataField` represented the enriched metadata. When building graphs, this required a `fetch` for the model configs so we could populate metadata correctly.
This recently changed, and app state now has everything we need for metadata. No need for a fetch or the separate `ModelMetadataField`.
Control Adapter metadata should work still.
This PR depends on #5953. It can be merged once approved.
=> feat(nodes,ui): consolidate model fields

invokeai/app/invocations/metadata.py, invokeai/frontend/web/src/features/controlAdapters/store/constants.ts, invokeai/frontend/web/src/features/nodes/util/graph/addControlNetToLinearGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/addIPAdapterToLinearGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/addT2IAdapterToLinearGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/addVAEToGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/metadata.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts
Fix two failure modes for control adapter graph creation:
- Invalid control adapters making it past an initial filter, but being rejected later on
- Usage of `await` within a `forEach` loop, causing a race condition
I saw a post on discord but cannot find it now.
Control adapters should work
=> fix(ui): control adapter errors

invokeai/backend/model_manager/convert_ckpt_to_diffusers.py
This adds additional logic to the safetensors->diffusers conversion script to check for and install missing core conversion models at runtime.
I am not convinced that this fixes the underlying issue. There is already a check for missing core conversion models when the app starts up and unless the user ran with `--ignore_missing_core_models` we should never reach a state where the conversion script cannot find its models!
- Related Issue #5934 
- Closes #
=> Work around missing core conversion model issue

invokeai/backend/image_util/depth_anything/__init__.py
We were passing a PIL image when we needed to pass the np image.
Closes #5956
We were passing a PIL image when we needed to pass the np image.
Closes #5956
- Closes #5956
Depth anything processor should work.
=> fix(nodes): depth anything processor (#5956)

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/modelsLoaded.ts
The switch to one model list introduced a bug in the main model logic where it was using the whole list of models and not just the main model list. When storage was cleared, this mean that model that was not type=main could get set as main model, and that manifested as an invalid main model select.
=> fix(ui): initial main model in dropdown

pyproject.toml
This PR updates Diffusers to version 0.27.0 and Accelerate to 0.28.0
Both updates have been tested by me and Ryan (Diffusers only), and it seems like the deprecation in 0.27 isn't an issue anymore (it was in their GitHub main last week).
Should be safe to merge. After this PR we can update Pytorch to 2.2.X, see https://github.com/invoke-ai/InvokeAI/pull/5860
Greetings!
- Closes #
=> Update diffusers 0.26.3 -> 0.27.0 and other HF packages

invokeai/app/services/model_install/model_install_default.py
Currently, if there's a model in your models directory that was added via symlink, the model install service will resolve the symlink and move the model. This will stop that behavior and leave it in place.
If a user symlinks the model to the wrong directory in the models dir, it will still move the model. Not sure how we want to handle that situation.
Add a model to your models dir using a symlink and start the app. On main, it'd resolve the symlink and move the model. Now it should handle it as expected.
=> Stop registering and moving models which have symlinks in the models dir

invokeai/backend/model_manager/load/model_loaders/stable_diffusion.py
This reverts commit 9d045964d6d7157fa8162001e1f6badc6fe2ba48.
This reverses a workaround that was originally applied to accommodate a bug in the diffusers model conversion code. This bug was fixed upstream and the workaround is no longer needed.
See discord thread https://discord.com/channels/1020123559063990373/1149513647022948483/1219457860321284096
- Closes #
With the current diffusers (version 0.27.0) remove the conversion `models/.cache` directory and then try to generate using a checkpoint model. It should convert and render correctly.
=> Revert "fix(mm): provide ckpt config as stream to diffusers"

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketModelInstall.ts, invokeai/frontend/web/src/services/api/endpoints/models.ts, invokeai/frontend/web/src/services/api/index.ts
When consolidating all the model queries I messed up the query tags. Fixed now, so that when a model is installed, removed, or changed, the list refreshes.
- Closes #5975
- Closes #5907 
Install/update/delete a model and the list should refresh.
=> fix(ui): model list refreshes after changes

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/metadata/util/handlers.ts, invokeai/frontend/web/src/features/metadata/util/parsers.ts
Fix translatios for refiner metadata
Give refiner a model a render function so its not [object Object]
=> fix(ui): fix refiner metadata

invokeai/backend/stable_diffusion/diffusers_pipeline.py
Denoise Mask was being applied at the wrong time in the step loop, creating an off-by-one error. Each step during masked denoise was computing based on an unmasked region that was 1 step more noised than it should have been. 
- Closes #5966 
This effect has been seen regularly in SDXL inpainting, since those models are better at matching the surrounding textures during denoising. It was most prevalent on smooth or otherwise featureless backgrounds. In anime models, it tends to present as sparkles or polkadots.
With very low step counts (8-step LCM) there was a fringe effect noticed on the edges of expanded masks.
Inpainting LCM still has some color drift, possibly affected by the VAE round trip. That can be investigated later on. The noise artifacting at least is gone.
This PR can be …
=> Fix(backend): Denoise Masks being applied at the wrong time

pyproject.toml
Successor of my mess here https://github.com/invoke-ai/InvokeAI/pull/5860 
Greetings,
diffusers 0.27.0 finally got released. It was the last obstacle for Pytorch 2.2.
This PR updates Pytorch to the most recent version 2.2.1. Same for xFormers and their compatible version 0.0.25.
I was able to test this. It runs smoothly, however, I am limited to my Nvidia 3060 Windows setup here, and I am not able to test it on other device. Mac users are welcome to test.
Once Pytorch 2.2.2 is released, it will then be the last version for 2.2. Then the cycle begins anew.
- Closes #
=> Update pytorch and xFormers 2.1.2 -> 2.2.1

invokeai/frontend/web/src/features/nodes/util/graph/addVAEToGraph.ts
When handling adding VAE to the graph, we need to manage the possible VAE sources. We might get the VAE from a VAE node or a Seamless node, which modifies the VAE. We weren't handling this correctly for SDXL graphs with Refiner.
Closes  #5995
Test cases:
- SD1.5 without seamless
- SD1.5 with seamless
- SDXL without seamless
- SDXL with seamless
- SDXL with Refiner & without seamless
- SDXL with Refiner & with seamless
n/a
=> fix(ui): handle seamless with refiner

pyproject.toml
This package was mistakenly commited to main but isn't actually used. This PR simply removes it from the toml.
Ensure no impact on pytests or ability to start `invokeai-web`
Can be merged as approved.
=> Remove no longer used pwinput dependency

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/setDefaultSettings.ts
We need to use the `widthRecalled` and `heightRecalled` actions, which handle the aspect ratio.
Closes  #5974
Use model default settings. It should set the aspect ratio to Free
N/A
=> fix(ui): set aspect ratio to free when using default model settings

invokeai/app/services/download/download_default.py, invokeai/app/services/model_install/model_install_default.py, tests/app/services/download/test_download_queue.py, tests/app/services/model_install/test_model_install.py, tests/backend/model_manager/model_manager_fixtures.py
This PR causes the model_installer and download_queue `stop()` methods to block until their worker threads have exited. Previously `stop()` returned immediately.
This fix addresses an issue in the model installer unit test, where the installer is created and torn down in a pytest fixture.  Because a new installer was created immediately after the previous installer was torn down, it was possible for the old installer’s threads to intermix with the current ones, causing unpredictable results. This may fix the sporadic hangs and timeouts observed in the model installer unit test.
The downside of this is that the `test_model_install` and `test_download` unit tests now run noticeably slower than they used to due to waiting for the threads to exit. The alternative, of scoping the install …
=> Wait for threads to exit after stopping model installer/downloader

docker/.env.sample, docker/Dockerfile, docker/docker-compose.yml, docker/docker-entrypoint.sh
- A new container without an existing root directory would fail to start due to permission issues and being unable to create the config file - this is fixed.
- The `--host` CLI argument was removed as part of config optimization, and we were using it in the Dockerfile. Because the default bind host is 127.0.0.1, the app would not be accessible from outside the container (even from local host). Anyway, this PR adds `INVOKEAI_HOST` and `INVOKEAI_PORT` to the Dockerfile to provide working defaults that do not require additional intervention from the user.
A couple of other improvements to the dockerized experience:
- `INVOKEAI_ROOT` can now be set to a relative path without using a dedicated env var pair for this purpose. The original (`HOST_` and `CONTAINER_`) root dir environment variables …
=> Fix running under Docker following 4.0.0rc4 config changes

pyproject.toml
If you switch between different branches, by the time you get back to `main`, a different version of `ruff` might be installed that has slightly different formatting rules. This leads to incorrect formatting changes.
Pinning `ruff` avoids this issue.
N/A
N/A
Smersh that merge button!
=> pkg: pin version of `ruff`

invokeai/frontend/web/src/features/controlAdapters/components/parameters/ParamControlAdapterModel.tsx, invokeai/frontend/web/src/features/parameters/components/MainModel/ParamMainModelSelect.tsx
Use the old Combobox component for main model and control adapter model dropdowns.
Closes #6011
Both dropdowns should still work.
N/A
=> fix(ui): use the old combobox component for dropdowns

invokeai/frontend/web/src/features/controlAdapters/store/controlAdaptersSlice.ts, invokeai/frontend/web/src/features/lora/store/loraSlice.ts, invokeai/frontend/web/src/features/parameters/store/generationSlice.ts, invokeai/frontend/web/src/features/parameters/store/types.ts, invokeai/frontend/web/src/features/sdxl/store/sdxlSlice.ts
With the change to model identifiers from v3 to v4, if a user had persisted redux state with the old format, we could get unexpected runtime errors when rehydrating state if we try to access model attributes that no longer exist.
For example, the CLIP Skip component does this:
```ts
CLIP_SKIP_MAP[model.base].maxClip
```
In v3, models had a `base_type` attribute, but it is renamed to `base` in v4. This code therefore causes a runtime error:
- `model.base` is `undefined`
- `CLIP_SKIP_MAP[undefined]` is also undefined
- `undefined.maxClip` is a runtime error!
Resolved by adding a migration for the redux slices that have model identifiers. The migration simply resets the slice or the part of the slice that is affected, when it's simple to do a partial reset.
Closes #6000
- Spin up a v3 …
=> fix(ui): runtime errors related to model types in ui

docs/features/CONFIGURATION.md, invokeai/app/services/config/config_default.py, invokeai/backend/model_hash/model_hash.py, invokeai/backend/model_manager/probe.py, scripts/probe-model.py, tests/test_model_hash.py
For SSDs, `blake3` is about 10x faster than `blake3_single` - 3 files/second vs 30 files/second.
For spinning HDDs, `blake3` is about 100x slower than `blake3_single` - 300 seconds/file vs 3 seconds/file.
For external drives, `blake3` is always worse, but the difference is highly variable. For external spinning drives, it's probably way worse than internal.
The least offensive algorithm is `blake3_single`, and it's still _much_ faster than any other algorithm.
---
Also rename `blake3` to `blake3_multi` for clarity.
Numerous discussions on discord from users with spinning disks or external drives.
Enable memory db and start up. You should still get reasonable hashing speeds as it migrates everything.
N/A
=> feat(mm): use blake3_single as default hashing algo

invokeai/backend/model_manager/load/model_loaders/controlnet.py, invokeai/backend/model_manager/load/model_loaders/stable_diffusion.py, invokeai/backend/model_manager/load/model_loaders/vae.py
Folks who used `main` prior to rc2 to install models will have root-relative paths to the original checkpoint config files. This PR converts the paths into absolute paths that can be passed to the checkpoint->diffusers convert scripts.
Problem reported at https://discord.com/channels/1020123559063990373/1149506274971631688/1220371502264750150
Remove the convert `.cache` directory to force checkpoint conversions. Try to load a checkpoint model that was installed in main prior to `rc2`. It should convert and load.
Now try to install a new checkpoint model. It should convert and load as well.
=> Allow checkpoint config files to use root-relative paths

invokeai/app/services/config/config_default.py, invokeai/app/services/model_install/model_install_default.py, tests/test_config.py
The config system was erroneously writing parsed env vars to both the config file and example config file.
This problem was exacerbated by the model manager re-writing the config file during models.yaml migration. This was a holdover from a previous iteration of the config system.
Thanks to @skunkworxdark for catching this issue and discussing with me in #5920. 
Test coverage should be good, but I'd appreciate if @skunkworxdark could test this out too.
N/A
=> fix(config): do not write env vars

invokeai/app/services/download/download_default.py, invokeai/app/services/model_install/model_install_default.py
Something about Python's thread implementation prevents the main thread from receiving the interrupt signal (sigINT) while waiting for a lock. The effect of this was to make it impossible to interrupt the server startup process with ^C during the potentially long model registration period when using an in-memory database and models are being hashed  and registered.
This PR contains an ugly workaround that installs a sigINT handler during the model installer startup method. When a sigINT is received, it shuts down the installer threads, reinstalls the default sigINT, and then raises the signal to the main process. The main process can then shut down in an orderly fashion.
I've tested this on Linux and Windows, and it seems to work ok. I had to remove a `lock.acquire()` from the installer's …
=> Catch ^C at startup time while models are being registered

invokeai/backend/model_manager/starter_models.py
This model is SDXL and relies on CLIP Skip. We don't support that yet. Eventually myself or somebody will fix CLIP Skip for SDXL in #4624 and we can add it back if we want.
#4624
N/A
N/A
=> fix(mm): remove proteus model

invokeai/backend/model_manager/probe.py
Case-sensitive typo. `ModelType.Lora` should be `ModelType.LoRA`
=> fix:Update probe.py - Case-sensitive typo on `.LoRA`

invokeai/backend/model_manager/config.py, tests/app/services/model_records/test_model_records_sql.py
Add `extra="forbid"` to the default settings models.
Pydantic has some quirks related to unions. This affected how the union of default settings was evaluated. See https://github.com/pydantic/pydantic/issues/9095 for a detailed description of the behaviour that this change addresses.
Closes #6035.
Make and save changes to a ControlNet and T2I Adapter. 
N/A
=> fix(mm): default settings pydantic error

invokeai/frontend/web/src/features/nodes/util/workflow/migrations.ts
Loading default workflows sometimes requires we mutate the workflow object in order to change the category or ID of the workflow.
This happens in `invokeai/frontend/web/src/features/nodes/util/workflow/validateWorkflow.ts`
The data we get back from the query hooks is frozen and sealed by redux, because they are part of redux state. We need to clone the workflow before operating on it.
It's not clear how this ever worked in the past, because redux state has always been frozen and sealed.
N/A
Load a default workflow or old workflow. It should work.
N/A
=> fix(ui): load default workflows mutation error

installer/templates/invoke.sh.in
Minor cleanup for the launcher script.
This does remove the `--no-tui` arg for the launcher, which only presented the launcher options a slightly different way but which added extra surface area to the launcher. So this is a breaking change, if anybody actually uses that arg.
N/A
N/A
N/A
=> tidy: launcher

invokeai/app/services/shared/graph.py, tests/test_graph_execution_state.py
This PR optimizes the graph execution order by prioritizing Iterate nodes and their children, ensuring the correct execution sequence. The changes made to the _get_next_node method within the GraphExecutionState class address the issue of random output order and execution of Iterate node children.
Key changes include:
-  Extracting Iterate nodes from the topological order and sorting them based on their index attribute.
-  Prioritizing the execution of Iterate nodes and their children, ensuring the correct order.
-  Falling back to the topological order if no Iterate node or its children are ready for execution.
These improvements provide a more predictable and intuitive behavior for Iterate nodes.
To test the changes in this PR:
1.  Set up a workflow with one or more Iterate nodes.
2. …
=> Change GraphExecutionState's _get_next_node method to prioritize Iterate Nodes

invokeai/app/services/model_install/model_install_default.py, tests/app/services/model_install/test_model_install.py
Previously we only handled expected error types. If a different error was raised, the install job would end up in an unexpected state where it has failed and isn't doing anything, but its status is still running.
This indirectly prevents the installer threads from exiting - they are waiting for all jobs to be completed, including the failed-but-still-running job.
We need to handle any error here to prevent this.
Related:  #6044 - we also need to fix what appears to be a problematic embedding format for this issue.
First, edit `invokeai/app/services/model_install/model_install_default.py` to raise an error in `_register_or_install`:
```diff
diff --git a/invokeai/app/services/model_install/model_install_default.py b/invokeai/app/services/model_install/model_install_default.py
index …
```
=> fix(mm): prevent installer softlock when an unhandled error occurs

invokeai/backend/model_manager/probe.py, tests/test_model_probe.py
It's possible for a model's state dict to have integer keys, though we do not actually support such models.
As part of probing, we call `key.startswith(...)` on the state dict keys. This raises an `AttributeError` for integer keys.
This logic is in `invokeai/backend/model_manager/probe.py:get_model_type_from_checkpoint`
To fix this, we can cast the keys to strings first. The models w/ integer keys will still fail to be probed, but we'll get a `InvalidModelConfigException` instead of `AttributeError`.
Closes #6044
I'd like to get approval from @ljleb that this fixes the problem, but no worries if that's a bit too much work. I'm fairly confident that this change plus #6048 will resolve #6044 satisfactorily.
N/A
=> fix(mm): handle integer state dict keys in probe

invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelManagerPanel/ModelList.tsx
While clicking on the image-badge of images in the gallery, the image was not getting selected. This pr fixes it and there was also a bug in localisation in the model manager.
Reported by @joshistoast
=> fix(ui): image not getting selected when clicked on image-badge

invokeai/backend/model_manager/load/model_loaders/stable_diffusion.py, invokeai/backend/model_manager/probe.py, invokeai/configs/stable-diffusion/v2-midas-inference.yaml
I assume this was handled by our own conversion logic until it was removed recently.
- Specify `num_in_channels` as needed when converting ckpt to diffusers
- Fix a typo in the legacy config map
- Add missing legacy config file for depth
Closes  #6058
Install a normal checkpoint and these two test models:
- Inpaint: https://huggingface.co/runwayml/stable-diffusion-inpainting/resolve/main/sd-v1-5-inpainting.ckpt
- Depth: https://huggingface.co/stabilityai/stable-diffusion-2-depth/resolve/main/512-depth-ema.safetensors
To test conversion, do a normal t2i generation with each model.
The inpaint model should work fully, but we don't expect the depth model to generate (separate issue).
You should see this message in the terminal for the depth model, then other non-error messages:
``` …
```
=> fix(mm): handle depth and inpaint ckpt conversion

invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryList.tsx
Simple fix for #5477, changing the default ordering of the workflow library to descending.
Closes #5477 unless it would be better to do that with something more comprehensive.
=> Flip default ordering of workflow library; #5477

invokeai/frontend/web/src/features/controlAdapters/components/ControlAdapterImagePreview.tsx
When using a Control Adapter image's dimensions as the main output dimensions, fit the dimensions to the model's optimal dimensions.
N/A
- Set a large control image - something that's too large/small and with funky dimensions
- Change the main w/h to be random values
- Click the little ruler icon to use the control image size
- The w/h should match the aspect ratio but fit to the model's optimal dimensions
N/A
=> feat(ui): when using a control image's dimensions, fit to the current model's optimal dimensions

.github/workflows/build-installer.yml, docs/RELEASE.md, scripts/get_external_contributions.py
- Fix naming of installer zip file
- Update RELEASE.md docs
- Add `scripts/get_external_contributions.py`, useful for getting all external contributions for release notes.
Example output:
```sh
❯ python scripts/get_external_contributions.py --from 3.7.0 --to v4.0.0rc6 --token ***
3e46f7a010748d7da527af3ff6d2640d8e164250: Harvester62 - translationBot(ui): update translation (Italian) (https://api.github.com/repos/invoke-ai/InvokeAI/commits/3e46f7a010748d7da527af3ff6d2640d8e164250)
edde0fe174a593edb2225997d6ba8e28898bdcb5: Sufi2425 - translationBot(ui): update translation (Bulgarian) (https://api.github.com/repos/invoke-ai/InvokeAI/commits/edde0fe174a593edb2225997d6ba8e28898bdcb5)
2dfa51c2e5a7bd63d7506cc2165637d092924a49: Vasyanator - translationBot(ui): update translation (Russian) …
```
=> ci: release process enhancements

invokeai/backend/stable_diffusion/seamless.py
Note: This is a partial fix. It doesn't fix seamless in a multi-GPU setup, but it will fix non-seamless generation on a multi-GPU setup.
---
The seamless logic errors when a second GPU is selected. I don't understand why, but a workaround is to skip the model patching when there there are no seamless axes specified.
This is also just a good practice regardless - don't patch the model unless we need to. Probably a negligible perf impact.
Partial fix for #6010
Needs a machine w/ 2 GPUs to test. Normal generation should work on the second GPU (though we expect the same error if you enable seamless).
n/a
=> fix(nodes): workaround seamless multi gpu error

invokeai/app/services/shared/sqlite_migrator/migrations/migration_7.py
Due to a typo, the unused `model_config` table is not dropped during `migration_7`. This fixes the issue for users still on database version 6. For those who have already migrated to 7, we will need to remember to drop the `model_config` table again in migration 8, but seems like overkill to create a new migration just to correct this.
* closes #6080
Should not be needed to QA, but restore database to version 6 and then start the web app under this PR.
=> Drop model_config table during database version 7 migration.

invokeai/app/services/model_install/model_install_default.py, invokeai/app/services/shared/sqlite/sqlite_util.py, invokeai/app/services/shared/sqlite_migrator/migrations/migration_8.py, invokeai/backend/model_manager/load/model_loaders/controlnet.py, invokeai/backend/model_manager/load/model_loaders/stable_diffusion.py, invokeai/backend/model_manager/load/model_loaders/vae.py, tests/app/services/model_install/test_model_install.py
See first commit message for why. 
Includes a DB migration as a convenience for RC users whose databases are now full of absolute paths.
Discord thread: https://discord.com/channels/1020123559063990373/1049495067846524939/1223169963624366080
Test against:
- v3 install w/ a models.yaml and no db
- v4 RC6 or earlier
Both test cases must have some checkpoint models to test the legacy config paths, which have the same issue.
I've done this testing already using some local DB fixtures, but I'm tired and don't trust my own work yet. I'd like to test again tomorrow, or somebody else can pick it up from here.
n/a
=> feat(mm): restore relative paths for invoke-managed models

invokeai/app/services/shared/sqlite/sqlite_util.py
I left a “HERE I AM’ debug statement in the absolute->relative PR that was just committed. This backs it out.
=> Remove debug statement

invokeai/app/services/session_processor/session_processor_default.py
This must not have been tested after the processors were unified. Needed to shift the logic around so the resume event is handled correctly. Clear and easy fix.
Closes #6090
Queue up some generations and pause and resume. Should work fine.
n/a
=> fix(queue): pause & resume

invokeai/app/services/session_processor/session_processor_default.py
This fixes a state in which the invokeai web server goes into a fast spin loop, consuming 100% CPU.
Related to the fix for generation pause/resume in commit `9a1b35fa372fcfe99a43cda1e93c17dfba76786f`. I have tested that pause/resume/cancel still work.
Launch `invokeai-web` and monitor its CPU usage with top or similar system profiling tool. It should settle down at near 0% CPU usage when not actively generating an image.
=> Fix 100% CPU load in `session_processor_default._process()`

invokeai/app/services/session_processor/session_processor_default.py
When paused, the processor was pegging the CPU at 100%. 
- wait for the resume event instead of checking it in loop
- reduce overall indentation by using an early continue in the loop (one less conditional)
n/a
- Start the app, confirm CPU is not 100%
- Queue some generations, then pause & confirm CPU is not at 100%
n/a
=> fix(nodes): 100% cpu usage when paused

invokeai/backend/model_manager/convert_ckpt_to_diffusers.py, invokeai/backend/model_manager/load/model_loaders/vae.py
Fix VAE conversion. See commits for details.
https://discord.com/channels/1020123559063990373/1149506274971631688/1224117693532213369
Empty your disk conversion cache and use a non-diffusers VAE. On `main`, we expect an assertion error when loading the VAE. On this branch, no error.
Here's a safetensors VAE you can test with: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors?download=true
n/a
=> fix(mm): vae conversion

invokeai/app/invocations/custom_nodes/init.py, invokeai/app/services/shared/sqlite/sqlite_util.py, invokeai/app/services/shared/sqlite_migrator/migrations/migration_9.py
- Custom node import errors could crash the app on startup. For example, if a custom node isn't updated for v4.0.0, it might try to import an nonexistent class from the invokeai python package. These errors are how handled gracefully - an error message is printed to the python terminal and the app startups up normally.
- Empty the session queue during data migration. This prevents pydantic errors from spamming the terminal on startup, if the queue items are no longer valid. This can occur if we change any pydantic schemas from `SessionQueueItem` and on downward.
Discord thread: https://discord.com/channels/1020123559063990373/1020123559831539744/1224527169753976956
(thanks for raising @empessah)
Node error:
- Add an outdated custom node to the custom nodes dir. I used [this node pack, …
=> fix: handle custom node errors on startup, clear session queue via migration

invokeai/app/services/config/config_default.py, tests/test_config.py
The logic incorrectly set the `legacy_conf_dir` on windows, where the slashes go the other direction. Handle this case and update tests to catch it.
An issue where the conversion YAML configs were not located correctly started the investigation:
https://discord.com/channels/1020123559063990373/1224562758469681272
- Set a v3-style `invokeai.yaml` with `legacy_conf_dir` set to `configs\stable-diffusion` (note the slash)
- Start the app up, it will migrate the file
- Check `invokeai.yaml` again, there should be no `legacy_conf_dir` setting now (because we detected it was using the default value)
It'd be nice if @empessah could confirm deleting the `legacy_conf_dir` in the new `invokeai.yaml` file fixes the issue, but this is definitely a bug regardless.
=> fix(config): handle windows paths in invokeai.yaml migration for legacy_conf_dir

invokeai/frontend/web/src/features/parameters/store/generationSlice.ts
The valid values for this parameter changed when inpainting changed to gradient denoise. The generation slice's redux migration wasn't updated, resulting in a generation error until you change the setting or reset web UI.
Multiple discord reports:
- https://discord.com/channels/1020123559063990373/1149506274971631688/1224769870135033937
- https://discord.com/channels/1020123559063990373/1149506274971631688/1224828774504468561
You can test it by booting up 3.7.0 and setting the coherence mode, then upgrade to 4.0.0. We expect an error when you inpaint on canvas, until you reset web UI or change the setting once. 
This PR fixes it so the default value is correct and you don't have to reset or change the setting
n/a
=> fix(ui): add default coherence mode to generation slice migration

invokeai/backend/model_manager/load/model_cache/model_cache_default.py
Gives us a bit more visibility into these errors, which seem to be popping up more frequently with the new MM.
#6106 is an example of an issue where this would be useful
Induce an OOM, and you should get a more informative error message, like this:
```
torch.cuda.OutOfMemoryError: Insufficient VRAM to load model, requested 5.15GB but only had 3.30GB free
```
n/a
=> feat(mm): include needed vs free in OOM

invokeai/frontend/web/src/features/settingsAccordions/components/AdvancedSettingsAccordion/AdvancedSettingsAccordion.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/ControlSettingsAccordion/ControlSettingsAccordion.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/GenerationSettingsAccordion/GenerationSettingsAccordion.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/ImageSettingsAccordion/ImageSettingsAccordion.tsx
Add some data-testid's so we can more effectively and reliably target the accordions via CSS selectors
=> add some test IDs for accordion targeting

invokeai/app/services/model_install/model_install_default.py, tests/app/services/model_install/test_model_install.py
Renaming the model file to the model name introduces unnecessary contraints on model names.
For example, a model name can technically be any length, but a model _filename_ can be too long.
There are also constraints on valid characters for filenames which shouldn't be applied to model record names.
I believe the old behaviour is a holdover from the old system.
n/a
- On `main`, rename a model. Observe that the model file or folder are renamed. Try renaming to something really long - you'll get an error.
- On this PR, rename a model. Observe taht the model file is not renamed.
n/a
=> fix(mm): do not rename model file when model record is renamed

invokeai/backend/model_manager/probe.py
Currently, the base model probe class doesn't identify a map device on torch loads. Due to this, if a model with gpu tensors is imported, it will attempt to use cuda whether or not it exists on the device
Attempt to install [this model](https://huggingface.co/stablediffusionapi/load_lora_embeddings/blob/6e2d802d3780fd60d3ea8512034341a77ac54007/badhandv4.pt) on a device with no GPU. 
Prior to this change (on MacOS):
After this change (on MacOS):
=> Update probe to always use cpu for loading models

docs/help/FAQ.md, invokeai/app/api/routers/model_manager.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketModelInstall.ts, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/ModelInstallQueue/ModelInstallQueueItem.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/ScanFolder/ScanFolderResultItem.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/ScanFolder/ScanFolderResults.tsx, invokeai/frontend/web/src/services/api/endpoints/models.ts, invokeai/frontend/web/src/services/api/index.ts
A common issue coming up for users who install v4 is missing models.
The root cause is the models aren't in the v3 `models.yaml` and thus don't get migrated to v4.
In v3, the MM would scan the `autoimport` dir and the `models_dir` for models on startup. It would add found models to its memory store, but not write them to `models.yaml`.
There's an easy fix: use `Scan Folder` on the `autoimport` dir and/or the `models_dir` to pick up missing models.
- Added an `inplace` checkbox to the `Scan Folder` UI. This allows users to scan `autoimport`, _disable_ inplace, and have the MM move the models into the invoke-managed models directory.
- Improved the scan folder endpoint to prevent incorrect results when detecting if a found model is already installed or not.
- Added a how-to to the FAQ.
- …
=> feat(mm): restore missing models

docs/installation/010_INSTALL_AUTOMATED.md, installer/lib/installer.py, installer/lib/messages.py
- Remove `CUDA_AND_DML`. This was for onnx, which we have since removed.
- Remove `AUTODETECT`. This option causes problems for windows users, as it falls back on default pypi index resulting in a non-CUDA torch being installed.
- Add more explicit settings for extra index URL, based on the torch website
- Fix bug where `xformers` wasn't installed on linux and/or windows when autodetect was selected
Discord thread where the user ended up with an incompatible version of `torchaudio` (? why this was installed, I do not know) after choosing the autodetect option:
https://discord.com/channels/1020123559063990373/1020123559831539744/1224998262100983829
Also another user at the same time had a problem with autodetect.
Run the `install.sh.in` script to test the installer. 
I tested macOS and …
=> feat(installer): remove extra GPU options

docs/installation/020_INSTALL_MANUAL.md, invokeai/app/services/config/config_default.py
This logic was a bit wonky. It only selected the `venv` parent if there was already an `invokeai.yaml` file in it. Removed this constraint.
https://discord.com/channels/1020123559063990373/1020123559831539744/1224932249737101393
Run `invokeai-web` with an active, fresh virtual environment. It should use the `venv`'s parent as the root dir.
n/a
=> fix(config): fix find_root to use venv parent if no CLI arg or env var

installer/lib/installer.py, invokeai/app/services/config/config_default.py, invokeai/app/services/model_install/model_install_default.py
We have had a few bugs with v4 related to file encodings, especially on Windows.
Windows uses its own character encodings instead of `utf-8`, often `cp1252`. Some characters cannot be decoded using `utf-8`, causing `UnicodeDecodeError`.
There are a couple places where this can cause problems:
- In the installer bootstrap, we install or upgrade `pip` and decode the result, using `subprocess`.
The input to this includes the user's home dir. In #6105, the user had one of the problematic characters in their username. `subprocess` attempts and fails to decode the username, which crashes the installer.
To fix this, we need to use `locale.getpreferredencoding()` when executing the command.
- Similarly, in the model install service and config class, we attempt to load a yaml config file. If a …
=> fix: unicode errors during install or app startup

invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
We need to reset the staging area if we are discarding the last image.
n/a
n/a
n/a
=> fix(ui): discarding last single canvas image breaks canvas

invokeai/app/invocations/latent.py
IdealSizeInvocation failed to execute because `get_config` was not given a proper key from the passed-in UNet.
=> Fix IdealSizeInvocation

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/modelManagerV2/store/modelManagerV2Slice.ts, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelManagerPanel/ModelList.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelManagerPanel/ModelTypeFilter.tsx
Show the refiner models in the MM tab.
Closes #6139
https://discord.com/channels/1020123559063990373/1020123559831539744/1225426267344605245
Revel in the glory of the refiner models shwoing in the mm tab
=> fix(ui): display refiner models in model manager

invokeai/backend/model_manager/load/model_cache/model_locker.py
This corrects a small bug that would result in an additional exception after an OOM error occurred in the model manager. The only effect of the bug was on the log error messages.
=> Fix misplaced lock call in VRAM management routines (minor)

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/public/locales/zh_CN.json, invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasSettingsButtonPopover.tsx, invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts, invokeai/frontend/web/src/features/canvas/store/canvasTypes.ts
**Feature (Frontend, Unified Canvas):** This PR add an option `shouldFitImageSize` to `IAICanvasToolbar` settings, which control the inital `boundingBoxDimensions` to fit initial image size.
Only frontend files are changed.
Switch to Unified Canvas tab, drag and drop an image. When the `shouldFitImageSize` is checked from top toolbar settings, the inital bounding box size will fit to image.
=> feat: Unified Canvas Fit Image Size on Drop

docs/help/FAQ.md, invokeai/backend/model_manager/load/model_cache/model_cache_base.py, invokeai/backend/model_manager/load/model_cache/model_cache_default.py
Remove the new VRAM checking logic from the ModelCache, which prematurely reports insufficient VRAM on Windows.
See #6106 for details.
Closes #6106
Use the generation settings in #6106 on a 12GB GPU on Windows. That combination will trigger the premature OOM on `main`, but will work on this branch (assuming the system has ~3GB free RAM).
n/a
=> fix(mm): premature insufficient VRAM reporting

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/NumberFieldInputComponent.tsx
This data is already in the template but it wasn't ever used.
One big place where this improves UX is the noise node. Previously, the UI let you change width and height in increments of 1, despite the template requiring a multiple of 8. It now works in multiples of 8.
https://github.com/invoke-ai/InvokeAI/assets/4822129/725939cd-86f6-4c2f-ba6a-ffaba1916353
Fields without the multipleOf attribute are unchanged
n/a
n/a
n/a
=> fix(ui): handle multipleOf on number fields

invokeai/backend/model_manager/load/load_default.py, invokeai/backend/util/devices.py
- Allow user-defined precision on MPS.
- Use more explicit logic to handle all possible cases.
- Add comments.
- Remove the app_config args (they were effectively unused, just get the config using the singleton getter util)
https://discord.com/channels/1020123559063990373/1049495067846524939/1226123179303370794
Test bfloat16 precision on MPS on torch 2.3 nightly @Vargol 
Pretty simple change.
n/a
=> feat(backend): clean up choose_precision

invokeai/app/services/shared/invocation_context.py
This PR adds a `get_path` method to the invocation context, so that nodes can access local files. 
Access to the local image path can be useful for nodes that need access to the image file for further processing with external tools (instead of directly dealing with the PIL pixel data).
Fixes #6175
/sa https://discord.com/channels/1020123559063990373/1049495067846524939/1226635058299797666
This PR only adds a new method and does not change any existing code.
=> (feat) add a method to get the path of an image from invocationcontext

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/NodeEditor.tsx, invokeai/frontend/web/src/features/nodes/util/workflow/graphToWorkflow.ts, invokeai/frontend/web/src/features/workflowLibrary/components/LoadWorkflowFromGraphModal/LoadWorkflowFromGraphModal.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryMenu/LoadWorkflowFromGraphMenuItem.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryMenu/WorkflowLibraryMenu.tsx
This is intended for debug usage, so it's hidden away in the workflow library `...` menu. Hold shift to see the button for it.
- Paste a graph (from a network request, for example) and then click the convert button to convert it to a workflow.
- Disable auto layout to stack the nodes with an offset (try it out). If you change this, you must re-convert to get the changes.
- Edit the workflow JSON if you need to tweak something before loading it.
Get the graph from the browser JS console, it's in the `Batch enqueued` log:
You could also get the graph from the network request to enqueue.
Here's a demo using a SDXL canvas inpainting graph (retrieved from JS console after generating on canvas).
Note that for this specific graph, I needed to go and tick `Save to Gallery` on the main "Canvas …
=> feat(ui): add graph-to-workflow debug helper

invokeai/app/invocations/ip_adapter.py, invokeai/app/invocations/latent.py, invokeai/backend/stable_diffusion/diffusers_pipeline.py, invokeai/backend/stable_diffusion/diffusion/conditioning_data.py, invokeai/backend/stable_diffusion/diffusion/custom_atttention.py, invokeai/backend/stable_diffusion/diffusion/regional_ip_data.py, invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py, invokeai/backend/stable_diffusion/diffusion/unet_attention_patcher.py
This PR adds support for applying region masks to IP-Adapter conditioning.
Sample workflow:
Sample results:
I tested the following:
=> Regional IP-Adapter (Backend Only)

invokeai/app/invocations/mask.py
Changed fields to go in w/h x/y order.
The prior ordering of height, then width, and y, then x, doesn't match up with the expected UX. This has been changed.
=> Fix field ordering

invokeai/backend/stable_diffusion/diffusion/regional_ip_data.py, invokeai/backend/stable_diffusion/diffusion/regional_prompt_data.py
This PR fixes a bug with regional prompting and regional IP-Adapter. Prior to this change, using regional prompts with input latent dimensions that aren't evenly divisible by 8 would raise an exception.
This issue was reported here: https://discord.com/channels/1020123559063990373/1049495067846524939/1227274512685338714
The root cause was that region mask downscaling did not mirror the downscaling padding behvaior of the SD/SDXL UNets.
I tested the following:
- Regional prompts, image resolution of 368x696, SD1.5
- Regional prompts, image resolution of 368x696, SDXL
- Regional IP-Adapter, image resolution of 368x696, SD1.5
- Regional IP-Adapter, image resolution of 368x696, SDXL
=> Fix regional prompt mask padding

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/addCommitStagingAreaImageListener.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedCanvas.ts, invokeai/frontend/web/src/features/canvas/components/IAICanvasStagingAreaToolbar.tsx, invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
When a canvas invocation was canceled, the next invocation would use the previous "staging area", including the bounding box settings. This change will make sure that every requested enqueue uses the current bounding box.
Closes https://github.com/invoke-ai/InvokeAI/issues/5969
Put an image on canvas
Set bounding box
Invoke
Cancel before it can finish
Move bounding box
Invoke again
Previously, the second invocation would use the bounding box from invocation #1.  With this fix, it should use the bounding box from invocation #2 as expected.
=> fix(ui): always enqueue with fresh staging area bbox

invokeai/app/invocations/latent.py, invokeai/backend/stable_diffusion/diffusers_pipeline.py
Two fixes here. Both contribute noticeably to the results when inpainting with refiner.
`LatentsField` objects have an optional `seed` field. This should only be populated when the latents are noise, generated from a seed.
`DenoiseLatentsInvocation` needs a seed value for scheduler initialization. It's used in a few places, and there is some logic for determining the seed to use with a series of fallbacks:
- Use the seed from the noise (a `LatentsField` object)
- Use the seed from the latents (a `LatentsField` object - normally it won't have a seed)
- Use `0` as a final fallback
In `DenoisLatentsInvocation`, we set the seed in the `LatentsOutput`, even though the output latents are not noise.
This is normally fine, but when we use refiner, we re-use the those same latents for the refiner …
=> fix(nodes): refined fixes for refiner inpainting

invokeai/app/services/session_processor/session_processor_default.py
When a queue item is finished (completed, canceled, failed), immediately poll the queue for the next queue item.
Closes #6189
Run on `main` and then this branch. Note the delay between a queue item finishing and the next one starting.
n/a
=> fix(queue): poll queue on finished queue item

invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/InstallModelForm.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ControlNetOrT2IAdapterDefaultSettings/ControlNetOrT2IAdapterDefaultSettings.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/MainModelDefaultSettings/MainModelDefaultSettings.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/TriggerPhrases.tsx
Fixes a problem on firefox, at least for me.
I think the type="submit" forced the browser to do a full "submit" action.
=> Remove type="submit" from all tsx files.

invokeai/frontend/web/src/features/metadata/util/parsers.ts, invokeai/frontend/web/src/features/metadata/util/recallers.ts
Currently "recall all" won't remove controls or hrf when they aren't used in the image, updates to set them to false or an empty array when not present. Loras were the same way but caught downstream elsewhere so also updated those
Closes #6210
=> Fix "recall all" when loras, controls, or high res fix are not present

invokeai/frontend/web/src/features/settingsAccordions/components/ImageSettingsAccordion/ImageSettingsAccordion.tsx
remove hires fix badge from settings when using sdxl since hrf isnt enabled with sdxl
Closes #5795
=> remove hires fix badge from settings when using sdxl

invokeai/frontend/web/knip.ts, invokeai/frontend/web/package.json, invokeai/frontend/web/src/common/components/Loading/Loading.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/NoBoardBoard.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/viewMode/EmptyState.tsx, invokeai/frontend/web/src/features/system/components/AboutModal/AboutModal.tsx, invokeai/frontend/web/src/features/system/components/InvokeAILogoComponent.tsx
The other day [someone asked](https://github.com/webpro/knip/issues/591#issuecomment-2053498743) for an example of Knip + Storybook including production mode. GitHub search led me to this repo. And then I was happy to see Knip being used in a great manner :)
One thing struck me, though, so here I am proposing a small change so Knip will stay out of your way even more.
This also enables `knip --production`, which to me seems to reveal some unused exports you might to remove as well, but I'm leaving that up to you.
N/A
CI should still pass. You could consider adding another task to additionally run `knip --production` as well.
N/A
=> Fix up Knip config & enable --production mode

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/flow/edges/InvocationDefaultEdge.tsx, invokeai/frontend/web/src/features/nodes/components/flow/edges/util/makeEdgeSelector.ts, invokeai/frontend/web/src/features/nodes/components/flow/panels/TopRightPanel/WorkflowEditorSettings.tsx, invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts, invokeai/frontend/web/src/features/nodes/store/types.ts
Add setting to render labels with format `Source Node label -> Target Node label` on edges.
https://github.com/invoke-ai/InvokeAI/assets/4822129/0874eb2b-2fc0-4042-b430-190cdc362146
(added during troubleshooting regional prompt graphs)
n/a
n/a
n/a
=> feat(ui): edge labels

invokeai/frontend/web/src/common/hooks/useGlobalHotkeys.ts, invokeai/frontend/web/src/features/gallery/components/Boards/BoardContextMenu.tsx, invokeai/frontend/web/src/features/gallery/components/CurrentImage/CurrentImageButtons.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/MultipleSelectionMenuItems.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx, invokeai/frontend/web/src/features/gallery/hooks/useMultiselect.ts, invokeai/frontend/web/src/features/hrf/components/HrfSettings.tsx, invokeai/frontend/web/src/features/modelManagerV2/hooks/useStarterModelsToast.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/InvocationNodeFooter.tsx, invokeai/frontend/web/src/features/nodes/hooks/useOutputFieldNames.ts, invokeai/frontend/web/src/features/nodes/hooks/useWithFooter.ts, invokeai/frontend/web/src/features/parameters/components/Canvas/InfillAndScaling/ParamInfillColorOptions.tsx, invokeai/frontend/web/src/features/parameters/components/Canvas/InfillAndScaling/ParamInfillMosaicOptions.tsx, invokeai/frontend/web/src/features/queue/components/QueueActionsMenuButton.tsx, invokeai/frontend/web/src/features/queue/components/QueueControls.tsx, invokeai/frontend/web/src/features/queue/components/QueueTabContent.tsx, invokeai/frontend/web/src/features/queue/components/QueueTabQueueControls.tsx, invokeai/frontend/web/src/features/queue/hooks/useQueueFront.ts, invokeai/frontend/web/src/features/settingsAccordions/components/ControlSettingsAccordion/ControlSettingsAccordion.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsLanguageSelect.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsMenu.tsx, invokeai/frontend/web/src/features/system/hooks/useFeatureStatus.ts
A few perf improvements:
- Extraneous rerenders in workflow editor
- Extraneous calculations in useFeatureStatus
- Memoize some state in infill components
n/a
n/a
n/a
=> perf(ui): misc ui improvements

invokeai/app/api_app.py, invokeai/app/services/model_install/model_install_default.py, invokeai/backend/util/catch_sigint.py
PR #6026, which was introduced to allow for ^C interruption during long model loading sequences at startup time, inadvertently interferes with the applications shutdown event from firing correctly (see #6242).  The original PR was written to address an issue with the `scan_models_on_startup` behavior. When using the in-memory database, `scan_models_on_startup`, which defaulted to True, would take a long time to compute the blake3 hash of each model in the `models` directory. Because of the ASGI application's sigINT handling, this process was uninterruptable, and very painful to wait through. However, more recently `scan_models_on_startup` defaults to False, and this is not so much of an issue.
The code in this PR temporarily disables ASGI sigINT handling just before model scanning starts …
=> Re-enable app shutdown actions

invokeai/frontend/web/src/features/nodes/util/graph/addRegionalPromptsToGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildLinearTextToImageGraph.ts, invokeai/frontend/web/src/features/regionalPrompts/components/RegionalPromptingEditor.stories.tsx, invokeai/frontend/web/src/features/regionalPrompts/components/StageComponent.tsx, invokeai/frontend/web/src/features/regionalPrompts/store/regionalPromptsSlice.ts, invokeai/frontend/web/src/features/regionalPrompts/util/bbox.ts, invokeai/frontend/web/src/features/regionalPrompts/util/renderers.ts
- Hook up SD1.5 graphs. HRF doesn't break, but I'm not sure if it really does what you want... I haven't attempted to integrate regions into HRF.
- Fix undo history with layer color picker to group these changes
- Less eye-stabbing default colors
- Some perf improvements to bbox calculations
- You can now select layers with the move tool to drag em around
https://github.com/invoke-ai/InvokeAI/assets/4822129/0a4f0b0a-5408-479e-bd79-fa9ea7807f3c
n/a
Have a play
n/a
=> feat(ui): regional prompting followups

invokeai/app/api/dependencies.py, invokeai/app/services/object_serializer/object_serializer_disk.py, tests/test_object_serializer_disk.py
If the web app exits unexpectedly it may not run its shutdown routine, which removes temporary directories, among other things. At initialization time, this PR checks the base directories used by `ObjectSerializerDisk` for temporary directories left dangling from previous runs, and removes them.
See #6242 for background on a bug that led to a large number of dangling temporary directories in `outputs/tensors`. 
If you have been running earlier versions of `invokeai-web` you probably have a lot of dangling temporary directories in `outputs/tensors`. When you run this PR, these directories should be removed.
=> Remove dangling temporary directories from `outputs/tensors` at startup time

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/src/features/parameters/components/ImageSize/AspectRatioCanvasPreview.tsx, invokeai/frontend/web/src/features/parameters/components/ImageSize/AspectRatioIconPreview.tsx, invokeai/frontend/web/src/features/parameters/components/ImageSize/ImageSize.tsx, invokeai/frontend/web/src/features/parameters/components/ImageSize/constants.ts, invokeai/frontend/web/src/features/regionalPrompts/components/RPLayerListItem.tsx, invokeai/frontend/web/src/features/regionalPrompts/components/StageComponent.tsx, invokeai/frontend/web/src/features/regionalPrompts/hooks/mouseEventHooks.ts, invokeai/frontend/web/src/features/regionalPrompts/store/regionalPromptsSlice.ts, invokeai/frontend/web/src/features/regionalPrompts/util/getLayerBlobs.ts, invokeai/frontend/web/src/features/regionalPrompts/util/renderers.ts, invokeai/frontend/web/src/features/settingsAccordions/components/ImageSettingsAccordion/ImageSizeCanvas.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/ImageSettingsAccordion/ImageSizeLinear.tsx
- Restore non-RCC aspect ratio preview for non-t2i tabs
- Layers default to having a positive prompt
- Hide the 3 buttons when layer has any prompt
- Internal cleanup
- Fix layer arrangement - the bg layer was on top of everything. This coincidentally created the cool transparency effect you were seeing @hipsterusername , but it's not compatible with multiple control layers. We can implement the same effect in a different way though.
n/a
n/a
n/a
=> feat(ui): regional control canvas feedback

invokeai/app/invocations/controlnet_image_processors.py, invokeai/app/invocations/metadata.py, invokeai/app/invocations/t2i_adapter.py, invokeai/app/util/controlnet_utils.py, invokeai/backend/image_util/hed.py, invokeai/backend/image_util/util.py, tests/app/util/test_controlnet_utils.py
While digging into controlnet image processors to understand how to best integrate with regional control, I ran into some poorly documented functions originating from the controlnet repo. In the process of figuring out exactly what they do, I cleaned them up and added comments + type annotations.
Should be no functional changes to the code.
Could try reproducing a controlnet gen before and after (I did test this already).
=> feat: controlnet util refresh

invokeai/backend/model_manager/probe.py, invokeai/configs/stable-diffusion/sd_xl_inpaint.yaml
There are only a couple SDXL inpainting models, and my tests indicate they are not as good as SD1.5 inpainting, but at least we support them now.
- Add the config file. This matches what is used in A1111. The only difference from the non-inpainting SDXL config is the number of in-channels.
- Update the legacy config maps to use this config file.
Closes #6280
I found one SDXL ckpt inpainting model: https://civitai.com/models/245423/juggerxlinpaint
It converts to diffusers with this fix.
n/a
=> feat(mm): support sdxl ckpt inpainting models

invokeai/app/invocations/latent.py
Quick bug I ran into while trying to test the CFG schedulers paper.  
Denoise Latents Invocation already allowed a list[float] input for cfg_scale, but it could not actually use it. The ge=1 would fail to compare int and list.
We already had an extra validator defined to check elements >=1 for both list and float input types. I have added an additional check for len(cfg_scale) == steps when it is a list, which would otherwise cause an index error if they did not match.
=> fix(nodes): denoise latents accepts and validates CFG lists as input

invokeai/app/invocations/controlnet_image_processors.py
There were some invalid constraints with the processors - minimum of 0 for resolution or multiple of 64 for resolution.
Made minimum 1px and no multiple ofs.
https://discord.com/channels/1020123559063990373/1049495067846524939/1235376182246248478
n/a
n/a
=> fix(nodes): fix constraints in cnet processors

README.md, docs/installation/010_INSTALL_AUTOMATED.md, docs/installation/INSTALLATION.md
Updates to the Updating/Installation docs.
Make sure they look good.
n/a
=> Update Installation Docs

invokeai/frontend/web/src/features/controlLayers/store/controlLayersSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx, invokeai/frontend/web/src/features/nodes/util/graph/addControlLayersToGraph.ts, invokeai/frontend/web/src/features/ui/components/InvokeTabs.tsx
Two changes:
[feat(ui): cache control layer mask images](https://github.com/invoke-ai/InvokeAI/commit/de62469fcf6e8bb2841e3aa6d5435abfdefdbd47)
When invoking with control layers, we were creating and uploading the mask images on every enqueue, even when the mask didn't change. The mask image can be cached to greatly reduce the number of uploads.
With this change, we are a bit smarter about the mask images:
- Check if there is an uploaded mask image name
- If so, attempt to retrieve its DTO. Typically it will be in the RTKQ cache, so there is no network request, but it will make a network request if not cached to confirm the image actually exists on the server.
- If we don't have an uploaded mask image name, or the request fails, we go ahead and upload the generated blob
- Update the …
=> feat(ui): cache mask images, fix viewer getting stuck bug

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/gallery/components/ImageViewer/EditorButton.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ViewerButton.tsx
https://github.com/invoke-ai/InvokeAI/assets/54517381/562fda42-38a2-4739-a2e2-f33534c86ee4
Edit: Actually simplified it further .. Right now it's always the viewer. So it doesn't need context active naming at the moment. So for now we go back to how it was but with a switch button visual.
=> feat: improve the switch states of the control layers / viewer area

invokeai/frontend/web/src/features/controlLayers/components/ToolChooser.tsx, invokeai/frontend/web/src/features/controlLayers/store/controlLayersSlice.ts, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImagePreview.tsx, invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts, invokeai/frontend/web/src/features/nodes/util/graph/addInitialImageToLinearGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildAdHocUpscaleGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildGenerationTabGraph.ts
- [fix(ui): do not run HRO if using an initial image](https://github.com/invoke-ai/InvokeAI/commit/49347dbb7cadaa6465e12dda61614f889768e4f8)
- [fix(ui): invalidate mask cache when moving layer](https://github.com/invoke-ai/InvokeAI/commit/d436fb215a8927d7771adfd91f363b5e7ef27a82)
- [feat(ui): close viewer when user switches tabs](https://github.com/invoke-ai/InvokeAI/commit/8a366a65333934530e5051a26fcb938a73ae3f31)
- [fix(ui): do not auto-hide next/prev image buttons](https://github.com/invoke-ai/InvokeAI/commit/aff446f1113e337010ac20288aa4ef77cc01b615)
- [fix(ui): save upscaled images to gallery on canvas tab](https://github.com/invoke-ai/InvokeAI/commit/0432020842e687eca98f7694fbd9c15b2687cb75)
Feedback scattered across discord
Try out each of the fixes/changes if you like. All very …
=> feat(ui): control layers fixes/enhancements

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/galleryImageClicked.ts, invokeai/frontend/web/src/features/controlLayers/components/StageComponent.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/layerStateHooks.ts, invokeai/frontend/web/src/features/controlLayers/hooks/mouseEventHooks.ts, invokeai/frontend/web/src/features/controlLayers/store/controlLayersSlice.ts, invokeai/frontend/web/src/features/controlLayers/util/bbox.ts, invokeai/frontend/web/src/features/controlLayers/util/renderers.ts, invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts
[fix(ui): open viewer on image click, not select](https://github.com/invoke-ai/InvokeAI/commit/b9760b01559e4462807be4161806eecfd4b8b87f) 
- fixes issue where the viewer opens when you click assets
[feat(ui): snap cursor pos when drawing rects](https://github.com/invoke-ai/InvokeAI/commit/1f66879141c370c5c2566059b3b29816791158ee)
- Rects snap to stage edge when within a threshold (10 screen pixels)
- When mouse leaves stage, set last mousedown pos to null, preventing nonfunctional rect outlines
Partially addresses https://github.com/invoke-ai/InvokeAI/issues/6306.
There's a technical challenge to fully address the issue - mouse event are not fired when the mouse is outside the stage. While we could draw the rect even if the mouse leaves, we cannot update the rect's dimensions on mouse …
=> feat(ui): more control layers enhancements

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/features/controlLayers/components/LayerCommon/LayerWrapper.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/mouseEventHooks.ts, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImagePreview.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/FloatingImageViewer.tsx, invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts, invokeai/frontend/web/src/features/gallery/store/types.ts, invokeai/frontend/web/src/features/system/components/HotkeysModal/useHotkeyData.ts, invokeai/frontend/web/src/features/ui/components/InvokeTabs.tsx, invokeai/frontend/web/src/features/ui/components/ParametersPanelTextToImage.tsx
- Fix hotkeys help for viewer
- Fix edge case with mouse events
- Style Settings/Control Layers tabs like tabs (see video)
- Add floating image viewer (see video)
https://github.com/invoke-ai/InvokeAI/assets/4822129/62dde786-73dc-42b4-9961-a41149a7208b
n/a
n/a
n/a
=> feat(ui): control layers styling, floating image viewer

invokeai/frontend/web/src/features/controlLayers/components/IILayer/IILayer.tsx, invokeai/frontend/web/src/features/controlLayers/store/controlLayersSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImagePreview.tsx, invokeai/frontend/web/src/features/nodes/util/graph/addInitialImageToLinearGraph.ts, invokeai/frontend/web/src/features/parameters/components/Canvas/ParamImageToImageStrength.tsx, invokeai/frontend/web/src/features/parameters/components/ImageToImage/ImageToImageStrength.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/ImageSettingsAccordion/ImageSettingsAccordion.tsx
feat(ui): move img2img strength out of advanced on canvas
n/a
n/a
n/a
=> feat(ui): move img2img strength out of advanced on canvas

invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImageButtons.tsx, invokeai/frontend/web/src/features/parameters/hooks/usePreselectedImage.ts
Sets tab to generation tab when someone chooses to send something to img2img initial image
=> switch to generation tab when someone sends to img2img

invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasToolbar.tsx, invokeai/frontend/web/src/features/controlLayers/components/AddLayerButton.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayersPanelContent.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayersSettingsPopover.tsx, invokeai/frontend/web/src/features/controlLayers/components/DeleteAllLayersButton.tsx, invokeai/frontend/web/src/features/controlLayers/components/StageComponent.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ToggleMetadataViewerButton.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ToggleProgressButton.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ViewerToggleMenu.tsx, invokeai/frontend/web/src/features/ui/components/ParametersPanelTextToImage.tsx
- [fix(ui): canvas toolbar centering](https://github.com/invoke-ai/InvokeAI/commit/e3afb3d309c440c2aa037a3bd161578e6c36f181)
- [feat(ui): add invert brush scroll checkbox to control layers settings](https://github.com/invoke-ai/InvokeAI/commit/680a728daf141c55e535860aea007894d1b46de5)
- [feat(ui): add data-testids to control layers components:](https://github.com/invoke-ai/InvokeAI/commit/fd9ec4afab092b891dfbbf73fb52e473ddd8e748)
- Add Layer Menu Button: `control-layers-add-layer-menu-button`
- Delete All Layers Button: `control-layers-delete-all-layers-button`
- CL Layer List: `control-layers-layer-list`
- CL Canvas: `control-layers-canvas`
- Toggle Metadata Button: `toggle-show-metadata-button`
- Toggle Progress Button: `toggle-show-progress-button`
- Toggle Viewer Menu Button: …
=> feat(ui): add `data-testid`s, fix canvas toolbar align, add invert scroll checkbox to CL settings

docs/installation/INSTALL_REQUIREMENTS.md
Moved 'Linux only.' back from under NVIDIA to under AMD for the SDXL hardware requirements.
Documentation change - at some point 'Linux only.' got put under NVIDIA's requirements for SDXL. It's actually meant to be under AMD, just like with the SD 1.5 requirements.
n/a
n/a
go go go
=> Update INSTALL_REQUIREMENTS.md - 'linux only' under AMD for SDXL.

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlAdapterPreprocessor.ts, invokeai/frontend/web/src/features/controlLayers/components/ControlAndIPAdapter/ControlAdapterImagePreview.tsx, invokeai/frontend/web/src/features/controlLayers/store/controlLayersSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/controlLayers/util/controlAdapters.ts, invokeai/frontend/web/src/features/metadata/util/parsers.ts
When a control adapter processor config is changed, if we were already processing an image, that batch is immediately canceled. This prevents the processed image from getting stuck in a weird state if you change or reset the processor at the right (err, wrong?) moment.
- Update internal state for control adapters to track processor batches, instead of just having a flag indicating if the image is processing. Add a slice migration to not break the user's existing app state.
- Update preprocessor listener with more sophisticated logic to handle canceling the batch and resetting the processed image when the config changes or is reset.
- Fixed error handling that erroneously showed "failed to queue graph" errors when an active listener instance is canceled, need to check the abort signal. …
=> fix(ui): CA processor cancellation

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/hooks/useGroupedModelCombobox.ts, invokeai/frontend/web/src/common/hooks/useIsReadyToEnqueue.ts, invokeai/frontend/web/src/features/controlLayers/components/ControlAndIPAdapter/ControlAdapterModelCombobox.tsx, invokeai/frontend/web/src/features/queue/components/InvokeQueueBackButton.tsx, invokeai/frontend/web/src/features/queue/components/QueueButtonTooltip.tsx, invokeai/frontend/web/src/features/queue/components/QueueFrontButton.tsx, invokeai/frontend/web/src/features/ui/components/FloatingParametersPanelButtons.tsx
T2I Adapter requires images be multiples of 64. It's not clear if this is fixable or worth the effort to fix.
Pre-4.2.0, there was a little hack that set the image dimensions to the nearest multiple of 64 when selecting a T2I adapter. This was lost in the CL implementation. I don't like this solution - the user can change the image dimensions at any time and then they'll get a mysterious error when invoking.
To address the issue, an additional pre-Invoke check is added. You cannot click Invoke if you have a T2I layer and the image dimensions are not a multiple of 64.
Another issue apparent in the discord thread is that there is no way to differentiate between T2I adapter models and ControlNet models in the drop-down if the model names don't include "controlnet" or "t2i adapter" in them. …
=> feat(ui): protect against t2i adapters with incompatible image dimensions

invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasToolbar.tsx, invokeai/frontend/web/src/features/canvas/store/canvasTypes.ts
Use translations instead of plain strings.
https://discord.com/channels/1020123559063990373/1054129386447716433/1239181243078279208
The layer select should still work.
n/a
=> fix(ui): use translations for canvas layer select

invokeai/app/api/routers/model_manager.py
Fixes two bugs with model cover images:
- [fix(api): add cover image to update model response](https://github.com/invoke-ai/InvokeAI/commit/a8109b01a7de75fa7b241b2e9649bc8ba8f3ebcf)
Fixes a bug where the image _appears_ to be reset when editing a model.
See: https://old.reddit.com/r/StableDiffusion/comments/1cnx40d/invoke_42_control_layers_regional_guidance_w_text/l3asdej/
- [fix(api): retain cover image when converting model to diffusers](https://github.com/invoke-ai/InvokeAI/commit/7e22fe4f0c7e19ef6edf6490133379977e041a31)
We need to retrieve and re-save the image, because a conversion to diffusers creates a new model record, with a new key.
See: https://old.reddit.com/r/StableDiffusion/comments/1cnx40d/invoke_42_control_layers_regional_guidance_w_text/l3bv152/
^ reddit links
Losing …
=> fix(api): model cover image lost

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedLinear.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedNodes.ts
Make the Invoke button show a loading spinner while queueing.
The queue mutations need to be awaited else the `isLoading` state doesn't work as expected. I feel like I should understand why, but I don't...
n/a
- Use Chrome devtools to simulate a slow network connection (FF devtools can do this, but it seems like you have to refresh the page for the throttling to kick in - chrome lets you change it on the fly)
- Invoke
On `main`, you won't see any loading state on the invoke button. On this PR, you should see loading state until the batch is enqueued.
n/a
=> fix(ui): invoke button shows loading while queueing

invokeai/app/api/routers/app_info.py, invokeai/app/invocations/image.py, invokeai/backend/image_util/safety_checker.py
- Fixes the catch-22 described in #6252.
- Uses better image blurring logic from #6260, the caution image is now centered on the blurred image, and the logic to do this is integrated in the `SafetyChecker` class.
Closes #6252
Supersedes #6260
- Delete the NSFW checker model from `core/convert/stable-diffusion-safety-checker`
- Start Invoke
- The toggle in Settings should not be greyed out
- Enable the NSFW checker in settings 
- Generate something spicy
- The model should download and then blur the image, adding the caution symbol centered in the output
n/a
=> feat(backend): fix nsfw checker catch-22

invokeai/frontend/web/src/features/nodes/util/graph/generation/addSDXLLoRAs.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildGenerationTabSDXLGraph.ts, invokeai/frontend/web/src/features/parameters/components/Advanced/ParamClipSkip.tsx, invokeai/frontend/web/src/features/parameters/types/constants.ts
Uses the same CLIP Skip value for both CLIP1 and CLIP2.
Adjusted SDXL CLIP Skip min/max/markers to be within the valid range (0 to 11).
Closes #4583
- Try it out, with and without LoRAs (which have a minor graph change to support SDXL CLIP Skip). Shouldn't break anything.
- This does not change the default CLIP skip value. Don't think we should make a change like that.
n/a
=> feat(ui): SDXL clip skip

invokeai/frontend/web/src/features/nodes/hooks/useIsValidConnection.ts, invokeai/frontend/web/src/features/nodes/store/util/findConnectionToValidHandle.ts, invokeai/frontend/web/src/features/nodes/store/util/makeIsConnectionValidSelector.ts
Minor fix. The auto-connect logic would let you connect to direct-only inputs (i.e. inputs without handles). Now it doesn't.
n/a
You shouldn't be able to connect to a direct-only input. Not sure if there's a way for this to happen with core nodes only, but it can happen with some community nodes.
n/a
=> feat(ui): prevent connections to direct-only inputs

invokeai/frontend/web/src/features/nodes/components/flow/Flow.tsx, invokeai/frontend/web/src/features/nodes/hooks/useCopyPaste.ts, invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts
[feat(ui): copy/paste input edges when copying node](https://github.com/invoke-ai/InvokeAI/commit/118a58e2f31bd3276194cdf4d77765b3c52b7c43)
- Copy edges to selected nodes on copy
- If pasted with `ctrl/meta-shift-v`, also paste the input edges
https://github.com/invoke-ai/InvokeAI/assets/4822129/f030f118-c731-4a14-8052-862ce7517fb6
Related: #5600
Copy and paste with the hotkeys 
n/a
=> feat(ui): copy/paste input edges when copying node

invokeai/frontend/web/src/common/hooks/useIsReadyToEnqueue.ts
When using T2I Adapter with SDXL base model, images with dimensions that are multiples of 32 are allowed. 
See https://github.com/invoke-ai/InvokeAI/pull/6342#issuecomment-2109912452 for discussion.
You should be prevented from Invoking if:
- SD1.5 model selected + T2I Adapter added + image dimensions are not a multiple of 64
- SDXL model selected + T2I Adapter added + image dimensions are not a multiple of 32
n/a
=> fix(ui): allow image dims multiple of 32 with SDXL and T2I adapter

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/EditableFieldTitle.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputField.tsx, invokeai/frontend/web/src/features/nodes/hooks/useAnyOrDirectInputFieldNames.ts, invokeai/frontend/web/src/features/nodes/hooks/useConnectionInputFieldNames.ts
As of the workflow internal state rework, fields were re-ordered when connecting/disconnecting them. With feedback that this [was jarring](https://discord.com/channels/1020123559063990373/1130288930319761428/1241022691834859621), I've changed the behaviour:
https://github.com/invoke-ai/InvokeAI/assets/4822129/72a32db6-7903-4d34-8112-3d680dd48976
Also sneaking in a fix for issue with field titles not updating correctly.
https://discord.com/channels/1020123559063990373/1130288930319761428/1241022691834859621
Try it out I suppose. There's some minor jank with the positioning of handles during a connection. This is an [upstream issue](https://github.com/xyflow/xyflow/issues/3983).
n/a
=> fix(ui): field ordering & display

invokeai/app/api/routers/images.py, invokeai/app/services/image_files/image_files_base.py, invokeai/app/services/image_files/image_files_disk.py, invokeai/app/services/image_records/image_records_base.py, invokeai/app/services/image_records/image_records_sqlite.py, invokeai/app/services/images/images_base.py, invokeai/app/services/images/images_default.py, invokeai/app/services/shared/invocation_context.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedLinear.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/workflowLoadRequested.ts, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataGraphTabContent.tsx, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataViewer.tsx, invokeai/frontend/web/src/features/nodes/store/actions.ts, invokeai/frontend/web/src/features/workflowLibrary/components/LoadWorkflowFromGraphModal/LoadWorkflowFromGraphModal.tsx, invokeai/frontend/web/src/features/workflowLibrary/hooks/useGetAndLoadEmbeddedWorkflow.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useGetAndLoadLibraryWorkflow.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useLoadWorkflowFromFile.tsx, invokeai/frontend/web/src/services/api/endpoints/images.ts, invokeai/frontend/web/src/services/api/hooks/useDebouncedImageWorkflow.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts
Note: This PR includes a failed attempt at this feature. The failed attempt was reverted.
[feat(ui): store graph in image metadata](https://github.com/invoke-ai/InvokeAI/pull/6384/commits/aecb224d1985b0b13ad7f6c5f3e30946d3dba07f)
[aecb224](https://github.com/invoke-ai/InvokeAI/pull/6384/commits/aecb224d1985b0b13ad7f6c5f3e30946d3dba07f)
The previous super-minimal implementation had a major issue - the saved workflow didn't take into account batched field values. When generating with multiple iterations or dynamic prompts, the same workflow with the first prompt, seed, etc was stored in each image.
As a result, when the batch results in multiple queue items, only one of the images has the correct workflow - the others are mismatched.
To work around this, we can store the _graph_ in the …
=> feat(ui): store workflow in generation tab images

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlAdapterPreprocessor.ts
- Fixes an edge case where we'd do processing unnecessarily
- Fixes a minor bug when clearing processor.
n/a
- Try changing the control model from ControlNet Canny to T2I Canny (leave processor settings default). Should not re-process the image.
- Open the JS console. Clear the processor. There should be no errors talking about config being null.
n/a
=> fix(ui): control adapter auto-process jank

invokeai/app/api/routers/images.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/canvasSavedToGallery.ts, invokeai/frontend/web/src/features/nodes/util/graph/canvas/buildCanvasImageToImageGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/canvas/buildCanvasInpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/canvas/buildCanvasOutpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/canvas/buildCanvasSDXLImageToImageGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/canvas/buildCanvasSDXLInpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/canvas/buildCanvasSDXLOutpaintGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/canvas/buildCanvasSDXLTextToImageGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/canvas/buildCanvasTextToImageGraph.ts, invokeai/frontend/web/src/services/api/endpoints/images.ts, invokeai/frontend/web/src/services/api/schema.ts
Store canvas objects in the metadata for both images generated by canvas graphs _and_ images created when clicking the `Save to Gallery` button.
Canvas objects (images, brush strokes, shapes, masks, etc) are stored as is. There is no recall capability - this is planned _only_ for a future canvas v2, based on the control layers renderer and state management.
I don't think we've had any requests for canvas metadata without the ability to recall, so this doesn't resolve any open issues.
- Generate on canvas. Every generation, in every mode - txt2img, img2img, inpaint, outpaint, sd1 & sdxl - should have a `_canvas_objects` property in the metadata.
- Click `Save to Gallery` on canvas after generating. Should have `_canvas_objects` property in the metadata.
n/a
=> feat: write-only canvas metadata

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/hooks/useIsReadyToEnqueue.ts
It now indicates the correct dimension of 64 (SD1.5) or 32 (SDXL) - before was hardcoded to 64.
https://github.com/invoke-ai/InvokeAI/assets/4822129/5479efc9-3a1a-4821-96ad-16ccd2db8eb6
n/a
n/a
n/a
=> fix(ui): fix t2i adapter dimensions error message

invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts, invokeai/frontend/web/src/features/nodes/types/workflow.ts, invokeai/frontend/web/src/features/nodes/util/workflow/buildWorkflow.ts
- [fix(ui): ensure invocation edges have a type](https://github.com/invoke-ai/InvokeAI/commit/c88b6703eed22dbbdc84c6a2cda69d8998936843)
- [fix(ui): store hidden state of edges in workflows](https://github.com/invoke-ai/InvokeAI/commit/f70ee689e396ce0822d4343d49f1e99a57b4bcf7)
This prevents a minor visual bug where collapsed edges between collapsed nodes didn't display correctly on first load of a workflow.
https://discord.com/channels/1020123559063990373/1149513625321603162/1241849984140447886
- Save and then load a workflow, its edges should be saved.
- Collapse two connected nodes so their edges are in the collapsed state. Save and load the workflow, the collapsed edge state should be retained (e.g. grey line w/ a number over it if there were multiple edges).
n/a
=> fix(ui): workflow edges not saved

invokeai/frontend/web/src/features/controlLayers/store/controlLayersSlice.ts
This change fixes the issue where changing the image used for image to image resets the denoising strength and opacity to default values of 0.75 and 1 respectively.
=> [#6351] ui: retain denoise strength and opacity when changing image

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/workflowLoadRequested.ts, invokeai/frontend/web/src/features/nodes/util/workflow/validateWorkflow.test.ts, invokeai/frontend/web/src/features/nodes/util/workflow/validateWorkflow.ts, invokeai/frontend/web/src/services/api/hooks/accessChecks.ts
These fields are reset back to `undefined` if not accessible. A warning toast is showing, and in the JS console, the full warning message is logged.
n/a
There are tests for this functionality. To test manually:
- Create a board
- Create a workflow with an image resize node
- Set the board to the new board
- Set an image
- Check the data tab in the bottom left panel of the workflow editor and check that the value for the board and image are populated
- Save the workflow
- Delete the board and image
- Refresh the page
- Re-load the workflow
- Check the data tab in bottom left panel of the workflow editor and check that the value for the board and image are now undefined
Then do the same thing, but with the model loader. You'll need to delete the model between the reloads.
n/a
=> feat(ui): workflow resource check

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/CALayer/CALayer.tsx, invokeai/frontend/web/src/features/controlLayers/components/IILayer/IILayer.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPALayer/IPALayer.tsx, invokeai/frontend/web/src/features/controlLayers/components/LayerCommon/LayerVisibilityToggle.tsx, invokeai/frontend/web/src/features/controlLayers/components/RGLayer/RGLayer.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/layerStateHooks.ts, invokeai/frontend/web/src/features/controlLayers/store/controlLayersSlice.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addControlLayers.ts
- Regional guidance layers were missing a check for the `isEnabled` flag and were always applied, even when disabled.
- Changed messaging from "visibility" to "enabled", which is what the checkboxes do
Closes #6424
- Generate an image w/ a regional guidance layer and manual seed
- Disable the layer and generate again
- Should be a different image created
- Metadata should correctly show only the enabled layers
n/a
=> fix(ui): regional guidance layers not disabling correctly

invokeai/app/api/routers/session_queue.py, invokeai/app/services/session_processor/session_processor_default.py, invokeai/app/services/session_queue/session_queue_base.py, invokeai/app/services/session_queue/session_queue_sqlite.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketQueueItemStatusChanged.ts
[feat(app): update queue item's session on session completion](https://github.com/invoke-ai/InvokeAI/commit/e9bbbabdfddc885a24e2e1bf0ee89a5557036472)
The session is never updated in the queue after it is first enqueued. As a result, the queue detail view in the frontend never never updates and the session itself doesn't show outputs, execution graph, etc.
We need a new method on the queue service to update a queue item's session, then call it before updating the queue item's status.
Queue item status may be updated via a session-type event _or_ queue-type event. Adding the updated session to all these events is a hairy - simpler to just update the session before we do anything that could trigger a queue item status change event:
- Before calling `emit_session_complete` in the processor …
=> feat: update queue items session on complete

pyproject.toml
Hello everyone,
it's been a while! :D Hope y'all having a great day.
This PR updates the following dependencies:
accelerate 0.29.2 -> 0.30.1
clip_anytorch 2.5.2 -> 2.6.0
transformers 4.39.3 -> 4.41.0
safetensors 0.4.2 -> 0.4.3
huggingface-hub 0.22.2 -> 0.23.1
I was not able to find any regressions in the updated packages. I am happy for people to test.
Otherwise, we are good to go. I will create a separate PR for a possible pytorch 2.3 update, as xformers has been updated to 2.3 and diffusers seems to be happy.
Greetings
Whenever you are ready!
=> Update deps to their lastest versions

invokeai/app/services/events/events_common.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketGeneratorProgress.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationError.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationStarted.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/events/types.ts
I had removed the full invocation from the event payloads. Shouldn't have done that.
> Note about the huge diff: I had a different version of pydantic installed at some point, which slightly altered a _ton_ of schema components. This typegen was done on the correct version of pydantic and un-does those alterations, in addition to the intentional changes to event models.
n/a
n/a
n/a
=> feat(events): restore full invocation in event payloads

invokeai/app/api/sockets.py, invokeai/app/services/events/events_common.py
This allows for events to be dispatched using dicts as payloads, and have the dicts validated as pydantic schemas.
Also fixed a minor typing issue.
n/a
n/a
n/a
=> feat(events): register event schemas

invokeai/app/services/events/events_common.py
Two fixes for pydantic events handling.
n/a
n/a
n/a
=> feat(events): add missing classvar to events, add validators for deserialization of events

invokeai/backend/textual_inversion.py
- Updated the documentation for `TextualInversionManager`
- Updated the `self.tokenizer.model_max_length` access to work with the latest transformers version. Thanks to @skunkworxdark for looking into this here: https://github.com/invoke-ai/InvokeAI/issues/6445#issuecomment-2133098342
Closes #6445 
I tested with `transformers==4.41.1`, and compared the results against a recent InvokeAI version before updating tranformers - no change, as expected.
=> Update TI handling for compatibility with transformers 4.40.0

invokeai/backend/model_manager/load/model_cache/model_locker.py
When lazy offloading is false, the model locker's `unlock()` method was asking `offload_unlocked_models` to free up VRAM sufficient to load the model that is being unlocked. This was incorrect. The method should be called with a size of 0, which will have the effect of removing models until VRAM is less than or equal to `max_vram_cache`.
Please see https://github.com/invoke-ai/InvokeAI/pull/6439#pullrequestreview-2081213194 for @RyanJDick 's discovery of this bug.
=> [MM]Fix bug in offload_unlocked_models() call

invokeai/frontend/web/src/features/controlLayers/util/controlAdapters.ts
The weights were limited to 0 to 1 for control adapter and ip adapters. This prevented metadata from validating and loading. Constraints widened to -1 to 2, which matches the UI input constraints.
https://discord.com/channels/1020123559063990373/1149506274971631688/1245345621393801278
- Use a control adapter or ip adapter with weight below 0 or above 1
- You should be able to recall the layer
n/a
=> fix(ui): remove overly strict constraints on control adapter weight

Makefile, invokeai/app/api_app.py, invokeai/app/invocations/baseinvocation.py, invokeai/app/services/events/events_common.py, invokeai/app/services/shared/graph.py, invokeai/app/util/custom_openapi.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlAdapterPreprocessor.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlNetImageProcessed.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/inspector/InspectorOutputsTab.tsx, invokeai/frontend/web/src/features/nodes/types/common.ts, invokeai/frontend/web/src/features/nodes/util/graph/buildNodesGraph.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts, invokeai/frontend/web/src/services/events/types.ts, pyproject.toml, scripts/generate_openapi_schema.py, tests/test_node_graph.py
Fix some issues with openapi schema generation. See commits for details.
https://discord.com/channels/1020123559063990373/1049495067846524939/1245141831394529352
App should work, workflows should work.
n/a
=> fix: openapi stuff

invokeai/frontend/web/src/features/metadata/util/handlers.ts, invokeai/frontend/web/src/features/metadata/util/modelFetchingHelpers.ts
Two metadata recall fixes:
- Fallback to recalling models by name, base and type when the model's key no longer exists. This allows models that were installed, deleted, and re-installed with the same name to be recalled.
- Set the prompt concat flag correctly when recalling prompts.
Closes #6478
Test model recall:
- Generate w/ whatever model - can be main, LoRA, whatever
- Note the model's name
- Delete the model
- Reinstall the model
- Ensure the reinstalled model has the same name as you noted earlier
- Check metadata for the image, it should show the model and let you recall it
Test prompt concat:
- Generate an image with concat enabled
- Disable concat
- Recall prompts/all - concat should enable
- Generate an image with concat disabled and with style prompts that are different from …
=> fix(ui): metadata recall fixes

invokeai/app/invocations/latent.py
- Pass the seed from `latents_a` to the output latents. Fixed an issue where using `BlendLatentsInvocation` could result in different outputs during denoising even when the alpha or slerp weight was 0.
`LatentsField` has an optional `seed` field. During denoising, if this `seed` field is not present, we **fall back to 0 for the seed**. The seed is used during denoising in a few ways:
The seed is used in two places in `invokeai/app/invocations/latent.py`.
The `get_scheduler()` utility function has special handling for `DPMSolverSDEScheduler`, which appears to need a seed for deterministic outputs.
`DenoiseLatentsInvocation.init_scheduler()` has special handling for schedulers that accept a generator - the generator needs to be seeded in a particular way. At the time of this commit, these …
=> fix(nodes): blend latents with weight=0 with DPMSolverSDEScheduler

invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/DataViewer.tsx, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataGraphTabContent.tsx, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataViewer.tsx, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataWorkflowTabContent.tsx
Added the image UUID as a prefix for the various JSON files generated from the image metadata interface
Closes #6469
Go to "info" for a generated image, switch to "Metadata", "Image Details", etc. and click the JSON download button. The downloaded file should now have the image UUID with an underscore and then the JSON label itself. If there is no UUID (no image_name), the fallback will just be the label.
N/A
=> Prefixed JSON filenames with the image UUID

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/controlAdapterPreprocessor.ts, invokeai/frontend/web/src/features/controlLayers/components/CALayer/CALayerControlAdapterWrapper.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlAndIPAdapter/ControlAdapter.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlAndIPAdapter/ControlAdapterImagePreview.tsx
If a processed control image is deleted and the page refreshed, the un-processed control image would be reset. This problem does not occur when recalling metadata - only affects active controlnets in the UI on page load.
- Add separate callbacks for errors when loading the control image and processed image
- Selectively clear missing images
- Update auto-process to re-process if the processed image is reset for any reason
n/a
n/a
n/a
- [z] _The PR has a short but descriptive title, suitable for a changelog_
=> fix(ui): re-process control image if processed image is missing on page load

invokeai/app/services/download/download_default.py, invokeai/app/services/events/events_base.py, invokeai/app/services/model_install/model_install_default.py, invokeai/invocation_api/__init__.py
Carry over from previous PR's. @lstein @RyanJDick 
- Fixes incorrect SchedulerOutput import from #6491
- Resolve duplicate imports pertaining to `TYPE_CHECKING` which now were made at the file level. If this needs to be the other way, then it needs to be flipped. For now, I applied resolution to be at file load rather than the bool check.
=> fix: Some imports from previous PR's

invokeai/app/invocations/constants.py, invokeai/app/invocations/create_denoise_mask.py, invokeai/app/invocations/create_gradient_mask.py, invokeai/app/invocations/denoise_latents.py, invokeai/app/invocations/image_to_latents.py, invokeai/app/invocations/latents_to_image.py
`DEFAULT_PRECISION` is a `torch.dtype`. Previously, `DEFAULT_PRECISION` was compared to a `str` (`"float32"`) in several places to determine the default precision for an invocation. Due to the type mismatch, these comparisons would always resolve to `False`. This PR fixes all of these comparison type mismatches.
This is a bugfix that results in a change to the default behaviour. In practice, this should not change the behaviour for many users, because it only causes a change for users that have configured float32 as their default precision (or have an old GPU without float16 support).
=> Fix `DEFAULT_PRECISION` handling

invokeai/app/api/routers/model_manager.py, invokeai/app/services/events/events_base.py, invokeai/app/services/events/events_common.py, invokeai/app/services/model_install/model_install_default.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketModelInstall.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/events/actions.ts, invokeai/frontend/web/src/services/events/types.ts, tests/app/services/model_install/test_model_install.py
added route to install huggingface models from model marketplace
test by going to http://localhost:5173/api/v2/models/install/huggingface?source=${hfRepo}
=> added route to install huggingface models from model marketplace

invokeai/app/invocations/denoise_latents.py, invokeai/backend/model_manager/probe.py, invokeai/backend/util/silence_warnings.py, invokeai/backend/util/util.py
No functional changes, just cleaning some things up as I touch the code. This PR cleans up the `SilenceWarnings` context manager:
- Fix type errors
- Enable SilenceWarnings to be used as both a context manager and a decorator
- Remove duplicate implementation
- Check the initial verbosity on `__enter__()` rather than `__init__()`
- Save an indentation level in DenoiseLatents
I generated an image to confirm that warnings are still muted.
=> Tidy `SilenceWarnings` context manager

invokeai/app/services/config/config_default.py, invokeai/app/services/session_queue/session_queue_sqlite.py
Simple fix to clear problematic queues on startups leading to crashes by adding `empty_queue_on_startup` config to `invokeai.yaml`
Closes #6333
=> [#6333] Add clear_queue_on_startup config to clear problematic queues

invokeai/backend/model_manager/load/model_loaders/vae.py, invokeai/backend/model_manager/probe.py
This adds support for probing and converting SDXL VAE checkpoint files. It is a lame solution because the base-determining method simply looks for the pattern "SDXL" in the filename. A quick inspection of SD1 vs SDXL VAEs found no differences in the state dict weights, so these can't be used as the basis of discrimination.
Conversion seems to work using the diffusers library. However, the need to convert will be obsoleted by PR #6510 .
See Discord thread at https://discord.com/channels/1020123559063990373/1020123559831539744/1253157322377793557
I've tested on the Civitai VAE https://civitai.com/models/140686/fix-fp16-errors-sdxl-lower-memory-use-sdxl-vae-fp16-fix-by-madebyollin. The results aren't great - the colors are washed out - but I don't know if this is a problem with the VAE or …
=> [MM] Add support for probing and loading SDXL VAE checkpoint files

invokeai/backend/model_hash/hash_validator.py
=> Update prevention exception message

invokeai/app/invocations/denoise_latents.py, invokeai/app/invocations/tiled_multi_diffusion_denoise_latents.py, invokeai/backend/stable_diffusion/diffusers_pipeline.py, invokeai/backend/stable_diffusion/multi_diffusion_pipeline.py
https://github.com/invoke-ai/InvokeAI/pull/6522 introduced a change in behavior in cases where start/end were set such that there are 0 timesteps. This PR reverts that change.
cc @StAlKeR7779 
Run with euler, 5 steps, start: 0.0, end: 0.05. I ran this test before #6522, after #6522, and on this branch. This branch restores the behavior to pre-#6522 i.e. noise is injected even if no denoising steps are applied.
=> Fix handling handling of 0-step denoising process

invokeai/backend/model_manager/starter_models.py
Updates the starter controlnets to the improved models released by Xinsir
Can validate that the starter models are listed and install successfully.
=> Update controlnet starters

invokeai/app/services/image_records/image_records_sqlite.py
Python 3.11 has a wonderfully devious breaking change where _sometimes_ using enum classes that inherit from `str` or `int` do not work the same way as they do in 3.10 when used within string formatting/interpolation.
This breaks the new gallery sort queries. The fix is to use `order_dir.value` instead of `order_dir` in the query.
This was not an issue during development because the feature was developed w/ python 3.10.
Thanks to @JPPhoto for reporting and troubleshooting: https://discord.com/channels/1020123559063990373/1149513625321603162/1256211815982039173
JP's fancy python 3.11 system should work on this PR.
n/a
=> fix(app): fix SQL query w/ enum for python 3.11

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/gallery/components/Boards/BoardContextMenu.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/GalleryBoard.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/NoBoardBoardContextMenu.tsx
* Do not show disabled "auto-add" menu item in context menu if click to auto-add is enabled
* Show "Selected for auto-add" instead of disabled menu item if board is already selected for auto-add
* Allow archived boards to be selected for auto-add
=> (ui) clarify auto-add logic

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/index.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/galleryOffsetChanged.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketio/socketInvocationComplete.ts, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryPagination.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GallerySearch.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GallerySelectionCountTag.tsx, invokeai/frontend/web/src/features/gallery/components/NextPrevImageButtons.tsx, invokeai/frontend/web/src/features/gallery/hooks/useGalleryHotkeys.ts, invokeai/frontend/web/src/features/gallery/hooks/useGalleryNavigation.ts, invokeai/frontend/web/src/features/gallery/hooks/useGalleryPagination.ts, invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts
[feat(ui): restore loading spinner in search box](https://github.com/invoke-ai/InvokeAI/commit/78663c6c3af5d95c9fa86fe2056c7b4dbfaf8f58)
@maryhipp you were right, after trying loading bars and different placements, this feels like the best place for it.
[feat(ui): gallery image selection ux](https://github.com/invoke-ai/InvokeAI/commit/5ed185cda379f680da967f0ddd42af4eec736ddb)
The selection logic is a bit complicated. We have image selection and pagination, both of which can be triggered using the mouse or hotkeys. We have viewer image selection and comparison image selection, which is determined by the alt key.
This change ties the room together with these behaviours:
- Changing the page using pagination buttons never changes the selection.
- Changing the selected image using arrows may …
=> feat(ui): gallery ux

invokeai/app/invocations/fields.py, invokeai/app/invocations/image_to_latents.py, invokeai/app/invocations/latents_to_image.py, invokeai/backend/stable_diffusion/vae_tiling.py, tests/backend/stable_diffusion/test_vae_tiling.py
- This PR exposes a `tile_size` field on `ImageToLatentsInvocation` and `LatentsToImageInvocation`.
- Setting `tile_size = 0` preserves the default behaviour.
- This feature is primarily intended to support upscaling workflows that require VAE encoding/decoding high resolution images. In the future, we may want to expose the tile size as a global application config, but that's a separate conversation.
- As a general rule, larger tile sizes produce better results at the cost of higher memory usage.
Original (5472x5472)
VAE roundtrip with 512x512 tiles (note the discoloration)
VAE roundtrip with 1024x1024 tiles (some discoloration still present, but less severe than at 512x512)
Related: #6144 
No special instructions.
=> Make the VAE tile size configurable for tiled VAE

invokeai/app/services/download/download_default.py
PR #6132 inadvertently broke the system for submitting access tokens that match the source URL's regular expression. This PR fixes the issue.
Nobody seems to have noticed this problem!
Be sure to set up a civitai or huggingface access token in `invokeai.yaml`. E.g.:
```
remote_api_tokens:
- url_regex: huggingface\.co
token: hf_xyxyxyxyxyxyx
- url_regex: civitai\.com
token: abcabcabcabc
```
Then attempt to download a restricted model. It should succeed. If you remove or change the access token in the config, the download should fail.
=> Fix access token lookup for model downloads

invokeai/backend/ip_adapter/ip_adapter.py, invokeai/backend/model_manager/load/model_cache/model_cache_default.py, invokeai/backend/model_manager/load/model_util.py, invokeai/backend/textual_inversion.py
This PR fixes a regression that caused the following models to be treated as having size 0 in the model cache: `(TextualInversionModelRaw, IPAdapter, LoRAModelRaw)`.
Changes:
- Call the correct model size calculation for all supported model types.
- Log an error message if an unexpected model type is loaded, to prevent similar regressions in the future.
I tested the following features and verified that no models fell back to using a size of 0 unexpectedly:
- Test-to-image
- Textual Inversion
- LoRA
- IP-Adapter
- ControlNet
(All tested with both SD1.5 and SDXL.)
I compared the model cache switching behavior before and after this change with a large number of LoRAs (10). Since LoRAs are small compared to the main models, the changes in behaviour are minimal. Nonetheless, it makes sense to …
=> Fix some models treated as having size 0 in the model cache

invokeai/app/invocations/constants.py, invokeai/app/invocations/denoise_latents.py, invokeai/app/invocations/scheduler.py, invokeai/app/invocations/tiled_multi_diffusion_denoise_latents.py, invokeai/backend/model_manager/config.py, invokeai/backend/stable_diffusion/schedulers/schedulers.py, invokeai/invocation_api/__init__.py, tests/backend/stable_diffusion/schedulers/test_schedulers.py
This PR makes the following changes:
- Moves `SCHEDULER_NAME_VALUES` to `invokeai/backend/`. Previously, it was located in `invokeai/app/invocations/`. In its old location, it was causing bidirectional imports between `invokeai/backend/` and `invokeai/app/invocations/` and thus contributing to circular import issues. This change helps to move towards having `invokeai/app/invocations/` import from `invokeai/backend/` and not the other way around. (More info on why this is important here: https://github.com/invoke-ai/InvokeAI/issues/6575)
- Fixes all the static type checking errors caused by doing `Literal[tuple(SCHEDULER_MAP.keys())]`.
An issue was raised on Discord where custom nodes fail to import due to a circular import error: …
=> Fix circular imports related to SCHEDULER_NAME_VALUES

installer/templates/invoke.bat.in
This commit corrects a broken link on line 16 that was pointing to the latest release but causing a 404 error (page not found) when clicked. The issue was identified as a trailing dot at the end of the URL, which has now been removed. This ensures users can access the intended latest release page.
=> Fixed 404 error on latest release link (line 16):

invokeai/backend/model_manager/load/model_util.py
Demote error log to warning for models treated as having size 0.
Closes #6587 
I looked into handling ESRGAN model sizes properly. They load a state_dict with a bit of an unusual nested-dict structure. Rather than figure out how to accurately calculate their size, we can just wait for https://github.com/invoke-ai/InvokeAI/pull/6556. ESRGAN model size handling should work properly when loaded through that pathway.
Loaded an ESRGAN model, and confirmed that the warning log is at the warning level.
No special instructions.
=> Demote error log to warning for models treated as having size 0

README.md, docker/.env.sample, docker/README.md, docker/docker-compose.yml, docker/docker-entrypoint.sh, docker/run.sh, docs/installation/040_INSTALL_DOCKER.md
- Adds instructions on running the official images to the main README, to the `docker/README.md`, and to the mkdocs documentation
- changes the name of docker-compose profile to `invokeai-cuda`, as suggested in https://github.com/invoke-ai/InvokeAI/pull/6043
- ensures that the `chown` command in docker entrypoint script does not break on read-only filesystems
Closes #6264 
I tested following these docs on a Linux system, but some testing on Windows with WSL would be helpful.
1. Try the `docker run` commands from the README, including working directory persistence. Try mounting an existing InvokeAI root dir into the container, as described in the README.
2. Test the `run.sh` script and `docker compose` commands
=> Overhaul docker documentation and fix minor bugs

docs/contributing/MODEL_MANAGER.md, invokeai/app/api/dependencies.py, invokeai/app/services/model_records/model_records_sql.py, tests/app/services/model_records/test_model_records_sql.py, tests/backend/model_manager/model_manager_fixtures.py
This PR changes the handling of invalid model configs in the DB to log a warning rather than crashing the app.
This change is being made in preparation for some upcoming new model additions. Previously, if a user rolled back from an app version that added a new model type, the app would not launch until the DB was fixed. This PR changes this behaviour to allow rollbacks of this type (with warnings).
**Keep in mind that this change is only helpful to users _rolling back to a version that has this fix_. I.e. it offers no help in the first version that includes it.**
1. Run the Spandrel model branch, which adds a new  model type https://github.com/invoke-ai/InvokeAI/pull/6556.
2. Add a spandrel model via the model manager.
3. Rollback to main. The app will crash on launch due to the invalid …
=> Do not crash if there are invalid model configs in the DB

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/addArchivedOrDeletedBoardListener.ts, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardsList.tsx, invokeai/frontend/web/src/services/api/endpoints/images.ts
- Prevent cutoff of last board in the list when scrolling down to the bottom.
- Fix handling of selected and auto-add boards when a board is archived or deleted.
- Do not invalidate an image's query cache when it was deleted. This was causing spurious `getImageDTO` requests and console errors like `[2024-07-12 10:46:50,049]::[InvokeAI]::ERROR --> Image record not found`.
- Closes #6598 
- Board list should display correctly.
- Should be able to generate/delete on archived boards (when they are visible in the list).
- Delete a big image on windows and confirm it deletes correctly.
Once we are sure the deletion issue is resolved we can do another release. May also want to get the intermediates count issue resolved first.
=> fix(ui): gallery followups

invokeai/app/api/routers/images.py, invokeai/app/api_app.py
[fix(api): deleting large images fails](https://github.com/invoke-ai/InvokeAI/commit/f74f400515aee84375b8741f82233b045bf26d3b)
This issue is caused by a race condition. When a large image is served to the client, it is done using a streaming `FileResponse`. This concurrently serves the image straight from disk. The file is kept open by FastAPI until the image is fully served.
When a user deletes an image before the file is done serving, the delete fails because the file is still held by FastAPI.
To reproduce the issue:
- Create a very large image (8k reliably creates the issue).
- Create a smaller image, so that the first image in the gallery is not the large image.
- Refresh the app. The small image should be selected.
- Select the large image and immediately delete it. You have to be …
=> fix(api): delete image race condition

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageDeletionListeners.ts
fix(ui): clear selection when deleting last image in board
Discord report: https://discord.com/channels/1020123559063990373/1149506274971631688/1261802456573280329
Individually delete images in a board until it is empty. When you delete the last image, the selection should be cleared (no image selected).
n/a
=> fix(ui): clear selection when deleting last image in board

invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardsList.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGalleryContent.tsx
Fixes an issue where the last board got cut off when the search was open.
https://discord.com/channels/1020123559063990373/1149506274971631688/1262184185091723274
Boards list should display correctly w/ search open or closed.
n/a
=> fix(ui): boards cut off when search open

invokeai/backend/ip_adapter/ip_adapter.py, invokeai/backend/lora.py, invokeai/backend/model_manager/load/model_cache/model_cache_default.py, invokeai/backend/model_patcher.py, invokeai/backend/onnx/onnx_runtime.py, invokeai/backend/raw_model.py, invokeai/backend/textual_inversion.py, invokeai/backend/util/devices.py
In #6490 we enabled non-blocking torch device transfers throughout the model manager's memory management code. When using this torch feature, torch attempts to wait until the tensor transfer has completed before allowing any access to the tensor. Theoretically, that should make this a safe feature to use.
This provides a small performance improvement but causes race conditions in some situations. Specific platforms/systems are affected, and complicated data dependencies can make this unsafe.
- Intermittent black images on MPS devices - reported on discord and #6545, fixed with special handling in #6549.
- Intermittent OOMs and black images on a P4000 GPU on Windows - reported in #6613, fixed in this commit.
On my system, I haven't experience any issues with generation, but targeted …
=> fix(backend): revert non-blocking device transfer

invokeai/backend/model_manager/starter_models.py
This PR adds some spandrel upscale models to the starter model list.
In the future we may also want to add:
- Some DAT models (https://drive.google.com/drive/folders/1iBdf_-LVZuz_PAbFtuxSKd_11RL1YKxM)
I installed the starter models via the model manager UI, and tested that I could use them in a workflow.
=> Add Spandrel upscale starter models

invokeai/backend/model_manager/load/model_cache/model_cache_default.py
The model patching/unpatching optimization introduced in #6439 does not work when image generation is executing on the CPU, leading to scrambled images on subsequent generations. This PR disables the optimization when running on CPU. 
See #6559 and a PR that solves the problem with a config option #6628 
Using CPU rendering, apply a LoRA and run the generation twice. On the second run, the image should not be scrambled looking.
=> Fix model unpatching process when running on CPU

invokeai/app/invocations/tiled_multi_diffusion_denoise_latents.py, invokeai/backend/stable_diffusion/multi_diffusion_pipeline.py
This PR adds gradient blending between tiles during MultiDiffusion denoising. Previously, no gradient was applied and the sharp cut-off caused visible seams in some case (particularly evident on smooth single-color regions).
Upsampled to 2240x1872
Upsampled to 4480x3744
Upsampled to 2240x1872
Upsampled to 4480x3744
- The non-gradient blending was based on the official MultiDiffusion implementation that accompanied the paper - this deviates from that.
- Other ideas that would likely help with this problem:
- Large overlaps between tiles so that each tile edge is covered by multiple other tiles. (This is what the official MultiDiffusion implementation seems to do.)
- Jitter the tile locations so that seams aren't in the same place in every step.
As seen in the sample images, there is a …
=> Add gradient blending to tile seams in MultiDiffusion

pyproject.toml
This is required to fix an issue in fastapi-events OpenTelemetry implementation. https://github.com/melvinkcx/fastapi-events/issues/63. PR fix is open but not yet merged: https://github.com/melvinkcx/fastapi-events/pull/64
- The diff in this version bump does not affect Invoke OSS: https://github.com/melvinkcx/fastapi-events/compare/v0.11.0...v0.11.1
- The changes in the proposed OpenTelemetry fix were tested in the Invoke hosted environment and do not affect the OSS installations either
Merge anytime
=> Bump fastapi-events dependency

invokeai/frontend/web/src/services/api/endpoints/images.ts
- currently the total for uncategorized images is not updating when moving and deleting images, this will update that count when making those actions
=> fix: update uncategorized board totals when deleting and moving images

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedUpscale.ts, invokeai/frontend/web/src/common/hooks/useIsReadyToEnqueue.ts, invokeai/frontend/web/src/features/modelManagerV2/hooks/useStarterModelsToast.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/StarterModels/StartModelsResultItem.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/StarterModels/StarterModelsResults.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/InstallModels.tsx, invokeai/frontend/web/src/features/nodes/util/graph/buildMultidiffusionUpscaleGraph.ts, invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/MultidiffusionWarning.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/UpscaleSettingsAccordion.tsx
Updates Structure math, consolidating some numbers and fixing a bug.
You can test the Upscaling Tab. 
Merge freely.
=> Math Updates

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsMenu.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsUpsellMenuItem.tsx
Adds menu items to settings menu for pro upsells
=> feat(ui): add upsells for pro edition to settings menu

invokeai/frontend/web/src/features/parameters/components/MainModel/ParamMainModelSelect.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLRefiner/ParamSDXLRefinerModelSelect.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/RefinerSettingsAccordion/RefinerSettingsAccordion.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/UpscaleSettingsAccordion.tsx
This issue has always existed but I didn't notice it until we added spandrel models. The `SwinIR` model's name is really long and it causes the model selects to overflow. The issue also occurs on the main and refiner model selects.
n/a
Before:
After:
n/a
=> fix(ui): model select overflowing when model  names are too long

invokeai/frontend/web/src/features/nodes/hooks/useCopyPaste.ts
Problems this was causing:
- Deleting an edge was a copy of another edge deletes both edges
- Deleting a node that was a copy-with-edges of another node deletes its edges and it's original edges, leaving what I will call "ghost noodles" behind
I think @JPPhoto had reported this recently but I can't find where that was.
- Load a workflow
- Copy a node that has a few inputs
- Ctrl + Shift + V to paste the node and its edges
- Delete one of the new edges - before this would delete the OG edge too, after it should not
- Delete the copied node - before this would delete the OG input edges & cause ghost noodles, after should not
n/a
=> fix(ui): copied edges must have new ids set

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/components/InformationalPopover/constants.ts, invokeai/frontend/web/src/features/parameters/components/Upscale/ParamCreativity.tsx, invokeai/frontend/web/src/features/parameters/components/Upscale/ParamSpandrelModel.tsx, invokeai/frontend/web/src/features/parameters/components/Upscale/ParamStructure.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/AdvancedSettingsAccordion/AdvancedSettingsAccordion.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/GenerationSettingsAccordion/GenerationSettingsAccordion.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/UpscaleScaleSlider.tsx, invokeai/frontend/web/src/features/settingsAccordions/hooks/useStandaloneAccordionToggle.ts
* collapse generation and advanced settings on upscale tab 
* add informational popovers for new upscale params
=> feat(ui): upscale folllow-ups

invokeai/app/services/workflow_records/default_workflows/MultiDiffusion SD1.5 (Beta).json, invokeai/app/services/workflow_records/default_workflows/MultiDiffusion SD1.5.json, invokeai/app/services/workflow_records/default_workflows/MultiDiffusion SDXL.json
- Update `MultiDiffusion SDXL (Beta)`
- Add `MultiDiffusion SD1.5 (Beta)`
n/a
Test out the workflows. I tested them myself and both are working as expected.
n/a
=> feat(app): update default workflows

docker/Dockerfile
Our frontend now requires pnpm version 8 to be used during installs. This small PR updates our dockerfile to build images using the correct pnpm version.
Run `docker build . -f ./docker/Dockerfile` with docker properly setup on your environment and confirm the image builds sucessfully.
This can be merged when approved
=> Update docker image to use pnpm version 8

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/addArchivedOrDeletedBoardListener.ts
[fix(ui): fix logic to reset selected/auto-add boards when toggling show archived boards](https://github.com/invoke-ai/InvokeAI/commit/9027c96470ac42d039d721ca3aff12ba55f93b7a)
The logic was incorrect in two ways:
1. We only ran the logic if we _enable_ showing archived boards. It should be run we we _disable_ showing archived boards.
2. If we couldn't find the selected board in the query cache, we didn't do the reset. This is wrong - if the board isn't in the query cache, we _should_ do the reset. This inverted logic makes more sense before the fix for issue 1.
[fix(ui): race condition when deleting a board and resetting selected/auto-add](https://github.com/invoke-ai/InvokeAI/commit/d804b6e1acd3f38d4d0c6efb1001c8ac4777c875)
We were checking the selected and auto-add board ids against …
=> fix(ui): deleting a board or hiding archived should reset selected & auto-add boards

invokeai/frontend/web/src/features/nodes/util/graph/buildMultidiffusionUpscaleGraph.ts
Metadata for SD-1 and SDXL multidiffusion graphs was being built separately, and the upscale metadata got left out of the SDXL graph. This combines metadata that the two have in common (everything but prompt), and includes upscale metadata in both base model graphs.
=> fix(ui): include upscale metadata for SDXL multidiffusion

invokeai/app/services/image_files/image_files_disk.py, invokeai/app/services/model_images/model_images_default.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/features/deleteImageModal/components/DeleteImageModal.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/DeleteBoardModal.tsx, invokeai/frontend/web/src/features/system/store/configSlice.ts, pyproject.toml
Many moons ago, we used `send2trash` to delete images. This provides a cross-platform way to send files to the OS's "trash bin" container. Users could restore the deleted images to their outputs folder and they would reappear in the app.
This doesn't work today. When you delete an image, we also delete the image record in the database, so restoring the file does not restore the image from the perspective of the app. The original motivation for using `send2trash` is no longer valid.
- Remove calls to `send2trash`
- Remove `send2trash` as a dependency
- Update delete image modal verbiage
- Cleaned up types for `DiskImageStorage` while I was there (nonfunctional)
- Related #6598: Attempting to delete an image causes an error on a cloud platform. I believe this is caused by `send2trash`, but …
=> feat(app): delete images without send2trash

pyproject.toml
There was a problem w/ this release on windows and the builds were pulled from pypi. When installing invoke on windows, pip attempts to build from source, but most (all?) systems won't have the prerequisites for this and installs fail.
This also affects GH actions.
The simple fix is to exclude version 3.9.1 from our deps.
For more information, see https://github.com/matplotlib/matplotlib/issues/28551
- Closes #6717
- [Discord discussion on #dev chat](https://discord.com/channels/1020123559063990373/1049495067846524939/1269599836781416520)
- [Discord user report](https://discord.com/channels/1020123559063990373/1149510134058471514/1269687327446532187)
If CI passes, we're good.
We could also disallow building from source for matplotlib but we'd need to update installer scripts and GH …
=> build: exclude matplotlib 3.9.1

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/common/hooks/useIsReadyToEnqueue.ts, invokeai/frontend/web/src/features/parameters/hooks/useIsTooLargeToUpscale.ts, invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/UpscaleInitialImage.tsx, invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/UpscaleWarning.tsx
* Restore and modify logic for having an optional limit on upscale output resolution size. A warning will be displayed and the Invoke button will be disabled if the output resolution (image width x image height x scale x scale) is above that amount.
* Adds image resolution badge to initial upscale image so make sure user knows where they are starting
=> feat(ui): restore optional upper limit on upscale resolution size

invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/UpscaleWarning.tsx
Fixes a but in the upscale tab logic that didn't render the warning for maxUpscaleDimension if the models tab was disabled
=> fix(ui): show warning for maxUpscaleDimension if model tab is disabled

invokeai/app/api/routers/images.py
In #6607 we fixed a race condition with deleting images. The fix inadvertently removed some headers from the image serving route that caused #6730. Headers restored
Closes #6730
Open image in new tab -> save image -> should use the correct filename
n/a
=> fix(api): image downloads with correct filename

invokeai/app/api/dependencies.py, invokeai/app/api_app.py, invokeai/app/services/events/events_fastapievents.py
(copied from commit message + videos)
Around the time we (I) implemented pydantic events, I noticed a short pause between progress images every 4 or 5 steps when generating with SDXL. It didn't happen with SD1.5, but I did notice that with SD1.5, we'd get 4 or 5 progress events simultaneously, so we get a new progress image once every ~100ms. I'd expect one event every ~25ms, matching my it/s with SD1.5. Mysterious!
<video src="https://github.com/user-attachments/assets/e781e2f1-d9f5-4392-9acf-bd6f0f1223d6"></video>
<video src="https://github.com/user-attachments/assets/664c3a5c-a470-496b-845a-2601167036e0"></video>
Digging in, I found an issue is related to our use of a synchronous queue for events. When the event queue is empty, we must call `asyncio.sleep` before checking again. We …
=> fix(app): delays in events

installer/templates/invoke.sh.in
When invoke.sh is executed using a symlink with a working directory outside of InvokeAI's root directory, it will fail with the following message:
`<path to symlink>: line 23: .venv/bin/activate: No such file or directory`
invoke.sh attempts to cd into the correct directory at the start of the script, but will cd into the directory of the symlink instead. This MR fixes that.
- Create a symlink to invoke.sh
- cd into any directory except InvokeAI's root directory
- Execute invoke.sh using the previously created symlink to verify that the initial problem is fixed
- Execute invoke.sh directly to verify that this still works
I performed these checks on Arch Linux 6.10.3-arch1-2 (64-bit). I did not test this MR on other Linux distributions or MacOS but to my knowledge `readlink` is available …
=> Fix invoke.sh not detecting symlinks

invokeai/version/invokeai_version.py, pyproject.toml
We need to specify in `pyproject.toml` to include the default style presets data else the app fails to launch and is unable to seed the db.
https://discord.com/channels/1020123559063990373/1149506274971631688/1273946504427601992
To test the wheel:
- `make installer-zip`
- `pip install installer/dist/InvokeAI-4.2.8rc2-py3-none-any.whl`
- `invokeai-web`
Should load and show the default style presets with their images. I tested and everything works.
I will do another release when merged
=> fix: bundle style preset defaults, bump version to v4.2.8rc2

invokeai/frontend/web/src/features/stylePresets/components/StylePresetForm/StylePresetForm.tsx, invokeai/frontend/web/src/features/stylePresets/components/StylePresetListItem.tsx
fix(ui): use translations for style preset strings
https://discord.com/channels/1020123559063990373/1054129386447716433/1274085755517534218
n/a
n/a
=> fix(ui): use translations for style preset strings

invokeai/app/api/routers/style_presets.py, invokeai/app/services/style_preset_records/style_preset_records_common.py, invokeai/frontend/web/src/features/stylePresets/components/StylePresetListItem.tsx
* add `type` as an option for updating style preset
* fix toast when deleting a style preset fails
=> some style preset follow-ups

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/gallery/hooks/useImageActions.ts
When a prompt is recalled (Remix, Recall All, Recall Prompt), clear prompt templates and let user know via toast
=> fix(ui): clear prompt template when prompts are recalled

invokeai/frontend/web/src/common/util/convertImageUrlToBlob.ts, invokeai/frontend/web/src/features/stylePresets/components/ActiveStylePreset.tsx, invokeai/frontend/web/src/features/stylePresets/components/StylePresetForm/StylePresetForm.tsx, invokeai/frontend/web/src/features/stylePresets/components/StylePresetForm/StylePresetModal.tsx, invokeai/frontend/web/src/features/stylePresets/components/StylePresetImage.tsx, invokeai/frontend/web/src/features/stylePresets/components/StylePresetMenuTrigger.tsx, invokeai/frontend/web/src/services/api/endpoints/stylePresets.ts
* add loading state to button when creating or updating a prompt template
* fix badge styling when template name is long
* fix extra slash in exports endpoint that UI calls
* fix(ui): error handling if unable to convert image URL to blob
=> fix(ui): more prompt template follow-ups

invokeai/frontend/web/src/features/gallery/hooks/useImageActions.ts
fix(ui): use empty string fallback if unable to parse prompts when creating style preset from existing image
discovered this using an outpainting image that had a positive prompt but no negative prompt
=> fix(ui): use empty string fallback if unable to parse prompts when creating style preset from existing image

invokeai/frontend/web/src/features/stylePresets/components/StylePresetExportButton.tsx
Instead of counting the number of user presets, count the number of non-default presets so that other types are included.
=> fix(ui): disable export button if no non-default presets

pyproject.toml
These two scripts are broken and can cause data loss. Remove them.
They are not in the launcher script, but _are_ available to users in the terminal/file browser.
Hopefully, when we removing them here, `pip` will delete them on next installation of the package...
- Closes #6776
- Closes #6188
- Closes #5486
- Closes #6518
Whether this deletes the scripts on users' machines or not doesn't matter - this change is needed either way.
n/a
=> build: remove broken scripts

invokeai/app/invocations/flux_text_encoder.py, invokeai/app/invocations/flux_text_to_image.py, invokeai/backend/flux/sampling.py, invokeai/backend/model_manager/load/load_default.py, invokeai/backend/model_manager/load/model_cache/model_cache_base.py, invokeai/backend/model_manager/load/model_cache/model_cache_default.py, invokeai/backend/quantization/bnb_llm_int8.py, invokeai/backend/stable_diffusion/diffusion/conditioning_data.py, invokeai/backend/util/__init__.py, invokeai/backend/util/util.py
This PR contains several improvements to memory management for FLUX workflows.
It is now possible to achieve better FLUX model caching performance, but this still requires users to manually configure their `ram`/`vram` settings. E.g. a `vram` setting of 16.0 should allow for all quantized FLUX models to be kept in memory on the GPU.
Changes:
- Check the size of a model on disk and free the requisite space in the model cache before loading it. (This behaviour existed previously, but was removed in https://github.com/invoke-ai/InvokeAI/pull/6072/files. The removal did not seem to be intentional).
- Removed the hack to free 24GB of space in the cache before loading the FLUX model.
- Split the T5 embedding and CLIP embedding steps into separate functions so that the two models don't both have …
=> FLUX memory management improvements

invokeai/app/services/model_install/model_install_common.py
This __string__ method is causing the model probe to insert incorrect sources into models installed via huggingface subfolders.
Install any flux model via starter models and ensure it changes to `Installed`
=> Fix source string in hugging face installs with subfolders

scripts/allocate_vram.py
Allocates the specified amount of VRAM, or allocates enough VRAM such that you have the specified amount of VRAM free.
Useful to simulate an environment with a specific amount of VRAM.
Wrote to help troubleshoot #6613
Try it out if you like. It works fine for me on linux.
n/a
=> scripts: add allocate_vram script

invokeai/app/invocations/flux_denoise.py, invokeai/app/services/shared/invocation_context.py, invokeai/app/util/step_callback.py, invokeai/backend/flux/denoise.py
This PR adds in progress images to our flux nodes. It adds a new context util function for flux pipelines step callbacks. RGB Latent factors were generated by updating a brute force script provided by @StAlKeR7779 
https://github.com/user-attachments/assets/e5dc6e8d-36f2-4848-abd8-a24596f97e5d
Run a flux image generation workflow and validate the progress images look satisfactory.
=> feat: flux preview images

invokeai/backend/model_manager/probe.py
During testing of the new Flux starter models, I found that installation of `clip-vit-large` and the quantized text encoders were failing during the model installer's model probe phase. This PR adds model probe support for the FLUX T5_encoder and ClipTextModel dependencies. This PR fixes "download failed" errors experienced when the FLUX starter models are installed.
To confirm the original issue, please first remove the T5 quantized text encoder and clip-vit-large, and try to install one of the quantized Flux models from the Model manager starter models tab. This should fail.
After pulling this PR, these tasks should run to completion and flux-based workflows should work.
=> Add install probes for T5_encoder and ClipTextModel

.github/workflows/build-container.yml
This pull request updates the container build GitHub Actions workflow to include an option that allows pushing the built image to the container registry from any branch (in addition to `main`), but only when triggered manually using Workflow Dispatch.
This feature enables the creation of ad-hoc images from any branch to test changes in a containerized environment, eliminating the need to build and push images locally.
Additionally, it supports forked repositories, where the image will be pushed to the package registry owned by the fork's owner.
The PR also bumps Github Action version pins in the workflow in response to deprecation warnings.
=> Build container image on-demand

invokeai/backend/model_manager/load/model_loaders/flux.py, invokeai/backend/model_manager/probe.py, invokeai/backend/model_manager/util/model_util.py
This update is meant to update our model loader and probe to support flux checkpoint bundles containing the transformer along with other models. We will update out loaders to support pulling out the encoders and other models from these in a future update. This PR enables users to leverage flux checkpoints commonly found on civitAI
Install checkpoint models such as [this one](https://civitai.com/models/652009/fluxrealisticv1?modelVersionId=733981) and ensure you're able to successfully run the flux workflows with it.
=> feat: support checkpoint bundles containing more than the transformer

invokeai/frontend/web/src/features/controlLayers/components/Filters/Filter.tsx, invokeai/frontend/web/src/features/controlLayers/components/Filters/FilterSpandrel.tsx
- Fix: infinite recursion (i.e. a crash) when selecting spandrel filter w/ no spandrel models installed
- Fix: translations for spandrel filter
Closes #6835 
Spandrel (image-to-image) filter shouldn't crash when you have no spandrel models installed.
n/a
=> fix(ui): spandrel filter

invokeai/app/invocations/create_gradient_mask.py, invokeai/app/invocations/fields.py, invokeai/app/invocations/flux_denoise.py
Invert the expected `denoise_mask` parameter to the FLUX Denoise node to match the behaviour of Denoise Latents node used for SD.
Changes the definition of the denoise_mask parameter on the "FLUX Denoise" node to match the "Denoise Latents" node. New definition: "Values of 0.0 represent the regions to be fully denoised, and 1.0 represent the regions to be preserved."
Also updates the docs in a few places to make this expectation more clear.
I tested on top of this branch: https://github.com/invoke-ai/InvokeAI/pull/6846
=> Invert the expected `denoise_mask` parameter to the FLUX Denoise node

invokeai/frontend/web/src/features/ui/components/VerticalNavBar.tsx
Change upscaling icon to a Phosphor icon, same as we use for the post-processing button:
n/a
n/a
n/a
=> feat(ui): change upscaling icon

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsMenu.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx
Restores functionality where Settings Modal is rendered using children that trigger it
Tested settings modal in OSS and commercial ✅
=> fix(ui): restore Settings Modal functionality to render using children

invokeai/backend/image_util/lineart.py, invokeai/backend/image_util/lineart_anime.py
The lineart model often outputs a lot of almost-black noise. SD1.5 ControlNets seem to be OK with this, but SDXL ControlNets are not - they need a cleaner map. 12 was experimentally determined to be a good threshold, eliminating all the noise while keeping the actual edges. Other approaches to thresholding may be better, for example stretching the contrast or removing noise.
I tried:
- Simple thresholding (as implemented here) - works fine.
- Adaptive thresholding - doesn't work, because the thresholding is done in the context of small blocks, while we want thresholding in the context of the whole image.
- Gamma adjustment - alters the white values too much. Hard to tuen.
- Contrast stretching, with and without pre-simple-thresholding - this allows us to treshold out the noise, then …
=> fix(nodes): add thresholding to lineart & lineart anime nodes

invokeai/frontend/web/src/common/components/IAIDndImage.tsx, invokeai/frontend/web/src/common/components/IAIDropOverlay.tsx, invokeai/frontend/web/src/common/components/IAIDroppable.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/useCanvasResetLayerHotkey.ts, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/GalleryBoard.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/NoBoardBoard.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ImageFieldInputComponent.tsx
Two small fixes:
- When you hit `shift+c` while in the middle of drawing on a layer, there's a bit of a janky delay as the reset propagates from redux and to the canvas classes. The hotkey now cancels the in-progress drawing, indirectly fixing the jank.
- Not sure how I've missed this before but there was a React error w/ the dnd drop zone labels which accepted a react node. Fixed this, drop zones labels must now be strings.
Shift+c issue reported on discord.
n/a
n/a
=> fix(ui): canvas followups 10

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/boardAndImagesDeleted.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageToDeleteSelected.ts, invokeai/frontend/web/src/common/hooks/useIsReadyToEnqueue.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/deleteImageModal/components/DeleteImageModal.tsx, invokeai/frontend/web/src/features/deleteImageModal/components/ImageUsageMessage.tsx, invokeai/frontend/web/src/features/deleteImageModal/store/selectors.ts, invokeai/frontend/web/src/features/deleteImageModal/store/types.ts, invokeai/frontend/web/src/features/gallery/components/Boards/DeleteBoardModal.tsx, invokeai/frontend/web/src/features/parameters/hooks/useIsTooLargeToUpscale.ts, invokeai/frontend/web/src/features/parameters/store/upscaleSlice.ts, invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/UpscaleSettingsAccordion.tsx
Update the image usage checks we do before deleting images to include the new layers for canvasV2 and upscaling.
Add image as various layers on canvas and try to delete it. Warning box should appear with details on where the image is being used.
=> feat(ui): update image usage check for canvas v2 layers and upscaling

invokeai/frontend/web/src/features/gallery/hooks/useGalleryNavigation.ts
There was an issue w/ the calculation causing an infinite loop but the fixed algorithm from #6887 wasn't correct bc it doesn't take into account the grid gap correctly. This then breaks arrow key navigation.
- Restore the previous calculation
- Bail out if the gallery elements don't have any width, which causes the infinite loop - this part was missed when copying the logic from GalleryImageGrid
n/a
shouldn't freeze
n/a
=> fix(ui): gallery grid calculation

invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolBrushWidth.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolEraserWidth.tsx, invokeai/frontend/web/src/features/gallery/hooks/useGalleryHotkeys.ts, invokeai/frontend/web/src/features/nodes/components/flow/Flow.tsx
- Delete hotkey on gallery doesn't delete
- Delete on workflows also triggers gallery delete
- Brush/eraser width hotkeys not working
discord & offline discussion
Try the fixed things
n/a
=> fix,feat: canvas followups 13

invokeai/frontend/web/src/features/controlLayers/components/Filters/Filter.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasCompositorModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityFilterer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectImage.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStateApiModule.ts, invokeai/frontend/web/src/features/controlLayers/store/filters.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/metadata/util/parsers.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/Graph.test.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/Graph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addControlAdapters.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addRegions.ts, invokeai/frontend/web/src/services/api/endpoints/images.ts, invokeai/frontend/web/src/services/events/errors.ts, invokeai/frontend/web/src/services/events/onInvocationComplete.tsx
I reviewed the canvas codebase to find places where errors could occur. Two categories:
- Network requests (e.g. getting images, uploading images, queuing graphs)
- Canvas operations (e.g. exporting canvas to `Blob`)
All instances of these things now have error handling at some level - either close to the error-producing code or higher up where the code is consumed.
Canvas filters were the most complex thing to handle. The filter queues a graph, waits for a specific node to finish and retrieves an output image. Handling all the possible cases requires care. There's a new method that wraps up executing a graph to get an image output into a single async function call. This is well-documented.
While iterating on filters, I made an internal change to how filter graphs are generated. Instead …
=> feat(ui): canvas error handling

invokeai/app/invocations/baseinvocation.py, invokeai/app/invocations/image.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/flow/AddNodeCmdk/AddNodeCmdk.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/InvocationNodeClassificationIcon.tsx, invokeai/frontend/web/src/features/nodes/types/common.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/events/onInvocationComplete.tsx
- Add `Classification.Internal` for nodes, handle it in the UI
- Mark canvas output node as internal
- Update canvas handling w/ changed node
n/a
Canvas should still work. Not a major change.
n/a
=> feat: canvas node cleanup

tests/backend/lora/test_lora_patcher.py
This PR attempts to fix a flaky FLUX LoRA unit test.
Example test failure: https://github.com/invoke-ai/InvokeAI/actions/runs/10958325913/job/30428299328?pr=6898
The failure _seems_ to be caused by a numerical precision error, but I haven't been able to reproduce it locally. I have reduced the tolerance of the offending comparison, and am pretty confident that this will solve the issue.
No QA necessary.
=> Fix flaky FLUX LoRA unit test

invokeai/frontend/web/src/app/hooks/useHandleStudioDestination.ts
* track whether studio destination hook fn has already fired to prevent it firing multiple times
* fix workflow library modal when `viewAllWorkflows`
=> fix(ui): track whether studio destination hook fn has already fired

invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts
This PR addresses a problem when user commands to recall all metadata from the generated image. While recalling only partial metadata everything works fine, but 'Use All' aka the Asterisk button resets state of canvas bbox to model optimal dimensions.
https://github.com/user-attachments/assets/3a9f5c9c-c216-41b0-8ccc-383332af90a0
- Addresses problem discussed on Discord: https://discordapp.com/channels/1020123559063990373/1149506274971631688/1287160033657884907
- Generate a sample image with dimensions other than defaults for the selected model.
- Perform WebUI reset and localStorage.clear(), clear cache, reload CanvasV2 Viewer.
- Use Asterisk (Use All) command to recall all generation parameters from the generated image.
- Invoke a new image using recalled parameters.
- Sample image and …
=> (fix) fixed bbox size reset to optimals on 'Use All' (Asterisk) button press

invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityFilterer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStateApiModule.ts
There's a situation in which the enqueue response comes after the graph actually executes. This was unexpected when I first wrote the logic. I suppose it has to do with the async endpoint handling.
Really hammer filtering. Use the fastest filter you can - probably color map? - as this is expected to trigger the race condition the most reliably. 
n/a
=> fix(ui): race condition when filtering causing errors/stuck filter

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/appConfigReceived.ts
LaMA is the next best infill after patchmatch - prefer it.
- Ensure you have patchmatch selected for infill
- Add `patchmatch: false` to `invokeai.yaml`
- Restart server
- It should auto-switch to lama
n/a
=> fix(ui): prefer 'lama' infill when handling infill fallback

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/modelSelected.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/modelsLoaded.ts, invokeai/frontend/web/src/features/controlLayers/components/CanvasAlerts/CanvasAlertsSendingTo.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasBboxModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStateApiModule.ts, invokeai/frontend/web/src/features/controlLayers/store/selectors.ts, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImagePreview.tsx, invokeai/frontend/web/src/services/events/stores.ts
- Fix: Bbox respects snap to grid setting when moving it
- Fix: Workflows hotkey translations
- Fix: Do not update bbox when changing models, if the model's base type doesn't change
- Fix: Canvas staging alerts displayed erroneously on workflows/upscaling tabs
- Fix: Invalid workflow model selected on first app launch or after reset web UI
- Fix: Blank viewer when progress does not have an image (e.g. spandrel upscale)
- Fix: Workaround 🤞 for out-of-order events
discord, offline discussion
try the fixes out
n/a
=> fix,feat: canvas followups 16

invokeai/frontend/web/src/features/controlLayers/konva/CanvasStateApiModule.ts
Another fix for filter event listeners. Was prematurely removing the listeners.
n/a
n/a
=> fix: filter event listeners

invokeai/frontend/web/src/features/gallery/store/gallerySlice.ts, invokeai/frontend/web/src/services/events/onInvocationComplete.tsx
Two changes to reduce extraneous image selection changes.
In the invocation complete handler, if it outputs an image, we refresh the gallery images list and select the new image.
We were inadvertently selecting the image _twice_ in some situations: if `auto-switch to new images` was enabled, and the currently-selected board is not the board of the new image, we would select the image twice.
@JPPhoto [has an issue](https://discord.com/channels/1020123559063990373/1278037635230863411/1287838550846476309) that I initially thought could be caused by this. After pondering I doubt it will fix his problem, but it's good to fix it anyways.
The fix simply skips the redundant image selection call.
In the `gallerySlice` reducers for `imageSelected` and `selectionChanged` (why does these both exist? …
=> fix(ui): reduce extraneous image selection

invokeai/frontend/web/src/features/gallery/components/GalleryPanelContent.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageComparisonSideBySide.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/NodeEditorPanelGroup.tsx, invokeai/frontend/web/src/features/ui/components/AppContent.tsx, invokeai/frontend/web/src/features/ui/components/tabs/ResizeHandle.tsx, invokeai/frontend/web/src/features/ui/hooks/usePanel.ts, invokeai/frontend/web/src/features/ui/store/uiSlice.ts
- Remove extraneous percentage layout logic from `usePanel`
- Fix bug where default size is handled as percentage instead of pixel (well, not really a bug, just a weird behaviour)
- Fix resize handle styling issues
n/a
panels should work the same
Should not be merged before v5
=> feat(ui): cleanup resizable panels

invokeai/frontend/web/src/features/ui/hooks/usePanel.ts
Fixes a bug introduced in a different bug fix in 9c0d357817a0a756543c3aa56de4b08bb1933a79.
Discord: https://discord.com/channels/1020123559063990373/1149506274971631688/1288538365011951636
Switch between layers & gallery tabs, with boards list open and closed. Its default size should never be reset or fill up the panel.
n/a
=> fix(ui): handle resizable panels not rendered in DOM

invokeai/frontend/web/src/features/toast/ErrorToastDescription.tsx
If an invocation error happens that results in a very long `description`, the toast can take over the vertical space on screen and be impossible to close without refreshing the page. This limits the toast description for these errors to 4 lines.
=> fix(ui): truncate error description so toast is always close-able

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/boardIdSelected.ts, invokeai/frontend/web/src/services/events/onInvocationComplete.tsx
New images weren't being selected. Actually, they were, but then they were quickly unselected.
The changes in #6930 unmasked a deeper logic issue that then became a bug.
n/a
Test with auto-switch enabled.
Test matrix:
- Auto-add board selected vs non-auto-add board selected
- On images tab vs on assets tab
n/a
=> fix(ui): new image selection logic

invokeai/frontend/web/src/features/gallery/components/GalleryPanelContent.tsx, invokeai/frontend/web/src/features/ui/components/AppContent.tsx, invokeai/frontend/web/src/features/ui/hooks/usePanel.ts
`usePanel` started panels with a `minSize` and `defaultSize` of 0, which means collapsed. This causes panels to load as collapsed on the very first app load. Then, in the layout effect, we see the panel as collapsed and skip setting it to the correct size.
Reviewing the library's API, `minSize` and `defaultSize` should not be lower than 1. Thankfully, setting this to 1 also prevents the issue described above.
- `minSize` and `defaultSize` start at 1
- Return a sentinel value when converting percentages to pixels, if the panel's container has no size. When that happens, we should not update the `minSize` or `defaultSize`.
- Split observer callback into its own function, so that the exact same logic can be used on the first run of hte effect.
- Update prop names and docstrings to accurately …
=> fix(ui): resizable panels collapsed on first app startup

invokeai/frontend/web/src/features/controlLayers/konva/CanvasStagingAreaModule.ts
Fixes a case where the canvas is erroneously interactable after refreshing the page while currently staging.
n/a
- Generate on canvas, getting an image or two onto the staging area
- Refresh the page
- The canvas should be locked down and not allow you to draw/move/etc
n/a
=> fix(ui): canvas interactable after refresh while staging

invokeai/app/api_app.py
This pops up every now and then and I could never figure it out. A user figured it out in #6936. The cause is appending a query string to the app URL.
For example:
```sh
http://127.0.0.1:9090/?__theme=dark
```
The query string breaking the static file serving, which prevents our translations from loading correctly. Instead of the JSON translations, FastAPI sends the index HTML page. The UI then errors when attempting to parse the translation JSON.
The query string `?__theme=dark` is used by Gradio to force dark mode. I believe the users with this issue are doing the same thing the user in #6936 did (just change the port number on an existing bookmark) or their browser history/bookmark includes the query string.
Though this is technically a user-caused problem (we cannot prevent the user …
=> fix(api): UI crash with `TypeError: i.map is not a function`

invokeai/backend/model_manager/config.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/setDefaultSettings.ts, invokeai/frontend/web/src/features/modelManagerV2/hooks/useMainModelDefaultSettings.ts, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/MainModelDefaultSettings/DefaultGuidance.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/MainModelDefaultSettings/MainModelDefaultSettings.tsx, invokeai/frontend/web/src/features/parameters/types/parameterSchemas.ts, invokeai/frontend/web/src/services/api/schema.ts
* Update default settings for FLUX models to include Guidance, and to exclude CFG, CFG rescale multiplier, VAE precision, and schedulers since we do not yet support those in the UI
=> feat(ui,api): add guidance as a default setting option for FLUX models

invokeai/frontend/web/src/features/modelManagerV2/store/modelManagerV2Slice.ts, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelManagerPanel/ModelList.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelManagerPanel/ModelTypeFilter.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelEdit.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelView.tsx, invokeai/frontend/web/src/services/api/hooks/modelsByType.ts, invokeai/frontend/web/src/services/api/types.ts
Not sure why they were hidden but it makes it hard to delete them if they are borked for some reason (have to go thru API docs page or do DB surgery).
- [discord](https://discord.com/channels/1020123559063990373/1020123559831539744/1290433044523782194)
Should be able to see and delete CLIP vision models in the MM tab
n/a
=> feat(ui): show CLIP Vision models in model manager UI

invokeai/app/invocations/flux_denoise.py, invokeai/app/invocations/flux_text_encoder.py, invokeai/backend/lora/conversions/flux_diffusers_lora_conversion_utils.py, invokeai/backend/lora/conversions/flux_kohya_lora_conversion_utils.py, invokeai/backend/lora/conversions/flux_lora_constants.py, tests/backend/lora/conversions/test_flux_diffusers_lora_conversion_utils.py, tests/backend/lora/conversions/test_flux_kohya_lora_conversion_utils.py
Fixes a regression in support for FLUX diffusers LoRA models (introduced in https://github.com/invoke-ai/InvokeAI/pull/6967).
Closes #6996
I ran the following manual tests:
- Non-quantized transformer
- Quantized tranformer (BnB NF4)
=> Fix regression with FLUX diffusers LoRA models

invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemCopy.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemDelete.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemDownload.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemOpenInNewTab.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemOpenInViewer.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemSelectForCompare.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx
Condensed top row of image context menus. This felt like a good short term necessary step to keep the image context menu from becoming too big and overwhelming.
Since submenus are a more complicated endeavor due to the current libraries being used, I took inspiration from Windows 11's infamous quick shortcuts ui pattern, which proved to be a great solution here.
=> feat(context menu): :sparkles: condense top row of image context menu

invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolColorPicker.ts
Fixes an issue where the color picker didn't display while hovering with a pen input device
discord convo
n/a
n/a
=> fix(ui): show color picker when using pen

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/CanvasContextMenu/CanvasContextMenuGlobalMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasContextMenu/CanvasContextMenuItemsCropCanvasToBbox.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasContextMenu/CanvasContextMenuSelectedEntityMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/InpaintMask/InpaintMaskMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/RasterLayer/RasterLayerMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/common/CanvasEntityMenuItemsCropToBbox.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterBase.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts
Add layer and canvas crop functionality.
All layer types can be cropped. Cropping rasterizes the layer and uploads it as an image. 
We can only do one rasterization action at a time, so when you crop to canvas, you'll see each layer get cropped individually. If this is unacceptable I can figure out another way to do it so that it looks like the whole canvas crops at once, but it's a bit more complex to do that.
- Closes #5509
- Closes #5775
Add some layers and crop them.
Crop the canvas to bbox or layers to bbox from the canvas context menu:
You can also crop the layer to bbox from the layer context menu:
n/a
=> feat(ui): layer/canvas crop

invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts
[fix(ui): give unique ID to duplicated regional guidance layers' ref images](https://github.com/invoke-ai/InvokeAI/commit/b69558fbc06e93f338fcbfb3817c64e0ef15ebe7)
Closes #6995
- Duplicate a regional guidance layer w/ a reference image
- Generation should still work
n/a
=> fix(ui): duplicating regional guidance layer breaks graph generation

invokeai/frontend/web/src/features/controlLayers/store/lorasSlice.ts
fix(ui): recall LoRAs may create duplicates
Closes #7004
- Generate w/ a LoRA
- Change the weight of the LoRA so when you recall, you know it replaced the existing LoRA
- Recall that LoRA from the image you just generated
- It should replace the existing LoRA and not duplicate it
n/a
=> fix(ui): recall LoRAs may create duplicates

pyproject.toml
#6890 bumped torch, which caused an incompatibility with xformers when installing with `pip install ".[xformers]"`. This PR bumps xformers.
I ran some smoke tests to confirm that generating with xformers still works.
In my tests on an A100, there is a performance regression after bumping xformers (2.7 it/s vs 3.2 it/s). I think it is ok to ignore this for A100s, since users should be using torch-sdp, which is much faster (4.3 it/s). But, we should test for regression on older cards where xformers is still recommended.
=> Bump xformers for compatibility with torch

invokeai/frontend/web/src/features/gallery/hooks/useImageActions.ts, invokeai/frontend/web/src/features/metadata/components/MetadataLoRAs.tsx, invokeai/frontend/web/src/features/metadata/hooks/useMetadataItem.tsx
There were a few places where metadata-related promise rejections were unhandled. Any instrumentation added to the app would see the rejections and log them, but these rejections are all no-ops and should jsut be ignored.
In this change, I reviewed the metadata recall logic to add handling everywhere rejections were unhandled. Think I got them all.
n/a
n/a
n/a
=> fix(ui): prevent unhandled promise rejections

installer/lib/installer.py, invokeai/version/invokeai_version.py
- Update the installer to use the correct index for our combination of `torch` and `xformers`
- Bump version to v5.1.0rc3
[Discord](https://discord.com/channels/1020123559063990373/1149506274971631688/1291526250665476147)
Installer should work. Successfully tested on Windows w/ nvidia GPU.
I will do the release
=> fix: install issues w/ torch

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardEditableTitle.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/GalleryBoard.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/NoBoardBoard.tsx
Dunno exactly why this broke but it did. I replaced the janky old hacked editable with the DIY editable I made for the canvas, which works much better and looks better too.
https://discord.com/channels/1020123559063990373/1149506274971631688/1291791807021191209
Double click board title to edit
n/a
=> fix(ui): board title editable

invokeai/frontend/web/src/common/components/IAIDropOverlay.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterImagePreview.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ImageFieldInputComponent.tsx
- Fix funky drop targets
- Bigger drop target for node images, and it has error state (i.e. when image is required and no image is selected)
- Add error state for IP adapter image drop target (i.e. when no image selected)
https://discord.com/channels/1020123559063990373/1149506274971631688/1291765977448448131
Try out drop targets
n/a
=> fix(ui): funky drop targets

invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemCopy.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemDelete.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemDownload.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemOpenInNewTab.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemOpenInViewer.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemSelectForCompare.tsx
Need to render as a `MenuItem` to trigger the close behaviour
https://discord.com/channels/1020123559063990373/1149506274971631688/1291880017709629563
The row of icon buttons in image context menu should close the menu
n/a
=> fix(ui): image context menu buttons don't close menu

invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/GalleryBoard.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/NoBoardBoard.tsx
We just changed all buttons to use `onPointerUp` events to fix Apple Pencil behaviour. This, plus the specific DOM layout of boards, resulted in the `onPointerUp` being triggered on a board before the drop triggered.
The app saw this as selecting the board, which then reset the gallery selection to the first image in the board. By the time you drop, the gallery selection had reset.
DOM layout slightly altered to work around this.
https://discord.com/channels/1020123559063990373/1149506274971631688/1291975564563054613
Drag and drop multiple images between boards
n/a
=> fix(ui): board drop targets

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolBrush.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolColorPicker.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolEraser.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/util.ts
- Tidy some messy parts of `CanvasToolModule`
- Add some typo insurance
- Revised cursor tracking - track both relative and absolute positions and use Konva's built-in API to get the relative position.
- Fix an edge case with the color picker, and throttle it to improve performance.
n/a
n/a
n/a
=> feat(ui): canvas tool cleanup & perf

invokeai/frontend/web/src/features/controlLayers/components/CanvasDropArea.tsx
- Use translation strings for canvas drop area
n/a
n/a
n/a
=> fix(ui): missing translations for canvas drop area

invokeai/frontend/web/src/features/system/store/configSlice.ts
The current range of 2-6 produces consistent images and serves as a good default for regular users. However, it can be somewhat restrictive in certain situations. For example, when creating more painterly images, using a value lower than 2 can yield interesting results.
This PR modifies the less visible input range to allow for a broader range of values.
=> feat(ui): allow for a broader range of guidance values for flux models

invokeai/frontend/web/public/locales/en.json
There was a duplicate string for "layer" causing a weblate issue. 
https://discord.com/channels/1020123559063990373/1054129386447716433/1292795435689312299
n/a
n/a
=> fix(ui): duplicate translation string for "layer"

invokeai/backend/flux/math.py
A simple fix to use float32 in the rope function instead of float64 when the pos tensor is currently on a MPS device  
as MPS doesn't support float64 and isn't likely too any time soon.
Related issue is Flux doesn't work on MPS, InvokeAI 5.1.0 has moved to torch 2.4.1, this should fix #6991 but will lead to 
the next issue, which is fixed by this PR. After that you'll get the mps_arrange function not being present for bfloat16
tensors, that is fixed in PyTorch 2.5.0. and the nightlies(it could also be fixed in InvokeAIs code too depending on when you plan to upgrade to PyTorch 2.5.0 after its out, I feel thats better in another PR).
Test its not broke on CUDA as I have no access to that. I've been running with this code since 5.0.1 was released
so I know it doesn't break anything on MPS …
=> Get Flux working on MPS when torch 2.5.0 test or nightlies are installed

invokeai/frontend/web/src/features/controlLayers/components/CanvasEntityList/EntityListSelectedEntityActionBarOpacity.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolBrushWidth.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolEraserWidth.tsx, invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbarScale.tsx
- Set an empty title to prevent browsers from showing "Please match the requested format." when hovering the number input
- Fix issue w/ `z-index` that prevented the popover button from being clicked while the input was focused
https://discord.com/channels/1020123559063990373/1149513625321603162/1293369992288538644
n/a
n/a
=> fix(ui): canvas sliders misc

invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolModule.ts
There's a Konva bug where `pointerenter` & `pointerleave` events aren't fired correctly on the stage.
In 87fdea4cc65f70b4890e52089916751d479059f0 I made a change that surfaced this bug, breaking touch and Apple Pencil interactions, because the cursor position doesn't get updated.
Simple fix - ensure we update the cursor on `pointerdown` events, even though we shouldn't need to.
Will make a bug report upstream
https://discord.com/channels/1020123559063990373/1149506274971631688/1293375942416273479
Use finger and Apple Pencil
n/a
=> fix(ui): sync pointer position on pointerdown

invokeai/app/services/config/config_default.py
feat(app): update example config file comment
https://discord.com/channels/1020123559063990373/1149510134058471514/1293333856887504947
n/a
n/a
=> feat(app): update example config file comment

docker/Dockerfile, installer/lib/installer.py, installer/lib/messages.py, invokeai/backend/stable_diffusion/diffusers_pipeline.py
A recent Torch upgrade introduced a performance regression on modern Nvidia GPUs when using xformers.
This PR adds an install option to select xFormers for older GPUs, where it's needed, and avoid it for the newer cards that can use `torch-sdp` or other attention types.
This PR also points `torch` to the CUDA v12.4 extra-index-url for cpu-only Docker builds (not related to xformers issues).
The updated installer, built from this PR, is attached here.. Please test it on Windows and macOS for completeness. On the mac it should simply proceed with the installation without displaying the GPU selection menu, and should result in a working install.
[InvokeAI-installer-v5.1.0.zip](https://github.com/user-attachments/files/17294883/InvokeAI-installer-v5.1.0.zip)  
1. Unzip the installer and run …
=> Allow explicitly selecting xFormers at install time

invokeai/frontend/web/src/features/controlLayers/components/common/CanvasEntityPreviewImage.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasBackgroundModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasBboxModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterBase.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterControlLayer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterInpaintMask.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterRasterLayer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterRegionalGuidance.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityFilterer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectBrushLine.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectBrushLineWithPressure.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectEraserLine.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectEraserLineWithPressure.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectImage.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectRect.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasProgressImageModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStageModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolBrush.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolColorPicker.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolEraser.ts, invokeai/frontend/web/src/features/controlLayers/konva/util.ts
Handful of optimizations implemented while attempting to get a performant full canvas preview (unfortunately unsuccessful).
- Do not rely on internal Konva API for layer preview canvas (indirectly addresses #6950) 
- Track whether layers intersect the bbox
- Track whether layers are on-screen
- Disable Konva's "perfect draw" for all shapes
- Hide layers when they are both off-screen and not the selected layer
- Throttle opacity and compositing fill rendering to 100ms
- Reduce compositing rect rendering to minimum
Closes #6950
Have a play, should be no change to behaviour. I _think_ I can feel it is a bit snappier but could be wishful thinking. 
n/a
=> perf(ui): rendering optimizations

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/hooks/addLayerHooks.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterBase.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewCanvasFromImage.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewLayerFromImage.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemsNewImg2ImgCanvasFromImage.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx
- Clean up canvas add layer hooks
- Add layer post-init callback system
- Add mutex to `CanvasEntityTransformer` to prevent concurrent operations
- Use new init callback and transform mutex to implement `New Img2Img from Image`
- Disable the "new X from image" actions when canvas is busy
Scattered discord & offline discussions
- Right click an image in gallery
- Click `New Img2Img from Image`, which should:
- Reset the Canvas
- Optimize the bbox size, retaining the image's aspect ratio
- Fit the image exactly to the bbox
- You should be able to click Invoke immediately after this and it should do `img2img`.
- I've left `New Canvas from Image` and `New Img2Img from Image` separate, but maybe it's better to not add a new button for img2img and instead update the behaviour of `New Canvas …
=> feat(ui): img2img UX 2

invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/InpaintMask/InpaintMaskMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/RasterLayer/RasterLayerMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/common/CanvasEntityMenuItemsDelete.tsx
fix(ui): use non-icon version of delete menu item on canvas context menu
UI issue discovered in https://discord.com/channels/1020123559063990373/1149506274971631688/1293901265322901515
n/a
n/a
=> fix(ui): use non-icon version of delete menu item on canvas context menu

invokeai/backend/stable_diffusion/diffusers_pipeline.py
This PR adds a workaround for broken sliced attention on MPS with torch 2.4.1. The workaround keeps things working on MPS at the cost of increased peak memory utilization. Users who are unhappy with this should manually downgrade to `torch==2.2.2`.
Bug report: https://github.com/invoke-ai/InvokeAI/issues/7049
=> Add a workaround for broken sliced attention on MPS with torch 2.4.1

invokeai/frontend/web/src/features/nodes/util/graph/generation/addControlAdapters.ts
We were:
- Incrementing `addedControlNets` or `addedT2IAdapters`
- Attempting to add it, but maybe failing and skipping
Need to swap the order of operations to prevent misreporting of added cnet/t2i.
I don't think this would ever actually cause problems.
n/a
n/a
n/a
=> fix(ui): edge case where controladapters added counts could be off

invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterBase.ts, invokeai/frontend/web/src/features/controlLayers/store/selectors.ts
To trigger the edge case:
- Have an empty layer and non-empty layer
- Select the non-empty layer
- Refresh the page
- Select to the empty layer without doing any other action
- You may be unable to draw on the layer
- Zoom in/out slightly
- You can now draw on it
The problem was not syncing visibility when a layer is selected, leaving the layer hidden. This indirectly disabled interactions.
The fix is to listen for changes to the layer's selected status and sync visibility when that changes.
Also extracted common layer intersection logic to a method.
n/a
n/a
n/a
=> fix(ui): edge case where entity isn't visible until interacting with canvas

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/common/components/IAIDndImage.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageContextMenu.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryPagination.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/JumpTo.tsx
The gallery was getting very slow.
On `main`, on FF in dev mode, after loading 2 pages of the gallery so the images are cached, switching between them took ~105ms across 7 renders.
With the changes in this PR, that's down to ~55ms across 3 renders.
This translates to the initial load of gallery pages and switching tabs in the app. Feels way better.
Specific changes:
- Refactor image context menu to be a singleton. Previously, we were creating a new context menu component for _every_ visible image. When changing pages in the gallery, we had to create new menu components, which was hugely wasteful. Now there is a single context menu and we just update the image it is for, as it is opened.
- Defer a lot of logic in `IAIDndImage` & `GalleryImage` (rendering components, calling hooks) until …
=> perf(ui): gallery / image perf

invokeai/app/services/board_records/board_records_sqlite.py
Update enum usage in board service to work for python 3.11
Discord reported issue
Pull branch with a python 3.11 venv and try to load board list sorted in different ways
=> fix(api): update enum usage to work for python 3.11

pyproject.toml
On current main, many users are experiencing the following error while trying to run the app.
```
ImportError: DLL load failed while importing onnx_cpp2py_export
```
According to this [issue on the onnx github](https://github.com/onnx/onnx/issues/6267), as well as various other issue reports, it seems like more recent versions of onnx require a dll that many users don't have on windows machines. I will call out that it does work on my personal windows machine with the latest onnx build, but I suspect it requires ddls received from the latest visual studio tools installation, which many users will not have installed.
To remedy this in the short term, this PR fixes the versions to versions of onnx that are known to work when receiving the above error. …
=> fix: Pin onnx versions to builds that don't require rare dlls

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataActions.tsx, invokeai/frontend/web/src/features/metadata/util/handlers.ts, invokeai/frontend/web/src/features/metadata/util/parsers.ts, invokeai/frontend/web/src/features/metadata/util/recallers.ts
Properly set the "guidance" value for images created with flux models when using "Use All" from the context menu. Also display the "guidance" value in the metadata viewer.
https://github.com/invoke-ai/InvokeAI/commit/ffbf4aba1f4018f92efd2e7b1247c5cf2aaac821
https://github.com/invoke-ai/InvokeAI/commit/c224971cb41affa73f94cd4479a905149201984f
=> fix(ui): properly recall guidance value for flux images

invokeai/frontend/web/src/features/controlLayers/hooks/useEntityTransform.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts
Need to `await` the startTransform call so it can acquire the lock on concurrent transformation operations.
https://discord.com/channels/1020123559063990373/1020123559831539744/1295877271823060994
Right-click layer -> fit to bbox should work.
n/a
=>  fix(ui): fit to bbox just flashes transform handles 

invokeai/frontend/web/src/common/hooks/useImageUploadButton.tsx
Add error handling to the new error button so that the user gets feedback on what is not allowed about what they attempted to upload.
Try to upload an invalid file type or more files than allowed based on `maxImageUploadCount`. You should see an error toast explaining what went wrong.
=> fix(ui): add error handling to upload button

invokeai/frontend/web/src/features/gallery/components/GalleryUploadButton.tsx
fix(ui): upload tooltip should only show plural if multiple upload is enabled
=> fix(ui): upload tooltip should only show plural if multiple upload is enabled

invokeai/frontend/web/src/app/store/middleware/debugLoggerMiddleware.ts
While troubleshooting an issue with this middleware, I found the inclusion of the nextState and diff to be very noisy. It's now a function that accepts some options to configure the output, and returns the middleware.
n/a
The middleware is not added to the app unless you change `store.ts`, so this PR changes nothing in and of itself.
If you wanted to test, add the middleware to the store and try the options. For example, to omit the diff:
```diff
diff --git a/invokeai/frontend/web/src/app/store/store.ts b/invokeai/frontend/web/src/app/store/store.ts
index 7345f47d7..1873b27b9 100644
--- a/invokeai/frontend/web/src/app/store/store.ts
+++ b/invokeai/frontend/web/src/app/store/store.ts
@@ -3,6 +3,7 @@ import { autoBatchEnhancer, combineReducers, configureStore } from '@reduxjs/too
import { …
```
=> feat(ui): make debug logger middleware configurable

installer/install.sh.in
The installer needs to figure out if a compatible version of Python is installed and what its binary is called. On Linux, to do this, `which` is used to test possible candidates. However, `which` prints a message to stderr for every candidate that does not exist. To fix this, the error stream is simply routed to `/dev/null/`.
While working on this I also noticed that the installer is supposed to print a suggestion to maximize the window "for best user experience". However, the `echo` statement was put into an incorrect branch, so it only prints when no suitable Python version is found, just before exiting the installer. The fix is of course to move the statement out of the branch. Although telling the user to maximize the window so they can watch the script exit it full HD (maybe even …
=> Small improvements for the installer text output

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/app/logging/logger.ts, invokeai/frontend/web/src/app/logging/useLogger.ts, invokeai/frontend/web/src/app/logging/useSyncLoggingConfig.ts, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx, invokeai/frontend/web/src/index.ts
Introduce two-stage logging configuration and overrides for enabled status, log level and log namespaces.
The first stage in `<InvokeAIUI />`, before we set up redux (and therefore before we have access to the user's configured logging setup). In this stage, we use the overrides or default values.
The second stage is in `<App />`, after we set up redux, via `useSyncLoggingConfig`. In this stage, we use the overrides or the user's configured logging setup. This hook also handles pushing changes made by the user into localstorage.
Other changes:
- Extract logging config to util function
- Remove the `useEffect` from `SettingsModal` that was changing the logging settings
- Remove extraneous log effects from `useLogger`
n/a
Should be no difference in behaviour:
- You should see some `debug` …
=> refactor(ui): logging config handling

invokeai/app/invocations/flux_denoise.py
Fixes an issue where the workflow editor erroneously requires a connection for the field
https://discord.com/channels/1020123559063990373/1149510134058471514/1297983406440972464
You should be able to omit the connection.
n/a
=> fix(nodes): `FluxDenoiseInvocation.controlnet_vae` missing `default=None`

invokeai/app/invocations/flux_denoise.py, invokeai/backend/flux/denoise.py, tests/app/invocations/test_flux_denoise.py
Add support for Classifier-Free Guidance with FLUX.
- Using CFG doubles the time for the denoising process. Running both the positive and negative conditioning in a single batch is left for future work, because most users are already VRAM-constrained (this would probably be faster at the cost of higher peak VRAM).
- Negative text conditioning is optional and only required if `cfg_scale != 1.0`
- CFG is skipped if `cfg_scale == 1.0` (i.e. no compute overhead in this case)
- `cfg_scale_start_step` and `cfg_scale_end_step` can be used to easily control the range of steps that CFG is applied for.
- CFG is a prerequisite for IP-Adapter support.
Positive Caption: `Professional photography of a luxury hotel in the Nevada desert`
CFG: 1.0
Positive Caption: `Professional photography of a luxury …
=> FLUX CFG support

docker/Dockerfile, installer/lib/installer.py
Each version of torch is only available for specific versions of CUDA and ROCm. The Invoke installer tries to install torch 2.4.1 with ROCm 5.6 support, which does not exist. As a result, the installation falls back to the default CUDA version so AMD GPUs aren't detected. This commits fixes that by bumping the ROCm version to 6.1, as suggested by the PyTorch documentation.[^1] Torch 2.4.1 does not appear to be available for ROCm 6.2.
The specified CUDA version of 12.4 is still correct according to [^1] so it does need to be changed.
[^1]: https://pytorch.org/get-started/previous-versions/#v241
Closes #7006
Closes #7146
- Install Invoke 5.1.1 or later with ROCm support using the installer on a system with an AMD GPU.
- Start the server.
- Generate any image.
Without this fix, the  CPU is …
=> Fix AMD GPUs not being detected

invokeai/backend/flux/sampling_utils.py, invokeai/backend/quantization/gguf/ggml_tensor.py
builds on top of my last pull request, https://github.com/invoke-ai/InvokeAI/pull/7063, to get a subset of Flux working with Torch 2.4.1. so new installs can use it. With these change, fp16 Flux will work and GGUF quantised Flux will work.
bitandbytes quantised models will still not work.
https://github.com/invoke-ai/InvokeAI/issues/7060
https://discord.com/channels/1020123559063990373/1294664228757569587
It will need testing against none MacOS setups. Has been tested locally on MacOS using Flux Q8  and Q5.1 models
and is all wrapped in "if mps then"  code so it shouldn't have broke anything.
It's pretty straight forward to merge. Note I ran ruff against the directors these files are in but it made changes 
to other code and other files so I'm assuming ruff doesn't run against these. I …
=> Get flux working with MPS on torch 2.4.1, with GGUF support

invokeai/frontend/web/src/features/nodes/util/graph/graphBuilderUtils.ts
The browser/UI uses float 0-1 for alpha, while backend uses 0-255. We need to normalize the value when building the infill nodes for outpaint.
https://discord.com/channels/1020123559063990373/1149506274971631688/1298593181348265984
Change the infill alpha in Canvas compositing settings when outpainting. The transparency for the infill should work as expected.
n/a
=>  fix(ui): normalize infill alpha to 0-255 when building infill nodes

invokeai/frontend/web/src/features/gallery/components/GalleryHeader.tsx, invokeai/frontend/web/src/features/gallery/components/GalleryPanelContent.tsx
The use of hard 25% widths caused issues for some translations. Adjusted styling to not rely on any hard numbers. Tested with a project name and URL.
https://discord.com/channels/1020123559063990373/1054129386447716433/1298960174400409681
n/a
n/a
=> tweak(ui): prevent show/hide boards button cutoff

invokeai/app/services/shared/invocation_context.py, invokeai/frontend/web/src/features/controlLayers/components/CanvasDropArea.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasSegmentAnythingModule.ts
- Canvas drop area layout fix
- Do not delete SAM point on right click (which opens the menu)
- Fixed image cache issue that could cause all sorts of problems (not the invocation cache! that still has a perfect track record)
- Drop area: https://discord.com/channels/1020123559063990373/1149506274971631688/1299123024125235210
- Right click: https://discord.com/channels/1020123559063990373/1149506274971631688/1299129130041999371
- Cache issue: https://discord.com/channels/1020123559063990373/1149506274971631688/1298593181348265984
n/a
n/a
=> feat(ui): canvas auto-mask followups 4

invokeai/app/services/shared/invocation_context.py
fix(nodes): return copies of objects in invocation ctx
- Related to #7193 (fixes the issue for images only)
- Closes #6820
Suppose we could do some perf testing, but I don't think it really matters, as we need to make this change regardless.
n/a
=> fix(nodes): return copies of objects in invocation ctx

docs/contributing/dev-environment.md
Improve dev install docs
Fix numbering of numbered items with nested code
=> Improve dev install docs

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/CanvasAlerts/CanvasAlertsPreserveMask.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasAlerts/CanvasAlertsSelectedEntityStatus.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasAlerts/CanvasAlertsSendingTo.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasContextMenu/CanvasContextMenuSelectedEntityMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasMainPanelContent.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/Filters/Filter.tsx, invokeai/frontend/web/src/features/controlLayers/components/InpaintMask/InpaintMaskMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/RasterLayer/RasterLayerMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/SelectObject/SelectObject.tsx, invokeai/frontend/web/src/features/controlLayers/components/Transform/Transform.tsx, invokeai/frontend/web/src/features/controlLayers/components/Transform/TransformFitToBboxButtons.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/addLayerHooks.ts, invokeai/frontend/web/src/features/controlLayers/hooks/useEntityTransform.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStagingAreaModule.ts, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewFromImageSubMenu.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx
- Always show staging images when staging starts, even if user hid them last staging session
- Add layer title to the canvas ctx menu, above the layer-specific items
- Move canvas alerts to top-left corner
- Close viewer when starting a transform
- Update filter/select object/transform UI buttons (restore dedicated apply, remove busy icons, updated processing indicator)
- Organize layer ctx menu items (group & sort Copy, Convert, Crop, & Save)
- Add image ctx menu item to create new canvas as control layer (prev only could do as raster)
Canvas ctx menu:
<video src="https://github.com/user-attachments/assets/aceda24e-61e5-4d9f-89b2-ea92a06dde18"></video>
Image ctx menu:
<video src="https://github.com/user-attachments/assets/1c0f92de-1289-4f13-99fd-5a33109acf92"></video> …
=> feat(ui): canvas auto mask followups 6

invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImagePreview.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx
fix(ui): canvas alerts blocking metadata panel
discord thread
Fixed to look like this:
<video src="https://github.com/user-attachments/assets/76c5a17f-e163-4c88-a7f5-fbbe70db5c17"></video>
n/a
=> fix(ui): canvas alerts blocking metadata panel

invokeai/frontend/web/src/features/nodes/util/graph/generation/addImageToImage.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addInpaint.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addOutpaint.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addTextToImage.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildFLUXGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildSD1Graph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildSDXLGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/graphBuilderUtils.ts, invokeai/frontend/web/src/services/events/onInvocationComplete.tsx
- Use a constant to identify the canvas graph outputs - just some typo insurance.
- Use an object instead of multiple args for graph building utility functions (e.g. `addInpaint`)
- Rearrange the canvas paste-back to save ourselves on extraneous image resize. This is accomplished by doing the resize the output after the paste-back and not before, in which case we had to resize both the output image _and_ the mask image. The output is the same either way, with one less intermediate image and expensive PNG encode. 
The only functional change is the rearranged paste-back. The changes are localized to the inpaint and outpaint flows, and only when we are using a scaled bbox. I've tested the generation flows that could be affected by the change, with this matrix:
- Inpaint, & Outpaint
- `Output …
=> feat(ui): canvas graph improvements

invokeai/app/invocations/denoise_latents.py, invokeai/backend/stable_diffusion/extensions/preview.py
Added conversions that trigger on SDXL to change the color order for t2i image inputs, which is required for OpenPose to work correctly. TencentARC t2i adapters were trained on cv2 preprocessor outputs in BGR format. As far as I can tell, those are the only publicly available SDXL-T2I available at this time, and OpenPose is the only one that is not greyscale. Changing the image order has no effect on canny/depth/etc.
Fix is applied for both main backend and the as-of-yet-unused modular backend. Also I snuck in a fix for the progress bar so the modular backend doesn't crash before denoising begins.
https://www.reddit.com/r/StableDiffusion/comments/1f854k3/psa_fixing_sdxl_t2iadapter_openpose/
Before:
After:
=> Fix SDXL t2i adapters expect BGR instead of RGB

invokeai/frontend/web/src/features/controlLayers/components/Filters/Filter.tsx, invokeai/frontend/web/src/features/controlLayers/components/SelectObject/SelectObject.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityFilterer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectImage.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasSegmentAnythingModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStateApiModule.ts
- When filtering, we used the parent entity's buffer renderer to render the filter preview. An sloppy copy-paste resulted in the filter committing the buffer when it should have been cleared when saving-as. This fixes the only cause I can imagine for [this issue](https://discord.com/channels/1020123559063990373/1149506274971631688/1300882469658169377) reported by @skunkworxdark.
- But akshually, there's no need to use the buffer renderer at all. The canvas SAM module renders its canvas objects directly to the parent layer, without using the parent's object renderers. This better separates the logic. Updated the filter module to use this pattern instead.
- Update the filter module with the more resilient and clearer logic from the SAM module. Namely, using a hash to determine if we've …
=> fix(ui): canvas filter and SAM module fixes

invokeai/app/invocations/baseinvocation.py, tests/test_config.py
- Add method to force a rebuild of the pydantic type adapter for the union of invocations, which is used to validate graphs.
- Update the xfail'd test.
Supersedes #5893
- Manually queue a batch with a denylist'd node.
n/a
=> fix(nodes): nodes denylist handling

invokeai/app/invocations/baseinvocation.py, tests/test_node_graph.py
Adds some checks for invocations' implementations of the `invoke` method, raising an error when the method isn't defined correctly.
See discussion here https://discord.com/channels/1020123559063990373/1233408559065206865
@dunkeroni I expect this commit to prevent invoke from launching, erroring on the problematic node you are working on.
n/a
=> feat(nodes): add validation for invoke method return types

invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterBase.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityFilterer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasSegmentAnythingModule.ts
- When using save-as with filter/select-object, do not exit the filter/select-object. This facilitates common workflows that want to use the output of these features for multiple layers.
- Fix a bug that is exacerbated by this change that causes inpaint mask and regional guidance layers not rendering correctly.
https://discord.com/channels/1020123559063990373/1020123559831539744/1301301721565233172
Try save-as when filtering/select-object-ing. Mask layers should render as expected when you exit filter or select-object.
n/a
=> feat(ui): filter/select-object do not exit on save-as

pyproject.toml
Dependency resolution by `pip` is fairly lax, and allows fallback to the main PyPi index in case a matching distribution cannot be found. As we're working on an improved installation experience, this is becoming a blocker for installing Invoke using other tools, such as `uv`. Also, this work exposed some spots where some transitive dependencies might be overridden in spite of different version requirements by direct dependencies (e.g. `requests` was pinned to a version that is no longer valid).
This PR makes the minimal adjustments to the dependency pins, just to satisfy all direct dependencies and allow the package to be installed.
This is best tested using a tool that has follows strict dependency resolution rules, such as Astral's `uv`: https://github.com/astral-sh/uv. Install it prior …
=> Adjust pins for torch, numpy, other dependencies

installer/templates/invoke.sh.in
Removing period from update link to prevent page not found error
=> removing periods from update link to prevent page not found error

pyproject.toml
pip's dependency resolution doesn't take into account transitive dependencies when choosing package versions for download. Even though `torch=~2.4.1` is required by `diffusers`, pip will download 2.5.0 and higher, but only install 2.4.1. Pinning torch to <2.5.0 prevents this behaviour.
https://discord.com/channels/1020123559063990373/1149506274971631688/1301766243237494855
Failing test:
```
pip install --require-virtualenv --force-reinstall --use-pep517 invokeai==5.3.1 --extra-index-url https://download.pytorch.org/whl/cu124
```
This will download torch 2.5.1, but only install 2.4.1 (as expected)
Passing test:
```
pip install --require-virtualenv --force-reinstall --use-pep517 git+https://github.com/invoke-ai/InvokeAI.git@ebr/max-pin-torch --extra-index-url …
```
=> Pin torch to <2.5.0 to prevent unnecessary downloads

invokeai/frontend/web/src/common/util/fixTooltipCloseOnScrollStyles.ts, invokeai/frontend/web/src/features/controlLayers/hooks/saveCanvasHooks.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasCompositorModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityFilterer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasProgressImageModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasSegmentAnythingModule.ts, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardsList.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/WorkflowList.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/WorkflowListItem.tsx, invokeai/frontend/web/src/features/stylePresets/components/StylePresetImage.tsx, invokeai/frontend/web/src/features/stylePresets/components/StylePresetList.tsx
Fixes:
- Canvas progress images do not clear when canceling after at least one image has been staged. [discord](https://discord.com/channels/1020123559063990373/1149506274971631688/1302076076985684018)
- Tooltips on boards list persist when scrolling (temp workaround, no clear long-term solution, pending upstream bug report). [discord](https://discord.com/channels/1020123559063990373/1149506274971631688/1302093372328251433)
- Saving canvas to gallery (and certain other image actions that composite and upload an image), do not create a new image in gallery. [discord](https://discord.com/channels/1020123559063990373/1149506274971631688/1302252612577398886)
- Filters can bork their source layers after applying. 
Linked inline.
Should fix the listed issues.
Probably should do a bugfix release …
=> fix(ui): misc fixes

invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryMenu/WorkflowLibraryMenu.tsx
In a8de6406c5e12e8fae7a6aef97c4fb606880b67f a change was made to many menus in an effort to improve performance. The menus were made to be lazy, so that they are mounted only while open.
This causes unexpected behaviour when there is some logic in the menu that may need to execute after the user selects a menu item.
In this case, when you click to load a workflow from file, the file picker opens but then the menuitem unmounts, taking the input element and all uploading logic with it. When you select a file, nothing happens because we've nuked the handlers by unmounting everything.
Easy fix - un-lazy-fy the menu.
Closes #7240
Loading workflow from the three-dots menu should work.
n/a
=> fix(ui): load workflow from file

pyproject.toml
We have received some reports of `mediapipe` failing to install on Windows. Version `0.0.18` was released on 2024-11-01, and is published to pypi, but not released in their Github repo.
Pinning it to the known working `v0.0.14` for now.
https://discord.com/channels/1020123559063990373/1020123559831539744/1302911486066163712
Install Invoke on windows and confirm that `mediapipe` is present.
Merge anytime
=> fix(deps): pin mediapipe strictly to a known working version

invokeai/backend/model_manager/util/model_util.py
This can fail if the folder isn't formatted how we expect it to be. This should never cause a model to fail so I wrapped it in a try catch.
Attempt to install any flux main model bundle in starter models and confirm InvokeAI/clip-vit-large-patch14-text-encoder::bfloat16 installs correctly
Can be merged when tested/approved
=> fix: Never throw an exception when finding the clip variant type

invokeai/app/api/routers/app_info.py, invokeai/frontend/web/src/features/ui/components/WhatsNew.tsx, invokeai/frontend/web/src/services/api/schema.ts
* Updates app_info router to have optional highlights list so that Whats New module can get data from back-end instead of being hard-coded in UI
* Updates release notes URL to be dynamic based on current version
=> feat(api,ui): allow Whats New module to get content from back-end

invokeai/backend/model_manager/util/model_util.py
Missed one spot in an earlier bugfix PR where get_clip_variant_type is returning None
=> fix: get_clip_variant_type should never return None

invokeai/frontend/web/knip.ts, invokeai/frontend/web/src/features/parameters/types/parameterSchemas.ts
- Simplify parameter schema declaration.
- Export some unused `zParameter` variables.
- Exclude the schema file in `invokeai/frontend/web/knip.ts`.
I prefer this concise version as it’s the most readable. In my opinion, more selective exports add unnecessary verbosity again.
https://github.com/invoke-ai/InvokeAI/pull/7217#discussion_r1820027840
=> feat(ui): simplify parameter schema declaration

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageDropped.ts, invokeai/frontend/web/src/app/store/nanostores/util.ts, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayer.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerControlAdapter.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerSettings.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerSettingsEmptyState.tsx, invokeai/frontend/web/src/features/controlLayers/components/Filters/Filter.tsx, invokeai/frontend/web/src/features/controlLayers/components/RasterLayer/RasterLayerMenuItemsConvertToSubMenu.tsx, invokeai/frontend/web/src/features/controlLayers/components/RasterLayer/RasterLayerMenuItemsCopyToSubMenu.tsx, invokeai/frontend/web/src/features/controlLayers/components/common/CanvasEntityGroupList.tsx, invokeai/frontend/web/src/features/controlLayers/components/common/CanvasEntityPreviewImage.tsx, invokeai/frontend/web/src/features/controlLayers/contexts/EntityAdapterContext.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/addLayerHooks.ts, invokeai/frontend/web/src/features/controlLayers/hooks/saveCanvasHooks.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityFilterer.ts, invokeai/frontend/web/src/features/controlLayers/store/filters.ts, invokeai/frontend/web/src/features/controlLayers/store/util.ts, invokeai/frontend/web/src/features/deleteImageModal/components/DeleteImageButton.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CompareToolbar.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImageButtons.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ToggleMetadataViewerButton.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ToggleProgressButton.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ViewerToolbar.tsx, invokeai/frontend/web/src/features/parameters/components/PostProcessing/PostProcessingPopover.tsx
- Update viewer styling to have a menubar-ish header. Also used for image comparison.
- Set default control weight & end step % to 0.75.
- Add " (recommended)" to the "Balanced" control mode label.
- Add tooltip to layer preview image showing the layer at the same size as the boards/style presets image preview tooltips.
- Add empty state for control layers guiding user to upload an image, drag an image from gallery or start drawing.
- Add "simple" mode for control layers filtering, triggered when you select a control model. This automatically selects and processes the default filter for that model, if a default exists. If the user clicks `Advanced`, they get the full filter settings UI.
- Default control layers to no model selection.
Offline discussion.
Try the changes out.
n/a
=> feat(ui): new user ux improvements

invokeai/backend/model_manager/util/model_util.py
Currently if a text encoder is in a subfolder of a climpembed, we have no way of determining its variant. This enables our probe to search deeper than the root directory.
Install InvokeAI/clip-vit-large-patch14-text-encoder::bfloat16 and validate it checks the text_encoder via debugger
=> fix: Look in known subfolders for configs for clip variants

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedLinear.ts, invokeai/frontend/web/src/common/util/extractMessageFromAssertionError.ts, invokeai/frontend/web/src/features/controlLayers/hooks/addLayerHooks.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addIPAdapters.ts
When creating a reference image (global or regional) we were not setting the CLIP vision model correctly. As a result, FLUX IP Adapters, which require the `ViT-L` model, were causing errors. 
This situation is now handled.
Also, when graph building fails, we now display an error toast. Previously, there was no feedback at all, so it felt like the invoke button just did nothing.
This won't fix existing misconfigured IP Adapters, but it does prevent new ones from ending up with the wrong CLIP vision model selection.
n/a
=> fix(ui): FLUX IP adapter clip vision model error

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageUploaded.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasCompositorModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts, invokeai/frontend/web/src/services/api/endpoints/images.ts
This is needed after a change to image uploading introduced by dnd migration.
- Add `withToast` flag to `uploadImage` util
- Skip the toast if this is not set
- Use the flag to disable toasts when canvas does internal image-uploading stuff that should be invisible to user
=> fix(ui): excessive toasts when generating on canvas

invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasBboxToolModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/util.test.ts, invokeai/frontend/web/src/features/controlLayers/konva/util.ts
The math used to fit the bbox to layers was a bit off and could result in a bbox that was slightly too large. 
Issue that prompted me to review the logic: https://discord.com/channels/1020123559063990373/1020123559831539744/1304232644338384927
The fit bbox to layers button should always result in the bbox being the same size as the composite of all raster layers, or smaller. The issue affects layers whose size is not already a multiple of the grid size (8px or 16px depending on model).
This image triggers the issue when it is the only layer - could test with it.
=> fix(ui): fit bbox to layers math

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/hooks/useIsReadyToEnqueue.ts, invokeai/frontend/web/src/features/settingsAccordions/components/UpscaleSettingsAccordion/UpscaleWarning.tsx
When an unsupported model architecture is selected, show that warning only, without the extra warnings (i.e. no "missing tile controlnet" warning)
Update Invoke tooltip warnings accordingly
Closes #7239
Closes #7177
You won't be able to choose FLUX or SD3.5 models when on the upscaling tab - but you can from the canvas tab. Choose one of those model types for your main model, then go to the upscaling tab.
You should get a message about unsupported model architecture instead of a misleading message about missing the tile upscaling model. Also, the invoke button tooltip should warn about incompatible model.
n/a
=> feat(ui): update warnings on upscaling tab based on model arch

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/ParamDenoisingStrength.tsx
- `Disabled - No Raster Layers` -> `Disabled (No Raster Content)`
- Made it a single string so translators can more freely translate
=> feat(ui): clarify denoising strength badge text

invokeai/app/invocations/compel.py, invokeai/app/invocations/create_denoise_mask.py, invokeai/app/invocations/create_gradient_mask.py, invokeai/app/invocations/flux_text_encoder.py, invokeai/app/invocations/flux_vae_decode.py, invokeai/app/invocations/flux_vae_encode.py, invokeai/app/invocations/image_to_latents.py, invokeai/app/invocations/latents_to_image.py, invokeai/app/invocations/sd3_latents_to_image.py, invokeai/app/invocations/sd3_text_encoder.py, invokeai/app/services/shared/invocation_context.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/features/controlLayers/components/CanvasAlerts/CanvasAlertsInvocationProgress.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasMainPanelContent.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImagePreview.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsMenu.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx, invokeai/frontend/web/src/features/system/store/systemSlice.ts, invokeai/frontend/web/src/features/system/store/types.ts, invokeai/frontend/web/src/services/events/stores.ts, tests/app/services/model_load/test_load_api.py, tests/test_nodes.py
* add invocation progress events to model loading
* render invocation progress messages on viewer/canvas as canvas alerts
Invoke to either gallery or canvas, see invocation progress details (model loading, denoising)
=> feat(ui, worker): add invocation progress events to model loading

invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx
The styling in gallery for selected vs hovered was very similar, leading users to think that the hovered image was also selected.
Reducing the borders for hovered images to a single pixel makes it easier to distinquich between selected and hovered.
https://discord.com/channels/1020123559063990373/1149506274971631688/1304457546563584011
Before:
<video src="https://github.com/user-attachments/assets/8c5a3afd-a86b-470c-b166-faab74e169b3"></video>
After:
<video src="https://github.com/user-attachments/assets/c8a9a5b4-bce7-4b6f-9fcf-d1d21fd5fc81"></video>
=> feat(ui): tweak image selection/hover styling

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageUploaded.ts, invokeai/frontend/web/src/common/hooks/useImageUploadButton.tsx, invokeai/frontend/web/src/features/controlLayers/components/StagingArea/StagingAreaToolbarSaveSelectedToGalleryButton.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/saveCanvasHooks.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasCompositorModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts, invokeai/frontend/web/src/features/dnd/FullscreenDropzone.tsx, invokeai/frontend/web/src/features/nodes/util/graph/generation/addImageToImage.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addInpaint.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addOutpaint.ts, invokeai/frontend/web/src/services/api/endpoints/images.ts, invokeai/frontend/web/src/services/api/types.ts
Rework uploadImage and uploadImages helpers and the RTK listener, ensuring gallery view isn't changed unexpectedly and preventing extraneous toasts.
Fix staging area save to gallery button to essentially make a copy of the image, instead of changing its intermediate status.
Multiple threads on discord
Test functionality that uploads an image:
- Generating on canvas, which uploads images for each layer type
- Clicking save to gallery on the canvas toolbar
- Clicking save to gallery on the staging area toolbar
- Uploading an image using a button (e.g. upscale initial image, node image field, control layer, ref image)
Probably bout time for a release.
=> fix(ui): image uploading handling

invokeai/frontend/web/src/features/controlLayers/components/CanvasEntityList/useCanvasEntityListDnd.ts, invokeai/frontend/web/src/features/dnd/DndImage.tsx, invokeai/frontend/web/src/features/dnd/util.ts, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/useLinearViewFieldDnd.ts
Fixes a Firefox-only bug that prevents text selection for `input` and `textarea` elements within draggables. This made it tricky to use linear view workflow fields and control layers.
Discord discussion
- Edit a prompt in a regional guidance layer
- Edit the name of a layer
- Edit any text field in a linear view workflow field
=> fix(ui): unable to use text inputs within draggable

invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx
fix(ui): multiple selection dnd sometimes doesn't get full selection
Discord: https://discord.com/channels/1020123559063990373/1149506274971631688/1306665643898175490
- Click the first image in a board.
- Hold shift and click a different image to get a multi-selection going on.
- Click and drag the first image in the board. You should get a multi-image drag.
=> fix(ui): multiple selection dnd sometimes doesn't get full selection

invokeai/frontend/web/src/services/events/stores.ts
Remove extraneous condition that would hide the progress message if the generation's destination was not canvas (this was left in from an earlier iteration of the feature)
=> fix(ui): remove progress message condition for canvas destinations

invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/ImageMetadataActions.tsx
add padding to the metadata recall section so buttons are not blocked
Closes https://github.com/invoke-ai/InvokeAI/issues/7325
=> fix(ui): add padding to the metadata recall section so buttons are not blocked

invokeai/frontend/web/src/features/controlLayers/components/CanvasAlerts/CanvasAlertsSelectedEntityStatus.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasContextMenu/CanvasContextMenuSelectedEntityMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayer.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerBadges.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerControlAdapter.tsx, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerMenuItemsTransparencyEffect.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapter.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterSettings.tsx, invokeai/frontend/web/src/features/controlLayers/components/InpaintMask/InpaintMask.tsx, invokeai/frontend/web/src/features/controlLayers/components/RasterLayer/RasterLayer.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidance.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceBadges.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceIPAdapters.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceMenuItemsAutoNegative.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceNegativePrompt.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidancePositivePrompt.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceSettings.tsx, invokeai/frontend/web/src/features/controlLayers/contexts/CanvasEntityStateGate.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/addLayerHooks.ts, invokeai/frontend/web/src/features/controlLayers/store/selectors.ts
The canvas react components pass canvas entity identifiers around, then redux selectors are used to access that entity. This is good for perf - entity states may rapidly change. Passing only the identifiers allows components and other logic to have more granular state updates.
Unfortunately, this design opens the possibility for for an entity identifier to point to an entity that does not exist.
To get around this, I had created a redux selector `selectEntityOrThrow` for canvas entities. As the name implies, it throws if the entity is not found.
While it prevents components/hooks from needing to deal with missing entities, it results in mysterious errors if an entity is missing. Without sourcemaps, it's very difficult to determine what component or hook couldn't find the entity. …
=> fix(ui): prevent entity not found errors

invokeai/backend/flux/ip_adapter/state_dict_utils.py, invokeai/backend/flux/ip_adapter/xlabs_ip_adapter_flux.py, invokeai/backend/model_manager/starter_models.py, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildFLUXGraph.ts, tests/backend/flux/ip_adapter/test_xlabs_ip_adapter_flux.py, tests/backend/flux/ip_adapter/xlabs_flux_ip_adapter_v2_state_dict.py
This PR adds support for the XLabs FLUX IP-Adapter v2 model (https://huggingface.co/XLabs-AI/flux-ip-adapter-v2).
The recommended inference configuration for XLabs IP v2 is different than that for v1:
- v1 works well with cfg_start_step=1 and cfg_scale=3
- v2 works well with cfg_scale=1 (i.e. no CFG)
This PR updates the Linear UI behavior to optimize for v2. As a result, the performance of v1 models in the Linear UI will be significantly degraded.
It is still possible to use the v1 models by manually constructing a workflow like the one shown on the original IP-Adapter v1 PR: https://github.com/invoke-ai/InvokeAI/pull/7157
**Example 1:**
- Promp: `a statue wearing sunglasses`
- ip-adapter weight: 0.8
- In order (left to right, top to bottom):
- Original
- IP-Adapter v2
- IP-Adapter v1 …
=> XLabs FLUX IP-Adapter v2

invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbarResetCanvasButton.tsx
feat(ui): change reset canvas icon to "empty"
https://discord.com/channels/1020123559063990373/1308084638023028807/1308084638023028807
=> feat(ui): change reset canvas icon to "empty"

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/features/system/components/VideosModal/VideoCard.tsx, invokeai/frontend/web/src/features/system/components/VideosModal/VideoCardList.tsx, invokeai/frontend/web/src/features/system/components/VideosModal/VideosModal.tsx, invokeai/frontend/web/src/features/system/components/VideosModal/VideosModalButton.tsx, invokeai/frontend/web/src/features/system/components/VideosModal/data.ts, invokeai/frontend/web/src/features/ui/components/VerticalNavBar.tsx
Add a modal w/ links to our support videos on youtube.
<video src="https://github.com/user-attachments/assets/e618c37b-3ebd-40c0-aeb6-0e1f6fa09874"></video>
=> feat(ui): support videos modal

invokeai/backend/model_manager/probe.py
Make sure Soft Edge Detection has correct string matching for preprocessor
=> fix(api): make sure Soft Edge Detection has preprocessor applied

invokeai/frontend/web/src/features/nodes/util/schema/parseSchema.ts
There's a technical challenge with outputting these values directly. `ImageField` does not store them, so the batch's `ImageField` collection does not have width and height for each image.
In order to set up the batch and pass along width and height for each image, we'd need to make a network request for each image when the user clicks Invoke. It would often be cached, but this will eventually create a scaling issue and poor user experience.
As a very simple workaround, users can output the batch image output into an `Image Primitive` node to access the width and height.
This change is implemented by adding some simple special handling when parsing the output fields for the `image_batch` node.
I'll keep this situation in mind when extending the batching system to other field types. …
=> fix(ui): disable width and height output on image batch output

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/app/hooks/useStudioInitAction.ts
Makes sure that the schema has been loaded and parsed before the UI tries to load any workflows. Solves a race conditions where edges didn't appear for workflows passed in a studio init action
=> fix(ui): make sure schema has loaded before trying to load any workflows

invokeai/frontend/web/src/common/hooks/focus.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStateApiModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasMoveToolModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolModule.ts, invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts
Adds the ability to nudge layers by a single pixel on canvas. Nudging is allowed when the move tool is selected, or when the selected entity is being transformed.
- This PR picks up on #7202, which had stalled. I didn't have permission to push to the contributor's fork, so I needed to create this new branch to address my feedback from that PR.
Should do what it says on the tin.
n/a
=> feat(ui): nudge on canvas

invokeai/frontend/web/src/features/controlLayers/components/StagingArea/StagingAreaToolbarSaveSelectedToGalleryButton.tsx
If there is a token in the store, use it to download the image before re-uploading copy
=> fix(ui): use token for download if its in store

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterMethod.tsx, invokeai/frontend/web/src/features/system/components/VideosModal/data.ts
* Updates information tooltip copy for: Begin/End Step Percentage, IP Adapter Mode (previously Method), ControlNet Weight
* Adds descriptions to the IP Adapter Method dropdown that will display if user has Model Descriptions turned on
* Updates youtube link
=> misc(ui): various copy updates

invokeai/app/invocations/flux_text_encoder.py, invokeai/app/invocations/image_panels.py
This PR adds a `ImagePanelLayoutInvocation` that makes it easy to calculate the coordinates of panels within an image grid. This utility invocation is intended to make it easier to experiment with In-Context LoRA workflows.
Instructions:
1. Install this LoRA: https://huggingface.co/ali-vilab/In-Context-LoRA/blob/main/visual-identity-design.safetensors
2. Load the sample workflow: [flux_icl_single_reference_image.json](https://github.com/user-attachments/files/17873610/flux_icl_single_reference_image.json)
3. Run.
Workflow
Sample output (cherry-picked, full grid):
Sample output (cherry-picked, cropped):
Instructions:
1. Install this LoRA: https://huggingface.co/ali-vilab/In-Context-LoRA/blob/main/film-storyboard.safetensors
2. Load the sample workflow: …
=> Add `ImagePanelLayoutInvocation` utility to facilitate In-Context LoRA workflows

pyproject.toml
This PR bumps the `transformers` dependency to address a DepthAnything post-processing bug.
Closes #7358 
Before:
After:
- Description of the DepthAnything artifact bug: https://github.com/invoke-ai/InvokeAI/issues/7358
- Relevant fix upstream in transformers: https://github.com/huggingface/transformers/pull/32550
- Related issues / discussions:
- https://github.com/huggingface/transformers/issues/34300
- https://github.com/huggingface/transformers/pull/34413
=> Bump transformers to ingest a DepthAnything post-processing fix

invokeai/frontend/web/src/features/controlLayers/components/StagingArea/StagingAreaToolbar.tsx, invokeai/frontend/web/src/features/controlLayers/components/StagingArea/StagingAreaToolbarSaveAsMenu.tsx, invokeai/frontend/web/src/features/controlLayers/components/StagingArea/StagingAreaToolbarSaveSelectedToGalleryButton.tsx, invokeai/frontend/web/src/features/imageActions/actions.ts, invokeai/frontend/web/src/services/api/endpoints/images.ts
When staging images, users may now save the current image as a new layer without accepting the current image or needing to do the round-trip of saving to gallery and then creating the layer.
The layers are created in a disabled state, to not interfere with the current canvas setup. All layer types are supported. Images are duplicated when creating the layer
n/a
n/a
n/a
=> feat(ui): add `New Layer from Image` menu to staging area toolbar

invokeai/frontend/web/src/common/hooks/useGlobalHotkeys.ts, invokeai/frontend/web/src/features/queue/components/ClearQueueButton.tsx, invokeai/frontend/web/src/features/queue/components/ClearQueueConfirmationAlertDialog.tsx, invokeai/frontend/web/src/features/queue/components/ClearQueueIconButton.tsx, invokeai/frontend/web/src/features/queue/components/QueueActionsMenuButton.tsx, invokeai/frontend/web/src/features/queue/hooks/useClearQueue.ts, invokeai/frontend/web/src/features/ui/components/FloatingParametersPanelButtons.tsx
Moves the `useClearQueue` hook to a separate file (like other queue related hooks).
=> refactor(ui): move clear queue hook to separate file

invokeai/frontend/web/src/features/queue/components/QueueActionsMenuButton.tsx
The cancel button in `<QueueActionsMenuButton />` erroneously calls "clear queue" instead of "cancel queue item".
Creates a conflict without https://github.com/invoke-ai/InvokeAI/pull/7391 due to changes on subsequent lines. Will rebase once merged/rejected/closed.
=> fix(ui): call cancel instead of clear queue

invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceIPAdapterSettingsEmptyState.tsx
It was easy to misunderstand the empty state for a regional guidance reference image. There was no label, so it seemed like it was the whole region that was empty.
This small change adds the "Reference Image" heading to the empty state, so it's clear that the empty state messaging refers to this reference image, not the whole regional guidance layer.
n/a
This is what was added
n/a
=> feat(ui): less confusing empty state for rg ref images

invokeai/frontend/web/src/features/controlLayers/hooks/addLayerHooks.ts, invokeai/frontend/web/src/features/imageActions/actions.ts
A redux selector is used to get the "default" IP Adapter. The selector uses the model list query result to select an IP Adapter model to be preset by default.
The selector is memoized, so if we mutate the returned default IP Adapter state, it mutates the result of the selector for all consumers.
For example, the `image` property of the default IP Adapter selector result is `null`. When we set the `image` property of the selector result while creating an IP Adapter, this does not trigger the selector to recompute its result. We end up setting the image for the selector result directly, and all other consumers now have that same image set.
Solution - we need to clone the selector result everywhere it is used. This was missed in a few spots, causing the issue.
Reported offline
- Drag an …
=> fix(ui): ref image defaults to prev ref image's image selection

invokeai/frontend/web/src/features/queue/components/InvokeButtonTooltip/InvokeButtonTooltip.tsx
The "adding to" text indicates if images are going to the gallery or staging area. This info is relevant only to the canvas tab, but was displayed on Upscaling and Workflows tabs. Removed it from those tabs.
n/a
n/a
n/a
=> fix(ui): remove "adding to" text on Invoke tooltip on Workflows/Upscaling tabs

invokeai/app/services/session_processor/session_processor_default.py
Fixes a bug in the session processor where a cancel event for any queue item was triggering the processor to cancel the current queue item.
Closes https://github.com/invoke-ai/InvokeAI/issues/7414
Queue up a batch of generations and cancel some at the end. The currently processing queue item should still finish and have expected output appear.
Should be reviewed by @psychedelicious before merge
=> fix(worker): only apply processor cancel logic if cancel event is for current item

invokeai/backend/model_manager/util/model_util.py
Importing a `gguf` file results in:
`Exception: The model file "blah.gguf" is potentially infected by malware. Aborting import.`
This happens because `gguf` files are scanned for malware and return an error; the file format does not suffer from the same problems as pickled files and does not need to be scanned.
This PR removes the scan from `gguf` files but keeps it for other potentially-unsafe formats.
=> Fix gguf importing

docs/contributing/ARCHITECTURE.md, docs/contributing/INVOCATIONS.md, docs/contributing/MODEL_MANAGER.md, docs/contributing/TESTS.md, docs/contributing/contribution_guides/development.md, docs/contributing/contribution_guides/newContributorChecklist.md, docs/contributing/dev-environment.md, docs/contributing/index.md, invokeai/frontend/web/README.md
I was reading the docs and saw lots of broken links, bad paths, extra ]'s, and incorrectly indented code blocks so I fixed most of them.
I ran mkdocs to make sure the links were all correct.
Should be able to be merged without problem.
=> [docs] Fix documentation broken links and remove whitespace at end of lines

invokeai/frontend/web/public/locales/en.json, invokeai/version/invokeai_version.py
chore: bump version to v5.4.3rc2
n/a
n/a
There are a number of pending PRs. After those have merged we should do a release.
=> chore: bump version to v5.4.3rc2

invokeai/app/services/session_processor/session_processor_default.py
The `is` operator compares references, not values. Thanks to a wonderfully unintuitive quirk of python, `is` works on integers from `-5` to `256`, inclusive.
Whenever integers in this range are used for a value, internally python returns a reference to a stable object in memory. When integers outside this range are used as a value, python creates a new object in memory for that integer.
See `PyLong_FromLong` documentation here: https://docs.python.org/3/c-api/long.html
Tying this back to our session processor, we were using `is` to compare the queue item ids for equality. Our queue item ids start at 0, and each queue item created increments this by one. So this comparison works only for the first 256 queue items on the machine.
Starting with the 257th queue item, the comparison starts …
=> fix(app): processor cancelation weirdness

invokeai/frontend/web/src/features/nodes/util/graph/generation/addIPAdapters.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addRegions.ts
I missed a spot in #7388.
https://discord.com/channels/1020123559063990373/1149506274971631688/1313348384693813298
Global Reference Images should be skipped when disabled.
n/a
=> fix(ui): skip disabled global reference image

invokeai/backend/flux/math.py
https://github.com/invoke-ai/InvokeAI/issues/7422
As reported in the above ticket, a recent FLUX performance improvement caused a regression on MacOS. This PR reverts the offending part of the change.
- Closes #7422 
- Original perf improvement: https://github.com/invoke-ai/InvokeAI/pull/7399
I don't have a Mac capable of running this test, so trusting the report in #7422 that this fixes the problem.
=> Revert FLUX performance improvement that fails on MacOS

docker/Dockerfile, docker/docker-entrypoint.sh, invokeai/app/invocations/__init__.py, invokeai/app/services/config/config_default.py, invokeai/app/services/shared/sqlite_migrator/migrations/migration_11.py, pyproject.toml
- upgrades docker image to ubuntu 24.04 (contributed by @rick-github)
- adds support in docker entrypoint for keeping HF cache in the invoke runtime directory, unless specified otherwise - this should help avoid unnecessary redownloads from HF (contributed by @rick-github)
- ubuntu 24.04 ships with python 3.12, so this PR changes our package management backend to use `uv`, including the installation of python itself. This will both improve performance when using docker cache, and decouple python versioning from the underlying OS.
- fixes: legacy model configs were being copied with their permissions intact. Because we're trying to copy them on every startup, this would cause the application to fail to start when the source code directory is read-only, because it could not overwrite the …
=> [docker] upgrade to ubuntu 24.04 + use uv for package management

invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewLayerFromImageSubMenu.tsx
The image context menu had the actions for global and regional reference layers swapped
=> fix(ui): image context menu -> create layer from -> swap regional/global actions

mkdocs.yml
The patchmatch lib links directly to our docs: https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/
That URL doesn't exist any more. Added a redirect to the new URL.
n/a
n/a
n/a
=> docs: add redirect for patchmatch docs

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedLinear.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketConnected.ts, invokeai/frontend/web/src/common/util/result.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasCompositorModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterBase.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityFilterer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasSegmentAnythingModule.ts
Improve error handling and logging for:
- Canvas layer rasterization, which occurs during transform, filter, select and crop operations
- Canvas layer compositing, which occurs during graph building
- Canvas generation mode calculations, which occurs during graph building
Minor additional changes:
- Remove duplicate log message when socket connects
- Simplify the handling of the `enqueueRequested` graph building RTK Q listener
These improvements should prevent canvas from getting stuck in a various processing states when an operation fails.
To test this, you could try this diff, which makes most uploads from within the app fail. This (hopefully) replicates a spotty/dropped network connection. There are other ways that canvas operations could fail, but this is the …
=> feat(ui): improved canvas/queue error handling

invokeai/app/invocations/flux_control_lora_loader.py, invokeai/backend/patches/layers/set_parameter_layer.py, invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerControlAdapter.tsx, invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/controlLayers/store/util.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addControlAdapters.ts, invokeai/frontend/web/src/services/api/schema.ts
Add the ability to control the weight of a FLUX Control LoRA.
Original image:
<div style="display: flex; gap: 10px;">
</div>
Prompt: `a scarecrow playing tennis`
Weights: 0.4, 0.6, 0.8, 1.0
<div style="display: flex; gap: 10px;">
</div>
<div style="display: flex; gap: 10px;">
</div>
**_Do not merge this PR yet._**
1. Merge #7450 
2. Merge #7446 
3. Change target branch to main
4. Merge this branch.
=> Add FLUX Control LoRA weight param

invokeai/backend/model_manager/starter_models.py
add Canny and Depth FLUX control loras to starter models
=> add FLUX control loras to starter models

invokeai/frontend/web/src/features/controlLayers/components/ControlLayer/ControlLayerControlAdapter.tsx
Depending on network latency, there was a race condition where filters would run twice and improved error handling showed a toast to user that previously was swallowed. This solves the root issue.
=> fix(ui): fix double filter on slow networks

invokeai/app/services/model_install/model_install_default.py
This is just a small fix for this minor but annoying issue: https://github.com/invoke-ai/InvokeAI/issues/6517
It just strips quotes from the local path string before it's used.  It should only affect local paths.
Not sure if this is the best place to apply the fix or cleanest approach, but it seems to work.
=> Fix error message when adding a local path with quotes (issue #6517)

invokeai/app/api_app.py, invokeai/app/services/config/config_default.py, invokeai/app/services/session_processor/session_processor_default.py
[feat(api): less verbose uvicorn logs](https://github.com/invoke-ai/InvokeAI/commit/97857430cb6b783759b5076bd8c7fa0b58596cba)
Uvicorn's logging is rather verbose. This change adds a `log_level_network` config setting to independently control uvicorn's log outputs. The setting defaults to warning.
The change hides this helpful startup message that says the host and port we are running on:
```
Uvicorn running on http://0.0.0.0:9090/ (Press CTRL+C to quit)
```
The ASGI lifespan handler is updated to log a similar message on startup, regardless of log level settings:
```
Invoke running on http://0.0.0.0:9090 (Press CTRL+C to quit)
```
Besides being helpful, the launcher relies on a message like this to launch the app. So, previously, if the user set their log level to anything above info …
=> feat(api): less verbose uvicorn logs

invokeai/app/invocations/create_denoise_mask.py, invokeai/app/invocations/create_gradient_mask.py, invokeai/app/invocations/image_to_latents.py, invokeai/app/invocations/latents_to_image.py
Address non-determinism in the typegen creation process. Set fixed default values.
https://github.com/invoke-ai/InvokeAI/pull/7463
=> fix(app): fixed InputField default values

.github/workflows/typegen-checks.yml
Workflow to check whether the generated frontend types in `invokeai/frontend/web/src/services/api/schema.ts` match those on the server.
There still appears to be some non-determinism in the typegen creation process. Depending on the Torch installation (CPU, GPU, etc.), the default value of an InputField may change.
Example: https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/app/invocations/create_denoise_mask.py#L33
```py
DEFAULT_PRECISION = TorchDevice.choose_torch_dtype()
fp32: bool = InputField(
default=DEFAULT_PRECISION == torch.float32,
description=FieldDescriptions.fp32,
ui_order=4,
)
```
- Address non-determinism (my suggestion: use a fixed default value) https://github.com/invoke-ai/InvokeAI/pull/7464
- Ensure schema is up-to-date: …
=> feat(ci): add typegen check workflow

invokeai/backend/model_manager/load/model_cache/cached_model/cached_model_only_full_load.py, invokeai/backend/model_manager/load/model_cache/cached_model/cached_model_with_partial_load.py, invokeai/backend/model_manager/load/model_cache/torch_module_autocast/autocast_modules.py, invokeai/backend/model_manager/load/model_cache/torch_module_autocast/cast_to_device.py, invokeai/backend/model_manager/load/model_cache/torch_module_autocast/custom_invoke_linear_8_bit_lt.py, invokeai/backend/model_manager/load/model_cache/torch_module_autocast/custom_invoke_linear_nf4.py, invokeai/backend/model_manager/load/model_cache/torch_module_autocast/torch_module_autocast.py, invokeai/backend/quantization/bnb_llm_int8.py, pyproject.toml, tests/backend/model_manager/load/model_cache/cached_model/test_cached_model_only_full_load.py, tests/backend/model_manager/load/model_cache/cached_model/test_cached_model_with_partial_load.py, tests/backend/model_manager/load/model_cache/cached_model/utils.py, tests/backend/model_manager/load/model_cache/torch_module_autocast/test_autocast_modules.py, tests/backend/model_manager/load/model_cache/torch_module_autocast/test_torch_module_autocast.py, tests/backend/quantization/test_bnb_llm_int8.py
This PR adds utilities to support partial loading of models from CPU to GPU. The new utilities are not yet being used by the ModelCache, so there should be no functional behavior changes in this PR.
Detailed changes:
- Add autocast modules that are designed to wrap common `torch.nn.Module`s and enable them to run with automatic device casting. E.g. a linear layer on the CPU can be executed with an input tensor on the GPU by streaming the weights to the GPU at runtime.
- Add unit tests for the aforementioned autocast modules to verify that they work for all supported quantization formats (GGUF, BnB NF4, BnB LLM.int8()).
- Add `CachedModelWithPartialLoad` and `CachedModelOnlyFullLoad` classes to manage partial loading at the model level.
Several options were explored for supporting …
=> Partial Loading PR2: Add utils to support partial loading of models from CPU to GPU

docs/contributing/dev-environment.md, docs/installation/manual.md
- Update the manual install and dev environment docs to use `uv` and the same logic we use in the launcher.
- Add a blurb to the manual install docs hinting at how to create your own install and launch scripts, since we are focusing our dev resources on the GUI launcher moving forward.
n/a
Fire up the docs and see how they look.
n/a
=> docs: install guides

invokeai/frontend/web/src/common/components/SessionMenuItems.tsx, invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts
This button now only resets the canvas layers - not the bbox.
One thing I'm unsure of. `Reset Generation Settings` _also_ does not reset the bbox. 
@skunkworxdark Do you think `Reset Generation Settings` should reset the bbox? In other words, should the fix instead be to move the bbox-resetting functionality from `Reset Canvas Layers` to `Reset Generation Settings`? Thanks for your input.
This was reported as unexpected behaviour by @skunkworxdark : https://discord.com/channels/1020123559063990373/1149506274971631688/1309557626476040253
n/a
=> feat(ui): reset canvas layers only resets the layers

invokeai/app/api/routers/boards.py, invokeai/app/services/board_records/board_records_common.py
limit board_name length to 300 characters to avoid vulnerability via excessively large payloads
=> fix(api): limit board_name length to 300 characters

invokeai/app/invocations/compel.py, invokeai/app/invocations/latents_to_image.py, invokeai/app/invocations/sd3_latents_to_image.py, invokeai/app/invocations/sd3_text_encoder.py, invokeai/app/services/config/config_default.py, invokeai/app/services/model_manager/model_manager_default.py, invokeai/backend/flux/modules/conditioner.py, invokeai/backend/image_util/hed.py, invokeai/backend/image_util/infill_methods/lama.py, invokeai/backend/image_util/lineart.py, invokeai/backend/image_util/lineart_anime.py, invokeai/backend/image_util/mlsd/utils.py, invokeai/backend/image_util/normal_bae/__init__.py, invokeai/backend/image_util/pidi/__init__.py, invokeai/backend/model_manager/load/load_base.py, invokeai/backend/model_manager/load/model_cache/cache_record.py, invokeai/backend/model_manager/load/model_cache/cached_model/cached_model_with_partial_load.py, invokeai/backend/model_manager/load/model_cache/model_cache.py, invokeai/backend/model_manager/load/model_cache/utils.py, invokeai/backend/patches/layers/ia3_layer.py, invokeai/backend/util/prefix_logger_adapter.py, tests/backend/model_manager/load/model_cache/torch_module_autocast/custom_modules/test_all_custom_modules.py, tests/backend/model_manager/model_manager_fixtures.py
This PR adds support for partial loading of models onto the GPU. This enables models to run with much lower peak VRAM requirements (e.g. full FLUX dev with 8GB of VRAM).
The partial loading feature is enabled behind a new config flag: `enable_partial_loading=True`. This flag defaults to `False`.
**Note about performance:**
The `ram` and `vram` config limits are still applied when  `enable_partial_loading=True` is set. This can result in significant slowdowns compared to the 'old' behaviour. Consider the case where the VRAM limit is set to `vram=0.75` (GB) and we are trying to run an 8GB model. When `enable_partial_loading=False`, we attempt to load the entire model into VRAM, and if it fits (no OOM error) then it will run at full speed. When `enable_partial_loading=True`, since we have …
=> Partial Loading PR4: Enable partial loading (behind config flag)

invokeai/app/api/routers/model_manager.py, invokeai/app/invocations/compel.py, invokeai/app/invocations/denoise_latents.py, invokeai/app/invocations/flux_denoise.py, invokeai/app/invocations/flux_text_encoder.py, invokeai/app/invocations/flux_vae_decode.py, invokeai/app/invocations/latents_to_image.py, invokeai/app/invocations/sd3_latents_to_image.py, invokeai/app/invocations/sd3_text_encoder.py, invokeai/app/invocations/spandrel_image_to_image.py, invokeai/app/invocations/tiled_multi_diffusion_denoise_latents.py, invokeai/app/services/config/config_default.py, invokeai/app/services/model_manager/model_manager_default.py, invokeai/backend/model_manager/load/load_base.py, invokeai/backend/model_manager/load/model_cache/cached_model/cached_model_with_partial_load.py, invokeai/backend/model_manager/load/model_cache/dev_utils.py, invokeai/backend/model_manager/load/model_cache/model_cache.py, invokeai/frontend/web/src/services/api/schema.ts, tests/backend/model_manager/load/model_cache/cached_model/test_cached_model_with_partial_load.py, tests/backend/model_manager/model_manager_fixtures.py
This PR enables RAM/VRAM cache size limits to be determined dynamically based on availability.
**Config Changes**
This PR modifies the app configs in the following ways:
- A new `device_working_mem_gb` config was added. This is the amount of non-model working memory to keep available on the execution device (i.e. GPU) when using dynamic cache limits. It default to 3GB.
- The `ram` and `vram` configs now default to `None`. If these configs are set, they will take precedence over the dynamic limits. **Note: Some users may have previously overriden the `ram` and `vram` values in their `invokeai.yaml`. They will need to remove these configs to enable the new dynamic limit feature.**
**Working Memory**
In addition to the new `device_working_mem_gb` config described above, memory-intensive …
=> Partial Loading PR5: Dynamic cache ram/vram limits

invokeai/app/invocations/spandrel_image_to_image.py
This PR contains a bugfix for an edge case with model unloading (from VRAM to RAM). Thanks to @JPPhoto for finding it.
The bug was triggered under the following conditions:
- A GGML-quantized model is loaded in VRAM
- We run a Spandrel image-to-image invocation (which is wrapped in a `torch.inference_mode()` context manager.
- The model cache attempts to unload the GGML-quantized model from VRAM to RAM.
- Doing this inside of the `torch.inference_mode()` cm results in the following error:
```
[2025-01-07 15:48:17,744]::[InvokeAI]::ERROR --> Error while invoking session 98a07259-0c03-4111-a8d8-107041cb86f9, invocation d8daa90b-7e4c-4fc4-807c-50ba9be1a4ed (spandrel_image_to_image): Cannot set version_counter for inference tensor
[2025-01-07 15:48:17,744]::[InvokeAI]::ERROR --> Traceback …
```
=> Bugfix: Offload of GGML-quantized model in `torch.inference_mode()` cm

docs/contributing/dev-environment.md, docs/installation/manual.md
Fix a typo in the docs. Was just fixed in the launcher in https://github.com/invoke-ai/launcher/pull/33. Hopefully this will resolve the AMD issue on Linux.
=> docs: fix pypi indices for manual install for AMD

invokeai/app/invocations/denoise_latents.py, invokeai/app/invocations/flux_denoise.py, invokeai/app/invocations/image_to_latents.py, invokeai/app/invocations/sd3_image_to_latents.py, invokeai/app/invocations/spandrel_image_to_image.py, invokeai/app/invocations/tiled_multi_diffusion_denoise_latents.py, invokeai/backend/flux/extensions/xlabs_ip_adapter_extension.py, invokeai/backend/model_patcher.py, invokeai/backend/stable_diffusion/extensions/t2i_adapter.py
Given the recent introduction of partial model loading, the meaning of `model.device` has changed. It could return the `"cpu"` device even if the model is partially loaded and should be passed a `"cuda"` input. This PR makes a best effort to go through and clean up places where we access `model.device`.
Original bug report: https://discord.com/channels/1020123559063990373/1149506274971631688/1326245764258861117
Smoke test all of the modified code paths:
I was also able to reproduce the error reported in Discord by manually loading models to the same level as OP (in a debugger). I confirmed that this changes fixed that particular issue.
=> Bugfix: Do not rely on `model.device` if model could be partially loaded

invokeai/app/invocations/denoise_latents.py
If a model defaults to DEIS scheduler and the user attempts to use DPM++ schedulers with it, the inherited config parameters clash giving #6368, this fixes it by changing the config to use DPM's default alogorythm type, which I
believe is was a user attempt to using the DPM++ would expect.
Closes #6368
Run a Dreamshaper 8 render using any of the following schedulers
DPM++ 2M
DPM++ 2M Karras
DPM++ 2S
DPM++ 2S Karras
It will fail without the pull request, and will work with the pull request.
N/A simple merge
=> Fix for DEIS / DPM++ config clash by setting algorithm type -  fixes #6368

invokeai/frontend/web/src/features/controlLayers/components/CanvasMainPanelContent.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx, invokeai/frontend/web/src/features/ui/components/AppContent.tsx
Hopefully fixes issues where, when run via the launcher, the main panel kinda just scrolls out of bounds.
Just adding `overflow: hidden` to all divs from the top level down to canvas and viewer. I did all sorts of stuff on canvas on Windows and macOS in an attempt to repro the issue but couldn't, so we'll just need to get this fix released to see if it works.
Multiple discord reports:
- https://discord.com/channels/1020123559063990373/1020123559831539744/1325485934908670022
- https://discord.com/channels/1020123559063990373/1020123559831539744/1325707642844348488
Release to affected users so they can test it.
n/a
=> fix(ui): prevent canvas & main panel content from scrolling

docs/nodes/communityNodes.md
The image under https://invoke-ai.github.io/InvokeAI/nodes/communityNodes/#stereogram-nodes is broken. Changing img src to fix.
=> Update communityNodes.md - Fix broken image

invokeai/frontend/web/src/features/nodes/util/graph/generation/addInpaint.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addOutpaint.ts
In 7cdda00a5493aea09083006b627c1b8285bd40d8, I made a small optimization to the graphs for inpainting and outpainting. The change makes the graphs a bit smaller, saving us one PNG encode and image writing step. 
As reported by @skunkworxdark on [discord](https://discord.com/channels/1020123559063990373/1149513647022948483/1307060842910449716), there is an issue where the unmasked regions of an image slowly degrade when the image is inpainted repeatedly.
Because of timing of the issue report coincided with 7cdda00a5493aea09083006b627c1b8285bd40d8, I think that optimization may be the cause, but I'm having trouble wrapping my head around why exactly.
@skunkworxdark , Could you please test this PR to confirm it resolves the degradation issue you noticed? If it does, we'll get this revert …
=> fix(ui): image quality degradation on canvas after repeated generations

invokeai/frontend/web/src/features/dnd/FullscreenDropzone.tsx
Use `window.addEventListener` instead of `document.addEventListener` for better compatibility with react wrapper when pasting images
=> fix(ui): use window instead of document for image pasting

invokeai/app/invocations/denoise_latents.py, invokeai/app/invocations/tiled_multi_diffusion_denoise_latents.py
Capture prediction type from model settings and pass it to the scheduler to enable v_prediction checkpoints to work again.
I'm certain there is a more correct way to handle this in the model manager that would also allow automatic detection from checkpoint files, but this at least gets vpred models working again before we go make sweeping changes to the model probe code.
Since our conversion code does not check the settings on the checkpoint, attempting to convert a v_prediction model to Diffusers will still default over to epsilon prediction and it will forever fail afterwards. It is not currently possible for users to change a diffusers model to v_prediction in Invoke without editing the local json files. User Mewt on discord has found that huggingface repos with correct …
=> Support v-prediction checkpoint models when set in the model manager

invokeai/frontend/web/src/features/stylePresets/components/StylePresetImage.tsx
There's a bug where preset image tooltips get stuck open in the list.
After much fiddling, debugging, and review of upstream dependencies, I have determined that this is bug in Chakra-UI v2.
Specifically, it appears to be a race condition related to the Tooltip component's internal use of the `useDisclosure` hook to manage tooltip open state, and the react render cycle.
Unfortunately, Chakra v2 is no longer being updated, and it's a pain in the butt to vendor and fix that component given its dependencies. Not 100% sure I could easily fix it, anyways.
Fortunately, there is a workaround - reduce the tooltip openDelay to 0ms. I prefer the current 500ms delay but I think it's preferable to have too-quick tooltips than too-sticky tooltips...
@hipsterusername please give this a spin and try to …
=> fix(ui): sticky preset image tooltip

invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/konva/util.ts
Due to the limited floating point precision, and konva's `scale` properties, it is possible for the relative rect of an object to have non-integer coordinates and dimensions.
When we go to rasterize and otherwise export images, the HTML canvas API truncates these numbers.
So, we can end up with situations where the relative width and height of a layer are very close to the "real" value, but slightly off.
For example, width and height might be 512px, but the relative rect is calculated to be something like 512.000000003 or 511.9999999997.
In the first case, the truncation results in 512x512 for the dimensions - which is correct. But in the second case, it results in 511x511!
One place where this causes issues is the image action `New Canvas from image -> As Raster Layer (resize)`. For …
=> fix(ui): round rects when applying transform

invokeai/app/invocations/flux_model_loader.py, invokeai/app/invocations/flux_text_encoder.py, invokeai/app/invocations/sd3_model_loader.py, invokeai/app/util/t5_model_identifier.py, invokeai/backend/flux/modules/conditioner.py
Prior to this change, attempting to use a T5 model that was bundled with an SD3 base model in a FLUX workflow resulted in the following exception.
```
[2025-01-09 22:58:53,711]::[InvokeAI]::ERROR --> Error while invoking session 3f4f9287-bb23-44f7-8e52-bbf6c4b114e8, invocation c3bd3f6d-71cd-4b86-a4c2-8e43758e4185 (flux_text_encoder): 
[2025-01-09 22:58:53,711]::[InvokeAI]::ERROR --> Traceback (most recent call last):
File "/home/ryan/src/InvokeAI/invokeai/app/services/session_processor/session_processor_default.py", line 129, in run_node
output = invocation.invoke_internal(context=context, services=self._services)
File "/home/ryan/src/InvokeAI/invokeai/app/invocations/baseinvocation.py", line 300, in invoke_internal
output = self.invoke(context)
File …
```
=> Make T5 models interchangeable between FLUX/SD3 workflows

invokeai/frontend/web/src/features/dnd/FullscreenDropzone.tsx
After lots of debugging, it seems that the AbortController and unmount logic was causing paste-to-upload logic not to work in some environments. This PR removes that and uses `removeEventListener` instead, while also simplifying dependencies.
=> fix(ui): remove AbortController logic from paste to upload

invokeai/backend/model_manager/load/model_loaders/flux.py
Prior to this change, there were several cases where we initialized the weights of a FLUX model before loading its state dict (and, to make things worse, in some cases the weights were in float32). This PR fixes a handful of these cases. (I think I found all instances for the FLUX family of models.)
- Helps with https://github.com/invoke-ai/InvokeAI/issues/7563
I tested that that model loading still works and that there is no virtual memory reservation on model initialization for the following models:
No special instructions.
=> Reduce peak memory during FLUX model load

docs/features/low-vram.md, invokeai/backend/model_manager/load/model_cache/model_cache.py
This PR revises the logic for calculating the model cache RAM limit. See the code for thorough documentation of the change.
The updated logic is more conservative in the amount of RAM that it will use. This will likely be a better default for more users. Of course, users can still choose to set a more aggressive limit by overriding the logic with `max_cache_ram_gb`.
- Should help with https://github.com/invoke-ai/InvokeAI/issues/7563
Exercise all heuristics:
=> Revise the default logic for the model cache RAM limit

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/StringFieldInputComponent.tsx
Not sure how or why but I accidentally made string field textarea elements read-only in 10f2c0dc9a6ddf8b61f75c1c66e3fa79a758e088. Cannot type into them in workflow editor. 
n/a
n/a
n/a
=> fix(ui): string field textarea accidentally readonly

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/FloatGeneratorFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/FloatGeneratorUniformRandomDistributionSettings.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/IntegerGeneratorFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/IntegerGeneratorUniformRandomDistributionSettings.tsx, invokeai/frontend/web/src/features/nodes/types/field.ts
Float and integer generators' random distribution supports a seed.
- Add JS Mersenne Twister implementation dependency to use as seeded PRNG. This is not a cryptographically secure algorithm.
- Add nullish seed field to float and integer random generators.
- Add UI to control the seed.
- When seed is not set, behaviour is unchanged - the values are randomized when you Invoke. When seed is set, the random distribution is deterministic depending on the seed. In this case, we can display the values to the user.
https://discord.com/channels/1020123559063990373/1049495067846524939/1329770360136007732
- With seed disabled, the generator should output different values each time you click Invoke. You should not see a preview of the generated values.
- With seed enabled, the generator should …
=> feat(ui): seeded random generators

docs/features/low-vram.md
Adds docs for troubleshooting and resolving the issue of crashes caused by insufficient Windows page file space.
- #7563 
N/A
No special instructions
=> Add troubleshooting docs for the Windows page file issue

invokeai/app/invocations/batch.py, invokeai/frontend/web/src/features/nodes/util/schema/parseSchema.ts
String batch inputs were marked as supporting direct input only (not connection), so you couldn't use generators with them. Fixed this.
Reported by @skunkworxdark on discord: https://discord.com/channels/1020123559063990373/1049495067846524939/1330867272193019948
Thanks!
Confirm string generator and string batch nodes may be connected by a noodle (glory to nodes).
<video src="https://github.com/user-attachments/assets/8abbbe0c-3449-4db2-a540-8545739dc5f8"></video>
n/a
=> fix: string batch input fields

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/StringGeneratorFieldComponent.tsx
Dynamic prompts string generators can cause an infinite feedback loop when added to the linear view.
The root cause is how these generators handle "resolving" their collections. They hit the dynamic prompts HTTP API within the view component to get the prompts, then set the batch node's internal state with those values.
When the same generator is rendered in both the node editor view and linear view and the timing is just right, that state update causes an infinite feedback loop between the two components as they respond to the state updates from the other component.
The other generators never store the generated values in the batch node's internal state. The values are "resolved" just-in-time as they are needed.
To fix this, the batch value "resolver" utilities could be made async and …
=> fix(ui): disable dynamic prompts generators pending resolution of infinite recursion issue

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/FieldHandle.tsx
Accidentally overwrote some reactflow styles which caused field handles to be positioned differently for non-batch fields. Just a minor visual issue.
=> fix(ui): field handle positioning for non-batch fields

invokeai/backend/patches/layers/lora_layer_base.py, invokeai/backend/patches/layers/param_shape_utils.py, tests/backend/model_manager/load/model_cache/torch_module_autocast/custom_modules/test_all_custom_modules.py
Fixes a bug with some LoRA variants (LoKR, LoHA and some other obscure variants - LoRA is not affected) when they are applied to bitsandbytes NF4 quantized models. Unit tests were added to exercise the affected case.
- Closes #6998 
- Closes #7134
Regression tests:
No special isntructions.
=> Fix bug with some LoRA variants when applied to bitsandbytes NF4 quantized models

invokeai/app/invocations/mask.py, invokeai/app/invocations/primitives.py, invokeai/app/invocations/segment_anything.py, invokeai/frontend/web/src/services/api/schema.ts
This PR fixes an issue with mask dimension consistency. Prior to this change, the following workflow would fail with `tuple out of range` error:
Dimension compatibility for invocations that take a mask input:
- `ApplyMaskTensorToImageInvocation`: 2 or 3
- `MaskTensorToImageInvocation`: 2 or 3
- `InvertTensorMaskInvocation`: 3
Mask dimension for invocations that produce a MaskOutput:
- `RectangleMaskInvocation`: 3
- `AlphaMaskToTensorInvocation`: 3
- `InvertTensorMaskInvocation`: 3
- `ImageMaskToTensorInvocation`: 3
- `SegmentAnythingInvocation`: 2
Dimension compatibility for invocations that take a mask input:
- `ApplyMaskTensorToImageInvocation`: 2 or 3
- `MaskTensorToImageInvocation`: 2 or 3
- `InvertTensorMaskInvocation`: **2 or 3** <----------------
Mask dimension for invocations that …
=> Improve MaskOutput dimension consistency

invokeai/app/invocations/sd3_model_loader.py
Fixes a minor bug that was introduced in https://github.com/invoke-ai/InvokeAI/pull/7590.
Prior to this fix, loading an SD3.5 model would produce this error:
```
[2025-01-28 22:41:48,643]::[InvokeAI]::ERROR --> Error while invoking session 1f03b5d1-f099-4a79-816c-1bae1aafa4c9, invocation 40c782ff-b38b-4137-9deb-a04874cb56be (sd3_model_loader): 1 validation error for T5EncoderField
loras
Field required [type=missing, input_value={'tokenizer': ModelIdenti...er3: 'text_encoder_3'>)}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.7/v/missing
[2025-01-28 22:41:48,643]::[InvokeAI]::ERROR --> Traceback (most recent call last):
File "/home/ryan/src/InvokeAI/invokeai/app/services/session_processor/session_processor_default.py", line 129, in run_node
output = …
```
=> Fix T5EncoderField initialization in SD3 model loader

invokeai/backend/model_manager/load/model_cache/model_cache.py
This PR makes the default max RAM cache size slightly more conservative. This should help with some reports of Invoke using more RAM/VRAM than expected/desired. Of course, users always have the option to configure Invoke to use a larger cache size.
The change is relatively straightforward. I tested the following cases:
- Max RAM limit is set to 50% of available system RAM.
- RAM limit is set to 50% of available system RAM and then reduced to 1x VRAM cache size
Reviewers are encouraged to try this out on their systems to see if default performance is worse/better/the same.
The real test will be whether this reduces the number of issue reports with the default configs.
No special instructions
=> Make the default max RAM cache size more conservative

invokeai/app/api/routers/model_manager.py, invokeai/backend/model_manager/load/model_cache/model_cache.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/features/queue/components/ClearModelCacheButton.tsx, invokeai/frontend/web/src/features/queue/components/QueueTabQueueControls.tsx, invokeai/frontend/web/src/services/api/endpoints/models.ts, invokeai/frontend/web/src/services/api/schema.ts
This PR adds a backend endpoint that can be used to empty the model cache (to free RAM / VRAM). 'Locked' models that are actively being used will not be dropped.
Locking was added to `ModelCache` to make it thread-safe. But, I suspect that it might be possible to trigger https://github.com/invoke-ai/InvokeAI/issues/7513 with an ill-timed request to empty the cache (in the middle of graph execution). Even if this does happen, the current graph execution would fail, but subsequent graph executions _should_ recover smoothly.
I tested that the new endpoint successfully empties the model cache with `curl -X POST 127.0.0.1:9090/api/v2/models/empty_model_cache`.
I tried to break things by hitting the endpoint throughout graph execution. Nothing broke, which is a good sign. Of course, this is far …
=> Add endpoint for emptying the model cache

invokeai/app/invocations/image.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/Filters/FilterAdjustImage.tsx, invokeai/frontend/web/src/features/controlLayers/components/Filters/FilterSettings.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityFilterer.ts, invokeai/frontend/web/src/features/controlLayers/store/filters.ts
Adds a new Canvas filter that exposes the ImageChannelOffsetInvocation and ImageChannelMultiplyInvocation functions.
* Adjust Image is now the default when opening the Filters menu, which is alphabetically pleasing and less jarring than the Canny filter. 
* ImageChannel invocations now reuse the original Alpha channel (when Alpha is not the channel being modified) to preserve transparent canvas operations.
* ImageChannelOffset now lets Hue (HSV) loop over when out of [0..255] bounds
Mostly satisfies #4942 but does not have contrast/sharpness abilities.
A Value of 1 is no change. 0 and 2 are -255 and +255 respectively. At Value=0.5, 128 will be subtracted from each pixel in the selected channel, with results clipping to a minimum of 0.
If "Scale Values" is true, the graph will switch to …
=> Feature: Adjust Image filter

invokeai/app/services/shared/graph.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/batchEnqueued.ts, invokeai/frontend/web/src/features/nodes/store/util/validateConnectionTypes.test.ts, invokeai/frontend/web/src/features/nodes/store/util/validateConnectionTypes.ts, tests/test_node_graph.py
- When validating edges, return the error message instead of just a boolean.
- When raising `InvalidEdgeError`, ensure we use that error message.
- Surface the error message to the user in the UI.
- Tweak the error toast to be a bit less cryptic.
- Fix issue with `Any` type fields not accepting collections
- Fix longstanding issue with iterate nodes not accepting connections from collect nodes
Error before:
Error after:
Should help in troubleshooting the issue here https://discord.com/channels/1020123559063990373/1083864753543331981/1334888935242858506
Closes #3956
@skunkworxdark Could you please try reproducing that issue with this PR? Hopefully it's easier to see what's going on.
For this specific issue, might need to set breakpoints for each of the 3 fail case returns in these two …
=> feat: better graph validation errors

docs/installation/quick_start.md
Add a troubleshooting section to the quick start guide.
=> docs: install troubleshooting

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectImage.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStagingAreaModule.ts
- Render different error state for the two failure modes for canvas image rendering:
1. Failed to retrieve image DTO = "Unable to find image"
2. Failed to retrieve image itself = "Unable to load image"
- Fix two issues that result from canvas image rendering failures:
1. Canvas image render error placeholder never disappears (when the last generation in a sequence is the failure)
2. Staging area stuck on progress image when canvas image rendering fails as described (when any generation except the last in a sequence is the failure)
- Add more data to a couple canvas module `repr` methods
- Fix a visual flicker, where the next generation's first progress image shows, then we briefly show the previous generation's final output image, then continue showing the next generation's progress …
=> feat(ui): canvas image error handling

invokeai/app/invocations/image.py
The alpha handling that lets image multiply work on canvas filters broke if it was downstream of certain nodes that always output RGB instead of RGBA. ImageChannelMultiply node now loads as RGBA first. I had this fix in the Offset node already, but forgot to add it to the multiply one. Oops.
ready to merge
=> Fix: Multiply Image Channel allows RGB inputs again

invokeai/frontend/web/index.html
Add `overflow: hidden` to `index.html`'s CSS to hopefully prevent the UI from slipping out of view during an edge case. Cannot repro so not sure it fixes it.
If you can repro the issue, great. If not, nothing to check really.
n/a
=> fix(ui): prevent overflow on document root

invokeai/frontend/web/src/features/nodes/util/graph/buildMultidiffusionUpscaleGraph.ts
Prior to this PR, upscaling workflows run from the Upscaling Tab used the default tile size for VAE encode/decode (512x512 for SD1, 1024x1024 for SDXL). The small tile size of 512x512 sometimes produces visible tile artifacts in the output image. This is most evident in regions with limited 'texture'.
This PR increases the default VAE encode/decode tile size to 1024 for all base model types.
Note: This change will increase the peak VRAM usage for SD1 upscale jobs. There are mitigations that we could apply if this causes issues for users with limited VRAM, but for now we are rolling forward since the number of affected users is expected to be small.
<table>
<tr>
<td align="center">
<sub>Original (1024x1024)</sub>
</td>
</tr>
<tr>
<td align="center">
<sub>4x upscale, tile size 512x512 (note …
=> Increase default VAE tile size in upscaling tab

docker/Dockerfile
Node v20 base image is causing the container frontend build to fail; this PR fixes it
Fixes #7637 
No specific QA required beyond usual testing
Merge at will
=> Fix container build (frontend)

invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterInpaintMask.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterRegionalGuidance.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasBrushToolModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasColorPickerToolModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasToolModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/util.ts
- Fix cursor disappearing when a draw tool is selected and a non-drawable layer (e.g. ref image) is selected. Now it shows the "not-allowed" cursor.
- Fix an issue where the color picker doesn't work when a non-drawable layer (e.g. ref image) is selected. Now it works.
- Fix an issue (80% certain) where mask layers didn't render until you jiggle or zoom the canvas.
- Fix an issue where shift-clicking to draw a line after panning the canvas cuts off the line.
- Color picker now supports alpha/transparency.
- Color picker now displays the RGBA value next to it. See video below.
https://github.com/user-attachments/assets/c4b7e19a-e6f1-4b83-b1e2-bcb32731a037
Offline discussion and scattered discord threads.
We could add a setting to toggle the RGBA value display, but I ran out of time for …
=> fix,feat(ui): canvas improvements

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/workflowLoadRequested.ts, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputFieldEditModeNodes.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputFieldHandle.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/OutputFieldHandle.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/common/NodeTitle.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/FormElementEditModeHeader.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/FormElementEditModeWrapper.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/WorkflowBuilder.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/dnd-hooks.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/dnd.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/form-manipulation.test.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/form-manipulation.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/shared.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/viewMode/ViewModeLeftPanelContent.tsx, invokeai/frontend/web/src/features/nodes/store/reactFlowInstance.ts, invokeai/frontend/web/src/features/nodes/store/workflowSlice.ts, invokeai/frontend/web/src/features/nodes/types/constants.ts, invokeai/frontend/web/src/features/nodes/types/field.ts, invokeai/frontend/web/src/features/nodes/types/workflow.ts, invokeai/frontend/web/src/features/nodes/util/workflow/graphToWorkflow.ts, invokeai/frontend/web/src/features/nodes/util/workflow/validateWorkflow.test.ts, invokeai/frontend/web/src/features/nodes/util/workflow/validateWorkflow.ts
I implemented these kinda-unrelated changes as I encountered them and didn't create a separate branch, so they are bundled up here. Some cross-pollination w/ the other changes, not gonna worry about splitting them.
- Fix: Model fields that reference nonexistent models weren't reset during workflow loading.
- Fix: After loading a workflow, the first click in the editor resets the zoom.
- Fix: Node title cursor is 'text' - should be 'grab'.
- Chore: Update `vitest`'s UI related packages, fixing a version mismatch taht prevented the test UI dashboard from loading.
Builder changes.
- Refactor: Use root container instead of non-container list for form root, substantially simplifying internal logic. Only tradeoff is a small amount of special handling needed in the UI for the for the root …
=> ui: workflow builder iteration

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputFieldEditModeNodes.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputFieldTitle.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/BooleanFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/ActiveWorkflowNameAndActions.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/WorkflowListMenuTrigger.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/ContainerElementSettings.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/FormElementEditModeHeader.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/HeadingElementComponent.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementComponent.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementSettings.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementStringSettings.tsx, invokeai/frontend/web/src/features/nodes/hooks/useZoomToNode.ts
- Fix overflow in workflow title
- Make form element edit mode headers less bright (just a bit less busy looking)
- Prevent accidental selection of edit mode headers (hard to de-select due to dnd interactions)
- Tweak styling of heading and text element editables
- Add missing translations for string field settings
- Fix issue where double-clicking a switch in a boolean field would zoom to node
- Fix issue preventing dragging a whole node on certain field names
- Add button to zoom to node on node field headers
n/a
Try it out
n/a
=> workflow builder iteration 4

invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImage.tsx, invokeai/frontend/web/src/features/gallery/components/ImageGrid/GalleryImageHoverIcons.tsx
Not sure why the perf optimisation doesn't work on Chrome but I reverted it.
Discord discussion: https://discord.com/channels/1020123559063990373/1149506274971631688/1342617367372628081
Buttons that appear when hovering over a gallery image should work on Chrome.
n/a
=> fix(ui): star button not working on Chrome

invokeai/frontend/web/src/features/nodes/store/workflowSlice.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useGetFormInitialValues.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useSaveWorkflow.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useSaveWorkflowAs.ts
We need some special handling to ensure the form builder's initial values are updated when the workflow is saved.
Note: This issue is not new - it existed in the previous linear view.
Repro on `main`:
- Create a new workflow
- Add a string primitive node (the issue occurs with any node, not just this one)
- Type something in it - let's say "OG value"
- Add the field to the builder
- Save the workflow
- Change the value of the field - let's say "new value"
- Save the workflow
- Note that the form field reset button resets the value to "OG value", not "new value" as it should
With this PR, the value should be reset as expected after saving or save-as-ing.
n/a
=> fix(ui): reset form initial values when workflow is saved

invokeai/app/services/session_queue/session_queue_common.py, invokeai/app/services/session_queue/session_queue_sqlite.py, invokeai/version/invokeai_version.py, tests/test_session_queue.py
- Bump version to v5.7.0rc2
I have cherry-picked the perf changes from #7688 into this PR so that I can get them into the RC for testing (that PR won't get an approval until tomorrow). See detailed notes in that PR.
- Supersedes #7688
n/a
I will do teh RC
=> chore: bump version to v5.7.0rc2

invokeai/app/services/session_queue/session_queue_common.py
Changes the type of `retried_from_item_id` to match the DB schema.
This only affects type annotations and does not affect operation of the app.
Merge at will
=> fix(backend): ValuesToInsertTuple.retried_from_item_id should be an int

invokeai/app/invocations/primitives.py
In the Image Primitive node, we were loading the PIL image from file storage, but it does nothing to it. We can instead retrieve the image DTO only, which is a cheaper operation.
n/a
n/a
n/a
=> feat(app): do not pull PIL image from disk in image primitive

invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/ContainerElementSettings.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementSettings.tsx
Fix a visual issue where you sometimes couldn't see the settings popover for form elements when inside a container.
n/a
n/a
n/a
=> fix(ui): form element settings obscured by container

invokeai/app/api_app.py, invokeai/app/run_app.py, invokeai/app/util/startup_utils.py
Prior to this PR, most of the app setup was being done in `api_app.py` at import time. This PR cleans this up, by:
- Splitting app setup into more modular functions
- Narrower responsibility for the `api_app.py` file - it just initializes the `FastAPI` app
The main motivation for this changes is to make it easier to support an upcoming torch configuration feature that requires more careful ordering of app initialization steps.
N/A
=> Tidy app entrypoint

.github/workflows/build-container.yml
GHA runners run out of disk space trying to pull and store the docker build cache. Additionally, this is very slow.
This PR disables the cache. Theoretically this may increase the size of our images, but because caching has been broken anyway, this will have no impact.
Will come back and take another stab on improving caching behaviours.
Merge at will.
=> Do not cache image layers in CI docker build

docs/features/low-vram.md, invokeai/app/run_app.py, invokeai/app/services/config/config_default.py, invokeai/app/util/torch_cuda_allocator.py, tests/app/util/test_torch_cuda_allocator.py
This PR adds a `pytorch_cuda_alloc_conf` config flag to control the torch memory allocator behavior.
- `pytorch_cuda_alloc_conf` defaults to `None`, preserving the current behavior.
- The configuration options are explained here: https://pytorch.org/docs/stable/notes/cuda.html#optimizing-memory-usage-with-pytorch-cuda-alloc-conf. Tuning this configuration can reduce peak reserved VRAM and improve performance.
- Setting `pytorch_cuda_alloc_conf: "backend:cudaMallocAsync"` in `invokeai.yaml` is expected to work well on many systems. This is a good first step for those looking to tune this config. (We may make this the default in the future.)
- The optimal configuration seems to be dependent on a number of factors such as device version, VRAM, CUDA kernel version, etc. For now, users will …
=> Add `pytorch_cuda_alloc_conf` config to tune VRAM memory allocation

docs/features/low-vram.md, invokeai/app/invocations/flux_vae_decode.py, invokeai/app/invocations/latents_to_image.py, invokeai/app/invocations/sd3_latents_to_image.py
This PR increases the working memory estimates for VAE decode operations. The previous values were set based on memory _allocations_ and were pretty aggressive about trying to make full use of the available VRAM. The updated values were set based on experimentally-observed _reserved_ memory (not just _allocated_) levels, and also aim to be conservative by including some buffer room.
This change is intended to address reports of slow VAE decoding.
The more conservative memory estimate values could cause more memory to be offloaded from the GPU during VAE decode. This in turn could result in slower model reloading on subsequent runs. The net impact of this change is expected to be positive, but there may be a noticeable regression for some users. We will want to keep a close eye on this …
=> Increase VAE decode memory estimates

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/WorkflowListItem.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryMenu/DownloadWorkflowMenuItem.tsx, invokeai/frontend/web/src/features/workflowLibrary/hooks/useDownloadCurrentlyLoadedWorkflow.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useDownloadWorkflowById.ts
Add a hook to download a workflow by ID and use it in the library list
n/a
Download button should work in library
n/a
=> fix(ui): download button in workflow library downloads wrong workflow

docs/RELEASE.md
docs: update RELEASE.md
n/a
n/a
n/a
=> docs: update RELEASE.md

invokeai/frontend/web/src/features/nodes/types/field.ts
Fixes an issue where fields like control weight on ControlNet nodes and image on IP Adapter nodes didn't render.
These are "single or collection" fields. They accept a single input object, or collection. They are supposed to render the UI input for a single object.
In a7a71ca935368db1d43ac1d2e84b048b643fa57e a performance optimisation for a hot code-path inadvertently broke this.
The determination of which UI component to render for a given field was done using a type guard function for the field's template. Previously, this used a zod schema to parse the template. This is very slow, especially when the template was not the expected type.
The optimization changed the type guards to check the field name (aka its type, integer, image, etc) and cardinality directly, without any zod parsing. …
=> fix(ui): single or collection field rendering

invokeai/frontend/web/src/common/hooks/useImageUploadButton.tsx, invokeai/frontend/web/src/features/dnd/FullscreenDropzone.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/Fields/ModelImageUpload.tsx
Accept WebP images for image asset upload (including drag-and-drop).
Fixes #6766
- Upload `.webp` image as canvas asset using upload button.
- Drag `.webp` file on to the canvas.
- In model manager, upload webp image for model thumbnail.
N/A
=> feat: accept WebP uploads for assets

invokeai/app/api/routers/session_queue.py, invokeai/app/api/sockets.py, invokeai/app/services/board_image_records/board_image_records_sqlite.py, invokeai/app/services/board_records/board_records_sqlite.py, invokeai/app/services/image_records/image_records_sqlite.py, invokeai/app/services/model_records/model_records_sql.py, invokeai/app/services/session_queue/session_queue_base.py, invokeai/app/services/session_queue/session_queue_sqlite.py, invokeai/app/services/shared/sqlite/sqlite_database.py, invokeai/app/services/shared/sqlite_migrator/sqlite_migrator_impl.py, invokeai/app/services/style_preset_records/style_preset_records_sqlite.py, invokeai/app/services/workflow_records/workflow_records_sqlite.py, invokeai/frontend/web/src/services/api/index.ts
Most service methods in the application are blocking. For example, `enqueue_batch` blocks the main thread - preventing HTTP and socket traffic. When enqueuing very large or complicated batches, this can cause unresponsiveness.
To make `enqueue_batch` non-blocking, we can make it async and run it in a thread. However, we have another source of "blocking" - a global mutex on database operations. 
This global mutex is required because SQLite, by default, does not support concurrent reads and writes. We painstakingly wrap _all_ DB operations in a re-entrant lock to prevent issues with interacting with a locked database.
SQLite has an alternate mode called [WAL (write-ahead logging) mode](https://www.sqlite.org/wal.html), which supports concurrent reads and allow us to treat writes as …
=> feat(app): non blocking enqueue_batch

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterSettingsEmptyState.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceIPAdapterSettingsEmptyState.tsx
https://github.com/user-attachments/assets/01c07a89-80a3-4c9e-a92c-3e3440fe8579
https://discord.com/channels/1020123559063990373/1020123559831539744/1346499880243167252
Safe change, uses existing functions.
n/a
=> feat(ui): add button ref image layer empty state to pull bbox

.github/workflows/python-checks.yml, invokeai/app/invocations/baseinvocation.py, invokeai/app/invocations/compel.py, invokeai/app/invocations/segment_anything.py, invokeai/app/services/config/config_default.py, invokeai/backend/image_util/pngwriter.py, invokeai/backend/model_manager/load/memory_snapshot.py, invokeai/backend/model_manager/load/model_cache/model_cache.py, invokeai/backend/model_manager/merge.py, invokeai/backend/model_manager/util/libc_util.py, invokeai/backend/patches/lora_conversions/sdxl_lora_conversion_utils.py, pyproject.toml, tests/app/services/download/test_download_queue.py
Upgrade ruff version to 0.9.9 and format existing code.
=> Ruff upgrade

invokeai/app/api/extract_metadata_from_image.py, invokeai/app/api/routers/images.py, invokeai/frontend/web/src/services/api/schema.ts, tests/app/test_extract_metadata_from_image.py
- Add a utility to extract metadata/workflow/graph from an image. 
- Fix typing for the `metadata` parameter int he upload route (was previously too wide, accepting any JsonValue when only stringified JSON dict is valid).
- Use the new util in the route.
- Add tests for the util.
We need to test that metadata is retained as expected after images are downloaded and then uploaded. There are 3 places to test:
- Generate an image in using send-to-gallery
- Download the image
- Upload it into Invoke
- Confirm that the metadata shows up
- Confirm that the graph tab of metadata still shows the graph
- Load workflow from image (which will build a workflow from this graph, it should use the auto-layout)
- Confirm the workflow looks correct - no errors
- Generate an image using …
=> feat(api): safer metadata extraction during image upload

invokeai/app/invocations/flux_redux.py, invokeai/backend/model_manager/starter_models.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/modelsLoaded.ts, invokeai/frontend/web/src/features/controlLayers/components/CanvasAddEntityButtons.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasEntityList/EntityListGlobalActionBarAddLayerMenu.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/CLIPVisionModel.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterModel.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterSettings.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceIPAdapterSettings.tsx, invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/controlLayers/store/util.ts, invokeai/frontend/web/src/features/controlLayers/store/validators.ts, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/FluxReduxModelFieldInputComponent.tsx, invokeai/frontend/web/src/features/nodes/util/graph/generation/addFLUXRedux.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addIPAdapters.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addRegions.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildFLUXGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildSD1Graph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildSDXLGraph.ts, invokeai/frontend/web/src/services/api/hooks/modelsByType.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts
Add support for FLUX Redux on Canvas. Choose a FLUX Redux model in a Global or Regional Reference Image layer to use it.
I made a breaking change to the `flux_redux` node, removing the SigLIP model field (node version bumped to `2.0.0` to account for this).
We don't think there will ever be a choice of SigLIP models, so to make the UX smoother, we will hardcode it and handle it like we do for CLIP Vision models:
- Include in starter models (as a dependency of the FLUX Redux model)
- When executing the `flux_redux` node, if the model is not available, attempt to download it on the spot w/ a 10min timeout and warning in the logs
- If, after the 10 min, we still don't have the model, the node will error and fail
n/a
- Try out FLUX Redux in Canvas - global and regional.
- Switch between FLUX …
=> feat(ui): flux redux canvas

invokeai/app/api/routers/workflows.py, invokeai/app/services/workflow_records/workflow_records_base.py, invokeai/app/services/workflow_records/workflow_records_sqlite.py, invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/app/store/nanostores/workflowCategories.ts, invokeai/frontend/web/src/app/store/store.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowLibrary/WorkflowLibrarySideNav.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowLibrary/WorkflowList.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowLibrary/WorkflowSearch.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowLibrary/WorkflowSortControl.tsx, invokeai/frontend/web/src/features/nodes/store/types.ts, invokeai/frontend/web/src/features/nodes/store/workflowLibrarySlice.ts, invokeai/frontend/web/src/features/nodes/store/workflowSlice.ts, invokeai/frontend/web/src/features/workflowLibrary/components/SaveWorkflowAsDialog.tsx, invokeai/frontend/web/src/services/api/endpoints/workflows.ts, invokeai/frontend/web/src/services/api/index.ts, invokeai/frontend/web/src/services/api/schema.ts
- Split workflow library state into separate slice. The OG workflows slice is just for the actively loaded workflow. 
- Fix up RTKQ tag invalidation for workflow library.
- Bump RTK to get fix for issue w/ infinite query.
- Rework tag checkboxes to be `AND` filters. Update library service methods, HTTP API and frontend.
n/a
Try it out!
n/a
=> feat: workflow library iteration 2

invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowLibrary/WorkflowLibraryTopNav.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowLibrary/WorkflowSortControl.tsx, invokeai/frontend/web/src/features/nodes/store/workflowLibrarySlice.ts
allow workflow sort options to be passed in
=> allow workflow sort options to be passed in

invokeai/frontend/web/src/features/nodes/store/workflowSlice.ts
fix(ui): do not mark workflow as touched when setting form field initial values
Fixes https://discord.com/channels/1020123559063990373/1149506274971631688/1350130951442927687
n/a
n/a
=> fix(ui): do not mark workflow as touched when setting form field initial values

invokeai/frontend/web/src/features/nodes/hooks/useConnection.ts
Fix an issue where an edge reconnect gets handled twice, adding two edges
Closes #7127
Repro:
- Create a workflow w/ 2 add integer nodes
- Connect the output of one to the A input of the other
- Drag the edge away from the A input to reconnect it to the B input
- Drop it just to the right of the red circle, such that the edge is snapped to the red circle but your cursor is not over the red circle
The edge connection will be handled both by reactflow's reconnect logic and our custom "drop an edge on the body of a node and have it auto-connect" logic. 
There was some logic to bail out of our custom logic that wasn't fully baked. This PR bakes it the rest of the way
n/a
=> fix(ui): duplicate edges on reconnect

.github/workflows/frontend-checks.yml, .github/workflows/frontend-tests.yml, .github/workflows/python-checks.yml, .github/workflows/python-tests.yml, .github/workflows/typegen-checks.yml
=> ci: pin tj-actions/changed-files

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/components/FocusRegionWrapper.tsx, invokeai/frontend/web/src/common/hooks/focus.ts, invokeai/frontend/web/src/features/controlLayers/components/CanvasLayersPanelContent.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasMainPanelContent.tsx, invokeai/frontend/web/src/features/gallery/components/GalleryPanelContent.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx, invokeai/frontend/web/src/features/nodes/components/NodeEditor.tsx, invokeai/frontend/web/src/features/system/components/SettingsModal/SettingsModal.tsx, invokeai/frontend/web/src/features/system/store/systemSlice.ts, invokeai/frontend/web/src/features/system/store/types.ts
adds a region wrapper with a highlight effect when that region is focused, this behavior can be toggled as a setting
Adds a region border highlight on focused regions. My approach to this was to create a Region Wrapper component responsible for handling focus state of children and using a pseudo element to highlight. This both reduces some verbosity in the focus management, and adds some visual clarity to the active region of the app.
This behavior can be toggled as a setting within the settings modal.
=> feat: :sparkles: Highlight Focused UI Regions

invokeai/frontend/web/src/features/dnd/FullscreenDropzone.tsx, invokeai/frontend/web/src/features/nodes/components/flow/Flow.tsx
- When focused in the Canvas, pasting is handled by the Canvas. Images will be pasted into the Canvas.
- When focused in the Workflow Editor, pasting is handled by the Workflow editor. Image pastes are ignored.
- When on either Canvas or Workflows tabs, when focused _outside_ the work areas, pasting is handled by the global image upload handler. Images will be pasted and then uploaded to gallery.
https://discord.com/channels/1020123559063990373/1149506274971631688/1349877631566483456
Try it out
n/a
=> feat(ui): allow pasting into gallery on canvas and workflows tabs

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/FloatGeneratorFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ImageGeneratorFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/IntegerGeneratorFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/StringGeneratorFieldComponent.tsx
fix(ui): generator widget should stretch to fill when added to builder
Minor visual issue
n/a
n/a
n/a
=> fix(ui): generator widget should stretch to fill when added to builder

invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/features/queue/components/CancelAllExceptCurrentButton.tsx, invokeai/frontend/web/src/features/queue/components/ClearQueueIconButton.tsx, invokeai/frontend/web/src/features/queue/components/QueueActionsMenuButton.tsx, invokeai/frontend/web/src/features/queue/components/QueueTabQueueControls.tsx, invokeai/frontend/web/src/features/ui/components/AppContent.tsx, invokeai/frontend/web/src/features/ui/components/FloatingParametersPanelButtons.tsx
Add `Cancel and Clear All` as an `AppFeature`, allowing it to be disabled.
When disabled, if we need to render something in its place, the `Cancel All Except Current` button is rendered instead.
Offline discussion
The `Cancel and Clear All` button is rendered in 4 places. Here are what those places look like when that feature is disabled.
- The main cancel button - replaced by `Cancel All Except Current`:
- The queue actions menu - omitted in the list:
- The floating panel buttons - replaced by `Cancel All Except Current`:
- The queue tab controls - replaced by `Cancel All Except Current`:
n/a
=> feat(ui): add cancel and clear all as toggleable app feature

invokeai/app/services/session_queue/session_queue_common.py, invokeai/app/services/session_queue/session_queue_sqlite.py
In #7688 we optimized queuing preparation logic. This inadvertently broke retrying queue items.
Previously, a `NamedTuple` was used to store the values to insert in the DB when enqueuing. This handy class provides an API similar to a dataclass, where you can instantiate it with kwargs in any order. The resultant tuple re-orders the kwargs to match the order in the class definition.
For example, consider this `NamedTuple`:
```py
class SessionQueueValueToInsert(NamedTuple):
foo: str
bar: str
```
When instantiating it, no matter the order of the kwargs, if you make a normal tuple out of it, the tuple values are in the same order as in the class definition:
```
t1 = SessionQueueValueToInsert(foo="foo", bar="bar")
print(tuple(t1)) # -> ('foo', 'bar')
t2 = SessionQueueValueToInsert(bar="bar", …
```
=> fix(app): incorrect values inserted when retrying queue item

invokeai/app/services/model_load/model_load_default.py, invokeai/backend/model_manager/legacy_probe.py, invokeai/backend/model_manager/util/model_util.py
Differentiate between malware detection and scan error.
Also fix string formatting issue with the error messages.
Investigation prompted by https://discord.com/channels/1020123559063990373/1020123559831539744/1351240891641237565
I suspect that issue is a transient scan error and not malware detection - I am able to download the model and it passes the scan.
n/a
n/a
=> feat(app): better errors when scanning models with picklescan

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/hooks/useStudioInitAction.ts, invokeai/frontend/web/src/common/components/OverlayScrollbars/ScrollableContent.tsx, invokeai/frontend/web/src/common/components/OverlayScrollbars/constants.ts, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/DataViewer.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/FloatFieldCollectionInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/FloatGeneratorFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ImageFieldCollectionInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/ImageGeneratorFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/IntegerFieldCollectionInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/IntegerGeneratorFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/StringFieldCollectionInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/StringGeneratorFieldComponent.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowLibrary/WorkflowLibrarySideNav.tsx, invokeai/frontend/web/src/features/nodes/store/workflowLibrarySlice.ts
* Adds concept of a `recommended` workflow tag that is presented with a little star
* Adds init action for studio `viewAllWorkflowsRecommended` that will open workflow library to browse view with recommended workflow selected
* Tweaked UI to make it clear that tags are scrollable when they overflow container, and moved reset icon to be next to Browse
=> Customized workflow browsing

invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowLibrary/WorkflowLibrarySideNav.tsx, invokeai/frontend/web/src/features/nodes/store/workflowLibrarySlice.ts
Minor fixes. Intended to push this to #7810 before merging.
n/a
n/a
n/a
=> ui: workflows recommended followup

invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasBrushToolModule.ts
When holding shift to draw straight lines, if clip to bbox is enabled, we should clip to bbox. 
Bug was introduced when clipping was totally disabled for shift-drawing in #7651.
Closes #7809
Try it out
n/a
=> fix(ui): clip shift-draw strokes to bbox when clip to bbox enabled

invokeai/backend/model_manager/legacy_probe.py
In #7780 we added FLUX Fill support, and needed the probe to be able to distinguish between "normal" FLUX models and FLUX Fill models.
Logic was added to the probe to check a particular state dict key (input channels), which should be 384 for FLUX Fill and 64 for other FLUX models.
The new logic was stricter and instead of falling back on the "normal" variant, it raised when an unexpected value for input channels was detected.
This caused failures to probe for BNB-NF4 quantized FLUX Dev/Schnell, which apparently only have 1 input channel.
After checking a variety of FLUX models, I loosened the strictness of the variant probing logic to only special-case the new FLUX Fill model, and otherwise fall back to returning the "normal" variant. This better matches the old behaviour and fixes the …
=> fix(mm): flux model variant probing

invokeai/app/invocations/flux_lora_loader.py, invokeai/app/invocations/model.py, invokeai/frontend/web/src/services/api/schema.ts
I had named them wonkily and caused some user confusion.
Here are all the new names
Wonky names introduced in #7795 
Are the names OK?
n/a
=> feat(nodes): clean up lora node names

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputFieldRenderer.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/StringField/StringFieldDropdown.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/StringField/StringFieldInput.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/StringField/StringFieldTextarea.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/StringField/useStringField.ts, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/StringFieldCollectionInputComponent.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementEditMode.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementFloatSettings.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementIntegerSettings.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementSettings.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementStringDropdownConfig.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementStringDropdownSettings.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementStringSettings.tsx, invokeai/frontend/web/src/features/nodes/types/workflow.ts
Add support for custom dropdowns for string fields in Builder. Workflow Builders can choose this for the string component and add options to it.
<video src="https://github.com/user-attachments/assets/c3af6e44-8f05-4987-b2b2-1c00586f1004"></video>
n/a
Try it out.
n/a
=> feat(ui): custom dropdowns for strings in builder

invokeai/frontend/web/src/features/nodes/util/graph/generation/addFLUXFill.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addInpaint.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addOutpaint.ts
Fix an issue where the wrong mask was being used in the inpaint graph.
Thanks to @dunkeroni for catching this: https://discord.com/channels/1020123559063990373/1149506274971631688/1353461523842076804
n/a
n/a
=> fix(ui): mask logic in graph builders

invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx, invokeai/frontend/web/src/features/nodes/components/NodeEditor.tsx
This was inadventently removed in #7786 and caused some minor layout overflow.
Noticed by aaronlink127 on discord: https://discord.com/channels/1020123559063990373/1020123559831539744/1353737287657062483
- Open an image in image viewer
- Resize window until the viewer region is not large enough for the image
- The image should fit to the viewer region and not be cut off/overflow
n/a
=> fix(ui): restore `display: flex` to image viewer and node editor

invokeai/app/run_app.py, invokeai/app/util/startup_utils.py
The `dev_reload` option to load Python changes on the fly should work for custom nodes as well as Invoke's own sources.
(Have y'all been trying to write nodes without this? Or do you have another hot-reloading mechanism you've been using instead?)
1. have some code in a `nodes/` subdirectory.
2. Run invoke with `INVOKEAI_DEV_RELOAD=true` environment variable. (Or set `dev_reload = True` in your `invokeai.yaml'.)
3. Run `invokeai-web`
4. Startup logs should include a `[jurigged] Watch` line for your nodes source.
5. When you edit that file, the log should include a `[jurigged] Update` line for it.
N/A
- N/A _Tests added / updated (if applicable)_
- N/A _Documentation added / updated (if applicable)_
=> fix: make dev_reload work for files in nodes/

tests/test_imports.py
This test imports all modules in the invokeai package and fails if there are any exceptions.
Existing issues are excluded to avoid blocking main.
=> Import Smoke Test

invokeai/app/util/startup_utils.py
The top-level `invokeai` package may have an obscured origin due to the way editible installs work, but it's much more likely that this module is from a specific file.
Fixes `expected str, bytes or os.PathLike object, not NoneType` error when launching from some editable installs.
https://discord.com/channels/1020123559063990373/1354081031040532524
Run invokeai-web with `INVOKEAI_DEV_RELOAD=True` and see that the log contains `[jurigged] Watch` lines for invokeai sources.
This is fixes a regression introduced by #7819 and should be included before 5.9 final.
=> fix: make source location discovery more robust

invokeai/app/api/routers/app_info.py, invokeai/app/run_app.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/system/components/AboutModal/AboutModal.tsx, invokeai/frontend/web/src/services/api/endpoints/appInfo.ts, invokeai/frontend/web/src/services/api/schema.ts
- Add route to get runtime config. This includes the config at runtime and a list of set fields (i.e. things that are not defaults).
- Update About modal to display the data. API Tokens are redacted.
https://github.com/user-attachments/assets/0255cb12-729d-48b4-be83-f7b2cb9a5ee2
n/a
Try it out, pretty simple change.
n/a
=> feat: show runtime config in about modal

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/inputs/StringGeneratorFieldComponent.tsx
Minor visual issue
Closes #7830
n/a
n/a
=> fix(ui): correctly render whitespace in strings in string generator previews

invokeai/backend/llava_onevision_model.py, invokeai/backend/model_manager/load/model_util.py
Let the LLaVA OneVision model report its own size.
Still cannot use the 7B model on my 4090.
n/a
n/a
n/a
=> fix(mm): LLaVA OneVision model calculates its own size

invokeai/app/invocations/image.py, invokeai/frontend/web/src/services/api/schema.ts
Handle edge case when user sets mask blur to 0 and we attempt to divide by zero
Closes #7850
n/a
n/a
=> fix(nodes): handle zero fade size (i.e. mask blur 0)

invokeai/app/api/routers/images.py, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/imageUploaded.ts, invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/common/hooks/useClientSideUpload.ts, invokeai/frontend/web/src/common/hooks/useImageUploadButton.tsx, invokeai/frontend/web/src/features/dnd/FullscreenDropzone.tsx, invokeai/frontend/web/src/features/gallery/components/GalleryUploadButton.tsx, invokeai/frontend/web/src/features/gallery/store/actions.ts, invokeai/frontend/web/src/features/system/store/configSlice.ts, invokeai/frontend/web/src/services/api/endpoints/images.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts
Adds support (behind flag) for client-side uploads. If enabled, image entries will be created via API and then uploaded using presigned URL provided by server. All other upload functionality should remain the same (listener actions, etc)
I tested pasting, drag n drop, and using button above gallery.
=> feat(ui, api): support for bulk client-side uploads

.github/workflows/python-checks.yml, .github/workflows/python-tests.yml, .github/workflows/typegen-checks.yml, pyproject.toml, tests/backend/flux/controlnet/test_state_dict_utils.py, tests/backend/flux/ip_adapter/test_xlabs_ip_adapter_flux.py
- Remove CUDA and ROCm from test matrix. We don't have GPU runners so there's no point in running these.
- Use `uv` for everything.
n/a
It it fits, I sits.
n/a
=> ci: streamline workflows

invokeai/app/invocations/image.py
The polynomial fit isn't perfect and we end up with alpha values of 1 instead of 0 when applying the mask. This in turn causes issues on canvas where outputs aren't 100% transparent and individual layer bbox calculations are incorrect.
I actually noticed this in testing but convinced myself I was seeing things:
- Inpaint a region
- Accept the inpainted region as new raster layer
- Toggle raster layer off and on - the area _around_ the raster layer changes brightness subtly
The impact on bbox was noted here:k
https://discord.com/channels/1020123559063990373/1149506274971631688/1355010785042104503
- Inpaint a region
- Accept the inpainted region as new raster layer
- Toggle raster layer off and on - the area _around_ the raster layer should not change at all
- The new raster layer's blue …
=> fix(nodes): expanded masks not 100% transparent outside the fade out region

invokeai/backend/flux/flux_state_dict_utils.py, invokeai/backend/model_manager/legacy_probe.py
Before FLUX Fill was merged, we didn't do any checks for the model variant. We always returned "normal".
To determine if a model is a FLUX Fill model, we need to check the state dict for a specific key. Initially, this logic was too strict and rejected quantized FLUX models. This issue was resolved, but it turns out there is another failure mode - some fine-tunes use a different key.
This change further reduces the strictness, handling the alternate key and also falling back to "normal" if we don't see either key. This effectively restores the previous probing behaviour for all FLUX models.
Closes #7856
Closes #7859
I have a variety of FLUX models already installed. My testing strategy:
- Set `use_memory_db: true` in `invokeai.yaml`
- Restart the server
- Scan my FLUX main models folder …
=> fix(mm): flux variant probing

invokeai/app/invocations/baseinvocation.py, invokeai/app/services/shared/graph.py, invokeai/app/util/custom_openapi.py, tests/test_config.py
- Add separate `InvocationRegistry` class to handle invocation registration. Previously it was all in `BaseInvocation` and `BaseInvocationOutput`. This was a bit awkward as logic for execution was mixed up with registration. The actual logic is the same, but the responsibilities are split up in a more logical way.
- Simplify the invocation typeadapter caching to use `@lru_cache(maxsize=1)` instead of what effectively was a bespoke version of the same logic.
- Update all tests and consumers to use the new methods.
- Improved type annotations for registration logic.
n/a
App should still work. Custom nodes should still work. Works for me. No issues expected as its pretty straightforward.
n/a
=> refactor(nodes): invocation registration logic

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts, invokeai/frontend/web/src/features/nodes/util/workflow/validateWorkflow.ts
Fixes an error when loading workflows. Looks like this: 
It occurs when a workflow has invalid edges. For example, between nodes that don't exist on the Invoke installation.
Previously, reactflow appears to have handled an edge case when using its `applyChanges` utility. If a change was provided without an item, it would skip that change. For example, an "add edge" change that somehow passed `null` as the edge, instead of a valid edge.
In our workflow loading and validation logic, invalid edges were removed from the array using `delete edges[i]`. This left "holes" in the array of edges. We then asked `reactflow` to add these edges to state. When it encountered one of the "holes", it skipped over it.
In a recent release (unsure which, somewhere between the latest v11 and ~v12.4) this seems …
=> fix(ui): error loading workflows

invokeai/frontend/web/src/features/gallery/hooks/useGalleryHotkeys.ts
Arrow keys should only navigate between tabs, not gallery images.
n/a
n/a
n/a
=> fix(ui): do not switch between images when focused on a tab element

invokeai/app/api/routers/session_queue.py, invokeai/app/services/session_queue/session_queue_common.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/flow/panels/TopPanel/TopLeftPanel.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/PublishWorkflowPanelContent.tsx, invokeai/frontend/web/src/features/queue/hooks/useEnqueueWorkflows.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useLoadWorkflowFromFile.tsx, invokeai/frontend/web/src/features/workflowLibrary/hooks/useLoadWorkflowFromImage.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useLoadWorkflowFromLibrary.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useLoadWorkflowFromObject.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useValidateAndLoadWorkflow.ts, invokeai/frontend/web/src/services/api/schema.ts
- Add missing conditions to button that starts publish flow, so that it is disabled when the graph is invalid
- Improved UX for choosing output node
- Added safeguard when loading workflows to delete ID field if present, which prevents an issue where a non-library workflow might be treated as one, causing weird bugs
- Add optional `published_workflow_id` to queue item model and enqueue batch endpoint
- Ensure `published_workflow_id` is passed when queuing validation run
n/a
n/a
n/a
=> feat: workflow publish followups

docker/Dockerfile, pyproject.toml, uv.lock
- Run `uv pip install` as the last step in the docker build - fixes #7883
- re-add the `sentencepiece` dependency, fixing a regression introduced as part of dependency cleanup:
```File "/opt/invokeai/invokeai/backend/util/hotfixes.py", line 6, in <module>
from diffusers.loaders.single_file_model import FromOriginalModelMixin
...
File "/opt/venv/lib/python3.12/site-packages/gguf/vocab.py", line 10, in <module>
from sentencepiece import SentencePieceProcessor
ModuleNotFoundError: No module named 'sentencepiece'
```
(this could probably use another look and review of whether any of that monkeypatching is still needed, but for now this is a fix)
Closes #7883 
`docker compose build --no-cache` should produce a working image. test with `docker compose up`.
Merge at will
=> Fix docker build and re-add missing dependency

invokeai/frontend/web/src/app/components/App.tsx, invokeai/frontend/web/src/app/components/GlobalHookIsolator.tsx, invokeai/frontend/web/src/app/components/GlobalModalIsolator.tsx, invokeai/frontend/web/src/app/store/store.ts, invokeai/frontend/web/src/features/nodes/components/flow/panels/TopPanel/ClearFlowButton.tsx, invokeai/frontend/web/src/features/nodes/components/flow/panels/TopPanel/SaveWorkflowButton.tsx, invokeai/frontend/web/src/features/nodes/components/flow/panels/TopPanel/TopLeftPanel.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowListMenu/ActiveWorkflowNameAndActions.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowName.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowsTabLeftPanel.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/form-manipulation.test.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/viewMode/EmptyState.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/IsolatedWorkflowBuilderWatcher.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/PublishWorkflowPanelContent.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowJSONTab.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/publish.ts, invokeai/frontend/web/src/features/nodes/hooks/useIsWorkflowEditorLocked.ts, invokeai/frontend/web/src/features/nodes/store/nodesSlice.ts, invokeai/frontend/web/src/features/nodes/store/types.ts, invokeai/frontend/web/src/features/nodes/store/workflowSlice.ts, invokeai/frontend/web/src/features/nodes/types/workflow.ts, invokeai/frontend/web/src/features/nodes/util/workflow/buildWorkflow.ts, invokeai/frontend/web/src/features/queue/components/InvokeButtonTooltip/InvokeButtonTooltip.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/LoadWorkflowConfirmationAlertDialog.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/NewWorkflowConfirmationAlertDialog.tsx, invokeai/frontend/web/src/features/workflowLibrary/components/WorkflowLibraryMenu/SaveWorkflowMenuItem.tsx, invokeai/frontend/web/src/features/workflowLibrary/hooks/useCreateNewWorkflow.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useSaveLibraryWorkflow.ts, invokeai/frontend/web/src/features/workflowLibrary/hooks/useSaveOrSaveAsWorkflow.ts, invokeai/frontend/web/src/services/events/setEventListeners.tsx
- Rework unsaved changes tracking, fixing a number of issues and some awkward UX.
- Make published state server-side state. 
n/a
Try opening and editing a workflow. It should track unsaved changes correctly. The workflow empty state should be detected correctly (i.e. when the workflow is identical to what you get when you make a new workflow, you should see empty state prompting you to load or create a new workflow).
n/a
=> refactor(ui): workflow unsaved changes/published state tracking

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/sidePanel/PublishedWorkflowPanelContent.tsx, invokeai/frontend/web/src/features/queue/components/QueueList/QueueItemComponent.tsx, invokeai/frontend/web/src/features/workflowLibrary/hooks/useLoadWorkflowFromLibrary.ts, invokeai/frontend/web/src/services/api/endpoints/workflows.ts
* make sure is_published is correctly set when workflow is loaded
* add endpoint for unpublishing
* make sure validation runs can be canceled but not retried
=> (ui): more publishing follow-ups

invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasColorPickerToolModule.ts
Alpha values are 0-1 in CSS but 0-255 in Canvas. Need to normalize to 0-1 when picking color else the alpha value gets borked.
https://discord.com/channels/1020123559063990373/1020123559831539744/1358840412546011431
Color picker should work for alpha 
n/a
=> fix(ui): normalize alpha value to 0-1 when picking color on canvas

invokeai/app/invocations/flux_redux.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/FLUXReduxImageInfluence.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterImagePreview.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterMethod.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterSettings.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceIPAdapterSettings.tsx, invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/controlLayers/store/util.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addFLUXRedux.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addRegions.ts, invokeai/frontend/web/src/services/api/schema.ts
Add downsampling and weight to Redux node - This should allow the main prompt conditioning to gain some traction over a Redux conditioning.
The downsampling and weight idea is derived from https://github.com/kaibioinfo/ComfyUI_AdvancedRefluxControl
- Downsampling of 3-4 is where the main prompt starts to gain some traction. 
- Weight of 0.3-0.4 is where it weakens the redux conditioning enough for the main prompt to have an effect. 
Downsampling reduces the size of the redux conditioning
Weight reduces the intensity of the conditioning but not the size
N/A
Test defaults to work like the previous non-down-sampled redux
https://stable-diffusion-art.com/flux-redux/ - article on the original comfy node. 
Needs testing and reviewing and frontend consideration discussed
=> Update flux_redux.py with downsampling and weight options

invokeai/frontend/web/src/common/util/convertImageUrlToBlob.ts, invokeai/frontend/web/src/features/controlLayers/components/common/CanvasEntityPreviewImage.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/useSaveLayerToAssets.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/konva/util.ts
When calling `ctx.drawImage()`, if the image to be drawn has a width of height of 0, the call will raise.
In this change, I have carefully reviewed the call hierarchy for all of our own code that calls this method and ensured that each call has error handling.
Well, with one exception - I'm not sure how to handle errors in `invokeai/frontend/web/src/common/hooks/useClientSideUpload.ts`. But this should never be an issue in that hook - it's a Canvas problem.
n/a
This is a pretty safe change. It only adds additional error handling for edge cases. 
n/a
=> feat(ui): safer use of drawImage

invokeai/frontend/web/src/features/dnd/DndListDropIndicator.tsx
Was set to bright red ages ago for troubleshooting but never reverted to be gray. Now its gray
n/a
n/a
n/a
=> fix(ui): canvas dnd drop indicator color

invokeai/frontend/web/src/features/controlLayers/hooks/useCanvasIsBusy.ts, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewCanvasFromImageSubMenu.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewLayerFromImageSubMenu.tsx, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/SingleSelectionMenuItems.tsx
Add `useCanvasIsBusySafe()` hook. This is like `useCanvasIsBusy()`, but when the canvas is not initialized, it gracefully falls back to false instead of raising.
Because app tabs are lazy-loaded, the canvas is not initialized until the user visits that tab. If the page loads up on the workflows tab, the canvas will be uninitialized until the user clicks on it.
This graceful fallback behaviour allows actions like sending an image to canvas to work even when the canvas is not yet initialized. These actions are exposed in the image context menu, and previously were hidden when the canvas was not initialized. We can now show these actions and use them even when the canvas is uninitialized.
- Add `useCanvasIsBusySafe()` hook
- Use the new hook in the image context menu for send to canvas …
=> feat(ui): allow send-image-to-canvas to work when canvas is uninitialized

.github/workflows/uv-lock-checks.yml, pyproject.toml, uv.lock
ci: add check for `uv` lockfile consistency with `pyproject.toml`
Inconsistency noted on discord by @keturn:
https://discord.com/channels/1020123559063990373/1049495067846524939/1360297727447011601
We have an inconsistency, so this PR should fail the check. I'll push a fixed lockfile after it fails, and confirm the updated lockfile lets the check pass.
Once pushed, we should add this check to the required checks for PR.
=> ci: add check for `uv` lockfile consistency with `pyproject.toml`

invokeai/app/invocations/infill.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/PublishWorkflowPanelContent.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/publish.ts, invokeai/frontend/web/src/features/nodes/store/selectors.ts
=> feat: publish misc

.pre-commit-config.yaml
- updates pre-commit syntax
- adds check for an outdated `uv.lock`, which will only run if `pyproject.toml` is being updated in the commit.
=> Add uv lock check to git pre-commit

invokeai/app/api/dependencies.py
I had set this to zero for testing udring the python 2.6.0 upgrade and neglected to remove it.
n/a
n/a
n/a
=> fix(app): remove accidentally committed tensor cache size

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/setDefaultSettings.ts, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/socketConnected.ts
fix(ui): ensure query subs are reset in case of error
prevent memory leak-ish behaviour
n/a
n/a
n/a
=> fix(ui): ensure query subs are reset in case of error

invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/WorkflowBuilder.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/viewMode/ViewModeLeftPanelContent.tsx
I am at loss as the to cause of this bug. The styles that I needed to change to fix it haven't been changed in a couple months. But these do seem to fix it.
Closes #7910
Confirm the builder form scrolls in both edit and view modes. I've tested successfully in FF and Chrome on macOS.
n/a
=> fix(ui): scrolling in builder

invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/DataViewer.tsx
All JSON dataviewers now wrap long lines.
Before:
<video src="https://github.com/user-attachments/assets/07d4afe8-f445-48b1-9d8d-542feef9d230"></video>
New:
<video src="https://github.com/user-attachments/assets/48b50e7a-617d-4c59-b474-24b82c8a7a8d"></video>
n/a
n/a
n/a
=> feat(ui): wrap JSON in dataviewer

invokeai/app/services/model_install/model_install_default.py, tests/test_model_probe.py, tests/test_model_probe/stripped_models/helloyoung25d_V15j.safetensors
There is a subtle change in behaviour with the new model probe API.
Previously, checks for model types was done in a specific order. For example, we did all main model checks before LoRA checks.
With the new API, the order of checks has changed. Check ordering is as follows:
- New API checks are run first, then legacy API checks.
- New API checks categorized by their speed. When we run new API checks, we sort them from fastest to slowest, and run them in that order. This is a performance optimization.
Currently, LoRA and LLaVA models are the only model types with the new API. Checks for them are thus run first.
LoRA checks involve checking the state dict for presence of keys with specific prefixes. We expect these keys to only exist in LoRAs.
It turns out that main models may have some of …
=> fix(mm): disable new model probe API

invokeai/frontend/web/src/features/nodes/types/common.ts, invokeai/frontend/web/src/services/events/onInvocationComplete.tsx
Previously, when a node completed, we checked to see if its output was _exactly_ an `ImageOutput`. If so, we add the image to the gallery. But there are multiple types of nodes that output images via some other output class. For example, an `ImageCollectionOutput`. When a node outputted one of these other classes, the UI wouldn't update the gallery. You'd have to refresh the page to see the image in gallery.
With the change in this PR, when a node completes, we check each of its output's properties. If any are an `ImageField` or `list[ImageField]`, they are all added to the gallery. This covers `ImageOutput`, `ImageCollectionOutput`, and all other outputs that have an image.
@skunkworxdark mentioned on discord: https://discord.com/channels/1020123559063990373/1049495067846524939/1365019122 …
=> feat(ui): add _all_ image outputs to gallery (including collections)

invokeai/app/invocations/baseinvocation.py, invokeai/app/util/custom_openapi.py, invokeai/frontend/web/src/services/api/schema.ts
Adds an optional output_metadata dict to invocations that can be used for internal outputs that we do not want to surface to UI/user
=> add optional output_metadata to baseinvocation

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/GlobalReferenceImageModel.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterImagePreview.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterSettings.tsx, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/RegionalReferenceImageModel.tsx, invokeai/frontend/web/src/features/controlLayers/components/RegionalGuidance/RegionalGuidanceIPAdapterSettings.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/addLayerHooks.ts, invokeai/frontend/web/src/features/controlLayers/hooks/saveCanvasHooks.ts, invokeai/frontend/web/src/features/controlLayers/hooks/useIsEntityTypeEnabled.ts, invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/controlLayers/store/util.ts, invokeai/frontend/web/src/features/imageActions/actions.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildChatGPT4oGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildImagen3Graph.ts, invokeai/frontend/web/src/services/api/hooks/modelsByType.ts, invokeai/frontend/web/src/services/api/types.ts
Support for reference images and img2img for ChatGPT 4o.
n/a
n/a
n/a
=> feat(ui): chatgpt ref images & img2img

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/enqueueRequestedLinear.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildChatGPT4oGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildFLUXGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildImagen3Graph.ts, invokeai/frontend/web/src/features/nodes/util/graph/types.ts
=> feat(ui): show unsupported gen mode toasts as warnings intead of errors

invokeai/app/util/misc.py
Quick fix for a deprecated function in the get_iso_timestamp function.
=> fix: deprecation warning in get_iso_timestamp

invokeai/app/api/routers/model_manager.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/HuggingFaceFolder/HFToken.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/HuggingFaceFolder/HuggingFaceForm.tsx, invokeai/frontend/web/src/services/api/endpoints/models.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts, invokeai/frontend/web/src/services/events/onModelInstallError.tsx
Sometimes the user has a valid HF token saved but needs to reset. For example, they set a token w/ incorrect permissions.
This PR adds a UI to reset the token. Here are the possible states & UX for the HF tab in MM:
<video src="https://github.com/user-attachments/assets/6d29af78-bd49-40de-b665-400ecde0a1f5"></video>
For whatever reason, this has popped up a _lot_ recently in discord.
- Closes #7980
If you already have a valid HF token saved, you should see the new UI where the token is displayed in a disabled input field (it's not your actual token, it's 37 letter `a`, same length as a real token).
Try resetting, setting an invalid token and setting a valid token.
🚨 The `Reset` button uses the HF Hub to reset the token. This permanently deletes the token from the HF hub cache. You'll need …
=> feat: UI to reset HF token

invokeai/frontend/web/src/app/components/InvokeAIUI.tsx, invokeai/frontend/web/src/app/store/nanostores/toastMap.ts, invokeai/frontend/web/src/features/toast/toast.ts, invokeai/frontend/web/src/services/api/authToastMiddleware.ts
This is Step 1 in introducing support for custom error toasts. This only works for our usage limit errors, but followup work will add more cases. The back-end is not yet updated to support error codes, so for not we are checking a substring of the error message and looking up in the map based on that.
=> feat(ui): custom error toast support

invokeai/app/invocations/baseinvocation.py, invokeai/app/invocations/batch.py, invokeai/frontend/web/src/services/api/schema.ts, tests/app/invocations/test_is_optional.py
When we do our field type overrides to allow invocations to be instantiated without all required fields, we were not modifying the annotation of the field but did set the default value of the field to `None`.
This results in an error when doing a ser/de round trip. Here's what we end up doing:
```py
from pydantic import BaseModel, Field
class MyModel(BaseModel):
foo: str = Field(default=None)
```
And here is a simple round-trip, which should not error but which does:
```py
MyModel(**MyModel().model_dump())
```
To fix this, we now check every incoming field and update its annotation to match its default value. In other words, when we override the default field value to `None`, we make its type annotation `<original type> | None`.
This prevents the error during deserialization.
This …
=> fix(nodes): pydantic field type massaging improvements

invokeai/app/api/dependencies.py, invokeai/app/api/routers/model_relationships.py, invokeai/app/api_app.py, invokeai/app/services/invocation_services.py, invokeai/app/services/model_relationship_records/model_relationship_records_base.py, invokeai/app/services/model_relationship_records/model_relationship_records_sqlite.py, invokeai/app/services/model_relationships/model_relationships_base.py, invokeai/app/services/model_relationships/model_relationships_common.py, invokeai/app/services/model_relationships/model_relationships_default.py, invokeai/app/services/shared/sqlite/sqlite_util.py, invokeai/app/services/shared/sqlite_migrator/migrations/migration_20.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/hooks/useRelatedGroupedModelCombobox.ts, invokeai/frontend/web/src/common/hooks/useRelatedModelKeys.ts, invokeai/frontend/web/src/common/hooks/useSelectedModelKeys.ts, invokeai/frontend/web/src/features/lora/components/LoRASelect.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelView.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/RelatedModels.tsx, invokeai/frontend/web/src/services/api/endpoints/modelRelationships.ts, invokeai/frontend/web/src/services/api/index.ts, invokeai/frontend/web/src/services/api/schema.ts, tests/conftest.py
Adds full support for managing model-to-model relationships in the UI and backend.
Introduces RelatedModels subpanel for linking and unlinking models in model management.
- Adds REST API routes for adding, removing, and retrieving model relationships.
- New database migration: creates model_relationships table for bidirectional links.
- New service layer (model_relationships) for relationship management.
- Updated frontend: Related models float to top of LoRA/Main grouped model comboboxes for quick access.
- Added 'Show Only Related' toggle badge to MainModelPicker filter bar
---
Introduces a full system for managing model-to-model relationships.
New database migration: model_relationships table (bidirectional, FK constrained, cascade deletes, sorted input).
New service layer: …
=> feat(ui): model relationship management

invokeai/backend/model_manager/load/model_cache/cached_model/cached_model_only_full_load.py, invokeai/backend/quantization/gguf/ggml_tensor.py
If a user has not enabled partial loading, and disabled  keeping copies of the models state dict  in CPU VRAM (both likely for MPS users) then GGUF models state dicts are not moved to the compute device from cpu device that models are loaded into by default. This is due to the quantised data being stored in its own field instead of the inherited Tensors data field.
This PR uses an overload of the Tensor `to`  method to  load the quantised data to the compute device when the model is moved by calling is `to` method,
Closes #7939
Duplicate the failure by removing  `enable_partial_loading: true` and adding `keep_ram_copy_of_weights: false` to invokeai.yaml as necessary  and attempting to run a image generation using a GGUF quantised Flux model.
Note: enable_partial_loading: true needs to be …
=> Add to overload for GGMLTensor, so calling to on the model moves the quantized data.

pins.json, pyproject.toml, uv.lock
- Update `pyproject.toml`
- Update `pins.json` so launcher installs latest CUDA 12.8 & ROCm 6.3
I've tested MPS on macOS and CUDA on Linux briefly. FLUX, SDXL and SD1.5 - no obvious issues.
Quite a few users have been testing 2.7.0 on Windows w/ 50xx series GPUs without any issues AFAIK. So I think we are safe to bump this dependency.
Test more?
n/a
=> chore: bump torch to 2.7.0

invokeai/app/invocations/denoise_latents.py, invokeai/app/invocations/ip_adapter.py, invokeai/backend/stable_diffusion/diffusers_pipeline.py, invokeai/backend/stable_diffusion/diffusion/conditioning_data.py, invokeai/backend/stable_diffusion/diffusion/custom_atttention.py, invokeai/backend/stable_diffusion/diffusion/unet_attention_patcher.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/IPAdapter/IPAdapterMethod.tsx, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/nodes/types/common.ts, invokeai/frontend/web/src/services/api/schema.ts
This pull request introduces enhancements to the IP-Adapter functionality, including the addition of two new methods (`style_strong` and `style_precise`) and corresponding updates across the backend and frontend to support these methods. Key changes include updates to data models, invocation logic, attention processing, and the user interface.
* **New Methods and Logic:**
- Added `style_strong` and `style_precise` methods to the `IPAdapterInvocation` class, with specific logic for determining target attention blocks based on the base type (e.g., `sd-1`, `sdxl`). (`[[1]](diffhunk://#diff-c63c2992c76f7ae765f25b13f9ecd2b8bb63eef5e5159dfa218a37926f95f980L97-R98)`, `[[2]](diffhunk://#diff-c63c2992c76f7ae765f25b13f9ecd2b8bb63eef5e5159dfa218a37926f95f980R151-R182)`)
* **Attention Processing …
=> Expanded IP Adapter modes.

invokeai/frontend/web/src/common/hooks/useImageUploadButton.tsx, invokeai/frontend/web/src/features/dnd/FullscreenDropzone.tsx
Single image uploads should continue using the main /upload endpoint even if client-side uploads are enabled, so that users have a path to retain metadata on upload if they need to.
=> fix(ui): only use client-side uploads if more than one image

invokeai/app/invocations/composition-nodes.py, invokeai/app/invocations/create_gradient_mask.py, invokeai/app/invocations/fields.py, invokeai/app/invocations/ideal_size.py, invokeai/app/invocations/image.py, invokeai/frontend/web/src/features/nodes/util/schema/buildFieldInputTemplate.ts, invokeai/frontend/web/src/features/nodes/util/schema/parseSchema.ts, invokeai/frontend/web/src/services/api/schema.ts
Fixes and better error handling for invalid invocation field default values.
Discord thread: https://discord.com/channels/1020123559063990373/1149506274971631688/1374029733423087636
Using this repo as a test https://github.com/mickr777/imagetoasciiimage
- No error in launcher/python terminal, just looks fine
- UI hangs at loading screen
- Error like this in the JS console of browser
- Big error in launcher/python terminal
- UI does not hang
- If, somehow, the invocation gets past the python safeguards, instead of hanging the UI, the error is logged and the UI loads.
Example terminal error:
```sh
[2025-05-20 08:30:45,802]::[InvokeAI]::ERROR --> Failed to load node pack imagetoasciiimage (may have partially loaded):
Traceback (most recent call last):
File …
```
=> fix(nodes): better defaults parsing and error handling

invokeai/app/services/model_install/model_install_default.py, invokeai/backend/model_manager/config.py, invokeai/backend/model_manager/model_on_disk.py, scripts/classify-model.py, scripts/strip_models.py, tests/test_model_probe.py
- Fallback to new classification API if legacy probe fails
- Method to read model metadata
- Created `StrippedModelOnDisk` class for testing
- Test to verify only a single config `matches` with a model
=> Re-enable classification API as fallback

invokeai/app/invocations/segment_anything.py
Upstream bug in `transformers` breaks use of `AutoModelForMaskGeneration` class to load SAM models
Simple fix - directly load the model with `SamModel` class instead.
See upstream issue https://github.com/huggingface/transformers/issues/38228
n/a
- Update `transformers` e.g. `uv pip install transformers --reinstall && uv pip install -e .`
- Do a select object on Canvas
Before the fix, we expect an error like this:
```
ValueError: Unrecognized configuration class <class 'transformers.models.sam.configuration_sam.SamConfig'> for this kind of AutoModel: AutoModelForMaskGeneration.
Model type should be one of SamHQConfig.
```
After the fix, it should work.
n/a
=> fix(nodes): transformers bug with SAM

invokeai/backend/quantization/gguf/utils.py
When using torch.compile with a Flux-type GGUF model, tlparse reports this error:
> Unsupported method call
>  Explanation: Dynamo does not know how to trace method `__contains__` of class `set`
>  Hint: Avoid calling `set.__contains__` in your code.
>  Hint: Please report an issue to PyTorch.
This is in `get_dequantized_tensor`, which gets called frequently enough for this to have a significant influence.
Changing the collection from a set to a list is sufficient to make it compatible.
See https://github.com/pytorch/pytorch/issues/145761
Run a GGUF.
=> fix: improve gguf performance with torch.compile

invokeai/frontend/web/src/features/controlLayers/konva/CanvasStageModule.ts
This pull request updates the zooming functionality in the `CanvasStageModule` to improve user experience by refining the scale factor and introducing snapping to common zoom levels. The changes ensure smoother scaling and better precision when zooming in and out.
* **Refined Scale Factor**: Updated the `SCALE_FACTOR` in the `DEFAULT_CONFIG` from `0.999` to `0.9995` for finer zoom adjustments. (`invokeai/frontend/web/src/features/controlLayers/konva/CanvasStageModule.ts`, [invokeai/frontend/web/src/features/controlLayers/konva/CanvasStageModule.tsL34-R34](diffhunk://#diff-4d008037af05cbd6c6475c45bc99bd430905bcd90da5ed8cb3a42881ed950a35L34-R34))
* **Enhanced Scale Constraining**: Modified the `constrainScale` method to:
- Round the scale to two decimal places to address floating-point …
=> Update scaling math to land on 100% consistently.

invokeai/frontend/web/src/features/controlLayers/util/getScaledBoundingBoxDimensions.ts, invokeai/frontend/web/src/features/parameters/util/optimalDimension.ts
This adds a quick check to the bbox auto scaling to leave the values alone when using an SDXL model and the dimensions are one of the standard sizes that SDXL was trained on. Scaling to nearby dimensions that do not play well with the Unet's internal downscaling results in edge artifacts.
All of the override dimensions are within 10% of the ~1MiP target size of the autoscaling code, and skipping the upscale will also avoid compression and reduce the number of saved intermediate images.
Previous discussion and suggestion of hard-coding fix:
https://discordapp.com/channels/1020123559063990373/1049495067846524939/1301654971254575175
Recent mention of the bug:
https://discordapp.com/channels/1020123559063990373/1020123559831539744/1375205214839115796
Original investigation about it a year ago …
=> Fix: Don't auto-scale away from SDXL training sizes

invokeai/app/invocations/compel.py, pyproject.toml, uv.lock
This pull request introduces changes to improve text handling in the compel node and updates project metadata and dependencies in `pyproject.toml`. Key updates include enabling sentence-based splitting for long text prompts, updating dependency versions, and revising project metadata to reflect the current state of the project.
We should consider advising that *very* long prompts may have different results using the new parsing logic, but are reproducible if manually split using the .and() parsing logic.
* Added `SplitLongTextMode.SENTENCES` to the `split_long_text_mode` parameter in two instances of `Compel` initialization, enabling more graceful splitting of long text prompts. [[1]](diffhunk://#diff-14e9e596b255e04c7d7909744a6e4378bffaf024e8eddd1cf9626a69d1ade79dR107) …
=> Update Compel to 2.1.1 and apply Sentences Split logic

invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbarScale.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStageModule.ts
Revised scale snapping on canvas.
Tracks the "intended" scale separately from "effective" scale to allow for snapping that does not inadvertently lock the scale to snap points, as described in #8048.
Also removed a couple constraints that were causing some jank:
- Canvas Scale is no longer rounded, allowing the scaling on touchpads to be smoother and get "stuck" less
- Canvas Position is no longer rounded, preventing the drift of canvas position while scaling in and out
n/a
n/a
n/a
=> feat(ui): revised canvas scale snapping

invokeai/app/api/routers/images.py, invokeai/app/invocations/controlnet.py, invokeai/app/util/controlnet_utils.py, invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewCanvasFromImageSubMenu.tsx, invokeai/frontend/web/src/features/imageActions/actions.ts, invokeai/frontend/web/src/services/api/endpoints/images.ts, invokeai/frontend/web/src/services/api/schema.ts, invokeai/frontend/web/src/services/api/types.ts, pyproject.toml, uv.lock
Make `heuristic_resize` ~20x faster. This function is a high-quality image resizing function that preserves Canny edge maps and segmentation maps much better than traditional interpolation. This function was inherited from `controlnet_aux`.
- Previously this kind of resize took ~4s to run on a 1024x1024 edge map with moderate edge density. Now it takes under 200ms.
- The outputs are slightly different for Canny edge maps, but IMO the new algo looks a tiny bit better - fewer spurious dingleberries. Segmentation maps and "normal" images are handled in the same way as the previous algo.
- Use the resize functionality with creating new layers & resizing at the same time, for example when using these actions:
- Add `resize_to` to upload endpoint. When dimensions are provided, the image is …
=> feat(nodes): faster heuristic resize, support resizing on upload, use it in canvas

invokeai/frontend/web/src/features/controlLayers/konva/CanvasCompositorModule.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addInpaint.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/addOutpaint.ts
Broken in #8035 because mask inversion was previously handled by the alpha-to-mask node which is no longer used. 
Now addInpaint and addOutpaint will pass `canvasSettings.preserveMask`, and compositing includes this boolean in the caching.
ready to merge
=> Fix: "Preserve Masked Region" for new mask compositing

invokeai/frontend/web/src/common/hooks/usePersistedTextareaSize.ts, invokeai/frontend/web/src/features/parameters/components/Core/ParamNegativePrompt.tsx, invokeai/frontend/web/src/features/parameters/components/Core/ParamPositivePrompt.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLPrompts/ParamSDXLNegativeStylePrompt.tsx, invokeai/frontend/web/src/features/sdxl/components/SDXLPrompts/ParamSDXLPositiveStylePrompt.tsx, invokeai/frontend/web/src/features/ui/store/uiSlice.ts, invokeai/frontend/web/src/features/ui/store/uiTypes.ts
Store height of positive prompt box in redux so it persists across refreshes
=> feat(ui): persist prompt box sizes

invokeai/backend/patches/layer_patcher.py
Chroma users will want to apply FLUX LoRA to Chroma models, despite the differences.
This PR changes the default behavior of LayerPatcher to continue operating (with a warning) after attempting to patch a missing layer.
In the case of Chroma, we have a good idea of which layers those will be, so we also provide a way to disable the warning for the expected layers.
- [Chroma discord thread](https://discord.com/channels/1020123559063990373/1369804553721217186)
- overall Chroma issue: #7986 
No code in core uses this yet, though do test that existing LoRA still work.
With this PR, the [Chroma node](https://gitlab.com/keturn/chroma_invoke) should be able to run with FLUX LoRA.
N/A
=> feat(LoRA): allow LoRA layer patcher to continue past unknown layers

invokeai/app/invocations/baseinvocation.py, invokeai/app/run_app.py, invokeai/app/util/custom_openapi.py
feat(ui): warn on unregistered invocation output
@JPPhoto got hit with the lack of warning and led to confusion in https://discord.com/channels/1020123559063990373/1083864753543331981/1376954234356105279
JP's node (without the decorator) should log a warning as the UI parses node templates
n/a
=> feat(ui): warn on unregistered invocation output

invokeai/app/run_app.py
Fix for `RuntimeError: configure_torch_cuda_allocator() must be called before importing torch.` on app start
```
Traceback (most recent call last):
File "D:\InvokeMain\InvokeAI\scripts\invokeai-web.py", line 20, in <module>
main()
File "D:\InvokeMain\InvokeAI\scripts\invokeai-web.py", line 16, in main
run_app()
File "D:\InvokeMain\InvokeAI\invokeai\app\run_app.py", line 33, in run_app
configure_torch_cuda_allocator(app_config.pytorch_cuda_alloc_conf, logger)
File "D:\InvokeMain\InvokeAI\invokeai\app\util\torch_cuda_allocator.py", line 13, in configure_torch_cuda_allocator
raise RuntimeError("configure_torch_cuda_allocator() must be called before importing torch.")
RuntimeError: configure_torch_cuda_allocator() must be called before importing torch.
```
=> (Fix)(app) Delay Imports that require torch for app launch

invokeai/frontend/web/src/features/controlLayers/components/CanvasBusySpinner.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasMainPanelContent.tsx, invokeai/frontend/web/src/features/controlLayers/contexts/EntityAdapterContext.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityAdapterBase.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStageModule.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/imageActions/actions.ts
- Fix issue where creating a new canvas from an image using one of the pictured buttons can result in the new layer being offset from the bbox, if the bbox had previously been moved.
- Fix issue where canvas isn't always centered and zoomed correctly when creating new canvas from an image
- Add a spinner that renders when the canvas is busy rasterizing, compositing (the pause between clicking Invoke and the graph getting queued) or calculating the bbox rect. Just a subtle hint that "we are doing something right now, don't be alarmed that nothing is happening"
- Add quick animation when fitting canvas view to make it less jarring
Reported somewhere in discord. I think the two issues have existed for a long time and are not new.
Demo of new behaviours: …
=> feat(ui): canvas stage, zoom, and fit improvements

invokeai/app/services/image_records/image_records_sqlite.py
This includes the `created_at` field in the gallery search. It does not do any smart parsing or before/after limits, but the user can follow the formatting in the Image Details viewer.
Shouldn't interfere with anything, and I'm pretty sure the impact on the search time is negligible.
=> Make image creation dates searchable in the gallery

invokeai/backend/ip_adapter/README.md, invokeai/backend/model_manager/starter_models.py
This pull request introduces`ip_adapter_plus_sdxl`, to the OSS Starter Models. The changes include documentation updates, model definition, and integration into relevant model bundles.
* **Documentation Update**: Added a link to the new `ip_adapter_plus_sdxl` model in the `IP-Adapters` section of the `README.md` file.
* **Model Definition**: Defined the new `ip_adapter_plus_sdxl` model in the `StarterModel` class, specifying its name, base model type, source, description, type, dependencies, and previous names.
* **Model Bundles Update**: Integrated `ip_adapter_plus_sdxl` into two model bundles in `starter_models.py` to ensure its availability alongside other models. [[1]](diffhunk://#diff-cbab31161be13858ecbcea1986df815ac0d6fd75d596a1b4dc44893dea3f1631R684) …
=> Add Precise Reference to SDXL Starter Models

invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/PublishWorkflowPanelContent.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/publish.ts
disable publish and cancel buttons once it begins
=> disable publish and cancel buttons once it begins

invokeai/app/invocations/compel.py, invokeai/app/services/session_processor/session_processor_default.py, invokeai/backend/model_patcher.py
Reduce peak memory usage by Invoke process. See commits for details.
TL;DR: We thought we had a memory leak. Not sure about that. I think we may just have a slowly climbing memory usage that eventually peaks and plateaus. Before we plateau, it looks like we have a memory leak.
Once the process allocates memory from the OS, it can never give it back, but it can re-use it. So the apparent memory leak is actually internal poor management of allocations, stemming frmo our usage patterns
- `del` patched tokenizer and related objects in compel nodes so python can free up the arenas used by them
- Skip TI patching logic when there are no TIs to patch
- GC before each queue item
Sampled process memory usage after each queue item (SDXL t2i nothing extra). First column is memory at that time, …
=> perf(app): reduce peak memory usage

invokeai/app/api_app.py, invokeai/app/invocations/baseinvocation.py, invokeai/app/invocations/fields.py, invokeai/app/services/images/images_default.py, invokeai/app/services/model_install/model_install_default.py
This small PR focuses on resolving the deprecation warnings of the `logger` library which you can find in the [CI logs](https://github.com/invoke-ai/InvokeAI/actions/runs/15506381315/job/43661781656#step:7:116):
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> Migrate to modern logger interface

invokeai/app/services/session_queue/session_queue_sqlite.py
In #7724 we made a number of perf optimisations related to enqueuing. One of these optimisations included moving the enqueue logic - including expensive prep work and db writes - to a separate thread.
At the same time manual DB locking was abandoned in favor of WAL mode.
Finally, we set `check_same_thread=False` to allow multiple threads to access the connection at a given time.
I think this may be the cause of #7950:
- We start an enqueue in a thread (running in bg)
- We dequeue
- Dequeue pulls a partially-written queue item from DB and we get the errors in the linked issue
To be honest, I don't understand enough about SQLite to confidently say that this kind of race condition is actually possible. But:
- The error started popping up around the time we made this change.
- I have reviewed …
=> fix(app): guard against possible race conditions during enqueue

invokeai/frontend/web/package.json, invokeai/frontend/web/pnpm-lock.yaml, invokeai/frontend/web/src/features/gallery/components/ImageMetadataViewer/DataViewer.tsx
The frontend metadata viewer uses fracturedjsonjs to format the JSON.  There are some cases where the commas look out of place and can cause unnecessary wrapping.  Updating to version 4.1.0 and setting two options fixes that.
Closes #8092 
Open an image in the viewer, click on the info icon, and select the metadata tab.  Look for the `model` property.  It should be an object whose values are all strings (at least, that's all I've seen).  If the code change worked, there should be no spaces between the strings' closing quotes and the commas that follow them.  (See issue #8092 for more clarification.)
N/A
=> Updated fracturedjsonjs to version 4.1.0 for friendlier comma placement

invokeai/app/services/config/config_default.py, invokeai/frontend/web/src/services/api/schema.ts, tests/backend/util/test_devices.py
Bring in support for defining a cuda gpu slot higher then 1.
Closes https://github.com/invoke-ai/InvokeAI/issues/8102
Ran the device pytest.
=> Update supported cuda slot input.

invokeai/app/invocations/baseinvocation.py
`_original_model_fields` is a dict `ClassVar` on `BaseInvocation`. It stores the original fields for an Invocation, before any modifications are made by the `@invocation` decorator.
Individual Invocations were _intended_ to override the whole dict, but instead they added their own fields to it. 
```py
cls._original_model_fields[field_name] = OriginalModelField(annotation=annotation, field_info=field_info)
```
The dict was therefore accidentally  **shared amongst all invocation classes**. Here's what it looks like for `IPAdapterInvocation`:
Note that a ton of fields unrelated to IP Adapter are in there. It shouldn't have those! Here's what it should look like:
Note that it only includes fields from the IP Adapter node.
---
This bug has a knock-on effect when two invocations share the same …
=> fix(nodes): ensure each invocation overrides _original_model_fields with own field data

invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbarSaveToGalleryButton.tsx
This pull request introduces a minor enhancement to the `CanvasToolbarSaveToGalleryButton` component. The change adds a `colorScheme` property set to `"invokeBlue"` to improve the button's visual styling.
Is it blue? (da ba dee)
Send it on in.
=> Change save button to Invoke Blue

invokeai/frontend/web/src/common/components/Picker/Picker.tsx, invokeai/frontend/web/src/features/lora/components/LoRASelect.tsx, invokeai/frontend/web/src/features/parameters/components/ModelPicker.tsx
Enhance LoRA picker to default filter by current base model architecture
Fixes new LoRA picker to auto select the architecture filter for the current model group
N/A
Open LoRA menu with any model group selected. The right models should be filtered.
Merge when ready.
=> fix(ui): Fix LoRA picker to default to current base model architecture

invokeai/app/invocations/flux_text_encoder.py
Added tokenizer logging to flux in a similar way to how compel does it. 
Based upon the log_tokenization flag it will output a colourised info log containing the tokenization of the prompt for clip and T5
NA
turn on the logging and do some flux prompts.
NA
=> Update flux_text_encoder.py with log_tokenization in a similar way to how compel does it. 

invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityTransformer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasSegmentAnythingModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasBboxToolModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/util.ts
Initially the stage has a width, height and scale of 0. With the new layout system, the stage doesn't get dimensions until the canvas tab is clicked. It's possible we need to divide something by one of these 0 values, which results in NaNs, which could end up in the konva internals, causing warnings/errors.
Not sure how to address the root issue without only rendering canvas when you are on it, which adds some lag/stutters when clicking the canvas tab.
In the meantime, this change adds some safeguards to prevent NaNs from getting in there.
=> fix(ui): prevent NaN from getting into konva internals

invokeai/app/services/shared/graph.py, tests/test_node_graph.py, tests/test_nodes.py
A subtle python bug caused invalid edges to be created when handling collect nodes. Who knows what weirdness this was causing.
Fixed the root cause and added some tests for this case and some other iterate/collect test cases.
Fixes this issue - and possibly others related to collect nodes:
@JPPhoto raised on discord: https://discord.com/channels/1020123559063990373/1083864753543331981/1389069903205634142
Should fix JP's issue.
n/a
=> fix(app): prep of collect nodes can create invalid edges

invokeai/frontend/web/src/common/components/Picker/Picker.tsx, invokeai/frontend/web/src/features/lora/components/LoRASelect.tsx, invokeai/frontend/web/src/features/parameters/components/ModelPicker.tsx
LoRA is using the new model picker component with icons, but hides unnecessary filters that overcomplicate it. Related models are now called out.
Discussion re: related model component functionliaty
Open the LoRA model and ensure it is effectively working w/ the model base you have selected.
Merge is go.
=> fix(ui): Fix related models in new model picker.

invokeai/frontend/web/src/features/ui/layouts/TabWithLaunchpadIcon.tsx, invokeai/frontend/web/src/features/ui/layouts/canvas-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/generate-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/shared.ts, invokeai/frontend/web/src/features/ui/layouts/upscaling-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/workflows-tab-auto-layout.tsx
Updated to include a new Launchpad Icon tab, and remove progress from the Canvas Image Viewer.
The **discussions**.
Use your eyeballs to see if it looks good.
Merge when ready.
=> fix(ui): Updating styling to include Launchpad Icon & remove Canvas progress bar

invokeai/app/api/routers/session_queue.py
Previously we were returning "raw" errors from the internal application API to the API consumer. This could result in very very large stack traces.
Instead, just return HTTP errors with error messages.
=> fix(api): exception handling in session queue

invokeai/frontend/web/src/features/nodes/components/sidePanel/WorkflowViewEditToggleButton.tsx
Summary
Fix: The "use in linear view" button on the workflow tab now correctly switches to and focuses the Image Viewer panel.
Related Issues / Discussions
N/A
QA Instructions
1.  Navigate to the "Workflow" tab.
2.  Click the "Use in linear view" (eye icon) button in the side panel.
3.  Verify that the UI switches to the Image Viewer panel within the workflow tab.
Merge Plan
N/A
Checklist
=> fix(ui): button functionality in workflow tab

invokeai/frontend/web/src/features/gallery/components/ImageViewer/CurrentImageButtons.tsx
When a user clicks the "Edit" button from the Image Viewer, the "Brush" tool is now automatically selected on the canvas. This streamlines the workflow by immediately preparing the user for common editing tasks after sending an image to the canvas.
N/A
1.  Navigate to the Image Viewer.
2.  Select any image.
3.  Click the "Edit" button.
4.  Observe that the canvas panel is focused and the "Brush" tool is automatically selected in the canvas toolbar.
N/A
%23%23 Checklist
=> feat(ui):Automatically select brush tool on edit

invokeai/frontend/web/src/features/lora/components/LoRASelect.tsx
The fix replaces the incorrect `t('models.selectModelFirst')` with the correct and existing `t('models.selectModel')` in `invokeai/frontend/web/src/features/lora/components/LoRASelect.tsx`.
N/A
1.  Navigate to the LoRA/Concepts section in the UI.
2.  Ensure that no base model is currently selected.
3.  Verify that the LoRA select dropdown displays "Select a Model" (or its translated equivalent) as its placeholder text.
4.  Open the LoRA select dropdown and confirm that the "no options" text also displays "Select a Model" (or its translated equivalent).
5. Enjoy the fix. Luxuriate in the translation.
N/A
=> fix(ui): Fix translation reference in models picker

invokeai/frontend/web/src/services/api/endpoints/images.ts
Fixes an issue where the Gallery was not updating immediately after an image was uploaded or copied (e.g., from the Staging Area).
The `uploadImage` mutation's cache invalidation was incomplete, preventing the Gallery from reflecting new images without a manual refresh. This PR updates the `uploadImage` mutation to use a comprehensive set of cache invalidation tags, aligning it with other mutations that affect image collections and boards.
1.  Go to the Staging Area.
2.  Select an image.
3.  Click the "Save Selected to Gallery" button.
4.  Verify that the Gallery (left sidebar) updates immediately to show the newly saved image, without requiring a page refresh.
-   [x] _The PR has a short but descriptive title, suitable for a changelog_
-   [ ] _Tests added / updated (if applicable)_
- …
=> fix(ui): Fix save to gallery image update issue from staging area.

invokeai/backend/model_manager/load/model_loaders/flux.py
Replace T5Tokenizer with T5TokenizerFast in the Flux model loader class. 
This PR updates the Flux model loader class to use` T5TokenizerFast` instead of `T5Tokenizer`. This change is a minor performance improvement. The `T5TokenizerFast` is Rust-based, and the `T5Tokenizer` is Python-based. 
Additionally, the Fast version also adds `Offset mapping`, which can be used to locate positions of tokens within the prompt that was tokenized. I am creating a custom node that will leverage this to bring compel-like weighting of T5 embeddings to FLUX. 
Should be a "drop-in" replacement with little to no effect on generations. 
Test generations that use the T5Tokeniser as part of the generation.  Flux and SD3.
NA
=> Update flux.py - change T5Tokenizer to T5TokenizerFast

invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/StagingAreaItemsList.tsx, invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/context.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStagingAreaModule.ts, invokeai/frontend/web/src/services/events/setEventListeners.tsx
Fixes the waiting for image screen sticking around after a cancel.
N/A
Cancel an image
Merge the PR
=> fix(ui): Reset canvas session when queue item is canceled 

invokeai/frontend/web/src/features/controlLayers/hooks/useExportCanvasToPSD.ts
Fixes incorrect positioning of brush layers when exporting to PSD files. Previously, the export logic did not accurately account for the actual content bounds of brush strokes, leading to misaligned layers in the PSD.
This PR updates the PSD export process to:
1.  Obtain the precise pixel bounds of each layer's content (excluding transparent regions).
2.  Crop the canvas data to these accurate content bounds.
3.  Position the PSD layer using these corrected content bounds, ensuring brush strokes are accurately represented and aligned.
N/A
1.  Create a canvas with multiple layers, including at least one brush layer where strokes extend beyond the initial layer position.
2.  Export the canvas to a PSD file.
3.  Open the exported PSD file in Photoshop or a compatible editor.
4.  Verify that …
=> fix(ui): Fix brush layer positioning in PSD export

invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewerPanel.tsx
This PR reintroduces image comparison directly from the Image Viewer panel by dragging an image from the gallery onto the Image Viewer, which was lost to the sands of time in the Great Earthquake of '25.
Customer reports
1.  Select an image in the gallery.
2.  Open the Image Viewer panel.
3.  Drag a *different* image from the gallery onto the Image Viewer panel.
4.  Verify that the Image Viewer automatically switches to comparison mode, displaying both images side-by-side.
5.  Confirm that the "Select for compare" drop target overlay is only visible when an image is selected and no comparison image is currently active.
=> fix(ui): Re-implement image comparison on drag

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/setDefaultSettings.ts
Sets CFG Rescale Multiplier to 0 when the Set Model Defaults icon is clicked if the Model does not have a default value for CFG Rescale Multiplier. See issue https://github.com/invoke-ai/InvokeAI/issues/7584 for the "why".  
Also addresses a minor issue where if the default is enabled but set to 0, and the Reset Model Defaults is clicked, the value is not reset to 0. 
Both issues were fixed in the default settings middleware by checking for a null value in the same way it's checked in the UseDefaultSettingsButton logic, and by adding an else block to force the value to 0 if it is null.
Closes #7584
Disabled a models default CFG Rescale Multiplier and changed settings in the Canvas view including CFG Rescale Multiplier, then clicked on the Reset Defaults icon (PiSparkleFil) to verify the …
=> fix(ui): sets cfg_rescale_multiplier to 0 if there is no default. Also fixes issue with truthiness check causing 0 value to be missed.

invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/CanvasLaunchpadPanel.tsx, invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/GenerateLaunchpadPanel.tsx, invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/LaunchpadContainer.tsx, invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/UpscalingLaunchpadPanel.tsx, invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/WorkflowsLaunchpadPanel.tsx
- Center launchpad vertically instead of padding top
- Slightly decrease gap to make it small enough to not overflow
- Add container component so all launchpads have consistent layout
=> fix(ui): launchapd overflows on small screens

invokeai/frontend/web/src/features/parameters/components/Prompts/UpscalePrompts.tsx, invokeai/frontend/web/src/features/ui/components/ParametersPanels/ParametersPanelUpscale.tsx
Removes unused ref image box from the Upscale tab.
Discussion
Does it show up? Nope!
Merge at will
=> fix(ui): remove ref image from upscale

invokeai/frontend/web/src/features/ui/layouts/auto-layout-context.tsx, invokeai/frontend/web/src/features/ui/layouts/canvas-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/generate-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/models-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/navigation-api.test.ts, invokeai/frontend/web/src/features/ui/layouts/navigation-api.ts, invokeai/frontend/web/src/features/ui/layouts/queue-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/upscaling-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/use-navigation-api.tsx, invokeai/frontend/web/src/features/ui/layouts/workflows-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/store/uiSlice.ts, invokeai/frontend/web/src/features/ui/store/uiTypes.ts
Panel states persist (size and active status). Panels are per-tab. In other words, the boards panel on the Generate tab is a different entity than the boards panel on the Canvas tab, and their state is persisted separately.
=> feat(ui): panel state persistence

invokeai/frontend/web/src/features/controlLayers/components/RefImage/RefImageHeader.tsx, invokeai/frontend/web/src/features/controlLayers/components/RefImage/RefImageList.tsx, invokeai/frontend/web/src/features/controlLayers/components/RefImage/RefImagePreview.tsx, invokeai/frontend/web/src/features/controlLayers/components/RefImage/RefImageWarningTooltipContent.tsx
Adds a button to pull the BBox into a new ref image on the canvas tab.
User requests
Try bringing the bbox into a ref image. It should work, including when images have transparency.
Merge when ready.
=> feat(ui): Adds bbox to ref image button on Canvas

invokeai/frontend/web/src/features/ui/components/AppContent.tsx, invokeai/frontend/web/src/features/ui/layouts/canvas-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/generate-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/models-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/navigation-api.test.ts, invokeai/frontend/web/src/features/ui/layouts/navigation-api.ts, invokeai/frontend/web/src/features/ui/layouts/queue-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/upscaling-tab-auto-layout.tsx, invokeai/frontend/web/src/features/ui/layouts/workflows-tab-auto-layout.tsx
Make the tab loading screen logic more resilient to getting stuck by using a proper debounce implementation.
=> fix(ui): prevent getting stuck on tab loading screen

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/Settings/CanvasSettingsDefaultAutoSwitchSelect.tsx, invokeai/frontend/web/src/features/controlLayers/components/Settings/CanvasSettingsPopover.tsx, invokeai/frontend/web/src/features/controlLayers/components/SimpleSession/context.tsx, invokeai/frontend/web/src/features/controlLayers/store/canvasSettingsSlice.ts, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/ModelInstallQueue/ModelInstallQueue.tsx
User feedback suggests a preference for 'switch' behavior that persists. This adds a config to the canvas settings.
v6 Feedback - Discord
Set a new default. Generate, confirm that its persisted.
Change the value in the staging area. Confirm that the new setting persists until the staging area closes.
Confirm the default is used in a new session.
Merge when good.
=> feat(ui): Add default value option for canvas switch settings

invokeai/app/services/board_image_records/board_image_records_sqlite.py, invokeai/app/services/board_records/board_records_sqlite.py, invokeai/app/services/image_records/image_records_sqlite.py, invokeai/app/services/model_records/model_records_sql.py, invokeai/app/services/model_relationship_records/model_relationship_records_sqlite.py, invokeai/app/services/session_queue/session_queue_sqlite.py, invokeai/app/services/shared/sqlite/sqlite_database.py, invokeai/app/services/shared/sqlite_migrator/sqlite_migrator_impl.py, invokeai/app/services/style_preset_records/style_preset_records_sqlite.py, invokeai/app/services/workflow_records/workflow_records_sqlite.py, tests/test_sqlite_migrator.py
- Add a context manager to the SqliteDatabase class which abstracts away creating a transaction, committing it on success and rolling back on error.
- Use it everywhere. The context manager should be exited before returning results. No business logic changes should be present.
Hopefully this addresses the recent increase in DB-related errors (the cause of which is likely a race condition with DB operations).
These are the two errors we are addressing:
- `sqlite3.InterfaceError: bad parameter or other API misuse`:
```
[2025-07-10 08:38:01,544]::[InvokeAI]::ERROR --> Non-fatal error in session processor InterfaceError: bad parameter or other API misuse
[2025-07-10 08:38:01,544]::[InvokeAI]::ERROR --> Traceback (most recent call last):
File …
```
=> feat(app): db abstraction to prevent threading conflicts

invokeai/app/services/download/download_default.py
A partial fix for Invoke exhausting disk space, this PR to the DownloadQueueService causes it to refuse to download if the advertised file size is bigger than the available space.
I tried to put this at a higher level, in ModelInstallService._install_remote_model, but despite its _attempt_ to calculate the total_bytes of the install job at that time, in practice it doesn't have that information.
I say _partial_ fix because the model installer _copies_ the files from the temporary directory to the model directory, causing you to temporarily need _twice_ as much disk space—that can be a separate issue.
It is also short-sighted in that if given an install job involving multiple files, it may spend the time to fully download earlier files before realizing it cannot complete all of them.
- …
=> fix(Model Manager): refuse to download a file when there's insufficient space

invokeai/frontend/web/src/features/queue/store/readiness.ts
fix(ui): ignore disalbed ref images in readiness checks
https://discord.com/channels/1020123559063990373/1149506274971631688/1393542903732633661
n/a
n/a
=> fix(ui): ignore disalbed ref images in readiness checks

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
- Add require drop down for install method
- Make browser version optional
- Link to latest release
- Update verbiage for sys info section
We have an increasing number of bug reports of issues that appear only on Stability Matrix installs. The options for install method are:
- "Invoke's Launcher"
- 'Stability Matrix'
- 'Pinokio'
- 'Manual'
Hopefully this lets us filter things out and reduce support load.
n/a
n/a
=> gh: update bug report template

docker/Dockerfile
Frontend was updated to use pnpm v10.x as package manager, but the Dockerfile was left at 8.x. This PR fixes the issue.
Merge at will
=> fix(docker): switch to pnpm10.x

invokeai/frontend/web/src/common/hooks/useImageUploadButton.tsx, invokeai/frontend/web/src/features/dnd/FullscreenDropzone.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/Fields/ModelImageUpload.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/WorkflowThumbnail/WorkflowThumbnailField.tsx, invokeai/frontend/web/src/features/stylePresets/components/StylePresetForm/StylePresetImageField.tsx
fix(ui): uppercase file extensions blocked for image upload
Closes #8284
Upload an image with uppercase extension by dragging from file explorer into browser.
n/a
=> fix(ui): uppercase file extensions blocked for image upload

invokeai/frontend/web/src/features/prompt/PromptTriggerSelect.tsx
```
Adds related model support to embeddings. Also reorders the prompt trigger popover menu to display LoRA trigger phrases before compatible embeddings. 
Missing embedding related models.
1.  Open the prompt trigger popover menu (e.g., by typing `/` in the prompt input field).
2.  Verify that "LoRA Trigger Phrases" are listed before "Compatible Embeddings".
3. Verify related embeddings are styled correctly.
merge when good.
```
=> fix(ui): Adds related model support to embeddings

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbar.tsx, invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbarFitBboxToMasksButton.tsx, invokeai/frontend/web/src/features/controlLayers/hooks/useAutoFitBBoxToMasks.ts, invokeai/frontend/web/src/features/system/components/HotkeysModal/useHotkeyData.ts
Adjusts the bbox to the current inpaint masks
N/A
Shift+B with a simple mask - BBox should resize w/ padding based on compositing settings.
Merge when you think it's ready
=> feat(ui): Adjust BBox to Inpaint Mask

invokeai/frontend/web/src/app/store/store.ts
We intermittently get an error like this:
```
TypeError: Cannot read properties of undefined (reading 'length')
```
This error is caused by a `redux-undo`-enhanced slice being rehydrated without the extra stuff it adds to the slice to make it undoable (e.g. an array of `past` states, the `present` state, array of `future` states, and some other metadata).
`redux-undo` may need to check the length of the past/future arrays as part of its internal functionality. These keys don't exist so we get the error. I'm not sure _why_ they don't exist - my understanding of `redux-undo` is that it should be checking and wrapping the state w/ the history stuff automatically. Seems to be related to `redux-remember` - may be a race condition.
The solution is to ensure we wrap rehydrated state for undoable …
=> fix(ui): return wrapped history in redux-remember unserialize

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/gallery/components/NewGallery.tsx, invokeai/frontend/web/src/features/system/components/HotkeysModal/useHotkeyData.ts
This adds a gallery hotkey for star/unstar image (using the `.` key). It also includes some minor fixes for other translation strings for other hotkeys that were missing definition in the translation file.
Discord
Select image. Press . - See it star. See it unstar.
Merge at will.
=> feat(ui): Add Star/Unstar Hotkey and fix hotkey translations

invokeai/frontend/web/src/features/controlLayers/components/CanvasEntityList/CanvasEntityGroupList.tsx
Moves the export button to the start of the list, so that it doesn't conflict with UX expectations around the positioning of standard actions like "hide layers)
User feedback 
- Hope it all still works.
- Merge at will.
=> fix(ui): Reposition export button

invokeai/frontend/web/src/features/controlLayers/konva/CanvasStageModule.ts
Fix an issue where when scrolling very slowly, the zoom direction could be incorrect.
https://discord.com/channels/1020123559063990373/1149506274971631688/1397221843072585829
Scroll very slowly with a mouse wheel. Shouldn't invert the zoom direction.
n/a
=> fix(ui): incorrect zoom direction on fine scroll

invokeai/frontend/web/src/features/nodes/hooks/useAutoLayout.ts
The `useAutoLayout` hook was re-rendering on every nodes/edges state change, including position changes, adding lag to the app.
n/a
Minor perf boost, you may or may not notice it.
n/a
=> perf(ui): imperatively get nodes and edges in autolayout hook

invokeai/frontend/web/src/features/nodes/util/graph/generation/buildChatGPT4oGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildFluxKontextGraph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildImagen3Graph.ts, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildImagen4Graph.ts
Metadata was being populated in the metadata node, but not connected to the image-outputting nodes, resulting in no metadata being saved to the image.
n/a
n/a
n/a
=> fix(ui): connect metadata to output node for ext api nodes

invokeai/frontend/web/src/features/queue/components/QueueCountBadge.tsx
When the left panel is collapsed, the queue count badge didn't detect that it should be hidden.
The logic for showing and hiding this badge is rather unpleasant, thanks to CSS padding and absolute positioning rules. We have to render it in a portal and dynamically calculate its position to have it float over the queue actions menu button 😵‍💫 . This includes logic to determine if the queue actions menu button is visible, which broke with the change to `dockview` for layouts.
n/a
n/a
n/a
=> fix(ui): queue count badge renders when left panel collapsed

invokeai/frontend/web/src/features/gallery/components/ImageViewer/context.tsx
Fix an issue where, when gallery auto-switch to new images is disabled, the viewer doesn't hide the final progress image when a generation completes.
https://discord.com/channels/1020123559063990373/1149506274971631688/1399574352940241088
n/a
n/a
=> fix(ui): progress image does not hide on viewer with autoswitch disabled

invokeai/app/services/model_install/model_install_default.py
Previously, we used pathlib's `with_suffix()` method to change add a suffix (e.g. ".safetensors") to a model when installing it.
The intention is to add a suffix to the model's name - but that method actually replaces everything after the first period.
This can cause different models to be installed under the same name!
For example, the FLUX models all end up with the same name:
- "FLUX.1 schnell.safetensors" -> "FLUX.safetensors"
- "FLUX.1 dev.safetensors" -> "FLUX.safetensors"
The fix is easy - append the suffix using string formatting instead of using pathlib.
This issue has existed for a long time, but was exacerbated in 075345bffd51704b217bdd41968812b523382610 in which I updated the names of our starter models, adding ".1" to the FLUX model names. Whoops!
- Closes #8276
- Closes …
=> fix(app): handle model files with periods in their name

invokeai/app/services/model_install/model_install_default.py, tests/app/services/model_install/test_model_install.py
It's not clear why we were copying downloaded models to the destination dir instead of moving them. I cannot find a reason for it, and I am able to install single-file and diffusers models just fine with the change.
This fixes an issue where model installation requires 2x the model's size (bc we were copying the model over).
CC @keturn who noticed this in #8268
Install a diffusers and single-file model. Should work and generation should succeed afterwards.
n/a
=> fix(app): move (not copy) models from install tmpdir to destination

invokeai/app/invocations/flux_denoise.py, invokeai/backend/flux/extensions/kontext_extension.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/nodes/util/graph/generation/buildFLUXGraph.ts, invokeai/frontend/web/src/features/queue/store/readiness.ts, invokeai/frontend/web/src/services/api/schema.ts
Support multiple ref images for FLUX Kontext (local model only). Images are concatenated in latent space. 
- FLUX Kontext extension updated to handle list of Kontext cond fields
- FLUX Denoise node updated (backwards-compatible change), version bumped
- Studio readiness checks updated to allow multiple ref images for _local_ Kontext
- BFL API still only supports a single image. For BFL API, we could do image-space concatenation I suppose - but it's a bit hairy when the image sizes are different. I think it's safest to just say multiple ref images for BFL API Kontext is not supported. The Invoke button tooltip warning message is updated to refer to BFL API specifically.
(I used the first images in my gallery, clearly not particularly high quality inputs! but it still works)
plus
"place the …
=> feat: support multiple ref images for flux kontext

invokeai/frontend/web/src/features/gallery/components/ImageViewer/CompareToolbar.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageComparison.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageComparisonHover.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageComparisonSlider.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewer.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewerPanel.tsx, invokeai/frontend/web/src/features/gallery/components/ImageViewer/common.ts
- Do not show both viewer and compare toolbars when in compare mode
- Update image viewer UI so toolbar styling matches viewer
- Prevent flash of images at wrong size when entering compare mode
<video src="https://github.com/user-attachments/assets/369b942a-a029-436a-a939-f32e8050d554"></video>
Raised on discord https://discord.com/channels/1020123559063990373/1149506274971631688/1399755456473202729
Should work as it did before.
n/a
=> feat(ui): zhoosh image comparison ui

invokeai/frontend/web/src/features/gallery/components/NewGallery.tsx
This fixes an issue where gallery's auto-scroll-into-view for selected images didn't work, and users instead saw a "Unable to find image..." debug log message in JS console.
n/a
n/a
n/a
=> fix(ui): add image name data attr to gallery placeholder image elements

invokeai/frontend/web/src/features/nodes/util/graph/generation/buildFluxKontextGraph.ts, invokeai/frontend/web/src/features/queue/store/readiness.ts
Update graph building for Flux Kontext API to allow multiple reference images with the support of image concatenation node
=> multi-ref image support for flux kontext API

invokeai/frontend/web/src/features/gallery/components/ImageContextMenu/ImageMenuItemNewCanvasFromImageSubMenu.tsx, invokeai/frontend/web/src/features/gallery/hooks/useEditImage.ts, invokeai/frontend/web/src/features/ui/layouts/LaunchpadAddStyleReference.tsx, invokeai/frontend/web/src/features/ui/layouts/LaunchpadEditImageButton.tsx, invokeai/frontend/web/src/features/ui/layouts/LaunchpadGenerateFromTextButton.tsx, invokeai/frontend/web/src/features/ui/layouts/LaunchpadUseALayoutImageButton.tsx
Disable these items while staging:
- New Canvas From Image context menu
- Edit image hook & launchpad button
- Generate from Text launchpad button (only while on canvas tab)
- Use a Layout Image launchpad button
Also fixed a bug w/ style ref launchpad button (unlikely to have caused problems for folks)
Stretch on discord: https://discord.com/channels/1020123559063990373/1149506274971631688/1401991424240652409
n/a
n/a
=> feat(ui): prevent creating new canvas when staging

invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardEditableTitle.tsx, invokeai/frontend/web/src/features/gallery/components/Boards/BoardsList/BoardTooltip.tsx, invokeai/frontend/web/src/features/gallery/components/Gallery.tsx
Fix overflow for long board names
Before:
After:
n/a
n/a
n/a
=> fix(ui): overflow w/ long board names

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbarFitBboxToLayersButton.tsx, invokeai/frontend/web/src/features/system/components/HotkeysModal/useHotkeyData.ts
This PR adds a new hotkey, `Shift+N`, for the "Fit Bbox to Layers" action. It also resets the canvas view to the newly fit layers.
This provides an ergonomic and consistent hotkey, aligning with existing canvas hotkeys like `Shift+C` (Reset Inpaint Mask), `Shift+V` (Invert Mask), and `Shift+B` (Fit BBox to Masks). 
N/A
1.  Open the canvas.
2.  Select an image or create a bounding box.
3.  Resize the BBox and move the canvas view away from the bounding box.
4.  Press `Shift+N` to confirm the bounding box is fit to layers and is centered in the staging area
5.  Open the Hotkeys Modal (`?` hotkey) and verify "Fit Bbox to Canvas" lists both `Mod+Shift+0` and `Shift+S`.
N/A
-   [x] _The PR has a short but descriptive title, suitable for a changelog_
-   [ ] _Tests added / updated (if …
=> Add reset bbox to canvas hotkey

invokeai/frontend/web/src/features/controlLayers/components/RefImage/RefImageImage.tsx, invokeai/frontend/web/src/features/controlLayers/store/canvasSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/paramsSlice.ts, invokeai/frontend/web/src/features/dnd/DndImageIcon.tsx
This is useful for FLUX Kontext, where you typically want the generation size to at least roughly match the first ref image size.
<video src="https://github.com/user-attachments/assets/06d13abd-1447-476a-9f02-bc140f2d93e5"></video>
Should only change the size for the tab you are on. For example, if you are on the generate tab, it should not change the Canvas Bbox and vice-versa. Button should be disabled while staging.
n/a
=> feat(ui): add button to ref image to recall size & optimize for model

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputFieldAddToFormRoot.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/use-add-node-field-to-root.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/workflow/publish.ts, invokeai/frontend/web/src/features/nodes/store/selectors.ts
A bug fix was implemented to avoid adding the same field to the form in the workflow editor.
- A new selector builder, `buildSelectWorkflowFormNodeExists`, was added to `selectors.ts`, which builds new node specific selectors to be able to decide if the node has already been added to the form.
- A new field, `isAddedToRoot`, is returned by `useAddNodeFieldToRoot` hook, which can be used to decide if the node has already been added to the form.
- `InputFieldAddToFormRoot` is disabled when the node has already been added to the form.
Closes #8400
=> fix(ui): same field cannot be added to form multiple times in workflow editor

.github/workflows/lfs-checks.yml
ci: add workflow to catch incorrect usage of git-lfs
#8433 inadvertently committed a non-LFS-tracked file to an LFS-tracked dir, causing a string of issues. #8446 fixed that file. This PR should prevent the issue from occurring again, catching the issue in CI.
n/a
Needs to be added to required workflows in repo settings
=> ci: add workflow to catch incorrect usage of git-lfs

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/common/util/randomFloat.ts, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/FloatField/FloatFieldInput.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/FloatField/FloatFieldInputAndSlider.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/FloatField/FloatFieldSlider.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/FloatField/useFloatField.ts, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/IntegerField/IntegerFieldInput.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/IntegerField/IntegerFieldInputAndSlider.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/IntegerField/IntegerFieldSlider.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/IntegerField/useIntegerField.ts, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementFloatSettings.tsx, invokeai/frontend/web/src/features/nodes/components/sidePanel/builder/NodeFieldElementIntegerSettings.tsx, invokeai/frontend/web/src/features/nodes/types/workflow.ts
A new feature was implemented to shuffle any number field in the workflow editor.
- `showShuffle` was added to the schemas of both integer and floating point field settings in `workflow.ts`
- a new utility function, `randomFloat`, was created in `randomFloat.ts` to be able to generate random floating point numbers
- `useIntegerField` and `useFloatField` were extended to generate a new random value and dispatch the changed value when the `Shuffle` button is clicked
- `Show Shuffle` toggle was added to `NodeFieldElementIntegerSettings` and `NodeFieldElementFloatSettings`
- `IntegerFieldInput`, `IntegerFieldSlider`, `IntegerFieldInputAndSlider`, `FloatFieldInput`, `FloatFieldSlider`, `FloatFieldInputAndSlider` were extended with the `Shuffle` button
- new tanslations, `showShuffle` and …
=> feat(ui): shuffle  button on workflows

invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/FloatField/useFloatField.ts, invokeai/frontend/web/src/features/nodes/util/constrainNumber.ts
Determine the "base" step for floats. If no `multipleOf` is provided, the "base" step is `undefined`, meaning the float can have any number of decimal places.
The UI library does its own step constrains though and is rounding to 3 decimal places. Probably need to update the logic in the UI library to have truly arbitrary precision for float fields.
In #8450 a bug was fixed, the `constrainValue` prop wasn't added on float fields when it should have been. Adding it added more constraints to the fields, altering their precision. 
float fields should behave like they did before #8450 now
n/a
=> fix(ui): float input precision

invokeai/frontend/web/public/locales/en.json
missing translation
https://discord.com/channels/1020123559063990373/1054129386447716433/1408100689107882004
n/a
n/a
=> fix(ui): toggle bbox visiblity translation

invokeai/frontend/web/src/features/changeBoardModal/components/ChangeBoardModal.tsx
A new feature was implemented to alphabetically order boards in the `Change Board` dialog
- order of `boards` was changed to sort them alphabetically in `ChangeBoardModal`
Closes [#1234" format, so that the issue will be automatically closed when the PR merges.-->](https://github.com/invoke-ai/InvokeAI/issues/8341)
=> feat(ui): change board - sorting order of boards alphabetical

invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasModuleBase.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasObject/CanvasObjectImage.ts
- Do not attempt to cache nodes without width or height. Prevents a console error from being logged by Konva. This particular error wasn't ever _raised_ - just logged. So this only reduces some noise.
- Log at error level when an image fails to load. Previously, this log was accidentally done without specifying a log level, which apparently results in no logs at all.
- Include the specific error when an image fails to load. Previously, only a message "unable to load image" was logged.
n/a
n/a
n/a
=> fix(ui): konva logging

invokeai/frontend/web/src/features/controlLayers/konva/CanvasEntity/CanvasEntityObjectRenderer.ts
A change in #8493 intended to prevent konva from caching nodes that have no content (preventing errors about caching a node with 0 width or height) inadvertently is breaking the Control Layer transparency effect. There appears to be a bug (?) where konva doesn't reliably calculate the size of object groups which means my fix doesn't reliably do what it was intended to do.
Reported on discord
n/a
n/a
=> fix(ui): control layer transparency effect not working

invokeai/frontend/web/src/features/controlLayers/konva/CanvasStagingAreaModule.ts
Fix an issue introduced in #8489 where progress images would show up tiny.
n/a
n/a
n/a
=> fix(ui): progress image renders at physical size

invokeai/app/services/board_image_records/board_image_records_sqlite.py
```sh
| sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 2, and there are 36 supplied.
```
https://discord.com/channels/1020123559063990373/1149506274971631688/1410657037549043864
n/a
n/a
=> fix(app): board count queries not getting categories as params

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/queue/store/readiness.ts
If incompatible LoRAs are added, prevent Invoking.
The logic to prevent adding incompatible LoRAs to graphs already existed. This does not fix any generation bugs; just a visual inconsistency where it looks like Invoke would use an incompatible LoRA.
---
I also slightly refactored how the readiness check args are passed in to use a single object. Much harder to accidentally pass the wrong thing in this way.
https://discord.com/channels/1020123559063990373/1149506274971631688/1410666884306571396
n/a
n/a
=> feat(ui): add readiness checks for LoRAs

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolFillColorPicker.tsx, invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbar.tsx, invokeai/frontend/web/src/features/controlLayers/konva/CanvasStateApiModule.ts, invokeai/frontend/web/src/features/controlLayers/konva/CanvasTool/CanvasColorPickerToolModule.ts, invokeai/frontend/web/src/features/controlLayers/store/canvasSettingsSlice.ts, invokeai/frontend/web/src/features/controlLayers/store/types.ts, invokeai/frontend/web/src/features/system/components/HotkeysModal/useHotkeyData.ts
A new feature was implemented to switch foreground/background colors
- a new hotkey, `toggleFillColor`, was added to toggle fill color by `x`
- new fields, `activeColor`, `color1` and `color2`, were added to `canvasSettingsSlice` to manage fill color
- `ToolFillColorPicker` component was refactored to handle foreground/background colors
- new tanslations, `hotkeys.canvas.setFillToWhite`, `fillColor1` and `fillColor2`, were added to en.json
Closes #8381
=> feat(ui): switchable foreground/background colors

invokeai/app/services/model_records/model_records_base.py, invokeai/backend/model_manager/config.py, invokeai/backend/model_manager/legacy_probe.py, invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/app/types/invokeai.ts, invokeai/frontend/web/src/features/controlLayers/store/lorasSlice.ts, invokeai/frontend/web/src/features/lora/components/LoRACard.tsx, invokeai/frontend/web/src/features/modelManagerV2/hooks/useLoRAModelDefaultSettings.ts, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/LoRAModelDefaultSettings/DefaultWeight.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/LoRAModelDefaultSettings/LoRAModelDefaultSettings.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelView.tsx, invokeai/frontend/web/src/features/system/store/configSlice.ts, invokeai/frontend/web/src/services/api/schema.ts
A new feature was implemented to specify LoRA default weight per model
- `LoraModelDefaultSettings` was created in `config.py` to represent LoRA related default settings
- a new instance variable, `default_settings`, was added to `LoRAConfigBase` to persist LoRA related default settings in every kind of LoRA model instance
- a new function, `get_default_settings_lora`, was added to `legacy_probe.py` to populate default settings extracted from models
- `LoraModelDefaultSettings` was added as another option to `ModelRecordChanges.default_settings` in order to persist LoRA related default settings
- API model re-generated into `schema.ts` to make latest changes in backend API available in the frontend
- a new field, `lora.weight`, was added to the `zAppConfig` schema to store LoRA weight UI …
=> feat(ui): LoRA default weight

invokeai/frontend/web/src/app/store/middleware/listenerMiddleware/listeners/boardIdSelected.ts, invokeai/frontend/web/src/features/deleteImageModal/store/state.ts, invokeai/frontend/web/src/features/gallery/components/ImageViewer/ImageViewerPanel.tsx
- [fix(ui): clear gallery selection when last image on selected board is deleted](https://github.com/invoke-ai/InvokeAI/commit/f26590b44bba8228416a84ccff68a86fadc7f1d7)
- [fix(ui): clear gallery selection when switching boards and there are no items in the new board](https://github.com/invoke-ai/InvokeAI/commit/56c0ef01b0e5bbb514be02afa5a4167485b5e1ba)
- [fix(ui): show fallback when no image is selected](https://github.com/invoke-ai/InvokeAI/commit/778b5fb5c54807935f56cf9f9baf2bad2ace4c6f)
Reported on discord: https://discord.com/channels/1020123559063990373/1149506274971631688/1412820856169693297
- Create a board and add a single image to it
- Delete the image - the image should disappear from viewer, and viewer should show the fallback
- Switch to a different board - the viewer should …
=> fix(ui): gallery selection issues

invokeai/frontend/web/src/features/controlLayers/konva/CanvasStageModule.ts
This has been an issue for a long time. I suspect it wasn't noticed until now because it's finicky to trigger - you have to click and release very quickly, without moving the mouse at all.
n/a
n/a
n/a
=> fix(ui): stop dragging when user clicks mmb once

invokeai/frontend/web/src/features/nodes/util/graph/generation/buildGemini2_5Graph.ts
Metadata node was in the graph but not connected to the Gemini node, so it didn't get saved with the image.
n/a
n/a
n/a
=> fix(ui): route metadata to gemini node

invokeai/frontend/web/src/features/controlLayers/store/lorasSlice.ts, invokeai/frontend/web/src/features/lora/components/LoRACard.tsx, invokeai/frontend/web/src/features/modelManagerV2/hooks/useLoRAModelDefaultSettings.ts, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/LoRAModelDefaultSettings/DefaultWeight.tsx, invokeai/frontend/web/src/features/system/store/configSlice.ts
A new bugfix was implemented to restore LoRA weight number input min/max limits
- `DEFAULT_LORA_WEIGHT_CONFIG` values, `numberInputMin` and `numberInputMax`, were restored
Closes #8532
=> fix(ui): LoRA number input min/max restored

invokeai/frontend/web/src/features/controlLayers/components/CanvasEntityList/EntityListSelectedEntityActionBarFill.tsx, invokeai/frontend/web/src/features/controlLayers/components/CanvasEntityList/EntityListSelectedEntityActionBarOpacity.tsx, invokeai/frontend/web/src/features/controlLayers/components/Settings/CanvasSettingsPopover.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolFillColorPicker.tsx, invokeai/frontend/web/src/features/controlLayers/components/Tool/ToolWidthPicker.tsx, invokeai/frontend/web/src/features/controlLayers/components/Toolbar/CanvasToolbarScale.tsx, invokeai/frontend/web/src/features/nodes/components/flow/nodes/Invocation/fields/InputFieldDescriptionPopover.tsx, invokeai/frontend/web/src/features/nodes/components/flow/panels/BottomLeftPanel/AutoLayoutPopover.tsx, invokeai/frontend/web/src/features/parameters/components/PostProcessing/PostProcessingPopover.tsx, invokeai/frontend/web/src/features/prompt/PromptPopover.tsx, invokeai/frontend/web/src/features/ui/components/Notifications.tsx
fix(ui): render popovers in portals to ensure they are on top of other ui elements
reported on discord: https://discord.com/channels/1020123559063990373/1020123559831539744/1416527738302631986
n/a
n/a
=> fix(ui): render popovers in portals to ensure they are on top of other ui elements

invokeai/frontend/web/src/features/controlLayers/store/paramsSlice.ts
Fix an issue where prompt history wasn't deduped
n/a
n/a
n/a
=> fix(ui): dedupe prompt history

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/controlLayers/store/paramsSlice.ts, invokeai/frontend/web/src/features/parameters/components/Core/ParamPositivePrompt.tsx, invokeai/frontend/web/src/features/parameters/components/Core/PositivePromptHistory.tsx, invokeai/frontend/web/src/features/system/components/HotkeysModal/useHotkeyData.ts
Adds Alt+up/down when text area is selected as a shortcut to traverse prompt history. Ensures duplicate prompts are treated correctly in chronological history.
N/A
Test it! It works!
Merge at will.
=> Prompt history shortcuts

invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPane.tsx, invokeai/frontend/web/src/features/modelManagerV2/subpanels/ModelPanel/ModelView.tsx
Fixes an issue in Model Manager that didn't allow vertical scroll when contents overflowed `ModelPane`.
Discussed briefly in Discord
=> fix(ui): allow scrolling in ModelPane

invokeai/frontend/web/public/locales/en.json, invokeai/frontend/web/src/features/modelManagerV2/subpanels/AddModelPanel/ScanFolder/ScanFolderResults.tsx
- Non-in-place install _moves_ the model files into the Invoke directory. The old verbiage said it copied. Fixed.
- Added tooltip to the in-place checkbox on the Scan Folder tab. There was no description of the checkbox on that tab.
Reported on discord https://discord.com/channels/1020123559063990373/1020123559831539744/1419505547035541616
n/a
n/a
=> fix(ui): correct the in-place install verbiage, add tooltip

docs/nodes/communityNodes.md
Adds two new community nodes to the documentation:
1. **BiRefNet Background Removal** - High-quality background removal using BiRefNet with multiple model variants
2. **Image Export** - Export images in multiple formats (AVIF, JPEG, PNG, TIFF, WebP) with compression and quality controls
Nodes are published at:
- https://github.com/veeliks/invoke_birefnet
- https://github.com/veeliks/invoke_image_export
Changes include:
- Added entries to the community nodes list in alphabetical order
- Included before/after example images for BiRefNet
- Included node screenshots for Image Export
- Updated table of contents
=> docs: add BiRefNet and Image Export to communityNodes.md
